### ISSUE TITLE
Makefile: wrong git id when there are several similar submodules

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#1000]
This makefile line gives the wrong result if there are several submodules matching the same directory name.  In my case, they were `simh` and `simh2`, and GIT_COMMIT_ID contained two hashes.

`GIT_COMMIT_ID=$(shell cd .. ; git submodule status | grep "$(notdir $(realpath .))" | awk '{ print $$1 }')`

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

Found in git commit 6a131ec59af671b6a9e5b3861868afc86a5fb54f.  The line is identical in the latest commit 9f064db5613026c3badf1bfa94d92f850453ecf0.

**Comment by markpizz** [comment]
This fails due to the grep matching more than one submodule, right?  

Please suggest an alternative expression that doesn't have this problem.

**Comment by larsbrinkhoff** [comment]
Yes.

My suggestion would be something like `grep " $(notdir $(realpath .)) "`, i.e. include spaces around the path.  I can test this and report back.

**Comment by larsbrinkhoff** [comment]
On second thought the regexp could be made even tighter.  Here's some sample output from `git submodule status` in the ITS repository:

```
$ git submodule status
 8234fec179bdb0c171b17f2b5adc2b271c50423f dasm (remotes/ats/pdf-94-g8234fec)
 47c628c0f78c82ff847a7e051c04ef2ba7fbf3ef itstar (heads/master)
 bde5dcdc27d45bd69c69ac567beaf8b1674534e8 klh10 (klh10-2.0j-Rhialto-64-gbde5dcd)
 7a04cfb5477c24377032ac342e392e8845050244 mldev (heads/master)
 e000f5b5a7409f47932c6d81bccfd0fd57598017 pdp6 (heads/master)
 9f064db5613026c3badf1bfa94d92f850453ecf0 sim-h (v4.0-devel-3897-g9f064db)
+6a131ec59af671b6a9e5b3861868afc86a5fb54f simh (v4.0-devel-3210-g6a131ec)
-37c54370594dede213e1796d035239faca74c1b2 simlac
 e4c55443d6cbceaf9fa289d9cba87f56519694d7 sims (heads/ITS)
 18d508089d59407f61887a7450577a1967d8cca1 supdup (remotes/simon/master)
 56d22663af651f22c2810e5cb1d80a3911e316f1 tapeutils (heads/master)
 de8ac330a1d47f8eee05ed733602f4909f2d1484 tek4010 (v1.5-19-gde8ac33)
 0af734cd1a27a9d7f19649c212ca355addf1b791 tv11 (remotes/origin/lars/sleep-2-g0af734c)
 d9afd64ed22ffbde9dee020f9b6deae9ff9b3bf0 vt05 (heads/master)
```

So we could grep for `^.........................................

**Comment by larsbrinkhoff** [comment]
Before:

```
*** git commit id is e1db7dec41098cc7e22d2b379a26a7c4561dfa14 9f064db5613026c3badf1bfa94d92f850453ecf0.
*** git commit time is 2021-01-18T20:43:56+01:00.
```

After adding spaces:

```
*** git commit id is e1db7dec41098cc7e22d2b379a26a7c4561dfa14.
*** git commit time is 2018-09-11T05:59:14-07:00.
```

The regexp could be made even more safe by making it `"^......................................... $(notdir ...) "`, but it's a bit unwieldy.  (There are 41 periods and then spaces around the path.)

**Comment by larsbrinkhoff** [comment]
The updated makefile line is this:

```
        GIT_COMMIT_ID=$(shell cd .. ; git submodule status | grep " $(notdir $(realpath .)) " | awk '{ print $$1 }')
```

**Comment by markpizz** [comment]
I believe that this problem is fixed with your suggested change, right?  Please close the issue.

**Comment by larsbrinkhoff** [comment]
Thanks!
