### ISSUE TITLE
display: Typing on keyboard frobs switches.

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#1001]
When using the PDP11 simulator in its GT40 configuration, typing on the keyboard changes the contents of the SR switch register.  This is especially apparent when running MIT's Datapoint emulator software, because one of the switches toggles between italic and normal text.

Originally the simulator only used the keyboard to operate the switches.  When keyboard support was added, the original function remained effective in parallel with the new typing support.

**Comment by markpizz** [comment]
What do you propose?

**Comment by larsbrinkhoff** [comment]
Maybe a user-configurable option.  SET VT SWITCHES=something.  "Something" could include "OFF" for starters.

The display library grabs the keys FDASG';KLVCZXB.,NM/ and Enter for togging switches.  They are arranged as four sets of five for playing PDP-6 Spacewar.  Maybe the F-keys could be used instead, although they are not enough to cover the full PDP-6 Spacewar inputs.  The GT40 Datapoint emulator only uses a few switches, so say F1-F3 would be enough.  Similarly the Imlac emulator also hooks into the switches and software will typically use a few.

@philbudne, thoughts?

**Comment by philbudne** [comment]
I think it's (past?) time to move the processing of keystrokes in an
XY display window (and cpu_[gs]et_switches) up and out of display.c
(by registering a key event callback) and into individual SIMH display
device simulations (or maybe CPU specific .c files, if there might be
a case where a single CPU has multiple display hardware simulations,
and it's desirable to have the same key/switch mappings for both/all
displays).

I can't say whether that should be something as simple as a single
callback for all keystrokes, or something more complex (up/down events
for single keycodes).

Instead of "SET VT SWITCHES=something", I think
"SET VT KEYBOARD=something" is clearer (especially when the keyboard needs to
be used as a QWERTY keyboard that was part of a particular bit of
display hardware).

**Comment by markpizz** [comment]
> I think it's (past?) time to move the processing of keystrokes in an
XY display window (and cpu_[gs]et_switches) up and out of display.c
(by registering a key event callback) and into individual SIMH display
device simulations (or maybe CPU specific .c files.

There already is a registration process for keyboard traffic, AND if the registered keyboard routine has processed a particular key (and it therefore shouldn't be interpreted as Spacewar switch settings), then the keyboard routine should return a non-zero value.  I've no specific idea how to setup the GT40 configuration, and therefore which PDP11 simh DEVICE that handles the keyboard traffic you're referring to, but the only code in the PDP11 directory that sets the keyboard action routine (vid_display_kb_event_process) is pdp11_daz.c, but that routine always returns 0, so all keyboard activities will always mess with the Spacewar CPU register.  Separate from that, the tt2500 use of the keyboard event handler (in tt2500_key.c) also always returns 0.  Maybe the is desirable, but if not, then that code should be changed.  Separate from this, maybe a 
SET VT|KEY KEYBOARD=NOSPACEWAR 
should be added to these DEVICEs and that setting should influence the behavior of the keyboard event handlers.

> if there might be a case where a single CPU has multiple display hardware simulations,
and it's desirable to have the same key/switch mappings for both/all
displays).

Lars has added support for multiple video windows using sim_video directly, but there no current support for more than one active DEVICE which uses the display functionality concurrently.

**Comment by larsbrinkhoff** [comment]
Thanks for the input.  The GT40 keyboard is handled by the TTI device in pdp11_stddev.c, by looking at `display_last_char`.  I can submit a pull request to change this to the newer `vid_display_kb_event_process` mechanism.

**Comment by markpizz** [comment]
Hmm... I forgot about the ```display_last_char``` mechanism.  I'm thinking that things will get a little messy trying to provide that with ```vid_display_kb_event_process``` when all you're trying to do is get the ```display_last_char``` behavior WITH(or WITHOUT) the spacewar register update side effects.  Lets see what you come up with.  

I think a better approach is to keep changes in pdp11_vt.c and let SET VT SPACEWAR=OFF|ON control a local flag which then changes what actually happens in ```cpu_set_switches``` and ```cpu_get_switches```.

**Comment by larsbrinkhoff** [comment]
Sure, I can code up a solution like that.

I believe the display_last_char thing was expressly for the GT40 and PDP10 STK device, and that it's not used for anything else.  This could be an opportunity to move over to vid_display_kb_event_process and remove display_last_char.

The commit https://github.com/simh/simh/commit/362eb4afaf35eed2d20659e1ac2154736dc34f43 added display_last_char.

**Comment by markpizz** [comment]
I understand that was the specific original goal.  Meanwhile, part of the intention was to not mingle/cross visibility to various things where they don't belong or otherwise need visibility.

You happen to have encountered the problem that started this issue in the particular use case of the GT40 as a terminal.  It would be hard to imagine that every other place where the display APIs are used actually are only used when playing spacewar.

**Comment by philbudne** [comment]
Mark Pizzolato wrote:
> It would be hard to imagine that every other place where the display APIs are used actually are only used when playing spacewar.

It might very well turn out that back in the day that any hardware
that _could_ be used to play spacewar, at some point _was_ used to
play spacewar.

BUT I think that that's no justification to keep mappings of key codes
to "switch register" bit patterns designed to make it remotely
possible to play specific versions of PDP-1 and PDP-6/10 spacewar in
display.c (the display_key{up,down} routines).

It seemed to me it's time to consider moving keycode to register bit
mappings and/or actions to specific simulator directories, and to
allow different sets of mappings based on "SET <display device>"

The current mapping has/had two purposes:

general frobbing of a switch register for "display hacks"
  Was chosen with 18 bits in mind, and extended to 36.
  Unlikely to be "obvious" for 24 or 32 bit machines!
  Only makes sense for a QWERTY keyboard

Playing spacewar.  I copied the key mappings from a JavaScript
  PDP-1 simulator done at the MIT Media lab.

The cpu_[gs]et_cpu_switches routines were likewise created to handle
the PDP-1, where 18 bits could fit in just about anyone's definition
of "long", and extended to two longs to handle 36 bits.
