### ISSUE TITLE
"help attach switches -f" does not document TAR format

### ISSUE THREAD

**Issue by hbent** [simh/simh#1002]
The title pretty much says it all; in "help attach switches -f" there is no mention of TAR tape format.

**Comment by markpizz** [comment]
Different sets of switches have different meaning for different devices and/or different commands.  Each device's ATTACH command may have completely different meaning.  HELP ATTACH SWITCHES describes the default switch interpretation for devices which don't leverage one of the common libraries (DISK, TAPE, ETHER, CARD, etc.).

Meanwhile, the HELP <tape-dev> ATTACH command (for tape devices) will display the meaningful switches for attaching tapes.

**Comment by markpizz** [comment]
```
sim> HELP <dev> ATTACH
or merely:
sim> HELP <dev>
```

will provide device specific help information if it is available for any particular device
