### ISSUE TITLE
PDP11: simh crashes on RESET after RESTORE

### ISSUE THREAD

**Issue by friesga** [simh/simh#1025]
- #### Context
The following scenario reproduces the issue:
-- SAVE an image,
-- Restart simh,
-- RESTORE the saved image,
-- RESET simh, specifically the vh device,
The result is a simh crash. The debugger shows a possible heap corruption on the realloc call on line 1879 in sim_tmxr.c.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
PDP-11 simulator V4.0-0 Current        git commit id: 62871bc5+uncommitted-changes
sim> show version
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 19.28.29336.00
        Simulator Compiled as C arch: x86 (Debug Build) on Mar 28 2021 at 09:16:31
        Build Tool: simh-Visual-Studio-Project
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.10, PNG Version 1.6.37, zlib: 1.2.11
        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: npcap or winpcap not installed
        OS: Microsoft Windows [Version 10.0.19041.867]
        Architecture: x86 on AMD64, Processors: 12
        Processor Id: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD, Level: 23, Revision: 7100
        tar tool: bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.5.f-ipp
        curl tool: curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
        git commit id: 62871bc5+uncommitted-changes
        git commit time: 2021-02-26T11:10:20+01:00
sim>
- #### how you built the simulator or that you're using prebuilt binaries
Rebuild started...
1>------ Rebuild All started: Project: BuildROMs, Configuration: Debug Win32 ------
1>Check for required build dependencies & git commit id
1>Library support for Visual Studio 2019 is available
1>sim_BuildROMs.c
1>BuildROMs.vcxproj -> G:\src\simh\BIN\NT\Win32-Debug\BuildTools\BuildROMs.exe
1>Verify ROM data
2>------ Rebuild All started: Project: PDP11, Configuration: Debug Win32 ------
2>Check for required build dependencies & git commit id
2>Library support for Visual Studio 2019 is available
2>pthread.c
2>display.c
2>ng.c
2>sim_ws.c
2>vt11.c
2>pdp11_ch.c
2>pdp11_cis.c
2>pdp11_cpu.c
2>pdp11_cpumod.c
2>pdp11_cr.c
2>pdp11_daz.c
2>pdp11_dc.c
2>pdp11_dl.c
2>pdp11_dmc.c
2>pdp11_dup.c
2>pdp11_dz.c
2>pdp11_fp.c
2>pdp11_hk.c
2>pdp11_io.c
2>pdp11_io_lib.c
2>pdp11_ke.c
2>Generating Code...
2>Compiling...
2>pdp11_kg.c
2>pdp11_kmc.c
2>pdp11_lp.c
2>pdp11_ng.c
2>pdp11_pclk.c
2>pdp11_pt.c
2>pdp11_rc.c
2>pdp11_rf.c
2>pdp11_rh.c
2>pdp11_rk.c
2>pdp11_rl.c
2>pdp11_rom.c
2>pdp11_rp.c
2>pdp11_rq.c
2>pdp11_rs.c
2>pdp11_rx.c
2>pdp11_ry.c
2>pdp11_stddev.c
2>pdp11_sys.c
2>pdp11_ta.c
2>Generating Code...
2>Compiling...
2>pdp11_tc.c
2>pdp11_td.c
2>pdp11_tm.c
2>pdp11_tq.c
2>pdp11_ts.c
2>pdp11_tu.c
2>pdp11_vh.c
2>pdp11_vt.c
2>pdp11_xq.c
2>pdp11_xu.c
2>scp.c
2>sim_console.c
2>sim_disk.c
2>sim_ether.c
2>sim_fio.c
2>sim_serial.c
2>sim_sock.c
2>sim_tape.c
2>sim_timer.c
2>sim_tmxr.c
2>Generating Code...
2>Compiling...
2>sim_video.c
2>arp_table.c
2>bootp.c
2>cksum.c
2>dnssearch.c
2>if.c
2>ip_icmp.c
2>ip_input.c
2>ip_output.c
2>mbuf.c
2>misc.c
2>sbuf.c
2>slirp.c
2>socket.c
2>tcp_input.c
2>tcp_output.c
2>tcp_subr.c
2>tcp_timer.c
2>tftp.c
2>udp.c
2>Generating Code...
2>Compiling...
2>glib_qemu_stubs.c
2>sim_slirp.c
2>Generating Code...
2>   Creating library ..\BIN\NT\Win32-Debug\PDP11.lib and object ..\BIN\NT\Win32-Debug\PDP11.exp
2>PDP11.vcxproj -> G:\src\simh\BIN\NT\Win32-Debug\PDP11.exe
2>Running Available Tests
2> Running internal register sanity checks on PDP-11 simulator.
2>*** Good Registers in PDP-11 simulator.
2>
2> Simulator specific tests not found for PDP11 simulator.
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

- #### the expected behavior and the actual behavior
G:\src\simh\BIN\NT\Win32-Debug>PDP11.exe

PDP-11 simulator V4.0-0 Current        git commit id: 62871bc5+uncommitted-changes
sim> sav image
sim> exit
Goodbye

G:\src\simh\BIN\NT\Win32-Debug>PDP11.exe

PDP-11 simulator V4.0-0 Current        git commit id: 62871bc5+uncommitted-changes
sim> rest image
sim> reset vh

G:\src\simh\BIN\NT\Win32-Debug>

I noticed this behaviour on testing the SAVE/RESTORE capabilities of my m9312 implementation. The code base is from simh/master on the 26th of february. The "uncommited changes" are the changes to the project files. In this code base are no changes by me.

**Comment by markpizz** [comment]
Please provide missing configuration file that was used prior to the SAVE command.

**Comment by friesga** [comment]
Hi Mark, I didn't use a configuration file. A SAVE/RESTORE on the default configuration produces the issue.

**Comment by friesga** [comment]
I investigated this issue a bit further with the aid of the VS2019 debugger. As I stated in the description the crash occurs on the realloc call on line 1879 in sim_tmxr.c. On that call the contents of lp->serconfig are corrupted.

Adding a watch breakpoint on that location shows that during a RESTORE the contents of that location are changed on the statement "*ptr = (*ptr & ~(((uint32) mask) << rptr->offset)) | (((uint32) val) << rptr->offset);" in put_rval_pcchk() (line 9467 in scp.c). The value of ptr is determined in the statement before: "ptr = (uint32 *)(((size_t) rptr->loc) + (idx * rptr->str_size));". This leads to the presumption that rptr->loc has an incorrect value at that point.

At this point rptr points at the register OBPTR in the td_reg array. Not knowing the intricacies of the tdc device, from the code I get the impression that the loc field of the register should point to an address in the first controller and that idx*rptr->str_size is used as an offset from that address.

The loc fields in the tdc registers are initialized in td_reset_ctlr(CTLR* ctlr). In this function the loc field for a register is set to the address of the relevant field in the controller, "reg = find_reg ("OBPTR", NULL, ctlr->dptr);
if (reg) reg->loc = (void *)&ctlr->obptr;" for example. For this initialization the address of the current CTLR structure is used. My assumption is that that is incorrect and instead the address of the first CTLR (i.e. the first element in the td_ctlr[] array) has to be used. (By the way, a call to td_reset() results in 16 td_reset_ctlr() calls which results in 16 updates to different values for the loc field.)

My assumption seems to be confirmed by the fact that on addition of the statement "ctlr = &td_ctlr[0];" in td_reset_ctlr() after the initialization of the controller and before setting the register loc fields, simh no longer crashes on the realloc call.

It's a bit complicated to explain, but I hope this helps to resolve the issue.

**Comment by markpizz** [comment]
Thanks for digging. I'll look at the TD subtlety.  

My initial test using VS2008 when you first reported this DID NOT experience the same problem, which does appear using VS2019.
I've been offline dealing with a medical procedure, so not too focused on working on things,  I'll get to it in a day or so.

Thanks again.
