### ISSUE TITLE
iosdispR function pointers cannot be cleared

### ISSUE THREAD

**Issue by friesga** [simh/simh#1029]
While resolving some attach/detach issues for the m9312 implementation, I noticed a possible issue in build_ubus_tab.

The Unibus table is initialized in init_ubus_tab. In that function the arrays iodispR, iodispW and iodipb, containing respectively pointers to the read function, the write function and the device information block (DIB) are initialized. When a ROM unit is added the function build_ubus_tab is called. That function sets (in lines 431 to 435) in iodispR a pointer to the read function for the ROM. This way the ROM contents are available in the I/O address space.

When a ROM unit is removed (detached), the ROM contents have to be removed from the I/O address space. That means that build_ubus_table is called again, this time with a nullified pointer to the read function to reflect that the ROM can no longer be read. I would expect this call would remove the pointer to the read function in iodispR. However in line 429 just the iodibp array is adjusted and iodispR is left intact. This means that on a read in the address space of the previously attached ROM, the ROM read function still is called, even when the ROM contents are removed.

I guess that after a deregistration of the DIB in line 429, also the entries in iodispR and iodispW should be cleared.

**Comment by markpizz** [comment]
Good catch.  Fixed now.
