### ISSUE TITLE
swtp6800 dwtbug doesn't execute

### ISSUE THREAD

**Issue by ctigs** [simh/simh#103]
Hello guys,

Host is Linux Mint 16, but maybe that doesn't matter..
## ~/simh $

When executing under 4.0 I get this:

$ swtp6800mp-a2

SWTP 6800, V2, MP-A2 CPU Board simulator V4.0-0 Beta        git commit id: 8b9e33c3
Logging to file "log.log"
sim> g

PC=E1AB SP=0000 IX=0000 A=07 B=00 CCR=D0
Invalid Opcode, PC: E1AB
sim> 

I removed the G command from the ini file and added the log command.

The set verbose or cpu history commands give errors.

I have tried to single step the system to see what's going on in the monitor rom and looking at the source for the monitor it looks like the cpu is miscalculating jump addresses, etc.  According to the swtp docs the start address for the rom is E0D0 yet when I initialize the simulator the PC is set to E0C6.

$ swtp6800mp-a2

SWTP 6800, V2, MP-A2 CPU Board simulator V4.0-0 Beta        git commit id: 8b9e33c3
Logging to file "log.log"
sim> e pc
PC: E0C6
sim> s

PC=E073 SP=0000 IX=0000 A=00 B=00 CCR=D0
Step expired, PC: E073
sim> s

PC=E075 SP=0000 IX=0000 A=07 B=00 CCR=D0
Step expired, PC: E075
sim> s

PC=E1AB SP=0000 IX=0000 A=07 B=00 CCR=D0
Step expired, PC: E1AB
sim> s

PC=E1AB SP=0000 IX=0000 A=07 B=00 CCR=D0
Invalid Opcode, PC: E1AB
sim> 

However it still doesn't run if I set the PC to the correct address:

$ swtp6800mp-a2

SWTP 6800, V2, MP-A2 CPU Board simulator V4.0-0 Beta        git commit id: 8b9e33c3
Logging to file "log.log"
sim> g e0d0
Segmentation fault
$

Stepping shows:

$ swtp6800mp-a2

SWTP 6800, V2, MP-A2 CPU Board simulator V4.0-0 Beta        git commit id: 8b9e33c3
Logging to file "log.log"
sim> d pc e0d0
sim> s

PC=E0D3 SP=A042 IX=0000 A=00 B=00 CCR=D8
Step expired, PC: E0D3
sim> s

PC=E102 SP=A042 IX=0000 A=00 B=00 CCR=D8
Step expired, PC: E102
sim> s

PC=E104 SP=A042 IX=0000 A=60 B=00 CCR=D1
Step expired, PC: E104
sim> s

PC=E106 SP=A042 IX=0000 A=FF B=00 CCR=D9
Step expired, PC: E106
sim> s

PC=E2D1 SP=A040 IX=0000 A=FF B=00 CCR=D9
Step expired, PC: E2D1
sim> s
Segmentation fault
$

I'll try the executables for "that other operating system" when I get back home this evening (M$)

**Comment by Amain** [comment]
> I thought these were all interchangeable. I can do the zipping on a linux platform if that works better?
> 
> ...

Little late to the party, but, if you're(@nj7p ) still working on this, please create a working zip for Linux. I tried to use the kit, http://simh.trailing-edge.com/kits/swtp6800-swk.zip, but whatever I do, including using the extract function in Windows Explorer, I get the md5 ending on ...631 and not on ..75a. 

The one ending on ..631 won't run, as mentioned in this bug, and  throws the 'Invalid Opcode, PC: E1AB' message. The ROM, ending on ..75a, from this simh repository works.

**Comment by nj7p** [comment]
My support files are at:

http://www.nj7p.org/Computers/simh.html

Bill

**Comment by Amain** [comment]
@nj7p thank you, that works!
