### ISSUE TITLE
Unable to build Simh using Visual Studio Build tools

### ISSUE THREAD

**Issue by sresun** [simh/simh#1032]
hello there from this [link](https://github.com/simh/simh/blob/master/Visual%20Studio%20Projects/0ReadMe_Projects.txt) I came to know that in order to install Simh on windows using Visual Studio I just need to download [this](https://github.com/simh/windows-build) repository and run the `build_vstudio.bat` file on Developers Command Prompt but I'm getting this:

![cmd](https://user-images.githubusercontent.com/63838516/114852444-a2b00800-9d97-11eb-89f7-b5ba6340c9a3.png)

while doing so. Please help me.

**Comment by markpizz** [comment]
You started at the right place by looking at 0ReadMe_Projects.txt in the "Visual Studio Projects" directory which describes how to do things.  

I just took a Windows 10 VM and did a cold install of Visual Studio Community 2019.  I then opened the Visual Studio GUI and opened the "Visual Studio Solution" simh.sln in the "Visual Studio Projects" directory.  Opening that simh.sln file caused the newer VS2019 environment to convert the simh.sln and the various project files it references to the current Visual Studio Version.  Once the conversion completed, I was again able to open the simh.sln file and then build any or all of the various simulators.

Once this conversion had been achieved the build_vstudio.bat procedure also produced useful results.  Using the most recent version of VS2019, there were some obtuse messages emitted during the setup of each build which seem to be a consequence of recent versions of VS2019, but these didn't change the net result which was that each binary built successfully.  Those obtuse messages were not produced by the earlier VS2019 version used to initially add VS2019 support.  The build_vstudio.bat file defaults to build Release targets of the various simulators.  The most recent version of VS2019 fails when building the Release version of any of the simulators that have video devices.  This does not happen with the original version of VS2019 that was used to add VS2019 support.  You can build and run Debug versions of these simulators without any problem, but if you really want to run with a Release build, I suggest using VS2008 to compile the simulator(s) in question.

If you want to have the simplest build experience, follow the instructions in the 0ReadMe_Projects.txt file as to how to install VS2008 (Leaving whatever other Visual Studio version you may have already in place unchanged).  Use the VS2008 GUI to build which should happen without any surprising messages.  If you previously tried with a different Visual Studio version, then the simh.sln file would have been modified.  The original one can be fetched out of the git repository, or the conversion process should have left a copy of the original in "Visual Studio Projects\Backup\simh.sln".

**Comment by sresun** [comment]
thank you [markpizz](https://github.com/markpizz) I've successfully build SimH
