### ISSUE TITLE
ibmpcxt: i8253.c:(.text+0x30a): undefined reference to `unreg_dev'

### ISSUE THREAD

**Issue by jbglaw** [simh/simh#1043]
Hi!

I've set up some software testing (initially for Binutils+GCC, now extended to build NetBSD and SIMH), and found this for the ibmpcxt simulator:

> make GCC=/usr/lib/gcc-snapshot/bin/gcc TEST_ARG=-v BIN/ibmpcxt
> [...]
> lib paths are: /lib/ /lib/x86_64-linux-gnu/ /lib32/ /libx32/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/lib32/ /usr/libx32/
> include paths are:  /usr/lib/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11/include /usr/local/include /usr/lib/gcc-snapshot/include /usr/include/x86_64-linux-gnu /usr/include
> using libm: /usr/lib/x86_64-linux-gnu/libm.so
> using librt: /usr/lib/x86_64-linux-gnu/librt.so
> using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h
> using libpcre: /usr/lib/x86_64-linux-gnu/libpcre.so /usr/include/pcre.h
> using semaphore: /usr/include/semaphore.h
> using libdl: /usr/lib/x86_64-linux-gnu/libdl.so /usr/include/dlfcn.h
> using libpng: /usr/lib/x86_64-linux-gnu/libpng.so /usr/include/png.h
> using zlib: /usr/lib/x86_64-linux-gnu/libz.so /usr/include/zlib.h
> using mman: /usr/include/x86_64-linux-gnu/sys/mman.h
> ***
> *** BIN/ibmpcxt Simulator being built with:
> *** - compiler optimizations and no debugging support. GCC Version: 11.0.1.
> *** - Per simulator tests will be run.
> ***
> *** git commit id is 60a3c52e123d32ce7aa62fe25918b1a82cac4f7e.
> *** git commit time is 2021-04-27T08:54:23-0700.
> ***
> #cmake:ignore-target
> /usr/lib/gcc-snapshot/bin/gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -DSIM_GIT_COMMIT_ID=60a3c52e123d32ce7aa62fe25918b1a82cac4f7e -DSIM_GIT_COMMIT_TIME=2021-04-27T08:54:23-0700  -DSIM_COMPILER="GCC Version: 11.0.1" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCRE_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./Intel-Systems/common/i8088.c ./Intel-Systems/ibmpcxt/ibmpcxt_sys.c ./Intel-Systems/common/i8253.c ./Intel-Systems/common/i8259.c ./Intel-Systems/common/i8255.c ./Intel-Systems/ibmpcxt/ibmpcxt.c ./Intel-Systems/common/pceprom.c ./Intel-Systems/common/pcram8.c ./Intel-Systems/common/pcbus.c ./Intel-Systems/common/i8237.c  ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -I ./Intel-Systems/ibmpcxt -o BIN/ibmpcxt -lm -lrt -lpthread -lpcre -ldl -lpng -lz
> /usr/bin/ld: /tmp/ccjxdK8d.o: in function `i8253_clr':
> i8253.c:(.text+0x30a): undefined reference to `unreg_dev'
> /usr/bin/ld: i8253.c:(.text+0x31d): undefined reference to `unreg_dev'
> /usr/bin/ld: i8253.c:(.text+0x330): undefined reference to `unreg_dev'
> /usr/bin/ld: i8253.c:(.text+0x343): undefined reference to `unreg_dev'
> /usr/bin/ld: /tmp/cctizJpf.o: in function `i8259_clr':
> i8259.c:(.text+0x426): undefined reference to `unreg_dev'
> /usr/bin/ld: /tmp/cctizJpf.o:i8259.c:(.text+0x439): more undefined references to `unreg_dev' follow
> collect2: error: ld returned 1 exit status
> make: *** [makefile:2633: BIN/ibmpcxt] Error 1

Cf. http://toolchain.lug-owl.de:8080/jobs/simh-ibmpcxt/2

Is Intel-Systems/common/cpu.c needed?

Thanks,
Jan-Benedict

**Comment by markpizz** [comment]
This simulator is not currently in working order and therefore it isn't in the all target for make nor is the Visual Studio project part of the simh.sln file.  The developer will eventually get this working.  When he does, it will be part of the full build on all platforms.
