### ISSUE TITLE
PDP8: Incorrect assembly/disassembly of RF08 instructions 

### ISSUE THREAD

**Issue by jdersch** [simh/simh#1045]
- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

It appears that SIMH improperly assembles/disassembles RF08 IOTs --

DCMA should be 6601, is assembled as 6660
DMAR should be 6603, is assembled as 6601
DMAW should be 6605, is assembled as 6603
DCIM should be 6611, is assembled as 6605

etc, etc.

Looking at the current source in pdp8_sys.c it looks like the opc_val[] table is incorrect for RF08 IOT.  (Starts with 6660, 6601, etc, should start with 6601; 6660 does not appear to be a valid RF08 or DF32 IOT.

Thanks!

**Comment by archivisth** [comment]
A fix was submitted a few weeks ago. Not sure where is stands.
