### ISSUE TITLE
VAX8600 idle

### ISSUE THREAD

**Issue by JohanD66** [simh/simh#1056]
VAX8600 simh exe.

SET CPU IDLE = VMS does not seem to work (well).
Idle is still triple of what vax.exe does on my server.

**Comment by markpizz** [comment]
Given the truly amazing amount of detail you've provided here, all I can say is "It works for me!".

We're NOT here to PULL TEETH so we can understand your actual problem and then to provide solutions.

If you want to create a new issue that might get a useful answer, then PLEASE provide ALL the details that are specifically requested in the new issue template.
