### ISSUE TITLE
The PWD command does not work because of the "command aliasing" via the environment

### ISSUE THREAD

**Issue by al20878** [simh/simh#1057]
PWD gets replaced with the environment variable "$PWD" (which is usually present) and then cannot be "interpreted".
"PW" works, though.

The issue is due to the fact that commands can be aliased through the environment (the notable example is for `ECHOF`, which is both in the docs and help).

IMO command aliasing should have been kept separately from the environment, because the environment is potentially unsafe, just to be blindly used as "commands" -- any simh command found in the environment would be taken from there "as is", and that is a huge security hole. Here's an example of an attack:
```
$ export ATTACH="Echo echo delete -rf /"
$ ./pdp11
PDP-11 simulator V4.0-0 Current
sim> attach rq ...
echo delete -rf / rq
sim>
```
Now consider that `ATTACH="! rm -rf /"`.  The user executing the commands is totally unaware that they are not actually the commands executed, and there's no way to prevent that, or at least explicitly control that (as in when such a substitution is actually requested by the user, so they know what they are doing and assume the validity and risks).

**Comment by al20878** [comment]
This fix (5f8a8cc) is not okay, because it prevents doing something like
```
sim> echo %PWD%
```
``PWD`` is a standard UNIX environment and can potentially be used in perfectly allowed and fine simh scripting.  Stripping it just like the fix goes, would create questions, as to where did it disappear to?

**Comment by markpizz** [comment]
Please note:

1) PWD command now works!  Reported problem now solved.
2) Your example (```echo %PWD%```) can be achieved with both PWD and SHOW DEFAULT.  The fact that PWD was broken on Unix systems was one reason the SHOW DEFAULT command existed,
3) Your original point about security or other potential confusion is absolutely addressed now without impacting working portable scripts.
4) Depending on an external environment variable of PWD is a non platform independent solution as are most potential references to external environment variables.
5) There are other ways to glean path information in portable ways within SCP:
a) A script's path is accessible as ```%p0``` which could be used directly or via ```SET ENV SCRIPT_PATH=%p0```
b) the current working directory can be put into a simh environment variable with ```SET ENV CWD=.```
c) That can be fully expanded to the specific path via a second line ```SET ENV CWD=%~pCWD%```
6) You are a slightly late to the game to complain about the alias implementation approach since that feature was added back in 2012.

**Comment by al20878** [comment]
> Your example (echo %PWD%) can be achieved with both PWD and SHOW DEFAULT.

The example was to show the PWD environment variable used in a simh command.  Is this better: ``attach rq0 %PWD%/mydisk.dsk`` for the illustration ?..  I don't understand how the same can be achieved with the simulator's ``PWD`` command or ``SHOW DEFAULT``.

> The fact that PWD was broken on Unix systems was one reason the SHOW DEFAULT command existed,

Hmm...  And nobody asked / figured out, why?  So the fix was to just add another command. Clever!

> PWD is a non platform independent solution as are most potential references to external environment variables

If I am using UNIX to run simh (and most people do use it on only one platform), this point is moot entirely.  I can have a script, which the current fix just broke.  That simple.

> the current working directory

I never mentioned the current working directory.  It is almost never necessary to reference it, generally, because... well, it is _current_ working directory. Whereas  I said "startup directory".  PWD contains the directory at the time simh was started.  The current working directory could have been changed with the ``cd`` command from within simh, since then.  Thanks to the fix, there's no way of knowing the startup directory ever again.

> You are a slightly late to the game to complain about the alias implementation

Is this your way of saying "Thank you" to me for reporting the bug?

**Comment by al20878** [comment]
Oh, and BTW, to fix your fix the correct way is actually very easy: while sanitizing the environment as you do it now, instead of just throwing away the conflicting environment settings (that you do with "unsetenv()"), stash them away in a new array that can only be used for the %NAME% substitutions, and use that array (in addition to the environment) when a command gets interpreted / expanded.

You're welcome.

**Comment by markpizz** [comment]
> > Your example (echo %PWD%) can be achieved with both PWD and SHOW DEFAULT.
>
> The example was to show the PWD environment variable used in a simh command. Is this better: attach rq0 %PWD%/mydisk.dsk for the illustration ?.. I don't understand how the same can be achieved with the simulator's PWD command or SHOW DEFAULT.

The "echo" command you used as an example will have the desired output if you use either the PWD or SHOW DEFAULT command in a trivial script (or directly entered by hand).

PWD should in fact precisely equal the CWD example I provided, so if you need an environment variable with PWD in it, you could start your script with the suggested commands substituting PWD for CWD.

> > The fact that PWD was broken on Unix systems was one reason the SHOW DEFAULT command existed,
>
> Hmm... And nobody asked / figured out, why? So the fix was to just add another command. Clever!

Actually, no.  SET DEFAULT and SHOW DEFAULT were implemented first and then PWD and CD were added as built in command aliases.  I noticed the problem with PWD but don't recall actually getting any complaints so I didn't look to why it wasn't working.  Thanks for pointing that detail out.

> > PWD is a non platform independent solution as are most potential references to external environment variables
> 
> If I am using UNIX to run simh (and most people do use it on only one platform), this point is moot entirely. I can have a script, which the current fix just broke. That simple.

The point is not moot if the fundamental goal is to provide reliable portable behaviors across host system types.

> > the current working directory
> 
> I never mentioned the current working directory. It is almost never necessary to reference it, generally, because... well, it is current working directory. Whereas I said "startup directory". PWD contains the directory at the time simh was started. The current working directory could have been changed with the cd command from within simh, since then. Thanks to the fix, there's no way of knowing the startup directory ever again.

So you could save the current working directory at the beginning of  your script which would meet your goal to be independent of the consequences of the current directory changing.

> > You are a slightly late to the game to complain about the alias implementation
> 
> Is this your way of saying "Thank you" to me for reporting the bug?

No.  It is a way to say that bugs (like you reported) will be fixed, but it's not going to be redesigned from scratch the way you suggested.

**Comment by al20878** [comment]
> PWD should in fact precisely equal the CWD example I provided

The ``PWD`` _environment_ is not changing when simh changes the current working directory (so it still refers to the original _startup directory_).  While the built-in ``PWD`` command does show the expanded value of "." (CWD).  They are two different entities!

> if the fundamental goal is to provide reliable portable behaviors across host system types

I don't think it is ever a goal for an average simh user.  Folks use it on the same platform, and along with that they use what the platform provides, potentially including the PWD environment on Unix.  So no, it's not _fundamental_ by any means.

> but it's not going to be redesigned from scratch the way you suggested.

Never suggested a redesign from scratch, or a redesign at all -- where is this coming from?  I merely said that "aliases should have been kept separately", as a conditional hypothetical clause, because that would have spared from having to fix this (and a potential security issue) now.

What I was pointing out, though, was that the fix you provided was incomplete, as it introduced a new problem and wasn't backward compatible.  I already suggested (see above) how you can possibly fix this, too.

**Comment by markpizz** [comment]
> > The "echo" command you used as an example will have the desired output if you use either the PWD or SHOW DEFAULT command
> 
> You are mistaken:
> 
> /cygdrive/g/cygwin/simh/simh
> $ BIN/pdp11
> PDP-11 simulator V4.0-0 Current        git commit id: f1a2c81c
> sim> echo %PWD%
> /cygdrive/g/cygwin/simh/simh
> sim> cd ..
> sim> echo %PWD%
> /cygdrive/g/cygwin/simh/simh
> sim> pw
> /cygdrive/g/cygwin/simh
> sim> cd /cygdrive/c/windows
> sim> echo %PWD%
> /cygdrive/g/cygwin/simh/simh
> sim> pw
> /cygdrive/c/windows

I was specifically speaking about the behavior of the trivial one line echo command script in your example.   PWD and SHOW DEFAULT are equivalent to that!


> > PWD should in fact precisely equal the CWD example I provided
> 
> The PWD environment is not changing (see above) when simh changes the current working directory (so it still refers to the original startup directory). While the built-in PWD command does show the expanded value of "." (CWD). They are two different entities!

The simh CD command was never intended to change any environment variables.

Meanwhile, I described a mechanism to populate a simh internal environment variable with the current directory value at the start of the script which is precisely the same as the external PWD environment variable.  That internal variable will persist throughout the simh execution until it is explicitly changed by some other deliberate action in the script.  If you want an environment variable to reflect the current working directory after a change of directory (with CD), then that previously described mechanism can be used to store that information in an environment variable.

> What I was pointing out, though, was that the fix you provided was incomplete, as it introduced a new problem and wasn't backward compatible. I already suggested (see above) how you can possibly fix this, too.

See the most recent commit.

**Comment by al20878** [comment]
> I was specifically speaking about the behavior of the trivial one line echo command script in your example. PWD and SHOW DEFAULT are equivalent to that!

Right, but I never specified at which point the command was issued.  The result of this command (provided that the ``PWD`` _environment_  is left alone) does not change, while the ``PWD`` _command_'s output depends on CWD of the process.

> The simh CD command was never intended to change any environment variables.

I'm well aware of that -- simh is no different that any other program with that respect.  Which is why I said that using the ``PWD`` _environment_ might be a very handy way to reference the _startup directory_ at any point of a simh session, regardless of any ``CD`` command(s) that might have been issued in the interim.

> See the most recent commit.

It is getting better, thanks!  One slight wrinkle still remains:  when an external command is spawned, it should receive the full environment as it existed when simh started.  Otherwise, there exists a discrepancy (suppose that someone is expecting their special environment to be used in shell scripts that they call from simh, regardless of any malicious intents).  For example:
```
...
$ export IGNORE="my fave env for some reason"
...
sim> echo %IGNORE%
my fave env for some reason
sim> ! echo $IGNORE

sim>
...
```
(note that ironically for the ``PWD`` _environment_ **specifically** that is not that critical, because the subshell will re-create it, although it might receive different contents than before -- especially if the _startup directory_ involved any symlinking -- that information will be usually lost when the shell creates, rather than inherits, the variable... but I digress)

So in order to fix that in general form, the environment passed to a (sub)process must be reconstructed: all non-conflicting entries from ``sim_external_env`` should be added back to the _environment_ prior to the ``system()`` call, and then all of those added -- stripped from the _environment_ again, once the command has completed (the pairs in ``sim_external_env`` remain unchanged throughout this process).  I think this is quite straightforward to implement: you can have an additional flag in ``sim_external_env`` in each entry for bookkeeping: if it was added(1) or not(0) prior to ``system()``. Once ``system()`` returns, you can go over that array again and call ``unsetenv()`` only for those having (1) in that flag.

Hope this helps.

**Comment by al20878** [comment]
> 2c820dc 

This patch is not exactly correct as it overwrites and corrupts all the environment variables that might have been modified from within the simh session by the user:  those should keep their values in the subprocess, not the original ones, that existed at the time simh started.  Which is why I said, "all non-conflicting entries", meaning only the entries of ``sim_external_env`` that do not exist in the current _environment_ (so if for example, ``SET ENV IGNORE "new value"`` was issued in the simh session, then ``"! echo $IGNORE"`` should output ``new value``, and not something that ``IGNORE`` was defined formerly:
```
  for (entry : sim_external_env) {
    if (!getenv(entry->name)) {
      setenv(entry->name, entry->value, 1/*irrelevant, but just in case*/);
      entry->flag = 1;
    } else
      entry->flag = 0;
  }
  ...
  system(...);
  ...
  for (entry : sim_external_env) {
    if (entry->flag)
      unsetenv(entry->name);
  }
```

**Comment by markpizz** [comment]
The most recent commit removed entries from the list of external alias command names that were initially collected WHENEVER any simh environment variable with precisely the same name is explicitly set.  As soon as simh defines an environment variable it becomes a potential simh alias and a name which is then inherited by spawned processes.  The name which may have existed in the environment when the simh process was created is no longer interesting to anything within simh or any spawned process it creates.

Why do you think this doesn't solve the problem you're concerned about?

**Comment by al20878** [comment]
> Why do you think this doesn't solve the problem you're concerned about?

My bad, I haven't noticed the part of the patch that removes entries from ``sim_external_env`` upon user's request to set an environment from within simh session -- it was obscured at the bottom part of my screen here.  Sorry about that.

Indeed the patch is complete, and I checked that it worked correctly (including under the debugger that actually showed to me that I was missing the last part of the patch, mentioned above).

Thanks
