### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by mcandre** [simh/simh#1062]
Hello,

I am having trouble getting basic usage information from the README. How does one:

* Launch an emulated VAX instance with simh?
* Enter a VAX terminal session with simh?
* Any SSH or serial support?

**Comment by mike632t** [comment]
I need to update this (basically change libsdl1.2debian to libsdl2-dev) but it and related posts should help you get you started...

https://mike632t.wordpress.com/2013/03/24/installing-simh/
