### ISSUE TITLE
Report an actual error when unable to open a file

### ISSUE THREAD

**Issue by al20878** [simh/simh#1064]
When simh is unable to open a disk image file (for some reason), it only reports that the "file doesn't exist" (which might not even be true, and so is very confusing):
```
sim> att -e rk dos_rk.dsk
RK0: File not found: dos_rk.dsk
sim> dir dos_rk.dsk
 Directory of /home/systems/dos11

08/06/2021  10:38 PM         2,457,600 dos_rk.dsk
               1 File(s)         2,457,600 bytes
               0 Dir(s)
```

Attached is a patch that makes the user aware of what exactly went wrong (and also uses less confusing wording).
```
sim> att -e rk dos_rk.dsk
RK0: Cannot open "dos_rk.dsk": Device or resource busy
sim> att rk dos_rk.dsk
RK0: Cannot create "dos_rk.dsk": Device or resource busy
```

Note that when simh is unable to open a file without the ``-e`` switch it proceeds with an attempt to create the file.  Since the underlying system errors (``errno``) can have a variety of reasons, it is hard to know (from just the the open failure) if the file in fact existed.  Using the ``stat()`` syscall could be a remedy in this case, before an attempt to re-create the file (it's in fact crucial on filesystems that support file versioning, but I don't think simh runs on any of those -- but if it does, then the error analysis should be performed, otherwise, a new file with a higher version will be created "to supersede" the existing version that just couldn't be opened).  The patch, however, does not address that (just like the original simh code didn't).

Hope this helps.

```
From 664a67a1e8d07551a5e72e369493e49fd42d90c6 Mon Sep 17 00:00:00 2001
From: Tony Lawrence <al20878@gmail.com>
Date: Sat, 7 Aug 2021 12:02:31 -0400
Subject: [PATCH] Report an actual error when unable to open a file

---
 sim_disk.c | 12 ++++++++----
 1 file changed, 8 insertions(+), 4 deletions(-)

diff --git a/sim_disk.c b/sim_disk.c
index 29c9c61d..d491af12 100644
--- a/sim_disk.c
+++ b/sim_disk.c
@@ -2599,14 +2599,18 @@ else {                                                  /* normal */
             sim_messagef (SCPE_OK, "%s: unit is read only\n", sim_uname (uptr));
             }
         else {                                          /* doesn't exist */
-            if (sim_switches & SWMASK ('E'))            /* must exist? */
-                return sim_messagef (_err_return (uptr, SCPE_OPENERR), "%s: File not found: %s\n", sim_uname (uptr), cptr);
+            if (sim_switches & SWMASK ('E')) {           /* must exist? */
+                return sim_messagef (_err_return (uptr, SCPE_OPENERR), "%s: Cannot open \"%s\": %s\n",
+                                     sim_uname (uptr), cptr, strerror (errno));
+                }
             if (create_function)
                 uptr->fileref = create_function (cptr, ((t_offset)uptr->capac)*ctx->capac_factor*((dptr->flags & DEV_SECTORS) ? 512 : 1));/* create new file */
             else
                 uptr->fileref = open_function (cptr, "wb+");/* open new file */
-            if (uptr->fileref == NULL)                  /* open fail? */
-                return sim_messagef (_err_return (uptr, SCPE_OPENERR), "%s: Can't create file: %s\n", sim_uname (uptr), cptr);
+            if (uptr->fileref == NULL) {                /* open fail? */
+                return sim_messagef (_err_return (uptr, SCPE_OPENERR), "%s: Cannot create \"%s\": %s\n",
+                                     sim_uname (uptr), cptr, strerror (errno));
+                }
             sim_messagef (SCPE_OK, "%s: creating new file: %s\n", sim_uname (uptr), cptr);
             created = TRUE;
             }
--
2.32.0
```

**Comment by markpizz** [comment]
Good suggestion.  More precise error messages is always better.

I've modified the formatting of the message a little to make it consistent with other messages emitted by sim_disk and made many of them more consistent as well.

File system versioning (on VMS host systems) more or less works as generally expected on such a system:
1) If a specific version number is mentioned as part of the file specification, then the existing code and error messages are fine,
2) If the file specification doesn't mention a version number:
a) An open for read (mode: "rb") works fine with existing messaging which naturally will attempt to open the most recent version.
b) An open for write (mode: "rb+") will open the most recent version or fail doing so as other things on that platform would do.
c) An open for create (mode: "wb+") (only tried if -R and -E not specified) will create a new version or fail doing so as other things on that platform would do.

**Comment by al20878** [comment]
> File system versioning (on VMS host systems) more or less works as generally expected on such a system:

Ok, here's the scenario:  Suppose ``image.dsk`` is locked, so it can't be open with ``-e`` (as in ``attach -e rk0 image.dsk``).  So the ``->fileref`` member is ``NULL``.  So the code goes on, and tries to open ``image.dsk`` with ``wb+``, meaning to create an empty file with a higher version.  So if ``image.dsk`` was in fact ``image.dsk;1`` on disk, attaching such an image would result in new ``image.dsk;2`` in the same directory.  That's not exactly correct, is it?  Unless I'm missing something.

**Comment by markpizz** [comment]
Absolutely true.  The problem you describes falls into the "more or less" category though.  With essentially 0 users actually running simh on VMS today (that may change when VMS on x86 is robustly available), I'll wait for a failing use case that actually demonstrates this and possibly react to the actual errno value that is observed.  That probably won't come up until pcap is available on that x86 VMS as well.

**Comment by al20878** [comment]
Okay.  The problem is that VMS users are used to "purge" their directories, and this "more of less" bug can cost them a loss of an image, absolutely obliviously.  Or if the version limit is set purposely low, VMS can even "take care" of that automatically ;-)

**Comment by al20878** [comment]
```
--- a/sim_disk.c
+++ b/sim_disk.c
@@ -2599,7 +2599,7 @@ else {                                                  /* normal */
             sim_messagef (SCPE_OK, "%s: Unit is read only\n", sim_uname (uptr));
             }
         else {                                          /* doesn't exist */
-            if (sim_switches & SWMASK ('E'))            /* must exist? */
+            if ((sim_switches & SWMASK ('E')) || (errno != ENOENT))  /* (must) exist? */
                 return sim_messagef (_err_return (uptr, SCPE_OPENERR), "%s: Cannot open '%s' - %s\n",
                                      sim_uname (uptr), cptr, strerror (errno));
             if (create_function)
```
This patch fixes the "more or less" bug, and also avoids seeing this kind of a message:
```
sim> att rk dos_rk.dsk
RK0: Cannot create 'dos_rk.dsk' - Device or resource busy
```
for images, which do exist:  "create" is not an applicable verb there.

So with the above, it shows:
```
sim> att rk dos_rk.dsk
RK0: Cannot open 'dos_rk.dsk' - Device or resource busy
```

**Comment by markpizz** [comment]
Good idea.

**Comment by al20878** [comment]
Thanks, that'll do.

**Comment by al20878** [comment]
BTW, may I suggest that comments are changed to reflect as to what's going on more correctly?
```
--- a/sim_disk.c
+++ b/sim_disk.c
@@ -2598,9 +2598,9 @@ else {                                                  /* normal */
             uptr->flags = uptr->flags | UNIT_RO;        /* set rd only */
             sim_messagef (SCPE_OK, "%s: Unit is read only\n", sim_uname (uptr));
             }
-        else {                                          /* doesn't exist */
+        else {                                          /* other error? */^M
             if ((sim_switches & SWMASK ('E')) ||        /* must exist? */
-                (errno != ENOENT))                      /* or other error? */
+                (errno != ENOENT))                      /* or must not re-create? */^M
                 return sim_messagef (_err_return (uptr, SCPE_OPENERR), "%s: Cannot open '%s' - %s\n",
                                      sim_uname (uptr), cptr, strerror (errno));
             if (create_function)
```

**Comment by al20878** [comment]
Thanks!
