### ISSUE TITLE
SCSI Problem with infoserver150vxt

### ISSUE THREAD

**Issue by vaxorcist** [simh/simh#1076]
- #### Context
The problem occurs with the simulator infoserver150vxt (and maybe others, too) 
One of the rz devices (e.g. rz2) is configured as an RRD42
When the simulator is booted there is an error message "SCSI: commands unimplemented for device type 4" 
The console command "SHOW DEVICE" shows the same error "SCSI: commands unimplemented for device type 4" and the device is not recognized
The simulator hangs when trying to boot from the console, e.g.: "BOOT DKA200:"  

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
sim> sh ver
Infoserver 150 VXT (KA41-2) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 8.3.0
        Simulator Compiled as C arch: x64 (Release Build) on Aug 27 2021 at 22:30:44
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.9
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux think 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
        git commit id: 522c853f
        git commit time: 2019-04-19T14:13:56+01:00
sim> 
- #### how you built the simulator or that you're using prebuilt binaries
make infoserver150vxt
lib paths are: /lib/ /lib/x86_64-linux-gnu/ /lib32/ /usr/lib/x86_64-linux-gnu/libfakeroot/ /usr/local/lib/ /usr/lib/
include paths are:  /usr/lib/gcc/x86_64-linux-gnu/8/include /usr/local/include /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed /usr/include/x86_64-linux-gnu /usr/include
using libm: /lib/x86_64-linux-gnu/libm.so
using librt: /lib/x86_64-linux-gnu/librt.so
using libpthread: /lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h
using libpcre: /lib/x86_64-linux-gnu/libpcre.so /usr/include/pcre.h
using semaphore: /usr/include/semaphore.h
using libdl: /lib/x86_64-linux-gnu/libdl.so /usr/include/dlfcn.h
using libpng: /lib/x86_64-linux-gnu/libpng.so /usr/include/png.h
using zlib: /lib/x86_64-linux-gnu/libz.so /usr/include/zlib.h
using mman: /usr/include/x86_64-linux-gnu/sys/mman.h
using libpcap: /usr/local/include/pcap.h
*** Info ***
*** Info *** infoserver150vxt Simulator is being built with
*** Info *** minimal libpcap networking support
*** Info ***
*** Info ***
*** Info *** Simulators on your Linux platform can also be built with
*** Info *** extended LAN Ethernet networking support by using VDE Ethernet.
*** Info ***
*** Info *** To build simulator(s) with extended networking support you
*** Info *** should install the vde2 package to provide this
*** Info *** functionality for your Linux system:
*** Info ***        $ sudo apt-get install libvdeplug-dev
*** Info ***
***
*** infoserver150vxt Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 8.3.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
*** - Per simulator tests will be run.
***
*** git commit id is 64b1223468b30c6c2e344bbfd9c82834437b92be.
*** git commit time is 2021-08-17T15:35:51-07:00.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -DSIM_GIT_COMMIT_ID=64b1223468b30c6c2e344bbfd9c82834437b92be -DSIM_GIT_COMMIT_TIME=2021-08-17T15:35:51-07:00  -DSIM_COMPILER="GCC Version: 8.3.0" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCRE_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./VAX/vax_cpu.c ./VAX/vax_cpu1.c ./VAX/vax_fpa.c ./VAX/vax_cis.c ./VAX/vax_octa.c ./VAX/vax_cmode.c ./VAX/vax_mmu.c ./VAX/vax_sys.c ./VAX/vax_syscm.c ./VAX/vax_watch.c ./VAX/vax_nar.c ./VAX/vax4xx_stddev.c ./VAX/vax420_sysdev.c ./VAX/vax420_syslist.c ./VAX/vax4xx_dz.c ./VAX/vax4xx_rd.c ./VAX/vax4xx_rz80.c ./VAX/vax_xs.c ./VAX/vax4xx_va.c ./VAX/vax4xx_vc.c ./VAX/vax4xx_ve.c ./VAX/vax_lk.c ./VAX/vax_vs.c ./VAX/vax_gpx.c ./sim_scsi.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -DVM_VAX -DVAX_420 -DUSE_INT64 -DUSE_ADDR64 -DUSE_SIM_VIDEO -I ./VAX -I ./PDP11 -DHAVE_PCAP_NETWORK -I/usr/local/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c   -DVAX_412 -o BIN/infoserver150vxt -lm -lrt -lpthread -lpcre -ldl -lpng -lz  
BIN/infoserver150vxt RegisterSanityCheck /media/ulli/SSD-Backup/Testing/9TRACK/simh-master/VAX/tests/vax-diag_test.ini </dev/null 
 Running internal register sanity checks on InfoServer 150 VXT (KA41-2) simulator.
*** Good Registers in InfoServer 150 VXT (KA41-2) simulator.

InfoServer 150 VXT (KA41-2) simulator V4.0-0 Current        git commit id: 64b12234
Running Hardware Core Test (EHKAA)

*** PASSED - InfoServer 150 VXT (KA41-2) Hardware Core Instruction test EHKAA

- #### the simulator configuration file (or commands) which were used when the problem occurred.
; ================================================
; infoserver150vxt.ini
; ================================================

; CPU Settings
SET CPU 4M
SET CPU IDLE=INFOSERVER
SET CPU CONHALT

ATTACH NVR VAX412.NVR

SET DZ DISABLED

SET RZ0 DISABLED

SET RZ1 RZ23
ATTACH RZ1 INFO.DSK

SET RZ2 RRD42
ATT RZ2 -R ag-r7lfa-bs.img

SET RZ3 DISABLED
SET RZ4 DISABLED
SET RZ5 DISABLED
SET RZ7 DISABLED

SET RZB0 DISABLED
SET RZB1 DISABLED
SET RZB2 DISABLED
SET RZB3 DISABLED
SET RZB4 DISABLED
SET RZB5 DISABLED
SET RZB7 DISABLED

BOOT CPU

- #### the expected behavior and the actual behavior
- The simulator should pass the self test when it is booted
- The CDROM device should be recognized by the console command "SHOW DEVICE"
- The CDROM device should be bootable

Remark: The simulator microvax3100 works as expected

Output:
KA41-2  V1.0          

F_..E...D...C?..B?..A...9_..8?..7SCSI: commands unimplemented for device type 4
?..6...5?..4_..3_..2_..1?..

??  C  0080  0000.0004
??  B  0010  0004.0020
??  8  0060  0000.0002
??  7  80A0  0602.31D0
 ?  6  80A1  0000.4001
??  5  0001  0000.000A
??  1  00C0  0000.1004

>>> show device
SCSI: commands unimplemented for device type 4
 VMS/VMB  ULTRIX    ADDR    DEVTYP  NUMBYTES  RM/FX  WP  DEVNAM  REV
 -------  ------  --------  ------  --------  -----  --  ------  ---
 ESA0     SE0     08-00-2B-D3-A3-E1

 DKA100   RZ1     A/1/0/00  DISK      104 MB   FX        RZ23   0A18
 ...HostID....    A/6       INITR

>>> b dka200

SCSI: commands unimplemented for device type 4
<Simulator hangs here ...>

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Both of the  commits you are reporting this issue above:
```
git commit id: 522c853
git commit time: 2019-04-19T14:13:56+01:00
```
and
```
-DSIM_GIT_COMMIT_ID=64b1223468b30c6c2e344bbfd9c82834437b92be 
-DSIM_GIT_COMMIT_TIME=2021-08-17T15:35:51-07:00 
```

Are not part of the code in this repository.  The code in this repository DOES NOT demonstrate your problem.
