### ISSUE TITLE
Hyper-V and SIMH networking - unable to get DHCP address

### ISSUE THREAD

**Issue by lukeb1961** [simh/simh#1078]
You have a Linux VM running under Hyper-V and you have configured a tap0 bridge
you then start simh VAX and it binds successfully.
boot your OS (eg NetBSD)

if you find your NetBSD vax is not getting a DHCP address
 go to your Hyper-V manager
  select the Linux VM
   settings->Network Adapter
   expand the "+"
    go to Advanced Features
    tick the box for "Enable MAC address spoofing"

your NetBSD can now successfully query for DHCP addresses.

**Comment by markpizz** [comment]
It doesn't look like you've described a simh problem here.
