### ISSUE TITLE
How to use PDP-1 sim?

### ISSUE THREAD

**Issue by assortedkingdede** [simh/simh#1079]
I wanted to play around with the PDP-1 Sim for fun but I have no idea how to use it, I tried to load a simple music program with the L command but I got either a file format error or a file open error. I have a feeling I'm doing something wrong. 
Any info would help.

**Comment by assortedkingdede** [comment]
Note Space War also hit me with the same error.

**Comment by markpizz** [comment]
This really isn't the place to ask how to use questions.  However, if you were to ask such a question here, you had better fill out the form you were presented with when you created this issue which CLEARLY didn't ask for vague things, but for precisely specific things which you tried (and in this case, how you possibly knew to try those things) and precisely what happened.  Feel free to reopen this issue or a new one when you can provide enough information so someone might be able to understand what you've done.
