### ISSUE TITLE
Migration to CMake or Meson

### ISSUE THREAD

**Issue by XVilka** [simh/simh#1093]
Currently the building system is unnecessary complex, also dependency handling and portability is lacking. Migrating to CMake or Meson will make everyone's life 10x times easier.

Moreover, it will allow to get rid of Visual Studio-specific files, MinGW hacks, and so on.

Related PRs and branches:
- https://github.com/simh/simh/pull/775
- https://github.com/markpizz/simh/tree/potential-cmake-support
- https://github.com/retroprom/simh/tree/feature/cmake-build

**Comment by markpizz** [comment]
I welcome fixes to things which are broken or new and/or updated simulator code.

I do not welcome fixing or partially replacing things which are not broken.

I do not welcome things which implement change for the sake of change without new functionality.

**Comment by friesga** [comment]
There are things called "progress".
