### ISSUE TITLE
SDL2 error message from SimH requests update, but updated version not in development binaries or Windows_build support

### ISSUE THREAD

**Issue by pghardy** [simh/simh#1095]
- #### Context
Running VAXStation3100M38, various behaviours (scrolling off bottom of window, or starting to shut down VMS) provoke SDL2 error messages from SimH as shown below. These hang SIMH and the simulation fails. The message requests an update to SDL2 to 2.0.14 , but that updated version is not included in the supplied development binaries or in the Windows_build support, so is not applicable. 

Please can Windows_Build support and the pre-built development binaries be updated to include SDL2 2.0.14, to avoid these errors?

Further, it would help if SIMH treated unexpected events as soft errors, and continued with the simulation, to allow a safe shutdown.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
sim> sh ver
VAXstation 3100 M38/GPX (KA42-B) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Debug Build) on Nov  7 2021 at 09:05:37
        Build Tool: simh-Visual-Studio-Project
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.10, PNG Version 1.6.37, zlib: 1.2.11
        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
        OS: Microsoft Windows [Version 10.0.19043.1288]
        Architecture: x86 on AMD64, Processors: 4
        Processor Id: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel, Level: 6, Revision: 9e09
        tar tool: bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.5.f-ipp
        curl tool: curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
        simh git commit id: 6d9a55d3
        simh git commit time: 2021-11-01T15:33:43-07:00
sim>
- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

SIMH has encountered a bug in SDL2.  An upgrade to SDL2 version 2.0.14 should fix this problem.
Unrecognized mouse motion event.
  type = 1024
  timestamp = 267464
  windowID = 0
  which = 0
  state = 0
  x = -148
  y = 199
  xrel = 4
  yrel = -4
  
  
  SIMH has encountered a bug in SDL2.  An upgrade to SDL2 version 2.0.14 should fix this problem.
  Unrecognized user event.
    type = 32768
    timestamp = 218399
    windowID = 7340924
    code = 10
    data1 = 00000000
    data2 = 00000000

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem
Just shutting down VMS from a Motif login is sufficient to trigger the bug.

**Comment by agn453** [comment]
I'm seeing this under macOS (Catalina x86_64) built using the latest Brew version of SDL 2.0.18 too.

Output from ```show version```

```
VAXstation 3100 M38/GPX (KA42-B) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC Apple LLVM 12.0.0 (clang-1200.0.32.29)
        Simulator Compiled as C arch: x64 (Release Build) on Dec  6 2021 at 08:35:04
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.18, PNG Version 1.6.37, zlib: 1.2.11
        PCRE RegEx (Version 8.45 2021-06-15) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: libpcap version 1.9.1
        OS: Darwin maxi.localdomain 19.6.0 Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64 x86_64
        tar tool: bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
        curl tool: curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
        simh git commit id: c5cd38af
        simh git commit time: 2021-12-04T17:44:57-08:00
```

Firstly trying VAX/VMS V5.5-2 with GPX graphics enabled in the .ini file with

```
set va capture
set cpu modem=vaxstationgpx
```

the console boot screen appears and typing ```boot cpu``` to the SIMH console prompt starts the firmware
as expected in the graphics window.  After selecting the language as English, I type ```b``` and press Enter
 
![Screen Shot 2021-12-06 at 9 59 09 am](https://user-images.githubusercontent.com/5526341/144767841-a1aa8549-2c87-45f0-bd39-1d4cfb26a72e.png)

and see the start-up dialog on the graphics console.  When this completes, I can log in to DECwindows but I see some screen anomolies (extra pixels - the black dots in a ```$ show system``` output

![Screen Shot 2021-12-06 at 10 05 12 am](https://user-images.githubusercontent.com/5526341/144767930-f54fa3e4-0e29-4c8e-804e-df0c363449db.png)

and when I close a window (like the Bookreader Help) the screen redraw is borked -

![Screen Shot 2021-12-06 at 10 06 05 am](https://user-images.githubusercontent.com/5526341/144767941-718c8939-6dd7-4538-a814-6aff3b27004a.png)

As soon as I do a something that scrolls a DECterminal window fast (or even a ```$ set reply/enable/temp``` the SIMH console spews out a continual stream of 

```
Loading boot code from internal ka42b.bin
Unrecognized user event.
  type = 32768
  timestamp = 197780
  windowID = 22260320
  code = 10
  data1 = 0x0
  data2 = 0x0

SIMH has encountered a bug in SDL2.  An upgrade to SDL2
version 2.0.14 should fix this problem.
Unrecognized user event.
  type = 32768
  timestamp = 197780
  windowID = 22260320
  code = 10
  data1 = 0x0
  data2 = 0x0

SIMH has encountered a bug in SDL2.  An upgrade to SDL2
version 2.0.14 should fix this problem.
Unrecognized user event.
  type = 32768
  timestamp = 197780
  windowID = 22260320
  code = 10
  data1 = 0x0
  data2 = 0x0

SIMH has encountered a bug in SDL2.  An upgrade to SDL2
version 2.0.14 should fix this problem.
Unrecognized user event.
  type = 32768
  timestamp = 197780
  windowID = 22260320
  code = 10
  data1 = 0x0
  data2 = 0x0
```

I have to resort to macOS Force Quit to kill the vaxstation3100m38 process.

I also tried booting from a fully patched OpenVMS V7.3 system disk (in case this is a problem with the GPX driver on the old VAX/VMS V5.5-2 system) - and it has similar artifacts and symptoms.

I don't have the expertise to start debugging this under macOS (given I've onlly done relatively minor work using Xcode - and this is a command-line build using a makefile).

Perhaps since the original report was using Windows and Visual Studio - when you get SDL 2.0.18
working, the problem and fixes would be more obvious.

Mark - given you may be still recovering from your fall - this is not urgent - so take your time!

**Comment by markpizz** [comment]
Please try the latest code and if the "continuous" messages no longer appear, that's progress.  Let me know here. I think it might be fixed.  As for the mangled characters, that's a different issue which has been reported elsewhere.  I'm hoping the GPX author will fix that some day.

**Comment by pghardy** [comment]
Mark,

Any chance of getting the windows prebuilt binaries updated to include all these fixes? I don’t have access to my Windows or Pi build systems at present.

 

-- 

Paul  Hardy

Email:   ***@***.*** ***@***.***> , web: www.paulhardy.net <http://www.paulhardy.net/>

**Comment by sgcyphers** [comment]
I've been working at building new Windows binaries myself.  When I get one built, I will let you know.Visual Studio is a "little" more obtuse than MACRO-32  ;-O


Steve Cyphers


1090 Tanney Lane
Hudson, WI 54016
(612) 386-7642 - Cell
***@***.***

 

    On Thursday, January 20, 2022, 07:07:43 AM CST, Paul Hardy ***@***.***> wrote:  
 
 

Mark,

Any chance of getting the windows prebuilt binaries updated to include all these fixes? I don’t have access to my Windows or Pi build systems at present.

 

-- 

Paul Hardy

Email: ***@***.*** ***@***.***> , web: www.paulhardy.net <http://www.paulhardy.net/>

**Comment by agn453** [comment]
> Please try the latest code and if the "continuous" messages no longer appear, that's progress. Let me know here. I think it might be fixed. As for the mangled characters, that's a different issue which has been reported elsewhere. I'm hoping the GPX author will fix that some day.

Mark,  I just tried the latest code (under macOS Catalina now using an updated brew installed SDL 2.0.20) and the graphics console under DECwindows no long causes the cascade of SDL2 unrecognised user event messages.  Thanks.

**Comment by sgcyphers** [comment]
I succeeded in building the binaries from the 370bfe00 commit (the latest) and sent Paul an offline pointer to the code that I built. 

Paul responded saying that the new commit fixes Issue #1095:

Steve, I’ve tried the VAXstation from your build, and it works OK, avoiding the repeating messages bug. So thanks to Mark for that fix. **It does however still show the font corruption bug, so that still needs addressing.** 

On a related point, that build by Steve gives 22.6 VUPS on mu little Intel NUC, while the build I did previously using the build script in the main branch (using VS2008) only gives 16 VUPS. So Mark, can the default build instructions be changed to whatever Steve used?
 
I followed the build instructions in the Readme.md and windows-build-versions.txt in SIMH/windows-build.
I downloaded  https://github.com/simh/simh/archive/master.zip and windows_build.zip and expanded them in my project directory per RTFM.  (Always been a stickler for Reading The Furnished Manual.)
I used Visual Studio 2022 and used the SIMH.sln solutions file to build all of the binaries.  After a couple of bonehead mistakes ( I can't tipe worth doodah)  the build proceeded with now errors.   I only had space for the VAX binaries on my sgcyphers GitHub account, but I have all the emulators built for Windows.   *However*... I have not tested (other than the integrity checks in VS) any of the packages.  And even though *theoretically* the builds should be backwards compatible with previous versions of Windows, I will need to build some instances earlier than my Windows 10 (21H2)  system and TEST TEST TEST.

Let me know if there's anything else I can do to help

[message-text.txt](https://github.com/simh/simh/files/7917052/message-text.txt)
.

**Comment by markpizz** [comment]
FYI, the binaries built under VS2022 will surprise me if they work further back than Windows 10, unless you've managed to install VS2022 on whatever OS.  

The VS2008 binaries will run from XP onward without any VS version being installed.

**Comment by sgcyphers** [comment]
I defer to your expertise.  That's why I'm saying that my efforts **Really** need to be thoroughly tested on other Win32 versions.
I did install the VS2008Express with SP1, but I need to run the build a few more times and really dissect all of the logs to see what C/C++ version was actually used.  
I was just hoping to make Paul's and your life a little simpler for this fix. 
Not declaring victory just yet...

**Comment by pghardy** [comment]
Shouldn’t the Windows development binaries be rebuilt before this is closed?

-- 
Paul Hardy | 
15 Kentings, Comberton, Cambridge, UK |
M +44 7810  523 452 | T +44 1223 263 232 |
***@***.*** | www.pghardy.net |

On 22 Jan 2022, at 18:47, Mark Pizzolato ***@***.***> wrote:

﻿
Closed #1095.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by markpizz** [comment]
Closed by accident.  Thus I reopened it.  I'll rebuild the Windows Development binaries as soon as I clear up some of the disk related issues...

**Comment by markpizz** [comment]
> sim> SHOW VERSION

is useful to tell what compiler was used to build a simulator and whether it was built as a released or debug version.

What compiler produced the faster simulator vs the slower one?

**Comment by sgcyphers** [comment]
Working on that now .    As Mark predicted, the simulators built  with Visual Studio 2022 will not run on Windows XP.
On XP, I get "VAX8200.exe is not a valid Win32 application"  (Or any of the other simulators).
All of the Visual Studio 2022 compiled programs, so far, are running just fine on Windows 7 32-bit and Windows 7 64-bit.

I am now going to build Visual Studio 2008 Express on the Windows 7 system and test that code on Windows XP and verify that my build are functional.   (I wondered just how many people still use XP and if we could depreciate that platform, but that's not my call.)

Paul, if I get you a VS2008 compiled version of the VAXstation3100M38, would you mind running a test to see what the VUPS  rating is for VS2008 ?

Will post an update when I get some more test results.

**Comment by sgcyphers** [comment]
[VAXstation3100M38_VS2008.zip](https://github.com/simh/simh/files/7919778/VAXstation3100M38_VS2008.zip)

Here is the VAXstation3100M38 simulator that I was hoping you could test.
It was built on Windows 7 Pro 64-bit SP1 running Visual Studio Express 2008.  Built with build_vstudio.bat

The entire  build job had 6 failures (on my first attempt); 
   four were Hardware Core test (EVKAA) failures on VAX 11/780, 11/750, 8600 and 8200
   two were Runtime limit exceeded errors on PDP-8 and 3B2 DGMON SBD
I found out where the build logs go!!  They are .html files, not .log files.  This is Cool Stuff!!!
   And the error in the html log for VAX 11/780 is right after a LIBPCRE ROM BUILD.  I bet I missed something in my setup.

I'll do some digging and let you know when I get a clean build.

**Comment by sgcyphers** [comment]
Here is the relevant SHOW VERSION for the 'faster' simulator
F:\VAX.Alpha>vaxstation3100m38

VAXstation 3100 M38 (KA42-B) simulator V4.0-0 Current        simh git commit id: 370bfe00
sim> show version
VAXstation 3100 M38 (KA42-B) simulator V4.0-0 Current
  ...
    Host Platform:
        Compiler: Microsoft Visual C++ 19.30.30709.00
        Simulator Compiled as C arch: x86 (Release Build) on Jan 20 2022 at 20:30:20
        Build Tool: simh-Visual-Studio-Project

Side note.  I just tried to run the VS2008 version on WinXP and it Horked big time.  So, I still have compatibility issues too.
Thanks for your patience.



This is the SHOW VERSION for the version posted above that I know was compiled with VS2008 
(just built a clean PC today)
C:\SIMH_Test>vaxstation3100m38

VAXstation 3100 M38 (KA42-B) simulator V4.0-0 Current        simh git commit id: 370bfe00
sim> show version
VAXstation 3100 M38 (KA42-B) simulator V4.0-0 Current
   ...
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Jan 22 2022 at 21:10:11
        Build Tool: simh-Visual-Studio-Project
   ...
        simh git commit id: 370bfe00
        simh git commit time: 2022-01-16T07:44:15-08:00
sim>

**Comment by pghardy** [comment]
Slow version built by me (VS2008) - 16 VUPs

 

VAXstation 3100 M38 (KA42-B) simulator V4.0-0 Current        simh git commit id: 370bfe00

sim> sh version

VAXstation 3100 M38 (KA42-B) simulator V4.0-0 Current

    Simulator Framework Capabilities:

        64b data

        64b addresses

        Threaded Ethernet Packet transports:PCAP:NAT:UDP

        Idle/Throttling support is available

        Virtual Hard Disk (VHD) support

        RAW disk and CD/DVD ROM support

       Asynchronous I/O support (Lock free asynchronous event queue)

        Asynchronous Clock support

        FrontPanel API Version 12

    Host Platform:

        Compiler: Microsoft Visual C++ 15.00.30729.01

        Simulator Compiled as C arch: x86 (Debug Build) on Jan 20 2022 at 13:19:52

        Build Tool: simh-Visual-Studio-Project

        Memory Access: Little Endian

        Memory Pointer Size: 32 bits

        Large File (>2GB) support

        SDL Video support: SDL Version 2.0.10, PNG Version 1.6.37, zlib: 1.2.11

        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands

        OS clock resolution: 1ms

        Time taken by msleep(1): 1ms

        Ethernet packet info: WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)

        OS: Microsoft Windows [Version 10.0.19044.1466]

        Architecture: x86 on AMD64, Processors: 4

        Processor Id: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel, Level: 6, Revision: 3d04

        tar tool: bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp

        curl tool: curl 7.79.1 (Windows) libcurl/7.79.1 Schannel

        simh git commit id: 370bfe00

        simh git commit time: 2022-01-16T07:44:15-08:00

sim>

 

Faster version built by Steve  (VS2022) - 22 VUPs

 

 

VAXstation 3100 M38 (KA42-B) simulator V4.0-0 Current        simh git commit id: 370bfe00

sim> sh version

VAXstation 3100 M38 (KA42-B) simulator V4.0-0 Current

    Simulator Framework Capabilities:

        64b data

        64b addresses

        Threaded Ethernet Packet transports:PCAP:NAT:UDP

        Idle/Throttling support is available

        Virtual Hard Disk (VHD) support

        RAW disk and CD/DVD ROM support

        Asynchronous I/O support (Lock free asynchronous event queue)

        Asynchronous Clock support

        FrontPanel API Version 12

    Host Platform:

        Compiler: Microsoft Visual C++ 19.30.30709.00

        Simulator Compiled as C arch: x86 (Release Build) on Jan 20 2022 at 20:30:20

        Build Tool: simh-Visual-Studio-Project

        Memory Access: Little Endian

        Memory Pointer Size: 32 bits

        Large File (>2GB) support

        SDL Video support: SDL Version 2.0.20, PNG Version 1.6.37, zlib: 1.2.11

        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands

        OS clock resolution: 1ms

        Time taken by msleep(1): 1ms

        Ethernet packet info: WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)

        OS: Microsoft Windows [Version 10.0.19044.1466]

        Architecture: x86 on AMD64, Processors: 4

        Processor Id: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel, Level: 6, Revision: 3d04

        tar tool: bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp

        curl tool: curl 7.79.1 (Windows) libcurl/7.79.1 Schannel

        simh git commit id: 370bfe00

        simh git commit time: 2022-01-16T07:44:15-08:00

sim>

 

And the second build from Steve – VS2008 but fast again (22 VUPS)

 

 

VAXstation 3100 M38 (KA42-B) simulator V4.0-0 Current        simh git commit id: 370bfe00

sim> sh version

VAXstation 3100 M38 (KA42-B) simulator V4.0-0 Current

    Simulator Framework Capabilities:

        64b data

        64b addresses

        Threaded Ethernet Packet transports:PCAP:NAT:UDP

        Idle/Throttling support is available

        Virtual Hard Disk (VHD) support

        RAW disk and CD/DVD ROM support

        Asynchronous I/O support (Lock free asynchronous event queue)

        Asynchronous Clock support

        FrontPanel API Version 12

    Host Platform:

        Compiler: Microsoft Visual C++ 15.00.30729.01

        Simulator Compiled as C arch: x86 (Release Build) on Jan 22 2022 at 21:10:11

        Build Tool: simh-Visual-Studio-Project

        Memory Access: Little Endian

        Memory Pointer Size: 32 bits

        Large File (>2GB) support

        SDL Video support: SDL Version 2.0.20, PNG Version 1.6.37, zlib: 1.2.11

        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands

        OS clock resolution: 1ms

        Time taken by msleep(1): 1ms

        Ethernet packet info: WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)

        OS: Microsoft Windows [Version 10.0.19044.1466]

        Architecture: x86 on AMD64, Processors: 4

        Processor Id: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel, Level: 6, Revision: 3d04

        tar tool: bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp

        curl tool: curl 7.79.1 (Windows) libcurl/7.79.1 Schannel

        simh git commit id: 370bfe00

        simh git commit time: 2022-01-16T07:44:15-08:00

sim>

 

So the difference seems to be Release build v Debug build. I thought I used the instructions given and the .sln file – should that have built a debug build?

 

-- 

Paul  Hardy

web: www.paulhardy.net <http://www.paulhardy.net/>

**Comment by markpizz** [comment]
> So the difference seems to be Release build v Debug build. I thought I used the instructions given and the .sln file – should that have built a debug build?

If you used Visual Studio (Any Version) in GUI mode and opened the simh.sln file, the default build is Debug.  The GUI has a drop-down in the Tool Bar to select Release or Debug. 

If you used build_vstudio.bat, Release or Debug is the first argument as clearly specified in the build_vstudio.bat comments at the top of the file.

**Comment by markpizz** [comment]
> Side note. I just tried to run the VS2008 version on WinXP and it Horked big time. So, I still have compatibility issues too.

I've never heard the word "Horked".  It might seem like a misspelling of "Worked", but it sounds like you think it didn't work, so that would be confusing.  :-)

Meanwhile, the XP version that is expected to work on is the latest update from Microsoft (SP2 with all subsequent windows updates).  I have no idea about any earlier version.

I see:
```
C:\Documents and Settings\Tracy>.\vax

MicroVAX 3900 simulator V4.0-0 Current        git commit id: 39f2ab96
sim> show version
MicroVAX 3900 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Jan 23 2022 at 11:07:44
        Build Tool: simh-Visual-Studio-Project
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.20, PNG Version 1.6.37, zlib: 1.2.11
        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 2ms
        Ethernet packet info: WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_
20091008)
        OS: Microsoft Windows XP [Version 5.1.2600]
        Architecture: x86, Processors: 1
        Processor Id: x86 Family 6 Model 62 Stepping 4, GenuineIntel, Level: 6, Revision: 3e04
        git commit id: 39f2ab96
        git commit time: 2022-01-22T10:13:29-08:00
sim>
```

**Comment by sgcyphers** [comment]
Paul:  So the slower (16 VUP) build would be a debug version.  
I have been intentionally building release versions, and it's good to see that both release versions operate at the same rating.   So, I will focus on using VS2008 (C++ 15). My goal is to be able to reliably produce the packaged versions, for myself an anyone else that needs them.  I'm thinking that there are a lot of non-developers out there that aren't interested in going through the build process themselves but would use a pre-built version.  I would be good to get younger people interested in these legacy (and still superior) operating systems.  Most of us vintage computer geeks are getting old.
If I get good enough, I might to be able to even offload some of Mark's tasks.  He's up to his arse in alligators with maintaining the code base.

Horked  adj.  A computer system or program that is totally messed up.  (Coined by VAX geeks working in Minnesota circa 1985.)
 [Think of the sound a cat makes when throwing up a hairball...]

**Comment by markpizz** [comment]
I have explicitly held off on producing the Windows-Development-Binaries due to the fact that there are some active issues I'd rather not have less adventurous types mess with.  I expect sometime this coming week...

**Comment by sgcyphers** [comment]
Timing is up to you.  I'm still learning and would like to be useful in the future.

**Comment by pghardy** [comment]
Mark,

Yes, that seems to be the problem. I followed the instructions in 0ReadMe_Projects.txt which said:

“To build any of the supported simulators you should open the simh.sln file in this directory.”

 

So having followed the installation instructions for VS2008, I double clicked on the .sln file, and VS2008 opened up. I looked for a button to start a build, clicked on Build, and away it went.

 

It would be helpful to put a line in 0ReadMe_Projects.txt saying what you said below, and that people should use explicitly select Release build unless they have special need of Debug.

 

Thanks for all you do for SimH. If I were you, I’d ask Steve if he can take over the role of regularly building the Windows binaries!

 

Regards,

 

-- 

Paul  Hardy

web:  <http://www.pghardy.net> www.pghardy.net

**Comment by markpizz** [comment]
Updated Windows binaries are now available including the most recent updates.

**Comment by rcornwell** [comment]
I am still getting build errors on windows. 

8>SDL2-StaticD.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp__SetupDiDestroyDeviceInfoList@4 referenced in function _PLATFORM_hid_enumerate
8>SDL2-StaticD.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp__SetupDiGetDeviceRegistryPropertyA@28 referenced in function _PLATFORM_hid_enumerate
8>SDL2-StaticD.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp__SetupDiEnumDeviceInfo@12 referenced in function _PLATFORM_hid_enumerate
8>SDL2-StaticD.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp__SetupDiGetDeviceInterfaceDetailA@24 referenced in function _PLATFORM_hid_enumerate
8>SDL2-StaticD.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp__SetupDiEnumDeviceInterfaces@20 referenced in function _PLATFORM_hid_enumerate
8>SDL2-StaticD.lib(SDL_hidapi.obj) : error LNK2019: unresolved external symbol __imp__SetupDiGetClassDevsA@16 referenced in function _PLATFORM_hid_enumerate
8>..\BIN\NT\Win32-Debug\PDP6.exe : fatal error LNK1120: 6 unresolved externals

**Comment by markpizz** [comment]
The PDP6 builds cleanly using https://github.com/simh/simh.  What's changed in the sims repo?

**Comment by markpizz** [comment]
Changes were made to all of the Visual Studio Projects for additional library requirements when the new SDL support was added.  You missed those changes.

**Comment by rcornwell** [comment]
I am pulling down the windows build object from:  https://github.com/simh/windows-build/archive/windows-build.zip
The KA and KI also have similar errors. These started occurring about a month ago. Last successful build on Windows was Jan 9th. First failed build was Jan 29th. 

I build with sims\build_vstudio.bat DEBUG

Since there is a bug in SCP under RELEASE build. Perhaps there was some changes to build_vstudio.bat that I did not see.

**Comment by markpizz** [comment]
You only have to mess with the windows-build.zip file if you don't have a working git in your system.  You do have to update the .cmd files in the Visual Studio Projects directory when you pick up stuff from the simh master branch.   Like I said previously, when the new SDL2 version was adopted, it required at least one new dependent system library to be mentioned at link time.  There was a global change across all of the .proj files to address this.  You missed these changes.

I am unaware of any Release build problem with SCP on Visual Studio 2008.  There was a SDL problem using some moving target version of Visual Studio 2019 that had linking problems with SDL2.   The Visual Studio compiler produced incompatible object files which wouldn't work across different minor versions of Visual Studio 2019.  The latest SDL2 support includes libraries for the last version of VS2019 and the first version of VS2022.  We may have similar problems with newer VS2022 versions going forward.

**Comment by rcornwell** [comment]
Fixed it with addition of missing library. I can't pull down from two git repositories with Jenkins. So I pull down the zip file.

**Comment by markpizz** [comment]
You don't have to pull the widows-build repo.  You just need git to be available as a command on the system.  The Visual Studio Pre-build-Event.cmd script detects what's available or missing and if git is around, it picks up what's needed and dumps it where it belongs.

**Comment by rcornwell** [comment]
I was having trouble getting this to work correctly.
