### ISSUE TITLE
Windows can't boot TOPS-10 disk image

### ISSUE THREAD

**Issue by ThomasMConnors** [simh/simh#1118]
PDP10
sim> att rp0 dskb.dsk
RP0: No File System found on 'dskb.dsk', skipping autosizing

Yet the same disk will load fine in the Windows Linux subsystem usuing the 

 
Windows can't boot TOPS-10 disk image

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

Tom Connors

**Comment by markpizz** [comment]
Please notice that when you created your issue, you were asked to provide the output of SHOW VERSION from the sim> prompt.

Notice that mentioning a context where it "works" is a clearly running a different version (on Linux), so providing that would be useful comparative info so SHOW VERSION there would also be relevant.

Reopen this issue when you've provided this information.
