### ISSUE TITLE
pdp1 Lisp not starting as documented

### ISSUE THREAD

**Issue by KedalionDaimon** [simh/simh#1153]
Hi!

When I try to run PDP1 Lisp as supplied by the software kit, I should get:

sim> set cpu mdv
sim> load lisp.rim
sim> d extm_init 1
sim> run

HALT INSTRUCTION, PC: 002353 (CLA LAT CLI)

Instead, I get:

sim> set cpu mdv
sim> load lisp.rim
sim> d extm_init 1
sim> run

Unit not attached, PC: 007751 (RPB I)

And from there on, the tutorial in the SimH kit does not seem to apply any more: http://simh.trailing-edge.com/kits/lispswre.zip

Please advise. Lisp is one of the main applications for the PDP1.

**Comment by markpizz** [comment]
It works for me.  Did you notice the form you were presented with when you created this issue.  You completely missed providing any version information.

When I try with the latest commit in the master branch, I get what you said you expect!

```
PDP-1 simulator V4.0-0 Current        git commit id: d3f1ee09+uncommitted-changes
sim> set cpu mdv
sim> load lisp.rim
sim> d extm_init 1
sim> run

HALT instruction, PC: 002353 (CLA LAT CLI)
sim> d tw 7777
sim> c

HALT instruction, PC: 002357 (CLA LAT)
sim> d tw 400
sim> c

HALT instruction, PC: 000005 (STF6)
sim> d ss 2
sim> save lisp.sav
sim> c
(car (quote (a b c d)))
a
Simulation stopped, PC: 001133 (SZS5)
s```

**Comment by markpizz** [comment]
I get absolutely the same results when using the Ubuntu provided simh v3.8-1, Bob Supnik's latest 3.12-2, the latest in the master branch on both Ubuntu and Windows.

I get the same results when using the provided lisp.rim, or when creating it as described in the doc.

You've left out details about how you actually got the results you observed.  

Reopen this issue with more information if needed.

**Comment by KedalionDaimon** [comment]
Correct to close - sorry for not providing you with the version, it was on Ubuntu 22.04, v3.8, and then a lot of others, including such emulated on wine. But now, I cannot any longer reproduce the behaviour. (Possible cause - corrupt archive?)
