### ISSUE TITLE
Simh VAX Install rq0 with rauser=5000 works fine, install of OpenBSD 5.8 went fine, but upon rerunning drive is readonly

### ISSUE THREAD

**Issue by misterspock1** [simh/simh#1154]
Built Simh VAX on Bodhi Linux, an Ubuntu based distro on April 16th -- Configuration of a rauser=5000 drive  worked fine, the install from cd-rom of OpenBSD/VAX 5.8 went fine, but after restarting  and running the finished install simh reports that the file I created can only be mounted as read only. I tried setting the WRITEENABLED parameter, with no luck, then I tried set the device as an ra92, also no luck. Wondering if this is a bug, since no such issue occurred watching this: https://youtu.be/TAQ3Ufw-B0w I followed almost exactly only using OpenBSD 5.8 instead.   

Built it cloning this GIT repo and doing a 'make all'

![simh](https://user-images.githubusercontent.com/48235722/165871440-77d8ff9e-b33a-41b9-803a-cb89c7a255ec.jpg)

**Comment by markpizz** [comment]
Before I answer anything here authoritatively, where did you get the OpenBSD/VAX 5.8 install media?

**Comment by misterspock1** [comment]
http://iso.nl.netbsd.org/OpenBSD/5.8/vax/  File : install58.iso

Thanks for your prompt response!

**Comment by markpizz** [comment]
You didn't provide your configuration details in other than the subject.

If your configuration during install contained:

```
set rq0 rauser=5000
attach rq0 rauser5000.dsk
set rq1 cdrom
attach rq1 install58.iso
```
and you use the same configuration details in your operational configuration, (optionally removing the setup for rq1), then things don't fail in any way.

If you neglect to specify the drive type/size and run with a default drive specification (or a different drive type altogether), then the problem you describe appears.  The problem in the current codebase is that rauser sized drives do not properly autosize.

Had you used one of the many DEC drive types during your initial install, That type would have properly autosized without issue.
```
set RQn RD31                    Set RD31 Disk Type
set RQn RD32                    Set RD32 Disk Type
set RQn RD51                    Set RD51 Disk Type
set RQn RD52                    Set RD52 Disk Type
set RQn RD53                    Set RD53 Disk Type
set RQn RD54                    Set RD54 Disk Type
set RQn RA60                    Set RA60 Disk Type
set RQn RA81                    Set RA81 Disk Type
set RQn RA82                    Set RA82 Disk Type
set RQn RA70                    Set RA70 Disk Type
set RQn RA71                    Set RA71 Disk Type
set RQn RA72                    Set RA72 Disk Type
set RQn RA73                    Set RA73 Disk Type
set RQn RA90                    Set RA90 Disk Type
set RQn RA92                    Set RA92 Disk Type
set RQn RC25                    Set RC25 Disk Type
set RQn RCF25                   Set RCF25 Disk Type
set RQn RA80                    Set RA80 Disk Type
set RQn RF30                    Set RF30 Disk Type
set RQn RF31                    Set RF31 Disk Type
set RQn RF35                    Set RF35 Disk Type
set RQn RF71                    Set RF71 Disk Type
set RQn RF72                    Set RF72 Disk Type
set RQn RF73                    Set RF73 Disk Type
```

Autosizing of rauser disks will behave properly for all operating systems in the near future.

- Mark

**Comment by misterspock1** [comment]
Thanks! My initial configuration did indeed match yours above and the install worked fine, I think the autosizing was the issue. I defined an RA92 and now it works fine, albeit only 1.5 GB. Thanks for the help! You may close at your discretion.
