### ISSUE TITLE
How do I need to compile vaxstation4000m60 and vaxstation4000vlc to get VC and VE devices?

### ISSUE THREAD

**Issue by FreeBSD-pzn** [simh/simh#1157]
- #### Context
VAXstation 4000-60 (KA46) simulator V4.0-0 Current        git commit id: e1ce9f4f
sim> show dev
VAXstation 4000-60 (KA46) simulator configuration

CPU     idle disabled, model=VAXstation 4000-60 (KA46), Implementing: Base Instruction Group
        Emulating: Packed-Decimal-String-Group Extended-Accuracy-Group Emulated-Only-Group
TLB     2 units
ROM     
NVR     
NAR     MAC=08:00:2B:97:6F:50
WTC     time=vms
SYSD    
CLK     
OR      4 units
DZ      lines=4, lines=4
RZ      7 units
LK      disabled
VS      disabled
XS      

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
sim> show version
VAXstation 4000-60 (KA46) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 7.4.0
        Simulator Compiled as C arch: x64 (Release Build) on May  9 2022 at 02:12:57
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 2ms
        Ethernet packet info: libpcap version 1.8.1
        OS: FreeBSD bsdacer 11.2-RELEASE-p4 FreeBSD 11.2-RELEASE-p4 #0: Thu Sep 27 08:16:24 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
        tar tool: bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6
        curl tool: curl 7.64.1 (amd64-portbld-freebsd11.2) libcurl/7.64.1 OpenSSL/1.0.2o zlib/1.2.11 libidn2/2.1.1 nghttp2/1.38.0
        git commit id: e1ce9f4f
        git commit time: 2022-05-01T08:01:18+1000

**Comment by markpizz** [comment]
When you built these simulators, the makefile would emit various messages that should have answered this question.  The commit template suggested that you should provide that output which you didn't provide.
