### ISSUE TITLE
set RQx unit=y gives "Plug y already in use on RQy" even if RQy is disabled

### ISSUE THREAD

**Issue by jwbrase** [simh/simh#1158]
When running vax8600 (pulled and built from master today), the command:

set RQx unit=y 

results in the error:

"Plug y already in use on RQy" 

for all values of y less than the maximum number of RQ drives allowed (254 drives, so everything up to unit=253 fails). This occurs even when RQy hasn't been enabled with "set RQ drives=z" (with z > y).

Arguably, this is correct behavior, because the alternative raises the sticky question of "what happens if the next line after set 'RQx unit=y' is 'set RQ drives=z?".

However, this means that if one does have to change a unit number (for example, to ensure uniqueness of unit numbers for drives within an alloclass for VMS), one has to first free up the desired unit number, even if one does not have that many drives enabled. This is exacerbated by the fact that trying to change the plug number on a disabled drive results in:

"%SIM-ERROR: Unit disabled: RQn"

So one first has to enable drives up to the desired unit number, then change the unit number on the drive occupying that unit number, then change the drive one originally wanted to change, then disable any unwanted drives.

Two possible solutions:

1) Allow unit numbers to be changed for disabled drives. Some juggling will still be necessary, but at least enabling/disabling drives won't be part of the process.

2) Allow enabled drives to be assigned unit numbers that would be the default number for disabled drives. If a drive is enabled while its default unit number is in use, keep it disabled until its unit number is changed, emitting a warning (or perhaps a WARNING with a ^G for good measure to get the user's attention).

**Comment by markpizz** [comment]
You are acting like there is a shortage of unit numbers (i.e. plugs).

On any given MSCP controller there can be as many as 254 drives.  EACH of those drives can have a unit number ranging from 0 thru 65534.  None can be duplicated.

> set RQx unit=y
>
> results in the error:
>
> "Plug y already in use on RQy"
>
> for all values of y less than the maximum number of RQ drives allowed (254 drives, so everything up to unit=253 fails). This occurs even when RQy hasn't been enabled with "set RQ drives=z" (with z > y).
> Arguably, this is correct behavior, because the alternative raises the sticky question of "what happens if the next line after set 'RQx unit=y' is 'set RQ drives=z?".

Correct, and the requirement is driven by how the simulator framework (SCP) manages the concepts of units and their configuration for all simulators not just this one.

> However, this means that if one does have to change a unit number (for example, to ensure uniqueness of unit numbers for drives within an alloclass for VMS), one has to first free up the desired unit number, even if one does not have that many drives enabled. 

More than 95% of the available unit plugs are unused at any time.  You are indeed burdened to pick one that isn't already dedicated.

> Allow unit numbers to be changed for disabled drives. Some juggling will still be necessary, but at least enabling/disabling drives won't be part of the process.

Not going to happen.  The command parsing logic which manages the concept of changing unit attributes is deep within the simulator framework (SCP) and is not specific to the RQ device implementation.  Similarly the logic which enables/disables units is also in the framework and doesn't involve any interactions with the logic in the device simulation code (RQ).

Feel free to use unit plugs which aren't already in use.  

> Allow enabled drives to be assigned unit numbers that would be the default number for disabled drives. If a drive is enabled while its default unit number is in use, keep it disabled until its unit number is changed, emitting a warning (or perhaps a WARNING with a ^G for good measure to get the user's attention).

Getting your configuration right is indeed your problem as it was in real hardware.  Sorry for the subtle differences.  
Note that there is no extra charge for the whole pallet of unused unit plugs that come with each controller. :-)

Most folks store the details of their configuration in a file which gets executed on simulator startup.  This file can be of arbitrary size.  They don't usually do significant multiple step configuration changes by hand.

**Comment by jwbrase** [comment]
>You are acting like there is a shortage of unit numbers (i.e. plugs).
>
>On any given MSCP controller there can be as many as 254 drives. EACH of those drives can have a unit number ranging from 0 thru 65534. None can be duplicated.

I'd noticed that SIMH makes that range of plug numbers available, but in reading VMS documentation I'd somehow gotten the impression that VMS expected plug numbers in the range 0-255. Reading back over things, I think I may have confused it with the range of valid alloclasses. 

> More than 95% of the available unit plugs are unused at any time. You are indeed burdened to pick one that isn't already dedicated.

Fair enough, see above. If the range I thought I'd absorbed from the VMS documentation were adquate, however, there would be only two available plug values.

> Most folks store the details of their configuration in a file which gets executed on simulator startup. This file can be of arbitrary size. They don't usually do significant multiple step configuration changes by hand.

So do I, but it still would be a bit silly to have to include multiple extra lines in every config that touched the unit numbers if there were indeed only 255 plug numbers that would actually be recognized, 253 of which were used.
