### ISSUE TITLE
The maintainer of this repo has hijacked the project and relicensed it under a closed source license https://groups.io/g/simh/topic/new_license/91108560

### ISSUE THREAD

**Issue by hormelcookies** [simh/simh#1161]
The maintainer of this repository has betrayed the trust of the community and has decided to unilaterally relicense it under a closed-source, restrictive license. Fork this now.

Look here for all the gory details:
https://groups.io/g/simh/topic/new_license/91108560

**Comment by AlanSmitheeJr** [comment]
I assume the community will want to review the notes that the maintainer's lawyer provided him when drafting the license addendum before deciding whether or not to create a true community for. I hope that these notes will demonstrate the legal basis on which these license changes are being performed.

Given their previous responsiveness to the community, I'd expect the maintainer will be providing these shortly.

**Comment by markpizz** [comment]
You are free to read the LICENSE.txt which describes what has changed.  

This codebase (in the master branch) is fully available for anyone who wants to use it unmodified.  

If someone wants to change any aspect of the code or add to it with the exception of the code which implements or manages the AUTOSIZE functionality you are also free to do that.

If someone "needs" to change some aspect of the how the AUTOSIZE functionality is implemented or operates, they are free to do that,  However, they will then not be licensed to any change authored by ME after the original additional of the LICENSE.txt.

I am specifically asserting license conditions on MY changes AFTER as long as then they can do anything with anything in the codebase that existed prior to the addition of the LICENSE.txt along with any changes after that that are authored by anyone by me.

**Comment by AlanSmitheeJr** [comment]
@markpizz:

You've come up with an interesting solution to a problem that seems to boil down to people harassing and criticizing you over design decisions, etc, and you having better things to do than to deal with those disagreements when you could be coding or contributing to the project in other ways. Any person with the requisite skill could remove and/or replace your future contributions and go on their merry way, including community forks and whatnot.

I'm curious as to the enforceability of these clauses--does the lawyer who drafted them specialize in open source licenses, or software licenses in general? I've worked with IP lawyers in the past on various issues (FLOSS licensing, patent procurement, etc) and it does seem to be a rather specialized field. I'd suggest you ask them to write something up and clarify on points of enforceability and in which jurisdiction these clauses will be considered valid. Or, if this is a matter of true concern to you, obtain a second opinion. As you know, copyright does not merely consider parts of a work, but the totality as well, and given that the work has many copyright holders associated with it, there may be some subtleties that the random whiners out there haven't yet grasped.

**Comment by wfjm** [comment]
@AlanSmitheeJr tried to shed some light on what's behind this move.  
The net effect is what I wrote in #1163: "_SimH is no longer a FOSS project_".  
The license effectively declares two files as proprietary.  
And declares a single person as guardian of these files.  

Clauses like this are an _absolute no go_ in an open source project.  
If this isn't corrected, SimH has ceased being an open source project with commit ce2adce6.

**Comment by AlanSmitheeJr** [comment]
@wfjm: SimH is @markpizz's personal project, no? He started the repo and put countless hours and commits into it. If he wants to make unilateral changes to the license file, why not? Provided he's covered all his legal bases and ensured his addendums do not violate various legal requirements that would render the license unenforcible--he's an expert in the community, I have every faith he's retained an equally expert legal counsel for this determination--I don't see why people are complaining? Anyone can make a copy of SimH whenever they like and do what they will with it under the old license.

People need to be calm, rational, and mature about this. This repository is for people like @markpizz, not haters who maliciously criticize someone like Mark and cannot abide his decisions and explicitly force him into these kinds of actions.

**Comment by wfjm** [comment]
@AlanSmitheeJr wrote

> He (@markpizz) started the repo ...

Yes, @markpizz started the GitHub Repo, but at hour-0 it contained the code written by Bob Supnik and others. So he has started this repo, and certainly put countless hours into it, but he definitely didn't start the project. That was Bob.

> If he wants to make unilateral changes to the license file, why not?

See above. SimH was a community project, also at Bob's time, with essential contributions from several persons. And in this situation it is, mildly phrased, highly problematic if one author changes the license and declares some code private, and splits the _persons who use_ into obedient and non-obedient.

> I don't see why people are complaining?

I do complain, reason see #1163. With this license SimH is no longer a FOSS project, and that has consequences.

> People need to be calm, rational, and mature about this.

I'm calm and rational. See #1163. Of course there were massive quarrels which led to this move. But this move is destructive, as it converts SimH from a FOSS project into a strange hybrid where the code is open, but some is proprietary.

**Comment by markpizz** [comment]
If you read the original license (indented in the LICENSE.txt file).  Me or anyone else can do absolutely anything at all with the original code.

According to Copyright law, everything that someone creates or makes changes to a copyrightable work has specific copyright entitlement on its own.  The changes to a prior work are separately copyrightable.

Given that, since it is my "work", I can specify any license terms I want.  Those specific terms are spelled out in the additional paragraphs at the end.

The 600% increase in the code size over the past 11 years was my work all licensed under the original BSD style license.  My changed license terms only affect MY future contributions throughout the project and the constraints only apply if specific changes personally "need" to be made by someone who wants to use the software.  

@AlanSmitheeJr, If you want to engage an IP lawyer to validate or invalidate what's been done, please do.

As for the assessment by @wfjm that what is in this repository is no longer FOSS, under the precise definition of FOSS, that is true for what is at the head of the the master branch.  Everything in the repo specifically before ce2adce is absolutely FOSS and folks are free to do anything they want with it.  Folks are free to do almost anything with what's at the head of the master branch also, so long as they specifically follow the terms in the LICENSE.txt. 

If @wfjm or anyone else, that doesn't have the previously mentioned "need", isn't comfortable with using the constraints of the no longer clearly defined FOSS software, feel free to use any version prior to the introduction of the LICENSE.txt.

**Comment by wfjm** [comment]
@markpizz mentioned _copyright_.  For the purpose of this discussion lets ignore that the legal term _copyright_ is defined quite differently in different countries, and focus on that a copyright disclaimer is usually added to indicate _authorship_.

I scanned the `*.[ch]` files of the current SimH code base, that are 1025 files, for the string `Copyright (c)`. That was done case blind. I found 1025 lines. I ignore disclaimers associated to
```
    Copyright (c) AdaCore
    Copyright (C) Free Software Foundation,
    Copyright (C) Regents of the University of California.
```
and end up with the following list, sorted alphabetically by author name, with the file count
```
    Copyright (c) Robert Armstrong          -->   6
    Copyright (c) Bruce Baumgart            -->   1
    Copyright (c) William A. Beech          -->  61
    Copyright (c) Fabrice Bellard           -->   4
    Copyright (c) James C. Bevier           -->  16
    Copyright (c) Philip L. Budne           -->  16
    Copyright (c) Matt Burke                -->  81
    Copyright (c) Lars Brinkhoff            -->  42
    Copyright (c) Leonid Broukhis           -->  14
    Copyright (c) J. David Bryan            -->  68
    copyright (c) William C. Colley, III    -->   1
    Copyright (c) Richard Cornwell          -->  89
    Copyright (c) Magnus Damm               -->   1
    Copyright (c) John A. Dundas III        -->   4
    Copyright (C) Marat Fayzullin           -->   1
    Copyright (c) John Forecast             -->  16
    Copyright (c) Danny Gasparovski.        -->  17
    Copyright (c) Douglas A. Gwyn           -->   3
    Copyright (c) Howard M. Harte           -->  31
    Copyright (c) David T. Hittner          -->   9
    Copyright (C) Jim Hudgens               -->   5
    Copyright (c) Robert M. A. Jarratt      -->   1
    Copyright (c) Patrick Linstruth         -->   3
    Copyright (c) Hans-Ake Lund             -->   4
    Copyright (c) Bill McDermith            -->   1
    Copyright (c) Todd C. Miller            -->   1
    Copyright (c) Seth J. Morabito          -->  51
    Copyright (c) Gerardo Ospina            -->   3
    Copyright (c) Charles E. Owen           -->  15
    Copyright (c) Mark Pizzolato            -->  20
    Copyright (c) David G. Pitts            -->   1
    Copyright (c) Ken Rector                -->   2
    Copyright (c) Roberto Sancho            -->   7
    Copyright (c) Peter Schorn.             -->  12
    Copyright (c) Jes Sorensen              -->   1
    Copyright (c) Klaus Stengel             -->   1
    Copyright (c) Robert M. Supnik          --> 357
    copyright (C) Simon Tatham              -->   4
    Copyright (c) Holger Veit               -->  32
    Copyright (c) Serge Vakulenko           -->   9
```

If one sorts that list according to file count one gets
```
    Copyright (c) Robert M. Supnik          --> 357
    Copyright (c) Richard Cornwell          -->  89   @rcornwell
    Copyright (c) Matt Burke                -->  81
    Copyright (c) William A. Beech          -->  61   @nj7p
    Copyright (c) J. David Bryan            -->  68
    Copyright (c) Seth J. Morabito          -->  51   @sethm
    Copyright (c) Lars Brinkhoff            -->  42   @larsbrinkhoff
    Copyright (c) Holger Veit               -->  32
    Copyright (c) Howard M. Harte           -->  31   @hharte
    Copyright (c) Mark Pizzolato            -->  20
    Copyright (c) Danny Gasparovski.        -->  17
    Copyright (c) John Forecast             -->  16   @JohnForecast
    Copyright (c) James C. Bevier           -->  16
    Copyright (c) Philip L. Budne           -->  16   @philbudne
    Copyright (c) Charles E. Owen           -->  15
    Copyright (c) Leonid Broukhis           -->  14   @leobru
    Copyright (c) Peter Schorn.             -->  12   @psco
    Copyright (c) David T. Hittner          -->   9
    Copyright (c) Serge Vakulenko           -->   9
    Copyright (c) Roberto Sancho            -->   7
    Copyright (c) Robert Armstrong          -->   6
    Copyright (C) Jim Hudgens               -->   5
    Copyright (c) Fabrice Bellard           -->   4
    Copyright (c) John A. Dundas III        -->   4
    Copyright (c) Hans-Ake Lund             -->   4
    copyright (C) Simon Tatham              -->   4
    Copyright (c) Douglas A. Gwyn           -->   3
    Copyright (c) Patrick Linstruth         -->   3
    Copyright (c) Gerardo Ospina            -->   3   @ngospina
    Copyright (c) Ken Rector                -->   2
    Copyright (c) Bruce Baumgart            -->   1    
    copyright (c) William C. Colley, III    -->   1
    Copyright (c) Magnus Damm               -->   1
    Copyright (C) Marat Fayzullin           -->   1
    Copyright (c) Robert M. A. Jarratt      -->   1
    Copyright (c) Bill McDermith            -->   1
    Copyright (c) Todd C. Miller            -->   1
    Copyright (c) David G. Pitts            -->   1
    Copyright (c) Jes Sorensen              -->   1
    Copyright (c) Klaus Stengel             -->   1
``` 
I'm fully aware that counting `Copyright (c)` disclaimers doesn't reflect size and depth of contribution. But is clearly indicates, that SimH is a community project.

**Comment by wfjm** [comment]
@markpizz wrote
> Given that, since it is my "work", I can specify any license terms I want. Those specific terms are spelled out in the additional paragraphs at the end.

This is a dangerous logic. What will you do if other authors are equally determined about their contributions ?

The license of an open source project simply should not contain author names or even files names. That Bob's name appeared in the initial license had very specific reasons rooted in his position at DEC at the time. A very very special case.

**Comment by wfjm** [comment]
@rcornwell  @9track @nj7p @sethm @larsbrinkhoff @hharte @JohnForecast @AZBevier @philbudne @leobru @psco @sergev @rsanchovilla @SpareTimeGizmos @ngospina: unless already informed, this issue is of relevance for you.

**Comment by larsbrinkhoff** [comment]
@wfjm, thanks for the heads up.  I think most people already know.  It has been discussed at length on the mailing list as well.

**Comment by masinter** [comment]
I recently got some pointers to a framework for open source software sustainability, done by people who care about the long-term.  [Open Source Software Models of Collaboration & Sustainability](https://www.lyrasis.org/programs/Pages/IMLS-OSS.aspx) 
It might be too late for a "can't we all just get along" moment, but perhaps there's a perspective where different future governance models for the 'simh' project can be discussed.

**Comment by Alhadis** [comment]
> Given that, since it is my "work", I can specify any license terms I want.

Can I ask what motivated this change? What problem(s) are you trying to solve by deviating from an OSI-approved license such as MIT/ISC, GPL, Apache, et al?

Because irrespective of the new conditions, this can have far-flung effects on any project that derives or depends on SimH. Many projects with strict licensing requirements will flat-out refuse to deal with any software encumbered by ambiguous or unvetted license terms. Hence why most projects adopt a ["standard" license](https://spdx.org/licenses/) with an SPDX identifier and OSI/FSF-approval.
