### ISSUE TITLE
Does not build under Arch Linux (GCC 12.2.0)

### ISSUE THREAD

**Issue by calmsacibis995** [simh/simh#1164]
- #### how you built the simulator or that you're using prebuilt binaries
grep: warning: stray \ before -
lib paths are: /usr/lib/ /usr/lib/libfakeroot/ /lib/
include paths are:  /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include /usr/local/include /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include-fixed /usr/include
using libm: /usr/lib/libm.so
using librt: /usr/lib/librt.a
using libpthread: /usr/lib/libpthread.a /usr/include/pthread.h
using libpcre: /usr/lib/libpcre.so /usr/include/pcre.h
using libedit: /usr/lib/libedit.so /usr/include/editline/readline.h
using semaphore: /usr/include/semaphore.h
using libdl: /usr/lib/libdl.a /usr/include/dlfcn.h
using libpng: /usr/lib/libpng.so /usr/include/png.h
using zlib: /usr/lib/libz.so /usr/include/zlib.h
using mman: /usr/include/sys/mman.h
using libpcap: /usr/include/pcap.h
***
*** 3b2 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 12.2.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
*** - Per simulator tests will be run.
***
*** git commit id is 32bafbb245de6805e1d8baac6664ec1f13e33e3b.
*** git commit time is 2022-10-26T16:44:58-0700.
***
sim_BuildROMs.c: In function ‘main’:
sim_BuildROMs.c:453:13: warning: implicit declaration of function ‘unlink’ [-Wimplicit-function-declaration]
  453 |             unlink (ROMs[i].IncludeFileName);
      |             ^~~~~~
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -DSIM_GIT_COMMIT_ID=32bafbb245de6805e1d8baac6664ec1f13e33e3b -DSIM_GIT_COMMIT_TIME=2022-10-26T16:44:58-0700  -DSIM_COMPILER="GCC Version: 12.2.0" -DSIM_BUILD_OS_VERSION="Linux zerocool32-eos 6.0.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64 GNU/Linux" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCRE_H -DHAVE_LIBEDIT -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DSIM_HAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./3B2/3b2_cpu.c ./3B2/3b2_sys.c ./3B2/3b2_rev2_sys.c ./3B2/3b2_rev2_mmu.c ./3B2/3b2_rev2_mau.c ./3B2/3b2_rev2_csr.c ./3B2/3b2_rev2_timer.c ./3B2/3b2_stddev.c ./3B2/3b2_mem.c ./3B2/3b2_iu.c ./3B2/3b2_if.c ./3B2/3b2_id.c ./3B2/3b2_dmac.c ./3B2/3b2_io.c ./3B2/3b2_ports.c ./3B2/3b2_ctc.c ./3B2/3b2_ni.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -DUSE_INT64 -DUSE_ADDR64 -DREV2 -I ./3B2 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -o BIN/3b2 -lm -lrt -lpthread -lpcre -ledit -ldl -lpng -lz  
./scp.c: In function ‘show_version’:
./scp.c:6954:72: error: macro "S_str" passed 2 arguments, but takes just 1
 6954 |         char buildosversion[2*PATH_MAX+1] = S_xstr(SIM_BUILD_OS_VERSION);
      |                                                                        ^
./scp.c:6758: note: macro "S_str" defined here
 6758 | #define S_str(a) #a
      | 
./scp.c:6757:19: error: ‘S_str’ undeclared (first use in this function)
 6757 | #define S_xstr(a) S_str(a)
      |                   ^~~~~
./scp.c:6954:45: note: in expansion of macro ‘S_xstr’
 6954 |         char buildosversion[2*PATH_MAX+1] = S_xstr(SIM_BUILD_OS_VERSION);
      |                                             ^~~~~~
./scp.c:6757:19: note: each undeclared identifier is reported only once for each function it appears in
 6757 | #define S_xstr(a) S_str(a)
      |                   ^~~~~
./scp.c:6954:45: note: in expansion of macro ‘S_xstr’
 6954 |         char buildosversion[2*PATH_MAX+1] = S_xstr(SIM_BUILD_OS_VERSION);
      |                                             ^~~~~~
make: *** [makefile:2814: BIN/3b2] Error 1

- #### the simulator configuration file (or commands) which were used when the problem occurred.
simh didn't build

- #### the expected behavior and the actual behavior
look above

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Thank you for this report.

The minor warning about unlink will be fixed later today.  The real problem is the second issue.

I'll try to adjust the makefile to accommodate the output of "uname -a" which on Arch Linux has a comma in the result (as part of the date stamp).  Other Linux distro's produce a very similar output for `uname -a`, but they avoid a comma in the result string...

Your Arch Linux produces:
```
Linux zerocool32-eos 6.0.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64 GNU/Linux
```
On Fedora 36:
```
Linux localhost-live.lan 5.19.16-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 16 22:50:04 UTC 2022 x86_x64 x86_64 x86_64 GNU/Linux
```
On Fedora 37:
```
Linux localhost-live.lan 5.19.16-301.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 21 15:55:37 UTC 2022 x86_x64 x86_64 x86_64 GNU/Linux
```

You may want to report the presence of the comma in the "uname -a" output upstream to the Arch Linux folks.
Likewise for the Hyper-V booting  crash. 

![Hyper-V-ArchLinux](https://user-images.githubusercontent.com/422671/198369822-6aa53e8f-4c32-4587-9c4f-1de64014f2d8.png)
