### ISSUE TITLE
microvax2 HELP ROM info partially outdated/wrong

### ISSUE THREAD

**Issue by vaxorcist** [simh/simh#1171]
microvax2 simulator HELP ROM info partially outdated/wrong: 

$ ./microvax2

MicroVAX II (KA630) simulator V4.0-0 Current        git commit id: 13164825
sim> sh ver
MicroVAX II (KA630) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 15
    Host Platform:
        Compiler: GCC 10.2.1 20210110
        Simulator Compiled as C arch: x64 (Release Build) on Apr  9 2023 at 08:36:35
        Build Tool: simh-makefile-single-compile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.14, PNG Version 1.6.37, zlib: 1.2.11
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: NAT, TAP, UDP, PCAP: libpcap version 1.9.0-PRE-GIT (with TPACKET_V3)
        OS: Linux think 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
        Processor Name: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
        tar tool: tar (GNU tar) 1.34
        curl tool: curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
        git commit id: 13164825
        git commit time: 2023-04-06T12:30:21-10:00
sim> 

The following microvax2 HELP passage is 
a) outdated (it describes the old mechanism of loading the boot ROM file from the current working directory if not loaded by "LOAD -R ...")
b) names a wrong boot ROM file name (ka655x.bin instead of ka630.bin)

"When the simulator starts running (via the BOOT command), if the ROM has
not yet been loaded, an attempt will be made to automatically load the
ROM image from the file ka655x.bin in the current working directory.
If that load attempt fails, then a copy of the missing ROM file is
written to the current directory and the load attempt is retried."

**Comment by markpizz** [comment]
Try now with the latest code.

Note: Someone could build with ```make DONT_USE_ROMS=1``` if, for some reason they didn't want build-in ROMs in the simulator binaries.  In this case, a somewhat different HELP ROM output is produced, user while operation is essentially unchanged.

**Comment by vaxorcist** [comment]
Fixed, perfect!
A HELP can be very irritating when not describing what really happens ...
Thanks a lot.
