### ISSUE TITLE
fis11 fac get_exp

### ISSUE THREAD

**Issue by Joonio** [simh/simh#1176]
In function fis11 (PDP11 VM) before passing arguments to operation function GET_EXP parameter must be fac.h

if (GET_SIGN (fac.h) && (GET_EXP (fac.l) == 0))
    fac.h = fac.l = 0;

**Comment by markpizz** [comment]
Your comments here needs more thorough explanation and some example data to show the problem.  Please elaborate.  Thanks.

**Comment by Joonio** [comment]
When using fis commands, if the first operand is less than zero, it is reset to zero. When getting the exponent, the wrong data field "l" is used instead of "h".

**Comment by Joonio** [comment]
PROGRAM FF;
VAR
      F:REAL;
BEGIN
      F:=-1.0 + 1.0;
      WRITELN(F);
END.

The program output is : 1.0

**Comment by Joonio** [comment]
![Uploading image.PNG…]()

**Comment by rms47** [comment]
Quite right. The indicated line should be

if (GET_SIGN (fac.h) && (GET_EXP (fac.h) == 0))
    fac.h = fac.l = 0;

Good catch.

**Comment by markpizz** [comment]
@Joonio 
Your fix is now part of Bob's just released simh v3.12-4 and is in the master branch here in this repo.

Thanks for reporting this.

**Comment by Joonio** [comment]
Good job.
