### ISSUE TITLE
simh build error (openSUSE Tumbleweed, GCC 13.1.1)

### ISSUE THREAD

**Issue by calmsacibis995** [simh/simh#1179]
- #### Context
I attempted to build the `vax780` simulator on openSUSE.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
- I didn't manage to build the simulator.

- #### how you built the simulator or that you're using prebuilt binaries
- I only chose to build the `vax780` simulator.

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior
Expected: simh to build sucessfully.
In reality: See the error messages below.

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem
- Compiler output:
- `sim_fio.c: In function ‘_check_source_check_file’:
sim_fio.c:2494:12: error: unknown type name ‘pcre’
 2494 |     static pcre *sys_include_re = NULL;
      |            ^~~~
sim_fio.c:2495:12: error: unknown type name ‘pcre’
 2495 |     static pcre *local_include_re = NULL;
      |            ^~~~
sim_fio.c:2496:12: error: unknown type name ‘pcre’
 2496 |     static pcre *sim_sock_re = NULL;
      |            ^~~~
sim_fio.c:2506:23: error: implicit declaration of function ‘pcre_compile’ [-Werror=implicit-function-declaration]
 2506 |         sim_sock_re = pcre_compile ("\\#\\s*include\\s+\\\"sim_sock\\.h\"", 0, &errmsg, &erroffset, NULL);
      |                       ^~~~~~~~~~~~
sim_fio.c:2506:21: error: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
 2506 |         sim_sock_re = pcre_compile ("\\#\\s*include\\s+\\\"sim_sock\\.h\"", 0, &errmsg, &erroffset, NULL);
      |                     ^
sim_fio.c:2510:14: error: implicit declaration of function ‘pcre_exec’ [-Werror=implicit-function-declaration]
 2510 |         rc = pcre_exec (sim_sock_re, NULL, data, (int)FileSize, startoffset, PCRE_NOTBOL, ovec, 6);
      |              ^~~~~~~~~
sim_fio.c:2510:78: error: ‘PCRE_NOTBOL’ undeclared (first use in this function)
 2510 |         rc = pcre_exec (sim_sock_re, NULL, data, (int)FileSize, startoffset, PCRE_NOTBOL, ovec, 6);
      |                                                                              ^~~~~~~~~~~
sim_fio.c:2510:78: note: each undeclared identifier is reported only once for each function it appears in
sim_fio.c:2511:19: error: ‘PCRE_ERROR_NOMATCH’ undeclared (first use in this function)
 2511 |         if (rc == PCRE_ERROR_NOMATCH)
      |                   ^~~~~~~~~~~~~~~~~~
sim_fio.c:2520:26: error: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
 2520 |         local_include_re = pcre_compile ("\\#\\s*include\\s+\\\"(.+)\\\"", 0, &errmsg, &erroffset, NULL);
      |                          ^
sim_fio.c:2539:24: error: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
 2539 |         sys_include_re = pcre_compile ("\\#\\s*include\\s+\\<(.+)\\>", 0, &errmsg, &erroffset, NULL);
      |                        ^
cc1: all warnings being treated as errors`

**Comment by markpizz** [comment]
Please provide the complete output produced by make when you try to build the vax780 simulator.

Thanks.

**Comment by markpizz** [comment]
Try with the latest from github.com/simh/simh master branch.

**Comment by calmsacibis995** [comment]
OK, now it compiles.
