### ISSUE TITLE
build fails due to pointer mismatch in sim_disk.c

### ISSUE THREAD

**Issue by jdbruner** [simh/simh#1184]
Line 2910 of sim_disk.c contains a pointer mismatch in the conditional expression for the second argument to ``sim_vhd_disk_set_dtype``:
```c
sim_vhd_disk_set_dtype (uptr->fileref, uptr->drvtyp ? uptr->drvtyp->name : f->DriveType, ctx->sector_size, ctx->xfer_encode_size, ctx->media_id, uptr->dptr->name, uptr->dptr->dwidth);
```
``uptr->drvtyp->name`` is a ``char *`` but ``f->DriveType`` is a ``uint8 []``  

The second argument to the function should be a ``char *``, so the apparent fix is a cast ``(char *)f->DriveType``

**Comment by markpizz** [comment]
Thanks for pointing this out.  It had already been fixed locally but was part of other significant changes, which needed a little more polish and now are part of the master branch.
