### ISSUE TITLE
Code Quality Measures and Potential Integration with Analysis Tool

### ISSUE THREAD

**Issue by cmiller321** [simh/simh#1198]
Hi, sorry for making an issue, but I'm interested to know if there's any code quality inspection or static analysis implemented in this repository. A quick look at the files tells me that there isn't. If my understanding is correct and there isn't any inspection or analysis currently, would integration with a free and open-source tool such as SonarCloud be considered favorably?

**Comment by rcornwell** [comment]
Coverity scan used to be setup.

**Comment by markpizz** [comment]
SonarCloud's service is only free for smaller projects (100K lines of code).  Many of the 78 simulators are each in excess of 150K lines).

**Comment by cmiller321** [comment]
Well, darn. Scanning might make more sense individually on case-by-case basis then. Thank you for the responses.
