### ISSUE TITLE
Simh not resetting condition codes bits in vax calls and callg

### ISSUE THREAD

**Issue by gnudles** [simh/simh#1200]
https://github.com/simh/simh/blob/670a3728ad67d44f87820a8bb21830139c4d778a/VAX/vax_cpu1.c#L375
According to online documentation, the op codes of CALLG and CALLS in VAX processor should reset the Z, N, V, C flags. I guess it is too harsh to do such critical change, that can have unknown results.

**Comment by rms47** [comment]
It does.

    case CALLS:
        cc = op_call (opnd, TRUE, acc);
        break;

    case CALLG:
        cc = op_call (opnd, FALSE, acc);
        break;

The last line of op_call is

        return 0; 

The only other exits from op_call are a reserved operand fault or a memory fault. In either case, the condition codes should not be changed.

**Comment by markpizz** [comment]
If you look closely at ALL the code, the cc value is kept in a separate variable during instruction execution and only pressed the PSL when sim_instr() returns to the sim> prompt where the whole PSL can be referenced.

How/why did you come to  suspect this as a problem?

**Comment by gnudles** [comment]
Oh sorry, I did not noticed that. I once wrote a vax emulator, and I went through the docs and also compared the implementation of simh. So I thought its a mistake... Thanks for clarification
