### ISSUE TITLE
Decnet multi-phase network operational compatibillity problems on Simh systems

### ISSUE THREAD

**Issue by R-Voorhorst** [simh/simh#138]
This thread is a more general and broader follow-up of the now closed issue #106:
Kdp/Dup on Pdp10 Tops-V4.1 phase-3 node will not combine with Dup/Dmc,r phase-4 system (Pdp11,Vax)  

With the advent of working Dmc/Dmr and Kdp/Dup synchronous interfaces and even with the possibility of usage of asynchronous interfaces for Decnet circuit interfaces, the various Pdp11, Pdp10 and Vax systems with their diverse OS'es  can be interconnected in larger Decnet configurations. 
There is also the possibility of creation of synchronous interfaces from the templates of the current ones (Dup) for even older Dec systems like Pdp-8 and so. For some of these systems there was also some form of Decnet available for sync and async lines.

This means that in the same network various phases of Decnet can be active, ranging from Phase-II for the eldest systems c.q. OS'es via Phase-III up to Phase-IV and even up to Phase-V (Decnet-plus, a somewhat unpleasant and uncomfortable variant in the range though as usual ymmv ...).

Consequence is that all these variants will not always cooperate together, either by design (limitations) but more frequently due to unfound errors in the older OS softwares and by divergence in implementations of a same Decnet phase with base OS and time; the latter being the case predominantly with Pdp11 Decnet phase-IV and Vax phase-IV but also with Tops10/20 phase-IV. 

Also playing a role is that with the advent of newer architectures with newer interface types like faster Ethernet adapters, the various tables for Decnet circuit cost calculations have been adapted in time by shifting older circuits to a higher cost range to allocate for the faster interface types with lower cost. 
For example the Dmr interface cost in Tops-10 is 2 while in the Vax the Una cost is 4 and the Dmc/Dmr cost is 5; in the Pdp11 then, the cost of the Dmc/Dmr is  also 5, but the Una cost is 3 and the Kdp/Dup and asynch costs are all 10.
As with routing information the various nodes and their circuit costs are transmitted in the context of the issuing routers along the diverse exchange paths, this creates a range of wrong calculated path costs across the various system types.
Luckily these things can usually be corrected rather easily by either updating of the tables and a rebuild or by a patch process otherwise. 

It has to be noted however, that all these aberrations are not related to the Simh emulation of the interfaces proper, but have to be corrected, if possible, in the next higher layer of creating a usable emulated system, that being formed by the OS'es.  

In this somewhat general thread it will be tried to find these eventual problems and create software solutions for them, thereby also possibly creating newer versions of software modules then have existed for which a suitable version system and clearinghouse have yet to be found.

Best regards

**Comment by dugoh** [comment]
What's still missing to configure a Qbus PDP11 with a DMV11(M8053)?

**Comment by markpizz** [comment]
Dugoh (please put your real name on your github profile),

I'm not sure what you're asking here.

Are you talking about simulators talking or real hardware?

There currently are no Qbus device simulators for the sync boards (DPV11, DMV11).  I once started a DPV11 extension to the DUP11 simulation, but I got busy with other projects and didn't get back to finish that.  Likewise, the DMV11 can be implemented within the pdp11_dmc simulator.  Some declarations already exist to support this, but the details need to be worked out.

Why not use a Unibus PDP11 as a router to an Ethernet connected Qbus system?

Thanks.

- Mark

**Comment by dugoh** [comment]
I wanted to find out if this was simply on the back burner or if there are other problems (eg. missing documentation, perceived impossibilities). From time to time I take a shot at simulating fuzzballs, ao. the original NSFnet Phase I machines, hence the particular hardware/topology.

**Comment by markpizz** [comment]
It is a lack of available bandwidth & focus not a lack of information.  

Working through the details for the DPV11 involves brute force observation of how the driver interacts with the device.  Having the actual PDP11 (RSX11) device driver for this device would make the job easier.

The DMV11 VMS driver is readily available on my VMS Listings CD, so other driver code woundn't be helpful.  However, this device being much later in the set of boards which internally implement DDCMP has a significantly richer set of commands than the earlier DMC/DMR and as such, more nitty gritty details to work through.

I'll be glad to help any interested parties who want to take a crack at this.

**Comment by R-Voorhorst** [comment]
As this issue has grown quite old by now without updates there has been made progress in this case. I choose to close the general thread now and deal with specific issues and solutions in per-issue threads.


Best regards,

R. Voorhorst
