### ISSUE TITLE
Tests for simulators

### ISSUE THREAD

**Issue by promovicz** [simh/simh#144]
This is half feature-request and half request-to-merge.
I have implemented a set of python-pexpect based tests for simh.

These tests mostly execute publicly available images, doing simple smoke tests
such as logging in, listing a directory and other such simple things.

Having written those tests a little while ago I wanted to make an attempt at
getting them into other peoples hands.

They are currently just a bunch of simple python scripts and are in need of a framework to put them into. They also depend on external files from various archives. Most of those are public though, so the framework could just download them.

Should I make an effort to integrate them? Are you interested in just the scripts?

My tests currently cover:
PDP-8: DMS, FOCAL69, OS-8, TSS-8
PDP-11: RSTS/E v7, RT-11 v4 and v5, UNIX v6 and v7, BSD 2.11, Ultrix 3.1
VAX: OpenVMS (install from CD)

**Comment by markpizz** [comment]
No answer.  Closing now.  If you come back with  something open a new issue.
