### ISSUE TITLE
i1620_cpu.c:  treating record marks as zeros is wrong solution

### ISSUE THREAD

**Issue by TomMcBride** [simh/simh#172]
1620 arithmetic instructions operated only on digits, never on other characters such as record marks, group marks, and numeric blanks. Any attempt to do so resulted in a check stop error on the machine. I see the comments in the code about treating record marks as zeros and the new code seems to correctly implement that; however, it's NOT how the real machine worked. I don't know what problem this code was intended to solve but if it did solve a problem, then either the program had an error or this is not the correct solution. 

I have been studying and using the i1620 off and on for a while now. It has a number of other bugs and flaws. I would like to contribute to fixing these but I must tell you that I know nothing about GitHub or the procedures used to update the code. I would welcome suggestions about how to get started/involved.

By way of background, the 1620 was the first computer I learned to use (about 1961), that I wrote lots of code for it both at school and in my job including compilers and assemblers. I have a deep understanding of the machine. I made some contributions to i1620 via notes to Bob Supnik a number of years ago.

@mention markpizz

**Comment by markpizz** [comment]
Hi Tom,

You don't need to be familiar with how to interface with github unless you really want to climb that learning curve.  

I welcome any input.  I'll be glad to take changes you may send along.  First, please pull down the latest code via https://github.com/simh/simh/archive/master.zip

Change the files you see need fixing.

Please send me whole files that have changed (or a zip containing all of the files in the i1620 directory).  Send these to mark@infocomm.com

When making changes to the existing files please keep the indentation and brace style that is already in use in the source files you change.  Also, PLEASE configure your editing environment to insert spaces rather than tabs while editing.  

When you send files back to me, include explanation/analysis of what changes have been made (hopefully more than a one line summary, more like your original comments above).

Thanks.

- Mark

**Comment by TomMcBride** [comment]
Mark,
      
      Thanks much for the quick reply. I will do as you asked and get
      the current version of the code. It will take me a little time to
      compare with the changes I have made and get all to work again. I
      don't mind doing that. 
      
      I gather from the comments in the code that Bob Armstrong had some
      program (an IBM diagnostic program?) that would not run until he
      made the changes to treat record marks as zeros in arithmetic
      operations. As I said, this may have permitted the program to run
      but is not correct. If the program failed trying to compute with a
      record mark, the error lies elsewhere. If I could get  a copy of
      the failing program, I could eventually find out what's wrong. 
      
      I will not go into the list of problems with the i1620 code right
      now in this note but will eventually. Most of the problems are
      very minor or deal with character translation issues. I will be
      testing a number of old programs from the bitsavers web site. If I
      get a number of them to run, I think it will be safe to say the
      simulator is in pretty good shape. I also have a couple of old
      programs that I worked on which I can test with. One of them is a
      replacement for the IBM SPS Assembler program and is now running
      correctly as far as I can tell.
      
      This simulator implements essentially every know instruction for
      the 1620-1, 1620-2 and 1710 computers. Many of those instructions
      will not appear in any of the IBM-supplied software and will not
      really be tested. This means that latent bugs may be there but
      will never be found. I don't see any real problem with that. 
      
      I expect my work to be spread out over a number of months. Besides
      finding and fixing bugs, I need to develop some tools to ease my
      testing and make it easier to view test results. I also will have
      to re-work the documentation specific to the i1620 program. That
      documentation is not bad as far as it goes but there is a lot
      omitted that is needed to make it easy for someone to use the
      program and there are some small mistakes which caused me a lot of
      confusion.
      
      Tom
      
    
    On 1/12/2015 2:16 PM, Mark Pizzolato
      wrote:
    
    
      Hi Tom,
      You don't need to be familiar with how to interface with github
        unless you really want to climb that learning curve. 
      I welcome any input. I'll be glad to take changes you may send
        along. First, please pull down the latest code via https://github.com/simh/simh/archive/master.zip
      Change the files you see need fixing.
      Please send me whole files that have changed (or a zip
        containing all of the files in the i1620 directory). Send these
        to mark@infocomm.com
      When making changes to the existing files please keep the
        indentation and brace style that is already in use in the source
        files you change. Also, PLEASE configure your editing
        environment to insert spaces rather than tabs while editing. 
      When you send files back to me, include explanation/analysis of
        what changes have been made (hopefully more than a one line
        summary, more like your original comments above).
      Thanks.
      
        Mark
      
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by markpizz** [comment]
Please send me your email directly to mark@infocomm.com and I'll give you Bob Armstrong's contact info and you can work out the details between each other.

**Comment by TomMcBride** [comment]
HI Tom,

Bob Armstrong’s email address is:

Bob Armstrong bob@jfcl.com<mailto:bob@jfcl.com>


-          Mark

**Comment by archivisth** [comment]
Tom,

I have the program. It was indeed a 1620 Mark I diagnostic that added two fields, one of which had no word mark and simply ran on until it encountered a random word mark elsewhere. In the course of processing the field, it encountered all sorts of garbage, including record marks. Because the diagnostic worked on a real 1620 Mark I, encountering garbage in the longer field did not seem to matter. I tried following the logic but was unsuccessful.

On the 1401, the adder was biquinary, and IBM added an extra logic term so that invalid digits got predictable results. On the Mark I, adding was by table lookup.

I can send you the program and listing to look through. /Bob Supnik

**Comment by TomMcBride** [comment]
Bob,
      
      Please do send me the program and listing. I am very interested. 
      
       I've been working on the 1620 simulator for several months to try
      to make it as perfect as practical. I've made good progress. It
      runs IBM diagnostics CU01, CU03, and CU05 perfectly.  Those are
      all that I can get copies of that are useful. CU02 did circuit
      tests of the machine and is of no value for the simulator to even
      try. There is a place in CU01 where a compare is done which, on
      the surface, seems to involve a record mark but actually the
      fields being compared have different signs and thus the compare
      operation stops as soon as a non-zero digit is encountered. The
      only case where fields of different signs compare equal is when
      both consist of only zeros. The code seems to know that and is
      actually, in a way, testing to make sure it stops correctly before
      it tries to use the record mark as data. I am also running the paper tape and card versions of the SPS assembler
      with no problems. I'm just now working on testing the math
      subroutines for the assembler before I go on to the Fortran
      compiler, etc. Unfortunately, I could not find any useful test program
      for the math routines so I must write some. I'm also working on a
      program to produce decent listings from the assembler to make it
      easier to document and debug programs. 
      
      Tom
    
    
    On 3/24/2015 3:47 PM, Bob Supnik wrote:
    
    
      Tom,
      I have the program. It was indeed a 1620 Mark I diagnostic that
        added two fields, one of which had no word mark and simply ran
        on until it encountered a random word mark elsewhere. In the
        course of processing the field, it encountered all sorts of
        garbage, including record marks. Because the diagnostic worked
        on a real 1620 Mark I, encountering garbage in the longer field
        did not seem to matter. I tried following the logic but was
        unsuccessful.
      On the 1401, the adder was biquinary, and IBM added an extra
        logic term so that invalid digits got predictable results. On
        the Mark I, adding was by table lookup.
      I can send you the program and listing to look through. /Bob
        Supnik
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by archivisth** [comment]
That's the problem! Here's what Bob Armstrong wrote in his update about 
the record marks:

     // [RLA]   CU01, in the indicator tests around address 18976, 
intentionally
     // [RLA] does a Compare involving a record mark.  I also remember 
reading
     // [RLA] in the IBM CE manual that the 1620 treated a record mark 
as a zero
     // [RLA] for arithmetic operations (although I can't find the specific
     // [RLA] reference anymore!).  We'll assume that CU01 is correct 
and that
     // [RLA] this is the way a real 1620 was expected to work.

 From what you're saying, a real 1620 does NOT use the standard add 
flows for compare, at least not for unlike signs. Hence an invalid 
character would be just fine, as long as it's not zero.

That would also explain why compare can never set overflow.

I will have to reread the 1620 flow manuals again. I think I have them 
somewhere. This is another example of needing to follow the hardware 
more or less exactly to get things right.

/Bob

**Comment by TomMcBride** [comment]
Bob,
      
      Thanks for getting back to me. First, I don't know what Bob
      Armstrong read in the past but I can assure you that the 1620 did
      not treat record marks as zeros. It, as you know, used a table to
      do add/subtract/compare. It addressed that table by forming the
      address 003ab in the MAR (memory address register) where a,b were
      the two digits to be added. It then loaded the digit from that
      location (along with its flag) to get the answer (and the carry
      indication: if there was a flag, it meant there was a carry). If
      either of the digits a,b was not a digit (numeric blank, record
      mark, group mark) the machine stopped with the big Check Stop
      light on. The MDR would have the bad character in it (shown in the
      lights) and you could see the address used by turning the MARS
      selector switch to the right place and pressing the Display MAR
      console switch.
      
      You are correct in saying that compare never set overflow. I'm
      going to quote a few sentences from the 1620-1 book:
      
      "If the signs of the two fields are different initially,
      comparison continues until a digit other than zero is detected in
      either the P or Q field. The on/off conditions of the indicators
      show the positive field to the the greater. When two fields
      containing all zeros are compared, the signs are disregarded and the
      E/Z indicator is turned on."
      
      And a little later on the same page: 
      
      "The record mark, group mark, and numeric blank cannot be used as
      data in an arithmetic of compare operation."
      
      The instruction in question is at 18976 in IBM diagnostic program
      CU01. It is 14 18984 00|1] where I have inserted spaces to
      separate the op code and addresses, the | is used to indicate a
      record mark and the ] indicates a flagged zero. The address 18984
      is the 0 immediately to the left of the |. Since this is an
      immediate, the right end of the field is at 18987, the flagged
      zero. The compare operation begins with examining the 0 at 18984
      and the ] at 18987. The signs are different and zero. This means
      that the next positions to the left must be examined . The next
      two digits are examined. The P field (18983) is zero; the Q field
      (18986) is a 1. This means that the Q field must be smaller than
      the P field and the operation terminates by setting the proper
      indicator. The record mark is never examined or processed.  
      
      I removed the code that treated record marks as zeros and CU01
      runs correctly without error.
      
      Let me know if this makes sense to you. 
      
      Tom McBride
      
      
      
      
    
    On 3/26/2015 8:32 AM, Bob Supnik wrote:
    
    That's the problem! Here's what Bob Armstrong wrote in
      his update about 
      the record marks:
      
      // [RLA] CU01, in the indicator tests around address 18976, 
      intentionally
      // [RLA] does a Compare involving a record mark. I also remember 
      reading
      // [RLA] in the IBM CE manual that the 1620 treated a record mark
      
      as a zero
      // [RLA] for arithmetic operations (although I can't find the
      specific
      // [RLA] reference anymore!). We'll assume that CU01 is correct 
      and that
      // [RLA] this is the way a real 1620 was expected to work.
      
      From what you're saying, a real 1620 does NOT use the standard add
      
      flows for compare, at least not for unlike signs. Hence an invalid
      
      character would be just fine, as long as it's not zero.
      
      That would also explain why compare can never set overflow.
      
      I will have to reread the 1620 flow manuals again. I think I have
      them 
      somewhere. This is another example of needing to follow the
      hardware 
      more or less exactly to get things right.
      
      /Bob
      
      On 3/25/2015 11:34 PM, Tom McBride wrote:
      >
      >
      >
      >
      >
      > Bob,
      >
      > Please do send me the program and listing. I am very
      interested.
      >
      > I've been working on the 1620 simulator for several months to
      try
      > to make it as perfect as practical. I've made good progress.
      It
      > runs IBM diagnostics CU01, CU03, and CU05 perfectly. Those
      are
      > all that I can get copies of that are useful. CU02 did
      circuit
      > tests of the machine and is of no value for the simulator to
      even
      > try. There is a place in CU01 where a compare is done which,
      on
      > the surface, seems to involve a record mark but actually the
      > fields being compared have different signs and thus the
      compare
      > operation stops as soon as a non-zero digit is encountered.
      The
      > only case where fields of different signs compare equal is
      when
      > both consist of only zeros. The code seems to know that and
      is
      > actually, in a way, testing to make sure it stops correctly
      before
      > it tries to use the record mark as data. I am also running
      the paper 
      > tape and card versions of the SPS assembler
      > with no problems. I'm just now working on testing the math
      > subroutines for the assembler before I go on to the Fortran
      > compiler, etc. Unfortunately, I could not find any useful
      test program
      > for the math routines so I must write some. I'm also working
      on a
      > program to produce decent listings from the assembler to make
      it
      > easier to document and debug programs.
      >
      > Tom
      >
      >
      > On 3/24/2015 3:47 PM, Bob Supnik wrote:
      >
      >
      > Tom,
      > I have the program. It was indeed a 1620 Mark I diagnostic
      that
      > added two fields, one of which had no word mark and simply
      ran
      > on until it encountered a random word mark elsewhere. In the
      > course of processing the field, it encountered all sorts of
      > garbage, including record marks. Because the diagnostic
      worked
      > on a real 1620 Mark I, encountering garbage in the longer
      field
      > did not seem to matter. I tried following the logic but was
      > unsuccessful.
      > On the 1401, the adder was biquinary, and IBM added an extra
      > logic term so that invalid digits got predictable results. On
      > the Mark I, adding was by table lookup.
      > I can send you the program and listing to look through. /Bob
      > Supnik
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub 
      >
      <https://github.com/simh/simh/issues/172#issuecomment-86325045>.
      >
      
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by archivisth** [comment]
It does make sense. I'm currently restructuring the CPU to have separate 
flows for compare. I don't want to gum up the add_field routine any 
more, and compare does not use the actual add flows.

/Bob

**Comment by archivisth** [comment]
The restructuring is done. The revised CPU runs CU01 without the "record mark" hack. I will forward the revised code to Mark for merging. The effected modules are i1620_cpu.c and i1620_fp.c (because add_field was simplified).

BTW, my comment about ADD_SIGNC was not correct. It is used, by the branch on index commands, to distinguish the no carry out (true add) case from the no carry out (recomplemented) case.

**Comment by markpizz** [comment]
Hi Tom,

Some of your earlier comments suggest that you may have other changes pending.  

      I gather from the comments in the code that Bob Armstrong had some
      program (an IBM diagnostic program?) that would not run until he
      made the changes to treat record marks as zeros in arithmetic
      operations. As I said, this may have permitted the program to run
      but is not correct. If the program failed trying to compute with a
      record mark, the error lies elsewhere. If I could get  a copy of
      the failing program, I could eventually find out what's wrong.

      I will not go into the list of problems with the i1620 code right
      now in this note but will eventually. Most of the problems are
      very minor or deal with character translation issues. I will be
      testing a number of old programs from the bitsavers web site. If I
      get a number of them to run, I think it will be safe to say the
      simulator is in pretty good shape. I also have a couple of old
      programs that I worked on which I can test with. One of them is a
      replacement for the IBM SPS Assembler program and is now running
      correctly as far as I can tell.

Please pick up the latest code from the "Supnik-Current" branch (available as a zip via: https://github.com/simh/simh/archive/Supnik-Current.zip) and pass your changes/observations along.  I suspect that passing them directly to Bob will be best...  Please open one or more new issues here to track the detailed discussion of what is happening.

Thanks.

- Mark

**Comment by TomMcBride** [comment]
Mark,
      Could you send me Bob Spunik's email address?
      
      Tom McBride
    
    On 3/26/2015 1:05 PM, Bob Supnik wrote:
    
    
      The restructuring is done. The revised CPU runs CU01 without
        the "record mark" hack. I will forward the revised code to Mark
        for merging. The effected modules are i1620_cpu.c and i1620_fp.c
        (because add_field was simplified).
      BTW, my comment about ADD_SIGNC was not correct. It is used, by
        the branch on index commands, to distinguish the no carry out
        (true add) case from the no carry out (recomplemented) case.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by markpizz** [comment]
I'm pretty sure that Bob will have seen your above request since he's participated in this discussion.

I case he doesn't, if you send me your email address (to mark@infocomm.com), I'll reply with Bob's.

I would appreciate having your eMail address without regard to Bob getting back to you though...

Thanks.
