### ISSUE TITLE
BESM6: make besm6 fails when no SDL is present

### ISSUE THREAD

**Issue by psco** [simh/simh#174]
File besm6_cpu.c references besm6_init_panel and besm6_close_panel without checking HAVE_LIBSDL. This causes a linker error.

**Comment by markpizz** [comment]
besm6_panel.c should define these routines in the \#else /* !defined (HAVE_LIBSDL) */ section of the file.

Additionally, each instance (SDL1 and SDL2) of besm6_init_panel() should return SCPE_OK in the success exit path of these routines.

**Comment by leobru** [comment]
ACK; will check-in soon.

**Comment by markpizz** [comment]
Fixed by 0d41242520ce2264f035d76340a854c7bd53736a
