### ISSUE TITLE
microvax3900 build fails on Debian 7

### ISSUE THREAD

**Issue by polaris6262** [simh/simh#179]
I get the following error when I try building the simulators on Debian 7:

gcc -march=native -m64 -std=c99 -U__STRICT_ANSI__  -O3 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=d6e60b88b77a73592bcc01dc0c8f83d9134debb7 -DSIM_COMPILER="GCC Version: 4.7.2" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_GLOB  VAX/vax_cpu.c VAX/vax_cpu1.c VAX/vax_fpa.c VAX/vax_io.c VAX/vax_cis.c VAX/vax_octa.c  VAX/vax_cmode.c VAX/vax_mmu.c VAX/vax_stddev.c VAX/vax_sysdev.c VAX/vax_sys.c  VAX/vax_syscm.c VAX/vax_syslist.c VAX/vax_vc.c VAX/vax_lk.c VAX/vax_vs.c VAX/vax_2681.c PDP11/pdp11_rl.c PDP11/pdp11_rq.c PDP11/pdp11_ts.c PDP11/pdp11_dz.c PDP11/pdp11_lp.c PDP11/pdp11_tq.c PDP11/pdp11_xq.c PDP11/pdp11_vh.c PDP11/pdp11_cr.c PDP11/pdp11_io_lib.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c -DVM_VAX -DUSE_INT64 -DUSE_ADDR64 -DUSE_SIM_VIDEO -I VAX -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_TAP_NETWORK -DHAVE_LIBSDL -I/usr/include/SDL2/ -lSDL2 -o BIN/microvax3900 -lm -lrt -lpthread -lpcreposix -ldl  
sim_video.c: In function ‘vid_thread’:
sim_video.c:1516:16: error: ‘SDL_RENDER_TARGETS_RESET’ undeclared (first use in this function)
sim_video.c:1516:16: note: each undeclared identifier is reported only once for each function it appears in
make: *** [BIN/microvax3900] Error 1

The compiler is the standard gcc version 4.7.2 (Debian 4.7.2-5)

**Comment by markpizz** [comment]
Fixed now
