### ISSUE TITLE
SAGE emulator does not boot

### ISSUE THREAD

**Issue by ericscharff** [simh/simh#181]
Following the instructions in readme-sage.txt

$ cp SAGE/FILES/68k.sim .
$ cp SAGE/FILES/cpm68k12.imd .
$ cp SAGE/sage-ii.hex .
$ BIN/sage 68k.sim

Output:

Sage-II/IV 68k simulator V4.0-0 Beta        git commit id: f0f3176c
Debug output to "debug.log"
Loading boot code from sage-ii.hex

Invalid Mem access, PC: 600018EE (ori.b #$b8,d6)

Build platform - Ubuntu 14.04

**Comment by ericscharff** [comment]
I believe this regression was introduced in commit acac7c1
If I check out the previous version, 995ab8f then it builds and runs

**Comment by ericscharff** [comment]
Sorry, typo, the regression was probably introduced in a9ac7c

**Comment by ericscharff** [comment]
(Not enough context)
Broken by a9ac7c1534c173029cff71887eb5e58a93bf106e

**Comment by markpizz** [comment]
I'm OK if you're OK.

Thanks.

**Comment by ericscharff** [comment]
Yeah, it's working for me now. Thanks!
