### ISSUE TITLE
Make error building simulators on Mageia 4.1

### ISSUE THREAD

**Issue by polaris6262** [simh/simh#187]
gcc -march=native -m64 -std=c99 -U__STRICT_ANSI__  -O3 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -flto -fwhole-program -Wno-unused-result -DSIM_GIT_COMMIT_ID=f2674766ca8b0f2ba3c4685b4d4b53ba7735ec2e -DSIM_COMPILER="GCC Version: 4.8.2" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_GLOB  VAX/vax_cpu.c VAX/vax_cpu1.c VAX/vax_fpa.c VAX/vax_io.c VAX/vax_cis.c VAX/vax_octa.c  VAX/vax_cmode.c VAX/vax_mmu.c VAX/vax_stddev.c VAX/vax_sysdev.c VAX/vax_sys.c  VAX/vax_syscm.c VAX/vax_syslist.c VAX/vax_vc.c VAX/vax_lk.c VAX/vax_vs.c VAX/vax_2681.c PDP11/pdp11_rl.c PDP11/pdp11_rq.c PDP11/pdp11_ts.c PDP11/pdp11_dz.c PDP11/pdp11_lp.c PDP11/pdp11_tq.c PDP11/pdp11_xq.c PDP11/pdp11_vh.c PDP11/pdp11_cr.c PDP11/pdp11_io_lib.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c -DVM_VAX -DUSE_INT64 -DUSE_ADDR64 -DUSE_SIM_VIDEO -I VAX -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_TAP_NETWORK -DHAVE_LIBSDL -I/usr/include/SDL2/ -lSDL2 -o BIN/microvax3900 -lm -lrt -lpthread -lpcreposix -ldl   -flto -fwhole-program
sim_video.c: In function ‘_vid_show_video’:
sim_video.c:1690:17: error: ‘SDL_HINT_VIDEO_ALLOW_SCREENSAVER’ undeclared (first use in this function)
                 SDL_HINT_VIDEO_ALLOW_SCREENSAVER    ,
                 ^
sim_video.c:1690:17: note: each undeclared identifier is reported only once for each function it appears in
sim_video.c:1695:17: error: ‘SDL_HINT_MOUSE_RELATIVE_MODE_WARP’ undeclared (first use in this function)
                 SDL_HINT_MOUSE_RELATIVE_MODE_WARP    ,
                 ^
sim_video.c:1699:17: error: ‘SDL_HINT_ACCELEROMETER_AS_JOYSTICK’ undeclared (first use in this function)
                 SDL_HINT_ACCELEROMETER_AS_JOYSTICK ,
                 ^
sim_video.c:1706:17: error: ‘SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK’ undeclared (first use in this function)
                 SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK ,
                 ^
sim_video.c:1707:17: error: ‘SDL_HINT_VIDEO_WIN_D3DCOMPILER’ undeclared (first use in this function)
                 SDL_HINT_VIDEO_WIN_D3DCOMPILER              ,
                 ^
sim_video.c:1708:17: error: ‘SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT’ undeclared (first use in this function)
                 SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT    ,
                 ^
sim_video.c:1718:17: error: ‘SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES’ undeclared (first use in this function)
                 SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES,
                 ^
makefile:1378: recipe for target 'BIN/microvax3900' failed
make: *** [BIN/microvax3900] Error 1

The compiler is the standard GCC version 4.8.2

**Comment by markpizz** [comment]
What is your OS and specific libSDL2 version?

**Comment by polaris6262** [comment]
I've tried on two different systems, one running Debian 7.8 using GCC 4.7.2 and SDL2 2.0.0, and a second running Mageia 4.1 (it's a derivative of Mandriva) using GCC 4.8.2 and SDL2 2.0.1 with the same result. My last system running Fedora 21 with newer software compiled fine.
