### ISSUE TITLE
Segmentation fault in sim_disk_show_capac()

### ISSUE THREAD

**Issue by JohnForecast** [simh/simh#194]
If sim_disk_show_capac() is called on a disk which is not attached (e.g. "show conf" right after starting the simulator), a segmentation fault will occur due to accessing a NULL disk context.

**Comment by markpizz** [comment]
Hi John.

I type SHOW CONF and DO NOT see a segmentation fault.

Please provide:
1) the output of SHOW VERSION from your simulator
2) the configuration file which the simulator executed BEFORE you see the segmentation fault.
3) the exact command which produced the segmentation fault.

Thanks.

- Mark

**Comment by JohnForecast** [comment]
Hi Mark,
   As far as I can see none of the existing simulators make use of sim_disk_show_capac() as described in simh.doc, in particular the MTAB entries. I’m working on a new simulator and, since I was about to start writing the disk access code, I decided to switch to 4.0 and make use of the disk emulation libraries. This is more of a heads-up in case anyone makes use of the routine in the future.

  My test configuration is built using the disk emulation library with the 2 MTAB entries (“FORMAT” and “CAPACITY”). The GIT commit ID is “50d1407c”, there is no configuration file and the command to generate the fault is “show conf”.

  John.

**Comment by markpizz** [comment]
Hi John,

What type of simulator are you working on?  Does it have support for disks of arbitrary sizes?  What are the 'units' of disk size expressed in (Bytes, Words, other)?  What is the largest sized disk that the system supported?

As you observed, no code in any current simulator actually uses sim_disk_show_capacity() or sim_disk_set_capacity().

One of the reasons for this is due to the fact that the two disk simulations which actually use the sim_disk APIs (pdp11_rq and pdp11_rp) were originally implemented before sim_disk existed and these had previously established ways to select or manipulate disk sizes.

It is not clear if sim_disk_show_capac is actually necessary, but I've now fixed it to avoid the issue you raised.

Thanks.

- Mark
I'm thinking that given the fact that

**Comment by JohnForecast** [comment]
Hi Mark,
    I working on a simulator for the CDC1700, a 16-bit mini-computer from the early ‘70s. Bitsavers has some software available and I’ve been able to boot the diagnostic magtape and successfully complete the tests for CPU, paper tape reader/punch and line printer. 

   The next device to implement would be the 1738 disk pack controller which allows access to up to 2 disks with 96 word sectors. There are 2 types of drives; the 853 which is ~1.5MW and the 854 which is ~3MW. There is no possibility of reading an 853 pack in an 854 drive or vice versa, so I don’t need to worry about autosizing. I haven’t quite figured out how to stop the user changing the type of drive while the system is running.

   Thanks for the fix,
     John.

**Comment by markpizz** [comment]
Thanks for the info.

As to how to stop changing the drive type….  Provide your own routine to explicitly do the type setting and in that routine fail if the device is UNIT_ATT is already set.

An example that does this check is in pdp11_xu.c “SET XU MAC”.


-        Mark

**Comment by markpizz** [comment]
Hi John,

From what you are saying "autosizing" might actually what you want.  The user attaches a disk image and as a result of autosizing the drive type is set to either 853 or 854.  You may need to have a device specific attach which first calls sim_disk_attach (allowing autosizing) and when sim_disk_attach returns successfully, you look at uptr->capac and based on that you set the drive type to the appropriate model and adjust any other drive specific parameters as necessary...  In general this is what most disk simulators mean by autosizing (even those which don't use the sim_disk APIs).

- Mark

- Mark

**Comment by JohnForecast** [comment]
Hi Mark,
   I can probably do something like that. I’m not sure if the O/S software can handle such a switch - I suspect the drive type needs to be specified during system generation.

  John.

**Comment by markpizz** [comment]
Hi John,

Hmmm...  I wasn't thinking of dynamically changing things with a system running.  

Did these drives have removable packs or were they fixed config drives?  If they were removable, then the suggestion indeed doesn't make sense, but if they were fixed, then the behavior I suggested would seem to be the most friendly/simplest for a user's basic configuration file which really is startup code and nothing surprising would happen to a running operating system...

- Mark

**Comment by JohnForecast** [comment]
Hi Mark,
    These were removable packs. I’m thinking of adding a private flag (UNIT_DEVLOCKED) which is set when the drive is attached and never cleared. Attaches will only be allowed while the flag is clear. If the wrong type of “disk pack” is attached, the OS device driver will either get an addressing error or see a half-sized drive. In real-life it looks as though the disk packed had an interlock to make sure the drives/packs could not be incorrectly mixed. I don’t see any way to enforce such capabilities in a simulated environment.

  John.

**Comment by markpizz** [comment]
Hi John,

I like the UNIT_DEVLOCKED idea which will allow autosizing to occur on the first attach, although that might not be right since a user might boot a system and only later attach a disk initially.  Maybe you want to keep track of whether the system has been 'booted' or not and allow any changes before the boot and none after.

Meanwhile, once the drive type has been set (either by an initial autosize or fixed due to a boot already having happened), any attempt to attach a disk image of the incorrect size should not succeed.  In your device specific attach routine, you can let sim_disk_attach attach the device and if the resulting attached file size is wrong, detach it and return SCPE_OPENERR from the device specific attach.

- Mark

Once

**Comment by JohnForecast** [comment]
Hi Mark,
   I don’t think I can make it completely bullet-proof, but that’s probably as good as I can make it. I haven’t checked, but can I return a custom SCPE_xxx error code from sim_disk_attach() so I can generate a specific error message for this case?

  John.

**Comment by markpizz** [comment]
Hi John,

You can't change the internal logic of sim_disk_attach.  That is why I described you writing your own device specific attach routine which applies your logical conditions and calls sim_disk_attach and then validates the requirements once attach succeeds and if conditions aren't OK calls sim_disk_detach and then returns SCPE_OPENERR.

- Mark

**Comment by JohnForecast** [comment]
Hi Mark,
   That’s what I was proposing to do, except rather than return SCPE_OPENERR, return a VM private error code so that I could output “Disk size mismatch” rather than “File open error”. Unfortunately, it appears that the VM-specifc SCPE_xxx error codes only display text errors when returned from sim_instr().

  John.

**Comment by markpizz** [comment]
Hi John,

Now that I know exactly what you want.  The solution is easy:

simply use the sim_messagef API to print your message with the following:

    if (bad disk)
        return sim_messagef (SCPE_OPENERR, "Disk size mismatch");
    return SCPE_OK;

Your message is emitted, and the return status is SCPE_OPENERR but the default message for SCPE_OPENERR will be suppressed.

- Mark

**Comment by JohnForecast** [comment]
Hi Mark,
   Thanks, that’s exactly what I need.

  John.

**Comment by JohnForecast** [comment]
Hi Mark,
    I tried to implement what we’ve been talking about, with UNIT_DEVLOCK defined as:

	1 << (DKUF_V_UF + 1)

Unfortunately, with all the various bitfields, DKUF_V_UF ends up defined as 32 so there’s no space available for private unit flags with the disk library.

  John.

**Comment by markpizz** [comment]
Hi John,

Two things:  

1) If you are really set on trying to use a device unit flag to influence this state, there are many flag bits available in the dynflags field.  You should have no collisions using any bit at 12 or above.
2) As I mentioned earlier, it would seem that the state which should influence this isn't really a device attribute, but an attribute of the whole simulator (i.e. if the simulator has booted and thus an OS has potentially seen/expected a particular device configuration it would be a bad idea to dynamically change the device configuration.  So, whether the simulator has been booted is global state outside of the device/unit specific details....

- Mark

**Comment by JohnForecast** [comment]
Hi Mark,
    I like the global state idea. I guess I can set a flag whenever any instruction has been executed. There is a flag “sim_is_running” which might provide the same semantics - I’ll take a look.

  John.

**Comment by markpizz** [comment]
Hi John,

There is a sim_is_running, but that only describes the fact that the current code has been invoked while sim_instr() is active.  If a user stops execution, sim_instr() exits and sim_is_running is no longer true.  Any context where an attach command could be executed will always have sim_is_running FALSE.

- Mark

**Comment by markpizz** [comment]
To record the state we've been talking about, you could merely set a global flag upon entry to sim_instr() and never clear it.

**Comment by JohnForecast** [comment]
Yes, that was what I was thinking of doing.
