### ISSUE TITLE
Nova PTR Errors using DCC Basic

### ISSUE THREAD

**Issue by 6sn7** [simh/simh#203]
I found an issue with the simh nova simulator where binary images of Basic programs from paper tape will not read using the DCC (Digital Computer Controls - nova clone) Basic interpreter. The ptr input stream is dropping bytes. The paper tape binary loader and basic interpreter object tapes load and run succsessfully. The failure ocurrs when attempting to load a Basic program from within the interpreter.

The boot loader built in the nova sim and the DCC paper tape loader use programmed IO whereas the basic interpreter uses interrupts for servicing IO devices.  I suspect there may be a problem in the nova interrupt handling code.

**Comment by archivisth** [comment]
Please post the files to a public site (Mega, mediafire) so that this problem can be investigated. Also include here a session log that demonstrates the problem you are seeing.

**Comment by 6sn7** [comment]
I don't have access to a public site for posting the files.  A gzipped tar file of a directory with all of the  files (dcc_loader.obj, dcc_basic.obj, basic_program.bas) is ~20Kb which could be emailed. Below is an output of a session that reproduces the problem.  BTW, I verified the basic program tape file is good.

Session Output
--------------

NOVA simulator V4.0-0 Beta        git commit id: 83338d1d
nova_ptr_problem.conf-7> a ptr dcc_loader.obj
nova_ptr_problem.conf-8> d sr 12
nova_ptr_problem.conf-9> boot ptr

HALT instruction, PC: 00150 (JMP 30,2)
nova_ptr_problem.conf-10> d sr 100012
nova_ptr_problem.conf-11> a ptr dcc_basic.obj
nova_ptr_problem.conf-12> continue

MAT OVERLAY Y OR N  N


Simulation stopped, PC: 02276 (INC 3,3)
sim> a ptr gunner.bas
sim> continue
NEW
TAPE00 RIT THS RORA  IMLAESTE"011 PIN "ESLT F IRNGA IED RTLLR WAPN.

ERROR #9
0 PIN

ERROR #9
0 PIN "OUAR TE FFCE-N-HAGE GVIG RDRST TE UN

ERROR #9

================

The following chars should have been read in from the tape.
ERROR #9 are syntax errors.

0100 PRINT "THIS PROGRAM  SIMULATES THE"
0110 PRINT "RESULTS OF FIRING A FIELD ARTILLERY WEAPON."
0120 PRINT


The lines below indicates which caracters were dropped.

0100 PRINT "THIS PROGRAM  SIMULATES THE"
 ^   ^  ^  ^  ^  ^^ ^  ^  ^  ^  ^  ^ ^

**Comment by archivisth** [comment]
Neither Mega (mega.co.nz) nor Mediafire (mediafire.com) require that you have an account or a special application. You can upload files from your web browser, and they return a URL that you can share. If you have email, you have web access, and if you have web access, you can upload.

Alternately, you can try attaching your zip file to your reply. GitHub will accept images; I don't know if it will accept arbitrary files.

**Comment by 6sn7** [comment]
I didn't know Mega didn't requie an account. Good to know - thanks.
URL to ptr_problem.tar.gz below (directory of files).
https://mega.co.nz/#fm/j45kXRSb

Let me know if you need further data.

**Comment by archivisth** [comment]
I'm afraid the URL is truncated. Mega URL share codes are much longer than that and never have an embedded / (#fm/ cannot be right).

**Comment by 6sn7** [comment]
Attempting to attache the *.gz file to this reply.
Not sure how to get the URL from Mega. When I click on "Get Link" it puts
up a message saying "reating links is only for registered users".

Hopefully the attachment will work.

John

On Thu, Apr 2, 2015 at 12:39 PM, Bob Supnik <notifications@github.com>
wrote:

> I'm afraid the URL is truncated. Mega URL share codes are much longer than
> that and never have an embedded / (#fm/ cannot be right).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simh/simh/issues/203#issuecomment-88969106>.
>



-- 
RDWHAHB
xyzzy

**Comment by markpizz** [comment]
It did not work.  Google Drive maybe?  By the way, you do not have to install anything on your computer to user Google Drive.  It is completely web based.

**Comment by 6sn7** [comment]
Mark,

I have never used google drive but just uploaded the file there. What do I
have to do to make it accessible to Bob?

John


On Thu, Apr 2, 2015 at 2:20 PM, Mark Pizzolato <notifications@github.com>
wrote:

> It did not work. Google Drive maybe? By the way, you do not have to
> install anything on your computer to user Google Drive. It is completely
> web based.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simh/simh/issues/203#issuecomment-88998608>.
>



-- 
RDWHAHB
xyzzy

**Comment by markpizz** [comment]
My browser I navigate to my Google Drive (https://drive.google.com/drive/#my-drive).
I right click on the file I want to share and select "Share" in the dropdown.  In the pop-up window I click on the "Get sharable link" link in the upper right corner.  I click on the "Copy Link" button and your clipboard will have a link you should be able to provide here.

**Comment by 6sn7** [comment]
Ok. Try this link please.

https://drive.google.com/file/d/0B2sv9JN4R9X9WUtBVWJ3bTlHQjA/view?usp=sharing

**Comment by archivisth** [comment]
Got it, thanks.

Mark, you can assign this to me, unless Bruce Ray is interested. ;)

I tried the paper tape reader under RDOS, which is purely interrupt 
driven, and it works fine, so this is something else.

/Bob

**Comment by archivisth** [comment]
It's a timing problem in the software. The paper tape delay is too short. 500 will work:

Do all the setup, and after attaching GUNNER.BAS to the PTR:

sim> D PTR TIME 500
sim> C
NEW‼ (NEW<ENTER> typed here, program echoes !!)
TAPE‼ (TAPE<ENTER> typed here, program echoes !!)
(Program seems to hang here for a long time; it is actually timing out end-of-tape on the paper-tape reader. While that is going on, the terminal is unresponsive. Eventually, it responds to <ENTER>>)
RUN‼ (RUN<ENTER> typed here, program echoes !!)
THIS PROGRAM  SIMULATES THE
RESULTS OF FIRING A FIELD ARTILLERY WEAPON.

YOU ARE THE OFFICER-IN-CHARGE, GIVING ORDERS TO THE GUN
CREW, TELLING THEM THE DEGREES OF ELEVATION YOU ESTIMATE
WILL PLACE THE PROJECTILE ON TARGET. A HIT WITHIN 100 YARDS
OF THE TARGET WILL DESTROY IT. TAKE MORE THAN 5 SHOTS,
AND THE ENEMY WILL DESTROY YOU!
MAXIMUM RANGE OF YOUR GUN IS 46500 YARDS.

    DISTANCE TO THE TARGET IS 21660 YARDS


ELEVATION:? (^E typed here)
Simulation stopped, PC: 02300 (LDA 0,323)
sim>

This issue can be closed.

**Comment by markpizz** [comment]
Does this suggest that the default paper tape delay should be changed?

**Comment by archivisth** [comment]
No harm in raising it from 100 to 200, I suppose (it works at 200). 
However, there's a global define called SERIAL_IN_DELAY, which is what 
the NOVA PTR and every other programmed IO input device uses. If you 
want to change the NOVA, it should be done locally, I think, not by 
changing the global define... might impact other areas.

/Bob

**Comment by markpizz** [comment]
Will you make this change in your code and I'll migrate it to the master branch on the next merge??

**Comment by 6sn7** [comment]
I did confirm that adding a delay of 500 works fine. 

Thanks!

**Comment by archivisth** [comment]
Yes, I'll do that.
