### ISSUE TITLE
MAC Address Conflict on LAN

### ISSUE THREAD

**Issue by mstramb** [simh/simh#207]
Running on Win Xp sp 3

Tried both :
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: 93b68432
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: d8306093

NVR: buffering file in memory
WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
Eth: opened OS device \Device\NPF_{0F42D728-D985-44B7-AF41-3E27FCC153BA}

Tue Apr 14 12:00:04 2015
_eth_write(pcap): send error: PacketSendPacket failed
Eth: Error Transmitting packet: Invalid argument
You may need to run as root, or install a libpcap version
which is at least 0.9 from your OS vendor or www.tcpdump.org
XQ: MAC Address Conflict on LAN for address 00:19:B9:21:39:39, change the MAC address to a unique value
Eth: closed \Device\NPF_{0F42D728-D985-44B7-AF41-3E27FCC153BA}

**** tried SET XQ MAC=12-34-56-78-9A-BC ***
XQ: MAC Address Conflict on LAN for address 12:34:56:78:9A:BC, change the MAC address to a unique value

    ipconfig /all
    
    Ethernet adapter LocalAreaConnection-192.168.0.1:
    
            Connection-specific DNS Suffix  . :
            Description . . . . . . . . . . . : Broadcom NetXtreme 57xx Gigabit Controller
            Physical Address. . . . . . . . . : 00-19-B9-21-39-39
            Dhcp Enabled. . . . . . . . . . . : No
            IP Address. . . . . . . . . . . . : 192.168.0.1
            Subnet Mask . . . . . . . . . . . : 255.255.255.0
            Default Gateway . . . . . . . . . :
            DNS Servers . . . . . . . . . . . : 64.140.120.21
                                                          64.140.120.22

---------------------------

--- vax.ini --------

set console telnet=23

; multiple telnet sessions
attach dz 2000
attach dz 2100
attach dz 2200
attach dz 2300

set console log=log.txt

load -r ka655x.bin

;Create and attach a file for emulated NVRAM
attach nvr nvram.bin

; ---- disks ------
SET RQ0 RA90
ATTACH RQ0 RQ0.dsk

SET RQ1 RA90
ATTACH RQ1 RQ1.dsk

SET RQ2 RRD40
ATTACH RQ2 VMS.iso

SET RL DISABLE
SET TS DISABLE

SET CPU 64M
SET CPU IDLE

; broadcom nic on dell optiplex 2014
; DELQA-T network device

set xq enable
SET XQ MAC=00-19-B9-21-39-39
attach xq eth1

SET CPU CONHALT
DEP BDR 0

;BOOT CPU
;boot -flags 0,30000 cpu
;boot -flags 0,1 cpu
;EXIT

**Comment by markpizz** [comment]
Setting the XQ MAC address to one which is already in use by the host system for instance definitely won't work.

Since you've only got a single system here, leave the MAC address as the default.

What is the output of "SHOW ETHER"?

**Comment by mstramb** [comment]
operator error (as usual)
After a  sh sq eth, found I was using the wrong device

**Comment by markpizz** [comment]
By the way, your configuration file contained:

    ; multiple telnet sessions
    attach dz 2000
    attach dz 2100
    attach dz 2200
    attach dz 2300

What was the intention of these multiple attach commands?  Only the last one has any useful effect.

**Comment by markpizz** [comment]
Back to the original issue, I'd like the simulator code to provide better feedback so you could have helped yourself initially without having to reach out for help.

To that end, please answer the following questions:

On your system, I presume that you initially didn't set the XQ MAC address to be the MAC address of the host interface.  Is that true?  If not, what were you trying to do?

Assuming you didn't initially change the XQ MAC address, what error was produced when you "ATTACH XQ ETH1"?

What is the output of "SHOW ETHER" (equivalent to "SHOW XQ ETH")?

What is the full output of "ipconfig/all"?

**Comment by markpizz** [comment]
Oh well, with no answers to these questions I can't help folks who make these mistakes to steer folks in the right direction...
