### ISSUE TITLE
Build fails in isys8010

### ISSUE THREAD

**Issue by polaris6262** [simh/simh#217]
Building with a 'make all' fails with the following error:

make: *** No rule to make target 'Intel-Systems/common/isbc80-10.c', needed by 'BIN/isys8010'.  Stop.

This occurs on all of my Linux distributions.

**Comment by polaris6262** [comment]
My apologies, I should have studied this issue closer before reporting it.

The following files in Intel-Systems/common should not have any uppercase letters:

iSBC80-10.c
iSBC80-20.c
iSBC80-30.c

Renaming them as such:

isbc80-10.c
isbc80-20.c
isbc80-30.c

solves the problem.

**Comment by markpizz** [comment]
Thanks for finding this and identifying exactly what was wrong.

It is now fixed.
