### ISSUE TITLE
PDP11: Magtape format is "sticky"

### ISSUE THREAD

**Issue by JohnForecast** [simh/simh#219]
If you attach a magtape using:

    att -f tq0 tpc file.tpc

and then later attach a different magtape using:

    att tq0 file.tap

the second tape is attached in "tpc" format, resulting in some bizarre errors since the two formats are almost identical. This should be explicitly documented or the format should be reset to simh format if "-f" is not present.

**Comment by markpizz** [comment]
Hi John,

The command:

    att -f tq0 tpc file.tpc

is 100% equivalent to:

    set tq0 format=tpc
    att tq0 file.tpc

Exactly what were the bizarre errors and when did they appear?

Please elaborate on the errors and we can probably come up with a better reporting paradigm.

**Comment by JohnForecast** [comment]
Hi Mark,
   I was trying to copy a DECnet kit from tape to disk which requires 2 tapes. The first was in TPC format and that went OK. The second was in SIMH format but, because I didn’t specify the “-f” switch it was considered to be in TPC format. Everything seemed to go OK until the framing became out of sync due to an odd-byte count record so the reported directory entry was garbled.

  When I originally saw this happen, I had started the original tape copy and left for a couple of hours. By the time I came back I had forgotten that I had attached the tape using the “-f” switch and just used the default syntax. I did think it was rather odd that it indicated that a .tap format file was mounted in read-only mode, but I didn’t care since I was just going to read the tape.

  Given the commands you describe below, I’m not sure how it could be implemented any other way, other than maybe an extra message such as:

	tq0: <filename> attached in TPC format

  John.

**Comment by markpizz** [comment]
Hi John,

Adding the format to the attach command output is a good idea.

Meanwhile, I asked about when and what 'bizarre' messages were produced so I could produce more informative ones.  When a TPC format tape is opened (via either command syntax previously mentioned), the tpc data is read in its entirety to create an internal file position map of each data record (and each tape mark).  Reasonable validation could be performed during this reading of the tpc data records and useful messages produced.

Can you provide pointers to the two tape images you were working with?

Thanks.

- Mark

**Comment by JohnForecast** [comment]
Hi Mark,
   The bizarre errors were not produced by simh - it just accepted what it was given. The errors were coming from RSX-11M+, it reported invalid and partially garbled directory names when I had previously checked the tape was valid (on a previous run when I had only attached a single tape). I guess you could check that the value of the trailing record size matches the size at the start of the record - that should catch any odd-sized records.

  In order to use the tape images I was using you need to have a running RSX-11M+ system. The 2 tape images are:

	rsxmplus_4_0_netkit_aq-ew97b-bc
	BB-3567E-BC_DECNET-11M+_V4.0_DECKIT

I don’t remember where I got them from - a web search should able to locate them.

  John.

**Comment by markpizz** [comment]
Hi John,

I don't really need an RSX-11M system.  A tape is a tape.  I'd only need an RSX system if I wanted to actually use it.  I can read (or attach) it with any system.

thanks for the names.  I found them.

Trailing Record size ONLY exists on simh format tapes.  TPC tapes have a 16bit record size preceding each record.  It will be pretty hard and somewhat arbitrary to try and validate a TPC format tape.  The only reliable test I can see is if the end of the tape file is where the last record size says it should be.  

I've added that check.  Now you get:

     sim> att -f tq0 tpc BB-3567E-BC_DECNET-11M+_V4.0_DECKIT.tap
     TQ: unit is read only
     Format error

Good enough?

- Mark

**Comment by JohnForecast** [comment]
Hi Mark,

    Yes, you’d only need an RSX-11M system to see the actual errors generated. I think the “format error” message should be a pretty good indication that something is wrong. Does it perform the test for all formats?

  John.
