### ISSUE TITLE
tmxr_linemsg() does not check for SCPE_STALL

### ISSUE THREAD

**Issue by charlesUnixPro** [simh/simh#223]
txmr_linemsg does not check the return value of tmxr_putc_ln(); if it returns SCPE_STALL, the character is dropped. 

txmr_linemsgf does check; adding the check into txmr_linemsg looks like:
~~~~
/* Write a message to a line */

void tmxr_linemsg (TMLN *lp, const char *msg)
{
int32 len;

for (len = (int32)strlen (msg); len > 0; --len)
    //tmxr_putc_ln (lp, *msg++);
    for (len = (int32)strlen (msg); len > 0; --len)
    {
        while (SCPE_STALL == tmxr_putc_ln (lp, *msg))
        {
            if (lp->txbsz == tmxr_send_buffered_data (lp))
              sim_os_ms_sleep (10);
        }
        msg ++;
    }
return;
}
~~~~

**Comment by markpizz** [comment]
Hi Charles,

I've added logic to the tmxr_linemsg routine to cover the SCPE_STALL case.  tmxr_linemsg (along with tmxr_msg, tmxr_linemsgf and tmxr_linemsgvf) exist to provide tools for simulator code to deliver simulator internal messages to clients across tmxr lines (connection, status change or other stuff)).  these routines are NOT to be used by device simulators to deliver data from the simulated system.
