### ISSUE TITLE
Attached disk no longer connected to disk container

### ISSUE THREAD

**Issue by mjjerabek** [simh/simh#224]
Using VAX emulator. Had a VMS ISO attached to RQ device. After rebooting the VMS OS several times the ISO was no longer attached. In general, things (attached devices) do not survive a reboot.

**Comment by jguillaumes** [comment]
Of the volume is dismounted without the /NOUNLOAD qualifier SIMH detaches the device (as a real unit would do). I think it is working as designed.

Jordi Guillaumes Pons


El 29/06/2015, a les 6:15, mjjerabek <notifications@github.com> va escriure:

**Comment by markpizz** [comment]
As Jordi says, this is explicitly a feature of disk devices which have removable media (CDROM, RA60, RX50, RRD40, etc).

- Mark
