### ISSUE TITLE
simh pdp-11/23 won't boot XXDP V2.5

### ISSUE THREAD

**Issue by vaxorcist** [simh/simh#225]
simh pdp-11/23 won't boot XXDP V2.5, whereas my real PDP-11/23 does:

PDP-11 simulator V4.0-0 Beta        git commit id: d8306093
G:\VAX\VAX-11\PDP-11\PDP11.ini-1> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-2> ; DISABLE ALL DEVICES FIRST
G:\VAX\VAX-11\PDP-11\PDP11.ini-3> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-4> ; NO TQK50 TMSCP DISK CONTROLLER
G:\VAX\VAX-11\PDP-11\PDP11.ini-6> SET TQ DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-7> ; NO DELQA/DEQNA QBUS ETHERNET CONTROLLER
G:\VAX\VAX-11\PDP-11\PDP11.ini-9> SET XQ DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-10> ; NO RP/RM MASSBUS DISK PACK DRIVES
G:\VAX\VAX-11\PDP-11\PDP11.ini-12> SET RP DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-13> ; NO RH70/RH11 MASSBUS ADAPTER
G:\VAX\VAX-11\PDP-11\PDP11.ini-15> SET RHA DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-16> ; NO RK11/RK05 CARTRIDGE DISK
G:\VAX\VAX-11\PDP-11\PDP11.ini-18> SET RK DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-19> ; NO RX11/RX01 FLOPPY DISK
G:\VAX\VAX-11\PDP-11\PDP11.ini-21> SET RX DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-22> ; NO RQDX3/UDA50 MSCP DISK CONTROLLER
G:\VAX\VAX-11\PDP-11\PDP11.ini-24> SET RQ DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-25> ; NO DHQ11 TERMINAL MULTIPLEXER
G:\VAX\VAX-11\PDP-11\PDP11.ini-27> SET VH DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-28> ; NO PC11 PAPER TAPE READER
G:\VAX\VAX-11\PDP-11\PDP11.ini-30> SET PTR DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-31> ; NO PC11 PAPER TAPE PUNCH
G:\VAX\VAX-11\PDP-11\PDP11.ini-33> SET PTP DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-34> ; LP11 LINE PRINTER
G:\VAX\VAX-11\PDP-11\PDP11.ini-36> SET LPT DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-37> ; NO TC11 CONTROLLER WITH TWO DECtapes TU56
G:\VAX\VAX-11\PDP-11\PDP11.ini-39> SET TC DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-40> ; NO TU10 MAGTAPE
G:\VAX\VAX-11\PDP-11\PDP11.ini-42> SET TM DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-43> ;NO RL DISKS
G:\VAX\VAX-11\PDP-11\PDP11.ini-45> SET RL DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-46> ; NO RK07 DISKS
G:\VAX\VAX-11\PDP-11\PDP11.ini-48> SET HK DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-49> ; NO DZ11 TERMINAL MULTIPLEXER
G:\VAX\VAX-11\PDP-11\PDP11.ini-51> SET DZ DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-52> ; No CARDREADER
G:\VAX\VAX-11\PDP-11\PDP11.ini-54> SET CR DISABLED
G:\VAX\VAX-11\PDP-11\PDP11.ini-54> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-55> ; END OF DISABLE ALL DEVICES FIRST
G:\VAX\VAX-11\PDP-11\PDP11.ini-56> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-58> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-59> ; CPU & MEMORY
G:\VAX\VAX-11\PDP-11\PDP11.ini-60> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-62> SET CPU 11/23
G:\VAX\VAX-11\PDP-11\PDP11.ini-62> ;SET CPU 64K
G:\VAX\VAX-11\PDP-11\PDP11.ini-64> SET CPU 256K
G:\VAX\VAX-11\PDP-11\PDP11.ini-65> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-66> ; LINE CLOCK
G:\VAX\VAX-11\PDP-11\PDP11.ini-67> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-69> SET CLK 50HZ
G:\VAX\VAX-11\PDP-11\PDP11.ini-70> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-71> ; DISKS
G:\VAX\VAX-11\PDP-11\PDP11.ini-72> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-73> ; SET RL02 DISKS
G:\VAX\VAX-11\PDP-11\PDP11.ini-75> SET RL ENABLE
G:\VAX\VAX-11\PDP-11\PDP11.ini-76> SET RL0 RL02
G:\VAX\VAX-11\PDP-11\PDP11.ini-77> SET RL1 RL02
G:\VAX\VAX-11\PDP-11\PDP11.ini-78> SET RL2 RL02
G:\VAX\VAX-11\PDP-11\PDP11.ini-79> ; CREATE/USE DISK FILE
G:\VAX\VAX-11\PDP-11\PDP11.ini-81> ATTACH RL0 XXDP25.RL2
G:\VAX\VAX-11\PDP-11\PDP11.ini-81> ;ATTACH RL1 XXDP22.RL2
G:\VAX\VAX-11\PDP-11\PDP11.ini-82> ;ATTACH RL2 test22.RL2
G:\VAX\VAX-11\PDP-11\PDP11.ini-84> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-85> ; CONSOLE SETTINGS
G:\VAX\VAX-11\PDP-11\PDP11.ini-86> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-88> SET TTO 7P
G:\VAX\VAX-11\PDP-11\PDP11.ini-89> SET CONSOLE LOG=008.log
Logging to file "008.log"
G:\VAX\VAX-11\PDP-11\PDP11.ini-90> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-91> ; BOOT
G:\VAX\VAX-11\PDP-11\PDP11.ini-92> ; -------------------------------------
G:\VAX\VAX-11\PDP-11\PDP11.ini-94> SHOW CPU
CPU     11/23, FPP, NOCIS, idle disabled, autoconfiguration enabled
        256KB
G:\VAX\VAX-11\PDP-11\PDP11.ini-95> BOOT RL0

HALT instruction, PC: 000104 (JMP SP)
sim>

By the way: the simh PDP-11/45 (with the rest of the config identical to that of the 11/23) does boot XXDP V2.5 without problems.

Regards,

Ulli

**Comment by vaxorcist** [comment]
Addendum:

The simh pdp-11/03 (64K) behaves the same as the pdp-11/23 (won't boot XXDP V2.5)
but the pdp-11/23+ (64K or 256K) boots sucessfully

**Comment by vaxorcist** [comment]
Sorry, wrong button ...

**Comment by vaxorcist** [comment]
Another addendum:

sim> sh version
PDP-11 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                32b data
                32b addresses
                Ethernet Packet transport:PCAP:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
        Host Platform:
                Compiler: Microsoft Visual C++ 15.00.30729.01
                Simulator Compiled: Feb 15 2015 at 12:51:05
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                PCRE RegEx support for EXPECT commands
                OS clock tick size (time taken by msleep(1)): 1ms
                OS: Windows:
Microsoft Windows [Version 6.0.6002]
                x86 Family 6 Model 23 Stepping 10, GenuineIntel - x86-%PROCESSOR
_ARCHITEW6432%

        git commit id: d8306093

Microsoft Windows [Version 6.0.6002]
                x86 Family 6 Model 23 Stepping 10, GenuineIntel - x86-%PROCESSOR
_ARCHITEW6432%
sim>

**Comment by markpizz** [comment]
I'm not a PDP11 user, but from a little searching, XXDP seems to be the PDP11 equivalent of the VAX diagnostic supervisor.  

In general, simh's goals have never included running original hardware diagnostics, but merely to provide an environment which allows application and operating system software to run.

One might argue that merely booting XXDP might be running an application(or operating system).  That might be true, but the next step will then be to actually run diagnostics.  Getting XXDP to boot seems like going down a slippery slope...

**Comment by vaxorcist** [comment]
My point of view is a little different:

XXDP is just another PDP-11 operating system (although a little special).
I do not expect to run all of the diags successfully with simh, but some (testing at the functional level) do really work.

What I use XXDP for (in conjunction with simh) is preparing XXDP images for e.g. RX01, RX02 or RX50 floppies. I write these images to real floppies using my VAXen and use them for testing my PDP-11s. That's a really useful tool to have! 

To my amazement booting on the simh pdp-11/23 does not work whereas it works on the 11/23+ and many others. 

Would be nice if someone took the time to have a look at this!

Regards

Ulli

**Comment by markpizz** [comment]
Given your use goals (to manipulate images), can't you merely use it with a configuration that works and not worry about the failing case?

**Comment by markpizz** [comment]
My last comment suggests a solution which will readily meet your needs. and since I haven't heard anything back and as I mentioned above running diagnostics is not a target activity of the simulator set, I'm closing this issue now.
