### ISSUE TITLE
Request for a new simh PDP-11 device: TU58

### ISSUE THREAD

**Issue by vaxorcist** [simh/simh#226]
It would be very convenient to have the TU58 tape drive available for the series of simh PDP-11 computer simulations. As the TU58 is already implemented in the simh VAX-11/730 and VAX-11/750 simulators it is probably not too much work to make it available for the PDP-11s. 

Many thanks in advance for all those who take this project into consideration!

Any comments welcome.

Regards,

Ulli

**Comment by markpizz** [comment]
The latest code now has TU58 device support for all VAX simulators and the PDP11.  The device name is TDC.  Up to 16 controllers can be enabled which means that 32 drives should be available in addition to the console TU58s on the VAX730 and VAX750 simulators.

Please test and provide feedback.

Thanks.

**Comment by MattisLind** [comment]
Related to TU58:

Is it possible to boot the SimH pdp-11 from a TU58? I tried:
TDC: buffering file in memory
sim> b tdc0

Command not allowed, PC: 156034 (BEQ 156056)

Then I poked in a bootstrap I found at 

http://www.pdp-11.nl/ba11-boxes/ba11va/ba11va-info.html

d 1000 012701
d 1002 176500
d 1004 012702
d 1006 176504
d 1010 010100
d 1012 005212
d 1014 105712
d 1016 100376
d 1020 006300
d 1022 001005
d 1024 005012
d 1026 012700
d 1030 000004
d 1032 005761
d 1034 000002
d 1036 042700
d 1040 000020
d 1042 010062
d 1044 000002
d 1046 001362
d 1050 005003
d 1052 105711
d 1054 100376
d 1056 116123
d 1060 000002
d 1062 022703
d 1064 001000
d 1066 101371
d 1070 005007

sim> run 1000
TU58 protocol error 3

Simulation stopped, PC: 001052 (TSTB (R1))

So SimH is saying something about "TU58 protocol error 3"

Anyone else tried to boot SimH from TU58 successfully?

/Mattis

**Comment by markpizz** [comment]
Hi Mattis,

Before exploring the subject of booting from this device, Can you confirm that it actually works for any PDP-11 operating systems which can use it?  I haven't heard back from @vaxorcist about whether he thinks it actually works.  I only tested what I implemented on VMS.

If it actually works under several PDP-11 operating systems, we can explore booting.  Can you point at a disk image which would be useful to boot from?  Once we work out the boot program details, we can add the boot program to the device simulation.

- Mark

**Comment by R-Voorhorst** [comment]
Hi Mark,

 

yes, in the past we had a Lsi 23 booting TU58 on RT11, longtime ago though. Must have been RT11 V4 or something.

 

Best regards

**Comment by markpizz** [comment]
Hi Reindert,

Booting a TU58 device is what Mattis was asking for.

The question I asked was if the currently available TDC device in the simh PDP-11 simulator actually works to access data with several PDP-11 operating systems.  Once I know that the current device simulation actually works for PDP-11 operating systems we can look into the details of getting booting from that device working.

- Mark

**Comment by MattisLind** [comment]
Mark, 

I have no problem creating a TU58 image and read and write to it under RT11SJ v5.3.

But it is not possible to boot the image that I made: https://dl.dropboxusercontent.com/u/96935524/rt11v53_dd.dsk.gz

I have not been able to test the image on real hardware but I believe it correct. I did exactly the same steps when making a bootable RX01 image in SimH.

**Comment by markpizz** [comment]
@MattisLind The TU58 is now a bootable device (given a disk which is actually bootable).  The one you've provided boots.
