### ISSUE TITLE
Newest Win32-Development-Binaries are 5 month old

### ISSUE THREAD

**Issue by vaxorcist** [simh/simh#227]
The newest Win32-Development-Binaries are 5 month old despite much additions and changes dating later.

Is there a reason for this or just a mistake?

**Comment by markpizz** [comment]
It was merely a 'round-tuit'.  Although there have been minor changes, none triggered my 'this needs to be available to absolutely everyone' threshold to initiate a new build.

The latest commit is now reflected in the pre-compiled binaries.
