### ISSUE TITLE
Serial Multiplexer CONNECT fails to establish full-duplex communications (PDP11)

### ISSUE THREAD

**Issue by EJMarr** [simh/simh#234]
On a PDP-11 emulator, using the CONNECT option on ATTACH DLI (as documented in simh_tmxr.c) fails to set up full duplex communications. The Connector never seems to set up for receive on the socket it has created. Except it worked once for me - perhaps there is only a small timing window when it can work.

I have a zip file with further description of the set up, test logs and ini files, which I will mail separately.

**Comment by markpizz** [comment]
Mail the zip file to mark@infocomm.com

**Comment by markpizz** [comment]
This issue was fixed by Commit: 77152c6e20681ac1dab2dc14fa53da8a834064aa
