### ISSUE TITLE
Please provide a way to capture screenshots and save them to disk

### ISSUE THREAD

**Issue by shattered** [simh/simh#235]
I am working on simulator of AT&T DMD 5620 (using sethm's work on 3B2) and having a built in feature would be helpful.

**Comment by R-Voorhorst** [comment]
If in windows: activate screen to save, press alt+PrtScr and open paint, paste clipboard and save resulting bmp or otherwise if this describes your problem.

 

Best regards

**Comment by shattered** [comment]
I can certainly do that (or equivalent in Linux) but this request is about building this feature into SIMH.

**Comment by markpizz** [comment]
Hmmm...  Thanks for that clarification.

The only place a screen shot would fit as part of the simh framework would be to provide an API in the sim_video library which a device that is simulating a video display could capture the window's contents.  Is this what you're asking for?

**Comment by shattered** [comment]
I was thinking rather of some common code in sim_video, to avoid copy-pasting code into individual simulators.

**Comment by markpizz** [comment]
From what I can tell, Seth's existing 3b2 simulator doesn't use sim_video (yet).

In any case, feel free to propose code changes to sim_video that will do what you want.  Please outline your ideas in this issue so we can agree on the interface to this functionality which will be most generally useful.

**Comment by markpizz** [comment]
OK.  Don't bother messing with sim_video.  The latest code provides a SCREENSHOT command.  Let me know if this is what you were thinking or you need something else.

By the way, can you put your full name on your github profile.

Reindert, Can you contact me offline...  Thanks.

shartered:  Please close this issue if the latest code looks good.

**Comment by shattered** [comment]
With latest code, terminal screen is showing some funky colors instead of b/w bitmap (https://img-fotki.yandex.ru/get/15517/264743.3/0_b13d2_d9c09004_orig). Will debug that first.

**Comment by markpizz** [comment]
I see the URL that you provided as something which looks quite reasonable as a black & white bitmap.. What host OS and version are you running on?  What video card are you using?

Can you point me at some simh code and related data which demonstrates what you describe are experiencing?

**Comment by shattered** [comment]
That URL shows the expected bitmap.  I am running NetBSD in a VirtualBox VM (= no video acceleration).

Will push my code soon.  So far I've found that it works fine with SDL1 but breaks with SDL2; previously it worked fine with SDL2 as well.

**Comment by shattered** [comment]
https://github.com/shattered/simh/tree/wip-rebased is sethm's tree rebased to HEAD of simh + my current code.

**Comment by markpizz** [comment]
The latest code seems to work correctly when using SDL2.

Thanks for reporting this.

**Comment by shattered** [comment]
Verified.

However, with SDL2, I cannot stop simulation with C-e -- is that expected behaviour?  Again, this works with sethm's snapshot of simh.

**Comment by markpizz** [comment]
I certainly noticed that Control-E didn't work.  The reason is that for reliable escape back to the "sim> " prompt behavior you MUST call sim_poll_kbd somewhere.  It seems that you've commented this out in your uart device.  calling sim_poll_kbd needn't be in the uart device.  It could be in your vc_svc routine, but for efficientcy you should probably only call sim_poll_kbd a couple of times a second.  Keep a counter reflecting the number of times vc_svc() has been called and call sim_poll_kbd if (0 == (++counter % (VC_HZ/2))).

**Comment by markpizz** [comment]
As a follow on to your original request.  Screenshots will now produce ,png format screenshot files if libpng is available in the host system build environment, otherwise .bmp format screenshots will be produced.
