### ISSUE TITLE
MicroVAX 3900 won't boot 4.3BSD Quasijarus (0c) anymore

### ISSUE THREAD

**Issue by dugoh** [simh/simh#241]
Normally the relevant part in the autoconfiguration would be:
```
ra0 at uda0 slave 0: ra82, size = 1216665 sectors
dz0 at uba0 csr 160100 vec 300, ipl 17
dz1 at uba0 csr 160110 vec 310, ipl 17
qe0 at uba0 csr 174440 vec 764, ipl 14
qe0: delqa, hardware address 08:00:2b:aa:bb:cc
Changing root device to ra0a
Automatic reboot in progress...
```
After commit ed57f061e2f0f2362de51f1533424946623da6b8 for #239 it is
```
ra0 at uda0 slave 0: ra82, size = 1216665 sectors
stray scb intr vec 0xc4 ipl14
stray scb intr vec 0xc4 ipl14
stray scb intr vec 0xc4 ipl14
stray scb intr vec 0xc4 ipl14
stray scb intr vec 0xc4 ipl14
dz0 at uba0 csr 160100 didn't interrupt
trap type 1, code = 0, pc = 80002368
panic: Privileged instruction
syncing disks... done
```

The config is pretty bare
```
set cr disa
set lpt disa
set rl disa
set ts disa
set rq0 ra82
att rq0 quas.dsk
set rq1 disa
set rq2 disa
set rq3 disa
att tq0 quas.tap
set tti 7b
set tto 7b
set dz lines=8
att dz 8888
set dz 7b
att nvr nvram.dat
dep bdr 1
;sh dev
boot cpu
quit
```
..and everything else just stock.

I can perform CPR with a `set DZ DISABLE', but I'm otherwise looking at a dead canary and no clue yet where to point the blame at (quasijarus, this commit or me for even expecting this to work).

**Comment by markpizz** [comment]
Hi Jacob,

Hmm...  The DZ (and several other devices) have more than one vector per device.  We also need to add the appropriate vector bias for the vectors beyond the first.  Oops.
