### ISSUE TITLE
Questions on simh for simple Z80 system

### ISSUE THREAD

**Issue by gtackett** [simh/simh#255]
I'm interested in using **simh** to simulate a very simple Z80 based system.

I haven't looked very closely at **simh** support for such systems, other than to see that it does
support an Altair-like system based on the Z80 and some S-100 bus I/O devices, capable of running CP/M.

What I have in mind is a much simpler system:
* No need for S-100 devices
* Runnable as "bare metal" (no O/S or BIOS, etc.)
* Support for only these peripherals:
 * Z8420 PIO (2 channel parallel I/O)
 * Z8430 CTC (4 channel counter/timer)
 * Z8440 SIO (2 channel serial I/O)
 * CGC (Clock Generator Controller, originated at Toshiba as TMPZ84C61A)
 * WDT (Watch Dog Timer, also originated at Toshiba)

I need no real functionality for the CGC and WDT other than:
* I/O registers in the Z80 I/O address space,
 * Readable and writable as if they were ordinary RAM memory cells
 * Accessible via **simh** console control commands

Does the **simh** Z80 simulator already have any of these devices, or hooks I could use to deal with them?

**Comment by psco** [comment]
Currently the AltairZ80 does not support the above mentioned peripherals although I assume that some of the peripherals (in particular the I/O ones) are very similar to supported ones. There is also a timer for generating periodic interrupts but it does not conform to a specific chip.

That said it should still be relatively straightforward to implement the above mentioned peripherals provided appropriate data sheets are available and test software exists.

**Comment by markpizz** [comment]
Since there is nothing to fix here, I'm closing this issue.
