### ISSUE TITLE
Deposit issue with I/O Address Space in SimH PDP-11 Simulator

### ISSUE THREAD

**Issue by decuser** [simh/simh#261]
I am seeing a potential issue with the SimH PDP-11 simulation.

I was working with the simulator on bootloaders and was trying to deposit a value directly in the I/O register of the RK device. I tried the following in the default PDP-11/73 with 4MB Memory:

PDP-11 simulator V4.0-0 Beta        git commit id: 0f43551d
sim> d 17777410 177540
Address space exceeded

It would seem that 17777410 is outside of addressable memory. However, if I then put info into the buffer by typing in some machine code and executing it directly:

PDP-11 simulator V4.0-0 Beta        git commit id: 0f43551d
sim> id 10000-10006
10000:    012737
10002:    177540
10004:    177410
10006:    000000
sim> g 10000

HALT instruction, PC: 010010 (HALT)

and then reference the I/O buffer in SimH:

sim> ex 17777410
17777410:    177540

The I/O buffer now appears to be available in the address space using examine.

sim> ex 17777410
17777410:    177540

And for deposit:
sim> d 17777410 177530
sim> ex 17777410
17777410:    177530

Interestingly, Address  space exceeded doesn't appear to be a problem as it was at the beginning of the simh session.

Is the RK device supposed to be available at start or should it require a device access first. I asked on the mailing list and it was suggested that I open an issue.

**Comment by decuser** [comment]
Don North commented after I opened the issue:
Same issue exists in the pre-git version of SIMH. Looks like the I/O registers don't exist until the CPU
runs at least one instruction (in this case just a HALT).

local[518] pdp11
PDP-11 simulator V3.9-0
sim> ex 17777560-17777566
Address space exceeded
sim> de 0 0
sim> go 0
HALT instruction, PC: 000002 (HALT)
sim> ex 17777560-17777566
17777560:       000000
17777562:       000000
17777564:       000200
17777566:       000000

**Comment by decuser** [comment]
Updated text

**Comment by markpizz** [comment]
@decuser 

I think you should be good now.  

Please close this issue if you are happy.

Mark

**Comment by decuser** [comment]
Looks good to me.

**Comment by archivisth** [comment]
Depositing via IO register address is damned dangerous, because IO writes have side effects. The simulator is not proof against state changes that might occur this way.

Use the register names to deposit. That's what they are there for.

**Comment by markpizz** [comment]
The example above was crafted to demonstrate the issue in a simple form.

The real case involves hand entered bootstrap programs for very old unix enviroments.  In these cases the side effects you describe are what is desired.
