### ISSUE TITLE
Error in DMC11/DMR11 Emulation in RSTS/E 10.1

### ISSUE THREAD

**Issue by cmgauger** [simh/simh#262]
Most of this is transcluded from the e-mail originally sent to the mailing list.

There's an issue with the DMC device under RSTS/E 10.1-L.

When starting the system, when it does the hardware scan, the following errors are printed on the TTI/TTO console:
Device XM2: internal micro-diagnostic failure - device disabled.
Device XM3: internal micro-diagnostic failure - device disabled.
XM4: is missing ECO's, but will still function.
XM1: is missing ECO's, but will still function.
XM0: is missing ECO's, but will still function.

There are five DMC lines due to testing.
DMC0/XM0 and DMC1/XM1 are DMC11, with micro-diagnostics enabled.
DMC2/XM2 is a DMR11, with micro-diagnostics enabled.
DMC3/XM3 is a DMR11, with micro-diagnostics disabled.
DMC4/XM4 is a DMC11, with micro-diagnostics disabled.

From that test we can see that the DMR11 does not work under RSTS/E with or without micro-diagnostics; and further that DMC11 simulation works but isn't "up to date" enough for RSTS/E 10.1-L (at least I'm assuming that is what is meant by the "missing ECO's" statement).

It exhibits this behaviour both when starting up SYSGEN.SIL, and when doing a normal system start-up. The simulator is configured as a UNIBUS machine (11/94 if that matters); trying it with a QBUS machine (11/93)... and SIMH crashes promptly.

Here's the "show version" output for completeness' sake:
sim> show version
PDP-11 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                32b data
                32b addresses
                Ethernet Packet transports:PCAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                FrontPanel API Version 1
        Host Platform:
                Compiler: Microsoft Visual C++ 15.00.30729.01
                Simulator Compiled: Dec 19 2015 at 12:51:02
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 1ms
                OS: Windows:
Microsoft Windows [Version 6.1.7601]
                Intel64 Family 6 Model 58 Stepping 9, GenuineIntel - x86-AMD64

```
    git commit id: ca4a6901
```

Unfortunately, I have not been able to find the driver sources for either the DMC11 or DMR11 within RSTS/E 10.1-L.

**Comment by markpizz** [comment]
Christian,

Now that Paul Koning provided the key parts of the driver, I can fix the simulation as long as I can test it.

Can you provide a configuration file and a disk image which demonstrates the above failure?

Please provide it in a publicly readable Google Drive or DropBox file

Thanks.

- Mark

**Comment by R-Voorhorst** [comment]
This problem is solved and could be closed. Paul delivered a patch for the Dmc driver in RstsE-10.1 and it works ok now, 
By the way (non) idling behavior on RstsE-10.1 is also fixed.
