### ISSUE TITLE
vax750 console tu58 writes to output file when set as locked

### ISSUE THREAD

**Issue by hbent** [simh/simh#266]
This is all with the latest sources from git.

When restoring VMS 4.0 from a standalone backup on a vax750, the console TU58 is written to even if it is set as locked:

sim> sh td
TD
        262KB, attached to BE-CT97A-BE.TAP, write locked
sim> boot td
Loading boot code from internal vmb.exe

Please remove the volume "SYSTEM_1" from the console device.

Insert the first standalone system volume and enter "YES" when ready: YES

Resuming load operation on volume "SYSTEM_1", please stand by . . .

Please remove the volume "SYSTEM_1" from the console device.

Insert the next standalone system volume and enter "YES" when ready: 
Simulation stopped, PC: 000089D8 (MFPR #20,R0)
sim> det TD
TD: writing buffer to file
sim> show td
TD
        262KB, not attached, write locked

The backup tapes I'm using are from ftp://pdp-11.trailing-edge.com/pub/iamvirtual.ca/VAX11/VAX-11-software.html .

**Comment by markpizz** [comment]
At first glance, this sounded worse than it actually is.  I thought that you meant that it allowed the simulator to write to the device.  Maybe it does, can you confirm that or not.

Independent of the concern I just raised, clearly writing out the contents of a write-locked device image shouldn't be necessary, but if my concern above is true, it should be benign and not change anything.

Meanwhile, it should be fixed, but this same problem may also exist for all devices which buffer the disk contents in memory.  Finding all of these will take some digging.

**Comment by hbent** [comment]
In this situation the contents of the local file were not changed.  I will see if I can find an example where the console device might have a write attempt while locked.

**Comment by hbent** [comment]
I can confirm that under Ultrix 4.3 the console tape is successfully write protected:

# dd if=/sys/consoles/vax/750cons/750console of=/dev/tu0
tu0: hard error bn0, pk_status 365 (Write Protected)
tu0: hard error bn0, pk_status 365 (Write Protected)
tu0: hard error bn0, pk_status 365 (Write Protected)
...

And in that instance when I dropped back to simh and did a "det td" I did not get a "TD: writing buffer to file" message.

**Comment by markpizz** [comment]
Actually, the current behavior might be considered 'as designed'.

If you had done:

    sim> att -R td tu58.img
you WOULD NOT see the writing buffer when you detach and simulated write operations would fail.

if you did:

    sim> att td tu58.img
    sim> set td locked
you WOULD see the writing buffer when you detach, but any simulated write operations performed after the "set td locked" command were executed will fail as you observed.

The same logic goes for most, if not all, other devices which have the ability to write lock the device with a user command.

Make sense?

**Comment by hbent** [comment]
OK, that makes sense, but it even happens if I do the commands in the reverse order:

`sim> set td lock`
`sim> att td BE-CT97A-BE.TAP`
...
`sim> det td`
`TD: writing buffer to file`

**Comment by markpizz** [comment]
That is still the same behavior since setting the device write-locked doesn't cause an open/attach to be read-only.  The buffer contents is written out if the file was open read/write and it is not if it is opened read-only.

**Comment by hbent** [comment]
I certainly understand your logic, but it just doesn't seem intuitive to me.  Shouldn't setting a virtual write-lock switch affect all of the actions that follow?  That's always how other tape devices have worked, at least in my experience.

**Comment by markpizz** [comment]
As soon as you set the virtual write lock switch, no further changes will happen to the buffered data.  That is certainly true.  

Meanwhile, if you initially opened the device read/write and you actually wrote something before you set the virtual write-lock switch, the change you made absolutely should make it back to the original file.

As soon as you opened the file read/write (even if you set the virtual write lock switch before doing that) you've changed the host system's timestamps on the file.  Writing out a buffer containing unchanged data does no harm.

**Comment by hbent** [comment]
I suppose I was thinking of a write lock as pertaining to the file on the local OS as well as the data in the simulator.  Well, in any case, if I'm that worried about my local data I can always set permissions such that SIMH can't write to the local file.  I'll go ahead and close this.

**Comment by markpizz** [comment]
If you want the OS to manage the concept, then you open/attach the file read only with the -R switch.

If you set file permissions in the host OS to limit write access, then the read/write open/attach will fail and you'll be forced to open/attach with -R to access the data.

The LOCKED device modifier changes the behavior of the simulated device but doesn't influence activities to the OS file system.

There is an odd cosmetic combination here...  If you do a read only open/attach, but don't set the device LOCKED, then a SHOW TD will not reflect the fact that the file is opened read/only, but write operations will still fail as if you'd explicitly set the device LOCKED.  Fixing this would require changes to essentially all device simulators which have a LOCKED device modifier.  This is too much change for too little gain.
