### ISSUE TITLE
Mouse basically unusable in X11R1 on MicroVAX 2 QVSS

### ISSUE THREAD

**Issue by hbent** [simh/simh#272]
Using the latest git sources, X11R1 on Ultrix 2.3 has great difficulties with the mouse.  In uncaptured input mode the mouse jumps around wildly and is totally unusable.  In captured input mode it still jumps around but it can at least be moved within a window, etc.

An image that can be used to demonstrate the problem is at http://ajlc.csr.oberlin.edu/hbent/ultrix23.tar.bz2 , root password is alpine.  Running /usr/bin/X11/xinit will get you an X server, a window manager, and an xterm which is enough to demonstrate the problem.

sim> show version
VAXStation II (KA630) simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:TAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                Asynchronous I/O support
                FrontPanel API Version 1
        Host Platform:
                Compiler: GCC 6.0.0 20160126 (experimental)
                Simulator Compiled: Jan 30 2016 at 08:33:41
                Memory Access: Little Endian
                Memory Pointer Size: 64 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.4
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 2ms
                OS: NetBSD aelfric 7.0 NetBSD 7.0 (AELFRIC) #0: Tue Dec 29 12:28:45 EST 2015  root@aelfric:/usr/src/sys/arch/amd64/compile/AELFRIC amd64

```
    git commit id: b8049645
```

**Comment by mike632t** [comment]
Had a similar issue with Ultrix 4.4 (#193) not had time to investigate further with libSDL2

**Comment by pghardy** [comment]
I get same issue on a VMS VAXstation on current SimH windows executable - graphics screen comes up, I can login, but then can't click on session menu - brings up pop-up menus at random places on screen, as if mouse position is being mangled.

**Comment by mjjerabek** [comment]
Built simh on Raspberry PI 2 and Raspberrian. Running vaxstation 3900 with vms 7.3/DECwindows 1.2-6. Mouse and keyboard input not good. A little of the problem might be using an under powered Pi as host. See config below. When not  using graphics, the wim of a VAX is great.

Mjj

sim> sh version
MicroVAX 3900 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:TAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 4.6.3
                Simulator Compiled: Apr 15 2016 at 22:20:55
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 1.2.15
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 2ms
                OS:
        git commit id: b502558d

pi@raspberrypi ~/VMS $ ./vax vax.ini

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: b502558d
Memory size changed: CPU0 = 512MB
NVR: buffering file in memory
libpcap version 1.3.0
Eth: opened OS device tap0
sim> set QVSS CAPTURE
sim> sh config
MicroVAX 3900 simulator configuration

CPU     idle=VMS, idle enabled, model=VAXServer 3900 (KA655), AUTOBOOT
        512MB, HALT to console
TLB     2 units
  TLB0  8192W
  TLB1  8192W
ROM
        128KB, 1usec calibrated access
NVR
        1024B, attached to nvram.bin
SYSD    2 units
  SYSD0
  SYSD1
QBA     autoconfiguration enabled
CLK     vector=C0
        8B
TTI     vector=F8
        8b
TTO     vector=FC
        8b
CSI     vector=F0
CSO     vector=F4
        not attached
TDC     disabled
DZ      disabled
VH      disabled
CR      address=20001E70-20001E77, vector=298, 285 cards per minute
        translation=029
        not attached, CR11, auto EOF
        unknown format
LPT     address=20001F4C-20001F4F, vector=280
        not attached
QVSS    disabled
LK      disabled
VS      disabled
RL      disabled
RQ      address=20001468-2000146B, vector=3FC*, RQDX3, 4 units
  RQ0   1216MB, attached to VAXVMS073.DSK, write enabled
        RA90, autosize, SIMH format
  RQ1   1216MB, attached to JUNK.DSK, write enabled
        RA90, autosize, SIMH format
  RQ2   681MB, attached to VAXVMS73CD.ISO, read only
        RRD40, autosize, SIMH format
RQB     disabled
RQC     disabled
RQD     disabled
TS      disabled
TQ      disabled
XQ      address=20001920-2000192F, vector=250, MAC=AA:00:04:00:01:04
        type=DELQA-T, polling=disabled, sanity=OFF
        throttle=disabled, DEQNALock=OFF, leds=(ON,ON,ON)
        attached to tap:tap0
XQB     disabled

**Comment by markpizz** [comment]
@mjjerabek Can you:
1) Provide the vax.ini file contents.
2) Explain how/why there is no detail following the OS: line of the SHOW VERSION output. On my Pi test system the line contains: "OS: Linux raspberrypi 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux"

Thanks.

- Mark

**Comment by mjjerabek** [comment]
#1 

vax.ini

pi@raspberrypi:~/VMS $ cat vax.ini
load -r ka655x.bin
attach nvr nvram.bin
set rq0 ra90
attach rq0 VAXVMS073.DSK
set rq1 ra90
attach rq1 JUNK.DSK
set rq2 rrd40
attach rq2 VAXVMS73CD.ISO
set cpu conhalt
set console notelnet, wru=10
set cpu autoboot
set cpu idle=vms
set cpu 512m
set tq disable
set ts disable
set rl disable
set dz disable
set cr disable
set xq mac=AA:00:04:00:01:04
attach xq tap:tap0

Manually at simh command prompt I add

set cPU MODEL=vaxstation
B CPU

#2 

Show VERSION output follows:

sim> sh version
MicroVAX 3900 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:TAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 4.9.2
                Simulator Compiled: Apr 18 2016 at 00:19:44
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.2
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 2ms
                OS: Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux
        git commit id: b502558d

I do not get anything else. Built simh from get master.zip pull on Raspberry pi 3. I did nothing strange ...

Mjj

**Comment by markpizz** [comment]
Hi Mjj,

This is different from your earlier SHOW VERSION output.  Specifically, the source seems to be the same (b502558 commit), but the previous OS info was missing and the previous SDL was  SDL 1.2.15 and now you've got SDL 2.0.2 along with a significantly different GCC version.  My Pi 2 test system only has SDL 1.2.15 available and the same GCC as your original SHOW VERSION.

I actually see useful behavior with VMS 7.3 running on my Pi2.
![vms-7 3-decwindows](https://cloud.githubusercontent.com/assets/422671/14654336/10448024-0632-11e6-993d-434516a679f7.png)

Changing SDL versions changes many things in the simulator, so I'd be very surprised if simulators with both of these SDL versions actually behave in the same way.

The configuration I ran with was essentially what you've got except I only had 128MB of RAM configured.

How did you get from the earlier Pi2 OS to the newer one you're currently using?  How did SDL end up on the system?

**Comment by mjjerabek** [comment]
Between the original post and now I upgraded to a Pi 3 and the version of Raspberian OS that came with it. I immediately did an apt-get upgrade/update of everything.

After that I did some google research and found a reference to using libsdl 2 to solve getting graphics to work, so I updated to libsdl2-dev.

I did a rebuilt of all simh (make clean, make).

Now, when I run the config (./vax vax.ini) I get better graphics, sort of ... If I try to pickup the DECterm by the title bar I get the equivalent of RIGHT-CLICK/Minimize window. Mice and keyboards are still doing funny things.

Looks like expose events in the QVSS windows do not work properly.

If a Raspberian windows or menu covers and then uncovers the QVSS windows, the QVSS window expose events do not repaint the QVSS windows contents.

If you iconify and de-iconify the QVSS window you get an empty window.

I am having fun with this. Will have to become familiar with the source code.

Mjj

**Comment by markpizz** [comment]
Well, you're ahead of me.  Both libSDL and libSDL2 are supported during the build.  If libSDL2 is available it is preferred.  You should be able to uninstall libsdl2-dev and use libsdl to test with.

I see the problem with trying to drag a DECterm by the title bar.  I also see some funny things with mouse activities.  I don't see the expose event problems you are describing.  This could easily be a libSDL vs libSDL2 difference.  Current libSDL2 is 2.0.4, so 2.0.2 is sort of old.

Fixes for either the libSDL or libSDL2 cases are welcome.

**Comment by hbent** [comment]
This is now fixed!  Thanks!
