### ISSUE TITLE
Serial ports aren't detected on NetBSD

### ISSUE THREAD

**Issue by hbent** [simh/simh#273]
Under NetBSD with the latest git sources, no serial ports are detected:

sim> show serial
Serial devices:
  no serial devices are available

This is because the fallback probe for Unix in sim_serial.c doesn't look for /dev/tty[00-63] which are the standard serial port devices on NetBSD.  FWIW it's probably worth probing for /dev/ttyU[0-7] as well which are USB serial ports.  Adding these probes fixes things for me:

sim> show serial
Serial devices:
 ser0   /dev/tty00
 ser1   /dev/tty01

**Comment by markpizz** [comment]
Thanks for finding this.

**Comment by hbent** [comment]
Detection needs to start at zero:

--- sim_serial.c.orig   2016-01-31 15:04:19.000000000 -0500
+++ sim_serial.c        2016-02-01 09:48:01.000000000 -0500
@@ -974,7 +974,7 @@
         close (port);
         }
     }
-for (i=1; (ports < max) && (i < 64); ++i) {
+for (i=0; (ports < max) && (i < 64); ++i) {
     sprintf (list[ports].name, "/dev/tty%02d", i);
     port = open (list[ports].name, O_RDWR | O_NOCTTY | O_NONBLOCK);     /* open the port */
     if (port != -1) {                                   /* open OK? */
@@ -983,7 +983,7 @@
         close (port);
         }
     }
-for (i=1; (ports < max) && (i < 8); ++i) {
+for (i=0; (ports < max) && (i < 8); ++i) {
     sprintf (list[ports].name, "/dev/ttyU%d", i);
     port = open (list[ports].name, O_RDWR | O_NOCTTY | O_NONBLOCK);     /* open the port */
     if (port != -1) {                                   /* open OK? */

**Comment by markpizz** [comment]
Oops.  :-)
