### ISSUE TITLE
PDP11 TU58 bootstrap fails

### ISSUE THREAD

**Issue by AK6DN** [simh/simh#285]
Booting a TU58 TDCx device fails in SIMH. The first byte of the 512B bootstrap in block zero is dropped. The block appears to be read correctly by SIMH, but it skips over byte zero in returning the data to the PDP11 host. This is because the DONE flag is not set when reading byte 0 from the buffer.

After line 1023:
```
      ctlr->rx_buf = ctlr->obuf[ctlr->obptr++];   /* get first byte */
```

Add two lines to make this sequence:
```
       ctlr->rx_buf = ctlr->obuf[ctlr->obptr++];   /* get first byte */
       ctlr->rx_csr |= CSR_DONE;                   /* set input flag */
       if (ctlr->rx_csr & CSR_IE) CSI_SET_INT;  /* interrupt if enabled */
```

Don

```
    case TD_OPBOO:
        if (ctlr->ibptr < 2) {                          /* whole packet read? */
            ctlr->ilen = 2;
            ctlr->o_state = TD_GETDATA;                 /* get rest of packet */
            return;
            }
        else {
            int8 *fbuf;
            int i;

            sim_debug (TDDEB_TRC, ctlr->dptr, 
                     "td_process_packet(OPBOO) Unit=%d\n", ctlr->ibuf[4]);
            ctlr->unitno = ctlr->ibuf[1];
            fbuf = ctlr->uptr[ctlr->unitno].filebuf;
            ctlr->block = 0;
            ctlr->txsize = 0;
            ctlr->p_state = TD_READ2;
            ctlr->offset = 0;
            ctlr->obptr = 0;

            for (i=0; i < TD_NUMBY; i++)
                ctlr->obuf[i] = fbuf[i];
            ctlr->olen = TD_NUMBY;
            ctlr->rx_buf = ctlr->obuf[ctlr->obptr++];   /* get first byte */
```
```
            ctlr->rx_csr |= CSR_DONE;                   /* set input flag */
            if (ctlr->rx_csr & CSR_IE) CSI_SET_INT;  /* interrupt if enabled */
```
```
            sim_data_trace(ctlr->dptr, &ctlr->uptr[ctlr->unitno],
                          ctlr->obuf, "Boot Block Data", ctlr->olen, "", TDDEB_DAT);
            sim_activate (ctlr->uptr+ctlr->unitno, td_ctime);/* sched command */
            }
        break;

    case TD_OPCNT:
        break;
```
Here is a partial section of the debug log output from SIMH. Notice that the first databyte 0xA0 is never returned, but data starts with 0x00 (byte1) then 0x20 (byte2) ...

```
DBG(930594)> TDC OWR: td_wr_o_buf()  o_state=GETDATA, ibptr=1, ilen=2
DBG(930594)> TDC OWR: TX_BUF: DAT=0x0
DBG(930594)> TDC TRC: td_process_packet() Opcode=OPBOO(8)
DBG(930594)> TDC TRC: td_process_packet(OPBOO) Unit=0
DBG(930594)> TDC DAT: TDC0  Boot Block Datalen: 00000200
DBG(930594)> TDC DAT: 0000 A0 00 20 01 06 00 00 00 0A 00 00 00 00 00 00 00 .. .............
DBG(930594)> TDC DAT: 0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
DBG(930594)> TDC DAT: 0020 thru 002F same as above
DBG(930594)> TDC DAT: 0030 00 00 00 00 00 00 00 00 02 0A 02 00 00 00 00 00 ................
DBG(930594)> TDC DAT: 0040 00 02 08 00 C6 15 00 60 05 00 C3 15 30 00 C2 15 .......`....0...
DBG(930594)> TDC DAT: 0050 03 00 53 10 D1 0B C2 0A FC 02 E6 17 04 00 DF 15 ..S.............
DBG(930594)> TDC DAT: 0060 6A 00 04 00 C9 0B 4B 10 03 01 CB 1D C4 FF 96 25 j.....K........%
DBG(930594)> TDC DAT: 0070 9F 15 04 00 F7 15 08 00 C8 FF C4 15 00 02 37 10 ..............7.
DBG(930594)> TDC DAT: 0080 BA FF E6 15 08 00 03 0A BF 0A A8 FF F7 09 E8 00 ................
DBG(930594)> TDC DAT: 0090 FF 0A A0 FF C3 15 04 04 FF 0B 96 FF F7 09 DC 00 ................
DBG(930594)> TDC DAT: 00A0 03 0A F7 09 EA 00 C3 00 C3 A5 10 00 04 03 CE 0A ................
DBG(930594)> TDC DAT: 00B0 EA 02 D6 0B 58 01 D6 0B B7 0A 86 FF F7 25 28 00 ....X........%(.
DBG(930594)> TDC DAT: 00C0 80 FF 06 02 C2 1D 74 FF C1 1D 64 FF 5F 00 26 02 ......t...d._.&.
DBG(930594)> TDC DAT: 00D0 F7 09 96 00 02 0A C0 15 38 00 02 64 42 0B C1 8A ........8..dB...
DBG(930594)> TDC DAT: 00E0 FC 02 88 10 F7 09 82 00 C0 15 38 00 03 14 F7 09 ..........8.....
DBG(930594)> TDC DAT: 00F0 8A 00 C1 8A FB 80 F7 09 92 00 C3 A5 01 00 12 02 ................
DBG(930594)> TDC DAT: 0100 C2 10 C3 00 C1 90 C1 45 00 FF 81 0C F7 09 7C 00 .......E......|.
DBG(930594)> TDC DAT: 0110 D4 10 C2 60 42 0B C1 8A F9 02 F7 09 6E 00 C2 20 ...`B.......n..
DBG(930594)> TDC DAT: 0120 EA 03 22 01 C3 A5 02 00 1E 02 C2 10 C3 00 C1 90 ..".............
DBG(930594)> TDC DAT: 0130 C1 45 00 FF 81 8C F7 09 52 00 C3 A5 40 00 13 02 .E......R...@...
DBG(930594)> TDC DAT: 0140 C3 0B 11 81 C2 60 42 0B C1 8A F7 09 3E 00 C2 60 .....`B.....>..`
DBG(930594)> TDC DAT: 0150 42 0B C1 8A FA 02 C3 0B 06 81 F7 09 2E 00 C2 20 B..............
DBG(930594)> TDC DAT: 0160 03 02 77 00 52 FF 00 00 00 00 C1 9D CB FE C1 45 ..w.R..........E
DBG(930594)> TDC DAT: 0170 00 FF 81 0C 81 0A 87 00 CF 09 CF 09 CF 09 FF 90 ................
DBG(930594)> TDC DAT: 0180 B4 FE C3 00 FF 8B AC FE FD 80 87 00 03 0A CF 09 ................
DBG(930594)> TDC DAT: 0190 FF 8B 9C FE FD 80 C5 1F 98 FE E5 81 43 D1 C3 00 ............C...
DBG(930594)> TDC DAT: 01A0 87 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
DBG(930594)> TDC DAT: 01B0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
DBG(930594)> TDC DAT: 01C0 thru 01FF same as above
DBG(930597)> TDC RRD: td_rd(PA=17776500(RX_CSR), access=0-Read)
DBG(930597)> TDC IRD: RX_CSR: DONE0 IE0
DBG(930599)> TDC RRD: td_rd(PA=17776500(RX_CSR), access=0-Read)
...
DBG(930763)> TDC IRD: RX_CSR: DONE1 IE0
DBG(930765)> TDC RRD: td_rd(PA=17776502(RX_BUF), access=0-Read)
DBG(930765)> TDC IRD: RX_BUF: ERR0 OVR0 RBRK0 DAT=0x00 <--------------------DATA=00
DBG(930767)> TDC RRD: td_rd(PA=17776500(RX_CSR), access=0-Read)
...
DBG(930943)> TDC IRD: RX_CSR: DONE1 IE0
DBG(930945)> TDC RRD: td_rd(PA=17776502(RX_BUF), access=0-Read)
DBG(930945)> TDC IRD: RX_BUF: ERR0 OVR0 RBRK0 DAT=0x20 <--------------------DATA=20
DBG(930947)> TDC RRD: td_rd(PA=17776500(RX_CSR), access=0-Read)

```

**Comment by markpizz** [comment]
I know I tested the PDP11 boot or I wouldn't have included it.  I'll have to dig up my original test case to see how I convinced myself that it was good.

**Comment by AK6DN** [comment]
All the .dsk files on this page are bootable TU58 images on the PDP-11:
    http://ak6dn.dyndns.org/PDP-11/TU58/

With the existing code here is what I see in memory starting at zero when I execute the boot command:
```
+0000:  000 040 001 006 000 000 000 012 000 000 000 000 000 000 000 000
+0020:  000 000 000 000 000 000 000 000 000 000 000 000 000 000 000 000
+0040:  000 000 000 000 000 000 000 000 000 000 000 000 000 000 000 000
+0060:  000 000 000 000 000 000 000 002 012 002 000 000 000 000 000 000
+0100:  002 010 000 306 025 000 140 005 000 303 025 060 000 302 025 003
+0120:  000 123 020 321 013 302 012 374 002 346 027 004 000 337 025 152
+0140:  000 004 000 311 013 113 020 003 001 313 035 304 377 226 045 237
+0160:  025 004 000 367 025 010 000 310 377 304 025 000 002 067 020 272
+0200:  377 346 025 010 000 003 012 277 012 250 377 367 011 350 000 377
+0220:  012 240 377 303 025 004 004 377 013 226 377 367 011 334 000 003
+0240:  012 367 011 352 000 303 000 303 245 020 000 004 003 316 012 352
...
```

Here is what it should be, and is, after I applied the code update indicated above:
```
+0000:  240 000 040 001 006 000 000 000 012 000 000 000 000 000 000 000
+0020:  000 000 000 000 000 000 000 000 000 000 000 000 000 000 000 000
+0040:  000 000 000 000 000 000 000 000 000 000 000 000 000 000 000 000
+0060:  000 000 000 000 000 000 000 000 002 012 002 000 000 000 000 000
+0100:  000 002 010 000 306 025 000 140 005 000 303 025 060 000 302 025
+0120:  003 000 123 020 321 013 302 012 374 002 346 027 004 000 337 025
+0140:  152 000 004 000 311 013 113 020 003 001 313 035 304 377 226 045
+0160:  237 025 004 000 367 025 010 000 310 377 304 025 000 002 067 020
+0200:  272 377 346 025 010 000 003 012 277 012 250 377 367 011 350 000
+0220:  377 012 240 377 303 025 004 004 377 013 226 377 367 011 334 000
+0240:  003 012 367 011 352 000 303 000 303 245 020 000 004 003 316 012
...
```
If you inspect the dumps carefully, you find that the original one is correct, but just shifted down in memory by one byte, and the leading 240(8) is missing. All DEC standard bootstraps for the PDP-11 start with a NOP instruction (000240(8) in 16 bits, or 240(8) in the first byte) as a flag.

Don

**Comment by AK6DN** [comment]
Another issue found when testing the 'bootstrap' command (command flag 10(8). After sending the command byte 10(8), followed by the unit id number byte, the TU58 should return exactly 512. bytes of data from block 0 of the tape image file. This is being done.

The TU58 should then go to the command idle loop, waiting for the next command packet from the host. However, as currently implemented, the TU58 goes to the code to send an END packet response (like would happen after a programmed read of block 0 512. bytes). This behavior is NOT correct protocol. There is NO end packet that should be sent after the bootstrap command.

When looking at the code in pdp11_td.c, I see an OPBOO command goes to state TD_READ2, which can then go to state TD_READ1 or TD_END. TD_END goes to TD_END1 which goes to TD_IDLE. In fact the transition thru TD_END/TD_END1 is incorrect for an OPBOO, after the last data byte is sent to the host the TU58 should transition to state TD_IDLE. NO END packet.

**Comment by AK6DN** [comment]
By the way this bootstrap functionality should apply exactly the same to the operation of the TU58 on a PDP11 or a VAX system. There is nothing PDP11 specific about this bootstrap functionality.

**Comment by AK6DN** [comment]
Attached is the original pdp11_td.c as pdp11_td.c.orig and my updated version as pdp11_td.c.

The updated file fixes the above bootstrap function issues (both the first byte and end packet issue) and also fixes the 'unimplemented functions' issue I opened as #287 

The updated pdp11_td.c now runs my PDP11 macro11 TU58 test program as expected. If you want I can supply the sources and assembled PDP11 binary file.

The following .zip contains the original pdp11_td.c (as .orig) and my updated version (as .c).

[pdp11_td.c.zip](https://github.com/simh/simh/files/175479/pdp11_td.c.zip)

**Comment by markpizz** [comment]
> By the way this bootstrap functionality should apply exactly the same to the operation of the TU58 on a PDP11 or a VAX system. There is nothing PDP11 specific about this bootstrap functionality.

Absolutely true.  

The only PDP11 simulator specific functionality in the pdp11_td.c source code is the presence of the PDP11 bootstrap code which is actually a piece of the PDP11 simulator directly 'related' to the TDC device rather than an internal feature of a real TU58.  As it turns out, the VAX730 and VAX750 boot ROMS don't actually use the TU58 BOOT commands to boot the respective systems.

**Comment by AK6DN** [comment]
I have downloaded and recompiled the new version with the updates to pdp11_td.c.

My PDP11 macro code regression test passes, as well as both a command line boot (via:  b_ tdc0) and a programmed boot (issue TU58 'boot' command, read and validate data) pass successfully.

Issuing the INIT, GetStatus, SetStatus, Diagnose commands all behave as expected (just return an END packet indicating success).

Issuing a Position (seek) command with both valid (0..511) and invalid (512...65535) block numbers returns either a success or fail (bad block) status, as expected.
