### ISSUE TITLE
VH hardware errors on Ultrix 4.5

### ISSUE THREAD

**Issue by hbent** [simh/simh#296]
I occasionally see VH hardware errors on Ultrix 4.5.  I believe I have also seen them on 3.0, but I'm not sure.  I have seen them during normal use but am not sure how to reproduce them.  The surefire way seems to be to halt the system (with "shutdown -h now"):

dhu0,line7 DHU HARDWARE ERROR.  TX.DMA.START failed
dhu0,line6 DHU HARDWARE ERROR.  TX.DMA.START failed
dhu0,line2 DHU HARDWARE ERROR.  TX.DMA.START failed
dhu0,line5 DHU HARDWARE ERROR.  TX.DMA.START failed

What is interesting is that this is for lines that are not in use, and have not been in use previously (I generally only use lines 0 and 1).

show version:
VAX 8600 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:TAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                Asynchronous I/O support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 6.0.0 20160323 (experimental)
                Simulator Compiled: Mar 24 2016 at 11:35:41
                Memory Access: Little Endian
                Memory Pointer Size: 64 bits
                Large File (>2GB) support
                SDL Video support: No Video Support
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 2ms
                OS: NetBSD aelfric 7.0 NetBSD 7.0 (AELFRIC) #0: Tue Dec 29 12:28:45 EST 2015  root@aelfric:/usr/src/sys/arch/amd64/compile/AELFRIC amd64
        git commit id: e7f7b10f

**Comment by markpizz** [comment]
Please provide a disk image, configuration file and potentially driver source which contains the message being produced.

**Comment by hbent** [comment]
I am also seeing "Warning: DHU device failed to exit self-test" on startup.
The original issue only seems to trigger if you connect to the VH (over telnet) and issue a shutdown from there.

Ultrix 4.3 disk image for a vax8600, which displays the problem:
https://www.mediafire.com/?nuwmrel09n0g927

Ultrix 4.3 DHU driver: http://pastebin.com/WQiYPYKw

reduced config file, also included with the disk image:
set cpu idle=ultrix
set cpu 64m
set rq0 ra82
att rq0 ra82.dsk
set rq1 dis
set rq2 dis
set rq3 dis
set cr dis
set rp dis
set hk dis
set ry dis
set lpt dis
set rl dis
set tq dis
set tu dis
set ts lock
set xu enabled
set xu MAC=08:00:2B:1C:43:99
set xu type=deuna
att xu tap:tap0
set dz disabled
set vh enabled
set vh lines=16
att vh 4500
att todr vax8600.todr
boot rq0

**Comment by markpizz** [comment]
The "Warning: DHU device failed to exit self-test" problem is easy to reproduce and I've fixed it.

I've seen the "dhu0,line7 DHU HARDWARE ERROR. TX.DMA.START failed" message once.  As you said it happens during a shutdown.  I suspect that this correlates to a shutdown message being sent to all lines mentioned on /etc/ttys.

If I follow the flow of normal output activities to any given line it seems that data output to a line which isn't connected should merely be dropped on the floor and, in general, errors should not occur.  There does seem to be some effort to Hangup a line which produces an output error (i.e. the line isn't connected).  This Hangup activity may create some transitional conditions which could change the line state to a condition where it doesn't actually try to send it, but decides earlier that th line isn't in good shape.  I don't actually see a path that does this, but I'm thinking that is why it doesn't occur consistently.

The dhu.c includes 2 other files: "dhu.h" and "../data/dhu_data.c".  Can you find these files?

**Comment by hbent** [comment]
dhu_data.c: http://pastebin.com/UYgxwTyE
dhureg.h: http://pastebin.com/vq36x2bS

**Comment by markpizz** [comment]
I think things are good now.  Please give the latest code a try.

**Comment by hbent** [comment]
Yes, everything looks good on this end.  Thanks!  Closing.
