### ISSUE TITLE
Multiple build errors for commit 736e341

### ISSUE THREAD

**Issue by polaris6262** [simh/simh#297]
Commit 736e341 fails to build on both openSUSE Leap 42.1 and Tumbleweed as well as on Sabayon 16.04, a Gentoo-derived distribution. Although the actual error differs between the openSUSE distributions and Sabayon, I believe they're both related to the recent use of sdl2-config in the build process.

The error for openSUSE Leap 42.1 and Tumbleweed is as follows:

lib paths are: /lib/ /lib64/ /usr/lib/ /usr/lib64/ /usr/lib64/graphviz/ /usr/local/lib64/
include paths are:  /usr/lib64/gcc/x86_64-suse-linux/5/include /usr/local/include /usr/lib64/gcc/x86_64-suse-linux/5/include-fixed /usr/lib64/gcc/x86_64-suse-linux/5/../../../../x86_64-suse-linux/include /usr/include
using libm: /usr/lib64/libm.so
using librt: /usr/lib64/librt.so
using libpthread: /usr/lib64/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib64/libpcreposix.so /usr/include/pcreposix.h
using libdl: /usr/lib64/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib64/libpng.so /usr/include/png.h
using mman: /usr/include/sys/mman.h
using libSDL2: /usr/include/SDL2/SDL.h
using libpcap: /usr/include/pcap.h
*** Info ***
*** Info *** all sigma alpha Simulators are being built with
*** Info *** minimal libpcap networking support
*** Info ***
*** Info *** Simulators on your Linux platform can also be built with
*** Info *** extended LAN Ethernet networking support by using VDE Ethernet.
*** Info ***
*** Info *** To build simulator(s) with extended networking support you
*** Info *** should read 0readme_ethernet.txt and follow the instructions
*** Info *** regarding the needed libvdeplug components for your Linux
*** Info *** platform
*** Info ***
***
*** all sigma alpha Simulators being built with:
*** - compiler optimizations and no debugging support. GCC Version: 5.2.1.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
***
*** git commit id is 736e341fd24af5b35968d1418e89f2ca5c935e8c.
***
font paths are: /usr/share/fonts/
font names are: DejaVuSans.ttf LucidaSansRegular.ttf FreeSans.ttf AppleGothic.ttf tahoma.ttf
mkdir -p BIN
gcc -march=native -m64 -std=gnu99 -U__STRICT_ANSI__  -O3 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=736e341fd24af5b35968d1418e89f2ca5c935e8c -DSIM_COMPILER="GCC Version: 5.2.1" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_LIBPNG -DHAVE_GLOB -DHAVE_SHM_OPEN  PDP1/pdp1_lp.c PDP1/pdp1_cpu.c PDP1/pdp1_stddev.c PDP1/pdp1_sys.c PDP1/pdp1_dt.c PDP1/pdp1_drm.c PDP1/pdp1_clk.c PDP1/pdp1_dcs.c PDP1/pdp1_dpy.c display/display.c display/sim_ws.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c -I PDP1 -DUSE_DISPLAY -DHAVE_LIBSDL -DUSE_SIM_VIDEO `/usr/bin/sdl2-config --cflags` `/usr/bin/sdl2-config --static-libs` -DDISPLAY_TYPE=DIS_TYPE30 -DPIX_SCALE=RES_HALF -o BIN/pdp1 -lm -lrt -lpthread -lpcreposix -ldl -lpng  
/usr/lib64/gcc/x86_64-suse-linux/5/../../../../x86_64-suse-linux/bin/ld: cannot find -lts
collect2: error: ld returned 1 exit status
makefile:1399: recipe for target 'BIN/pdp1' failed
make: *** [BIN/pdp1] Error 1

The error for Sabayon 16.04 is as follows:

lib paths are: /lib32/ /lib64/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/ /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/32/ /usr/lib32/ /usr/lib32/OpenCL/vendors/nvidia/ /usr/lib32/opengl/nvidia/lib/ /usr/lib32/qt4/ /usr/lib64/ /usr/lib64/OpenCL/vendors/nvidia/ /usr/lib64/opengl/nvidia/lib/ /usr/lib64/qt4/ /usr/lib64/sidplay/builders/
include paths are:  /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include /usr/local/include /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include-fixed /usr/include
using libm: /usr/lib32/libm.so
using librt: /usr/lib32/librt.so
using libpthread: /usr/lib32/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib32/libpcreposix.so /usr/include/pcreposix.h
using libdl: /usr/lib32/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib32/libpng.so /usr/include/png.h
using mman: /usr/include/sys/mman.h
using libSDL2: /usr/include/SDL2/SDL.h
using libpcap: /usr/include/pcap.h
using libvdeplug: /usr/lib64/libvdeplug.so /usr/include/libvdeplug.h
***
*** all sigma alpha Simulators being built with:
*** - compiler optimizations and no debugging support. GCC Version: 4.9.3.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
***
*** git commit id is 736e341fd24af5b35968d1418e89f2ca5c935e8c.
***
font paths are: /usr/share/fonts/ /usr/lib/jvm/
font names are: DejaVuSans.ttf LucidaSansRegular.ttf FreeSans.ttf AppleGothic.ttf tahoma.ttf
using libSDL_ttf: /usr/lib32/libSDL_ttf.so /usr/include/SDL/SDL_ttf.h
***
mkdir -p BIN
gcc -march=native -m64 -std=gnu99 -U__STRICT_ANSI__  -O3 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -flto -fwhole-program -Wno-unused-result -DSIM_GIT_COMMIT_ID=736e341fd24af5b35968d1418e89f2ca5c935e8c -DSIM_COMPILER="GCC Version: 4.9.3" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_LIBPNG -DHAVE_GLOB -DHAVE_SHM_OPEN  PDP1/pdp1_lp.c PDP1/pdp1_cpu.c PDP1/pdp1_stddev.c PDP1/pdp1_sys.c PDP1/pdp1_dt.c PDP1/pdp1_drm.c PDP1/pdp1_clk.c PDP1/pdp1_dcs.c PDP1/pdp1_dpy.c display/display.c display/sim_ws.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c -I PDP1 -DUSE_DISPLAY -DHAVE_LIBSDL -DUSE_SIM_VIDEO `/usr/bin/sdl2-config --cflags` `/usr/bin/sdl2-config --static-libs` -DDISPLAY_TYPE=DIS_TYPE30 -DPIX_SCALE=RES_HALF -o BIN/pdp1 -lm -lrt -lpthread -lpcreposix -ldl -lpng -lvdeplug -Wl,-R,/usr/lib64/ -L/usr/lib64/  -flto -fwhole-program
Usage: /usr/bin/sdl2-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs]
/tmp/ccfG5RTr.ltrans2.ltrans.o: In function `dpy_svc':
<artificial>:(.text+0xa80): undefined reference to `SDL_SemTryWait'
<artificial>:(.text+0xa98): undefined reference to `SDL_SemTryWait'
<artificial>:(.text+0xb53): undefined reference to `SDL_PushEvent'
<artificial>:(.text+0xba1): undefined reference to `SDL_PushEvent'
<artificial>:(.text+0xc3c): undefined reference to `SDL_SemPost'
<artificial>:(.text+0xda4): undefined reference to `SDL_SemPost'
<artificial>:(.text+0xdb1): undefined reference to `SDL_GetError'
<artificial>:(.text+0xdf8): undefined reference to `SDL_SemPost'
<artificial>:(.text+0xe8d): undefined reference to `SDL_SemWait'
<artificial>:(.text+0x1000): undefined reference to `SDL_SemPost'
<artificial>:(.text+0x10c9): undefined reference to `SDL_GetError'
<artificial>:(.text+0x112c): undefined reference to `SDL_GetError'
<artificial>:(.text+0x11a7): undefined reference to `SDL_GetError'
<artificial>:(.text+0x11f0): undefined reference to `SDL_SemPost'
<artificial>:(.text+0x11fa): undefined reference to `SDL_GetError'
<artificial>:(.text+0x126d): undefined reference to `SDL_PushEvent'
<artificial>:(.text+0x12c1): undefined reference to `SDL_GetError'
<artificial>:(.text+0x13ab): undefined reference to `SDL_GetError'
/tmp/ccfG5RTr.ltrans5.ltrans.o: In function `screenshot_cmd':
<artificial>:(.text+0x1d06): undefined reference to `SDL_Delay'
/tmp/ccfG5RTr.ltrans12.ltrans.o: In function `vid_show':
<artificial>:(.text+0x946): undefined reference to `SDL_Delay'
/tmp/ccfG5RTr.ltrans12.ltrans.o: In function `vid_video_events':
<artificial>:(.text+0x158a): undefined reference to `SDL_CreateWindowAndRenderer'
<artificial>:(.text+0x15b9): undefined reference to `SDL_SetRenderDrawColor'
<artificial>:(.text+0x15c5): undefined reference to `SDL_RenderClear'
<artificial>:(.text+0x15d1): undefined reference to `SDL_RenderPresent'
<artificial>:(.text+0x15f4): undefined reference to `SDL_CreateTexture'
<artificial>:(.text+0x1609): undefined reference to `SDL_StopTextInput'
<artificial>:(.text+0x1615): undefined reference to `SDL_GetWindowID'
<artificial>:(.text+0x163b): undefined reference to `SDL_SetWindowTitle'
<artificial>:(.text+0x16aa): undefined reference to `SDL_WaitEvent'
<artificial>:(.text+0x1779): undefined reference to `SDL_WarpMouseInWindow'
<artificial>:(.text+0x187d): undefined reference to `SDL_SetWindowTitle'
<artificial>:(.text+0x1979): undefined reference to `SDL_PeepEvents'
<artificial>:(.text+0x1a37): undefined reference to `SDL_FreeCursor'
<artificial>:(.text+0x1a4e): undefined reference to `SDL_DestroyTexture'
<artificial>:(.text+0x1a65): undefined reference to `SDL_DestroyRenderer'
<artificial>:(.text+0x1a7c): undefined reference to `SDL_DestroyWindow'
<artificial>:(.text+0x1ae1): undefined reference to `SDL_GetError'
<artificial>:(.text+0x1bf5): undefined reference to `SDL_PumpEvents'
<artificial>:(.text+0x1c08): undefined reference to `SDL_WarpMouseInWindow'
<artificial>:(.text+0x1c0d): undefined reference to `SDL_PumpEvents'
<artificial>:(.text+0x1c67): undefined reference to `SDL_SetCursor'
<artificial>:(.text+0x1c6c): undefined reference to `SDL_GetMouseFocus'
<artificial>:(.text+0x1c94): undefined reference to `SDL_FreeCursor'
<artificial>:(.text+0x1ca3): undefined reference to `SDL_ShowCursor'
<artificial>:(.text+0x1cff): undefined reference to `SDL_RenderClear'
<artificial>:(.text+0x1d1e): undefined reference to `SDL_RenderCopy'
<artificial>:(.text+0x1d32): undefined reference to `SDL_RenderPresent'
<artificial>:(.text+0x1d5d): undefined reference to `SDL_PauseAudio'
<artificial>:(.text+0x1df7): undefined reference to `SDL_UpdateTexture'
<artificial>:(.text+0x1eb0): undefined reference to `SDL_SetRelativeMouseMode'
<artificial>:(.text+0x1edd): undefined reference to `SDL_WarpMouseInWindow'
<artificial>:(.text+0x1ee2): undefined reference to `SDL_PumpEvents'
<artificial>:(.text+0x1f09): undefined reference to `SDL_PeepEvents'
<artificial>:(.text+0x1f3e): undefined reference to `SDL_SemWait'
<artificial>:(.text+0x2022): undefined reference to `SDL_SemPost'
<artificial>:(.text+0x202f): undefined reference to `SDL_GetError'
<artificial>:(.text+0x20c0): undefined reference to `SDL_SemWait'
<artificial>:(.text+0x2113): undefined reference to `SDL_SemPost'
<artificial>:(.text+0x2120): undefined reference to `SDL_GetError'
<artificial>:(.text+0x2211): undefined reference to `SDL_GetError'
<artificial>:(.text+0x2247): undefined reference to `SDL_Quit'
<artificial>:(.text+0x2251): undefined reference to `SDL_GetError'
<artificial>:(.text+0x2291): undefined reference to `SDL_GetError'
<artificial>:(.text+0x2300): undefined reference to `SDL_ShowCursor'
<artificial>:(.text+0x2351): undefined reference to `SDL_GetError'
<artificial>:(.text+0x2401): undefined reference to `SDL_GetError'
<artificial>:(.text+0x243e): undefined reference to `SDL_DestroyRenderer'
<artificial>:(.text+0x2455): undefined reference to `SDL_DestroyWindow'
<artificial>:(.text+0x2465): undefined reference to `SDL_Quit'
<artificial>:(.text+0x2482): undefined reference to `SDL_SemWait'
<artificial>:(.text+0x2544): undefined reference to `SDL_SemPost'
<artificial>:(.text+0x2551): undefined reference to `SDL_GetError'
<artificial>:(.text+0x259f): undefined reference to `SDL_WarpMouseInWindow'
<artificial>:(.text+0x2606): undefined reference to `SDL_SetRelativeMouseMode'
<artificial>:(.text+0x2942): undefined reference to `SDL_GetKeyboardState'
<artificial>:(.text+0x2ae5): undefined reference to `SDL_GetError'
<artificial>:(.text+0x2b54): undefined reference to `SDL_GetError'
/tmp/ccfG5RTr.ltrans12.ltrans.o: In function `png_error_SDL.lto_priv.139':
<artificial>:(.text+0x8d0): undefined reference to `SDL_SetError'
/tmp/ccfG5RTr.ltrans18.ltrans.o: In function `vid_thread':
<artificial>:(.text+0x118): undefined reference to `SDL_SetHint'
<artificial>:(.text+0x122): undefined reference to `SDL_Init'
<artificial>:(.text+0x136): undefined reference to `SDL_CloseAudio'
<artificial>:(.text+0x152): undefined reference to `SDL_Quit'
<artificial>:(.text+0x1c1): undefined reference to `SDL_OpenAudio'
/tmp/ccfG5RTr.ltrans18.ltrans.o: In function `_vid_show_video.isra.8.lto_priv.155':
<artificial>:(.text+0x26dd): undefined reference to `SDL_GetVersion'
<artificial>:(.text+0x276b): undefined reference to `SDL_Init'
<artificial>:(.text+0x2775): undefined reference to `SDL_GetError'
<artificial>:(.text+0x279a): undefined reference to `SDL_GetNumVideoDisplays'
<artificial>:(.text+0x27aa): undefined reference to `SDL_GetCurrentDisplayMode'
<artificial>:(.text+0x27d2): undefined reference to `SDL_GetDisplayName'
<artificial>:(.text+0x2835): undefined reference to `SDL_GetError'
<artificial>:(.text+0x285a): undefined reference to `SDL_GetNumRenderDrivers'
<artificial>:(.text+0x2872): undefined reference to `SDL_GetRenderDriverInfo'
<artificial>:(.text+0x2aac): undefined reference to `SDL_GetHint'
<artificial>:(.text+0x2ab9): undefined reference to `SDL_GetHint'
<artificial>:(.text+0x2af1): undefined reference to `SDL_Quit'
<artificial>:(.text+0x2b7f): undefined reference to `SDL_GetCurrentVideoDriver'
<artificial>:(.text+0x2c11): undefined reference to `SDL_GetRendererInfo'
/tmp/ccfG5RTr.ltrans18.ltrans.o: In function `vid_close.part.0.lto_priv.136':
<artificial>:(.text+0x2d1c): undefined reference to `SDL_PushEvent'
<artificial>:(.text+0x2d38): undefined reference to `SDL_WaitThread'
<artificial>:(.text+0x2db7): undefined reference to `SDL_DestroySemaphore'
<artificial>:(.text+0x2dd3): undefined reference to `SDL_DestroySemaphore'
/tmp/ccfG5RTr.ltrans18.ltrans.o: In function `_vid_screenshot.lto_priv.154':
<artificial>:(.text+0x2ecc): undefined reference to `SDL_CreateRGBSurface'
<artificial>:(.text+0x2eec): undefined reference to `SDL_RenderReadPixels'
<artificial>:(.text+0x2f1b): undefined reference to `SDL_RWFromFile'
<artificial>:(.text+0x2f30): undefined reference to `SDL_FreeSurface'
<artificial>:(.text+0x2f79): undefined reference to `SDL_GetError'
/tmp/ccfG5RTr.ltrans18.ltrans.o: In function `vid_audio_callback':
<artificial>:(.text+0xc9): undefined reference to `SDL_PauseAudio'
/tmp/ccfG5RTr.ltrans20.ltrans.o: In function `show_version.part.20.lto_priv.144':
<artificial>:(.text+0x1b27): undefined reference to `SDL_GetVersion'
/tmp/ccfG5RTr.ltrans26.ltrans.o: In function `vid_set_cursor.constprop.98':
<artificial>:(.text+0x4bf): undefined reference to `SDL_CreateCursor'
<artificial>:(.text+0x6a6): undefined reference to `SDL_PushEvent'
<artificial>:(.text+0x6cf): undefined reference to `SDL_GetError'
<artificial>:(.text+0x70b): undefined reference to `SDL_FreeCursor'
/tmp/ccfG5RTr.ltrans26.ltrans.o: In function `display_init.constprop.94':
<artificial>:(.text+0xb3c): undefined reference to `SDL_CreateSemaphore'
<artificial>:(.text+0xb6b): undefined reference to `SDL_CreateSemaphore'
<artificial>:(.text+0xb8e): undefined reference to `SDL_CreateThread'
/tmp/ccfG5RTr.ltrans31.ltrans.o: In function `SDL_SavePNG_RW.constprop.54':
<artificial>:(.text+0xa9a): undefined reference to `SDL_SetError'
<artificial>:(.text+0xabf): undefined reference to `SDL_SetError'
<artificial>:(.text+0xae0): undefined reference to `SDL_SetError'
<artificial>:(.text+0xb18): undefined reference to `SDL_SetError'
collect2: error: ld returned 1 exit status
makefile:1399: recipe for target 'BIN/pdp1' failed
make: *** [BIN/pdp1] Error 1

**Comment by markpizz** [comment]
Please check that the current code builds cleanly on each of these operating system.  I tested on OpenSUSE Leap 42.1

**Comment by polaris6262** [comment]
I've confirmed that commit 02d9bc3 does build successfully on both openSUSE Leap 42.1 and openSUSE Tumbleweed, as well as on Sabayon 16.04. Many thanks once again for the quick resolution.

**Comment by markpizz** [comment]
By the way, can you put your full name on your github profile (NOT your eMail)?

Thanks.
