### ISSUE TITLE
PDP11: tm will boot from a tape image but tu won't

### ISSUE THREAD

**Issue by hbent** [simh/simh#301]
Pretty straightforward, pdp11 trying to boot from v7m.tap ( https://www.mediafire.com/?n0uc13n5ntiol8a ):

PDP-11 simulator V4.0-0 Beta        git commit id: c8cd8531
Disabling XQ
sim> boot tu

HALT instruction, PC: 000002 (HALT)
sim> boot tm
Boot
:   

minimal pdp11.ini to reproduce:
set cpu 11/34
set cpu idle
set cr disabled
set lpt disabled
set dz disabled
set rk disabled
set rl disabled
set hk disabled
set rx disabled
set rp disabled
set rq disabled
set tm enabled
set tm0 lock
att tm0 v7m.tap
set tq disabled
set tu enabled
set tu0 lock
att tu0 v7m.tap

show version:
PDP-11 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                32b data
                32b addresses
                Ethernet Packet transports:PCAP:TAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                Asynchronous I/O support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 6.0.0 20160404 (experimental)
                Simulator Compiled: Apr 11 2016 at 14:05:23
                Memory Access: Little Endian
                Memory Pointer Size: 64 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.4
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 2ms
                OS: NetBSD aelfric 7.0 NetBSD 7.0 (AELFRIC) #1: Mon Apr 11 12:49:13 EDT 2016  root@aelfric:/usr/src/sys/arch/amd64/compile/AELFRIC amd64
        git commit id: 60439625

**Comment by hbent** [comment]
On that same config, f I don't do "disable rp", this happens:

sim> boot tu
Device RHB interrupt vector conflict with TM at 224

Simulation stopped, PC: 000000 (HALT)

and if I then disable tm, I can boot from tu:
sim> boot tu
Boot
:

**Comment by markpizz** [comment]
Well, there are some devices that have fixed addresses and/or vectors which can't be enabled at the same time.  TM and TS are examples of this.  They share fixed addresses (12520) and vectors (224) 
.
RHB (used by the TU device) will get a conflicting vector if it is the second RH device enabled.  RP uses RHA and it gets the first fixed vector (254) and the next available fixed vector is 224.

The v7m.tap.gz file you're pointing at above can be uncompressed with gunzip.  Is it corrupted?

**Comment by hbent** [comment]
Not sure what the problem with the file is.  I checked it on this end and uploaded it again, try now: https://www.mediafire.com/?0kdwyk71bg24ggv

**Comment by markpizz** [comment]
Got it.  Thanks.   I see the problem.  I'm looking into fixing it.

**Comment by markpizz** [comment]
Henry,

The latest code should fix this any other combination of issues relating to various combinations of Massbus devices being enabled or not.  The first Massbus device (of RP, TU or RS) will get Massbus 0 (MBA0 on VAX or RHA on PDP11), and the second Massbus device will get Massbus 1 (MBA1 on VAX or RHB on PDP11) and the third Massbus device (PDP11 only) will get RHC.  For historical compatibility with prior simh behavior MBAs will be allocated preferentially with the order of RP, TU, and RS.

Please test this and close the issue if you're happy with the results.

- Mark

**Comment by hbent** [comment]
Looks good, thanks!

**Comment by markpizz** [comment]
It has been pointed out that for PDP11 systems to be well behaved based on assumptions in operating systems and/or boot block code, the devices connected through the RH Massbus controllers must always have the same fixed address (and vectors).  That is RP must use RHA, TU must use RHB and RS must use RHC without regard to which other Massbus devices may be in the configuration.
