### ISSUE TITLE
Anomaly with ATTACH command

### ISSUE THREAD

**Issue by jackrubin** [simh/simh#302]
I'm running SIMH under Raspian Wheezy on a Raspberry Pi. I get different results between two versions of the PDP8 simulator when using the "at" command in a .ini script:

PDP-8 simulator V4.0-0 Beta        git commit id: f961a98b
sim> at ttix 2222
Listening on port 2222
sim> exit
Goodbye

PDP-8 simulator V4.0-0 Beta        git commit id: 54335613
sim> at ttix 2222
Sockets: socket error 97 - Address family not supported by protocol
Sockets: socket error 97 - Address family not supported by protocol
Listening on port 2222
sim> exit
Goodbye

Unfortunately, the problem is with the current commit; the command seems to work fine with the earlier version.

Here is the version info:

Older version that works -

sim> sh ver
PDP-8 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                32b data
                32b addresses
                no Ethernet
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
        Host Platform:
                Compiler: GCC 4.6.3
                Simulator Compiled: Jun 24 2014 at 21:37:13
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                OS clock tick size: 2ms
                OS: Linux DskSrv01 4.1.21+ #872 Wed Apr 6 17:27:13 BST 2016 armv6l GNU/Linux

        git commit id: f961a98b

Current version that throws socket 97 error:

sim> sh ver
PDP-8 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                32b data
                32b addresses
                no Ethernet
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 4.6.3
                Simulator Compiled: Apr 11 2016 at 08:43:05
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: No Video Support
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 2ms
                OS: Linux DskSrv01 4.1.21+ #872 Wed Apr 6 17:27:13 BST 2016 armv6l GNU/Linux
        git commit id: 54335613

It seems confusing that the current commit id is a lower number than the earlier commit?

Thanks for all the work you put in to keep SIMH running!

best,
Jack

**Comment by markpizz** [comment]
Hi Jack,

Thanks for this report.

The Git commit id: is actually a hash value that is 40 hex digits long.  These values are so unique that the first n (usually 7) digits are sufficiently unique to represent the whole 40 digit hex string.  A person assigning significance to the actual value (presuming numeric ordering for instance) isn't valid since the hash is, by design, essentially a string of random numbers.

As for the issue you're reporting.  Can you provide the build (make) output for each of these versions.

Can you identify a little more about which Pi you're using here.  I have a couple of different ones for testing.

Also, can you describe some details of your network (i.e. IPv4 only, IPv6 only, or mixed)?


- Mark

**Comment by markpizz** [comment]
I reproduced this problem on my Raspberry Pi 2.  Fix pending.

**Comment by jackrubin** [comment]
Damn, I was just finishing copying over the make file output!
Thanks for the quick action – you’ll make lots of SerialDisk users happy!

Where are you geographically – would you consider speaking at one of the Vintage Computer Festival gatherings?

Best,
Jack
