### ISSUE TITLE
dev TTIX doesn't transmit data in current commit

### ISSUE THREAD

**Issue by jackrubin** [simh/simh#303]
We are working with a .ini file for the PDP8 sim that includes these lines:

at ttix 2222
...
l ../bootloader/bootloader.bin

The bootloader is loaded into addresses 17 through 45. Location 45 contains the boot character (@) which should be transmitted via socat to a process in an Xwindow. The routine at addresses 24 and 25 sends the character. 

For testing, we opened TTIX on port 2222 and simply monitored the port via telnet. Socat was not invoked for this stage. We tested by setting a breakpoint at 26, then executing the bootloader from its starting address of 20.

In a earlier versions of SIMH, the '@' is sent via TTIX to the listening telnet session.

![bootchar_yes](https://cloud.githubusercontent.com/assets/4658426/14481654/a6e5cade-00fa-11e6-81ac-d8661318b6d7.png)

In the current commit, no character is received over TTIX

![bootchar_no](https://cloud.githubusercontent.com/assets/4658426/14481830/535c0048-00fc-11e6-964a-b06bc1285693.png)

Sorry, but I can't tell you when in the tree development this feature broke.

Thank you for your help.

**Comment by markpizz** [comment]
Hi Jack,

Please give the latest code a try and if things look good, close this issue.

Thanks.

- Mark

**Comment by jackrubin** [comment]
Thanks Mark, works a treat!

Fun facts: running 'make pdp8' takes 11.7 seconds to complete on an Intel i5-4430 @ 3 GHz; it takes 5 minutes, 45 seconds on a Raspberry Pi Model B. 

Please close this case.
