### ISSUE TITLE
Warnings compiling pdp11 with gcc 6.1.1

### ISSUE THREAD

**Issue by polaris6262** [simh/simh#308]
These are produced compiling the pdp11 simulator under Linux Arch with the newly-released gcc 6.1.1; they may not be significant but I thought they might be of interest. None of the other simulators including the VAXen exhibit that volume of warnings.

gcc -march=native -std=gnu99 -U__STRICT_ANSI__  -O3 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -flto -fwhole-program -Wno-unused-result -DSIM_GIT_COMMIT_ID=550e3607697fdae216b68f9aa63a6e28490c8c2f -DSIM_COMPILER="GCC Version: 6.1.1" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_LIBPNG -DHAVE_GLOB -DHAVE_SHM_OPEN  PDP11/pdp11_fp.c PDP11/pdp11_cpu.c PDP11/pdp11_dz.c PDP11/pdp11_cis.c PDP11/pdp11_lp.c PDP11/pdp11_rk.c PDP11/pdp11_rl.c PDP11/pdp11_rp.c PDP11/pdp11_rx.c PDP11/pdp11_stddev.c PDP11/pdp11_sys.c PDP11/pdp11_tc.c PDP11/pdp11_tm.c PDP11/pdp11_ts.c PDP11/pdp11_io.c PDP11/pdp11_rq.c PDP11/pdp11_tq.c PDP11/pdp11_pclk.c PDP11/pdp11_ry.c PDP11/pdp11_pt.c PDP11/pdp11_hk.c PDP11/pdp11_xq.c PDP11/pdp11_xu.c PDP11/pdp11_vh.c PDP11/pdp11_rh.c PDP11/pdp11_tu.c PDP11/pdp11_cpumod.c PDP11/pdp11_cr.c PDP11/pdp11_rf.c PDP11/pdp11_dl.c PDP11/pdp11_ta.c PDP11/pdp11_rc.c PDP11/pdp11_kg.c PDP11/pdp11_ke.c PDP11/pdp11_dc.c PDP11/pdp11_dmc.c PDP11/pdp11_kmc.c PDP11/pdp11_dup.c PDP11/pdp11_rs.c PDP11/pdp11_vt.c PDP11/pdp11_td.c PDP11/pdp11_io_lib.c display/display.c display/sim_ws.c display/vt11.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c -DVM_PDP11 -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -DUSE_DISPLAY -DHAVE_LIBSDL -DUSE_SIM_VIDEO `/usr/bin/sdl2-config --cflags` `/usr/bin/sdl2-config --libs` -o BIN/pdp11 -lm -lrt -lpthread -lpcreposix -ldl -lpng   -flto -fwhole-program
./display/vt11.h:93:14: warning: type of ‘vt11_get_dpc’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_dpc(void);        /* read Display PC */
              ^
display/vt11.c:643:1: note: return value type mismatch
 vt11_get_dpc(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:643:1: note: ‘vt11_get_dpc’ was previously declared here
 vt11_get_dpc(void)
 ^
display/vt11.c:643:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:94:14: warning: type of ‘vt11_get_mpr’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_mpr(void);        /* read mode parameter register */
              ^
display/vt11.c:714:1: note: return value type mismatch
 vt11_get_mpr(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:714:1: note: ‘vt11_get_mpr’ was previously declared here
 vt11_get_mpr(void)
 ^
display/vt11.c:714:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:95:14: warning: type of ‘vt11_get_xpr’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_xpr(void);        /* read graphplot incr/X pos register */
              ^
display/vt11.c:739:1: note: return value type mismatch
 vt11_get_xpr(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:739:1: note: ‘vt11_get_xpr’ was previously declared here
 vt11_get_xpr(void)
 ^
display/vt11.c:739:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:96:14: warning: type of ‘vt11_get_ypr’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_ypr(void);        /* read char code/Y pos register */
              ^
display/vt11.c:754:1: note: return value type mismatch
 vt11_get_ypr(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:754:1: note: ‘vt11_get_ypr’ was previously declared here
 vt11_get_ypr(void)
 ^
display/vt11.c:754:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:97:14: warning: type of ‘vt11_get_rr’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_rr(void);         /* read relocate register */
              ^
display/vt11.c:771:1: note: return value type mismatch
 vt11_get_rr(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:771:1: note: ‘vt11_get_rr’ was previously declared here
 vt11_get_rr(void)
 ^
display/vt11.c:771:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:98:14: warning: type of ‘vt11_get_spr’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_spr(void);        /* read status parameter register */
              ^
display/vt11.c:783:1: note: return value type mismatch
 vt11_get_spr(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:783:1: note: ‘vt11_get_spr’ was previously declared here
 vt11_get_spr(void)
 ^
display/vt11.c:783:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:99:14: warning: type of ‘vt11_get_xor’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_xor(void);        /* read X offset register */
              ^
display/vt11.c:802:1: note: return value type mismatch
 vt11_get_xor(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:802:1: note: ‘vt11_get_xor’ was previously declared here
 vt11_get_xor(void)
 ^
display/vt11.c:802:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:100:14: warning: type of ‘vt11_get_yor’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_yor(void);        /* read Y offset register */
              ^
display/vt11.c:821:1: note: return value type mismatch
 vt11_get_yor(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:821:1: note: ‘vt11_get_yor’ was previously declared here
 vt11_get_yor(void)
 ^
display/vt11.c:821:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:101:14: warning: type of ‘vt11_get_anr’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_anr(void);        /* read associative name register */
              ^
display/vt11.c:840:1: note: return value type mismatch
 vt11_get_anr(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:840:1: note: ‘vt11_get_anr’ was previously declared here
 vt11_get_anr(void)
 ^
display/vt11.c:840:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:102:14: warning: type of ‘vt11_get_scr’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_scr(void);        /* read slave console/color register */
              ^
display/vt11.c:856:1: note: return value type mismatch
 vt11_get_scr(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:856:1: note: ‘vt11_get_scr’ was previously declared here
 vt11_get_scr(void)
 ^
display/vt11.c:856:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:103:14: warning: type of ‘vt11_get_nr’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_nr(void);         /* read name register */
              ^
display/vt11.c:910:1: note: return value type mismatch
 vt11_get_nr(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:910:1: note: ‘vt11_get_nr’ was previously declared here
 vt11_get_nr(void)
 ^
display/vt11.c:910:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:104:14: warning: type of ‘vt11_get_sdr’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_sdr(void);        /* read stack data register */
              ^
display/vt11.c:922:1: note: return value type mismatch
 vt11_get_sdr(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:922:1: note: ‘vt11_get_sdr’ was previously declared here
 vt11_get_sdr(void)
 ^
display/vt11.c:922:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:105:14: warning: type of ‘vt11_get_str’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_str(void);        /* read char string term register */
              ^
display/vt11.c:958:1: note: return value type mismatch
 vt11_get_str(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:958:1: note: ‘vt11_get_str’ was previously declared here
 vt11_get_str(void)
 ^
display/vt11.c:958:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:106:14: warning: type of ‘vt11_get_sar’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_sar(void);        /* read stack address/maint register */
              ^
display/vt11.c:971:1: note: return value type mismatch
 vt11_get_sar(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:971:1: note: ‘vt11_get_sar’ was previously declared here
 vt11_get_sar(void)
 ^
display/vt11.c:971:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:107:14: warning: type of ‘vt11_get_zpr’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_zpr(void);        /* read Z position register */
              ^
display/vt11.c:1021:1: note: return value type mismatch
 vt11_get_zpr(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:1021:1: note: ‘vt11_get_zpr’ was previously declared here
 vt11_get_zpr(void)
 ^
display/vt11.c:1021:1: note: code may be misoptimized unless -fno-strict-aliasing is used
./display/vt11.h:108:14: warning: type of ‘vt11_get_zor’ does not match original declaration [-Wlto-type-mismatch]
 extern int32 vt11_get_zor(void);        /* read Z offset register */
              ^
display/vt11.c:1036:1: note: return value type mismatch
 vt11_get_zor(void)
 ^
display/vt11.h:39:14: note: type ‘int32’ should match type ‘int32’
 typedef long int32;
              ^
./sim_defs.h:168:25: note: the incompatible type is defined here
 typedef signed int      int32;
                         ^
display/vt11.c:1036:1: note: ‘vt11_get_zor’ was previously declared here
 vt11_get_zor(void)
 ^
display/vt11.c:1036:1: note: code may be misoptimized unless -fno-strict-aliasing is used
display/vt11.h:133:13: warning: type of ‘vt_fetch’ does not match original declaration [-Wlto-type-mismatch]
 extern int  vt_fetch(uint32, vt11word *);       /* get a display-file word */
             ^
PDP11/pdp11_vt.c:522:1: note: type mismatch in parameter 1
 vt_fetch(uint32 addr, vt11word *wp)
 ^
./sim_defs.h:171:25: note: type ‘uint32’ should match type ‘uint32’
 typedef unsigned int    uint32;
                         ^
display/vt11.h:40:23: note: the incompatible type is defined here
 typedef unsigned long uint32;
                       ^
PDP11/pdp11_vt.c:522:1: note: ‘vt_fetch’ was previously declared here
 vt_fetch(uint32 addr, vt11word *wp)
 ^
PDP11/pdp11_vt.c:522:1: note: code may be misoptimized unless -fno-strict-aliasing is used

**Comment by markpizz** [comment]
The latest code should fix this.

I don't have a gcc 6.1.1 environment.

Please test and follow up here or close the issue if it still is a problem.

Thanks.

**Comment by polaris6262** [comment]
Great job! Clean compile for the pdp11 with gcc 6.1.1, and the simulator itself runs RSTS fine.
