### ISSUE TITLE
Pdp11 crashes with multiple TDC controllers enabled

### ISSUE THREAD

**Issue by polaris6262** [simh/simh#309]
I tried booting my RSTS/E 10.1 installation on a simulated MSCP 456MB RA81 disk (device RQ0) using the latest pdp11 simulator (commit 7bd58c6d) and the simulator aborted. This was compiled using gcc 6.1.1 on Arch Linux running the 4.5.3 kernel.

I hadn't started this in a while (last time was over a month ago) so unfortunately I can't tell exactly when it stopped working, but I've used it successfully for over a year and a half without any problems. I have an older installation of the same RSTS/E 10.1 but this one on a simulated Massbus 166MB RP06 disk (device RP0), and that one is booting fine on the same simulator. This older installation on the RP06 is not as complete as the more recent one as I found the RP06 too small, so I would really appreciate being able to use my newest one.

PDP-11 simulator V4.0-0 Beta
	Simulator Framework Capabilities:
		32b data
		32b addresses
		Ethernet Packet transports:PCAP:TAP:NAT:UDP
		Idle/Throttling support is available
		Virtual Hard Disk (VHD) support
		RAW disk and CD/DVD ROM support
		Asynchronous I/O support
		FrontPanel API Version 2
	Host Platform:
		Compiler: GCC 6.1.1 20160501
		Simulator Compiled: May 10 2016 at 12:29:03
		Memory Access: Little Endian
		Memory Pointer Size: 64 bits
		Large File (>2GB) support
		SDL Video support: SDL Version 2.0.4
		PCRE RegEx support for EXPECT commands
		OS clock resolution: 1ms
		Time taken by msleep(1): 2ms
		OS: Linux tovilyis.excom.com 4.5.3-1-ARCH #1 SMP PREEMPT Sat May 7 20:43:57 CEST 2016 x86_64 GNU/Linux
        git commit id: 7bd58c6d

-----------------------------------------------------------------------------------------------------------------------

PDP-11 simulator V4.0-0 Beta        git commit id: 7bd58c6d
Logging to file "./console.log"
Debug output to "STDERR"
Disabling XQ
CPU	11/70, FPP, RH70, idle enabled, autoconfiguration enabled
	4088KB
CLK	60Hz, address=17777546-17777547, vector=100
RQ	address=17772150-17772153, no vector, RQDX3, 4 units
  RQ0	456MB, attached to ./rsts_sys101.ra81, write enabled
	RA81, autosize, SIMH format
  RQ1	456MB, not attached, write enabled
	RA81, autosize, SIMH format
  RQ2	622MB, not attached, write enabled
	RA82, autosize, SIMH format
  RQ3	700MB, not attached, write enabled
	RA71, autosize, SIMH format
RQB	address=17760374-17760377*, no vector, RQDX3, 4 units
  RQB0	204MB, not attached, write enabled
	RA60, autosize, SIMH format
  RQB1	2400KB, not attached, write enabled
	RX33, autosize, SIMH format
  RQB2	800KB, not attached, write enabled
	RX50, autosize, SIMH format
  RQB3	681MB, not attached, read only
	RRD40, autosize, SIMH format
RHA	address=17776700-17776753, vector=254
RP	Massbus adapter 0, 8 units
  RP0	87MW, not attached, write enabled
	SIMH format, RP06
  RP1	87MW, not attached, write enabled
	SIMH format, RP06
  RP2	258MW, not attached, write enabled
	SIMH format, RP07
  RP3	258MW, not attached, write enabled
	SIMH format, RP07
RHB	address=17772440-17772477, vector=224
TU	Massbus adapter 1, FORMATTER, TM03, 8 units
  TU0	not attached, write enabled, TU77
	SIMH format, unlimited capacity
  TU1	not attached, write enabled, TU77
	SIMH format, unlimited capacity
  TU2	not attached, write enabled, TU77
	SIMH format, unlimited capacity
  TU3	not attached, write enabled, TU77
	SIMH format, unlimited capacity
RK	address=17777400-17777417, vector=220, 8 units
  RK0	1247KW, not attached, write enabled
  RK1	1247KW, not attached, write enabled
  RK2	1247KW, not attached, write enabled
  RK3	1247KW, not attached, write enabled
HK	address=17777440-17777477, vector=210, 8 units
  HK0	6944KW, not attached, write enabled
	RK06
  HK1	6944KW, not attached, write enabled
	RK06
  HK2	13MW, not attached, write enabled
	RK07
  HK3	13MW, not attached, write enabled
	RK07
RL	RL11, address=17774400-17774411, vector=160, 4 units
  RL0	2621KW, not attached, on line
	write enabled, RL01
  RL1	2621KW, not attached, on line
	write enabled, RL01
  RL2	5242KW, not attached, on line
	write enabled, RL02
  RL3	5242KW, not attached, on line
	write enabled, RL02
RX	address=17777170-17777173, vector=264, 2 units
  RX0	256KB, not attached, write enabled
  RX1	256KB, not attached, write enabled
RY	address=17760270-17760273*, vector=340*, 2 units
  RY0	512KB, not attached, write enabled
	double density
  RY1	512KB, not attached, write enabled
	double density
TQ	TK50 (94MB), address=17774500-17774503, no vector, 4 units
  TQ0	not attached, write enabled, SIMH format
	capacity=98MB
TC	address=17777340-17777351, vector=214, 8 units
  TC0	147KW, not attached, write enabled
	16b
  TC1	147KW, not attached, write enabled
	16b
TDC	controllers=2, address=17776500-17776517, vector=300*, 4 units
  TDC0	262KB, not attached, write enabled
  TDC1	262KB, not attached, write enabled
  TDC2	262KB, not attached, write enabled
  TDC3	262KB, not attached, write enabled
LPT	address=17777514-17777517, vector=200
	attached to ./lp11.out
PTP	address=17777554-17777557, vector=74
	not attached
PTR	address=17777550-17777553, vector=70
	not attached
TTI	address=17777560-17777563, vector=60
	7b
TTO	address=17777564-17777567, vector=64
	7p
Listening on port 1170
DZ	address=17760100-17760137*, vector=320-354*, lines=32
	attached to 1170, 8b, 0 current connections
XU	address=17774510-17774517, vector=120, MAC=08:00:2B:CC:DD:EE
	type=DELUA, throttle=disabled
	not attached
Listening on port 10000
sim> boot rq0
Aborted (core dumped)

**Comment by markpizz** [comment]
While I look into this, please put your full name on your github profile.

Thanks.

**Comment by markpizz** [comment]
My testing the PDP11 simulator built from the latest current codebase boots RSTS 10.1 just fine from an RQ device.  

That happens with my configuration.  Please provide the specific configuration file you are using when this happens.

Thanks

**Comment by polaris6262** [comment]
I've updated my github profile as requested; I hadn't noticed my name was missing.

The configuration I'm using hasn't changed for quite some time, and was used for the RSTS sysgen.

It's as follows:

;********************************************************************************
;*                                                                              *
;*   p d p 1 1 / 7 0   U n i b u s   R S T S / E   C o n f i g u r a t i o n    *
;*                                                                              *
;********************************************************************************

;================================================================================
; Configure the console
;================================================================================

;--------------------------------------------------------------------------------
; Record a copy of console output
;--------------------------------------------------------------------------------

SET CONSOLE LOG=./console.log

;--------------------------------------------------------------------------------
; Send debug info to simh's stderr
;--------------------------------------------------------------------------------

SET CONSOLE DEBUG=STDERR

;--------------------------------------------------------------------------------
; Turn ON Escape Sequences for VT support
;--------------------------------------------------------------------------------

SET CONSOLE PCHAR=01000023600

;================================================================================
; Configure the CPU
;================================================================================

;--------------------------------------------------------------------------------
; pdp11/70, 4M memory, Floating-Point Processor (FPP), idle
;--------------------------------------------------------------------------------

SET CPU 11/70, 4M, FPP, IDLE
SHOW CPU

;--------------------------------------------------------------------------------
; KW11-L Line-Time Clock (CLK)
;--------------------------------------------------------------------------------

SHOW CLK

;================================================================================
; Disable unneeded default devices
;================================================================================

;--------------------------------------------------------------------------------
; CR11/CD11 Card Reader (CR)
;--------------------------------------------------------------------------------

SET CR  DISABLED

;--------------------------------------------------------------------------------
; TM11/TU10 Magnetic Tapes (TM)                                     8 Drives - MT
;--------------------------------------------------------------------------------

SET TM  DISABLED

;--------------------------------------------------------------------------------
; TS11 Magnetic Tape (TS)                                            1 Drive - MS
;--------------------------------------------------------------------------------

SET TS  DISABLED

;================================================================================
; Configure storage devices
;================================================================================

;================================================================================
; MSCP Disk Controllers (RQDX3,UDA50/RQ,RQB,RQC,RQD)
;================================================================================

;--------------------------------------------------------------------------------
; MSCP Disks
;--------------------------------------------------------------------------------
; RA60*(204M)
; RA71(700M),RA72(1G)
; RA80*(121M),RA81*(456M),RA82*(622M),RA90(1216M),RA92(1505M),RC25*(26M)
; RD31*(21M),RD32*(42M)
; RD51*(11M),RD52*(30M),RD53*(71M),RD54*(152M)
; RX33*(1228K),RX50*(409K)
; RRD40(CD-ROM,681MB)
;--------------------------------------------------------------------------------

;--------------------------------------------------------------------------------
; RQ(RQDX3)                                                       4*4 Drives - DU
;--------------------------------------------------------------------------------

SET RQ  ENABLED
SET RQ  RQDX3

SET RQ0 ENABLED
SET RQ0 RA81

SET RQ1 ENABLED
SET RQ1 RA81

SET RQ2 ENABLED
SET RQ2 RA82

SET RQ3 ENABLED
SET RQ3 RA71

ATTACH RQ0 ./rsts_sys101.ra81

SHOW RQ

;--------------------------------------------------------------------------------
; RQB(RQBDX3)                                                     4*4 Drives - DU
;--------------------------------------------------------------------------------

SET RQB  ENABLED
SET RQB  RQDX3

SET RQB0 ENABLED
SET RQB0 RA60

SET RQB1 ENABLED
SET RQB1 RX33

SET RQB2 ENABLED
SET RQB2 RX50

SET RQB3 ENABLED
SET RQB3 RRD40

SHOW RQB

;================================================================================
; Massbus Disk Controller (RHA/RH70)
;================================================================================

;--------------------------------------------------------------------------------
; RP04(83M),RP06(176M),RP07(504M) Disk Drives (RP)                  8 Drives - DB
; RM03(67M),RM05(256M),RM80(124M) Disk Drives (RP)                  8 Drives - DR
;--------------------------------------------------------------------------------

SET RP  ENABLED

SET RP0 RP06
SET RP0 WRITEENABLED

SET RP1 RP06
SET RP1 WRITEENABLED

SET RP2 RP07
SET RP2 WRITEENABLED

SET RP3 RP07
SET RP3 WRITEENABLED

SET RP4 DISABLED
SET RP5 DISABLED
SET RP6 DISABLED
SET RP7 DISABLED

SHOW RHA
SHOW RP

;================================================================================
; Massbus Tape Controller (RHB/RH70)
;================================================================================

;--------------------------------------------------------------------------------
; TM02,TM03/TE16,TU45,TU77 Magnetic Tapes (TU)                      8 Drives - MM
;--------------------------------------------------------------------------------

SET TU  ENABLED
SET TU  TM03

SET TU0 TU77
SET TU1 TU77
SET TU2 TU77
SET TU3 TU77

SET TU4 DISABLED
SET TU5 DISABLED
SET TU6 DISABLED
SET TU7 DISABLED

; Install tape for RSTS/E 10.1

; ATTACH TU0 -ER /projects/Simulations/DEC/RSTS-E/Software/rstse_v10_1_install_sep10_1992.tap
; SET TU0 LOCKED

; Special tape options are required for layered products release tapes, which are
; encoded in a different format than regular tapes
; Command "@[0,1]instal layered_products" is used for the actual installation
; from the mounted tape

; SET TU1 FORMAT=TPC
; ATTACH TU1 -ER /projects/Simulations/DEC/RSTS-E/Software/bp2_v2_7.tap
; ATTACH TU1 -ER /projects/Simulations/DEC/RSTS-E/Software/fortran_iv_v2_8.tap
; SET TU1 LOCKED

; SET TU2 FORMAT=TPC
; ATTACH TU2 -ER /projects/Simulations/DEC/RSTS-E/Software/decnet-e_v4_1.tap
; ATTACH TU2 -ER /projects/Simulations/DEC/RSTS-E/Software/fms11_v2_1.tpc
; SET TU2 LOCKED

; Both Fortran77 (F77) and C (CCC) require a special procedure involving AUTOIN$

; SET TU3 FORMAT=TPC
; ATTACH TU3 -ER /projects/Simulations/DEC/RSTS-E/Software/fortran-77_v5_4.tap
; ATTACH TU3 -ER /projects/Simulations/DEC/RSTS-E/Software/c_v1_2.tap
; SET TU3 LOCKED

SHOW RHB
SHOW TU

;================================================================================
; Cartridge disks (RK/RK11, HK/RK611, RL/RL11)
;================================================================================

;--------------------------------------------------------------------------------
; RK11/RK05(2.5M) Cartridge Disk (RK)                               8 Drives - DK
;--------------------------------------------------------------------------------

SET RK  ENABLED

SET RK0 WRITEENABLED
SET RK1 WRITEENABLED
SET RK2 WRITEENABLED
SET RK3 WRITEENABLED

SET RK4 DISABLED
SET RK5 DISABLED
SET RK6 DISABLED
SET RK7 DISABLED

SHOW RK

;--------------------------------------------------------------------------------
; RK611/RK06(13M),RK07(27M) Cartridge Disk (HK)                     8 Drives - DM
;--------------------------------------------------------------------------------

SET HK  ENABLED

SET HK0 RK06
SET HK0 WRITEENABLED

SET HK1 RK06
SET HK1 WRITEENABLED

SET HK2 RK07
SET HK2 WRITEENABLED

SET HK3 RK07
SET HK3 WRITEENABLED

SET HK4 DISABLED
SET HK5 DISABLED
SET HK6 DISABLED
SET HK7 DISABLED

SHOW HK

;--------------------------------------------------------------------------------
; RL11(RLV12)/RL01(5.2M),RL02(10M) Cartridge Disk (RL)              4 Drives - DL
;--------------------------------------------------------------------------------

SET RL  ENABLED

SET RL0 RL01
SET RL0 WRITEENABLED

SET RL1 RL01
SET RL1 WRITEENABLED

SET RL2 RL02
SET RL2 WRITEENABLED

SET RL3 RL02
SET RL3 WRITEENABLED

SHOW RL

;================================================================================
; Floppy Disk Drives (RX/RX11,RY/RX211)
;================================================================================

;--------------------------------------------------------------------------------
; RX11/RX01 Floppy Disk (RX)                                         2 Units - DX
;--------------------------------------------------------------------------------

SET RX  ENABLED

SET RX0 WRITEENABLED
SET RX1 WRITEENABLED

SHOW RX

;--------------------------------------------------------------------------------
; RX211/RX02 Floppy Disk (RY)                                        2 Units - DY
;--------------------------------------------------------------------------------

SET RY  ENABLED

SET RY0 DOUBLE
SET RY0 WRITEENABLED

SET RY1 DOUBLE
SET RY1 WRITEENABLED

SHOW RY

;================================================================================
; TMSCP Magnetic Tape (TQ/TUK50,TQK50)
;================================================================================

;--------------------------------------------------------------------------------
; TUK50(TQK50)/TK50(96M),TK70,TU81                                   4 Units - MU
;--------------------------------------------------------------------------------

SET TQ  ENABLED
SET TQ  TK50

SET TQ0 WRITEENABLED

; RSTS/E supports up to two TMSCP drives but only one unit per TQK50 controller,
; whereas simh only provides a single TQK50 controller with up to four drives,
; thus at this time only one TMSCP drive can be configured on RSTS/E

SET TQ1 DISABLED
SET TQ2 DISABLED
SET TQ3 DISABLED

SHOW TQ

;================================================================================
; DECtape (TC/TC11)
;================================================================================

;--------------------------------------------------------------------------------
; TC11/TU56 (TC)                                                     8 Units - DT
;--------------------------------------------------------------------------------

SET TC  ENABLED

SET TC0 WRITEENABLED
SET TC1 WRITEENABLED

SET TC2 DISABLED
SET TC3 DISABLED
SET TC4 DISABLED
SET TC5 DISABLED
SET TC6 DISABLED
SET TC7 DISABLED

SHOW TC

;--------------------------------------------------------------------------------
; TU58 (TDC)                                                              4 Units
;--------------------------------------------------------------------------------

SET TDC  ENABLED
SET TDC  CONTROLLERS=2

SET TDC0 WRITEENABLED
SET TDC1 WRITEENABLED
SET TDC2 WRITEENABLED
SET TDC3 WRITEENABLED

SHOW TDC

;================================================================================
; Input/output devices
;================================================================================

;--------------------------------------------------------------------------------
; LP11-S Line printer (LPT)                                           1 unit - LP
;--------------------------------------------------------------------------------

SET LPT ENABLED

ATTACH LPT ./lp11.out

SHOW LPT

;--------------------------------------------------------------------------------
; PC11/High-speed paper tape punch (PTP)                              1 Unit - PP
;--------------------------------------------------------------------------------
;
SET PTP ENABLED
SHOW PTP

;--------------------------------------------------------------------------------
; PC11/High-speed paper tape reader (PTR)                             1 Unit - PR
;--------------------------------------------------------------------------------
;
SET PTR ENABLED
SHOW PTR

;================================================================================
; Terminal devices
;================================================================================

;--------------------------------------------------------------------------------
; DL11 Console (TTI,TTO)
;--------------------------------------------------------------------------------

SHOW TTI
SHOW TTO

;--------------------------------------------------------------------------------
; DZ11 Terminal Multiplexer (DZ)                                   4*8 Lines - 32
;--------------------------------------------------------------------------------

SET DZ  ENABLED
SET DZ  LINES=32
SET DZ  8B

ATTACH DZ 1170

SHOW DZ

;================================================================================
; Communication devices
;================================================================================

;--------------------------------------------------------------------------------
; DELUA/DEUNA Ethernet controller (XU)
;--------------------------------------------------------------------------------

SET XU  ENABLED
SET XUB DISABLED

SET XU  TYPE=DELUA

SHOW XU

;================================================================================
; Console set-up
;================================================================================

;--------------------------------------------------------------------------------
; Separate the simulated pdp11 console from the simh command window
;--------------------------------------------------------------------------------

SET CONSOLE TELNET=10000

;--------------------------------------------------------------------------------
; Open a separate terminal window for the pdp11 system console
;--------------------------------------------------------------------------------

! gnome-terminal --profile=Simulator -e 'telnet localhost 10000' &

; ! konsole --profile Simulator -e 'telnet localhost 10000' &

;================================================================================
; End of pdp11/70 configuration
;================================================================================

**Comment by polaris6262** [comment]
As well, here's the output from the RSTS Hardware List command from a recent run; it shows that every enabled device is properly "seen" by RSTS:

  Name  Address Vector  Comments
  TT0:   177560   060   
  RK0:   177400   220   Units: 0(RK05) 1(RK05) 2(RK05) 3(RK05)
  RL0:   174400   160   Units: 0(RL01) 1(RL01) 2(RL02) 3(RL02)
  RM0:   177440   210   Units: 0(RK06) 1(RK06) 2(RK07) 3(RK07)
  RB0:   176700   254   BAE=+050, Units: 0(RP06) 1(RP06) 2(RP07) 3(RP07)
  RU0:   172150  P364   RQDX3   Units: 0(RA81) 1(RA81) 2(RA82) 3(RA71)
  RU1:   160374  P370   RQDX3   Units: 4(RA60) 5(RX33) 6(RX50) 7(RRD40)
  MU0:   174500  P374   TK50    Units: 0(TK50)
  TU0:   172440   224   BAE=+034, Units: 0(TU77 @TM03 #0) 1(TU77 @TM03 #0) 
                               2(TU77 @TM03 #0) 3(TU77 @TM03 #0) 
  TC0:   177340   214
  PR0:   177550   070
  PP0:   177554   074
  LP0:   177514   200
  RX0:   177170   264   Units: 0(RX01) 1(RX01)
  RX1:   160270   360   Units: 2(RX02) 3(RX02)
  DD0:   176500   300
  DD1:   176510   310
  DZ0:   160100   320   Sub-lines: 8
  DZ1:   160110   330   Sub-lines: 8
  DZ2:   160120   340   Sub-lines: 8
  DZ3:   160130   350   Sub-lines: 8
  XE0:   174510   120   DELUA Address: 08-00-2B-CC-DD-EE

  KW11L  177546   100
  SR     177570
  DR     177570

  Hertz = 60.

  Other: FPU, SL, 22-Bit, Data space, Cache w/address, System ID = 4660

**Comment by markpizz** [comment]
OK.I don't have any problem booting my RSTS disk with the current codebase using your config file.

That suggests one of two things:

1. there is something unusual with your rsts disk image.
2. there is something unusual about your host platform.

I usually try to replicate host platform issues by installing the host OS in a virtual machine and making direct observations with the failing system.  In this case, that is somewhat a problem since your Arch Linux platform, unlike most Linux distros, doesn't have an easy install procedure.  I've downloaded the latest Arch Linux ISO, but there aren't very specific instructions about how to actually install it.  Suggestions?

**Comment by polaris6262** [comment]
I've been using computers for quite some time now, more than thirty years. In the late seventies I started with BASIC on an HP2000 (very pleased with that simulator!), then RSTS/E V06C and V7.0 on a real pdp11/70, then moved on professionally to IBM mainframes using various flavours of MVS and Assembler.  Got involved in the late eighties with SunOS on Sun Workstations, then in the nineties worked with UnixWare on Pentium and Pentium Pro servers, as well as AIX on POWER and HP/UX on PA-RISC in addition to Solaris 7, 8, 9 and 10 on 32-bit and 64-bit Intel hardware.

These days I'm semi-retired and for fun I'm collecting Linux distributions (once a geek, always a geek). I have Red Hat Enterprise Linux 6.8 with gcc 4.4.7, Red Hat Enterprise Linux 7.2 with gcc 4.8.5, Fedora 23 Workstation with gcc 5.3.1, Mint 17.3 with gcc 5.3.0, openSUSE Leap 42.1 with gcc 5.3.1, Ubuntu 16.04 with gcc 5.3.1, Sabayon 16.05 with gcc 4.9.3, Debian 8.4 ("Jessie") with gcc 4.9.2, Arch Linux with gcc 6.1.1, Mageia 5 with gcc 4.9.2, openSUSE Tumbleweed with gcc 5.3.1, Antergos (an Arch derivative) with gcc 6.1.1 and Solus Project with gcc 5.3.0. Sorry for the exhaustive list, but as you can see, I'm well equipped for testing stuff.

I agree that Arch is somewhat daunting. It cannot be installed per se - it must actually be built, and as such tends to be popular mostly for those seeking the ultimate Linux challenge. I had to install and manage eight Linux distributions before I felt ready to tackle Arch. If you're interested, Antergos is an easy-to-install derivative of Arch.

I download the simh github zip file quite often and I keep all the source that I download, organised by commit number and date. I build almost all that I download on all my Linux distributions, and I keep four versions back apart from the latest.

I have the following simh versions built on all my distributions:

717f3820 [20160426] 
d8aafde7 [20160429]
820d77ef [20160505]
550e3607 [20160507]
7bd58c6d [20160509]

So, back to my problem, and I admit it's got me stumped. Thinking that you might indeed have a point concerning the possible corruption of my RSTS disk image, I restored an old copy dated March 2 which I will retain for testing purposes. That image is certified as being in working order. I tried it with the latest commit, 7bd58c6d [20160509], and that promptly aborted. A compare of the RSTS disk images shows that it was not modified. I then tried the same test with commit 550e3607 [20160507] and that failed as well. However, when I tried with commit 820d77ef [20160505], lo and behold, that one worked. What's interesting to note is that those last two commits were compiled with gcc 6.1.1 (built on 20160501 and new to Arch) while the previous three, including the one that worked were compiled with the previous gcc, version 5.3.0.

Thinking that it might be a problem with compiling the simulators with gcc 6.1.1 (I reported a bunch of warnings a few days ago), I went to some of my other Linux distributions and tried the same tests. To my bewilderment, all of my tests failed with the same abort, both the latest commit 7bd58c6d [20160509] (unsurprisingly), but also the one that had previously worked on Arch, 820d77ef [20160505]. The distributions I tested with were Fedora 23 with gcc 5.3.1 and Linux Mint 17.3 with gcc 5.3.0. In all cases I made sure that the RSTS disk image was the "certified" March 2 copy.

Honestly, I have no idea what to make of this. Bad software elsewhere on the systems? Possibly, but on all the distributions I tested with, including Mint 17.3 which is based on fairly old code, Ubuntu 14.04, the previous LTS release?

As a last resort, can't we use of some sort of debugging technique or software to find out what it's aborting on? I'm not up to speed on debugging code on Linux, so if you're able to shed any light on the matter it would be much appreciated. I stand ready to assist in any way I can.

By the way, as I've mentioned before, if you're interested in a cool Linux distribution, you may want to try Antergos; all the goodness of Arch without the steep learning curse. It's a bit heavier than its progenitor (some disdainfully call it bloated) but I find it wasn't that bad. I recommend the Cinnamon desktop, much more pleasant than either GNOME or KDE (I have a profusion of both on my systems).

**Comment by polaris6262** [comment]
I tried something else to more fully determine the source of the problem. Using my Fedora 23 distribution and the latest commit 7bd58c6d [20160509], I made a copy of my existing environment settings and attempted a new RSTS installation from my installation tape image. The simulator successfully booted from TU0 and the installation proceeded along normally including the disk formatting until it reached the point where it issued the "Copying required system files" and the "Performing limited hardware scan" messages at which point it aborted. The problem would seem to be within the hardware handling in the simulator.

Everything worked fine back around March 2, so in between then and now something changed in the pdp11 simulated hardware handling that no longer supports my configuration. I realise that my pdp11 configuration is rather "heavy" and deliberately so. I have indeed included every possible device that could conceivably co-exist in a real very well equipped pdp11, and I have done so for experimentation purposes. Since changing hardware on a pdp11 invariably requires another RSTS sysgen, I sought to have everything I could possibly want to play with right from the start, and frankly, since there is no additional cost to loading up on simulated hardware, why not?

So now I'm left with an unusable configuration that used to work fine but no longer. I suppose I could strip down my configuration to the bare essentials and progressively add up devices and try installing RSTS to find out which combination causes this problem, but that would be incredibly time-consuming and somewhat frustrating. The question at this point is, what to do? Give up running RSTS or try with a smaller configuration when I knew that the previous worked fine at some point in the past?

Any suggestions?

**Comment by markpizz** [comment]
Antergos would not install on VirtualBox, but I was able to install Fedora 23 and reproduce the problem.  Once I could see it the problem was obvious.

The processing of initialization commands improperly attempted to initialize 
all controllers AND these attempts (for controllers beyond 0) referenced 
beyond the bounds of the unit array.

This appeared to be a platform specific problem due to the different contents of data beyond the bounds of the unit array on Linux vs Windows.

Please confirm that this is fixed now and close the issue if so.

**Comment by polaris6262** [comment]
Brilliant! It works perfectly. Many thanks once again. I was twenty years old when I got to play on a real pdp11/70, and believe me, it's quite the feeling to reconnect with all of it.

Problems like this one highlight the importance of testing on as many platforms as possible, and I for one will continue to do my part to ensure the highest quality in those simulators.
