### ISSUE TITLE
Warnings produced when building the isys8010 and isys8020 simulators

### ISSUE THREAD

**Issue by polaris6262** [simh/simh#313]
The following warnings are produced when building both the isys8010 and isys8020 simulators with gcc 6.1.1:

gcc -march=native -std=gnu99 -U__STRICT_ANSI__  -O3 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -flto -fwhole-program -Wno-unused-result -DSIM_GIT_COMMIT_ID=03445f5f941ed5091e3e8d2a168b7f42e03ef434 -DSIM_COMPILER="GCC Version: 6.1.1" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_LIBPNG -DHAVE_GLOB -DHAVE_SHM_OPEN  Intel-Systems/common/i8080.c Intel-Systems/isys8010/isys8010_sys.c Intel-Systems/common/i8251.c Intel-Systems/common/i8255.c Intel-Systems/common/ieprom.c Intel-Systems/common/iram8.c Intel-Systems/common/multibus.c Intel-Systems/common/isbc80-10.c Intel-Systems/common/isbc064.c Intel-Systems/common/isbc208.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -I Intel-Systems/isys8010 -o BIN/isys8010 -lm -lrt -lpthread -lpcreposix -ldl -lpng   -flto -fwhole-program
Intel-Systems/common/ieprom.c:51:13: warning: type of ‘i8255_unit’ does not match original declaration [-Wlto-type-mismatch]
 extern UNIT i8255_unit;
             ^
Intel-Systems/common/i8255.c:112:6: note: ‘i8255_unit’ was previously declared here
 UNIT i8255_unit[] = {
      ^
Intel-Systems/common/ieprom.c:52:14: warning: type of ‘xack’ does not match original declaration [-Wlto-type-mismatch]
 extern uint8 xack;      /* XACK signal */
              ^
./sim_defs.h:187:25: note: type ‘uint32’ should match type ‘uint8’
 typedef unsigned int    uint32;
                         ^
./sim_defs.h:185:25: note: the incompatible type is defined here
 typedef unsigned char   uint8;
                         ^
Intel-Systems/common/multibus.c:71:14: warning: type of ‘xack’ does not match original declaration [-Wlto-type-mismatch]
 extern uint8 xack;                          /* XACK signal */
              ^
./sim_defs.h:187:25: note: type ‘uint32’ should match type ‘uint8’
 typedef unsigned int    uint32;
                         ^
./sim_defs.h:185:25: note: the incompatible type is defined here
 typedef unsigned char   uint8;
                         ^
Intel-Systems/common/i8080.c:168:8: note: ‘xack’ was previously declared here
 uint32 xack = 0;                        /* XACK signal */

**Comment by markpizz** [comment]
I'll be glad to fix this if you can suggest a Linux or other x86/64 system has gcc 6.1.1 as the default and is easy to install AND will run in a VirtualBox VM.

Alternatively, you can suggest changes which might fix the problem and I'll consider them.

**Comment by polaris6262** [comment]
Wish I could help fix the code, but unfortunately I'm mostly a systems administrator, not a developer. Good with shell scripts but not so with complex C programs.

The only systems with gcc 6.1.1 as a standard that I know so far include Arch and its derivatives such as Manjaro and Antergos (but you didn't have much luck with the latter). It's available as well for Ubuntu 16.04 LTS in the Toolchain Test Builds PPA (https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/ppa); the default gcc for vanilla 16.04 is still 5.3.1.

**Comment by markpizz** [comment]
Like the last case, I'm sure that a reasonable fix will only be a couple of minutes worth of effort.  Spending hours to setup the test environment is beyond what I'm willing to spend on this report since the affected population of users is only you.  If you want to install Arch linux on a VirtualBox VM and export that VM so I can then import it, I'll have my test case.and be able to address this issue and any others you may find going forward.

Let me know.

**Comment by polaris6262** [comment]
My humble apologies. I was only reporting those in an attempt to help make the software better. I am certainly not trying to impose an undue burden on your time. Consider this a trivial matter not worth further consideration.

**Comment by markpizz** [comment]
I would

**Comment by markpizz** [comment]
I would also like to make the software better, and it certainly wouldn't hurt to have another test system, so if you're a user on the Arch platform and you have the skills to configure a base system, I'll be glad to leverage your efforts and then fix the issues you encounter.

**Comment by jguillaumes** [comment]
I've taken a look at this. There are two problems:

- i8255_unit is declared as an array and then referenced as an external scalar. 
- xack is defined as uint32 and referenced as external uint8.

This patch fixes the syntactical issues, but I can't be sure it fixes the simulator FUNCTIONALLY, since I have no way to test it. I've chosen to take as "correct" the definition and as "wrong" the external references, which makes sense to me.

I'm not doing a pull request since my last attempt ended messing all the things :)

```
diff --git a/Intel-Systems/common/ieprom.c b/Intel-Systems/common/ieprom.c
index a573042..18cda61 100644
--- a/Intel-Systems/common/ieprom.c
+++ b/Intel-Systems/common/ieprom.c
@@ -48,8 +48,8 @@ t_stat EPROM_attach (UNIT *uptr, CONST char *cptr);
 t_stat EPROM_reset (DEVICE *dptr, int32 size);
 int32 EPROM_get_mbyte(uint32 addr);

-extern UNIT i8255_unit;
-extern uint8 xack;                                             /* XACK signal */
+extern UNIT i8255_unit[];
+extern uint32 xack;                                            /* XACK signal */

 /* SIMH EPROM Standard I/O Data Structures */

@@ -170,7 +170,7 @@ int32 EPROM_get_mbyte(uint32 addr)
 {
     int32 val;

-    if (i8255_unit.u5 & 0x01) {         /* EPROM enabled */
+    if (i8255_unit[0].u5 & 0x01) {         /* EPROM enabled */
         sim_debug (DEBUG_read, &EPROM_dev, "EPROM_get_mbyte: addr=%04X\n", addr);
         if (addr < EPROM_unit.capac) {
             SET_XACK(1);                /* good memory address */
diff --git a/Intel-Systems/common/iram8.c b/Intel-Systems/common/iram8.c
index 9c5f9a9..a31c3cd 100644
--- a/Intel-Systems/common/iram8.c
+++ b/Intel-Systems/common/iram8.c
@@ -45,8 +45,8 @@ t_stat RAM_reset (DEVICE *dptr, int32 base, int32 size);
 int32 RAM_get_mbyte(int32 addr);
 void RAM_put_mbyte(int32 addr, int32 val);

-extern UNIT i8255_unit;
-extern uint8 xack;                         /* XACK signal */
+extern UNIT i8255_unit[];
+extern uint32 xack;                         /* XACK signal */

 /* SIMH RAM Standard I/O Data Structures */

@@ -122,7 +122,7 @@ int32 RAM_get_mbyte(int32 addr)
 {
     int32 val;

-    if (i8255_unit.u5 & 0x02) {         /* enable RAM */
+    if (i8255_unit[0].u5 & 0x02) {         /* enable RAM */
         sim_debug (DEBUG_read, &RAM_dev, "RAM_get_mbyte: addr=%04X\n", addr);
         if ((addr >= RAM_unit.u3) && ((uint32) addr < (RAM_unit.u3 + RAM_unit.capac))) {
             SET_XACK(1);                /* good memory address */
@@ -142,7 +142,7 @@ int32 RAM_get_mbyte(int32 addr)

 void RAM_put_mbyte(int32 addr, int32 val)
 {
-    if (i8255_unit.u5 & 0x02) {         /* enable RAM */
+    if (i8255_unit[0].u5 & 0x02) {         /* enable RAM */
         sim_debug (DEBUG_write, &RAM_dev, "RAM_put_mbyte: addr=%04X, val=%02X\n", addr, val);
         if ((addr >= RAM_unit.u3) && ((uint32)addr < RAM_unit.u3 + RAM_unit.capac)) {
             SET_XACK(1);                /* good memory address */
diff --git a/Intel-Systems/common/isbc064.c b/Intel-Systems/common/isbc064.c
index 28bf9ce..4eb32c1 100644
--- a/Intel-Systems/common/isbc064.c
+++ b/Intel-Systems/common/isbc064.c
@@ -47,7 +47,7 @@ int32 isbc064_get_mword(int32 addr);
 void isbc064_put_mbyte(int32 addr, int32 val);
 void isbc064_put_mword(int32 addr, int32 val);

-extern uint8 xack;                         /* XACK signal */
+extern uint32 xack;                         /* XACK signal */

 /* isbc064 Standard I/O Data Structures */

diff --git a/Intel-Systems/common/isbc80-10.c b/Intel-Systems/common/isbc80-10.c
index eef42d9..d722253 100644
--- a/Intel-Systems/common/isbc80-10.c
+++ b/Intel-Systems/common/isbc80-10.c
@@ -71,7 +71,7 @@ extern void  multibus_put_mbyte(int32 addr, int32 val);
 extern int32 EPROM_get_mbyte(int32 addr);
 extern int32 RAM_get_mbyte(int32 addr);
 extern void RAM_put_mbyte(int32 addr, int32 val);
-extern UNIT i8255_unit;
+extern UNIT i8255_unit[];
 extern UNIT EPROM_unit;
 extern UNIT RAM_unit;
 extern t_stat i8255_reset (DEVICE *dptr, int32 base);
@@ -99,12 +99,12 @@ t_stat SBC_reset (DEVICE *dptr)
 int32 get_mbyte(int32 addr)
 {
     /* if local EPROM handle it */
-       if (i8255_unit.u5 & 0x01) {
+       if (i8255_unit[0].u5 & 0x01) {
                if ((addr >= EPROM_unit.u3) && ((uint16)addr < (EPROM_unit.u3 + EPROM_unit.capac))) {
                        return EPROM_get_mbyte(addr);
                }
     } /* if local RAM handle it */
-       if (i8255_unit.u5 & 0x02) {
+       if (i8255_unit[0].u5 & 0x02) {
                if ((addr >= RAM_unit.u3) && ((uint16)addr < (RAM_unit.u3 + RAM_unit.capac))) {
                        return RAM_get_mbyte(addr);
                }
@@ -128,11 +128,11 @@ int32 get_mword(int32 addr)
 void put_mbyte(int32 addr, int32 val)
 {
     /* if local EPROM handle it */
-    if ((i8255_unit.u5 & 0x01) && (addr >= EPROM_unit.u3) && ((uint16)addr <= (EPROM_unit.u3 + EPROM_unit.capac))) {
+    if ((i8255_unit[0].u5 & 0x01) && (addr >= EPROM_unit.u3) && ((uint16)addr <= (EPROM_unit.u3 + EPROM_unit.capac))) {
         sim_printf("Write to R/O memory address %04X - ignored\n", addr);
         return;
     } /* if local RAM handle it */
-    if ((i8255_unit.u5 & 0x02) && (addr >= RAM_unit.u3) && ((uint16)addr <= (RAM_unit.u3 + RAM_unit.capac))) {
+    if ((i8255_unit[0].u5 & 0x02) && (addr >= RAM_unit.u3) && ((uint16)addr <= (RAM_unit.u3 + RAM_unit.capac))) {
         RAM_put_mbyte(addr, val);
         return;
     } /* otherwise, try the multibus */
diff --git a/Intel-Systems/common/multibus.c b/Intel-Systems/common/multibus.c
index 159967a..a172495 100644
--- a/Intel-Systems/common/multibus.c
+++ b/Intel-Systems/common/multibus.c
@@ -68,7 +68,7 @@ extern t_stat isbc208_reset (DEVICE *dptr);

 /* external globals */

-extern uint8 xack;                          /* XACK signal */
+extern uint32 xack;                          /* XACK signal */
 extern int32 int_req;                       /* i8080 INT signal */

 /* multibus Standard SIMH Device Data Structures */                                                                      
```

(BTW: I've setup the test environment using docker... in something like five minutes *wink* *wink*)
