### ISSUE TITLE
VAX780 Decimal instruction error

### ISSUE THREAD

**Issue by markpizz** [simh/simh#319]
sim> boot rp0 /R5:10
    Loading boot code from vmb.exe

                            VAX DIAGNOSTIC SOFTWARE
                                    PROPERTY OF
                          DIGITAL EQUIPMENT CORPORATION

                        ***CONFIDENTIAL AND PROPRIETARY***

    Use Authorized Only Pursuant to a Valid Right-to-Use License
    Copyright, Digital Equipment Corporation,  1986.  All Rights Reserved.

    DIAGNOSTIC SUPERVISOR.  ZZ-ESSAA- 10.2-2032  31-MAY-1986 09:54:47
    DS> show load
    [SYS0.SYSMAINT]
    DS> dir

    Directory _CSA0:

    EVKAA.EXE          EVKAB.EXE          EVKAC.EXE          EVKAD.EXE

    Total of 4 files.
    DS> run evkab

    .. Program:  ZZ-EVKAB, VAX Basic Instructions Exerciser , revision 5.2, 161 test
    s,
       at 09:55:43.44.
    ?? No units to test, none selected with device type(s)
    KA000, KA999, KA730, KA750, KA780, KA785, KA86, KA820, KA850, KA880
    DS> att ka780 sbi
    Device Name? KA0
    G-floating instructions? y
    H-floating instructions? y
    WCS last address? ffff
    Accelerator type? 0
    DS> sel all
    DS> run evkab

    .. Program:  ZZ-EVKAB, VAX Basic Instructions Exerciser , revision 5.2, 161 test
    s,
       at 09:56:17.46.
    Testing: _KA0

    ********   ZZ-EVKAB, VAX Basic Instructions Exerciser  - 5.2  ********
     Pass 1, test 160, subtest 5, error 0, 31-MAY-1986 09:56:34.10
     Hard error while testing KA0: Exception error

    Instruction:    ASHP    R10, (R11), (AP), (R0), (R1), (R2)
    expected exception:     T-bit trap
    actual exception:       Decimal overflow trap

             ADDRESS     INITIAL    EXPECTED      ACTUAL       XOR
    OPR1    R10               0F          0F          0F
    OPR2    0011D9FF        0002        0002        0002
    OPR3    0011DDFF
     @OPR   0011DDFF          00          00          00
                              1C          1C          1C
    OPR4    0011E1FF          01          01          01
    OPR5    0011E5FF        001F        001F        001F
    OPR6    0011E9FF
     @OPR   0011E9FF          5A          00          00
                              5A          00          00
                              5A          00          00
                              5A          00          00
                              5A          00          00
                              5A          00          00
                              5A          00          00
                              5A          01          01
                              5A          00          00
                              5A          00          00
                              5A          00          00
                              5A          00          00
                              5A          00          00
                              5A          00          00
                              5A          00          00
                              5A          0C          0C
    Registers:
            R0          0011E1FF    00000000    00000000
            R1          0011E5FF    0011DDFF    0011DDFF
            R2          0011E9FF    00000000    00000000
            R3          33333333    0011E9FF    0011E9FF
            R10         5A5A5A0F    5A5A5A0F    5A5A5A0F
            R11         0011D9FF    0011D9FF    0011D9FF
            AP          0011DDFF    0011DDFF    0011DDFF
            PC          0011D1FF    0011D206    0011D206
            PSL         000000F6    000000F0    400000F2    40000002

    ********  End of Hard error number 0 ********

    Test 160 had 1 hard error.
    .. End of run, 1 error detected, pass count is 1,
       time is 31-MAY-1986 09:56:36.52
    DS>

**Comment by archivisth** [comment]
This "fix" to AHSP in 2008 was partially correct: NibbleLshift was okay, but WordLshift was FUBAR'd. I've rewritten the routine to be drastically less clever and a whole lot more correct. EVKAB now passes. (Note that I have an earlier revision - 3.4 - so this fix should be checked with the actual failing case.)
