### ISSUE TITLE
Missing VAX Instructions, BUGL & BUGW

### ISSUE THREAD

**Issue by JonathanBelanger** [simh/simh#322]
This may be purely intentional, but I was looking at all the VAX instructions and everything appears to be in vax_defs.h and vax_cpu.c, but I did not see anything for the BUGL and BUGW instructions.  According to the VAX architecture, BUGW does a word to longword extend and BUGL is a longword, if either of these are executed at a non-privilege level, then they are reserved instructions.  If executed at a privileged level, then the O/S can handle this.  I'm thinking there may be some O/Ses that may use this to report errors from privileged code to non-privileged code.  What are your thoughts?  Were these instructions intentionally left off?

JonBelanger

**Comment by archivisth** [comment]
These instructions do not exist in the hardware. On all VAXes, they take reserved instruction faults, without any interpretation of the operand, regardless of mode. Quoting the Architecture Reference Manual, "The hardware treats these opcodes as reserved to DIGITAL and faults. The VAX/VMS operating system treats them as requests to report software detected errors."

**Comment by markpizz** [comment]
So, the net results of what Bob is saying that the simulator behaves just as the hardware did and it generates reserved instruction faults.  Some operating systems (VMS) identify these specific instruction faults and interpret the additional argument as meaning something for the purposes of error reporting and generate some formatted message based on the internally (within the OS) defined error codes.
