### ISSUE TITLE
Output character transmit rate should be based on the line speed.

### ISSUE THREAD

**Issue by wcwuttke** [simh/simh#326]
ref: [Simh] PDP-8 KL8E XON/XOFF thread.

When using a teletype as a console device for simh/PDP-8, using the PiDP-8 front panel, I noticed that a DIR listing would cause the accumulator to be active for only a few seconds, but the listing would take 3 minutes to print. If you enter a Control-C after the first few seconds, you cannot stop the output. I put a quick patch in pdp8_tt.c to set the tto_unit wait time to 20000 (vs default of 100), which closely approximates the desired data rate which is synchronized with accumulator activity, and allows a Control-C to be recognized. I think something similar should be done, but based on the serial port baud baud rate.  I think there should be a way for the simh/PiDP-8 to output the characters at the correct baud rate.

**Comment by markpizz** [comment]
Please give the current code a try.  This problem should be solved.
