### ISSUE TITLE
VAX FATAL Bad Memory Block. when access ethernet

### ISSUE THREAD

**Issue by wjameskirk** [simh/simh#332]
using SIMH when I boot I receive memory errors when accessing the ethernet. The same happens when VMS is running when I attempt to access the Ethernet. Any help would be appreciated. Being run on a Surface Pro 4 running Windows 10. Same error when I run earlier versions of SIMH with Ethernet support

The following is the vax.ini file

;
; Load CPU microcode
load -r f:\simh39-0\exe\ka655.bin
;
; Attach non-volatile RAM to a file
attach nvr f:\simh39-0\vaxdata\nvram.bin
;
; This virtual machine has 64M memory
set cpu 64m
;
; Define disk drive types. RA92 is largest-supported VAX drive.
set rq0 ra92
set rq1 ra92
set rq2 ra92
set rq3 cdrom
set rq4 cdrom
;
; Attach defined drives to local files
attach rq0 f:\simh39-0\vaxdata\d0.dsk
attach rq1 f:\simh39-0\vaxdata\d1.dsk
attach rq2 f:\simh39-0\vaxdata\d2.dsk
;
; Attach the CD-ROM to its file (read-only) 
attach -r rq3 f:\simh39-0\vaxdata\cd.iso
attach -r rq4 f:\simh39-0\vaxdata\vmslp.iso
;
; Disable unused devices. It's also possible to disable individual devices,
; using a construction like "set rq2 disable" if desired. 
;
set rl disable
set ts disable
; 
; Attach Ethernet to a network interface
set xq mac=30-59-BC-16-C6-74
;set XQ TYPE=DELQA
attach xq eth0
;
; Now start the emulator
boot cpu

The following is the error when running vax.exe

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: 75ab9f51
NVR: buffering file in memory
F:\simh39-0\exe\VAX.ini-16> set rq4 cdrom
Unit disabled
RQ3: unit is read only
F:\simh39-0\exe\VAX.ini-25> attach -r rq4 f:\simh39-0\vaxdata\vmslp.iso
Unit disabled
WinPcap version 4.1.3 (packet.dll version 10, 2, 0, 5002), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
Eth: opened OS device {A0B95D6C-59A5-4C0F-8C2E-27E9BB78011C} - Realtek USB NIC
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.

[c
KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Tests completed.
>>>
Simulation stopped, PC: 200436A6 (MOVL #2014042D,R11)
sim> show ver
MicroVAX 3900 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                FrontPanel API Version 2
        Host Platform:
                Compiler: Microsoft Visual C++ 15.00.30729.01
                Simulator Compiled as C: Jul 21 2016 at 06:08:42
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.3
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 1ms
                OS: Microsoft Windows [Version 10.0.14393]
                Architecture: x86 on AMD64, Processors: 4
                Processor Id: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel, Level: 6, Revision: 4501
        git commit id: 75ab9f51
sim> show ethernet
ETH devices:
 eth0   {A0B95D6C-59A5-4C0F-8C2E-27E9BB78011C} (Realtek USB NIC)
 eth1   {1B44D476-C2E8-49AA-9E98-8CF5F0138CA2} (Microsoft)
 eth2   {8D17ABAE-8E5D-4DA5-90FE-8A38ADB53B00} (Microsoft)
 eth3   {8F1A624F-108D-4382-8E07-895472B14B6E} (Microsoft)
 eth4   nat:{optional-nat-parameters}          (Integrated NAT (SLiRP) support)
 eth5   udp:sourceport:remotehost:remoteport   (Integrated UDP bridge support)
WinPcap version 4.1.3 (packet.dll version 10, 2, 0, 5002), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
Windows Packet Capture Service Name: npf
Open ETH Devices:
 XQ     eth0 (Realtek USB NIC)
Ethernet Device:
  Name:                    {A0B95D6C-59A5-4C0F-8C2E-27E9BB78011C}
  Reflections:             0
  Self Loopbacks Sent:     2
  Self Loopbacks Rcvd:     0
  Packets Sent:            3
  Asynch Interrupts:       Disabled
  Read Queue: Count:       0
  Read Queue: High:        0
  Read Queue: Loss:        0
  Peak Write Queue Size:   1
  BPF Filter: (((ether dst 30:59:BC:16:C6:74)))
sim>

**Comment by markpizz** [comment]
Hi there,

This is interesting.

First, can you please put your full name on your github profile (no email necessary).  Thanks.

Second, I see you're running with the just released Windows 10 Version 1607.  That's not special just an observation.  Did you have success before the recent upgrade?

Third, there is something unexpected with this line of the show version output:

> WinPcap version 4.1.3 (packet.dll version 10, 2, 0, 5002), based on libpcap version 1.0 branch 1_0_rel0b (20091008)

On my Desktop I see:

> WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)

On my Test system I see:

> WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)

Something is fishy or otherwise unusual about the packet.dll on your system since it doesn't seem to be the one that comes with the WinPcap 4.1.3 installation.

Ideas?

Thanks.

- Mark

**Comment by markpizz** [comment]
I'm closing this issue since there's been no response here.  

Feel free to reopen this issue if the problem persists and/or you have more information relating to the problem you were experiencing.
