### ISSUE TITLE
HP3000 COBOLII produces executable which will result in illegal instruction when run

### ISSUE THREAD

**Issue by RogerMcCarty** [simh/simh#336]
Using this version of simh
HP 3000 simulator V4.0-0 Beta        git commit id: e06b815d

ABORT :$OLDPASS.OPERATOR.SYS.%0.%1070
PROGRAM ERROR #7 :ILLEGAL INSTRUCTION

More details and source code used.
[illegal instruction.txt](https://github.com/simh/simh/files/450882/illegal.instruction.txt)

**Comment by markpizz** [comment]
Hi Roger,

You may want to review:   https://github.com/simh/simh/blob/master/HP3000/hp3000_release.txt

Where you'll find implementation notes which say:

   The simulator currently does not provide the HP 32234A COBOL II 
   firmware instructions, so programs generated by the COBOLII compiler
   will abort at run time with an "ILLEGAL INSTRUCTION" error.  Programs
   generated by the COBOL compiler do not use these instructions and
   therefore are not affected.

Additionally, in the release announcement:

  http://mailman.trailing-edge.com/pipermail/simh/2016-July/015696.html

...which states in part:

   Preinstalled User-Defined Commands (UDCs) provide access to the COBOL
   74 compiler with the MPE-V/E :COBOLII, :COBOLIIPREP, and :COBOLIIGO
   commands, and to the COBOL 85 compiler with :COBOLIIX, :COBOLIIXPREP,
   and :COBOLIIXGO.  However, note that the simulator currently does not
   provide the HP 32234A COBOL II firmware instructions, so programs
   generated by the COBOLII compiler will abort at run time with "ILLEGAL
   INSTRUCTION" errors, limiting the current utility of the compilers to
   syntax checking.

The author (J. David Bryan) is taking this as an enhancement request for 
a future version.

Thanks.

**Comment by RogerMcCarty** [comment]
Thanks Mark!

Guess I've just been too busy playing.

**Comment by markpizz** [comment]
Hi Roger,

Dave Bryan has done some work to address what you noticed.  He'd like to work with you to confirm he's on the right track before migrating these efforts into the github repo.  Please contact him directly via email which is indicated in the previously mentioned release announcement.

Have fun.

- Mark

**Comment by markpizz** [comment]
Dave now says:
1) The release notes are correct for the current version, 
2) He's worked with Roger to address the issue
3) The next version will implement the COBOL-II instructions.

Closing this issue now.
