### ISSUE TITLE
Support VC8E in PDP-8

### ISSUE THREAD

**Issue by drovak** [simh/simh#337]
It looks like there's already PDP-11 VR14 (and other) code so that Lunar Lander can play; I seem to recall compiling and running that a few years ago. Is there any reason not to support the VC8E option for the PDP-8? It'd be nice to play Spacewar! and run other graphical programs.

**Comment by markpizz** [comment]
The PDP11 indeed has graphics support for a simulated VR14 device.

Try building the PDP11 code in the master branch and run it with the following configuration:

     sim> SET VT ENABLE
     sim> BOOT VT

The PDP1 has support for spacewar.  Look in the PDP1 directory.

Both of these things were originally implemented by Phil Budne and Doug Gwyn.

Back to the other dimension of your question:

If you want to implement a device (VC8E) which has software support somewhere you're free to do that.  If you wish to explore this and you want it integrated back into the main source base please do so by leveraging the existing SDL based graphics code in sim_video potentially using the same Display code that the pdp11_vt  device uses.  If you need help getting started please ask here for details.

- Mark

**Comment by drovak** [comment]
Thanks Mark. I do indeed have an interest in adding a device but might need a little handholding for the SimH tie-ins. After looking at `pdp8_defs.h`, I am a bit confused on the terminology used regarding interrupt flags. It looks to me that, hardware-wise, the console TTY and RX8E, for instance, both have individual IE bits that can be modified using their respective interrupt enable functions. However, the RX8E is in the category of "doesn't have a separate IE". Anyways, perhaps this is not relevant in the current discussion; maybe we can take this off the issues area.

**Comment by drovak** [comment]
Well, perhaps this is an appropriate place for this question: is there a specific guide in adding a new device already, or is my best bet to look at similar devices and emulate their structure? Thanks!

**Comment by markpizz** [comment]
Look at simh.doc and simh_vmio.doc in the doc directory.  Additionally, you will certainly benefit from looking at the existing devices in the pdp8 and pdp11 simulators.  Feel free to ask questions directly to me via email.  I'll either answer directly and/or refer you to other resources as needed.

**Comment by drovak** [comment]
Wonderful; thank you, Mark!

**Comment by markpizz** [comment]
I'm closing this now.  Contact me with specific questions and/or problems as needed.
