### ISSUE TITLE
Indirect register access in examine/deposit commands ... possible?

### ISSUE THREAD

**Issue by AK6DN** [simh/simh#343]
In debugging some code on the PDP11, I have a need to examine memory at a variable location, whose address is in a register (ie, like SP).

Ideally I'd like to do something like:   EX (SP)    or even   EX  4(SP)-12(SP)

Is there a way to do this using existing command syntax? I can't find any way.

Or would this be classified as a new feature?

I just started using the RWSX breakpoint feature (very nice!) but now need the above functionality.

**Comment by markpizz** [comment]
There currently is minimal (no) expression evaluation functionality.
However, there is:

>  sim> ; Display some register value
>  sim> EX SP
>  sim> ; Use the last displayed value as an address to examine now
>  sim> EX $

The $ (last value referenced) was added a while back but hasn't seen much use or your request would have come up earlier.

So, I've just added the extended the allowed syntax to now allow:

>  sim> ; Use the last displayed value as an address to examine now
>  sim> EX $/10

Which will use the last value displayed as the starting address and display that address thru N-1 beyond it (where in this example N is 10).

Additionally, you can combine both of these in a breakpoint action string:

> sim>    bre 100 ; ex sp ; ex $/12
> sim> dep pc 100
> sim> g
> 
> Breakpoint, PC: 000100 (HALT)
> sim> ex sp
> SP:     000000
> sim> ex $/12
> 0:      000000
> 2:      000000
> 4:      000000
> 6:      000000
> 10:     000000
> sim>

**Comment by AK6DN** [comment]
Thanks for the pointer, that seems to work. I tried this:

`set break -sx 17777172 ; ex r0,$,r1,$,r2,$,r3,$,r4,$,r5,$,sp,$ ; cont`

and it does what you might expect, where $ equates to the last value examined.

I don't need the length option just yet, I'll get that when I pull the next commit.

Thanks for the help!
Don
