### ISSUE TITLE
UBA750 simulation is incorrect

### ISSUE THREAD

**Issue by archivisth** [simh/simh#346]
The UBA750 simulation is incorrect, based on the UBA750 spec, in at least the following ways:
1. The MAP is 512 entries, not 496. Unibus address17:9 selects the map entry, with no checking.
2. MAP entries have no LWAE bit.
3. MAP entries have a 14b PFN field - UBAMAP_PAG = 0x3FFF, not 0x1FFFFF. (The same issue exists in the MBA, which is shared with the 780.)
4. MAP entries have a 2b datapath field - UBAMAP_M_DP = 0x3, not 0xF.
5. There are no datapath registers, period. It is unclear whether they are read 0, write NOP, or cause an NXM.
6. CSR1-330:29, the two errors bits, are write 1 to clear, CSR<31,0> are read only.

These observations are based on a code read.

**Comment by 9track** [comment]
I've modified the UBA750 simulation, incorporating these comments. Ultrix appears to access the non-existant datapath registers and given that this works on the real hardware the most likely option seems to be read 0 and write NOP. I think this will be true for any access to the UBI outside of the known registers.
