### ISSUE TITLE
PDP 11/73 emulator with RT-11 5.7 and TSX 601

### ISSUE THREAD

**Issue by pverdet** [simh/simh#351]
Hi, 
I have build a virtual PDP, with 11/73, RA82 disk, and DZ11 (cf attached file)
[Conf.txt](https://github.com/simh/simh/files/599819/Conf.txt)
The machine work well :
PDP-11 simulator V4.0-0 Beta        git commit id: b8842e40
Disabling RK
Disabling HK
Disabling TM
PCLK    100K Hz, address=17772540-17772545, vector=104
        50 Hz Line Frequency
RQ      address=17772150-17772153, no vector, RQDX3, 4 units
  RQ0   622MB, attached to RT-11 V57 BIN RA82.dsk, write enabled
        RA82, autosize, SIMH format
  RQ1   159MB, not attached, write enabled
        RD54, autosize, SIMH format
  RQ2   159MB, not attached, write enabled
        RD54, autosize, SIMH format
  RQ3   800KB, not attached, write enabled
        RX50, autosize, SIMH format
Listening on port 10000
boot RQ0

Connected to the PDP-11 simulator CON-TEL device

RT-11SB (S) V05.07
.R MSCPCK
.SH
TT  (Resident)
DU  (Resident)
    DU0 = DK , SY
LD
VM
LP
NL
6 free slots
Until I ran TSXplus

.R TSX
* TSX-Plus Version 6.01 *

Copyright (c) 1980, 1981, 1982, 1983, 1984, 1985 an unpublished work by
S&H Computer Systems, Inc., Nashville, TN, USA (S&H) All rights reserved.
This material contains the valuable properties and trade secrets of S&H
and may not be used except by the express written permission of S&H.
Distributed by JPY Associates Limited
Licensed for use on a single computer system at HI TECH SYSTEMS S A
License # = 56-T1S-10783

Line # 1
.
HALT instruction, PC: 150006 (HALT)
sim>

May be a conflicting version ? I'm unable do find a compatibility matrix between RT-11/TSX on internet.
Anyone could help me ?
Thanks

**Comment by markpizz** [comment]
This question seems to be an issue with the software you are trying to run on the simulator as opposed to a specific problem with the simulator you are using.  If my answer below isn't sufficient, I suggest you look for resources specifically related to that OS or ask this general question on the simh mailing list.  

Meanwhile, A little poking around brings me to:  http://shop-pdp.net/tshtml/tsxpls.htm

Which has a paragraph that says:

>  TSX-Plus  will  run  on  any  PDP-11 or LSI-11 computer with
memory management hardware and at least 128Kb of  memory.   The
system must also have a disk suitable for program swapping (the
swapping disk can be used for regular file  storage  as  well).
Time-sharing  lines and serial printers may be connected to the
system   through   DH(U,V,Q)-11,    DL(V)-11,    or    DZ(V)-11
communication devices.  Both hardwired and dial-up time-sharing
lines are supported by TSX-Plus.

That would suggest that the simulated hardware should be good.  
However it seems that TSX depends on "RT-11 XM" which is mentioned earlier in that same article:

> -  TSX-Plus uses RT-11 XM version device handlers. 

Additionally, the page at: https://en.wikipedia.org/wiki/RT-11 mentions:

> Versions
> Users could choose from four variants with differing levels of support for multitasking:
> RT-11SJ (Single Job) allowed only one task. This was the initial distribution.
> RT-11FB (Foreground/Background) supported two tasks: a high-priority, non-interactive "Foreground" job, and a low-priority, interactive "Background" job.
> RT-11XM (eXtended Memory) provided support for memory beyond 64kb, but required a minicomputer with memory management hardware; distributed from approx. 1975-on.
> RT-11ZM provided support for systems with Separate Instruction and Data space (such as on the Unibus-based 11/44, 45, 55, 70, 84, and 94 and the Q-Bus-based 11/53, 73, 83, and 93)

The combination of information here would suggest to me that RT-11XM might be what you should be running to get the XM functionality TSX needs.

**Comment by pverdet** [comment]
Hi Mark,
Thanks for your answer. 
Please look on TSX-Plus-601_Installation_Guide manual, page 48, He say that : 
TSX-Plus may be started under RT11SJ (Single job)...
I do that 35 years ago, on real pdp11/73, and it's work fine ...
This morning, I try the same think without telnet connection on console ... It's same issse :-(

**Comment by markpizz** [comment]
OK.  I've never been a user of the software you're using here.

Are you sure the system you've got configured has the same set of hardware as your original system?

For instance:
     Why do you have:

        set PCLK enable
        set PCLK 50

Additionally, you've got:

        set dz enable
        set dz 8b
        set dz lines=8
        ;attach dz 8023

I notice that the attach command is commented out.  Having terminal lines without anyone being able to connect to them would seem at least odd to me given you're trying to run a package (TSX) which enables multi-user access...

**Comment by markpizz** [comment]
By the way, since you said:
> This morning, I try the same think without telnet connection on console ... It's same issse :-(

This would certainly be expected since the only difference you realize when the telnet console path is enabled is that the console serial port on the simulator will be separate from the interface which directly controls the simulator (via ^E and commands from the sim> prompt).  A telnet connected console would also allow you to connect a terminal emulator of your liking connecting through the telnet session.  It would seem that you really haven't gotten far enough to care much about a terminal emulator's abilities.

**Comment by pverdet** [comment]
;attach dz 8023
Yes, I leave the DZ unused, until the TSX work; I try with the console only to insure that the Ethernet connection in not the problem.
When the processor "Halt", is it possible to have a stack trace ?
 _(On Aix debugger, it' s very useful way to find where is the root problem. )_

**Comment by markpizz** [comment]
First I would uncommented the dz attach command.  There may be a programmatic difference with the device attached or not (that would be a simulator bug).  You don't have to connect anything to the dz port until TSX is working.

Second, when you get the HALT message that means that the running program merely executed a HALT instruction.  At the "sim>" prompt you can look at all the state of the simulated machine (registers, memory contents, etc.) with the "EXamine" command.  If you run with instruction history recording enabled ( SET HISTORY=200), you can see how things got to the HALT instruction with SHOW HISTORY after the HALT.  HELP CPU will provide some useful clues as to how to interact with the simulator.

**Comment by pverdet** [comment]
Ok, I understand.
I try to install Unix V7 on PDP simulator. 
[uboot.txt](https://github.com/simh/simh/files/603130/uboot.txt)
It's work well as design .
Boot
: hp(0,0)unix
mem = 2020544
#
# RESTRICTED RIGHTS: USE, DUPLICATION, OR DISCLOSURE
IS SUBJECT TO RESTRICTIONS STATED IN YOUR CONTRACT WITH
WESTERN ELECTRIC COMPANY, INC.
WED DEC 31 19:37:13 EST 1969

login: root
Password:
You have mail.
#
I have apply the path to handle DZ, and them working file.
I think that the issue is  conflicting version between RT-11 and TSX, or may be when I try to simulate a PDP 11/73, a conflict between 11/73 Qbus architecture and DZ11 unibus ?
How is handled DZ in simulator ?

**Comment by markpizz** [comment]
I'm a little confused.  How come you're suddenly jumping from RT-11/TSX to Unix???

Essentially the only difference between the Unibus DZ11 and the Qbus DZQ11 is that the Unibus device has 8 ports per controller, while the Qbus device has 4 ports per controller.  The simulator deals with simulating the appropriate number of controllers based on the number of "lines" you configure on the device and the native bus for the CPU being simulated (Qbus or Unibus PDP11 model).  Each simulated controller has its own set of device registers that the device driver uses to interface with the respective serial ports on the multiplexer.

**Comment by pverdet** [comment]
Hi. 
This is to determine if it is the simulated hardware that is the root cause, or if I have to investigate for software issue. 
As Unix works fine, I will try to find the cause of the "halt" using the CPU history, and registers.
But I think the problem is either a version conflict between RT-11 and TSX, or possibly a bad grasp of the DZ driver by TSX ...

**Comment by markpizz** [comment]
OK, but using history and registers may be pretty hard without some sort of source code for the TSX you are running.

Meanwhile, since you're considering the version conflict between the RT-11 you're using and TSX, AND since the TSX is documented as leveraging the XM driver interfaces, you might want to try using RT-11XM....

**Comment by pverdet** [comment]
Hi,
Here is a examine of main registers when the HALT occur 
sim> e R0,R1,R2,R3,R4,R5,SP,PC,CPUERR,PIRQ,PSW
R0:     000061
R1:     000002
R2:     042550
R3:     000200
R4:     000001
R5:     054656
SP:     141410
PC:     150006
CPUERR: 000160
PIRQ:   000000
PSW:    000341  CM=K PM=K RS0 FPD0 IPL=7 TBIT0 N0 Z0 V0 C1
sim>
I'm ok with the psw, but how to read the cpuerre register ? Thanks

**Comment by pverdet** [comment]
I have found that in KDJ11 user's manual
![cpu error register](https://cloud.githubusercontent.com/assets/23553379/20750207/f5afff20-b6f5-11e6-9462-d5937030920c.png)
But, what is the meaning of 000160

**Comment by R-Voorhorst** [comment]
This is clearly octal coded: 0-7 per digit

00160 would mean Address error+not existing memory+I/O bus timeout; the combination could make sense.

 

 

Regards

**Comment by pverdet** [comment]
Hi, Thanks. It's a mistake from me. I'm not used to the octal ...
I have to get back into the bath!

**Comment by R-Voorhorst** [comment]
Pas de problèmes, enjoy J.

**Comment by pverdet** [comment]
Yes, this makes sense, the first job of TSXplus, is to allocate itself some working memory.
However, I walking trough the system registers,  I find memory management registers,but I can't find page registers...
sim> e pc,mmr0-mmr3,psw,sp
PC:     150006, (HALT)
MMR0:   000357
MMR1:   000000
MMR2:   150004
MMR3:   000020
PSW:    000341  CM=K PM=K RS0 FPD0 IPL=7 TBIT0 N0 Z0 V0 C1
SP:     141416
sim>
How to display the instruction before halt ?
Please can you help me ?

**Comment by markpizz** [comment]
Before you run the program enable instruction history:

     sim> SET HISTORY=100

When the HALT returns you to the "sim>" prompt, you SHOW HISTORY and the instructions executed up to the HALT will be displayed.

The problem you're having may not be the instruction immediately prior to the HALT, but somewhere before that.  You can put a SIMH breakpoint at any point you want to stop execution to look around.

      sim> BREAK 200

will set a breakpoint which will stop execution when the PC reaches 200.

The PDP11 simulator has other types of breakpoints as well.  HELP CPU should give you some clues about options.

**Comment by pverdet** [comment]
Hi,
Thanks, it's very useful command,
It seams that a test will be not good ...
120100 030340|               BHI 120310
120310 030340|000340 030000  BIC @#13610,@#177776
120316 030000|151260 151260  MOV (SP)+,R2
120320 030010|000002 000002  MOV (SP)+,R1
120322 030000|       120324  RTS PC
120050 030000|       120052  RTS PC
014340 030000|       014342  RTS PC
013774 030000|000340 030340  BIS #340,@#177776
014002 030340|       000000  CLRB @#13472
014006 030344|000002 000002  MOVB @#13466,R1
014012 030340|               BEQ 14042
014014 030340|000030 000015  CMP 7330(R1),#15
014022 030340|               BHI 14042
014042 030340|000340 030000  BIC @#13610,@#177776
014050 030000|               BR 13770
013770 030000|000000 014314  JSR PC,@#14314
014314 030000|       000001  TSTB @#6132
014320 030000|               BEQ 14340
150004 000341|               HALT
sim>

**Comment by pverdet** [comment]
Hi,
After making several tests, with RT-11 different s versions, the problem is the same, with different address, depending of the size of the monitor.
I assume that is a memory management problem , from tsx, from rt-11 ? I don't know, but without TSX sources, it's very difficult to debug.
I close this case.
Cheers,
Pascal

**Comment by pverdet** [comment]
Hi,
After further investigation, I found a note from TSX conceptors:

  Device handlers were not updated.  The base version of RT-11 from
  which device handlers were derived remains RT-11 V05.04C.  Most
  significantly, **this means that extended unit support for DU is not
  included.  For sites with MSCP devices larger than 256Mb, contact
  S&H for information on "pass through" or "front end" handlers which
  allow you to fully utilize large MSCP devices.**

I will try to check, if the problem is the same with "classic" disk (eg RL02)

**Comment by pverdet** [comment]
Working only on RL02, RT-11 work fine, but the problem remain, with another kind of error message
.R TSX
?TSX-F-Error reading device handler file: DL

sim> SH RL
RL      RLV12, address=17774400-17774411, vector=160, 4 units
  RL0   5242KW, attached to RT-11 V5.7 BIN WORKING.DSK, on line write enabled, RL02
  RL1   5242KW, attached to tsx601.dsk, on line                                write enabled, RL02
  RL2   2621KW, not attached, on line        write enabled, autosize
  RL3   2621KW, not attached, on line        write enabled, autosize

TSX version is 6.01, If someone wants to share with me a TSX version 6.05 ... ?
Thanks

**Comment by pverdet** [comment]
Working on, seems it's clock issue. I open a new issue
