### ISSUE TITLE
KLDCP PDP-11 DECTape, simh booting woes

### ISSUE THREAD

**Issue by markpizz** [simh/simh#358]
Yeah, exactly, hmm...

It turns out that the TC11 is a lot more like a traditional DECtape controller (such as the TC15) than it is a normal PDP11 device. The 'DO' 
bit is not the 'kick off execution' gate I thought it was; that is, it is not a 'GO' bit. Instead:

1) Writing TCCM is the big gate. You can set direction, function, etc, without setting DO. If the selected tape is not in motion, it is started. So the mov #4002,tccm work fine. It starts the tape searching in the reverse direction, but it doesn't clear READY. This is okay for detecting the end zone via the error register.

2) Writing DO clears READY; that's pretty much all it does, in fact. 
(The rest of the command register is written at the same time; see point
1.) However, that's needed before a true block number search or a data transfer, to avoid reading the data register prematurely. Ready is also cleared automagically by RALL, WALL, and WRTM without DO.

That's why mov #4002,tccm works for finding end zones, but mov #3,tccm is needed to actually read a block number.

Fixing this is going to take some surgery; more in the nature of going back to the code's roots in the PDP-8 and PDP-15 simulators than new invention. It will take some time to check out, so please be patient.

Thanks for bringing this to my attention. There's nothing like real hardware to show up the limitations of simulators.

/Bob

I've copied Mark Pizzolato so that he can open an issue in GitHub and assign it to me.

On 12/2/2016 8:01 PM, Josh Dersch wrote:
> And I've confirmed the behavior works on the real hardware; if I execute the MOV #4002,@#TCCM instruction, the tape reverses.  I can execute this as many times as I like and it continues to work, regardless of whether I Continue execution or do a Start (which resets the bus) from the front panel.
>
> Hmm.
>
> - Josh
>
>> -----Original Message-----
>> From: Josh Dersch
>> Sent: Friday, December 2, 2016 4:15 PM
>> To: 'Bob Supnik' <bob@supnik.org>
>> Subject: RE: KLDCP PDP-11 DECTape, simh booting woes
>>
>> And that's interesting, I just noticed the toggle-in bootstrap 
>> doesn't have the DO bit set either at 1010.
>>
>> This is the same loader as listed at 
>> http://www.psych.usyd.edu.au/pdp- 11/bootstraps.html, so it isn't 
>> just my listing here (which came from god knows where, it's taped to 
>> the front panel of the machine...)
>>
>> - Josh
>>
>>
>>> -----Original Message-----
>>> From: Josh Dersch
>>> Sent: Friday, December 2, 2016 3:44 PM
>>> To: 'Bob Supnik' <bob@supnik.org>
>>> Subject: RE: KLDCP PDP-11 DECTape, simh booting woes
>>>
>>> Yeah, I noticed that oddity at 74 as well but I don't know the TC11 
>>> hardware enough to know if that was truly broken or just something I 
>>> didn't understand.
>>>
>>> Your explanation for what's going on makes sense given that.
>>>
>>> The bootstrap that we use on the 11/40 is the toggle-in bootstrap 
>>> that's much simpler than the simh one, but the end result *seemed* 
>>> to be identical so I figured the two were interchangeable, perhaps 
>>> there is a subtle difference there, but if there is, I'm not seeing it...
>>>
>>> I just tried the toggle-in bootstrap (see below) and it doesn't seem 
>>> to want to work either, looping at 1014/1016 indefinitely.
>>>
>>> I've attached the KLDCP tape, in simh format.
>>>
>>> Thanks,
>>> Josh
>>>
>>> Bootstrap:
>>>
>>> @1000:012700      mov #177344,r0    ;TCWC DECtape word count register
>>> address
>>>        177344
>>>        012710      mov #-400,(r0)    ;Negative count in TCWC
>>>        177400
>>>        012740      mov #4002,-(r0)   ;Reverse tape, read in TCCM
>>>        004002
>>>        005710      tst (r0)          ;Error bit set?
>>>        100376      bpl .-2           ;No, check again
>>>        012710      mov #3,(r0)       ;Put GET BLOCK # + DO into TCCM
>>>        000003
>>>        105710      tstb (r0)         ;Ready bit set? (= operation done)
>>>        100376      bpl .-2           ;No, check again
>>>        012710      mov #5,(r0)       ;Put READ + DO into TCCM
>>>        000005
>>>        105710      tstb (r0)         ;Ready bit set? (= command complete)
>>>        100376      bpl .-2           ;No, check again
>>>        005007      clr r7            ;Set PC to 0
>>>
>>>
>>>> -----Original Message-----
>>>> From: Bob Supnik [mailto:bob@supnik.org]
>>>> Sent: Friday, December 2, 2016 2:48 PM
>>>> To: Josh Dersch <JoshD@livingcomputers.org>
>>>> Subject: Re: KLDCP PDP-11 DECTape, simh booting woes
>>>>
>>>> I think you had best send me the tape; from the disassembly, I 
>>>> already don't understand what is going on.
>>>>
>>>> In particular, the command at line 74 does not have the GO bit set.
>>>> I thought the TC11 will simply ignore writes to TCCM if GO is not 
>>>> set; certainly the simulator will. So the tape, which was left 
>>>> moving forward by the bootstrap, continues to move forward until it 
>>>> hits the end zone - in this case, the end of tape end zone. Now the 
>>>> read block number forward command will, in fact, never see a block 
>>>> and will not set
>>> ready.
>>>> Instead, the end zone flag will come up again, and the simulator will halt.
>>>>
>>>> Contrast the sequence in the boot block with the actual bootstrap 
>>>> code (which was taken from official DEC bootstraps):
>>>>
>>>> static const uint16 boot_rom[] = {
>>>>       0042124,                        /* "TD" */
>>>>       0012706, BOOT_START,            /* MOV #boot_start, SP */
>>>>       0012700, 0000000,               /* MOV #unit, R0        ; unit
>>>> number */
>>>>       0010003,                        /* MOV R0, R3 */
>>>>       0000303,                        /* SWAB R3 */
>>>>       0012701, 0177342,               /* MOV #TCCM, R1        ; csr */
>>>>       0012702, 0004003,               /* RW: MOV #4003, R2    ;
>>>> rev+rnum+go */ <<< has go set
>>>>       0050302,                        /* BIS R3, R2 */
>>>>       0010211,                        /* MOV R2, (R1)         ; load csr */
>>>>       0032711, 0100200,               /* BIT #100200, (R1)    ; wait */
>>>>       0001775,                        /* BEQ .-4 */
>>>>       0100370,                        /* BPL RW               ; no err,
>>>> cont */
>>>>       0005761, 0177776,               /* TST -2(R1)           ; end zone? */
>>>>       0100036,                        /* BPL ER               ; no, err */
>>>>       0012702, 0000003,               /* MOV #3, R2           ; rnum+go */
>>>>       0050302,                        /* BIS R3, R2 */
>>>>       0010211,                        /* MOV R2, (R1)         ; load csr */
>>>>       0032711, 0100200,               /* BIT #100200, (R1)    ; wait */
>>>>       0001775,                        /* BEQ .-4 */
>>>>       0100426,                        /* BMI ER               ; err, die */
>>>>       0005761, 0000006,               /* TST 6(R1)            ; blk 0? */
>>>>       0001023,                        /* BNE ER               ; no, die */
>>>>       0012761, 0177000, 0000002,      /* MOV #-256.*2, 2(R1)  ; load wc */
>>>>       0005061, 0000004,               /* CLR 4(R1)            ; clear ba */
>>>>       0012702, 0000005,               /* MOV #READ+GO, R2     ; read & go */
>>>>       0050302,                        /* BIS R3, R2 */
>>>>       0010211,                        /* MOV R2, (R1)         ; load csr */
>>>>       0005002,                        /* CLR R2 */
>>>>       0005003,                        /* CLR R3 */
>>>>       0012704, BOOT_START+020,        /* MOV #START+20, R4 */
>>>>       0005005,                        /* CLR R5 */
>>>>       0032711, 0100200,               /* BIT #100200, (R1)    ; wait */
>>>>       0001775,                        /* BEQ .-4 */
>>>>       0100401,                        /* BMI ER               ; err, die */
>>>>       0005007,                        /* CLR PC */
>>>>       0012711, 0000001,               /* ER: MOV #1, (R1)     ; stop all */
>>>>       0000000                         /* HALT */
>>>>       };
>>>>
>>>> Because this tape works on the real 11/40, the most likely case is 
>>>> that the simulator is treating a "change of command while in motion"
>>>> incorrectly. I will have to go and dig through the maintenance 
>>>> manual to see what is going on.
>>>>
>>>> There's a remote chance that the transcription process from real 
>>>> tape to simulated tape failed in some way, but it seems highly 
>>>> unlikely, given that the tape works.
>>>>
>>>> /Bob
>>>>
>>>> On 12/2/2016 4:16 PM, Josh Dersch wrote:
>>>>> Hi Bob --
>>>>>
>>>>> I've imaged a fairly obscure DECTape at the museum this week; it's 
>>>>> a
>>>> Stanford KLDCP boot tape used to run the front-end for a WAITS 
>>>> system on a 2065.  I'm attempting to get it to boot on SIMH and the 
>>>> bootstrap code appears to be dying for reasons I don't understand 
>>>> -- I'm curious if this might be an emulation bug.  (On the real 
>>>> 11/40 front-end machine, this tape boots
>>>> fine.)  For the record, I'm not expecting KLDCP to actually work, 
>>>> but I do expect it to get further than it's getting...
>>>>> The code (with my disassembly notes) follows, this is in block 0 
>>>>> of the tape,
>>>> which is loaded at address 0 by the bootstrap.  When executing, it 
>>>> never gets to 140 (eventually, after thousands of loops, the ERROR 
>>>> flag gets set and the BMI at 130 jumps to 214 to die)  I can do 
>>>> some debugging on the simh codebase but before I get started, I'm 
>>>> curious if you have any thoughts, I don't know if there are known 
>>>> limitations of the simh DECTape emulation or if I'm missing 
>>>> something
>> obvious.
>>>>> I can send you a copy of the tape if you want.
>>>>>
>>>>> Thanks,
>>>>> Josh
>>>>>
>>>>>
>>>>> ; entrypoint
>>>>> 0:      BR 70				; continue elsewhere
>>>>>
>>>>> ; elsewhere
>>>>> 70:     MOV #17744,SP		; set stack
>>>>>
>>>>> 							; Rewind tape until
>>>> we hit ENDZ:
>>>>> 74:     MOV #4002,@#177342	; write command register -- read
>>> block #, unit
>>>> 0, reverse
>>>>> 102:    TST @#177342		;
>>>>> 106:    BPL 102				; wait until error bit is set in
>>> command
>>>> reg (bit 15)
>>>>> 110:    TST @#177340		; check status register
>>>>> 114:    BPL 214				; if not ENDZ (bit 15),
>>> something's
>>>> wrong, halt.
>>>>> 							; Find block 30:
>>>>> 116:    MOV #3,@#177342		; write command reg -- RNUM, DO,
>>>> unit 0, forward
>>>>> 124:    TST @#177342
>>>>> 130:    BMI 214				; if error, halt
>>>>> 132:    TSTB @#177342		; test low byte
>>>>> 136:    BPL 124				; not ready (bit 7 clear), try it
>>> again
>>>>> 140:    CMP @#177350,#30	; is this block 30?
>>>>> 146:    BCS 116				; no -- do the next one
>>>>> 150:    BHI 214				; greater than 30, we missed
>>> it
>>>> somehow, halt.
>>>>> 							; Read in blocks from
>>>> tape:
>>>>> 152:    MOV #163400,@#177344	; write word count -- 6400(10) words
>>>> to read
>>>>> 160:    CLR @#177346		; clear bus address register
>>>>> 164:    MOV #5,@#177342		; RDATA, DO, unit 0, forward to
>>>> command reg
>>>>> 172:    TST @#177342
>>>>> 176:    BMI 214				; error?  go off and halt
>>>>> 200:    TSTB @#177342
>>>>> 204:    BPL 172				; not ready? keep waiting.
>>>>>
>>>>> 							; Jump to loaded
>>>> code:
>>>>> 206:    RESET				; reset everything
>>>>> 210:    MOV #1200,PC		; start at 1200
>>>>>
>>>>> ; error: save status code in r0, stop tape, halt.
>>>>> 214:    MOV @#177342,R0
>>>>> 220:    CLR @#177342
>>>>> 224:    HALT
>>>>>
>

**Comment by livingcomputermuseum** [comment]
Just tested the changes and I can now boot the KLDCP tape.  Thanks!

**Comment by archivisth** [comment]
This issue can be closed.
