### ISSUE TITLE
Compile error building imds-225

### ISSUE THREAD

**Issue by polaris6262** [simh/simh#359]
I tend to always build the simulators using 'make all' even though I have never used most of them. I use a number of Linux distributions and thus I think it provides a good test of the simh source to compile them on many different distributions using various versions of gcc.

One the recently introduced simulators, imds-225, currently fails to build:

gcc -march=native -m64 -std=gnu99 -U__STRICT_ANSI__  -O3 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -DSIM_GIT_COMMIT_ID=cf14061c646a7c2bf349b283e94e4a58f5f887f9 -DSIM_COMPILER="GCC Version: 4.4.7" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_LIBPNG -DHAVE_GLOB -DHAVE_SHM_OPEN  Intel-Systems/common/i8080.c Intel-Systems/imds-225/imds-225_sys.c Intel-Systems/common/i8251.c Intel-Systems/common/i8255.c Intel-Systems/common/i8259.c Intel-Systems/common/i8253.c Intel-Systems/common/ipceprom.c Intel-Systems/common/ipcram8.c Intel-Systems/common/ipcmultibus.c Intel-Systems/imds-225/ipc.c Intel-Systems/common/ipc-cont.c Intel-Systems/common/ioc-cont.c Intel-Systems/common/isbc202.c Intel-Systems/common/isbc201.c Intel-Systems/common/zx200a.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -I Intel-Systems/imds-225 -o BIN/imds-225 -lm -lrt -lpthread -lpcreposix -ldl -lpng  
Intel-Systems/common/ipceprom.c: In function ‘EPROM_get_mbyte’:
Intel-Systems/common/ipceprom.c:176: warning: implicit declaration of function ‘SET_XACK’
Intel-Systems/common/ipcram8.c: In function ‘RAM_get_mbyte’:
Intel-Systems/common/ipcram8.c:127: warning: implicit declaration of function ‘SET_XACK’
Intel-Systems/common/ipcmultibus.c: In function ‘multibus_reset’:
Intel-Systems/common/ipcmultibus.c:156: error: ‘SBC201_BASE’ undeclared (first use in this function)
Intel-Systems/common/ipcmultibus.c:156: error: (Each undeclared identifier is reported only once
Intel-Systems/common/ipcmultibus.c:156: error: for each function it appears in.)
Intel-Systems/common/ipcmultibus.c:158: error: ‘SBC202_BASE’ undeclared (first use in this function)
Intel-Systems/common/isbc202.c: In function ‘isbc202_reset’:
Intel-Systems/common/isbc202.c:310: error: ‘SBC202_NUM’ undeclared (first use in this function)
Intel-Systems/common/isbc202.c:310: error: (Each undeclared identifier is reported only once
Intel-Systems/common/isbc202.c:310: error: for each function it appears in.)
Intel-Systems/common/isbc202.c: In function ‘isbc202_get_dn’:
Intel-Systems/common/isbc202.c:464: error: ‘SBC202_NUM’ undeclared (first use in this function)
Intel-Systems/common/isbc201.c: In function ‘isbc201_reset’:
Intel-Systems/common/isbc201.c:307: error: ‘SBC201_NUM’ undeclared (first use in this function)
Intel-Systems/common/isbc201.c:307: error: (Each undeclared identifier is reported only once
Intel-Systems/common/isbc201.c:307: error: for each function it appears in.)
Intel-Systems/common/isbc201.c: In function ‘isbc201_get_dn’:
Intel-Systems/common/isbc201.c:443: error: ‘SBC201_NUM’ undeclared (first use in this function)
Intel-Systems/common/zx200a.c: In function ‘zx200a_reset’:
Intel-Systems/common/zx200a.c:316: error: ‘ZX200A_NUM’ undeclared (first use in this function)
Intel-Systems/common/zx200a.c:316: error: (Each undeclared identifier is reported only once
Intel-Systems/common/zx200a.c:316: error: for each function it appears in.)
Intel-Systems/common/zx200a.c: In function ‘zx200_get_dn’:
Intel-Systems/common/zx200a.c:474: error: ‘ZX200A_NUM’ undeclared (first use in this function)
make: *** [BIN/imds-225] Error 1

This is on Red Hat Linux 6.8 using gcc version 4.4.7, admittedly a fairly old release but which is still supported. I plan to try more recent releases on other Linux distributions.

**Comment by markpizz** [comment]
Oops..  The imds-225 simulator is not ready for prime time and as such certainly shouldn't have been included in the 'make all' target set.
