### ISSUE TITLE
MicroVAX 3900 - old original SIMH bootrom fails self test

### ISSUE THREAD

**Issue by agn453** [simh/simh#366]
Something has happened that now causes the old SIMH MicroVAX 3900 microcode self-test to fail.  This is using the original ka655.bin that I've been using since SIMH V3.1 (or before).

trillian:~/simh$ ls -la ka655.bin 
-rwxrwx---+ 1 Tony Tony 131072 Nov 23  2001 ka655.bin

Using the current (latest) GitHub sources -

trillian:~/simh$ vax

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: 36276a79
sim> show version
MicroVAX 3900 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                Asynchronous I/O support
                Asynchronous Clock support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 5.4.0
                Simulator Compiled as C arch: x86 (Release Build) on Dec 19 2016 at 08:59:27
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.3
                No RegEx support for EXPECT commands
                OS clock resolution: 1ms
                OS: CYGWIN_NT-10.0-WOW trillian 2.6.0(0.304/5/3) 2016-08-31 14:27 i686 Cygwin
        git commit id: 36276a79
sim> load -r ka655.bin
sim> att nvr vaxnvram.bin
NVR: buffering file in memory
sim> boot cpu

KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..

?53 2 09 FF 00 0000

P1=00000002  P2=00000028  P3=80001B43  P4=00D40077  P5=00000000
P6=FFFFFFFF  P7=00000000  P8=00000000  P9=00000000 P10=20051CE0
r0=00000000  r1=20140110  r2=C5FC3F66  r3=000302F5  r4=C5FC3F70
r5=2004E8F9  r6=00018678  r7=000186C8  r8=00016B5D ERF=80000000
30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Normal operation not possible.

Compared with a version I compiled a few weeks ago -

trillian:~/simh$ ../src/simh-master-f8147fca/BIN/microvax3900.exe 

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: f8147fca
sim> show version
MicroVAX 3900 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                Asynchronous I/O support
                Asynchronous Clock support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 5.4.0
                Simulator Compiled as C arch: x86 (Release Build) on Nov 28 2016 at 12:02:57
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.3
                No RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 2ms
                OS: CYGWIN_NT-10.0-WOW trillian 2.6.0(0.304/5/3) 2016-08-31 14:27 i686 Cygwin
        git commit id: f8147fca
sim> load -r ka655.bin
sim> att nvr vaxnvram.bin
NVR: buffering file in memory
sim> boot cpu

KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Tests completed.
>>>

If I switch to using the built-in ka655x rom code things appear to be fine (maybe more selftests have been bypassed in this).  Just reporting in case you get other reports like this!  I've been using the same old version of KA655.BIN for a very long time!  According to the KA655 System Maintenance guide - test 53 is a TOY Clock test.

I also tried this under Visual Studio Express 2013 for Desktop - and the old boot rom selftest sometimes hangs after test 30 or 31 - and sometimes completes normally to the chevron >>> prompt.  Weird!

Tony

**Comment by markpizz** [comment]
Hi Tony,

The test which is failing has nothing to do with the ROM image you're using.  The sometimes completes normally and sometimes doesn't is the problem.  It is a matter of timing chance.  

The test 53 (as indicated in "?53 2 09 FF 00 0000") is measuring the TODR (Time of Year clock) with the interval timer, and if exceeds certain tolerance values the test fails.

The built-in ROM has only changed once since the large memory support was added and it doesn't disable any different ROM tests than were already disabled in the original ROM.

The sim_timer library has been massively reworked over the past several weeks.  While that was happening the various things about the TODR and interval timer implementation in the VAX simulator were changed.  I'll look more closely at this.

**Comment by markpizz** [comment]
Tony,

Can you provide the output of "SHOW CLOCK" for both the failing and successful cases using the latest code?

Thanks.
- Mark

**Comment by agn453** [comment]
Mark,

See below

Failing version (current code)

trillian:~/simh$ vax

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: 36276a79
sim> load -r ka655.bin
sim> att nvr vaxnvram.bin
NVR: buffering file in memory
sim> boot cpu


KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..

?53 2 09 FF 00 0000

P1=00000002  P2=00000028  P3=80001B3C  P4=00D40077  P5=00000000
P6=FFFFFFFF  P7=00000000  P8=00000000  P9=00000000 P10=20051CE0
r0=00000000  r1=20140110  r2=C6108B1B  r3=000302F5  r4=C6108B25
r5=2004E8F9  r6=00018678  r7=000186C8  r8=00016B64 ERF=80000000
30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Normal operation not possible.

>>>
Simulation stopped, PC: 2004368F (BEQL 200436A6)
sim> show clock
Minimum Host Sleep Time:       1 ms (1000Hz)
Host Clock Resolution:         1 ms
Execution Rate:                787,600 instructions/sec
Calibrated Timer:              CLK
Calibration:                   Always

MicroVAX 3900 clock device is CLK
Calibrated Timer 0:
  Running at:                100 Hz
  Tick Size:                 10 msecs
  Ticks in current second:   54
  Seconds Running:           9 (9 seconds)
  Calibration Opportunities: 9
  Instruction Time:          6491190
  Real Time:                 348516714
  Virtual Time:              348516718
  Next Interval:             1,004
  Base Tick Delay:           7,845
  Initial Insts Per Tick:    5,000
  Current Insts Per Tick:    7,876
  Initializations:           3
  Total Ticks:               954
  Tick Time:                 9.53 seconds
  Initialize Base Time:      12:50:24.838
  Tick Start Time:           12:50:25.158
  Wall Clock Time Now:       12:50:38.632
sim> 


Previous version that worked -

trillian:~/simh$ ../src/simh-master-f8147fca/BIN/microvax3900.exe 

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: f8147fca
sim> load -r ka655.bin
sim> att nvr vaxnvram.bin
NVR: buffering file in memory
sim> boot cpu


KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Tests completed.
>>>
Simulation stopped, PC: 20043617 (BNEQ 2004362D)
sim> show clock
Minimum Host Sleep Time:       2 ms (500Hz)
Host Clock Resolution:         1 ms
Execution Rate:                781000 instructios/sec
Calibrated Timer:              CLK


MicroVAX 3900 clock device is CLK
Calibrated Timer 0:
  Running at:               100 Hz
  Tick Size:                10 msecs
  Ticks in current second:  15
  Seconds Running:          9 (9 seconds)
  Calibrations:             9
  Instruction Time:         6620188
  Real Time:                348886027
  Virtual Time:             348886026
  Next Interval:            999
  Base Tick Delay:          7818
  Initial Insts Per Tick:   5000
  Current Insts Per Tick:   7810
  Initializations:          3
  Total Ticks:              915
  Tick Time:                9.14 seconds
  Wall Clock Time Now:      12:56:47.642
sim> 

Tony

**Comment by markpizz** [comment]
Hi Tony,

I don't see this failing (as I said it is a matter of timing - sometimes it works and other times it doesn't).  I did see the problem a few weeks back while working my way through changing sim_timer.  At that time, the problems were specifically related to unfinished functionality in sim_timer.

Your initial comments about there being differences in what diagnostics were disabled in old vs new ROM versions weren't 100% off track.  The change wasn't in the ROM, but in the simulation code having been tweaked internally to behave so the ROM test passed.  Specifically the interval timer is defined to counts microseconds.    The previous simulator code which implemented the interval timer functionality didn't actually count microseconds.  It counted instructions for short intervals (less than 10ms) and counted 10ms clock ticks for long intervals and then instructions once the remaining interval count got to be shorter than 10ms.  The new sim_timer functionality has the ability to deal with microsecond intervals reliably and, as such, I changed the VAX interval timer code to count microseconds in all cases which made it match the real hardware and made the implementation significantly simpler.

The problem we're seeing intermittently now actually was there intermittently prior to simh 3.0 (2003).  To solve this at that time, the count instructions strategy for short intervals was established.

I'm not seeing the failures on my system(s), so I can't really take any steps to identify why exactly what isn't behaving as needed.

I will be less available for the next week or so as the holiday approaches.  I'll keep thinking about this and I may have to revert to the prior strategy....

**Comment by agn453** [comment]
Thanks for looking into this Mark.

For now I've switched to using the internal KA655X bootcode and I haven't (yet) seen the bootrom selftest fail using this.  I've only seen it on my PC - a 5 year-old Intel Core i7 870 LGA1156 CPU @ 2.93GHz running Windows 10 version 1607 (OS Build 14393.576) and SSD - and it's Cygwin I'm using (I know it's not a supported/preferred combination - but I like the X11 capabilities it provides in allowing me to run SIMH in xterm windows).  SIMH VAX on my Mac mini under macOS Sierra runs fine (if somewhat limited by a less capable CPU and slower hard drive).

Enjoy your holidays and all the best for the New Year!

Tony

**Comment by markpizz** [comment]
Thanks for repeating that suggestion.  I can't explain why, but I've now seen it when loading an original boot ROM.  As I mentioned, earlier while working on changes to sim_timer, I saw it with the built in ROM, and I've seen it once or twice since (out of hundreds of attempts).

**Comment by markpizz** [comment]
Tony,

There have been additional changes to to the timing subsystem which the failing boot rom test (53) is testing.  I don't see the problem now with either the built-in ROM or by explicitly loading the original KA655.bin ROM image.

Can you confirm that you no longer see the problem.

Thanks.

**Comment by agn453** [comment]
Mark,

I still see it with the most recent sources - however, (and this is the weird part) only if I remote desktop into my PC.  I was using my Mac when I received your message, so opened up Microsoft's Remote Desktop for Mac app - connected to my PC, grabbed the latest sources and compiled to see -

trillian:~/simh$ vax

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: 6ebeb345
sim> load -r ka655.bin
sim> att nvr vaxnvram.bin
NVR: buffering file in memory
sim> b cpu


KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..

?53 2 09 FF 00 0000

P1=00000002  P2=00000028  P3=80001B41  P4=00D40077  P5=00000000
P6=FFFFFFFF  P7=00000000  P8=00000000  P9=00000000 P10=20051CE0
r0=00000000  r1=20140110  r2=CB34E82B  r3=000302FF  r4=CB34E835
r5=2004E8F9  r6=00018678  r7=000186C8  r8=00016B5F ERF=80000000
30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Normal operation not possible.

>>>show version
KA655-B V5.3, VMB 2.7
>>>
Simulation stopped, PC: 20043601 (BSBW 2004367B)
sim> show version
MicroVAX 3900 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                Asynchronous I/O support
                Asynchronous Clock support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 5.4.0
                Simulator Compiled as C arch: x86 (Release Build) on Dec 29 2016 at 12:20:39
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.3
                No RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 1ms
                OS: CYGWIN_NT-10.0-WOW trillian 2.6.1(0.305/5/3) 2016-12-16 11:50 i686 Cygwin
        git commit id: 6ebeb345
sim> show clock
Minimum Host Sleep Time:       1 ms (1000Hz)
Host Clock Resolution:         1 ms
Execution Rate:                781,800 instructions/sec
Calibrated Timer:              CLK
Calibration:                   Always

MicroVAX 3900 clock device is CLK
Calibrated Timer 0:
  Running at:                100 Hz
  Tick Size:                 10 msecs
  Ticks in current second:   38
  Seconds Running:           22 (22 seconds)
  Calibration Opportunities: 22
  Instruction Time:          16666931
  Real Time:                 1211198711
  Virtual Time:              1211198709
  Next Interval:             998
  Base Tick Delay:           7,834
  Initial Insts Per Tick:    5,000
  Current Insts Per Tick:    7,818
  Initializations:           3
  Total Ticks:               2,238
  Tick Time:                 22.37 seconds
  Initialize Base Time:      12:28:13.829
  Tick Start Time:           12:28:14.151
  Wall Clock Time Now:       12:28:59.939
sim> 

To send this reply, I tried it directly on my PC's keyboard/display and it doesn't fail (I tried it about 10 times).

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: 6ebeb345
sim> load -r ka655.bin
sim> att nvr vaxnvram.bin
NVR: buffering file in memory
sim> b cpu


KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Tests completed.
>>>

This is starting to smell like some strange timing interaction between SIMH and Windows 10 RDP!  I wonder if you're able to confirm the same symptoms?  I regularly use Remote Desktop from my Mac or iPad when the weather it hot (like it is today - around 40 deg C outside) in the cool on my living room sofa.

I can also reproduce the problem using the Microsoft Visual Studio Express 2013 for Windows Desktop (Version 12.0.40629.00 Update 5) compiler - which I think is similar to your development environment. When I use RDP in it fails, direct console it's OK.

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: 6ebeb345
sim> cd ..\..\inifiles
sim> load -r ka655.bin
sim> att nvr vaxnvram.bin
NVR: buffering file in memory
sim> b cpu

[c
KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..

?53 2 09 FF 00 0000

P1=00000002  P2=00000028  P3=80000052  P4=00D40077  P5=00000001
P6=FFFFFFFF  P7=00000000  P8=00000000  P9=00000000 P10=20051CE0
r0=00000009  r1=20140110  r2=CB37E55A  r3=00030069  r4=CB37E564
r5=2004E8F9  r6=00018678  r7=000186C8  r8=0001864E ERF=80000000
30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Normal operation not possible.

>>>show version
KA655-B V5.3, VMB 2.7
>>>show\wohs^U
>>>
Simulation stopped, PC: 2004361B (BEQL 20043601)
sim> show version
MicroVAX 3900 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                Asynchronous Clock support
                FrontPanel API Version 2
        Host Platform:
                Compiler: Microsoft Visual C++ 18.00.40629.00
                Simulator Compiled as C arch: x86 (Debug Build) on Dec 29 2016 at 12:54:44
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.5
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 30ms
                OS: Microsoft Windows [Version 10.0.14393]
                Architecture: x86 on AMD64, Processors: 8
                Processor Id: Intel64 Family 6 Model 30 Stepping 5, GenuineIntel, Level: 6, Revision: 1e05
        git commit id: 6ebeb345
sim>

Tony

**Comment by markpizz** [comment]
Hi Tony,

Thanks for the hint about RDP somehow making the problem more reproducible.  I can't actually explain why that might happen, but I was more easily able to reproduce it in an RDP session.

I actually was able to force the problem to be demonstrated and to capture the needed debug information with the following ini file:

    set debug -rpn tmr.dbg
    set int-clock debug=time;queue;calib
    set clk debug
    set sysd debug=todr;int;schd;regr;regw
    set remote telnet=12347
    load -r ka655.bin
    set quiet
    ; Stop execution when reaching test 26 (beyond all interval timer tests)
    expect -p "26.."
    expect "?53" noexpect "26.."; echo ; show clock ; return
    :boot_cpu
    boot cpu
    ; reached test 26, reset debug file and restart
    set debug -rpn tmr.dbg
    goto boot_cpu

In any case, the problem was purely timing related and would occur when a clock calibration (once per second) happened to occur during the TOY test which runs the clock for some 120ms (possibly repeatedly).  If the clock calibration observed a significantly different instruction execution rate then what had been previously observed, the value returned when reading the interval timer's interval remaining value would be wrong and if the difference was beyond the allowed tolerance in the TOY test, then the error would be reported.

All of the VAX model interval timers have now been simplified to use the usec timing capabilities which now exist in the simh framework and they can now avoid direct instruction rate to wall clock time computations.

You may want to try things with the above ini script before you pick up the latest code to convince yourself 1) you can reproduce it and 2) it has been fixed.

- Mark

**Comment by agn453** [comment]
Hi Mark,,

There is still a problem - this time I am getting ?52 errors (programmable timer). 

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: d456bac8
sim> cd ../../inifiles
sim> !type test.ini
set debug -rpn tmr.dbg
set int-clock debug=time;queue;calib
set clk debug
set sysd debug=todr;int;schd;regr;regw
set remote telnet=12347
load -r ka655.bin
set quiet
; Stop execution when reaching test 26 (beyond all interval timer tests)
expect -p "26.."
expect "?53" noexpect "26.."; echo ; show clock ; return
:boot_cpu
boot cpu
; reached test 26, reset debug file and restart
;;set debug -rpn tmr.dbg
;;goto boot_cpu
sim> do test.ini
Debug output to "tmr.dbg"
   Debug messages contain current PC value
   Debug messages display time of day as hh:mm:ss.msec relative to the start of debugging
Listening on port 12347


KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..

?52 2 10 FF 00 0000

P1=00000000  P2=0000000A  P3=00000000  P4=0000000A  P5=00000078
P6=FFFFFFFF  P7=00000000  P8=00000000  P9=00000000 P10=20051CE0
r0=000003FC  r1=2014010C  r2=20140110  r3=00000000  r4=00000000
r5=000001FC  r6=FFFFFC03  r7=00000000  r8=20140100 ERF=80000000
32..

?52 2 10 FF 00 0001

P1=00000001  P2=0000000A  P3=00000000  P4=0000000C  P5=0000007C
P6=FFFFFFFF  P7=00000000  P8=00000000  P9=00000000 P10=20051CE0
r0=000003FC  r1=2014011C  r2=20140100  r3=00000000  r4=00000000
r5=000001FC  r6=FFFFFC03  r7=00000000  r8=20140110 ERF=80000000
31..30..29..28..27..26..sim> show clock
Minimum Host Sleep Time:       1 ms (1000Hz)
Host Clock Resolution:         1 ms
Execution Rate:                1,425,500 instructions/sec
Calibrated Timer:              CLK
Calibration:                   Always

MicroVAX 3900 clock device is CLK
Calibrated Timer 0:
  Running at:                100 Hz
  Tick Size:                 10 msecs
  Ticks in current second:   50
  Seconds Running:           2 (2 seconds)
  Calibration Opportunities: 2
  Instruction Time:          949819
  Real Time:                 1360979719
  Virtual Time:              1360980197
  Next Interval:             1,478
  Base Tick Delay:           9,645
  Initial Insts Per Tick:    5,000
  Current Insts Per Tick:    14,255
  Initializations:           3
  Ticks:                     250
  Tick Time:                 2.49 seconds
  Initialize Base Time:      07:54:35.950
  Tick Start Time:           07:54:36.269
  Wall Clock Time Now:       07:54:52.116
sim> show version
MicroVAX 3900 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                Asynchronous Clock support
                FrontPanel API Version 2
        Host Platform:
                Compiler: Microsoft Visual C++ 18.00.40629.00
                Simulator Compiled as C arch: x86 (Debug Build) on Dec 31 2016 at 07:19:40
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.5
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 1ms
                OS: Microsoft Windows [Version 10.0.14393]
                Architecture: x86 on AMD64, Processors: 8
                Processor Id: Intel64 Family 6 Model 30 Stepping 5, GenuineIntel, Level: 6, Revision: 1e05
        git commit id: d456bac8
sim>

This is under Visual Studio Express 2013 and connected via RDP.  If you want to look at it - I put the tmr.dbg file up on my Google drive for you to grab at https://drive.google.com/file/d/0B8ua4QU-3W8kbHg5X1d6NjB4ZDg/view?usp=sharing as it's too big for here.

If I try just the "load -r ka655.bin / boot cpu" commands on their own, I get the self test passing.  If I try to boot OpenVMS using the script I have for configuring SIMH and mounting disk volumes I get the ?52 error.

If there's any further information you need - just ask.  I'm afraid I don't have the expertise to debug this like you do!

Your help/time is much appreciated.

Tony

**Comment by markpizz** [comment]
Hmmm...  This is crazy!!  I've got the script I provided running for 5 + hours in an RDP session without failure.

Please pick up the latest code and run the tests again using this script:

    set env LAST_ONE="28.."
    set debug -rpn tmr.dbg
    set console log=debug
    set int-clock debug=time;queue;calib
    set sysd debug=todr;int;schd;regr;regw
    set remote telnet=12347
    load -r ka655.bin
    set quiet
    expect -p %LAST_ONE% ; set debug -rpn tmr.dbg ; set console log=debug; goto boot
    expect "?53" noexpect %LAST_ONE%; echo ; show clock ; return
    expect "?52" noexpect %LAST_ONE%; echo ; show clock ; return
    :boot
    boot
    noexpect %LAST_ONE%
    show clock

The resulting debug file will be shorter and what I need to look at should be near the end of the file.

In your above output, test 52 failed twice (once for each of the interval timers).  Since they both fail, things are very consistent in your environment.  The first failure will be more than sufficient to try and understand what is happening especially if it can be uncluttered from the subsequent activities with the interval timers.

Thanks.

- Mark

**Comment by agn453** [comment]
Hi Mark,

With the latest code (compiled with Visual Studio Express 2013 under Windows 10 connected via RDP)

(I tried pasting this inside "Insert code" as I see you did some magic editing of my previous msgs)

`
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: 711f6167
sim> cd ..\..\inifiles
sim> !notepad test.ini
sim> !type test.ini
set env LAST_ONE="28.."
set debug -rpn tmr.dbg
set console log=debug
set int-clock debug=time;queue;calib
set sysd debug=todr;int;schd;regr;regw
set remote telnet=12347
load -r ka655.bin
set quiet
expect -p %LAST_ONE% ; set debug -rpn tmr.dbg ; set console log=debug; goto boot
expect "?53" noexpect %LAST_ONE%; echo ; show clock ; return
expect "?52" noexpect %LAST_ONE%; echo ; show clock ; return
:boot
boot
noexpect %LAST_ONE%
show clock
sim> do test.ini
Debug output to "tmr.dbg"
   Debug messages contain current PC value
   Debug messages display time of day as hh:mm:ss.msec relative to the start of debugging
Logging to file "tmr.dbg"
Listening on port 12347


KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..

?52
Minimum Host Sleep Time:       1 ms (1000Hz)
Host Clock Resolution:         1 ms
Execution Rate:                1,594,500 instructions/sec
Calibrated Timer:              CLK
Calibration:                   Always

MicroVAX 3900 clock device is CLK
Calibrated Timer 0:
  Running at:                100 Hz
  Tick Size:                 10 msecs
  Ticks in current second:   0
  Seconds Running:           2 (2 seconds)
  Calibration Opportunities: 2
  Instruction Time:          1024431
  Real Time:                 1383589210
  Virtual Time:              1383589739
  Next Interval:             1,500
  Base Tick Delay:           10,630
  Initial Insts Per Tick:    5,000
  Current Insts Per Tick:    15,945
  Initializations:           3
  Ticks:                     200
  Tick Time:                 1.99 seconds
  Initialize Base Time:      14:11:25.488
  Tick Start Time:           14:11:25.792
  Wall Clock Time Now:       14:11:26.983
sim>`

Attached is the debug file (renamed as .txt so the github web interface accepts it)

Tony

[tmr.dbg.txt](https://github.com/simh/simh/files/679432/tmr.dbg.txt)

**Comment by markpizz** [comment]
I'm not sure what the "insert code" actually does, but it didn't work.  When I do this I go back and forth between the "Write" and "Preview" tabs to see what the results will look like.  
Notice there is a "Styling with Markdown is supported" link just below the comment text edit/entry window.  That is there for reference and I use it as needed.  When I'm grabbing some output to paste into an issue comment I'll often drop it in an editor and quickly indent the whole thing by 4 spaces.  Then I paste it into an issue comment (preceded and followed by a blank line) and it ends up as a code block.  I just edited your most recent comment and inserted \`\`\` (that is triple back-ticks) before and after the code block which is another way to mark a code block.

Anyway, thanks for the debug output.  I'll let you know what I find later.

**Comment by agn453** [comment]
Resolved with latest changes to the bootrom timing.  Thanks
