### ISSUE TITLE
VAX clock drift

### ISSUE THREAD

**Issue by jguillaumes** [simh/simh#37]
At some (recent) point in time, the VAXen clock drifts away from the real time. I have observed it under x64 Linux and under ARM linux, in all the VAX simulators I run permanently (currently, vax3900, vax8600, vax730 and vax780). Unfortunately I am not able to tell which commit was the first showing the problem, but it is probably not older than a month. 

Update: the microvax3900 clock does not seem to drift.

**Comment by rdebath** [comment]
This compile option appears to work perfectly for Ultrix 4.5 on the vax/microvax3900. The severe clock drift (while idle) that I was having seems to have stopped completely.

There was, however, a rather worrying warning during the compile... 
```
sim_timer.c:898:3: warning: initialization from incompatible pointer type
   { MTAB_VDV,          MTAB_VDV, "ASYNC", "ASYNC",   &sim_timer_set_async, &sim_timer_show_async, NULL, "Enables/Displays Asynchronous Timer operation mode" },
   ^
sim_timer.c:898:3: warning: (near initialization for ‘sim_timer_mod[0].valid’)
sim_timer.c:898:3: warning: initialization from incompatible pointer type
sim_timer.c:898:3: warning: (near initialization for ‘sim_timer_mod[0].disp’)
sim_timer.c:899:3: warning: initialization from incompatible pointer type
   { MTAB_VDV,                 0,    NULL, "NOASYNC", &sim_timer_clr_async, NULL,                  NULL, "Disables Asynchronous Timer operation" },
   ^
sim_timer.c:899:3: warning: (near initialization for ‘sim_timer_mod[1].valid’)
```

I don't think I want to try to change the config option :smile: 

On a related note, the difference between the way that VMS and Ultrix treat the "TOY" clock seems to be that VMS stores local time in it and Ultrix stores UTC.

**Comment by markpizz** [comment]
@rdebath Please put your full name on your GitHub profile (no public email necessary).

Can you provide:
1) Details about the host platform you're seeing these compile warnings on?
2) Can you provide the FULL OUTPUT produced when you 'make vax'.

**Comment by rdebath** [comment]
Okay, full `make vax` is this
```
S2p4(robert)simh$ make vax CFLAGS_G=-DSIM_ASYNCH_CLOCKS
lib paths are: /lib/ /lib/i386-linux-gnu/ /lib/i386-linux-gnu/i686/cmov/ /lib/x86_64-linux-gnu/ /lib64/ /libx32/ /usr/X11R6/lib/ /usr/i486-linuxaout/lib/ /usr/lib/ /usr/lib/i386-linux-gnu/ /usr/lib/i386-linux-gnu/fakechroot/ /usr/lib/i386-linux-gnu/i586/ /usr/lib/i386-linux-gnu/i686/cmov/ /usr/lib/i386-linux-gnu/i686/sse2/ /usr/lib/i386-linux-gnu/libfakeroot/ /usr/lib/i386-linux-gnu/sse2/ /usr/lib/i486/ /usr/lib/i586/ /usr/lib/i686/cmov/ /usr/lib/i686/sse2/ /usr/lib/x86_64-linux-gnu/ /usr/lib64/ /usr/libx32/ /usr/local/lib/
include paths are: /usr/include
using libm: /usr/lib/i386-linux-gnu/libm.so
using librt: /usr/lib/i386-linux-gnu/librt.so
using libpthread: /usr/lib/i386-linux-gnu/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib/i386-linux-gnu/libpcreposix.so /usr/include/pcreposix.h
using libdl: /usr/lib/i386-linux-gnu/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib/i386-linux-gnu/libpng.so /usr/include/png.h
using mman: /usr/include/sys/mman.h
using libSDL: /usr/include/SDL/SDL.h
using libpcap: /usr/include/pcap.h
using libvdeplug: /usr/lib/libvdeplug.so /usr/include/libvdeplug.h
***
*** vax Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 4.9.2.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP NAT(SLiRP)
*** - video capabilities provided by libSDL (Simple Directmedia Layer).
***
*** git commit id is 3d7c4dc510b75e43fa6a4c8a169c90333e5e4d46.
***
mkdir -p BIN
gcc -std=gnu99 -U__STRICT_ANSI__ -DSIM_ASYNCH_CLOCKS -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=3d7c4dc510b75e43fa6a4c8a169c90333e5e4d46 -DSIM_COMPILER="GCC Version: 4.9.2" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_LIBPNG -DHAVE_GLOB -DHAVE_SHM_OPEN  sim_BuildROMs.c -o BIN/BuildROMs
BIN/BuildROMs
rm -f BIN/BuildROMs
mkdir -p BIN
gcc -std=gnu99 -U__STRICT_ANSI__ -DSIM_ASYNCH_CLOCKS -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=3d7c4dc510b75e43fa6a4c8a169c90333e5e4d46 -DSIM_COMPILER="GCC Version: 4.9.2" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_LIBPNG -DHAVE_GLOB -DHAVE_SHM_OPEN  VAX/vax_cpu.c VAX/vax_cpu1.c VAX/vax_fpa.c VAX/vax_io.c VAX/vax_cis.c VAX/vax_octa.c  VAX/vax_cmode.c VAX/vax_mmu.c VAX/vax_stddev.c VAX/vax_sysdev.c VAX/vax_sys.c  VAX/vax_syscm.c VAX/vax_syslist.c VAX/vax_vc.c VAX/vax_lk.c VAX/vax_vs.c VAX/vax_2681.c PDP11/pdp11_rl.c PDP11/pdp11_rq.c PDP11/pdp11_ts.c PDP11/pdp11_dz.c PDP11/pdp11_lp.c PDP11/pdp11_tq.c PDP11/pdp11_xq.c PDP11/pdp11_vh.c PDP11/pdp11_cr.c PDP11/pdp11_td.c PDP11/pdp11_io_lib.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -DVM_VAX -DUSE_INT64 -DUSE_ADDR64 -DUSE_SIM_VIDEO -I VAX -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_VDE_NETWORK -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -DHAVE_LIBSDL -DUSE_SIM_VIDEO `/usr/bin/sdl-config --cflags` `/usr/bin/sdl-config --libs` -o BIN/microvax3900 -lm -lrt -lpthread -lpcreposix -ldl -lpng -lvdeplug -Wl,-R,/usr/lib/ -L/usr/lib/
sim_timer.c:898:3: warning: initialization from incompatible pointer type
   { MTAB_VDV,          MTAB_VDV, "ASYNC", "ASYNC",   &sim_timer_set_async, &sim_timer_show_async, NULL, "Enables/Displays Asynchronous Timer operation mode" },
   ^
sim_timer.c:898:3: warning: (near initialization for ‘sim_timer_mod[0].valid’)
sim_timer.c:898:3: warning: initialization from incompatible pointer type
sim_timer.c:898:3: warning: (near initialization for ‘sim_timer_mod[0].disp’)
sim_timer.c:899:3: warning: initialization from incompatible pointer type
   { MTAB_VDV,                 0,    NULL, "NOASYNC", &sim_timer_clr_async, NULL,                  NULL, "Disables Asynchronous Timer operation" },
   ^
sim_timer.c:899:3: warning: (near initialization for ‘sim_timer_mod[1].valid’)
cp BIN/microvax3900 BIN/vax
S2p4(robert)simh$
```

This is the System Information generated for the distro package, I've already raised a bug with them complaining that it's version 3.8.
```
Debian Release: 8.4
  APT prefers stable-updates
  APT policy: (700, 'stable-updates'), (700, 'stable'), (690, 'oldstable'), (50, 'oldstable-updates')
Architecture: i386 (x86_64)
Foreign Architectures: amd64, armhf, powerpc, mips

Kernel: Linux 3.16.0-4-amd64 (SMP w/8 CPU cores)
Locale: LANG=en_GB.utf8, LC_CTYPE=en_GB.utf8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: sysvinit (via /sbin/init)

Versions of packages simh depends on:
ii  libc6       2.19-18+deb8u4
ii  libpcap0.8  1.6.2-2
```

**Comment by markpizz** [comment]
Thanks.   Still no full name though...  :-(

In any case, the SIM_ASYNCH_CLOCKS functionality isn't yet enabled by default since it has numerous operational issues.  A rework of that project is in progress but is still not ready for daylight.  When it is, the default build will include asynch clocks for all simulators that can leverage it (VAX and PDP11 and PDP10 are absolutely candidates).

As for the point/concern you raised about:

> On a related note, the difference between the way that VMS and Ultrix treat the "TOY" clock seems to be that VMS stores local time in it and Ultrix stores UTC.

You should try adding the following to your configuration file:

    sim> ATTACH CLK TOY_CLOCK_FILE

This won't affect clock drift, but it should address things like UTC or not.

If you still observe inconsistent/unreasonable TOY behavior, please create a separate issue.

Thanks.

- Mark

**Comment by rdebath** [comment]
Actually, the full name is in lots of commit messages, but I prefer it to be a bit harder than "on the front page" when web scrapers try to find it.

Re: `sim> ATTACH CLK TOY_CLOCK_FILE`

Yup found that, it works too, but I don't need to do it, if I do this instead:
`$ TZ=UTC simh ultrix-setup-file.ini`
The time Ultrix sees is exactly correct. 
Would you like me to put that into a "wishlist" issue?

I assume the warnings will be a 'WONTFIX' as the code is being replaced, so I won't make that a new issue. 

* Robert

**Comment by markpizz** [comment]
As for name... OK I guess.

As for:

> Yup found that, it works too, but I don't need to do it, if I do this instead:
> $ TZ=UTC simh ultrix-setup-file.ini
> The time Ultrix sees is exactly correct. 
> Would you like me to put that into a "wishlist" issue?

The real solution is the ATTACH mechanism which then has the clock behave as the real hardware did and have the TOY register behave as various OS code expects which is to store the programmed value and increment it every 10ms and overflow when it will naturally overflow.

As for:
> I assume the warnings will be a 'WONTFIX' as the code is being replaced, so I won't make that a new issue.

Yes, WONTFIX is the right answer, the current latent SIM_ASYNCH_CLOCKS code will be almost completely replaced.

**Comment by rdebath** [comment]
> increment it every 10ms and overflow when it will naturally overflow.

hmm; overflow ... right, turn it on before the end of April, then it knows it should increment the year.
Reset the clock back to zero and it gets all worried and confused.

_Okay_, I won't use the timezone then. 

Thankyou.
• • • Robert
