### ISSUE TITLE
PDP10: RIM format differs slightly between ITS and DEC

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#378]
The RIM format as generated by the RIM10 directive in ITS' MIDAS assembler is different from the DEC format:

- The checksum calculation is different; there is a ROT 1 before the addition.
- The very first block doesn't have a checksum.
- The payload block header word has the address in the right half; there's no subtraction with one.

Because of these differences, the `load -r` command will not accept an ITS RIM paper tape image.

The problem was first encoutered in PDP-10/its#440.

**Comment by larsbrinkhoff** [comment]
This input to MIDAS:

    TITLE RIM test
    RIM10
    NOSYMS
    LOC     707070
    FOO:    HALT
    END FOO

Results in this output:

    777761000000  -17,,0        ;First block header, PTR loader
    710601000060  CONO PTR,60
    541441000004  HRRI 11,4
    710741000010  CONSO PTR,10
    254000000003  JRST 3
    241011777776  ROT 0,-2(11)
    710472000010  DATAI PTR,@10(10)
    256011000010  XCT 10(11)
    256011000013  XCT 13(11)
    364440000000  SOJA 11,
    312000000017  CAME 17,
    270017000000  ADD (17)
    331740000000  SKIPL 17,
    254200000001  JRST 4,1
    253740000003  AOBJN 17,3
    254000000002  JRST 2
    000000707070  -1,,707070    ;Second block header, payload
    254200000000  HALT
    254177616161                ;Checksum
    254000707070  JRST 707070   ;Jump to start

**Comment by larsbrinkhoff** [comment]
CC @rcornwell

**Comment by archivisth** [comment]
Well, a KS10 doesn't have either a paper-tape reader or read-in mode, so the point is kind of moot. On a KA10, for example, read-in mode would read the first block (the loader) into locations 1-17 and then start executing it.

That said, it would be easy enough to add an ITS RIM loader, triggered by, say, -R with -I. However, I would be a lot more comfortable if there was formal documentation of the format somewhere, or if someone could analyze the program like this page (http://www.inwap.com/pdp10/rim10b.html), which explains the standard RIM loader. The ITS loader is basically the same, with the addition of the ROT 0,-2(11). However, the amount of rotation is controlled by AC11, which is a state variable. It can be 4, 3, or 2, depending on whether the program is looking for the IOWD, a data word, or the block checksum. It appears from the example that the pseudo IOWD is ROR 1 and the data words are unchanged.

**Comment by larsbrinkhoff** [comment]
Right, the issue was brought up when I tried to run an ITS program on @rcornwell's KA10 addition to SIMH.

**Comment by larsbrinkhoff** [comment]
From the MIDAS manual:

        The PDP-10 has a hardware readin mode which can read in one
    block of data.  Programs which can be loaded using this readin mode
    are said to use RIM10 format.  The format of this block is:
        -n,,loc-1       ; equiv to IOWD n,,loc
        <n data words>  ; the last data word is executed after readin.

    In MIDAS, "RIM10" causes the output binary to start with a RIM10-format
    SBLK loader provided by MIDAS.  The assembled code then follows in SBLK
    format.  Only data blocks and the final transfer block are output (no
    symbol blocks or anything else).  This is very similar to MACRO's "RIM10B"
    (see below).  The RIM10 loader code can be found at label LDR10 in MIDAS.

And SLKB format:

    Each simple block starts with an AOBJN-pointer to the range of
    core to be loaded; explicitly, -<number of words>,,<first word's
    address>.  It is inadvisable for any block to load more than 1K,
    or for a block's range to wrap around from -1 to 0.  After the
    range-word come as many words of data as the range-word specifies.
    The simple block is completed by the checksum word, which is
    computed as follows:

            (DO ((I 0 (1+ I)) (ACCUM 0))
                ((> I NUMBER-OF-DATA-WORDS) ACCUM)
                (SETQ ACCUM (+ (WORD I) (ROT ACCUM 1))))

**Comment by larsbrinkhoff** [comment]
I have implemented the SBLK checksum in a disassembler.  It works as documented.

**Comment by larsbrinkhoff** [comment]
From MIDAS source code:

    ;PDP10 SBLK LOADER
    ;FOLLOWING CODING ACTUAL WORDS TO BE OUTPUT
    ;BY ASSEMBLER, COMPILER, OR WHATEVER
    ;SHOULD BE EXECUTED BY PDP10 HARDWARE READIN FEATURE
    ;USES ONLY THE AC'S (BUT ALL OF THEM)

    LDR10:
            -17,,0          ;BLKI POINTER FOR READ SWITCH

    LDRC=0          ;CHECKSUM (OK, SO YOU'RE NOT ALLOWED TO LOAD
                    ;INTO IT DURING HARDWARE READIN, BUT WHO SAYS
                    ;YOUR PROGRAM CAN'T USE IT?)
    OFFSET -.+1             ;BEGIN LOADING INTO 1 AS PER HEADER
    LDRGO==.
            CONO PTR,60     ;START UP PTR (RESTART POINT)
    LDRRD==.
            HRRI LDRB,.+2   ;INITIALIZE INDEX
    LDRW==.
            CONSO PTR,10    ;WAIT FOR WORD TO BE AVAILABLE
            JRST .-1
            ROT LDRC,-LDRRD(LDRB)   ;BEFORE READING IN HEADER, ROTATE 2 BITS (THEN IGNORE)
                    ;BEFORE READING IN EACH DATA WORD, ROTATE 1 BIT (FOR UPDATING CHECKSUM)
                    ;BEFORE READING IN CHECKSUM, ROTATE NOT AT ALL (DON'T ROTATE CALCULATED CHECKSUM)
            DATAI PTR,@LDRT1-LDRRD(LDRB)    ;READ WORD INTO RIGHT PLACE
                    ;HEADER => READ INTO C
                    ;STORAGE WORD => READ INDEXED BY AOBJN POINTER IN A
                    ;CHECKSUM => READ INTO A FOR COMPARISON WITH C(C)
            XCT LDRT1-LDRRD(LDRB)   ;EXECUTE RELEVANT T1 ENTRY (MAYBE SKIPS)
            XCT LDRT2-LDRRD(LDRB)   ;EXECUTE RELEVANT T2 ENTRY (MAYBE JUMPS)
    LDRB==.
            SOJA .,         ;-RD(B) IS 2, 1, AND 0 FOR SUCCESSIVE ENCOUNTERS OF THIS INSTRUCTION
                            ;USED AS INDEX INTO TABLES, ETC.

                    ;TABLE 1
                    ;INDIRECTED THROUGH FOR DATAI
                    ;THEN EXECUTED TO SEE WHAT TO DO WITH READ IN WORD
                    ;ENTRIES EXECUTED IN REVERSE ORDER

    LDRT1==.
            CAME LDRC,LDRA  ;COMPARE CHECKSUM WITH CALCULATED, SKIP TO B IF THEY AGREE
            ADD LDRC,(LDRA) ;UPDATE CHECKSUM
            SKIPL LDRA,LDRC ;INITIALIZE HEADER AND SKIP UNLESS JUMP BLOCK

                    ;TABLE 2
                    ;EXECUTED IF CORRESPONDING ENTRY IN TABLE 1 DIDN'T SKIP WHEN EXECUTED

    LDRT2==.
            JRST 4,LDRGO    ;CHECKSUM ERROR
            AOBJN LDRA,LDRW ;UPDATE AOBJN POINTER AND GO BACK FOR NEXT STORAGE WORD IF NOT EXHAUSTED
    LDRA==.
            JRST LDRRD              ;WHEN INITIALLY LOADED IS JUMP BLOCK TO THIS LOADER
                    ;DURING LOADING USED TO HOLD HEADER (AOBJN POINTER), WHICH MAY BE LOADED JUMP BLOCK

    OFFSET 0
    ELDR10==.

**Comment by archivisth** [comment]
Lars wrote: 

```
Each simple block starts with an AOBJN-pointer to the range of
core to be loaded; explicitly, -<number of words>,,<first word's
address>.  It is inadvisable for any block to load more than 1K,
or for a block's range to wrap around from -1 to 0.  After the
range-word come as many words of data as the range-word specifies.
The simple block is completed by the checksum word, which is
computed as follows:

        (DO ((I 0 (1+ I)) (ACCUM 0))
            ((> I NUMBER-OF-DATA-WORDS) ACCUM)
            (SETQ ACCUM (+ (WORD I) (ROT ACCUM 1))))
```
For a one-word block, the example was 

`000000707070  -1,,707070    ;Second block header, payload`

Is this right? "-1" is not 0000000, it's 777777. I don't see how 000000 can work. The XCT'd SKIPL will not skip, and the loader will blow up.

**Comment by larsbrinkhoff** [comment]
Sorry, the `000000707070` is wrong.  It should be `777777707070`.

Yes, I can provide more examples.

**Comment by larsbrinkhoff** [comment]
Input:

    TITLE RIM test
    RIM10
    NOSYMS
    LOC     012345
    FOO:    0
            0
    END FOO

I suppose we can skip the identical RIM part?  The simple block looks like this:

    12345/   -2,,12345   
    12346/   0   
    12347/   0   
    12350/   -10,,51627   =777770051627  
    12351/   JRST 12345

**Comment by larsbrinkhoff** [comment]
Four words:

    TITLE RIM test
    RIM10
    NOSYMS
    LOC     030000
    FOO:    001000
            000300
            000010
            000007
    END FOO

File after RIM loader:

    30000/   -4,,30000   =777774030000   
    30001/   1000   
    30002/   300   
    30003/   10   
    30004/   7   
    30005/   -100,,611446   =777700611446   
    30006/   JRST 30000

**Comment by archivisth** [comment]
Okay, I've coded a revised RIM loader. Please post a couple of example paper tape files where I can download them. And if you can find a RIM10B format paper tape, I'd appreciate it...

**Comment by larsbrinkhoff** [comment]
I made paper tape images with the ITS MAGDMP and DSKDMP programs:  
https://github.com/larsbrinkhoff/ka10-simh/raw/its/magdmp.rim
https://github.com/larsbrinkhoff/ka10-simh/raw/its/BIN/dskdmp.rim

**Comment by archivisth** [comment]
Lars, if the changes fix your problem, please close this issue.

**Comment by larsbrinkhoff** [comment]
Yes, the files load just fine now.  Thanks!

**Comment by larsbrinkhoff** [comment]
I'm sorry, I only tested that `load` didn't flag any error loading the RIM file.  It now appears it silently fails.

**Comment by larsbrinkhoff** [comment]
The problem is that load_rim() doesn't properly sign extend ldrc when it converts the 36-bit left half to a 32-bit int.  So the comparison against 016 and 017 fails, but then it doesn't return SCPE_FMT because "return" is missing.

**Comment by archivisth** [comment]
Right. Fixed as follows:

```
ldrc = 01000000 - ((int32) (LRZ (data)));               /* get loader count */
if (ldrc == 016)                                        /* 16? RIM10B */
    its_rim = FALSE;
else if (ldrc == 017)                                   /* 17? ITS RIM */
    its_rim = TRUE;
else return SCPE_FMT;                                   /* unknown */
```

The first and last lines of this block are changed.
