### ISSUE TITLE
Testing DEUNA on PDP-10

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#382]
David Hittner @dthittner requested testing DEUNA with PDP-10.  I'm willing to help.

How is the DENUA control registers accessed from a KS10?  Memory mapped registers?  I/O instructions?

I'll be examining the pdp11_xu.c file, but some assistance might speed up the process.

**Comment by markpizz** [comment]
It is a Unibus device that has registers and does DMA.  There were rumors of some work done on a driver which was possibly never finished and certainly never released.  The manual for the DEUNA and DELUA are on Bitsavers.

The KS10 access would be the same as other Unibus DMA devices.

**Comment by R-Voorhorst** [comment]
Actually there is a more or less working Deuna implementation based on Tcp/Ip fabricated by J. Ericsson a lot of years ago. It worked with pinging but the Tcp/Ip stack was never finished. The Deuna of course had to work for this, so it could be a working base for further developments. 
I had it combined with Decnet on Dmr's on a KS10 with Tops10 7.04 and it worked without problems, although the Tcp/Ip stack is useless and development stopped there. Its name was (also) UNASER.

Then there are the Tops10 unsupported UNASER, UNAPRM drivers from Tim Litt, but they were never finished.  

There is also the fully operational KNISER parallel for the KL10 Tops10.

Merging these 3 sets could help a lot getting a proper UNASER,UNAPRM combo usable for Decnet, TCP/IP, even LAT or whatever one wants to do. 
Tops10 ETHSER is the generalized interface to KNISER and Tim's UNASER was meant to interface to ETHSER as well on Tops10.
For other network things your mileage may vary.

Remember though that as far as Tops10 is concerned there is little available virtual memory space for complex networking as these components seem to have a ferocious appetite for the scarce virtual memory space on a single section machine

**Comment by hrlzm** [comment]
Comment 1 of n:

My Tops-10 driver for the DEUNA/DELUA can be found in the file
  https://www.pdc.kth.se/~bygg/tops/unxser.mac
It works with my original emulation, and worked on real HW when I had a system up
and running.

(more to come)

--Johnny

**Comment by larsbrinkhoff** [comment]
*Make them laugh, make them cry, make them wait.*

**Comment by hrlzm** [comment]
Comment 2 of n:

Regarding the Tops-10 IP stack and device drivers:

My UNASER has been renamed to UNXSER, and can be used to talk directly to the hardware
on a KS-10 system.  If the system has a general ethernet (ETHSER et al) the driver is I4EINT,
which works for KL-based systems.  If/when the "other" UNASER gets done and talks to ETHSER,
UNXSER can be retired.

--Johnny

**Comment by hrlzm** [comment]
Comment 3 of n:

The DEUNA/DELUA has four 16-bit registers on the UNIBUS.  These can be used with the normal
RDIO/WRIO instructions (or the eqvivalent ITS ones).  If a user process has USRIO set it can talk
to the hardware, but since most of the communication with the card(s) is done via shared memory
doing it from a user process might not be that useful.

The shared memory contains the Port Command Block (pcb), the Unibus Data Block (udb) and
the transmit and receive buffer rings.  You start with putting the pcb address into CSR2 and 3,
and telling the HW to go from there.  Most commands go via the pcb.

--Johnny

**Comment by larsbrinkhoff** [comment]
Thank you.  Yes, I'm working in ITS.

With the USRIO bit on, I can write some commands to the DEUNA which SIMH seems to like, and I can trigger an interrupt.

**Comment by b4** [comment]
There is a SIMH mailing list post somewhere I believe where I had the DEUNA enabled and sending/receiving packets using @hrlzm 's stack.

**Comment by dthittner** [comment]
The network cards have memory mapped registers similar to the disk controllers. Host software initializes the registers to a known state, sets up host memory ring buffers for Ethernet packets, and then uses the memory-mapped registers to send commands to the Ethernet controller, and check status using other memory mapped registers. A read or write to the memory mapped registers wakes up the controller to do something.

A sample transmit (after initialization of registers and host ring buffers):

Write to transmit demand register
Controller scans current position in the transmit ring buffer to see if a packet needs to be transmitted. If the owner bit is set to controller, a packet is to be processed by the controller.
If a packet needs to be transmitted, packet is copied from host ring buffer to controller buffer, and transmitted. The host ring buffer status field is updated (including transferring ownership back to the host), and the memory mapped CSR register is updated.
The CSR status register is updated during the process of copying and transmission, and an interrupt can be generated at the end of packet transmission or after the last packet is transmitted, or both, if that behavior is set by the host software in the registers.
When an interrupt arrives, the host network software can scan the CSR to see what is attracting attention, or the host network software can poll the CSR at intervals to see what is going on.
When the last packet has been transmitted, the transmitter goes back to the off state.
If a packet is not waiting to be transmitted, the CSR status is updated, and the transmitter turns off until the transmit poll demand is pushed again.

A similar process occurs for receive – either the host software can write to the receive demand register to receive a single packet, or it can set the controller to continue to receive until the receive ring buffers are full. In either case, the CSR status register is updated, and an interrupt can be generated when each packet is received, and when the receive ring buffers are full (meaning that ownership of the next ring buffer is set to host). You can also poll for CSR status if you don’t want to implement interrupts, but it obviously lowers efficiency.

If the host and controller get into a state where they disagree where the “current” buffer is in the two rings, the controller will “lock up”, and the host will have to re-initialize the jammed ring buffer address registers to re-synchronize the buffers. This is also the process used to change the size/location of the host ring buffers on the fly.

Note that no PDP-10 OS (as far as I know) actually implemented Ethernet networking, which at the time was the DEUNA only. AFAIK, only the parallel interfaces (DMR, etc.) were used for point-to-point networking. There have been some people (Budne, FvK, Stark?) who have written various PDP-10 DEUNA drivers, but none has been integrated into OS’s, they have always been experimental add-ons. It would be a lot easier to debug if you had a real PDP-10 of the appropriate type with an actual DEUNA card in it to verify real behavior. Mark P may also have hacked the SIMH parallel network interface to transmit/receive over the host’s Ethernet controller to simulate point-to-point networking (DECnet Phases I/II/III) over the SIMH host’s Ethernet connection.

The DEUNA/DELUA works correctly under PDP-11 and VAX software, and has been debugged on VAX OpenVMS, VAXClusters, PDP-11 RSTS/E, and PDP-11 RSX-11/M+.

The original DEUNA/DELUA/DEQNA/DELQA manuals on BitSavers (noted in the pdp11_xu  and pdp11_xq comments) have a good description of the host ring buffers and their use. Most of the simulated and real networking performance problems occur when the simulated host doesn’t set up adequate sized ring buffers to deal with the real networking rate, and the simulated host has to sew together multiple short ring buffer entries to transmit or receive a single Ethernet packet, or if the simulated controller has to split/repackage Ethernet packets to accommodate small ring buffer entries.

Dave

**Comment by dthittner** [comment]
I should have also mentioned that the existing XU and XQ devices have good built-in debugging facilities to debug packets, ring buffer entries, and controller registers. :-)

SET XU DEBUG=ETH;TRACE;REG;WARN;PACKET;DATA

Dave

From: Hittner, David T [US] (MS)
Sent: Monday, February 20, 2017 6:18 PM
To: 'simh/simh'; simh/simh
Cc: Mention
Subject: RE: EXT :[simh/simh] Testing DEUNA on PDP-10 (#382)

The network cards have memory mapped registers similar to the disk controllers. Host software initializes the registers to a known state, sets up host memory ring buffers for Ethernet packets, and then uses the memory-mapped registers to send commands to the Ethernet controller, and check status using other memory mapped registers. A read or write to the memory mapped registers wakes up the controller to do something.

A sample transmit (after initialization of registers and host ring buffers):

Write to transmit demand register
Controller scans current position in the transmit ring buffer to see if a packet needs to be transmitted. If the owner bit is set to controller, a packet is to be processed by the controller.
If a packet needs to be transmitted, packet is copied from host ring buffer to controller buffer, and transmitted. The host ring buffer status field is updated (including transferring ownership back to the host), and the memory mapped CSR register is updated.
The CSR status register is updated during the process of copying and transmission, and an interrupt can be generated at the end of packet transmission or after the last packet is transmitted, or both, if that behavior is set by the host software in the registers.
When an interrupt arrives, the host network software can scan the CSR to see what is attracting attention, or the host network software can poll the CSR at intervals to see what is going on.
When the last packet has been transmitted, the transmitter goes back to the off state.
If a packet is not waiting to be transmitted, the CSR status is updated, and the transmitter turns off until the transmit poll demand is pushed again.

A similar process occurs for receive – either the host software can write to the receive demand register to receive a single packet, or it can set the controller to continue to receive until the receive ring buffers are full. In either case, the CSR status register is updated, and an interrupt can be generated when each packet is received, and when the receive ring buffers are full (meaning that ownership of the next ring buffer is set to host). You can also poll for CSR status if you don’t want to implement interrupts, but it obviously lowers efficiency.

If the host and controller get into a state where they disagree where the “current” buffer is in the two rings, the controller will “lock up”, and the host will have to re-initialize the jammed ring buffer address registers to re-synchronize the buffers. This is also the process used to change the size/location of the host ring buffers on the fly.

Note that no PDP-10 OS (as far as I know) actually implemented Ethernet networking, which at the time was the DEUNA only. AFAIK, only the parallel interfaces (DMR, etc.) were used for point-to-point networking. There have been some people (Budne, FvK, Stark?) who have written various PDP-10 DEUNA drivers, but none has been integrated into OS’s, they have always been experimental add-ons. It would be a lot easier to debug if you had a real PDP-10 of the appropriate type with an actual DEUNA card in it to verify real behavior. Mark P may also have hacked the SIMH parallel network interface to transmit/receive over the host’s Ethernet controller to simulate point-to-point networking (DECnet Phases I/II/III) over the SIMH host’s Ethernet connection.

The DEUNA/DELUA works correctly under PDP-11 and VAX software, and has been debugged on VAX OpenVMS, VAXClusters, PDP-11 RSTS/E, and PDP-11 RSX-11/M+.

The original DEUNA/DELUA/DEQNA/DELQA manuals on BitSavers (noted in the pdp11_xu  and pdp11_xq comments) have a good description of the host ring buffers and their use. Most of the simulated and real networking performance problems occur when the simulated host doesn’t set up adequate sized ring buffers to deal with the real networking rate, and the simulated host has to sew together multiple short ring buffer entries to transmit or receive a single Ethernet packet, or if the simulated controller has to split/repackage Ethernet packets to accommodate small ring buffer entries.

Dave

**Comment by larsbrinkhoff** [comment]
@dthittner 
Thank you.  Since my last comment, I have made some small progress writing a user mode ITS tool to prod the DEUNA.  I also added an interrupt handler stub to the ITS monitor.

I'm nowhere near handling actual Ethernet frames, but so far, everything seems to work as expected.

**Comment by wfjm** [comment]
I'v opened #405 on some sections in the DEUNA code which I consider questionable. Be great if this could be addressed in the same testing effort.   Walter

**Comment by larsbrinkhoff** [comment]
@wfjm My primary interest is to enable ITS networking with SIMH.  I will do some light testing, but that's in support of adding DEUNA code to the ITS monitor.

If someone wants to take my tool and extend it to cover more test cases, that's fine.  It's an opportunity to do some fun ITS hacking!

**Comment by larsbrinkhoff** [comment]
@atsampson has a work in progress to add DEUNA support to ITS.  I gather it's doing packet I/O, so I'd say that confirms DEUNA works on the KS10 simulator.
