### ISSUE TITLE
[Feature] Attaching serial port to a PTY

### ISSUE THREAD

**Issue by darkstar** [simh/simh#384]
- #### Context
I would like to be able to connect the emulated machine's serial ports to a PTY, to have it communicate with another emulated machine via a simple socat buffer.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
````
sim> show version
MicroVAX 3900 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                Asynchronous Clock support
                FrontPanel API Version 2
        Host Platform:
                Compiler: GCC 5.4.0 20160609
                Simulator Compiled as C arch: x64 (Release Build) on Jan 27 2017 at 23:43:18
                Memory Access: Little Endian
                Memory Pointer Size: 64 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.4
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 1ms
                OS: Linux kubuntu.lab.au.local 4.9.0-rc8-darkstar #15 SMP Tue Dec 20 14:04:14 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
        git commit id: 7ac92a0e
````

- #### how you built the simulator or that you're using prebuilt binaries
````
darkstar@kubuntu:/usr/src/simh$ make all
lib paths are: /lib/ /lib/i386-linux-gnu/ /lib/x86_64-linux-gnu/ /lib32/ /libx32/ /usr/lib/ /usr/lib/i386-linux-gnu/ /usr/lib/i386-linux-gnu/mesa/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/ /usr/lib/x86_64-linux-gnu/mesa-egl/ /usr/lib/x86_64-linux-gnu/mesa/ /usr/lib32/ /usr/libx32/
include paths are: /usr/include
using libm: /usr/lib/i386-linux-gnu/libm.so
using librt: /usr/lib/i386-linux-gnu/librt.so
using libpthread: /usr/lib/i386-linux-gnu/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib/x86_64-linux-gnu/libpcreposix.so /usr/include/pcreposix.h
using libdl: /usr/lib/i386-linux-gnu/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib/i386-linux-gnu/libpng.so /usr/include/png.h
using mman: /usr/include/sys/mman.h
using libSDL2: /usr/include/SDL2/SDL.h
using libpcap: /usr/include/pcap.h
using libvdeplug: /usr/lib/libvdeplug.so /usr/include/libvdeplug.h
***
*** all Simulators being built with:
*** - compiler optimizations and no debugging support. GCC Version: 5.4.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
***
*** git commit id is 7ac92a0e84313c9ddb80dca2a4ed0e75f74996fd.
***
font paths are: /usr/share/fonts/ /usr/lib/jvm/
font names are: DejaVuSans.ttf LucidaSansRegular.ttf FreeSans.ttf AppleGothic.ttf tahoma.ttf
...
````

- #### the simulator configuration file (or commands) which were used when the problem occurred.
First, run SOCAT and let it create a PTY with two fixed-name softlinks:
````
darkstar@kubuntu:/tmp$ sudo socat -d -d pty,raw,echo=0,link=/tmp/A pty,raw,echo=0,link=/tmp/B
[sudo] password for darkstar:
2017/01/28 00:08:27 socat[641] N PTY is /dev/pts/2
2017/01/28 00:08:27 socat[641] N PTY is /dev/pts/3
2017/01/28 00:08:27 socat[641] N starting data transfer loop with FDs [5,5] and [7,7]
````

Check the created links:
````
darkstar@kubuntu:/usr/src/simh$ ls -l /tmp/[AB]
lrwxrwxrwx 1 root root 10 Jan  28 00:08 /tmp/A -> /dev/pts/2
lrwxrwxrwx 1 root root 10 Jan  28 00:08 /tmp/B -> /dev/pts/3
````

Then, run SimH and try to attach a DZ line to the PTY:
````
darkstar@vmAUmd1-kubuntu:/usr/src/simh$ BIN/vax

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: 7ac92a0e
sim> show serial
Serial devices:
  no serial devices are available
sim> attach dz line=1,connect=/tmp/A
Invalid destination: /tmp/A
````

- #### the expected behavior and the actual behavior
I would expect the simulator to attach the simulated serial line to the PTY

The actual result is an error message (see above)

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem
none needed

**Comment by markpizz** [comment]
What you're proposing here seems to be a solution to a problem which I'm not 100% sure you've actually stated.

If you are merely saying that you'd like to have the simulated serial ports of two independent simh simulators connected to each other (as if two physical serial ports on real systems were connected via a null modem cable), then that capability is already built in to every serial port on all simulators:

     Simulator 1:
     sim> attach dz line=3,4321,connect=localhost:1234
     
     Simulator 2:
     sim> attach dz line=1,1234,connect=localhost:4321

Details about what is connected/configured is visible with the SHOW MUX command.

If this doesn't solve you problem, please describe the problem in more detail.

**Comment by darkstar** [comment]
Well, besides being able to connect 2 SimH instances directly, I also want to use expect(1) to talk to SimH's serial port (I'm trying to do some automation stuff with the emulated OS).
I think this is only possible if I have a named pipe/FIFO or PTY to connect to, and I figured that a PTY would be the better solution since it was made for (virtual) serial TTYs. I mean I could use telnet(1) to connect to the serial port and drive that through expect(1), but this seems to be one step more than what's actually needed.

Another point is that, in larger environments, having a simulator's serial port available with a name like "/foo/host1/dz_line4.fifo" makes life easier than having to remember the exact port number(s) where to send/receive data ;-)

**Comment by markpizz** [comment]
Fortunately, the built-in functionality in the SCP framework provides ways to automatically interact with a simulated OS.  The simh EXPECT and SEND commands can be used to script interactions with a simulated OS.

As for creative ways to name ports, you can also use environment variables in simh commands to pass around names:

    $ HOST1_DZ_LINE4_PORT=1234
    $ export HOST1_DZ_LINE4_PORT
    $ HOST2_DZ_LINE3_PORT=4321
    $ export HOST2_DZ_LINE3_PORT
    $ # Host 1
    $ BIN/vax
    sim> att dz line=4,%HOST1_DZ_LINE4_PORT%,connect=localhost:%HOST2_DZ_LINE3_PORT%
    $ # Host 2
    $ BIN/vax
    sim> att dz line=3,%HOST2_DZ_LINE3_PORT%,connect=localhost:%HOST1_DZ_LINE4_PORT%

**Comment by darkstar** [comment]
Ah! I didn't know about the environment variables. That will help. thanks.
