### ISSUE TITLE
PDP8: Clear MA, MB and IR at sim_instr() start?

### ISSUE THREAD

**Issue by tangentsoft** [simh/simh#386]
In going over the diffs between the PiDP-8/I version of `pdp8_cpu.c` and yours, I wonder if this line in our version should go upstream in some form:

    MA = MB = IR = 0;

This is outside the main `while()` loop in that function.

I think the current logic in your version is that these registers don't need to have explicit values until they're set for the first time when instructions first start executing.

Our current trunk version needs these registers to have definite values earlier because we start driving the LEDs before the first instruction executes, and we don't want a blip of garbage to appear there.

If that analysis is correct, I wonder if you would mind setting these register variables to 0 at their point of declaration so I can remove this difference between our versions? It seems these three registers are not held across continuations as with `saved_PC` and friends, so it doesn't matter if they go back to 0 when re-entering `sim_instr()`.

**Comment by archivisth** [comment]
The hardware doesn't work that way. Looking at the 8A schematics, for example, the clear line on the MA, MD (=MB), and IR quad flops are tied to ground. These registers are never initialized to 0. The 8/E appears to work the same way.

IIRC, when a classic -8 or -8/I powered up, the lights showed random values until a program was run or you started entering the RIM loader via the front panel switches.

In any case, the entry into sim_instr() would be the wrong place to clear these registers, if they were cleared at all. If you are single stepping, or continuing from a halt or breakpoint, you wouldn't want these values to be arbitrarily reset to 0.

If you want these registers initialized, it should be in the panel startup code, not in the simulator.

**Comment by tangentsoft** [comment]
> when a classic -8 or -8/I powered up, the lights showed random values

Surely that is due at least in part to the persistent nature of core memory?

One of the to-do items I have for the PiDP-8/I software is to persist memory to a file when you use one of the "nice" methods of stopping or restarting the simulator. (As opposed to just killing the program, or Ctrl-E quit.)

> or continuing from a halt

Well, there's one clear difference: at the moment, the PiDP-8/I simulator doesn't exit `sim_instr()` on HLT, because we have no way to get back in via the front panel CONT switch. That will change if we can get our project ported to the SIMH front panel API.

> If you want these registers initialized, it should be in the panel startup code, not in the simulator.

Okay, closing this issue.
