### ISSUE TITLE
Asynch I/O Problem on armv5tel system

### ISSUE THREAD

**Issue by Flupsy** [simh/simh#393]
- #### Context
An OpenVMS image, which boots successfully in 3.9, fails in 4.0-beta.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
MicroVAX 3900 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                Asynchronous Clock support
                FrontPanel API Version 4
        Host Platform:
                Compiler: GCC 4.9.2
                Simulator Compiled as C arch: ARM (Release Build) on Feb  7 2017 at 12:20:26
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: No Video Support
                RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 1ms
                OS: Linux little 3.16.0-4-kirkwood #1 Debian 3.16.39-1 (2016-12-30) armv5tel GNU/Linux
        git commit id: f46c048b
```
- #### how you built the simulator or that you're using prebuilt binaries

```
ian@little:~/simh/simh$ make vax
lib paths are: /lib/ /lib/arm-linux-gnueabi/ /usr/lib/ /usr/lib/arm-linux-gnueabi/ /usr/lib/arm-linux-gnueabi/libfa
keroot/
include paths are: /usr/include
using libm: /usr/lib/arm-linux-gnueabi/libm.so
using librt: /usr/lib/arm-linux-gnueabi/librt.so
using libpthread: /usr/lib/arm-linux-gnueabi/libpthread.so /usr/include/pthread.h
using regex: /usr/include/regex.h
using libdl: /usr/lib/arm-linux-gnueabi/libdl.so /usr/include/dlfcn.h
*** Info ***
*** Info *** The simulator you are building could provide more
*** Info *** functionality if video support were available on your system.
*** Info *** Install the development components of libSDL or libSDL2
*** Info *** packaged for your operating system distribution for
*** Info *** your Linux system:
*** Info ***        $ sudo apt-get install libsdl2-dev
*** Info ***    or
*** Info ***        $ sudo apt-get install libsdl-dev
*** Info ***
using libpcap: /usr/include/pcap.h
using libvdeplug: /usr/lib/libvdeplug.so /usr/include/libvdeplug.h
***
*** vax Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 4.9.2.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP NAT(SLiRP)
***
*** git commit id is f46c048bb696216c36bdefd6d7d146320c4136dd.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=f46c048bb696216c36bdefd6d7d146320c4136dd -DSIM_COMPILER="GCC Version: 4.9.2" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_REGEX_H -DHAVE_DLOPEN=so -DHAVE_GLOB  sim_BuildROMs.c -o BIN/BuildROMs
BIN/BuildROMs
rm -f BIN/BuildROMs
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=f46c048bb696216c36bdefd6d7d146320c4136dd -DSIM_COMPILER="GCC Version: 4.9.2" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_REGEX_H -DHAVE_DLOPEN=so -DHAVE_GLOB  VAX/vax_cpu.c VAX/vax_cpu1.c VAX/vax_fpa.c VAX/vax_io.c VAX/vax_cis.c VAX/vax_octa.c  VAX/vax_cmode.c VAX/vax_mmu.c VAX/vax_stddev.c VAX/vax_sysdev.c VAX/vax_sys.c  VAX/vax_syscm.c VAX/vax_syslist.c VAX/vax_vc.c VAX/vax_lk.c VAX/vax_vs.c VAX/vax_2681.c PDP11/pdp11_rl.c PDP11/pdp11_rq.c PDP11/pdp11_ts.c PDP11/pdp11_dz.c PDP11/pdp11_lp.c PDP11/pdp11_tq.c PDP11/pdp11_xq.c PDP11/pdp11_vh.c PDP11/pdp11_cr.c PDP11/pdp11_td.c PDP11/pdp11_io_lib.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -DVM_VAX -DUSE_INT64 -DUSE_ADDR64 -DUSE_SIM_VIDEO -I VAX -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_VDE_NETWORK -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c   -o BIN/microvax3900 -lm -lrt -lpthread -ldl -lvdeplug -Wl,-R,/usr/lib/ -L/usr/lib/
cp BIN/microvax3900 BIN/vax
```

- #### the simulator configuration file (or commands) which were used when the problem occurred.

```
;
; Load CPU microcode
load -r /home/ian/simh/simh/VAX/ka655x.bin
;
; Attach non-volatile RAM to a file
attach nvr /home/ian/simh/vax/nvram.bin
;
; This virtual machine has 64M memory
set cpu 64m
set cpu idle
;
; Define disk drive types. RA92 is largest-supported VAX drive.
set rq0 ra92
set rq1 ra92
set rq2 ra92
set rq3 cdrom
;
; Attach defined drives to local files
attach rq0 /home/ian/simh/vax/d0.dsk
attach rq1 /home/ian/simh/vax/d1.dsk
attach rq2 /home/ian/simh/vax/d2.dsk
;
; Attach the CD-ROM to its file (read-only)
attach -r rq3 /home/ian/simh/vax/openvms.iso
;
; Disable unused devices. It's also possible to disable individual devices,
; using a construction like "set rq2 disable" if desired.
;
set rl disable
set ts disable
;
; Attach Ethernet to a network interface -- commented out for now
;set xq mac=08-00-2B-AA-BB-CC
;attach xq nat:
;
; Now start the emulator
boot cpu
```
- #### the expected behavior and the actual behavior

```
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: f46c048b
NVR: buffering file in memory
RQ0: '/home/ian/simh/vax/d0.dsk' Contains ODS2 File system
RQ0: Volume Name: OVMSVAXSYS   Format: DECFILE11B   Sectors In Volume: 2940951
RQ1: '/home/ian/simh/vax/d1.dsk' Contains ODS2 File system
RQ1: Volume Name: DATA1        Format: DECFILE11B   Sectors In Volume: 2940951
RQ2: '/home/ian/simh/vax/d2.dsk' Contains ODS2 File system
RQ2: Volume Name: DATA2        Format: DECFILE11B   Sectors In Volume: 2940951
RQ3: unit is read only
RQ3: '/home/ian/simh/vax/openvms.iso' Contains ODS2 File system
RQ3: Volume Name: VAXVMS073    Format: DECFILE11B   Sectors In Volume: 1331200


KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Tests completed.
>>>b
(BOOT/R5:0 DUA0



  2..
-DUA0
?4B CTRLERR, DUA0
HALT instruction, PC: 00000C1A (MOVL (R11),SP)
```

There is a long (multi-minute) pause at `-DUA0`.  Under 3.9 (built locally) and 3.8 (stock Debian), that step is passed with no delay.

**Comment by markpizz** [comment]
Hi Ian,

This is strange indeed.  

Do you get the same result if you comment out the 'load -r ...' line?  I suspect you will, but I don't know exactly what ROM image you're running with.  All versions *should* work.  

What happens when you:

```
        >>>B DUA3
```

After that we need to go under the covers to see what is happening.  This is a case of 'it works for me', so I'm going to need info gathered on your system.  Fortunately this happens early in the system operation so the info gathered should be relatively small.

Please add the following lines to your configuration file right before the 'boot cpu' line:

```
set rq debug
set debug -t vax-boot.dbg
```

Run with this configuration and after the boot fails, stop simulation with ^E, exit the simulator.

If the vax-boot.dbg file is relatively small (less than a couple of hundred lines), then please include it in your issue text, otherwise attach the file to your issue comments (via drag & drop).

Thanks.

- Mark

**Comment by Flupsy** [comment]
Hi Mark, and thanks for the quick response!

I tried commenting out the `load -r` line but as you suspected the results were the same.  I left the line commented out for the rest of my tests.

Booting from DUA3 gives similar results:

```
>>>b dua3
(BOOT/R5:0 DUA3



  2..
-DUA3
```
except that the simulator hangs forever at this point (or at least for longer than I'm willing to stare at it :)).

I ran a normal boot with debugging on and I've attached the output.
[vax-boot.txt](https://github.com/simh/simh/files/760360/vax-boot.txt)

Cheers
- Ian

**Comment by markpizz** [comment]
The debug output suggests we've got a problem completing an asynchronous I/O operation.  This could be a pthreads problem or an issue with the code that implements a lock free linked list insert.  To confirm that this thinking is on the right track, please put this in your config file before the boot command:
```
SET NOASYNC
```
and try running again and report your results.

If that works, it would, at best, be a workaround.  I want to actually solve the problem so please explain exactly what platform are you on?  The SHOW VERSION output suggests it is some sort of ARM...

**Comment by Flupsy** [comment]
Well it fails quicker! :)  This is what I get with 'SET NOASYNC':

```
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: f46c048b
NVR: buffering file in memory
RQ0: '/home/ian/simh/vax/d0.dsk' Contains ODS2 File system
RQ0: Volume Name: OVMSVAXSYS   Format: DECFILE11B   Sectors In Volume: 2940951
RQ1: '/home/ian/simh/vax/d1.dsk' Contains ODS2 File system
RQ1: Volume Name: DATA1        Format: DECFILE11B   Sectors In Volume: 2940951
RQ2: '/home/ian/simh/vax/d2.dsk' Contains ODS2 File system
RQ2: Volume Name: DATA2        Format: DECFILE11B   Sectors In Volume: 2940951
RQ3: unit is read only
RQ3: '/home/ian/simh/vax/openvms.iso' Contains ODS2 File system
RQ3: Volume Name: VAXVMS073    Format: DECFILE11B   Sectors In Volume: 1331200
Asynchronous I/O disabled
Loading boot code from internal ka655x.bin


KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Tests completed.
>>>b
(BOOT/R5:0 DUA0



  2..
?4F SCBINT, DUA0
HALT instruction, PC: 00000C1A (MOVL (R11),SP)
```

No pause this time.

I tried adding the debug lines too, and then it booted successfully!  Heisenberg would be proud.

Platform data:

```
ian@little:~/simh/vax$ arch
armv5tel
ian@little:~/simh/vax$ uname -a
Linux little 3.16.0-4-kirkwood #1 Debian 3.16.39-1 (2016-12-30) armv5tel GNU/Linux
ian@little:~/simh/vax$ cd
ian@little:~$ arch
armv5tel
ian@little:~$ uname -a
Linux little 3.16.0-4-kirkwood #1 Debian 3.16.39-1 (2016-12-30) armv5tel GNU/Linux
ian@little:~$ cat /proc/cpuinfo
processor       : 0
model name      : Feroceon 88FR131 rev 1 (v5l)
BogoMIPS        : 1185.79
Features        : swp half thumb fastmult edsp
CPU implementer : 0x56
CPU architecture: 5TE
CPU variant     : 0x2
CPU part        : 0x131
CPU revision    : 1

Hardware        : Marvell Kirkwood (Flattened Device Tree)
Revision        : 0000
Serial          : 0000000000000000
```

**Comment by Flupsy** [comment]
I spoke too soon.  With debug enabled, I get different results each time.  The first attempt gave me:

```
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: f46c048b
NVR: buffering file in memory
RQ0: '/home/ian/simh/vax/d0.dsk' Contains ODS2 File system
RQ0: Volume Name: OVMSVAXSYS   Format: DECFILE11B   Sectors In Volume: 2940951
RQ1: '/home/ian/simh/vax/d1.dsk' Contains ODS2 File system
RQ1: Volume Name: DATA1        Format: DECFILE11B   Sectors In Volume: 2940951
RQ2: '/home/ian/simh/vax/d2.dsk' Contains ODS2 File system
RQ2: Volume Name: DATA2        Format: DECFILE11B   Sectors In Volume: 2940951
RQ3: unit is read only
RQ3: '/home/ian/simh/vax/openvms.iso' Contains ODS2 File system
RQ3: Volume Name: VAXVMS073    Format: DECFILE11B   Sectors In Volume: 1331200
Debug output to "/dev/null"
   Debug messages display time of day as hh:mm:ss.msec
Asynchronous I/O disabled
Loading boot code from internal ka655x.bin


KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Tests completed.
>>>b
(BOOT/R5:0 DUA0



  2..
-DUA0
  1..0..


%SYSBOOT-I-SYSBOOT Mapping the SYSDUMP.DMP on the System Disk
%SYSBOOT-I-SYSBOOT SYSDUMP.DMP on System Disk successfully mapped
%SYSBOOT-I-SYSBOOT Mapping PAGEFILE.SYS on the System Disk
%SYSBOOT-I-SYSBOOT SAVEDUMP parameter not set to protect the PAGEFILE.SYS
   OpenVMS (TM) VAX Version V7.3     Major version id = 1 Minor version id = 0

Exception in interrupt or exception, PC: 83C848FC (MOVL #D,(R0)+)
```

Then I tried again and got this:

```
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: f46c048b
NVR: buffering file in memory
RQ0: '/home/ian/simh/vax/d0.dsk' Contains ODS2 File system
RQ0: Volume Name: OVMSVAXSYS   Format: DECFILE11B   Sectors In Volume: 2940951
RQ1: '/home/ian/simh/vax/d1.dsk' Contains ODS2 File system
RQ1: Volume Name: DATA1        Format: DECFILE11B   Sectors In Volume: 2940951
RQ2: '/home/ian/simh/vax/d2.dsk' Contains ODS2 File system
RQ2: Volume Name: DATA2        Format: DECFILE11B   Sectors In Volume: 2940951
RQ3: unit is read only
RQ3: '/home/ian/simh/vax/openvms.iso' Contains ODS2 File system
RQ3: Volume Name: VAXVMS073    Format: DECFILE11B   Sectors In Volume: 1331200
Debug output to "vax-boot.dbg"
   Debug messages display time of day as hh:mm:ss.msec
Asynchronous I/O disabled
Loading boot code from internal ka655x.bin


KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Tests completed.
>>>b
(BOOT/R5:0 DUA0



  2..
-DUA0
  1..0..


%SYSBOOT-F-Unexpected Exception
HALT instruction, PC: 0000A7A4 (HALT)
```

I've attached the debug file from the last attempt.
[vax-boot.txt](https://github.com/simh/simh/files/760934/vax-boot.txt)

**Comment by markpizz** [comment]
Thanks for the debug output.

Back to the question about the platform, I asked it since what we're seeing doesn't seem like it can be solved "debugging at a distance"...

**Comment by Flupsy** [comment]
Is there anything else I can give you beyond the platform information in my comment above?

**Comment by markpizz** [comment]
Where I can get my hands on one so I can track this down.  Borrow would be preferable, but buy would be OK if costs were in the Raspberry Pi price range.

**Comment by Flupsy** [comment]
Ah gotcha.  It's a 'Sheevaplug' -- here's the UK reseller's website where I got mine (a while ago). https://www.newit.co.uk/shop/All-SheevaPlug

I'd lend you mine but it's also my home router :)

**Comment by markpizz** [comment]
You're trying to run a VAX simulator on the device which is simultaneously your network router? Wow!

Meanwhile, I've looked through the debug data and it shows the disk working completely as expected.  You can disable the debug since the original problem I described (pthread and/or lock free list insertion) is now being avoided.  The error you're seeing seems out of the blue.  

Without me being able to reproduce the problem(s), all I can offer is suggestions to work around them.

In any case, please answer:
1) When using prior versions of sim on this 'system', did you have working ethernet networking from the simulated system?
2) Please pickup the latest code from github and build the vax simulator with:
```
    $ make vax NOPTHREADS=1
```

This will build a simulator which completely avoids using threads, but I suspect we haven't approached the other failure at all.

I'm suspecting that one or more compiler/runtime issues are factors here.  

Will you please also try building a debug simulator (unoptimized):
```
    $ make vax DEBUG=1
```
OR
```
    $ make vax DEBUG=1 NOPTHREADS=1
```

Run both the no thread one and the debug one and see what happens.

-----------
I think I've found one of your devices on eBay for $30 delivered.  I'll need 
to have it in hand to actually address the problems.

**Comment by Flupsy** [comment]
Sorry for the delay in getting back to you.  Yeah, I know it's a strange thing to do :)

I'll try what you've asked and let you know how I get on.

**Comment by Flupsy** [comment]
Interesting.  (these tests are all with commit d112c22f)

- First I built a 'clean' binary (i.e. no `make` options) just in case something changed.  That gives me a clean set of system tests, but a hang at `-DUA0` when I try to boot VMS.

- If I build a `NOPTHREADS=1` version, I reliably get

```
KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..

?53 2 09 FF 00 0000

P1=00000002  P2=00000028  P3=80012D9B  P4=00D40077  P5=00000001
P6=FFFFFFFF  P7=00000000  P8=00000000  P9=20051BD0 P10=20051CE0
r0=00000004  r1=20140110  r2=266AF0B2  r3=00030745  r4=266AF0BC
r5=2004E8F9  r6=00018678  r7=000186C8  r8=00005905 ERF=82000180
30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Normal operation not possible.
```

but if I continue to boot VMS, I get a clean boot every time (I tried three times).

The `DEBUG=1` version gives me the same as the clean binary (only a bit slower).

`DEBUG=1 NOPTHREADS=1` is the most successful, giving clean system tests and a clean boot.

**Comment by Flupsy** [comment]
Incidentally, this may be expected behaviour but with the `NOPTHREADS=1` versions the simulators hang at `attach xq nat:`.  I had this line commented out for all my tests above.

**Comment by Flupsy** [comment]
I just tried building with clang instead of gcc and got the same result, so I guess that's one thing that can be ruled out.

**Comment by markpizz** [comment]
1) The system test problem is something else I'm already working on and unrelated to the boot hang problem.
2) That you get a clean boot with NOPTHREADS=1 is completely expected since, from the beginning I've suspected the lock free link list insertion functionality.
3) Clang vs GCC are most likely producing the the same code when __sync_val_compare_and_swap() is invoked and I'm thinking that is somehow related to the problem.
4) "attach xq nat:" with threading disabled was never tried and it wouldn't be surprising that it doesn't work.    Part of the answer to that may be that NAT may not be supported if pthreads aren't available.

Due to slow UPS delivery it may be another week before the eBay purchase gets here and I can test directly.

**Comment by Flupsy** [comment]
Thanks so much for your prompt attention.  If there's anything else I can do to help in the meantime just let me know.

**Comment by markpizz** [comment]
Hi Ian,

I received the SheevaPlug and somewhat quickly managed to make it unbootable as I fumbled around trying to connect extra storage so I could install the necessary toolchain to actually reproduce the problem.  Fixing the unbootable situation needed me getting some serial port drivers which were hard to come by since the support for this relatively old platform isn't great.  Today I finally got the pieces needed to access the console port and I've reinstalled Debian from scratch on a SD card which is big enough to be useful.  I have now reproduced the problem here.

On to exploring and addressing the details...

I'll let you know when this is solved.

- Mark

**Comment by Flupsy** [comment]
Fab!  Thanks so much for your attention and dedication.

**Comment by Flupsy** [comment]
That commit fixes the problem for me.  I still see the occasional failure to boot but it's maybe one time in ten.

**Comment by markpizz** [comment]
If the failure to boot is the ?53... error during the boot count down, that's another issue already which is tracked elsewhere.  If it is another problem, please describe it in detail? Otherwise feel free to close this issue.

**Comment by Flupsy** [comment]
To be honest I haven't seen it in the last couple of days, and now I'm questioning whether I've ever seen it with the latest build.  I'll close this just now, and open a fresh ticket if I see more problems.

Thanks so much for all your help!
