### ISSUE TITLE
builds under OpenVMS VAX has problems

### ISSUE THREAD

**Issue by agn453** [simh/simh#394]
I fired up my VAXstation 3100 M48 to charge up the TOY clock battery and decided to give it some "useful work" to compile the latest AltairZ80 SIMH simulator.  However, I soon discovered it now uses the uint64 data type so the compilation aborted with many diagnostic messages like -

```
                uint64 mask;
        ........^
%CC-E-NOLONGLONG, In this declaration, 64-bit integral types are not supported
 on this platform.
                At line number 5071 in USER_DISK:[LOCAL.SOURCES.SIMH-MASTER.ALTAIRZ80]M68KOPAC.C;1.
```
This is under OpenVMS VAX V7.3 using Compaq C V6.4-005.

This is probably not too important to fix - since I can get by on other platforms.  Perhaps the DESCRIP.MMS file needs a note (along similar lines to the PDP-10, Eclipse, IBM 7094...) to include AltairZ80 in the build restrictions.   This is a shame though, since my first use for SIMH was on this very VAX to emulate my Z80 S-100 homebrew system using SIMH V2.10-1

Tony

**Comment by markpizz** [comment]
Thanks for testing the build on the VAX/VMS environment.  Clearly that hasn't been done for a LONG time.

Please check to see if the attached (descrip.mms) [descrip.zip](https://github.com/simh/simh/files/762105/descrip.zip) is well behaved.

While, you are there can you test the build of the rest of the simulators and, if needed, make changes or report back here with details.

-------
If you really want to emulate your Z80 S100 system on your VAX, you could still run the older simh AltairZ80 simulator.  :-)

**Comment by agn453** [comment]
Thanks Mark.

I found another problem building under VSI OpenVMS 8.4-2 on ALPHA using `mmk /macro=(noasynch=1) vax
` following a successful build of the PDP11 target -

```
..
$!
$! Building The SYS$DISK:[.BIN]PDP11-AXP-NOASYNCH.EXE Simulator.
$!
$ CC/DECC/PREF=ALL/DEBUG/OPT=(LEV=5)/ARCH=HOST  /NEST=PRIMARY/NAME=(AS_IS,SHORT)/INCL=(SYS$DISK:[],SYS$DISK:[.PDP11],SYS$DISK:[-.PCA
P-VMS.PCAP-VCI]) /DEF=("_LARGEFILE","VM_PDP11=1","USE_NETWORK=1","HAVE_PCAP_NETWORK=1")/OBJ=SYS$DISK:[.BIN.VMS.LIB.BLD-AXP-NOASYNCH]
 SCP.C
$ LINK /NODEBUG/NOTRACEBACK/EXE=SYS$DISK:[.BIN]PDP11-AXP-NOASYNCH.EXE  SYS$DISK:[.BIN.VMS.LIB.BLD-AXP-NOASYNCH]SCP.OBJ,SYS$DISK:[.BI
N.VMS.LIB]PDP11L1-AXP-NOASYNCH.OLB/LIBRARY,SYS$DISK:[.BIN.VMS.LIB]PDP11L2-AXP-NOASYNCH.OLB/LIBRARY,SYS$DISK:[.BIN.VMS.LIB]SIMH-AXP-N
OASYNCH.OLB/LIBRARY,SYS$DISK:[.BIN.VMS.LIB]PCAP-AXP-NOASYNCH.OLB/LIB/SYSEXE
$ DELETE/NOLOG/NOCONFIRM SYS$DISK:[.BIN.VMS.LIB.BLD-AXP-NOASYNCH]*.OBJ;*
$! PDP11 done
$ mmk /macro=(noasynch=1) pdp11
$! BuildROMs done
$! PDP11 done
$ mmk /macro=(noasynch=1) vax
$! BuildROMs done
$!
$! Building The SYS$DISK:[.BIN.VMS.LIB]SIMH64-AXP-NOASYNCH.OLB Library.
$!
$ CC/DECC/PREF=ALL/DEBUG/OPT=(LEV=5)/ARCH=HOST  /NEST=PRIMARY/NAME=(AS_IS,SHORT)/DEF=("_LARGEFILE","USE_NETWORK=1","HAVE_PCAP_NETWOR
K=1","USE_ADDR64=1","USE_INT64=1")/INCL=(SYS$DISK:[-.PCAP-VMS.PCAP-VCI])  /OBJ=SYS$DISK:[.BIN.VMS.LIB.BLD-AXP-NOASYNCH] SYS$DISK:[]S
IM_CONSOLE.C,SYS$DISK:[]SIM_SOCK.C,SYS$DISK:[]SIM_TMXR.C,SYS$DISK:[]SIM_ETHER.C,SYS$DISK:[]SIM_TAPE.C,SYS$DISK:[]SIM_FIO.C,SYS$DISK:
[]SIM_TIMER.C,SYS$DISK:[]SIM_DISK.C,SYS$DISK:[]SIM_SERIAL.C,SYS$DISK:[]SIM_VIDEO.C
$ IF (F$SEARCH("SYS$DISK:[.BIN.VMS.LIB]SIMH64-AXP-NOASYNCH.OLB").EQS."") THEN  LIBRARY/CREATE SYS$DISK:[.BIN.VMS.LIB]SIMH64-AXP-NOAS
YNCH.OLB
$ LIBRARY/REPLACE SYS$DISK:[.BIN.VMS.LIB]SIMH64-AXP-NOASYNCH.OLB SYS$DISK:[.BIN.VMS.LIB.BLD-AXP-NOASYNCH]*.OBJ
$ DELETE/NOLOG/NOCONFIRM SYS$DISK:[.BIN.VMS.LIB.BLD-AXP-NOASYNCH]*.OBJ;*
$!
$! Building The SYS$DISK:[.BIN.VMS.LIB]VAXL1-AXP-NOASYNCH.OLB Library.
$!
$ RUN/NODEBUG SYS$DISK:[.BIN]BuildROMs-AXP-NOASYNCH.EXE
%DCL-W-ACTIMAGE, error activating image SYS$DISK:[.BIN]BUILDROMS-AXP-NOASYNCH.EXE

```

Somehow the ARCH macro is missing the NOASYNCH part when looking for the BuildROMs target (it built BUILDROMS-AXP.EXE for the PDP11 target).  I kludged around this with the following change to DESCRIP.MMS -

```
ALPHA $ diff descrip.mms ;-1
************
File USER_DISK:[LOCAL.SOURCES.SIMH-MASTER]DESCRIP.MMS;2
  306   .ifdef NOASYNCH
  307     @ IF (("$(BUILDING_ROMS)".EQS."").AND.(F$SEARCH("$(BIN_DIR)BuildROMs-$(ARCH)-NOASYNCH.EXE").EQS."")) THEN $(MMS) BUILDROMS
  308   .else
  309     @ IF (("$(BUILDING_ROMS)".EQS."").AND.(F$SEARCH("$(BIN_DIR)BuildROMs-$(ARCH).EXE").EQS."")) THEN $(MMS) BUILDROMS/MACRO=(B
  310   .endif
  311   
******
File USER_DISK:[LOCAL.SOURCES.SIMH-MASTER]DESCRIP.MMS;1
  306     @ IF (("$(BUILDING_ROMS)".EQS."").AND.(F$SEARCH("$(BIN_DIR)BuildROMs-$(ARCH).EXE").EQS."")) THEN $(MMS) BUILDROMS/MACRO=(B
  307   
  308   
************

Number of difference sections found: 1
Number of difference records found: 5
```
I probably should not be using NOASYNCH anymore - but this might bite anyone still using a OpenVMS Alpha V7.3-2.

I'll fire up a batch job to build all the targets on the VAX and report back any further failures - however this will take many hours on my VAXstation!  For comparison I'll also do it under SIMH VAX :)

Tony

**Comment by agn453** [comment]
Mark,

The scp.c file has a `long long` in it now :( - so maybe nothing will build now on VAX.

Checking the progress of my batch job shows `mmk altair` failing with -

```
..
$!
$! Building The SYS$DISK:[.BIN]ALTAIR-VAX.EXE Simulator.
$!
$ CC/DECC/DEBUG/OPTIMIZE  /NEST=PRIMARY/NAME=(AS_IS,SHORT)/INCL=(SYS$DISK:[],SYS
$DISK:[.ALTAIR])/DEF=("__VAX")/OBJ=SYS$DISK:[.BIN.VMS.LIB.BLD-VAX] SCP.C
                sprintf(tim_t, "%" LL_FMT "d.%03d ", (long long)(time_now.tv_sec
), (int)(time_now.tv_nsec/1000000));
        ..............................................^
%CC-E-NOLONGLONG, In this statement, 64-bit integral types are not supported on
 this platform.
                At line number 10520 in DISK$VOGON_USER:[LOCAL.SOURCES.SIMH-MAST
ER]SCP.C;1.

        #endif
%VCG-I-NOBJECT, No object file produced.
                At line number 11877 in DISK$VOGON_USER:[LOCAL.SOURCES.SIMH-MAST
ER]SCP.C;1.

%VCG-I-SUMMARY, Completed with 1 error(s), 0 warning(s), and
                1 informational messages.
                At line number 11877 in DISK$VOGON_USER:[LOCAL.SOURCES.SIMH-MAST
ER]SCP.C;1.
```

Something that your recent timer changes has introduced?

Tony

**Comment by markpizz** [comment]
Well, there is nothing ASYNCH or NOASYNC specific about the BUILDROMS program.  It is a build facilitating tool and not a target simulator.  It constructs and/or verifies the contents of the include files that are used for the built-in ROMs that some simulators use.  It reads the binary ROM image files and confirms that what they contain is what currently is in each ROMs respective include file.  

I'm looking at what's going on with that now.  On other platforms, all the simulators have buildroms as a dependency and when buildroms is built it is also run to 'do its job' and if it finds errors the build fails and someone has to figure out why.  It didn't start out that way (it was originally only used by the VAX simulators), so I think in the descrip.mms I explicitly included running it as part of the build steps for the simulators that need it.  I think I revisited that and tried to make it run first without regard to what simulator is being built.

I just committed a change to allow scp.c to be built on the VAX host which should then allow the remaining non 64bit simulators to build as well.

**Comment by agn453** [comment]
Thanks - I'll fetch the recent commit later on today and give it a whirl.

My kludge was just to pass the NOASYNC flag into the build of BuildROMs so that the image filename that was built matched the rules for a target with the BuildROMS-$(ARCH).EXE prerequisite (e.g. BUILDROMS-AXP-NOASYNC.EXE if I was building VAX with noasynch=1)

Tony

**Comment by markpizz** [comment]
Tony,

I've got an OpenVMS VAX build going right now my continuously running simh VAX.  I've fixed several other problems already beyond what you originally observed.  I'll let you know when it is finished.

- Mark

**Comment by agn453** [comment]
Thanks Mark.

I was busy doing other things the past few hours - but I'm back home now if you need me to verify any changes.

Tony

**Comment by markpizz** [comment]
I've got the VAX build of the non 64bit simulators working cleanly.

There is one compiler message which occurs once for each VAX simulator that I can't fix :-)

```
%VCG-I-NOOPTIMIZATION, Complex control flow caused optimization
                to be suppressed for procedure or function. "__"

%VCG-I-SUMMARY, Completed with 0 error(s), 0 warning(s), and
                1 informational messages.
                At line number 3734 in DUA0:[SIMH-BUILD.VAX]VAX_CPU.C;1.

```

**Comment by agn453** [comment]
Mark,

I suspect we've hit a compiler limitation with Compaq C under OpenVMS VAX.  Nothing shows up using "`HELP CC Messages NOOPTIMIZATION`" - so back in the day I'd resort to posting a message on comp.os.vms and wait for someone like John Reagan (the VAX/Alpha/Itanium compiler guru) to respond.  In the back of my mind I remember reading somewhere that the VAX Code Generator backend (VCG) had to be disabled to compile other common C code on VAX (perhaps in OpenVMS itself).

Tony

**Comment by markpizz** [comment]
Tony,

The message was merely "Informational", not a "Warning" or "Error", and after running a full compile of all available simulators INSIDE a VAX simulator, I'm not excited to attempt to run a VAX simulator there, so if the optimizer didn't do a great job, it won't bother me since I'll never run that simulator.

I think we can close this.  If you want to run another build from scratch on your system first, please do and then close this issue.

Thanks.

- Mark
