### ISSUE TITLE
PDP-8: Cannot set DF from SCP

### ISSUE THREAD

**Issue by tangentsoft** [simh/simh#398]
There seems to be a bug in the SCP which prevents calling a register "DF", as the current PDP-8 simulator does:

    $ pdp8

    PDP-8 simulator V4.0-0 Beta        git commit id: d980bcd7
    sim> d df 0
    Too few arguments

Since I observed that I *can* set IF, which is defined near-identically, I decided to try renaming DF to DFX in the register definition, and now it works.

Is the SCP `DEPOSIT` command parser doing something odd with "DF"?

**Comment by archivisth** [comment]
The command is considered ambiguous, because DF is also the name of a disk (DF32/DF08), and specifying a device/unit takes precedence, e.g.:

sim> d df wc 0

Not sure what the best way is to fix this. The implicit rule is that a register must not have the same name as a device/unit.

**Comment by tangentsoft** [comment]
It seems wrong to rename DF, since that's it's proper name. It's also not optional, as a DF32 is, so it seems to me that in a fight between the two, DF-the-register should win.

Simply disabling the DF32 device doesn't seem to help:

    sim> set df disabled
    sim> d df 0
    Invalid argument

> Not sure what the best way is to fix this.

In other areas of command handling, SIMH insists that you be specific. Since "DF" does already specifically refer to the DF register, whereas "DF" refers to the disk device only as an abbreviation, I'm not seeing why renaming the device would be wrong.

Do the above errors not also prove that no one can be relying on existing behavior of "DF" commands? That is, isn't the simulator going to reject them anyway?

How often do we have a situation where only an emulated DF32 will do? If we change how that needs to be referred to in boot scripts, how many people would we affect? I'm guessing the vast majority of PDP-8 simulator users who set up a hard drive do so with the RK05 device, simply because it's biggest, and there is no cost difference between them under SIMH.

**Comment by markpizz** [comment]
The ambiguous name problem can come up in several situations.  The more common case is when different devices have REGisters that have the same name.  A typical ambiguous case is the TIME REGister.

The solution to the ambiguous name problem is to use the fully qualified name format which says "which device" and then "which REGister":

```
sim> deposit CPU DF 4
```

The frontpanel API lets you specify the fully qualified form or the default global search form.

**Comment by archivisth** [comment]
Mark is correct, and that is the answer. (Thanks for remembering what I seem to have forgotten after 20+ years.) However, the behavior of d df 0 not working with DF disabled seems to be a V4 issue:

```
PDP-8 simulator V3.10-0
sim> d df 0
Too few arguments
sim> set df disabled
sim> d df 0
sim>
```
/Bob

**Comment by tangentsoft** [comment]
I'm still seeing this with [f07987b7]:

<pre>$ BIN/pdp8 

PDP-8 simulator V4.0-0 Beta        git commit id: f07987b7
sim> d df 0
Too few arguments
sim> d cpu df 0
Invalid argument
sim> set df disabled
sim> d df 0
Invalid argument
sim> d cpu df 0
Invalid argument
</pre>

I did a clean rebuild after my pull, and ensured there were no local diffs. (That's how I found the IBM1130 bug reported in #404.)

**Comment by tangentsoft** [comment]
(Ignore prior reply. I still had some local changes because `git reset`...doesn't. And `git revert` doesn't do what `revert` does in every other SCM. Grr.)

It looks like this change fixes the `set df disabled` problem, but doesn't fix the original problem I reported. Also, I don't get the new "Ambiguous register" message:

<pre>$ BIN/pdp8 

PDP-8 simulator V4.0-0 Beta        git commit id: f07987b7
sim> d cpu df 0
sim> d df 0
Too few arguments
sim> set df disabled
sim> d df 0
sim> </pre>

This is after a complete "make clean && make", which is how I found the IBM1130 problem.

(Normally I don't do `make clean`, as I feel that's only necessary in trees where the `make` dependencies are incomplete, as happens when you don't have an autodependency system. Feel free to [steal ours](https://tangentsoft.com/pidp8i/file/Makefile.in), which is based on code I stole, with credit given in the Makefile comment.

**Comment by markpizz** [comment]
> Also, I don't get the new "Ambiguous register" message:

Well, you don't actually have ambiguous registers defined.  You have a register name which collides with a device name.  The first token after the command (D) is DF which is first looked up as a device name.  If a legit device is found, then the next token is taken to be the register name and given this logic, the message is correct.  You haven't supplied enough tokens.  If the lookup of the first token isn't a legit device, then a global search commences looking for a register that matches.

The when the device name is present, the register lookup isn't tried unless the number of arguments is reasonable.  If I changed the order of that test, the best message which could be issued would be:
```
sim> d df 0
DF device does not have a register named '0'.
```
I'm not sure that this is much better than Too few arguments...

**Comment by tangentsoft** [comment]
That sounds like a fine improvement, in fact. The error should not beg the question, "*Why* too few arguments?" Your alternative explains that it thinks "DF" is a device name, which leads you to the solution.

**Comment by markpizz** [comment]
Well, I was wrong.  I can't really produce that message since, if the second argument is a device name (as in your case), a subsequent numeric argument is actually legal since you might be depositing into some part of the device's address space.  This is a legitimate operation. 
```
sim> D DF 0 0
Unit not attached
sim> E DF 0
Unit not attached
```
This additional confusing message gets to a messier rat hole than "Too few arguments".

That is all without considering that some simulators have default radix of 16.  This means that a value of DF could be a register name OR a hex value.

Please just use:
```
sim> D CPU DF 0
```
and press on.

**Comment by tangentsoft** [comment]
So renaming the DF device to DF32 is off the table, then?

If so, I think we'll merge this patch as-is, but disable the DF device, since as I argued above, uses of "DF" meaning the register are going to be vastly more common than uses of "DF" the device.

**Comment by markpizz** [comment]
I don't see the need to change the name.  All you need to do is use a fully qualified register name.

Where/how are you doing this that it causes problems?

**Comment by tangentsoft** [comment]
When I sit down at the keyboard and say "d df 0" and the SIMH manual says the DEPOSIT command can be used to set a register, then I expect DF to be set to 0.

Yes, yes, yes, the manual also says I can set a value in a device. But since I just booted that simulator up, and I have nothing attached to a "DF" device, why am I expected to understand that my perfectly sensible "d df 0" command is going to go to the *device* instead?

I'm not talking about programmatically-generated code here, which can be modified, compiled, checked in, and then forgotten. I'm talking about normal end users typing sensible commands at the simulator, which it is misunderstanding.

I am talking about the principle of least surprise.

**Comment by markpizz** [comment]
I'll be glad to enrich the documentation (and help) to be more clear about the arguments to the examine and deposit commands along with the convenience feature to perform a global search for register names across all devices.

If you essentially, always only care about examine and deposit referencing CPU REGisters, you could have a configuration file which does this:
```
PDP-8 simulator V4.0-0 Beta        git commit id: cbf90e7d
sim> e df
Too few arguments
sim> set env e=ex cpu
sim> set env d=dep cpu
sim> e df
DF:     0
sim> d df 3
sim> e df
DF:     3
sim>
```
and then for the rare case you might ever want to look at a device's registers you'd have to:
```
sim> ex rk rkda
RKDA:   0000
sim> 
```

**Comment by tangentsoft** [comment]
> you could have a configuration file which does this:

Actually, I think we're just going to disable the DF device by default. I fully expect that no PiDP-8/I users will complain.
