### ISSUE TITLE
Ambiguous REGister names produce "Invalid Argument" failure message

### ISSUE THREAD

**Issue by pkoning2** [simh/simh#402]
This is with the current SIMH, though it isn't all that new.

In the PDP11, if KE11 is enabled, the switch register ("SR") is not accessible.  Attempts to reference it produce "Invalid argument".

**Comment by markpizz** [comment]
simh (SCP) lets you use REGister names rather freely to avoid the extra typing involved in specifying fully qualified REGister names.  However, when REGister names are ambiguous (across the enabled devices in the system), you must type fully qualified REGister names when using the EXAMINE or DEPOSIT commands.

The "HELP dev REG" command will display scan the defined REGisters in the enabled devices and, if an ambiguity exists, display the fully qualified name form that must be used.

I'll look at enhancing the EXAMINE and DEPOSIT commands to provide a more useful error message other than "Invalid Argument" when these commands are presented with an ambiguous register name.

**Comment by pkoning2** [comment]
Part of the confusion is that I didn't know (and couldn't tell) that the switch register is part of the pseudo-device SYSTEM (rather than the more obvious CPU).

**Comment by markpizz** [comment]
I'll look at producing useful error messages that explain that detail (i.e. describe the ambiguities).

**Comment by markpizz** [comment]
How does this look?
```
PDP-11 simulator V4.0-0 Beta        git commit id: 7f2c7480
sim> set 11/70
Disabling XQ
sim> e sr
SR:     000000
sim> set ke enab
sim> e sr
Ambiguous register.  SR appears in devices SYSTEM and KE
sim>
```

**Comment by pkoning2** [comment]
Looks nice.  What would also be nice is something like "help register sr" that finds all the SR registers and list where, and the associated help string if there is one.

**Comment by markpizz** [comment]
The attempt to reference a register with an ambiguous name already identifies the devices which define the overlapping names.  An interested user can then type the (most often) two help commands himself.

**Comment by pkoning2** [comment]
Ok, that makes sense.
