### ISSUE TITLE
Wrap vid_version() call with #if defined(USE_SIM_VIDEO)

### ISSUE THREAD

**Issue by tangentsoft** [simh/simh#418]
The [call to vid_version()](https://github.com/simh/simh/blob/master/scp.c#L4601) within show_version() in scp.c depends on sim_video.h to be included, else you get a C99 warning about an implicitly-defined function and a separate one about the potential mismatch in the printf() type specifier. This line should be wrapped for builds that do not enable this option.

**Comment by markpizz** [comment]
I don't see the problem.  scp.c always includes sim_video.h without regard to any compiler defines precisely for this reason.  Are you using an unmodified scp.c?

**Comment by tangentsoft** [comment]
Yes, we modify scp.c, and now I see that one of those mods is to ifdef out the #include for sim_video.h as well, since we don't include that module in our PiDP-8/I build of the simulator. (Maybe someday, but today, we don't need it.)

**Comment by markpizz** [comment]
There is no need to ifdef out that include.  If USE_SIM_VIDEO isn't defined, then it merely declares the entry points.  You should also be compiling sim_video.c which will do nothing if USE_SIM_VIDEO isn't defined, but it will produce stub routines.

**Comment by tangentsoft** [comment]
We have plenty of incentive to reduce the number of modules we compile. On a Raspberry Pi 1, a full build of our software takes something like 11 minutes, and we're building only one simulator.

If you're unwilling to make this module purely optional upstream, we will add the ifdefs on our side.

**Comment by markpizz** [comment]
Avoiding extra files to build is useful when there is real work to compile a file.  I doubt that adding sim_video.c to the compile will affect the compile time by more than 2 seconds.  I just tested a compile of that file on a little sheevaplug box which I'm pretty sure is no faster than a Raspberry Pi 1.

Take a look at the bottom of that file (this is the only section compiled when USE_SIM_VIDEO isn't defined).  You've got a handful of return statements and 3 fprintf statements.

**Comment by tangentsoft** [comment]
We've removed these diffs, and are now building sim_video into our simulator with SIM_VIDEO left undefined, for now. We may later use it for things like a Spacewar! local X-Y display.
