### ISSUE TITLE
Unable to boot RT11 (RL11)

### ISSUE THREAD

**Issue by pdp11me** [simh/simh#424]
- #### Context

Unable to boot RT11 on SIMH v4.0 beta, I can boot RT11 with the same commands when running SIMH V3.9-0

RT11 disk downloaded here: http://simh.trailing-edge.com/kits/rtv53swre.tar.Z

Running SIMH under slackware 13.37 built from downloaded source

- #### the simulator configuration file (or commands) which were used when the problem occurred.

PDP-11 simulator V4.0-0 Beta        git commit id: b2cd329f
sim> set cpu 11/23+ 256k
sim> set tto 8b
sim>
sim> set rl enable
sim> set rl0 rl02
sim> attach rl0 rtv53_rl.dsk
sim>
sim> boot rl0

- #### the expected behavior and the actual behavior

HALT instruction, PC: 000002 (HALT)

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
This is a duplicate of #412

**Comment by markpizz** [comment]
@pdp11me Please put your whole name in your GitHub profile.

Thanks.

**Comment by pdp11me** [comment]
I just tested the new release and I can now boot RT11 on V4.0B  THanks

(Name updated in profile)

len
