### ISSUE TITLE
I1620: First typewriter screen wrap is wrong

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#439]
- #### Context

tto_col in i1620_tty.c is initialized to 0 at startup, but after break, SIMH moves the cursor, and tto_col loses sync.  I fixed it by setting it to -1 at the beginning of sim_instr().  (-1, because if 0 is used, the first line gets 79 chars instead of 80.)  I'm not saying that's the Right Thing, but it looks good here.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Well, the right observation to make is when the simulated console is separate from the interactions created while controlling the simulator.

This would be achieved by:
```
sim> SET TELNET nnn
```
Then using a telnet client on the local system telnet to localhost:nnn.  On windows I recommend PuTTY as a telnet client.  DO NOT use the Microsoft telnet client.  It is broken and doesn't follow the telnet protocol spec regarding binary mode telnet (which simh uses).

**Comment by DaveWise2** [comment]
(Note: "SET TELNET nnn" is not in the help, only SET CONSOLE TELNET=nnn.)

Here is what I get using PuTTY on telnet.  Initial setup is
```
sim> d 0 dnty 19800
sim> d 12 h
sim> go 0
```

So we're dumping 200 characters.
Result is

```
Connected to the IBM 1620 simulator CON-TELNET device

00000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000
```

Note the short first line, due to tto_col coming in 0, while the second and third lines begin with tto_col == 80 causing a wrap before the first character is output.  Subsequent "go 0" commands continue from the last printed column, since the output is not disrupted by the SIMH command prompt.

If you count columns, you will find 81 characters on the second line.  The above was captured by marking and copying using the mouse.  It does not match the visual appearance, which is an 80-character line, an 81-character line wrapped by PuTTY or Windows at 80 characters leaving a one-character runt on the third line which is then wrapped again by SIMH, and a 39-character fourth line.

Compare with local console output:
```
IBM 1620 simulator V4.0-0 Beta        git commit id: b5a5aec5
sim> d 0 dnty 19800
sim> d 12 h
sim> go 0
00000000000000000000000000000000000000000000000000000000000000000000000000000000

00000000000000000000000000000000000000000000000000000000000000000000000000000000
0
000000000000000000000000000000000000000
HALT instruction, PC: 24 (00)
sim> go 0
000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
0
00000000000000000000000000000000000000000000000000000000000000000000000000000
HALT instruction, PC: 24 (00)
sim>
```

Here, subsequent "go 0" commands produce various patterns because tto_col doesn't notice that SIMH has moved the cursor to display its prompt and take commands.  I see that setting tto_col in sim_instr is indeed the Wrong Thing when the console is remote.  But what is the Right Thing?

**Comment by DaveWise2** [comment]
If I initialize tto_col to TTO_COLMAX instead of 0, and compare >= instead of > , I get good output in PuTTY.  I still get a sequence of patterns on the local console, because the SIMH command prompt changes the cursor position without telling tto_col.  Are you inclined to just document it, or...  Is it easy to tell when the console is local?  Either way, I could add code to output \r followed by tto_col spaces, to reestablish the cursor position.  Where should it go?

**Comment by DaveWise2** [comment]
```
IBM 1620 simulator V4.0-0 Beta        git commit id: b5a5aec5
sim> set console telnet=23
Listening on port 23
sim> d 0 dnty 19800
sim> d 12 h
sim> go 0

HALT instruction, PC: 24 (00)
sim>
```
```
Connected to the IBM 1620 simulator CON-TELNET device

00000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000
```
Above I used the prebuilt binary.  The CON-TELNET data looks different on-screen.  There, line 1 is 80 chars, line 2 is 80 chars, line 3 is 1 char, and line 4 is 39 chars.  Lines 2 and 3 are one 81-char line emitted by SIMH, wrapped at 80 by PuTTY leaving a 1-char runt on line 3.
```
IBM 1620 simulator V4.0-0 Beta        git commit id: fb8a01da
sim> set console telnet=23
Listening on port 23
sim> d 0 dnty 19800
sim> d 12 h
sim> go 0

HALT instruction, PC: 24 (00)
sim>
```
```
Connected to the IBM 1620 simulator CON-TELNET device


00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000
```
Here I used my local build with mods.  The copied/pasted console output matches the screen.
1. Your sim_console.c
2. tto_write() compares tto_col >= TTO_COLMAX instead of tto_col > TTO_COLMAX
3. tty_reset() sets tto_col to TTO_COLMAX instead of 0

The only wart I see is the extra wrap after the console connect banner, due to tto_col before the first char.  The local console looks the same on the first "go 0", but it has a shortened first line on the second "go 0" because tto_col is still 40 from the first DNTY but SIMH has moved the cursor to column 0.  If I knew when the console was local, I could emit 'tto_col' spaces to get the cursor back out to where tto_write() expects it to be, but I'm not sure it's worth it provided the behavior is documented.

**Comment by markpizz** [comment]
There is absolutely no goal to get visuals right when the simh commands are intermixed with the natural device output.  Don't try to entangle the code to consider this.

The simulated system console should be right in the telnet session and the interactions controlling and/or influencing the simulator should happen elsewhere.  Elsewhere could be a windows command prompt (as you've got here) or a Front Panel application which provided something which simulated (with hardware or software) the additional physical controls the original system actually had.  Rather than the 'soft' terminal provided by the telnet session, the console could be connected to a serial port and a physical terminal of some sort could be connected...

As for:
> The only wart I see is the extra wrap after the console connect banner, due to tto_col before the first char. 

is the "extra wrap" you are referring to an initial blank line, or something else?

**Comment by DaveWise2** [comment]
Thanks for the policy clarification, Mark.  I won't lose a minute of sleep over column tracking in the local console.

Yes, it's an extra blank line between the connect banner and the start of output, caused by tto_col coming in as TTO_COLMAX which provokes a wrap right before the first printed char.  I think I can avoid it by initializing tto_col to -1 instead of TTO_COLMAX.  The first printing char will inc it to 0 and we're off to the races.

**Comment by markpizz** [comment]
I don't think the initialization of -1 will solve it.  Specifically I think you've correctly in setting tto_col to TTO_COLMAX in tty_reset.  Given that, the static initialization is irrelevant since all devices have their reset routine called when the simulator starts.

I'd forget the first blank line.  Consider the initial blank line in the telnet session as equivalent to positioning the paper in the terminal when you first feed it through.

**Comment by DaveWise2** [comment]
-1 does exactly what I hoped.  The first char incs it to 0 without extraneous wrap.

I like your imagery about positioning the paper, but virtually all programs start with a RCTY out of self-defense.

**Comment by markpizz** [comment]
I really don't know anything about this system, so RCTY is meaningless to me.  

Meanwhile setting tto_col to -1 and TTO_COLMAX probably equivalent.  Personally I like to keep with positive values for indexes.

**Comment by DaveWise2** [comment]
Sorry, RCTY is the instruction to do a CRLF on the console typewriter.

-1 is not equivalent to TTO_COLMAX.  When tto_col is preset to TTO_COLMAX, the first printing char causes a wrap.  When tto_col is preset to -1, it does not.  I feel the same as you about sign of index, but some loops simply require a -1 preset unless they are restructured, and sometimes that gets awkward.

**Comment by DaveWise2** [comment]
I am looking into a light restructure which treats tto_col and TTO_COLMAX as one-based, with tto_col representing the empty cell we are about to print on.

**Comment by DaveWise2** [comment]
Attached please find zip file* with i1620_tty.c modified to handle wrap and tab correctly.  tto_col is now one-based, going from 1 to 80 and representing the character cell at which we will next print.  tto_tabs array is unchanged, with zero-based access.  Tab set/show UI is unchanged.  (One-based.)

Or should I commit it and... do what with my repository?  Push it?  I don't know the protocol.  Newbie.

\* I had to force a .txt extension before the site would allow me to upload it.  It says it will accept .zip but it does not.

This implementation matches the behavior of the real 1620 Model I console typewriter.  After printing the last possible character in a line, the carriage stays resting against the right margin stop until the next tab or printing character, at which point it will return to the left margin (plus linefeed) before doing the char/tab.


[i1620_tty.zip.txt](https://github.com/simh/simh/files/977083/i1620_tty.zip.txt)

**Comment by markpizz** [comment]
Does the real hardware keyboard have a TAB key?  
Is a tab character one that a 1620 program could emit?

Contact me offline (mark@infocomm.com) to review workflow details for submitting code.

**Comment by DaveWise2** [comment]
The Model I's typewriter has a TAB key, and if you hit it the carriage moves but this does not feed back to the CPU.  The CPU can also frob the TAB key via solenoid, same as the other keys, but the only feedback is a hardware interlock to prevent the TBTY instruction from finishing until the carriage has hit the stop.  As far as 1620 software is concerned, it's a write-only function.

Yes, sort of.  TAB is not part of the 1620's character set, so it doesn't emit a character per se, but it can cause tabulation, by executing the TBTY instruction.  SIMH does not make this distinction, and I don't blame it.  :)

I'll contact you later; I have a burst of paying work to handle right now.

**Comment by archivisth** [comment]
I'll add Dave's changes to column record keeping to the revision of TTY.

**Comment by DaveWise2** [comment]
[i1620_tty.c.txt](https://github.com/simh/simh/files/1012785/i1620_tty.c.txt)
Thanks, Bob!

Here is my latest i1620_tty.c .  It contains wrap changes, plus part of my change for making TTY IO interruptible.  You will have no trouble teasing them apart.

**Comment by archivisth** [comment]
Change committed. This issue can be closed.

**Comment by DaveWise2** [comment]
Thanks, Bob, looks fine here.
