### ISSUE TITLE
Windows: Dismissing SIMH window crashes

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#443]
- #### Context

Running Windows 7/64.  If I kill SIMH by clicking the "dismiss" icon in the window corner, I get
```
Unhandled exception at 0x043874AC in I1620.exe: 0xC0000005: Access violation executing location 0x043874AC.
```
This occurs on all targets, not just I1620.  That's the April 24 prebuilt binaries.  It also occurs on a local I1620 build of today's commit, so it hasn't been fixed between April 24 and now.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

IBM 1620 simulator V4.0-0 Beta        git commit id: 6a180c3d
sim> show ver
IBM 1620 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 4
    Host Platform:
        Compiler: Microsoft Visual C++ 18.00.40629.00
        Simulator Compiled as C arch: x86 (Debug Build) on May  3 2017 at 13:50:40
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 6.1.7601]
        Architecture: x86 on AMD64, Processors: 36
        Processor Id: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel, Level: 6, Revision: 3f02
        git commit id: 6a180c3d
sim>

- #### how you built the simulator or that you're using prebuilt binaries

Both.

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
This does not happen for me.

Please provide exact steps to reproduce.  You pick the simulator and describe the input you enter before clicking on the "dismiss" icon.  This is the X in the upper right corner of the window, right?

**Comment by markpizz** [comment]
What version of Visual Studio are you using?

**Comment by markpizz** [comment]
By the way, the simh simulators are not Windows GUI apps, so they don't actually have a 'dismiss' icon in the upper right corner.  They are console applications, which if invoked by clicking on the executable in a Windows Explorer window, the console subsystem will create a window.

**Comment by DaveWise2** [comment]
<right?>  Yes.  I double click on the .exe's icon, its window appears, and I click on the X.  Can you suggest a good spot for a breakpoint?  Then I can step through the exit sequence.

My local build was built using:
```
Microsoft Visual Studio Professional 2013
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

Team Explorer for Visual Studio 2013   06177-004-0447006-02192
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06177-004-0447006-02192
Microsoft Visual Basic 2013

Visual C# 2013   06177-004-0447006-02192
Microsoft Visual C# 2013

Visual C++ 2013   06177-004-0447006-02192
Microsoft Visual C++ 2013

Visual F# 2013   06177-004-0447006-02192
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06177-004-0447006-02192
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

Common Azure Tools   1.4
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   2.8.60610.756
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Phoenix CoreArchitect 6.0 Debugger  6.0.0.1    
Phoenix CoreArchitect 6.0 DebugEngine. For more information, see the Phoenix website at http://www.phoenix.com.
Copyright (c) 2003-2016 Phoenix Technologies Ltd. All rights reserved.

Phoenix CoreArchitect 6.0 Language Services   1.0
Phoenix CoreArchitect 6.0 Language Services. For more information, see the Phoenix website at http://www.phoenix.com.
Copyright (c) 2003-2016 Phoenix Technologies Ltd. All rights reserved.

Phoenix CoreArchitect 6.0 Main Package   6.0.0.1
Phoenix CoreArchitect 6.0. For more information, see the Phoenix website at http://www.phoenix.com.
Copyright (c) 2003-2016 Phoenix Technologies Ltd. All rights reserved.

Phoenix CoreArchitect 6.0 Tools Options Page   1.0
Phoenix CoreArchitect 6.0 Tools Options Page. For more information, see the Phoenix website at http://www.phoenix.com.
Copyright (c) 2011-2016 Phoenix Technologies Ltd. All rights reserved.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

Phoenix CoreArchitect 6.0 EDK II Project Package
Phoenix CoreArchitect 6.0 EDK II Project Package. For more information, see the Phoenix website at http://www.phoenix.com.
Copyright (c) 2011-2016 Phoenix Technologies Ltd. All rights reserved.

Phoenix CoreArchitect 6.0 Information Browser
Phoenix CoreArchitect 6.0 Information Browser. For more information, see the Phoenix website at http://www.phoenix.com.
Copyright (c) 2011-2016 Phoenix Technologies Ltd. All rights reserved.

Phoenix CoreArchitect 6.0 SCT Project Package
Phoenix CoreArchitect 6.0 SCT Project Package. For more information, see the Phoenix website at http://www.phoenix.com.
Copyright (c) 2011-2016 Phoenix Technologies Ltd. All rights reserved.

Phoenix CoreArchitect 6.0 SCT3 Project Package
Phoenix CoreArchitect 6.0 SCT3 Project Package. For more information, see the Phoenix website at http://www.phoenix.com.
Copyright (c) 2011-2016 Phoenix Technologies Ltd. All rights reserved.

Phoenix CoreArchitect 6.0 SCT4 Project Package
Phoenix CoreArchitect 6.0 SCT4 Project Package. For more information, see the Phoenix website at http://www.phoenix.com.
Copyright (c) 2011-2016 Phoenix Technologies Ltd. All rights reserved.

Phoenix CoreArchitect 6.0 Solution Manager
Phoenix CoreArchitect 6.0 Solution Manager. For more information, see the Phoenix website at http://www.phoenix.com.
Copyright (c) 2011-2016 Phoenix Technologies Ltd. All rights reserved.
```

**Comment by DaveWise2** [comment]
<not Windows GUI apps> Ah, right, I should have known that.  So there isn't any dismiss code.  How does Windows kill SIMH?

**Comment by markpizz** [comment]
I'm 99% sure that Windows will end up calling the Win32 TerminateProcess API.  This may be after some determination of whether the process is a Console or Windows subsystem process, which would presumably send the Windows Subsystem process an Exit Message first.

You haven't been precise about exactly how you're observing this.
I'm guessing that you:
1) Find the simulator executable (Say VAX.exe) using Windows Explorer
2) You click on the VAX.exe in the explorer window to start the VAX simulator
3) You click on the X in the upper right hand corner of the console window that is created.
No other input or interactions are happening, right?

**Comment by markpizz** [comment]
What happens if, in Visual Studio, you:
1) Open the "Visual Studio Projects\simh.sln" Solution file.
2) Point at a particular simulator and Right Click->"Set as Startup Project" 
3) Hit F5
4) When Visual Studio finishes compiling the simulator and the simulator starts you click on the X in the upper right hand corner of the simulator window.
Do you get a similar crash?  Does the debugger stop in any interesting place?

**Comment by DaveWise2** [comment]
> I'm guessing that you:
>
>Find the simulator executable (Say VAX.exe) using Windows Explorer
>You click on the VAX.exe in the explorer window to start the VAX simulator
>You click on the X in the upper right hand corner of the console window that is created.
>No other input or interactions are happening, right?

That's correct, no other input.  (But simple commands other than exit do not change the outcome.)

>What happens if, in Visual Studio, you:
>
>Open the "Visual Studio Projects\simh.sln" Solution file.
>Point at a particular simulator and Right Click->"Set as Startup Project"
>Hit F5
>When Visual Studio finishes compiling the simulator and the simulator starts you click on the X in the >upper right hand corner of the simulator window.
>Do you get a similar crash? Does the debugger stop in any interesting place?

The same, including the address.  The debugger says no source is available.  Disassembly shows the instruction pointer is in the weeds.

Additional info from dismissing VAX.EXE:
~~~
Problem signature:
  Problem Event Name:	BEX
  Application Name:	VAX.exe
  Application Version:	0.0.0.0
  Application Timestamp:	58fe64b8
  Fault Module Name:	StackHash_0a9e
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	043874ac
  Exception Code:	c0000005
  Exception Data:	00000008
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
~~~

**Comment by markpizz** [comment]
>> I'm guessing that you:
>>
>>Find the simulator executable (Say VAX.exe) using Windows Explorer
>>You click on the VAX.exe in the explorer window to start the VAX simulator
>>You click on the X in the upper right hand corner of the console window that is created.
>>No other input or interactions are happening, right?
>
>That's correct, no other input.  (But simple commands other than exit do not change the outcome.)

Do things shutdown cleanly if you enter an "exit" or "quit" command?

Something else strange is going on here.  You have this problem with binaries that I built and binaries you've built, right?

What happens if you temporarily turn off your Anti-Virus?

----
Plan B...

Please take the files in this zip file
[hello.zip](https://github.com/simh/simh/files/977198/hello.zip)
and drop them into the "Visual Studio Projects" folder of your working directory.

Then in Visual Studio with the simh.sln loaded, Right Click on the "Solution 'Simh'"->Add->Existing Project.  Navigate to and select the hello.vcproj file.  This will probably do a conversion to vcxproj and add a hello project to the solution explorer.
Select the hello project and RightClick->"Set as Startup Project".
Hit F5.
Click on the X in the upper right corner of the resulting console window.
Does this fail in the same way as the simulators?

**Comment by DaveWise2** [comment]
It exits cleanly on "exit".  On window dismiss, it crashes the same way with yours and mine.  I can't change AV right now, this is a work machine and locked down tight.  I'll try some window dismisses tonight at home.  And build 'hello'.

**Comment by DaveWise2** [comment]
Hello crashes the same way.  I'll try it at home later.

**Comment by DaveWise2** [comment]
Hello dismissed just fine at home.  So did I1620.  I will chalk this up to AV or some other institutional evil on my work machine.

**Comment by DaveWise2** [comment]
Update: Whatever was evil on my work machine, changed.  It doesn't crash on dismiss anymore.  Whatever!
