### ISSUE TITLE
i1620_cpu.c: treating record marks as zeros is RIGHT solution

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#446]
Issue #172 got it wrong.

Although users were admonished not to attempt arithmetic on record marks, IBM did indeed design the 1620 to accept them and treat them as zeros - provided they only appear in the Q operand.
As far as I can tell, this is documented nowhere except in the schematics themselves.

You can test my assertion for yourself.  Just download schematics, either
1620_F_ALD_SN11093 or
227-5631-0_IBM_1620_Customer_Engineering_Instructional_System_Diagrams_1962,
find page 01.60.34.1 (near PDF page 308), which is TRUE COMP SW DIGIT 1 DIGIT, grind the wiring down to logic equations, and try them with zero and with 8-2.  In both cases, if TRUE, you get zero, and if COMP, you get 8-1, the nines complement of zero.

Here are the equations, but feel free to reconstruct them yourself:
~~~
1 = (1 && TRUE)
 || (!1 && COMP)
2 = (2 && !8)
4 = (4 && TRUE)
 || (2 && !4 && (!2 || !8 || !COMP) && COMP)     /* This boils down to (2 && !4 && !8 && COMP) */
 || (!8 && !2 && 4)
8 = (8 && !2 && TRUE)
 || (!4 && !2 && !8 && COMP)
 || (8 && 2 && COMP)
~~~

This logic block connects the DIGIT or DIGIT/BRANCH register (which contains a digit of the Q operand) to MAR UNITS during Trigger 13, which is the trigger that looks up one digit of result from the add table.  Meanwhile, the P operand is in the MDR, which goes straight to MAR TENS.  A record mark there will activate the MAR VRC (vertical redundancy check) logic and cause a MAR CHECK.

I added the following before each BAD_DIGIT(src) test in add_field() and cmp_field(), three instances total:
~~~
    if ((src & DIGIT) == REC_MARK)                      /* treat src RM as 0 */
        src = 0;
~~~
Note that only record mark is affected; group mark (8-4-2-1) remains invalid, even though elsewhere in I1620 it terminates I/O just like a record mark.

IBM used this undocumented feature in program MI-015, "HASH TOTAL" [MI015.PT.txt](https://github.com/simh/simh/files/991414/MI015.PT.txt), which is used to check the integrity of tapes.  (There was probably a version for cards, but I don't have it.)  It initializes an accumulator variable to a seed, then reads alphamerically, separating the input into twenty-digit chunks, then adding the chunks to the accumulator.  (I'm skipping details; it's actually a subtract but that's beside the point.)

Obviously MI-015 has to tolerate record marks, since any given tape may be riddled with them.  The key is that the P operand - the augend - never contains a record mark; only the Q operand - the addend.

To use MI-015, you attach it to ptr, boot ptr, attach the test tape to ptr (it can be anything, even MI-015), go, attach \<whatever\> to ptr (another SIMH bug, running out of tape should complete the instruction even though it's also an error - on the real 1620 it lights up READER NOT READY but you can RELEASE out of it), set sw1, and go.  It will print out the hash total and halt.  However, you have to hack another I1620 bug first, by changing ind_table[18] from -1 to 0.  Another undocumented feature, indicator 18 is MAR CHECK.  Normally this causes a CHECK STOP, but it can be turned off at the CE panel inside the machine.  MI-015 does a BI on indicator 18.

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by DaveWise2** [comment]
Looking through `227-5857-0_1620_Model_2_Customer_Engineering_Intermediate_Level_Diagrams_Apr64.pdf`, page 10.01.32.1 (pdf page 172), the Model II Q T/C Network does not handle record mark, so treating RM as 0 should be confined to Model I.

**Comment by archivisth** [comment]
So let me get this straight. If the P operand is a record mark, it would trigger a MAR CHECK due to VRC failure during its transfer to the MAR TENS position. But if the Q operand is a record mark, special logic grinds it down to 0 as part of the transfer to the MAR ONES position, and there is no VRC or MAR CHECK. This applies to any flow that is doing a table lookup add via Trigger 13. Does that mean it would applies to multiply and divide as well?

Is MI-015 expecting a MAR CHECK to be generated? Is that why it's testing indicator 18? Or is expecting it to be off?

Is MI-015 listed as not working on a Model II? Because it certainly won't.

**Comment by DaveWise2** [comment]
> If the P operand is a record mark, it would trigger a MAR CHECK due to VRC failure during its transfer to the MAR TENS position

I believe so.  I will verify it on my machine.

> Does that mean it would apply to multiply and divide as well?

I thought "maybe", but I found an IBM writeup for MI-015 yesterday, and it had an old Post-It on the front where I had mentioned that for multiply, Q RM acted like 6, not 0.  Since divide uses repeated subtraction, Q RM might act like 0 but it all depends on how divide uses the true/complement logic.  I'll have to study it and try it.

It may be moot, since as far as I know, MI-015 is the only program ever written that was designed to do record mark arithmetic, and the only thing it does is subtract.  That's probably all we need to keep programs happy, and go ahead and err out on everything else.

No, MI-015 doesn't care about MAR CHECK, it's just ritually turning off indicators.  The BI instructions all go to *+12.

I don't have any MI-015 writeups from the Model II era (the last one I have is still 1961), and the only Catalog of Programs I have is from 1962 which IIRC is still pre-Model II.  IBM may have supported MI-015 on the Model II, but they could only have done so by writing a new version of the program, that zeroes out RM's itself.  It wouldn't surprise me if they did, they were always distributing new versions of this and that.  
Back in the early Model I timeframe, every program distribution writeup included a hash total, so it was a commonly used program at that point.
[MI015.pdf](https://github.com/simh/simh/files/1012597/MI015.pdf)

(Beware, the MI-015.PT I attached earlier is a stripped down version, no banner, no compare.  It doesn't match the writeup but it's identical where it counts.  I can't remember whether it came from IBM, from me, or from the original owner of the machine.)

Here's what I'm doing for it today.  See lines 415, 419, 1400, 1401, 1420, 1421, 1494, and 1495.
[i1620_cpu.c.txt](https://github.com/simh/simh/files/1012603/i1620_cpu.c.txt)

**Comment by archivisth** [comment]
This is truly a hack, but I can't argue with the hardware. However, I'm going to place this under control of a mode flag that is <off> by default. Flagging invalid digits is too useful a debugging technique to give up for the sake of one poorly written program.

**Comment by DaveWise2** [comment]
That's what I did in the i1620_cpu.c that I posted yesterday.  I added a UI flag, "RM0", which controls the substitution.  I set the default to 1, i.e., on.  It also only substitutes on Model I; that is, when `cpu_unit.flags & IF_MII == 0`.

**Comment by DaveWise2** [comment]
I discovered a newer Catalog Of Programs, GC20-1603-10_1620_Catalog_of_Programs_Jan71.pdf .  IBM was out of the hash total business, but someone at Marquette wrote one for cards.  The algorithm sounds the same.  JFYI.

**Comment by archivisth** [comment]
Change submitted. This is under control of a new CPU option for the MODEL I only:

SET CPU RMOK

It is off by default.

This issue can be closed.

**Comment by DaveWise2** [comment]
Thanks, Bob.  I will test it this week.

I am unsure of one section of code.  In cmp_field(), I think that the RM-to-0 substitution should be performed before the "unlike sign and nonzero digit" test for early exit.  A raw RM will test as nonzero and may therefore cause an early exit, while the same RM will look like zero on the far side of the true/complement logic and not exit.  Don't change it yet; I will try it on my 1620 and confirm it with the schematics, and post my findings here.

**Comment by DaveWise2** [comment]
Nope, you are right.  The DIGIT trigger (DIGIT/RM/GM in later machines) which controls exit is set directly from the MDR (Memory Data Register), not from the True/Complement logic hanging off the DIGIT register.  So a different-sign operand containing RM will exit even though the same-sign version of that operand would treat the RM as zero.

Anybody who writes a program that depends on this deserves what he gets.  :)

**Comment by DaveWise2** [comment]
Looks fine here, Bob.  Thanks!

**Comment by DaveWise2** [comment]
Oops, sorry, Bob, I just studied your change more, and there's a small problem.  Your change will treat RM as zero, but it will err out on flagged RM.  The real CPU treats RM as zero regardless of flag.  You need to change

`if ((src == REC_MARK)`
to
`if (((src & DIGIT) == REC_MARK)`.

**Comment by archivisth** [comment]
No, there isn't. In all three cases, src has been masked with DIGIT.

add #1

src = M[s] & DIGIT;
if ((src == REC_MARK) &&                                /* Q record mark? */
     ((cpu_unit.flags & IF_RMOK) != 0))                  /* Model I & 
enabled? */
     src = 0;                                            /* treat as 0 */

add #2

     if (src_f)                                          /* src done? 
src = 0 */
         src = 0;
     else {
         src = M[s] & DIGIT;                             /* get src digit */
         if (cnt >= skp)                                 /* get src flag */
             src_f = M[s] & FLAG;
         MM (s);                                         /* decr src addr */
         if ((src == REC_MARK) &&                        /* Q record 
mark? */
             ((cpu_unit.flags & IF_RMOK) != 0))          /* Model I & 
enabled? */
             src = 0;                                    /* treat as 0 */
         }

compare

     if (src_f)                                          /* src done? 
src = 0 */
         src = 0;
     else {
         src = M[s] & DIGIT;                             /* get src digit */
         if (d != dsv)                                   /* if not first 
digit, */
             src_f = M[s] & FLAG;                        /* get src flag */
         MM (s);                                         /* decr src addr */
         }
     if (unlike && ((dst | src) != 0)) {                 /* unlike 
signs, digit? */
         ind[IN_EZ] = 0;                                 /* not equal */
         return SCPE_OK;
         }
     if ((src == REC_MARK) &&                            /* Q record 
mark? */
         ((cpu_unit.flags & IF_RMOK) != 0))              /* Model I & 
enabled? */
         src = 0;                                        /* treat as 0 */

**Comment by archivisth** [comment]
No, there isn't. In all three cases, src has been masked with DIGIT.

add #1

```
src = M[s] & DIGIT;
if ((src == REC_MARK) &&                                /* Q record mark? */
     ((cpu_unit.flags & IF_RMOK) != 0))                  /* Model I & enabled? */
     src = 0;                                            /* treat as 0 */
```

add #2

```
     if (src_f)                                          /* src done? src = 0 */
         src = 0;
     else {
         src = M[s] & DIGIT;                             /* get src digit */
         if (cnt >= skp)                                 /* get src flag */
             src_f = M[s] & FLAG;
         MM (s);                                         /* decr src addr */
         if ((src == REC_MARK) &&                        /* Q record mark? */
             ((cpu_unit.flags & IF_RMOK) != 0))          /* Model I & enabled? */
             src = 0;                                    /* treat as 0 */
         }
```

compare

```
     if (src_f)                                          /* src done? src = 0 */
         src = 0;
     else {
         src = M[s] & DIGIT;                             /* get src digit */
         if (d != dsv)                                   /* if not first digit, */
             src_f = M[s] & FLAG;                        /* get src flag */
         MM (s);                                         /* decr src addr */
         }
     if (unlike && ((dst | src) != 0)) {                 /* unlike signs, digit? */
         ind[IN_EZ] = 0;                                 /* not equal */
         return SCPE_OK;
         }
     if ((src == REC_MARK) &&                            /* Q record mark? */
         ((cpu_unit.flags & IF_RMOK) != 0))              /* Model I & enabled? */
         src = 0;                                        /* treat as 0 */
```

**Comment by DaveWise2** [comment]
Ah, didn't notice the src preprocessing.
