### ISSUE TITLE
I1620: Implement indicator 18, MAR CHECK

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#447]
Need to change ind_table[18] from -1 to 0.  This indicator is MAR CHECK.  It is not documented, but IBM-written program MI-015 (HASH TOTAL) does a BI on indicator 18.  May want to set indicator 18 and commit the PC in certain error paths, but it's a corner case - in normal use, MAR CHECK causes a CHECK STOP which can only be RESET out of.  You have to open up the machine and set a switch inside to bypass it.  A-level machines (i.e., prototypes) had a MAR STOP console switch like the DATA STOP and I/O STOP switches.

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by archivisth** [comment]
I'll add this to the next revision of the CPU. I normally don't implement diagnostic features, but this seems harmless enough.

**Comment by DaveWise2** [comment]
Thanks, Bob.

Update: The Indicator 18 tested by MI-015 is in fact unimplemented, while Indicator 08 is MAR CHECK.  The CU02 diagnostic program reads the latter, so both 08 and 18 need to read 0 to run these programs without modification.

Pages 01.25.25.1, 01.25.30.1, and 01.25.35.1 of both B and F Model I schematics show that testing an unimplemented indicator does not cause an error; it simply reads zero, "indicator not set".  BI won't branch, BNI will.

Informative Appendix:

Furthermore, in the Digit/Branch TENS position, only the 1 and C bits are used for indicator selection; therefore,
0X and 6X select indicator 0X;
1X and 7X select indicator 1X;
2X, 4X, and 8X select no indicator, and
3X, 5X, and 9X select both indicator 0X and 1X simultaneously, their states being ORed.

Of course nobody in their right mind would do that, I just post it here for completeness.
This is Model I.  Without Model II schematics, I can't say what the latter does.

**Comment by archivisth** [comment]
Change submitted not to cause an error on an undefined indicator. Undefined indicators are always 0.

This issue can be closed.

**Comment by DaveWise2** [comment]
Thanks, Bob, looks fine here.

**Comment by DaveWise2** [comment]
I just noticed one thing.  In i1620_defs.h, 
`#define IN_MARCHK       18                              /* MAR check - diag only */`
should be 08, not 18.  Indicator 18 is not implemented.
This change is in almost cosmetic, as nobody refers to IN_MARCHK.
