### ISSUE TITLE
Ibm1130 (Windows GUI): printer.txt is lost when lineprinter icon is clicked

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#448]
- #### Context
I seem to have a pathological case in which using the lineprinter icon to "tear off"
the printer page (detach prt, view "printer.txt", etc.) **always** results in the
printer.txt file being deleted before notepad can open it.  This may have something
to do with my using Console2 rather than standard cmd.exe to start SimH in,
because it doesn't seem to happen with cmd.exe

I've discovered a modification that seems to eliminate the problem.
In ibm1130_gui.c, function tear_printer(), I made the following change:

#if 0
    remove(filename);                                   /* delete the file */
#else
    sprintf(cmd, "!del %s", filename);
    if (! stuff_and_wait(cmd, 3000, 500))
        return;
#endif

This seems to solve the problem.
- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
See attached screengrab

![simh_version](https://cloud.githubusercontent.com/assets/17226010/26027024/a9358326-37d4-11e7-9696-f9d7856ed6c0.png)

- #### how you built the simulator or that you're using prebuilt binaries

See attached screengrab

![build_output](https://cloud.githubusercontent.com/assets/17226010/26027028/c20130c6-37d4-11e7-9f94-197e42fb5958.png)

- #### the simulator configuration file (or commands) which were used when the problem occurred.

set cpu 32k
set prt 1403
set cr 2501

;set gui off
;set throttle 100k
reset
delete printer.txt

att dsk0 dms.dsk

att prt printer.txt
boot dsk

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Hmmm....

I think I broke this when I 'fixed' earlier problems with stuffing input commands.

Code which uses stuff_and_wait() isn't properly waiting since even though the command input is correctly being entered into the input side of things, the wait test isn't valid.  This should be fixed now.  Please confirm.

**Comment by Jim-F** [comment]
This seems to work now.

**Comment by Jim-F** [comment]
. . .add that card reader/card punch stuff as a Github issue
as well?

Jim F.

**Comment by markpizz** [comment]
> . . .add that card reader/card punch stuff as a Github issue
> as well?

Is that question really part of this issue?  If so, is there still a problem with this?  If it is part of this issue, then please reopen it and let me know.

Thanks.
