### ISSUE TITLE
Ibm1130 (Windows GUI): lineprinter button is still active when simulation is running

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#449]
- #### Context
If an 1130 program is running -- in particular, if it's PAUSEed (i.e., in a
wait state) awaiting input from the keyboard, the lineprinter button
is not disabled (as it was, e.g., in the 2012 version of ibm1130.exe
from ibm1130.org.

Here's a symptom (see attached screenshot symptom.png):

![symptom](https://cloud.githubusercontent.com/assets/17226010/26036175/f2a54ce4-38a6-11e7-9a0e-24b431ca044a.png)

I have devised a local fix that seems to work (though it's no doubt an ugly hack on top
of the way the program was designed) by putting an "enable_printer_button"
function (takes TRUE or FALSE as argument) into ibm1130_gui.c and then
calling it from ibm1130_cpu.c to disable the lineprinter button when
the instruction-execution loop starts running and re-enabling it when it exits.  This overrides
whatever is happening in (I presume) update_gui(), which is probably where
this kind of button control is supposed to be taking place.

See attached screenshot "enable-disable lineprinter button.png":

![enable-disable lineprinter button](https://cloud.githubusercontent.com/assets/17226010/26036217/8fa157ea-38a7-11e7-915f-5c127cb320ef.png)

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
See attached screenshot simh_version.png:

![simh_version](https://cloud.githubusercontent.com/assets/17226010/26036231/b27c7de4-38a7-11e7-80fc-bf20ac0769e7.png)

- #### how you built the simulator or that you're using prebuilt binaries

See attached screenshot build_output.png:

![build_output](https://cloud.githubusercontent.com/assets/17226010/26036235/bfa43ed0-38a7-11e7-8d67-cf2b4e5fec2a.png)

- #### the simulator configuration file (or commands) which were used when the problem occurred.

set cpu 32k
set prt 1403
set cr 2501

;set gui off
;set throttle 100k
reset
delete printer.txt

att dsk0 dms.dsk

att prt printer.txt
boot dsk

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Will you zip up the "c:\ibm1130\dms\fortran_console_io_text.job" file and drop it here in this issue.

A much simpler fix might be:

```
In ibm1130_gui.c:
@@ -1466,7 +1466,8 @@ static void tear_printer (void)
 {
     char cmd[MAX_PATH+100], filename[MAX_PATH];
  
-    if ((prt_unit.flags & UNIT_ATT) == 0)
+    if (((prt_unit.flags & UNIT_ATT) == 0) ||
         (running))
         return;
```

**Comment by Jim-F** [comment]
> Will you zip up the "c:\ibm1130\dms\fortran_console_io_text.job" file and drop it here.

Here it is:

[fortran_console_io_text.zip](https://github.com/simh/simh/files/999816/fortran_console_io_text.zip)
