### ISSUE TITLE
Ibm1130 (Windows GUI): Focus stays in GUI on keyboard activate or IMMediate STOP

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#450]
- #### Context
This is more of an operational annoyance than a bug, but I think it could be addressed
without too much hassle.  If you're running a program that does console I/O
(like prompting for input from the keyboard), the focus doesn't automatically shift to
the SimH console after you've used the GUI to load the card reader and click
PROGRAM START -- if you start typing, you'll discover that you forgot to click the mouse
in the console window.  Same with using the IMM STOP button in the GUI to
drop back to the simulator prompt -- if you start trying to type SCP commands, you'll
discover you forgot to click the mouse in the console window.

I've made a local hack, in which the focus shift has been added to two places:
in ibm1130_gui.c for the IMM STOP button-push case, and in ibm1130_stddev.c
when the keyboard is selected.

I've tested the focus shifting on a Windows 7 machine, and it works there
too.

Here's the hack (I've put it in a screen grab so the alignment doesn't get messed up):

![shift focus to simh console window](https://cloud.githubusercontent.com/assets/17226010/26037979/803917be-38cc-11e7-875f-2029aaf9048c.png)

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

![simh_version](https://cloud.githubusercontent.com/assets/17226010/26036703/d1b7bf9e-38b0-11e7-9971-cc57de710f13.png)

- #### how you built the simulator or that you're using prebuilt binaries

![build_output](https://cloud.githubusercontent.com/assets/17226010/26036707/da020376-38b0-11e7-9a3c-78538398a694.png)

- #### the simulator configuration file (or commands) which were used when the problem occurred.

set cpu 32k
set prt 1403
set cr 2501

;set gui off
;set throttle 100k
reset
delete printer.txt

att dsk0 dms.dsk

att prt printer.txt
boot dsk

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by Jim-F** [comment]
I just noticed that that
guiThreadId = GetWindowThreadProcessId. . .
in ibm1130_gui.c, Pump()
was in the wrong place, and was never getting called, so the calls
to AttachThreadInput() couldn't have been necessary after all.

So that simplifies things:

![shift focus to simh console window](https://cloud.githubusercontent.com/assets/17226010/26037933/d002a9b4-38cb-11e7-8477-ddb6edf0bc40.png)

**Comment by markpizz** [comment]
> Here's the hack (I've put it in a screen grab so the alignment doesn't get messed up):

FYI: comments here in the issue system can be formatted with GFM (Github Flavored Markdown).  If you start a section of text with \`\`\` (on a blank line) and end it with \`\`\` (on another blank line) , the text between these tags will be formatted with a fixed width font and thus keep alignment and indentation.  This will leave the text in this block so that it can be cut and pasted, etc.  Click on the "Preview" tab of the comment window you're typing in to see how the formatting will look.

**Comment by Jim-F** [comment]
Mark,

I see you've already checked in new code for this.

It occurred to me this morning that if this enhancement
were deemed suitable for IDC_IMM_STOP (the IMM STOP button),
it might as well also be added for IDC_POWER (the POWER button).

Same additional line in ibm1130_gui.c:

-------------------
void HandleCommand (HWND hWnd, WORD wNotify, WORD idCtl, HWND hwCtl)
{
    int i;

    switch (idCtl) {
        case IDC_POWER:                     /* toggle system power */
            power = ! power;
            reset_all(0);
            if (running && ! power) {       /* turning off */
                reason = STOP_POWER_OFF;
                /* wait for execution thread to exit */
/* this prevents message pump from running, which unfortunately locks up
 * the emulator thread when it calls gui_run(FALSE) which calls EnableWindow on the Run lamp
 *              while (running)
 *                  Sleep(10);
 */             
SetForegroundWindow(hMainConsole);
            }
-------------------

Jim F.

**Comment by markpizz** [comment]
Step back from this a little..

Why wouldn't keyboard focus always be set to the console window after every button press?  You certainly won't be typing anywhere else?

**Comment by Jim-F** [comment]
> Why wouldn't keyboard focus always be set to the console window
> after every button press? You certainly won't be typing anywhere else?

Yes, I can't think of any reason why that wouldn't work.
After all, if you click on a button you're always yanking
the focus back to the GUI window automatically, so that
shouldn't be a problem.

I was just being conservative.  ;->
