### ISSUE TITLE
Ibm1130 (Windows GUI): Threading problem when building w/async from source with MinGW

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#451]
- #### Context
Building with MinGW from source code dating back to 13 June 2015 (which is the
earliest I have on hand for SimH v4) up to and including the latest code from 14 May 2017,
using build_mingw.bat (i.e., with SIM_ASYNCH_IO defined and using pthreads),
causes a bug in the GUI which does not appear when running the Win32 Development
binaries (built with Visual Studio) from the same dates.

My MinGW builds utilize the pthreads from a windows-build component package I
downloaded from github on 4 May 2017 (in which pthreads hasn't changed in two years).

The problem disappears when I build with build_mingw_noasync.bat

When ibm1130.exe is built as described above, then clicking on either the POWER
or the CHECK RESET button in the GUI causes SimH to terminate with the error message:

Improper thread context for operation

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

![simh_version](https://cloud.githubusercontent.com/assets/17226010/26039430/db496c3c-38e8-11e7-8d10-991468d3707b.png)

- #### how you built the simulator or that you're using prebuilt binaries

![build_output](https://cloud.githubusercontent.com/assets/17226010/26039442/f146b562-38e8-11e7-8e3f-7550c9d9279e.png)

- #### the simulator configuration file (or commands) which were used when the problem occurred.

set cpu 32k
set prt 1403
set cr 2501

;set gui off
;set throttle 100k
reset
delete printer.txt

att dsk0 dms.dsk

att prt printer.txt
boot dsk

- #### the expected behavior and the actual behavior

Output when clicking either the POWER or the CHECK RESET button
(running ibm1130.exe built with MinGW and pthreads):

![error_message](https://cloud.githubusercontent.com/assets/17226010/26039468/246ce588-38e9-11e7-84ef-27b84e6bfab1.png)

Expected behavior (running ibm1130.exe built with MinGW using build_mingw_noasync.bat
or when running a Win32 Development binary built with Visual Studio):

1.  CHECK RESET button
Does nothing if a program is running, clears the registers if the 1130 is in a wait state.

2. POWER button
Clears the registers, turns off FILE READY and POWER ON lights (and the
RUN light if a program was running).  If a program was running, SimH drops
back to its command prompt and a message like

Power off, IAR: 00000000 (70ff JMP    0000   )

appears on the console.

---

This is not an issue that anybody (any SimH developer, at any rate)
needs to be concerned about fixing.

These 1130 GUI buttons do not need to be operated under normal circumstances
anyway.

But the difference in behavior of the MinGW and Visual Studio builds is
of some concern, and is probably worth noting here.

I will be building with build_mingw_noasync.bat hereafter unless something
changes.
- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Thanks for reporting this.

There are many problems related to many/most simulators built with MinGW and asynch support.

There is nothing in the IBM1130 simulator which can leverage any asynch support provided by simh.

The Win32 Development binaries only build simulators with asynch support if the simulator contains functionality which can leverage it.  So using build_mingw_noasynch.bat for the ibm1130 simulator will produce close or similar functionality to the Visual Studio built binaries.

I'll explore ways to get useful asynch functionality for simulators that can leverage it when building with MinGW

**Comment by markpizz** [comment]
This problem is a general synchronization one.

Both of these buttons end up invoking the simh framework function reset_all(0);

This function is ONLY ever meant to be called from the main simh thread and not from any separate thread context that may be handling windows messages.

**Comment by Jim-F** [comment]
I like the "reset" messages you added for RESET and POWER buttons.

**Comment by markpizz** [comment]
The same functionality is happening only now in the correct thread (the main thread).
