### ISSUE TITLE
Ibm1130 (Windows GUI): Permit PROGRAM LOAD button to auto "boot dsk" if no cr attached

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#452]
- #### Context
This is also a request for an additional bit of operational "candy".

At the moment, the 1130 simulator "cheats" a bit by allowing you to boot
DMS from disk without actually having a binary "cold start card" in the
card reader -- ibm1130_cr.c contains an array (dms_boot_data[]), originally
generated from a cold start card image, that is loaded into memory automatically when
you issue the SCP command "boot dskN".

The PROGRAM LOAD button in the GUI will currently issue a "boot cr" command
that will boot the 1130 from a (binary) card deck in the card reader --
either a cold start card image or one of the "onecard" programs available from ibm1130.org.

Since the SCP "boot dskN" command is already "pretending" that there is a
cold start card in the card reader, even if there is not, I think it would be appropriate
for the PROGRAM LOAD button to act the same way -- i.e., check the card reader
first (as it is now doing), but if there is no file attached to the card reader, then
attempt to boot from disk.

This would allow you to reboot DMS entirely from the GUI, by clicking, e.g.,
IMM STOP, CHECK RESET, PROGRAM LOAD
rather than (as is now necessary)
IMM STOP, CHECK RESET, and then going down to the console to type "boot dskN'.

It's even possible to have the button automatically check the console switches
for a disk other than drive 0, as per the manual at
http://www.ibm1130.net/DM2/ColdStart.html ,
according to which:

Console Entry Switch register contains boot drive #

all switches off -- CES == 0
switch 15 on -- CES == 1
switch 14 on -- CES == 2
switch 15,14 on -- CES == 3
switch 13 on -- CES == 4

Here's some code.  In ibm1130_gui.c, function HandleCommand():

```
------------------------
        case IDC_PROGRAM_LOAD:
            if (! running) {                /* if card reader is attached to a file, do cold start read of one card */
                IAR = 0;                    /* reset IAR */
#ifdef PROGRAM_LOAD_STARTS_CPU
if (cr_unit.flags & UNIT_ATT)
{
                stuff_cmd("boot cr");
}
else if (dsk_unit[0].flags&UNIT_ATT || dsk_unit[1].flags&UNIT_ATT || dsk_unit[2].flags&UNIT_ATT || dsk_unit[3].flags&UNIT_ATT)
{
  switch (CES) {
    case 0:
      stuff_cmd("boot dsk0");
      break;

    case 1:
      stuff_cmd("boot dsk1");
      break;

    case 2:
      stuff_cmd("boot dsk2");
      break;

    case 3:
      stuff_cmd("boot dsk3");
      break;
  }
}
#else
                if (cr_boot(0, NULL) != SCPE_OK)    /* load boot card */
                    remark_cmd("IPL failed");
#endif
            }
            break;
------------------------
```

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by Jim-F** [comment]
And also, of course, "case 4" in the above (there can be 5 drives).

But why can't I edit this?

**Comment by Jim-F** [comment]
There's an additional wrinkle.

If you load a program in the card reader and then start it, the reader remains attached,
and in STATE_1442_EOF, and this will prevent the buttons
IMM STOP, CHECK RESET, PROGRAM LOAD
from rebooting from disk, as desired, unless you remember to click the
card reader icon first to detach it, which is a bit of a nuisance.

So it's probably reasonable to have CHECK RESET to detach the card reader
unless it's in STATE_1442_FULL (as it would be if you had put a
cold start card in it).  And you need to call update_gui() so the empty card reader
displays its state properly.

Here's the modified code (ibm1130_gui.c, HandleCommand() ).
(And yes, I know you can build the command string instead of having
that case statement.  ;->   This is just for illustration and a quick try-out.)

```
-------------------------
        case IDC_RESET:
            if (! running) {                /* check-reset is disabled while running */
                reset_all(0);
                forms_check(0);             /* clear forms-check status */
                print_check(0);
if ((cr_unit.flags & UNIT_ATT) && btn[IDC_1442].state!=STATE_1442_FULL)
{
  stuff_cmd("detach cr");
  update_gui(TRUE);
}

            }
            break;

        case IDC_PROGRAM_LOAD:
            if (! running) {                /* if card reader is attached to a file, do cold start read of one card */
                IAR = 0;                    /* reset IAR */
#ifdef PROGRAM_LOAD_STARTS_CPU
if (cr_unit.flags & UNIT_ATT)
{
                stuff_cmd("boot cr");
}
else if (dsk_unit[0].flags&UNIT_ATT || dsk_unit[1].flags&UNIT_ATT || dsk_unit[2].flags&UNIT_ATT || dsk_unit[3].flags&UNIT_ATT || dsk_unit[4].flags&UNIT_ATT)
{
  switch (CES) {
    case 0:
      stuff_cmd("boot dsk0");
      break;

    case 1:
      stuff_cmd("boot dsk1");
      break;

    case 2:
      stuff_cmd("boot dsk2");
      break;

    case 3:
      stuff_cmd("boot dsk3");
      break;

    case 4:
      stuff_cmd("boot dsk4");
      break;
  }
}
#else
                if (cr_boot(0, NULL) != SCPE_OK)    /* load boot card */
                    remark_cmd("IPL failed");
#endif
            }
            break;
-------------------------
```

**Comment by Jim-F** [comment]
I wanted to test this with a bootable cold-start card in the card reader, but I didn't see
one lying about at ibm1130.org.  So I made one.  Here it is:

[coldstart.ZIP](https://github.com/simh/simh/files/1010664/coldstart.ZIP)

When you boot from a "real" cold-start card, you don't get the console message
"Loaded DMS V2M12 cold start card" which is what happens in ibm1130_cr.c
load_cr_boot() when it's faking a coldstart card in the reader.

After a while, you get familiar with the message
Wait, IAR: 0000002A (4c80 BSC  I  ,0028   )
as indicating that DMS has been successfully booted (or re-entered)
and is awaiting input.

But just for a little reassurance, I added a message to the end of ibm1130_cpu.c,
sim_instr():

```
------------------------------
    if (cgi)                                /* give CGI hook function a chance to do something */
        cgi_stop(reason);

if (reason == STOP_WAIT)
{
  if (((sim_switches & SWMASK('Q')) == 0) && ! cgi)
  {
    if (IAR==0x2a)
    {
      IR = ReadW(IAR);
      if (IR==0x4c80)
      {
      sprintf(msg, "\nEntered DMS V2M12\n");
#ifdef GUI_SUPPORT
      remark_cmd(msg);
#else
      printf("%s", msg);
#endif
      }
    }
  }
}

    return reason;
}

------------------------------
```

Maybe this would be useful to keep around permanently?

It results in console output like this:

![entered_dms_v2m12_message](https://cloud.githubusercontent.com/assets/17226010/26200381/cbe24524-3b9b-11e7-8243-b205c10c7339.png)

**Comment by Jim-F** [comment]
I commented, above:

> If you load a program in the card reader and then start it,
> and if the reader then remains attached, in STATE_1442_EOF,
> then this will prevent the buttons IMM STOP, RESET, PROGRAM LOAD
> from rebooting from disk, as desired, unless you remember to click the
> card reader icon first to detach it, which is a bit of a nuisance.
>
> So it's probably reasonable to have RESET detach the card reader
> unless it's in STATE_1442_FULL (as it would be if you had put a
> cold start card in it). And you need to call update_gui() so the empty card reader
> displays its state properly.
>
> Here's the modified code (ibm1130_gui.c, HandleCommand() ):

```
-------------------------
        case IDC_RESET:
            if (! running) {                /* check-reset is disabled while running */
                stuff_and_wait("reset", 0, 500);
                forms_check(0);             /* clear forms-check status */
                print_check(0);
            }
if ((cr_unit.flags & UNIT_ATT) && btn[IDC_1442].state!=STATE_1442_FULL)
{
  stuff_cmd("detach cr");
  update_gui(TRUE);
}
-------------------------
```

This should probably also happen for the POWER button (especially since RESET
and POWER are now issuing a "reset" command to SimH that displays on
the console).

Also ibm1130_gui.c, HandleCommand() :

```
-------------------------
        case IDC_POWER:                     /* toggle system power */
            power = ! power;
            if (running && ! power) {       /* turning off */
                reason = STOP_POWER_OFF;
                /* wait for execution thread to exit */
/* this prevents message pump from running, which unfortunately locks up
 * the emulator thread when it calls gui_run(FALSE) which calls EnableWindow on the Run lamp
 *              while (running)
 *                  Sleep(10);
 */             
            }
            stuff_and_wait("reset", 0, 500);

            btn[IDC_POWER_ON].state = power;
            EnableWindow(btn[IDC_POWER_ON].hBtn, power);

            for (i = 0; i < NBUTTONS; i++)  /* repaint all of the lamps */
                if (! btn[i].pushable)
                    InvalidateRect(btn[i].hBtn, NULL, TRUE);
if ((cr_unit.flags & UNIT_ATT) && btn[IDC_1442].state!=STATE_1442_FULL)
{
  stuff_cmd("detach cr");
  update_gui(TRUE);
}
-------------------------
```

**Comment by Jim-F** [comment]
On further reflection, I think I should be a little less heavy-handed
about **forbidding** the user to select an illegal set of switches
(i.e., a CES value that wouldn't work to boot DMS)
before a program (standalone or DMS bootstrap) is loaded into the computer.
The switches can have other uses than selecting the DMS-resident
disk drive for booting, and a standalone program loaded via the
card reader might need switch settings at startupe that would be illegal
for booting DMS.

So instead of **forcing** all switches other than 13-15 to
be off and 13-15 to have a value CES>=0 and CES<=4, I just **look**
at switches 13-15 and choose that CES value as the boot drive
if CES>=0 and CES<=4 and ignore it (leave the boot drive unset)
if CES>4.

Also, calling a flag "dms_is_booted" bothered me, because it's not
whether DMS is booted, but whether **any** program, either standalone
card program or DMS bootstrap, has been loaded, that I want
to keep track of (and this is not the same as whether the CPU
is running, because the CPU can be in a wait state after a program,
or the DMS bootstrap, has been loaded).

The idea here, once again, is that if the 1130 is powered on but
no program has been loaded, I want the FILE READY light to go
on and the DISK UNLOCKED light to go off to indicate that
the CES switch value (of just switches 13-15, and ignoring the rest),
is between 0 and 4 **and** matches a disk that's actually attached.
Otherwise, turn off FILE READY and turn on DISK UNLOCKED.
At this stage, the lights track both the switches (13-15) and
any attach dskN or detach dskN commands to SimH.

But once a program (standalone or DMS bootstrap) is loaded,
I want the switches decoupled from the lights, which
will then only change in response to "attach dskN" or
"detach dskN" commands, indicating whether the drive that the lights
were coupled to when a program was originally loaded is still online
or has been taken offline, or has been put **back** online,
until the machine is either RESET or POWERed off -- then the
lights will go back to tracking whether CES switches 13-15
give a legal DMS boot-disk selection value which also matches
some attached drive.

This gives the DRIVE READY and DISK UNLOCKED indicators something
more interesting to do than just tracking whether dsk0 is attached,
which is what they do now.  (Which means if you boot DMS from
a drive other than dsk0 -- which is allowed! -- the DISK UNLOCKED light
stays on (and the DRIVE READY light stays off) all the time, which is kind of
lame.

So I made five changes on top of the above-indicated changes:

1. Change boolean variable name "dms_is_booted" to "program_is_loaded"

2. Examine CES, but do not assign to it -- (except in load_cr_boot(),
   the load-a-fake-coldstart-card-and-boot function,
   which was **already** setting CES to N in response to
   a "boot dskN" command).  [This also affects issue #452
   (allow the PROGRAM LOAD button to boot the machine) -- we
   can't just assume CES is valid and use it directly.]

3. In ibm1130_cr.c set program_is_loaded=TRUE not just when we
   fake a coldstart in load_cr_boot() but also in cr_boot() when
   we genuinely boot from binary card(s) in the card reader.
   I forgot this before.

4. Make the POWER button behave like the RESET button in terms
   of this enhancement -- after detaching the card reader if it isn't full,
   and updating the GUI to indicate any change to the card reader
   (both for issue #452), set program_is_loaded=FALSE.

5. Don't put variable declarations boot_drive and program_is_loaded
   under conditional compilation based on GUI_SUPPORT.  They're
   harmless if there's no GUI, and it's messier if every instance
   of them is conditionally compiled.


Here are all the changes, superseding the ones given before.
A few of these changes interpenetrate with issue #452
(allow the PROGRAM LOAD button to boot the machine).


ibm1130_cr.c -- Added:

```
---------------------
int boot_drive = -1;
t_bool program_is_loaded = FALSE;
---------------------
```


ibm1130_cr.c, function t_stat load_cr_boot (int32 drvno, int switches) -- Added:

```
---------------------
    }

boot_drive = drvno;                      <--- new lines
program_is_loaded = TRUE;                <---

    return SCPE_OK;
}
---------------------
```


ibm1130_cr.c, function t_stat cr_boot (int32 unitno, DEVICE *dptr)
(This is new this time around.)  Added:


```
---------------------
    readstate = STATION_READ;                   /* the current card has been consumed */

program_is_loaded = TRUE;                <--- new line

    return SCPE_OK;
}
---------------------
```


ibm1130_disk.c -- Added:


```
---------------------
extern void void_backtrace (int afrom, int ato);

extern int boot_drive;                   <--- new line

void xio_disk
---------------------
```


ibm1130_disk.c, function static t_stat dsk_attach (UNIT *uptr, CONST char *cptr) -- Added:


```
---------------------
#if 0                                    <--- new line
    if (drv == 0) {
#else                                    <--- new lines
    if (boot_drive>=0 && (dsk_unit[boot_drive].flags&UNIT_ATT)) {    <---
#endif                                   <---
        disk_ready(TRUE);
        disk_unlocked(FALSE);
    }
---------------------
```


ibm1130_disk.c, function static t_stat dsk_detach (UNIT *uptr) -- Added:


```
---------------------
#if 0                                    <--- new line
    if (drv == 0) {
#else                                    <--- new lines
    if (boot_drive>=0 && (!dsk_unit[boot_drive].flags&UNIT_ATT)) {   <---
#endif                                   <---
        disk_unlocked(TRUE);
        disk_ready(FALSE);
    }
---------------------
```


ibm1130_gui.c -- Added:

```
---------------------
/* reset for the "console" display device  */

extern UNIT cr_unit;                                    /* pointers to 1442 and 1132 (1403) printers */
extern UNIT prt_unit;

extern UNIT dsk_unit[];                                               <--- new lines
extern int boot_drive;                                                <---
extern t_bool program_is_loaded;                                      <---
---------------------
```


ibm1130_gui.c, function void update_gui (BOOL force) -- Added:


```
---------------------
    GUI_END_CRITICAL_SECTION

    CND = 0;    /* combine carry and V as two bits */
    if (C)
        CND |= 2;
    if (V)
        CND |= 1;

if (boot_drive<0 || !program_is_loaded)                               <--- new lines
{                                                                     <---
  boot_drive = CES & 7;                                               <---
  if (boot_drive > 4)                                                 <---
  {                                                                   <---
    boot_drive = -1;                                                  <---
  }                                                                   <---
}                                                                     <---
if (boot_drive>=0 && dsk_unit[boot_drive].flags&UNIT_ATT)             <---
{                                                                     <---
  disk_ready(TRUE);                                                   <---
  disk_unlocked(FALSE);                                               <---
}                                                                     <---
else                                                                  <---
{                                                                     <---
  disk_ready(FALSE);                                                  <---
  disk_unlocked(TRUE);                                                <---
}                                                                     <---

    int_lamps |= int_req;
---------------------
```

ibm1130_gui.c, function static DWORD WINAPI Pump (LPVOID arg) -- Added:


```
---------------------
            SetWindowPos(hActWnd, 0, 0, 0, ra.right-ra.left+1, ra.bottom-ra.top+1, SWP_NOZORDER|SWP_NOMOVE);
        }
    }

Sleep(300);                                                          <--- new lines
update_gui(TRUE);                                                    <---
    if (running) 
---------------------
```

ibm1130_gui.c, function void HandleCommand (HWND hWnd, ... -- Added:


```
---------------------
        case IDC_POWER:                     /* toggle system power */

. . .

            for (i = 0; i < NBUTTONS; i++)  /* repaint all of the lamps */
                if (! btn[i].pushable)
                    InvalidateRect(btn[i].hBtn, NULL, TRUE);
if ((cr_unit.flags & UNIT_ATT) && btn[IDC_1442].state!=STATE_1442_FULL)  <--- issue #452
{                                                                        <--- issue #452
  stuff_cmd("detach cr");                                                <--- issue #452
  update_gui(TRUE);                                                      <--- issue #452
}                                                                        <--- issue #452
program_is_loaded = FALSE;                                               <--- new line

. . .

        case IDC_RESET:
            if (! running) {                /* check-reset is disabled while running */
                stuff_and_wait("reset", 0, 500);
                forms_check(0);             /* clear forms-check status */
                print_check(0);
            }
if ((cr_unit.flags & UNIT_ATT) && btn[IDC_1442].state!=STATE_1442_FULL)  <--- issue #452
{                                                                        <--- issue #452
  stuff_cmd("detach cr");                                                <--- issue #452
  update_gui(TRUE);                                                      <--- issue #452
}                                                                        <--- issue #452
program_is_loaded = FALSE;                                               <--- new line
            break;

        case IDC_PROGRAM_LOAD:
            if (! running) {                /* if card reader is attached to a file, do cold start read of one card */
                IAR = 0;                    /* reset IAR */
#ifdef PROGRAM_LOAD_STARTS_CPU
if (cr_unit.flags & UNIT_ATT)                                                              <--- issue #452
{                                                                                          <--- issue #452
                stuff_cmd("boot cr");
}                                                                                          <--- issue #452
else if (dsk_unit[0].flags&UNIT_ATT || dsk_unit[1].flags&UNIT_ATT ||                       <--- issue #452
dsk_unit[2].flags&UNIT_ATT || dsk_unit[3].flags&UNIT_ATT || dsk_unit[4].flags&UNIT_ATT)    <--- issue #452
{                                                                                          <--- issue #452
  boot_drive = CES & 7;                                                                    <--- issue #452 NEW
  if (boot_drive > 4)                                                                      <--- issue #452 NEW
  {                                                                                        <--- issue #452 NEW
    boot_drive = -1;                                                                       <--- issue #452 NEW
  }                                                                                        <--- issue #452 NEW
                                                                                           <--- issue #452 NEW
  switch (boot_drive) {                                                                    <--- issue #452 NEW
    case 0:                                                                                <--- issue #452
      stuff_cmd("boot dsk0");                                                              <--- issue #452
      break;                                                                               <--- issue #452
                                                                                           <--- issue #452
    case 1:                                                                                <--- issue #452
      stuff_cmd("boot dsk1");                                                              <--- issue #452
      break;                                                                               <--- issue #452
                                                                                           <--- issue #452
    case 2:                                                                                <--- issue #452
      stuff_cmd("boot dsk2");                                                              <--- issue #452
      break;                                                                               <--- issue #452
                                                                                           <--- issue #452
    case 3:                                                                                <--- issue #452
      stuff_cmd("boot dsk3");                                                              <--- issue #452
      break;                                                                               <--- issue #452
                                                                                           <--- issue #452
    case 4:                                                                                <--- issue #452
      stuff_cmd("boot dsk4");                                                              <--- issue #452                                                          <--- issue #452
      break;                                                                               <--- issue #452
                                                                                           <--- issue #452
    default:                                                                               <--- issue #452
      break;                                                                               <--- issue #452
  }                                                                                        <--- issue #452
}                                                                                          <--- issue #452
#else
                if (cr_boot(0, NULL) != SCPE_OK)    /* load boot card */
                    remark_cmd("IPL failed");
#endif
            }
            break;
---------------------
```

**Comment by markpizz** [comment]
FYI.  The recent change adding the 'visible' reset really is no different than the prior logic which silently performed the same reset internally which didn't happen to be properly serialized with other activities in the simulator.

You've got too many changes here.  Please zip up your changed files (whole files are fine) and drop the zip file here.

**Comment by Jim-F** [comment]
> FYI. The recent change adding the 'visible' reset
> really is no different than the prior logic. . .

Yes, I saw that.  But the visible "reset" is striking,
anyway.

> You've got too many changes here. Please zip up your
> changed files. . .

Yes, OK.  The earlier long comment I posted here was actually not in #453 where
I intended it to be.  Although it also contained material related to #452.
#452 and #452 are sort of joined at the hip.

Changes for "issues" (enhancement requests, actually) 452 and 453:

452 - (allowing user to reboot the machine from the GUI by pressing
RESET, PROGRAM LOAD), and related issue. . .

453 - (using the switches to select a non-zero boot drive
and making use of FILE READY and DISK UNLOCKED indicators
to show whether the chosen drive is attached).

[changes_for_issues_452_and_453.ZIP](https://github.com/simh/simh/files/1020796/changes_for_issues_452_and_453.ZIP)
