### ISSUE TITLE
Ibm1130 (Windows GUI): card reader button is still active when simulation is running

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#454]
- #### Context
This is exactly the same issue, with the same symptoms, as issue #449
(with the lineprinter icon), except it's the card reader icon.  Should've checked this
before!  Anyway, I guess the fix is the same.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

![simh_version](https://cloud.githubusercontent.com/assets/17226010/26083675/2b44ac80-39a5-11e7-84f7-6a777f67c583.png)

- #### how you built the simulator or that you're using prebuilt binaries

![build_output](https://cloud.githubusercontent.com/assets/17226010/26083692/3ff47dc2-39a5-11e7-9595-ae7948b559e7.png)

- #### the simulator configuration file (or commands) which were used when the problem occurred.

set cpu 32k
set prt 1403
set cr 2501

;set gui off
;set throttle 100k
reset
delete printer.txt

att dsk0 dms.dsk

att prt printer.txt
boot dsk

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
The attach case was already well behaved.  In fact the logic there was used in the printer.  The card reader detach case needed to be handled the same way.  Check it now.
