### ISSUE TITLE
 Ibm1130 (Windows GUI): Suggestion to change drag & drop for SCP scripts

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#456]
- #### Context
In the existing code, there are two kinds of files that can be dragged and dropped onto
the GUI:  card decks, which can be dropped on the card reader icon; and SimH SCP
scripts, which can be dropped almost anywhere else that isn't a button.

This leads to the occasional embarrassment where you accidentally fumble a
file intended for the card reader before you've quite gotten there, near the
edge of the screen.  When this happens, your "card deck" is interpreted as
an SCP script, and a lot of junk comes out on the console.

So this got me thinking about the possibility of restricting the target for dragging
and dropping SCP scripts.

First of all, the code change required to do this turned out to be simpler than
it first appeared.

But there was also the question of **where** on the GUI to designate as the
new (smaller) target for SCP drops.  At first I thought the KEYBOARD button,
because it isn't used for anything else.  But then it occurred to me that the
PROGRAM LOAD button might be a better choice. For one thing, getting there
doesn't require passing over the card reader.  But the name "PROGRAM LOAD"
is also kind of logical.  The button would have a dual purpose -- if you use it
as a button, in the IMM STOP, CHECK RESET, PROGRAM LOAD sequence,
it might reboot DMS (as in another proposed modification).  As a target for
SCP drops, it LOADs scripts.

I realize this proposal may cross the boundary of respecting
the current documentation at ibm1130.org, and might be a change that
Brian Knittel wouldn't appreciate.  But I think I'm going to use it in
my local copy of the simulator whether or not it get adopted.

This is the changed code, in ibm1130_gui.c, function
static void accept_dropped_file (HANDLE hDrop)

```
-----------------------
    if ((hWndDrop = ChildWindowFromPoint(hConsoleWnd, pt)) == btn[IDC_1442].hBtn)
        cardreader = TRUE;           /* file was dropped onto 1442 card reader */

else if ((hWndDrop = ChildWindowFromPoint(hConsoleWnd, pt)) == btn[IDC_PROGRAM_LOAD].hBtn)       <--- new lines
 cardreader = FALSE;                 /* file was dropped onto PROGRAM_LOAD button */             <---

#if 0
    else if (hWndDrop == NULL || hWndDrop == hConsoleWnd)                                        <--- deleted lines
        cardreader = FALSE;          /* file was dropped onto console window, not a button */    <---
#endif
    else {
        MessageBeep(0);              /* file was dropped onto another button */
        return;
    }
-----------------------
```

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
Same as earlier today.
- #### how you built the simulator or that you're using prebuilt binaries

Same as earlier today.
- #### the simulator configuration file (or commands) which were used when the problem occurred.

Same as earlier today.
- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
> I realize this proposal may cross the boundary of respecting the current documentation at ibm1130.org

I think you could make the choice of SCP commands vs card deck based on the contents of the file that has been dropped.   The set of SCP commands is relatively small and with a couple of heuristics could easily make the right determination.

**Comment by Jim-F** [comment]
> I think you could make the choice of SCP commands vs card deck
> based on the contents of the file that has been dropped

You mean keep the larger screen area as the target for SCP drops, but
perform a behind-the-scenes analysis of the file and just ignore it if it
doesn't look like a genuine SCP file?  Yes, I guess that would work, if it could be done
reliably.

(Doing the inverse for the card reader -- having it reject SCP files -- might
not be possible.  Card readers are expected to swallow all sorts of things.)

**Comment by Jim-F** [comment]
> Yes, I guess that would work, if it could be done reliably.

Though it would be bloody annoying (for anybody who actually uses
the drag-n-drop facility for SCP files, rather than just the "do..." command
from the console) to have the heuristic misfire and ignore a script
for no apparent reason.    ("Artificial intelligence" strikes again.  ;-> )

**Comment by Jim-F** [comment]
> "Artificial intelligence" . . .

We could send the dropped file to the Cloud and let Watson decide.
Now **that** would be a retrocomputing first!

**Comment by markpizz** [comment]
This could be the flow:
1) Drag-n-Drop doesn't work at all unless the simulator is stopped (at the sim> prompt).  This is current behavior.
2) File analysis is performed
3) if outside of reader and NOT an SCP file, a message indicating garbage input is emitted in the console window OR it is merely ignored. with a Beep emitted.
4) if inside of reader and it is an SCP file, then a message indicating this is emitted AND it is processed as an SCP file.  If a user REALLY wants to pass a file containing SCP commands into the reader, they can always issue an explicit attach command in the console window at the sim> prompt

**Comment by Jim-F** [comment]
> 2. File analysis is performed

It occurred to me that a useful way to implement this might be as a generally-available
SCP capability -- a sim_try_command() function, or some such, that takes a string
and passes it to the command parser with the implication "don't actually execute this;
just tell me if it would be a legal command" (and then returns TRUE or FALSE).

**Comment by markpizz** [comment]
> It occurred to me that a useful way to implement this might be as a generally-available
SCP capability -- a sim_try_command() function, or some such, that takes a string
and passes it to the command parser with the implication "don't actually execute this;
just tell me if it would be a legal command" (and then returns TRUE or FALSE).

That more or less exists, see the latest code.

There may be trivial/minimal cases where a file could be either SCP commands or job input.  Someone more familiar with legit IBM1130 input syntax could identify these cases...

**Comment by Jim-F** [comment]
BTW, that earlier proposal I made to pick up dropped SCP files at the
PROGRAM LOAD button is no good in Windows 10.  Works in XP and 7,
but not in 10.  The existing drag-n-drop stuff works in 10 though.  I'll check
out the latest code.

**Comment by Jim-F** [comment]
No, not quite there.  It works fine for ASCII (or 029-format) SCP files and card decks,
but it thinks binary-format card decks are SCP files (the window-at-large sends them
to SCP, and the card reader throws up a message asking if you want to
process them as SCP files).

**Comment by markpizz** [comment]
Like I said, I was sure that the SCP detection logic might need some refinements.  

Please point me at cases which aren't correctly handled.

**Comment by Jim-F** [comment]
> Please point me at cases which aren't correctly handled.

OK, here's one.  This program needs a DMS configured to use the 1132 printer, which
is what the dms.dsk in the package from ibm1130.org is, and what I assume you're
testing with.  The card reader, by the way can be set to 029 or binary mode, but
the default is "automatic" which tries to figure out which is which by itself.

[lunar.ZIP](https://github.com/simh/simh/files/1006220/lunar.ZIP)

**Comment by Jim-F** [comment]
Oh, one other kind of file the SimH 1130 has to deal  with is the "deck file".
This is a kind of indirect file that specifies lists of other files to be processed
through the card reader, possibly interspersed with DMS command cards.

I've never used them, but I've cobbled together an example for you.

They're attached with the syntax, e.g.,  "attach cr @for.1132.deck" (to use
the name of the example deck I've supplied).

They cannot be used by dragging them to the card reader icon in the GUI,
though of course the current code does not reject such files when they
are dropped on either the card reader or the SCP target area, so they
just result in errors when they're misused in either of those ways.

Reliably filtering out these files so that they never lead to errors when
inappropriately dropped somewhere might be difficult (and a too zealous
attempt to do so might result in a filter that too often annoyingly rejects
files that **are** legitimate drops).

I suppose we could take the attitude that since the user has no legitimate reason to
drag and drop these "deck files" anyway, since they can only be used via
the SCP command line, then if they are accidentally dropped and produce errors,
then that's just too bad.

I still kind of wish there was a specific target for SCP drops, rather than "the rest
of the screen", but that's not how the GUI was designed.

[deck.ZIP](https://github.com/simh/simh/files/1006463/deck.ZIP)

**Comment by Jim-F** [comment]
> This could be the flow:
>
>  1. Drag-n-Drop doesn't work at all unless the simulator
>     is stopped (at the sim> prompt). This is current behavior.
>
>  2. File analysis is performed
>
>  3. if outside of reader and NOT an SCP file, a message
>     indicating garbage input is emitted in the console window
>     OR it is merely ignored. with a Beep emitted.
>
>  4. if inside of reader and it is an SCP file, then a message
>     indicating this is emitted AND it is processed as an SCP file.
>     If a user REALLY wants to pass a file containing SCP commands
>     into the reader, they can always issue an explicit attach command
>     in the console window at the sim> prompt

Here's an alternative suggestion.  When the simulator is stopped
and drag-n-drop is enabled:

1.  If a file is dropped on the reader, don't perform any analysis,
    don't issue any messages.  Just take it.

2.  If a file is dropped in the SCP area (anywhere else but the reader),
    check a line or two to see if it looks like a legitimate SCP file.
    If so, send it to the SCP.  Otherwise:

3.  If a file is dropped in the SCP area and it **doesn't** look like
    a legitimate SCP file, then **just send it to the card reader**.
    Don't issue any error messages.

This takes care of the situation that caused me to make this an issue
in the first place -- trying to drag a file to the card reader,
"missing" it, inadvertently dropping the file on the edge of the window.
and having a card deck sent to the SCP.

We'd just be reversing the behavior in case of a fumble like this --
if you "miss" the card reader, the drop would be treated
as though it were intended for the card reader
unless analysis shows it's likely to be an SCP script.

The error messages aren't really necessary -- they're just an additional
annoyance.  It's pretty obvious if you've sent something
(whether inadvertently or not) to either the card reader or the SCP.

**Comment by Jim-F** [comment]
> This could be the flow:
>
>  1. Drag-n-Drop doesn't work at all unless the simulator
>     is stopped (at the sim> prompt). This is current behavior.
>
>  2. File analysis is performed
>
>  3. if outside of reader and NOT an SCP file, a message
>     indicating garbage input is emitted in the console window
>     OR it is merely ignored. with a Beep emitted.
>
>  4. if inside of reader and it is an SCP file, then a message
>     indicating this is emitted AND it is processed as an SCP file.
>     If a user REALLY wants to pass a file containing SCP commands
>     into the reader, they can always issue an explicit attach command
>     in the console window at the sim> prompt

Here's an alternative suggestion.  When the simulator is stopped
and drag-n-drop is enabled:

1.  If a file is dropped on the reader, don't perform any analysis,
    don't issue any messages.  Just take it.  This is current behavior.

2.  If a file is dropped in the SCP area (anywhere else but the reader),
    check a line or two to see if it looks like a legitimate SCP file.
    If so, send it to the SCP.  Otherwise:

3.  If a file is dropped in the SCP area and it **doesn't** look like
    a legitimate SCP file, then **just send it to the card reader**.
    Don't issue any error messages.

This takes care of the situation that caused me to make this an issue
in the first place -- trying to drag a file to the card reader,
"missing" it, inadvertently dropping the file on the edge of the window.
and having a card deck sent to the SCP.

We'd just be reversing the behavior in case of a fumble like this --
if you "miss" the card reader, the drop would be treated
as though it were intended for the card reader
unless analysis shows it's likely to be an SCP script.

The error messages aren't really necessary -- they're just an additional
annoyance.  It's pretty obvious if you've sent something
(whether inadvertently or not) to either the card reader or the SCP.

**Comment by markpizz** [comment]
Indirect Deck files can be indicated during a drop in the GUI by holding the SHIFT key while dropping into the card reader.  Forgetting to hold the SHIFT key would be the user's problem.

> The error messages aren't really necessary -- they're just an additional
annoyance. It's pretty obvious if you've sent something
(whether inadvertently or not) to either the card reader or the SCP.

Well, something is going to issue some (or possibly many) error messages, 
while the simple interactive one that has already been correctly determined 
is really the problem.

Give the latest code a try.

**Comment by Jim-F** [comment]
> Well, something is going to issue some (or possibly many) error messages,
> while the simple interactive one that has already been correctly determined
> is really the problem.

By "error messages" I meant the Windows BONK and the message box
popping up "Ignoring Invalid SCP command file. . ." that you then
have to click OK on.

Do you think that punishment is really necessary?  Wouldn't it be
better just to assume at that point that the file was actually
intended for the card reader and just redirect it there without comment?
After all, the card reader is the only other place it could have been intended for
as the destination of a drag-n-drop.

As for the inverse scenario -- dropping a binary deck on the card reader
and getting a BONK and a message box "Process '.....' as SCP commands?"
OK/CANCEL -- that's really **terrible**.  It means that every time you want
to use the GUI to run a binary job (which is a perfectly legitimate
thing) you now have to put up with a BONK and click something to confirm
that's what you really want to do.  In any case, in the latest github
download, clicking CANCEL at this point apparently doesn't mean "No, I really
did mean the card reader" so that means that now you can't process a
binary job **at all** from the GUI.  So that's actually broken now.

I think I'd rather keep the current behavior -- having the invalid
SCP file produce a screenful of (silent) error messages on the console --
rather than having BONKs and message boxes that have to be dismissed.

But if we're going to change it at all, let me reiterate the suggestion
that I woke up with this morning:

1.  If you accidentally drop a file that **doesn't** contain SCP
commands on a part of the window that isn't the card reader
(like the edge of the window to the right of the card reader)
then just redirect the file to the card reader without comment.

2.  If a file gets dropped on the card reader, don't "analyze"
it **at all** -- just believe the user's intention and have the card
reader accept it.  Let the 1130 and DMS worry about that mistake,
if it is a mistake.

I think that would give the smoothest experience.

**Comment by markpizz** [comment]
> As for the inverse scenario -- dropping a binary deck on the card reader
and getting a BONK and a message box "Process '.....' as SCP commands?"
OK/CANCEL -- that's really terrible. It means that every time you want
to use the GUI to run a binary job (which is a perfectly legitimate
thing) you now have to put up with a BONK and click something to confirm
that's what you really want to do. In any case, in the latest github
download, clicking CANCEL at this point apparently doesn't mean "No, I really
did mean the card reader" so that means that now you can't process a
binary job at all from the GUI. So that's actually broken now.

Have you tried the latest code?  Please do, and then comment.

It would seem that given reliable detection of SCP command files (which this iteration is better at), then it would hard to imagine that a user would prefer feeding garbage into either SCP or the card reader and then having to interpret oddball error messages (or conditions) from either SCP or the running system.

**Comment by Jim-F** [comment]
> Have you tried the latest code? Please do, and then comment.

Yes, of course I've been using the latest code!
(git commit id: d9cc6636)

Unless it's changed again in the past 2 1/2 hours, I'm using
the latest code now.  (In fact, I suspect I've downloaded new
code and rebuilt the executable several times -- unnecessarily --
since the last time anything changed.)

> It would seem that given reliable detection of SCP command files
> (which this iteration is better at), then it would hard to imagine
> that a user would prefer feeding garbage into either SCP or the
> card reader and then having to interpret oddball error messages
> (or conditions) from either SCP or the running system.

Reliable detection of SCP command files is fine.

That means that if a user is trying to load the card reader and
inadvertently drops the file onto the SCP area, the reliable detection
can happen and then, if the file is clearly **not** an SCP file,
it can be silently and conveniently redirected to the card reader.  This is the most
common operational error case -- because of the location of the card reader icon
on the screen, it often happens (to me, at least) that when I'm trying
to get a file to the card reader and I don't quite make it,
the file lands on the edge of the window to the right of the card
reader icon (in an SCP drop area).  I don't think there should be any BONKs or
Windows message boxes to dismiss at this point -- it's just unnecessary
punishment.

It is much less likely that a user will inadvertently drop an
SCP file onto the card reader, so I don't see it as necessary
to do any kind of analysis of those drops.  If you accidentally drop
an SCP file onto the card reader, you'll see the reader fill up,
and you can double-click on the card reader icon to correct your mistake.
You don't need a BONK and a Windows message box instead.

Also, false rejections of files the user wants to drop onto the
card reader make the GUI **extremely** unpleasant to use.
And binary card files **are** getting falsely rejected by the
reader right now.

![binary_rejection](https://cloud.githubusercontent.com/assets/17226010/26174596/ec50e79e-3b1d-11e7-9856-8f06e633a56d.png)

**Comment by markpizz** [comment]
Oops.  I missed a step pushing my changes to github.  We were talking past each other.  The code I just pushed out there doesn't falsely detect any case I tried as SCP commands.

**Comment by Jim-F** [comment]
OK, this version (1cf4f779) seems to have fixed the rejection of binary card
files by the card reader.

I still think it's unnecessarily unfriendly with the BONKs and error message boxes,
but you're the gatekeeper, and if you say that's the way it's going to be, then I guess
that's the way it's going to be.

Can I persuade you to compromise halfway on this, and at least send fumbled
card files to the lineprinter, rather than doing the BONK?

If you want to continue to have the lineprinter reject files that look like SCP files,
that's fine with me (as long as they're not false rejections).  I'd just as soon
use "do" from the command line for SCP scripts anyway.

Let me know.  If you're adamant that it has to work this way, I'll close the issue.

**Comment by markpizz** [comment]
>Can I persuade you to compromise halfway on this, and at least send fumbled
card files to the lineprinter, rather than doing the BONK?
>
> If you want to continue to have the lineprinter reject files that look like SCP files,
that's fine with me (as long as they're not false rejections). I'd just as soon
use "do" from the command line for SCP scripts anyway.

You mean card reader NOT lineprinter, in the above questions, right?

In any case, I think I've just made the questions/prompts that are asked a little more 
natural to indicate that an unreasonable action has been performed, and to allow
the user to control what actually happens.  That seems much more natural than
merely allowing "Garbage In" to produce "Garbage Out".

**Comment by Jim-F** [comment]
Yes, that's a reasonable compromise -- giving the user a chance to correct the mistake
without starting over.  I'll go ahead and close this.
