### ISSUE TITLE
i1620: Invalid instruction message displays bad opcode incorrectly

### ISSUE THREAD

**Issue by TomMcBride** [simh/simh#458]
1620 opcodes are two digits long and stored in a pair of characters. This error message correctly notes what's wrong, displays the correct value for the PC but displays the hex content of only the first of the two digits. In my example below I have stored digits 8 and 7 into locations 0 and 1. Opcode 87 is not valid and it produces this error message when executed. The opcode should display as 87 instead of 08. 

The code that displays this message is in function fprint_stopped_gen in scp.c at line 6897. I don't understand Simh (or the C language) well enough to fix this. I don't think it's very hard. Here is the output I get from my example:

IBM 1620 simulator V4.0-0 Beta        git commit id: 7317645d
sim> de 0 8
sim> de 1 7
sim> go 0

Invalid instruction, PC: 0 (08)
sim> 

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
sim> show version
IBM 1620 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 4
    Host Platform:
        Compiler: GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)
        Simulator Compiled as C arch: x64 (Release Build) on May 10 2017 at 09:53:56
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin Thomass-MacBook-Pro.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
        git commit id: 7317645d
- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by archivisth** [comment]
Actually, it's doing what it's supposed to - print the memory cell pointed to by the PC when it is unable to parse the instruction.

I think this can be fixed, because a unique identifier (SIM_SW_STOP) is passed in for this case only. So instead of reporting failure, it could print the opcode in decimal and return success. I'll take a look at it.

**Comment by archivisth** [comment]
Change submitted. This issue can be closed.
