### ISSUE TITLE
 Ibm1130: Enable static linking with MinGW pthreads

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#466]
- #### Context

Linking ibm1130.exe (or presumably any SimH executable) against MinGW-provided
pthreads pulls in dependencies on pthreadGC-3.dll and  libgcc_s_dw2-1.dll
(or on libwinpthread-1.dll with MinGW-w64).

This can be remedied in the makefile:

```
--------------
777  #Win32 Environments (via MinGW32)

. . .

799  # Give preference to any MinGW provided threading (if available)
800  ifneq (,$(call find_include,pthread))
801  PTHREADS_CCDEFS = -DUSE_READER_THREAD
802    ifeq (,$(NOASYNCH))
803      PTHREADS_CCDEFS += -DSIM_ASYNCH_IO 
804    endif
805    PTHREADS_LDFLAGS = -static -lpthread               <--- add the "-static" here
806  else. . .
--------------
```

And (in conjunction with the fix for the plotter DLLs) eliminates any dependency
on DLLs for a Windows build (via MinGW).
- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by Jim-F** [comment]
This, of course, only comes up if you're building with async support
(which is now possible once again, if not particularly useful for the
IBM 1130).

**Comment by markpizz** [comment]
The addition of -static breaks the build for other simulators (which use SDL).

**Comment by Jim-F** [comment]
OK, then I'll close this.  It might be nice, though, to add a comment to the makefile
to the effect that if you're **not** using SDL, you can add "-static" in order to
avoid the DLL dependency if you want.
