### ISSUE TITLE
Ibm1130 (Windows GUI): APL CON-TELNET terminal loses focus

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#467]
- #### Context
When running APL\1130 (which switches keyboard input to a telnet-connected
HyperTerminal terminal emulator), the terminal program loses focus on every keystroke.

I believe this must've happened when we made the change
to switch focus back to to the cmd.exe console after every button push in the GUI
(issue #450).  It would seem that the CON-TELNET terminal
is being treated the same way as the GUI, and loses focus after every
"button push" (keystroke).

At any rate, git commit id 4df0a9fb (5/14) works properly,
and starting with git commit id 22efe758 (5/15) it's broken.  (Note: APL
still works, but you have to click the terminal title bar before
typing every keystroke).

I guess a quick fix to this would be to disable the focus shifting altogether
if a CON-TELNET connection is active; a fancier (but maybe unnecessary)
solution would be to switch focus back to the **terminal window** (an
external program), not the cmd.exe console, after each button push.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Please provide a configuration file (and data files if necessary) that I can use to reproduce the problem.

**Comment by markpizz** [comment]
Never mind about providing the reproducing case.
