### ISSUE TITLE
I1620: ARSTOP should default to 0

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#471]
The 1620 has three console switches that control whether the CPU stops on certain error conditions.  They are 

(a) PARITY                  ...in memory
(b) I/O                         ...parity or translation error
(c) O'FLOW                 ...arithmetic overflow

The operating instructions for virtually all vintage 1620 programs, including assemblers, compilers, interpreters, and diagnostics, indicate that the switches should be set to STOP, STOP, and PROGRAM, respectively.  That is, the program handles overflow itself, sometimes by simply ignoring it.

See page 52 in the attached 1620 Data Processing System Reference Manal. 
[A26-4500-2_1620ref_Jul61.pdf](https://github.com/simh/simh/files/1064743/A26-4500-2_1620ref_Jul61.pdf)

Here is a code snippet, with context:
i1620_cpu.c
~~~
uint32 io_stop = 1;                                     /* I/O stop */
uint32 ar_stop = 0;                                     /* **CHANGED** arith stop */
uint32 cpuio_inp = 0;                                   /* IO in progress */
~~~

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by archivisth** [comment]
Seems harmless enough, but configuring the machine is what .ini files are for...

**Comment by DaveWise2** [comment]
That would work too, but just about everybody has to do it.  Even the basic diagnostic program, CU01, requires it, and isn't that the program originally used to test I1620?

**Comment by archivisth** [comment]
There's a way to handle this already without breaking backward compatibility. I've already had complaints about deferred IO breaking another user's workflow. So please use the existing capabilities of the simulator to customize startup conditions to your liking.

**Comment by DaveWise2** [comment]
Okay.

**Comment by DaveWise2** [comment]
I hear that Mark's change to revert to stock delay behavior when CPS == 0 took care of that complaint.
