### ISSUE TITLE
I1620: Fix error message on card punch

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#472]
On a card punch error, "CDR I/O error" is printed.  Should be CDP.
Code snippet in cdp_write():
~~~
if (ferror (cdp_unit.fileref)) {                        /* error? */
    ind[IN_WRCHK] = 1;
    sim_perror ("CDP I/O error");         /* **CHANGED** */
    clearerr (cdp_unit.fileref);
    return SCPE_IOERR;
    }
return SCPE_OK;
~~~

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by archivisth** [comment]
Well, it's right in 3.X...

```
if (ferror (cdp_unit.fileref)) {                        /* error? */
    ind[IN_WRCHK] = 1;
    perror ("CDP I/O error");
    clearerr (cdp_unit.fileref);
    return SCPE_IOERR;
    }
```

**Comment by archivisth** [comment]
This should be closed.

**Comment by DaveWise2** [comment]
Done.  Thanks!
