### ISSUE TITLE
I1620: IO is throttled to inconvenient speed

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#474]
Setting the instruction rate somewhat consistent with real-world CPU performance (5KIPS, i.e. `set throttle 50/10`) causes IO to go much faster or slower than reality.
(I am not advocating 10cps tty, even though that is real.)

(Disclaimer: I understand that strict realism is not a goal of SIMH.  But convenience should be, and if throttling is used, it is used for one of two reasons, first, to reduce host system load, and second, to approximate realistic target performance.  I'm addressing the latter.)

- #### Context

[CU01.PT.txt](https://github.com/simh/simh/files/1064789/CU01.PT.txt)

Current behavior.

 a. Paper tape input is throttled, about 1% of stated rate
~~~
IBM 1620 simulator V4.0-0 Beta        git commit id: c389573c
sim> set throttle 50/10
sim> att ptr cu01.pt   ; 19977 chars
sim> d 0 rnpt 24
sim> d 12 b 14004
sim> g 0
/* 6m 40s pass, or about 50 char/s, should be 150+, I suggest.. */
/* .. 10% of rate or 500 */

START ROUTINES. ETOS FOLLOW.
Overflow check, PC: 6252 (A    06233,06239)
sim>
~~~

 b. Tty output is throttled, about 1% of stated rate
~~~
IBM 1620 simulator V4.0-0 Beta        git commit id: c389573c
sim> set throttle 50/10
sim> d 0 dnty 0
sim> d 12 h
sim> g 0
/* IO proceeds at 50 char/s, ^E interrupts successfully */
/* This is a comfortable speed */
35000000010048000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000001020304000204060800030609021004080216
IO in progress
Simulation stopped, PC: 12 (H   )
sim>
~~~

 c. Tty input is throttled, about 0.02% of stated rate
~~~
IBM 1620 simulator V4.0-0 Beta        git commit id: c389573c
sim> set throttle 50/10
sim> d 0 rnty 1000
sim> d 12 h
sim> g 0
>1234512345
/* typewriter input echoed at 1 char/s, should be 10+ */
/* then hit ^E */
IO in progress
Simulation stopped, PC: 12 (H   )
sim> set cpu release
IO operation canceled
sim>
~~~

Recommended behavior:
    PTP: 100, i.e.  50cps at 5KIPS
    PTR: 10,  i.e. 500cps at 5KIPS
    TTO: 100, i.e.  50cps at 5KIPS
    TTI: 100, i.e.  50cps at 5KIPS

With these changes and `set throttle 50/10`, SIMH produces a fairly realistic 1620 experience, erring on the side of convenience.

i1620_pt.c
~~~
UNIT ptr_unit = {
    UDATA (&ptr_svc, UNIT_SEQ+UNIT_ATTABLE+UNIT_ROABLE, 0), 10      /* 500cps at 5KIPS */
    };
UNIT ptp_unit = {
    UDATA (&ptp_svc, UNIT_SEQ+UNIT_ATTABLE, 0), 100                 /* 50cps at 5KIPS */
    };
~~~
i1620_tty.c
~~~
UNIT tty_unit[] = {
    { UDATA (&tti_svc, 0, 0), 100 },        /* 50cps at 5KIPS */
    { UDATA (&tto_svc, 0, 0), 100 }         /* 50cps at 5KIPS */
    };
~~~

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

IBM 1620 simulator V4.0-0 Beta        git commit id: c389573c
sim> show version
IBM 1620 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 4
    Host Platform:
        Compiler: Microsoft Visual C++ 18.00.40629.00
        Simulator Compiled as C arch: x86 (Debug Build) on Jun  7 2017 at 09:30:
16
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 6.1.7601]
        Architecture: x86 on AMD64, Processors: 36
        Processor Id: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel, Level:
 6, Revision: 3f02
        git commit id: c389573c
sim>
- #### how you built the simulator or that you're using prebuilt binaries

Local build using Microsoft Visual Studio 2013
- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Give this a try for the ptp/ptr:
```
diff --git a/I1620/i1620_pt.c b/I1620/i1620_pt.c
index f4b5c0e..8eb92cc 100644
--- a/I1620/i1620_pt.c
+++ b/I1620/i1620_pt.c
@@ -48,4 +48,6 @@
 #define PT_FD   0x7F                                    /* deleted */
 
+#define PTP_PTR_CPS 50                                  /* Characters Per Second */
+
 static uint32 ptr_mode = 0;                             /* normal/binary */
 static uint32 ptp_mode = 0;
@@ -74,5 +76,5 @@ t_stat ptp_num (void);
 
 UNIT ptr_unit = {
-    UDATA (&ptr_svc, UNIT_SEQ+UNIT_ATTABLE+UNIT_ROABLE, 0), SERIAL_IN_WAIT
+    UDATA (&ptr_svc, UNIT_SEQ+UNIT_ATTABLE+UNIT_ROABLE, 0), PTP_PTR_CPS
     };
 
@@ -80,5 +82,5 @@ REG ptr_reg[] = {
     { FLDATA (BIN, ptr_mode, 0) },
     { DRDATA (POS, ptr_unit.pos, T_ADDR_W), PV_LEFT },
-    { DRDATA (TIME, ptr_unit.wait, 24), PV_LEFT },
+    { DRDATA (CPS, ptr_unit.wait, 24), PV_LEFT },
     { NULL }
     };
@@ -100,5 +102,5 @@ DEVICE ptr_dev = {
 
 UNIT ptp_unit = {
-    UDATA (&ptp_svc, UNIT_SEQ+UNIT_ATTABLE, SERIAL_OUT_WAIT)
+    UDATA (&ptp_svc, UNIT_SEQ+UNIT_ATTABLE, 0), PTP_PTR_CPS
     };
 
@@ -106,5 +108,5 @@ REG ptp_reg[] = {
     { FLDATA (BIN, ptp_mode, 0) },
     { DRDATA (POS, ptp_unit.pos, T_ADDR_W), PV_LEFT },
-    { DRDATA (TIME, ptp_unit.wait, 24), PV_LEFT },
+    { DRDATA (CPS, ptp_unit.wait, 24), PV_LEFT },
     { NULL }
     };
@@ -268,5 +270,5 @@ if (cpuio_cnt >= MEMSIZE) {                             /* over the limit? */
     return STOP_RWRAP;
     }
-sim_activate (uptr, uptr->wait);                        /* sched another xfer */
+sim_activate_after (uptr, 1000000/uptr->wait);          /* sched another xfer */
 if ((uptr->flags & UNIT_ATT) == 0)                      /* not attached? */
     return SCPE_UNATT;
@@ -425,5 +427,5 @@ if ((cpuio_opc != OP_DN) && (cpuio_cnt >= MEMSIZE)) {   /* wrap, ~dump? */
     return STOP_RWRAP;
     }
-sim_activate (uptr, uptr->wait);                        /* sched another xfer */
+sim_activate_after (uptr, 1000000/uptr->wait);          /* sched another xfer */
 if ((uptr->flags & UNIT_ATT) == 0)                      /* not attached? */
     return SCPE_UNATT;

```

**Comment by DaveWise2** [comment]
Thanks, Mark.  I see where you're going and I like it.  (Except ptr needs to be faster; at 50cps you die of old age.  :)  I hacked it to 500.)  I'll try it this weekend.

**Comment by DaveWise2** [comment]
I spoke too soon.  I didn't see, and it doesn't work well.  Your proposed change gives realistic IO when throttle is disabled, but when throttle is enabled, the IO speed scales downward with throttled CPU speed, so if the CPU is 5KIPS, IO is "die of old age".  Although there's something to be said for independent speed settings on the CPU and the various IO's, a single dial controlling all is a Good Thing too, just in a different way that's more convenient for casual use.

We're supposed to be shutting down, I may be out of contact until tomorrow.

**Comment by DaveWise2** [comment]
`sim_activate (uptr, 5000/uptr->wait);                   /* sched another xfer */` will scale a unit.wait that was specified in CPS so that it gives the stated IO CPS when CPU is 5KIPS.

**Comment by markpizz** [comment]
What I provided changed sim_activate() calls from sim_activate_after().  You got that, right?

If that doesn't produce consistent results (independent of throttling) then I've got a different problem to look at.  I'll let you know what I find.

**Comment by DaveWise2** [comment]
Right, results using sim_activate_after() depended on the throttle setting.

**Comment by markpizz** [comment]
There definitely is a general problem rate limiting things when throttling with insts/msecs.  I'm working on a fix.

Three knobs or one is a subtlety once the basics work.

**Comment by markpizz** [comment]
OK, please try the above suggested CPS change with the latest code.  It should provide CPS data delivery correctly independent of throttling mode.

**Comment by DaveWise2** [comment]
I got interesting results.  It seems to work as advertised for many throttle settings, but when set very slow it gets wedged.  Here is a session transcript.  I boosted ptp to 5000cps to get quick results.  For most of the settings I tried (nothrottle, 50/1, 50/5, 50/10, 5k), ptp output goes at 5000cps, but when I set 20/10 or 2k, the IO goes partway then wedges.  Breaking in with Visual Studio shows that ptp_svc() is no longer being called, only sim_timer_tick_svc(), sim_throttle_svc(), and tti_svc().

I got similar results with ptr - fast and medium worked, slow did not.
~~~

IBM 1620 simulator V4.0-0 Beta        git commit id: c389573c
sim> cd c:\temp
sim> e ptp cps
CPS:    50
sim> d ptp cps 5000
sim> d 0 dnpt 0
sim> d 12 h
sim> att ptp junk
sim> g 0
/* Four seconds pass */

HALT instruction, PC: 24 (00)
sim> g 0
/* Four seconds pass */

HALT instruction, PC: 24 (00)
sim> set throttle 50/1
sim> g 0
/* Four seconds pass */

HALT instruction, PC: 24 (00)
sim> g 0
/* Four seconds pass */

HALT instruction, PC: 24 (00)
sim> set throttle 50/5
sim> g 0
/* Four seconds pass */

HALT instruction, PC: 24 (00)
sim> set throttle 50/10
sim> g 0
/* Four seconds pass */

HALT instruction, PC: 24 (00)
sim> e par
PAR:    20000
sim> g 0
/* Four seconds pass */

HALT instruction, PC: 24 (00)
sim> set throttle 20/10
sim> g 0
/* Long time passes, press ^E */

IO in progress, PC: 0 (DNPT 00000)

Simulation stopped, PC: 12 (H   )
sim> e par
PAR:    799
sim> g
/* Long time passes, press ^E */

IO in progress, PC: 0 (DNPT 00000)

Simulation stopped, PC: 12 (H   )
sim> e par
PAR:    799
sim> show queue
IBM 1620 event queue status, time = 50613000, executing 31,490 instructions/sec
  TTY unit 0 at 100 (3.176 msecs)
sim>
~~~

**Comment by markpizz** [comment]
This was an excellent test case that reliably detected an edge condition logic error in the timer scheduling.  I believe it has now been fixed,

**Comment by DaveWise2** [comment]
I'm delighted you found it, Mark.

In case my position is unclear, I prefer all speeds to change together with THROTTLE.  It's neat to have individual knobs, but I would always twist them all in sync, to maybe three positions, maximum, realistic, and somewhere in between that's obviously semi-realistic but fast enough to get in two runs between shaves.  :)

**Comment by DaveWise2** [comment]
Works.  There are still odd interactions between throttle and CPS, but that's out of scope here.  Straight throttle behaves the same on local console and telnet console.

**Comment by DaveWise2** [comment]
Oops that comment was meant for a different issue, sorry.

**Comment by DaveWise2** [comment]
Mark just indicated that this is indeed where he'd like to discuss the throttle/CPS interaction.
To summarize, I see correct behavior when either throttle or CPS is used, but when both are active, the actual IO speed is affected by both settings.  For example, if ptr or ptp is set to 10000cps, adding a throttle setting of 1/1 or 100/100 (effectively 1KIPS) reduces the actual speed to about 1000cps.  I've been modeling the numerical resemblance between 1KIPS and 1000cps as a coincidence, but I could be wrong - it's possible that the actual model for IO speed is MIN(KIPS,CPS).  I imagine we can devise experiments to determine the truth.

**Comment by markpizz** [comment]
> I've been modeling the numerical resemblance between 1KIPS and 1000cps as a coincidence, but I could be wrong - it's possible that the actual model for IO speed is MIN(KIPS,CPS). 

Actually, MIN(CyclesPerSecond, CharactersPerSecond) is the upper bound for deferred character I/O.  

This bound is true without regard to throttling.  Throttling to slow speeds makes this limit obvious, but the limit exists due to the fact that with deferred I/O each character's processing is performed in the context of an internal scheduled event.  The simh scheduling model limits a particular device to be scheduled at most once per Cycle, hence the bound.

**Comment by DaveWise2** [comment]
I think it's really MIN(CyclesPerSecond/TIME, CharactersPerSecond), because

~~~
d ptp time 100
d ptp cps 20
set throt 100/100 /* 1KIPS */
d 0 dnpt 19900
d 12 h
g 0
~~~

finishes in about five seconds instead of ten.

**Comment by markpizz** [comment]
When CPS is non zero, TIME is never referenced.  Prove that to yourself by running with the attached command file.
[ptp.zip](https://github.com/simh/simh/files/1103227/ptp.zip)

**Comment by DaveWise2** [comment]
I get it.  So my example above took five seconds not because CPS < (1000 cycles/second * 0.1 seconds/cycle), but because CPS != 0 .  Right?

**Comment by markpizz** [comment]
Not really knowing anything about the 1620 machine, I don't know exactly how many characters will be processed by:

```
d 0 dnpt 19900
d 12 h
```

But at 20 CPS, 5 seconds would imply that there was 100 characters involved.

CPS will have an effect when it is non-zero and when that happens, it MIGHT be the limit on deferred I/O rate if the execution rate (CyclesPerSecond) exceeds the specified CPS value.  The CyclesPerSecond is influenced by the host system execution speed and/or the rate controlled by throttling.

**Comment by DaveWise2** [comment]
Quite right, Mark.  `dnpt 19900` will output ram[19900-19999].   Even though it's a short sample, it's consistent with ptp.ini .

**Comment by markpizz** [comment]
So, now that the mechanisms/behaviors are clear can we close this?

**Comment by DaveWise2** [comment]
Yes.  And thanks.
