### ISSUE TITLE
I1620: Conflict between D/E CPU IAE and "IA" switch in SET/SHOW CPU

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#475]
Why was IAE added to the CPU registers?  There is already an IA switch in SET CPU.  And you can set one one way and the other the other way.  What will the CPU do?

~~~
sim> show cpu
CPU
        60KB, IA, EDT
        DIV, no IDX, no BIN
        no FP, RM disallowed, Model 1
sim> e cpu iae
IAE:    0
sim>
~~~

If IAE and IA are supposed to be the same thing, then they need to change in sync; or, if IAE is just an indicator of the IA state, it should be read-only.

If there's a good reason to keep IAE, the descriptive text needs a small change.

~~~
sim> help cpu
CPU help

CPU device SET commands:

set CPU IA                      enable indirect addressing
set CPU NOIA                    disable indirect addressing
[snip]

The CPU device implements these registers:

  PC          16
[snip]
  IAE          1  indirect address enable (Model 2 only)
  IDXE         1  indexing enable (Model 2 only)
  IDXB         1  indexing band select (Model 2 only)
  INDMAX      16
  PCQ[0:63]   14
  WRU          8  interrupt character
The default breakpoint type is: -E
sim>
~~~

The description for IAE implies that Indirect Addressing is a Model 2-only feature.  This is not so.  It is an optional feature in Model 1 CPUs, which is why SIMH has an enable/disable switch for it.  It is a standard feature on Model 2 CPUs, and after `SET CPU MOD2`, IA is not disableable.

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

~~~
sim> show version
IBM 1620 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 4
    Host Platform:
        Compiler: Microsoft Visual C++ 18.00.40629.00
        Simulator Compiled as C arch: x86 (Debug Build) on Jun 22 2017 at 15:01:38
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 6.1.7601]
        Architecture: x86 on AMD64, Processors: 36
        Processor Id: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel, Level: 6, Revision: 3f02
        git commit id: a93078ce
sim>
~~~

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Just to clarify, the help information that David is quoting above, comes from the i1620_doc.doc.  So, that should be changed as part of resolving this and I'll reflect the changes to i1620_doc.doc in the 4.X REGister and MTAB descriptions.

**Comment by archivisth** [comment]
The reason for iae is that in a Model 2, indirect addressing (and indexing) can be turned off and on by the program. Thus, the IA option indicates whether it is part of the CPU (optional in Model 1, always present in Model 2), while iae indicates whether it is currently on or off. Thus, for a Model 2, it needs to be read/write.

It is not controllable in a Model 1, so it should just be ignored. Register displays are the same for Model 1 and Model 2.

Close this issue, please, and don't change the documentation.

**Comment by markpizz** [comment]
Would it be reasonable to update the documentation to add the above explanation?

**Comment by DaveWise2** [comment]
It seems to me that if someone as smart as Mark got the wrong idea from the doc, the doc ought to be changed.

Bob, thanks for the explanation.  I've never studied Model 2 and had no idea there was program control over IA enable.  I see it now, it's BS (Branch and Select) with Q11 = 8 or 9.

My only brush with controlling IA was in 1979 when I tried out SP-007, the One-Pass SPS assembler.  It crashed.  Turned out it used a flag in P6 or Q11 to indicate some status in the program.  Must have been written before IA became a feature.  I wired up a little hack to disable it, using a relay and a spare console switch and lamp.  It's still there.

**Comment by markpizz** [comment]
David,

Don't credit me with any particular smartness in this domain.  I was merely transcribing the info in the doc's register list into the simulator's source code.  I have absolutely no detailed knowledge of the 1620's capabilities.  Bob, yourself and others are the experts in this domain.  The question you raised merely suggests that the answer should probably be documented...

- Mark
