### ISSUE TITLE
I1620: Subsequent Ptr EOF displays "Invalid character" instead of "PTR end of file"

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#476]
Second and subsequent Ptr EOF displays "Invalid character" instead of "PTR end of file".
Throttle/CPS doesn't matter.  RESET CPU clears it temporarily.
 
~~~
sim> reset cpu
sim> att ptr cu01.pt
/* It can be any tape */
/* It can even be alpha if you use rapt instead of rnpt */
sim>d 0 rnpt 24
sim>d 12 b 0
sim> g 0
/* Reads until EOF */
PTR end of file
 
IO in progress
 
End of file, PC: 12 (B    00000)
sim> att ptr cu01.pt
sim> set cpu rel
IO operation canceled
sim> g 0
/* Reads until EOF again but emits wrong error */
 
Invalid character, PC: 12 (B    00000)
sim>
/* "reset cpu" will straighten it out again but only for one run */
~~~

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

~~~
sim> show version
IBM 1620 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 4
    Host Platform:
        Compiler: Microsoft Visual C++ 18.00.40629.00
        Simulator Compiled as C arch: x86 (Debug Build) on Jun 22 2017 at 15:01:38
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 6.1.7601]
        Architecture: x86 on AMD64, Processors: 36
        Processor Id: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel, Level: 6, Revision: 3f02
        git commit id: a93078ce
sim>
~~~
- #### how you built the simulator or that you're using prebuilt binaries

Local build using Microsoft Visual Studio 2013 but it does it with prebuilt too starting with 2017-06-06.
(Note: To avoid dying of old age with the 2017-06-13 build, `d ptr cps 20000`.)

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by archivisth** [comment]
The end of file condition is setting the read check indicator.  It shouldn't. Because you used GO and not RUN, the indicator doesn't get cleared.

It looks like the simulator is altogether too generous in setting RDCHK and WRCHK. The 1620 manual says they get set only on parity errors. The simulator sets them on almost any device error, including end of file, unattached, bad parity, invalid characters from memory, and so on.

It would help if you could see whether RDCHK and WRCHK get set for anything else other than parity errors. For example, what happens if you try to punch an invalid digit or character from memory?

**Comment by DaveWise2** [comment]
My guess is that since the 1620 is not capable of emitting a non-character or one with bad parity unless the PARITY and IO switches are off (something rarely done except for diagnostics), IBM didn't bother to specify, and it would be a safe and reasonable approximation to set RDCHK/WRCHK on parity and invalid char but not on EOF/unattached/deverr.  EOF/unattached should be treated as "no media" which is not an error and which can be rectified, and other device errors are outside the scope of a real 1620 so SIMH can do what it likes.

This is what a real 1620 does, bear with me, read to the end:
(a) TTO of bad parity gives you the character plus centerstrike plus WRCHK,
but the only way to get bad parity on the IO bus is bad parity in ram (which SIMH does not simulate),
or hardware malfunction, or non-character;
(b) TTO of non-character that happens to achieve good IO parity gives you Cyrillic "Zha", plus WRCHK;
(c) It's hard to predict whether you will get A, B, or both simultaneously, which means that
SIMH can choose ad libitum;
(d) Except for one special case I will have to research.  There's a "One-Armed Bandit" program (1620-11.0.011 and 1620-11.0.002) that is run with IOSTOP off to allow it to generate Zha on purpose;
(e) TTI of non-character (e.g. alpha during RNTY) gives RDCHK and puts unspecified garbage in ram;
(f)  EOF/unattached on ptr and cdr gives READER NOT READY (but not RDCHK), and attaching will clear it;
(g) Unattached on ptp and cdp gives PUNCH NOT READY (but not WRCHK), and attaching will clear it.

I hope I gave you a useful answer.  If not, keep at me.

**Comment by archivisth** [comment]
Here is the current error matrix for the 1620, after eliminating a few obvious places where RDCHK and WRCHK should not be set. 

[i1620_error_matrix.txt](https://github.com/simh/simh/files/1098605/i1620_error_matrix.txt)

**Comment by archivisth** [comment]
I agree that EOF and unattached should not set RDCHK or WRCHK. I'm less sure about true file IO errors. They're very rare - in fact, I've never seen one - but I suppose it could happen if the user filled up his disk on output, for example. There's no real recovery possible, so whether a check indicator is set or not is kind of moot.

Right now, the simulator ignores invalid characters on TTY input, simply echoing beep. It could set RDCHK, as you indicated, and store junk (most likely 0xF) in memory, but I'm not sure it matters.

**Comment by DaveWise2** [comment]
Beep is more convenient.  In this case, reality sucks.

I studied your error matrix.  I agree, except for tty and ptp.  Just like ptr, on WA/WN/DN, it should set WRCHK, then complete the operation, and then stop if IOSTOP is on.

In real life, it's the same for cdr, cdp, and probably lpt too.  The real CPU never stops in the middle of a buffer transfer.  But if SIMH models the operation as atomic instead of column by column, it's a distinction without a difference.

Ptp is a weird case.  The real 1624 punch has a parity check right at the die, so if a mechanical error occurs inside the punch, the CPU can stop on the bad character (with PUNCH NO FEED but not WRCHK) so you can overwrite it with "tape feed" code, retry the character, and continue from there.  But this can't happen in SIMH.

On the other hand, if there's a bad character in memory, the CPU will set WRCHK, complete the instruction, and then stop if IOSTOP is on, same as ptr.
