### ISSUE TITLE
Can't build with Visual Studio Community 2017

### ISSUE THREAD

**Issue by mgthompson** [simh/simh#479]
My configuration is:
Microsoft Visual Studio Community 2017 Version 15.3.2
VisualStudio.15.Release/15.3.2+26730.10
Microsoft .NET Framework Version 4.6.01055
Visual C++ 2017   00369-60000-00001-AA205
GitHub.VisualStudio   2.2.0.11
Visual Studio tools for CMake   1.0

When I opened the Simh.sln file it asked to upgrade everything for use with VS 2017, and I clicked OK.

I retargetted the solution to Windows SDK V10.0.15063.0.
Each of the Projects had an output like this:
Upgrading project 'BuildROMs'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v141' (was 'v100').
	Configuration 'Release|Win32': changing Platform Toolset to 'v141' (was 'v100').

If I build the BuildROMs project the output is below. It looks like it needs the VS2010 build tools.
Building the entire Solution results in the same messages for each Project.

1>  Task "SetEnv"
1>    INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\atlmfc\include;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\include;;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt;;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\UnitTest\include;C:\Program Files (x86)\Windows Kits\8.1\Include\um;C:\Program Files (x86)\Windows Kits\8.1\Include\shared;C:\Program Files (x86)\Windows Kits\8.1\Include\winrt;;
1>  Done executing task "SetEnv".
1>Target "SetUserMacroEnvironmentVariables" skipped, due to false condition; ('@(BuildMacro)' != '' and '$(DesignTimeBuild)' != 'true') was evaluated as ('' != '' and '' != 'true').
1>Target GetResolvedWinMD:
1>Target PlatformPrepareForBuild:
1>  Task "VCMessage" skipped, due to false condition; ('$(_Error64bitToolsNotInstalled)' == 'true') was evaluated as ('' == 'true').
1>  Task "VCMessage" skipped, due to false condition; ('$(DesignTimeBuild)'!='true' and '$(_ToolsetFound)' != 'true' and '$(PlatformToolset)' == 'v110') was evaluated as (''!='true' and '' != 'true' and 'v100' == 'v110').
1>  Using "VCMessage" task from assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Build.CppTasks.Common.dll".
1>  Task "VCMessage"
1>    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
1>  Done executing task "VCMessage" -- FAILED.
1>Done building target "PlatformPrepareForBuild" in project "BuildROMs.vcxproj" -- FAILED.
1>
1>Done building project "BuildROMs.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8020	The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	BuildROMs	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets	55

**Comment by markpizz** [comment]
I'll check out the details here and explore what is necessary to support both older and the latest VS2017 build environment s.

Meanwhile, the 0ReadMe_Projects.txt file contains info about where you can download VS2008 which runs just fine on Windows 10.

**Comment by 2kaud** [comment]
For VS2017, you need to set the platform toolset to v141. From project/properties/general change PlatformToolset.

I built the PDP11 simulator today with that platform toolset OK. Note that you will also need to define _CRT_SECURE_NO_WARNINGS and _WINSOCK_DEPRECATED_NO_WARNINGS.

**Comment by LegalizeAdulthood** [comment]
@2kaud Upgrading the projects should have done this on every project.  That's what I got.  I did encounter a different error on BuildROMs when I tried to build it the first time, but when I built it again it worked.

**Comment by markpizz** [comment]
A fresh clone or zip download of the github.com/simh/simh repo should convert and build cleanly now (after also downloading the windows-build components).
