### ISSUE TITLE
Instruction throttling is not smooth

### ISSUE THREAD

**Issue by jblang** [simh/simh#481]
- #### Context

Software that uses the PDP-1 display, for example munching squares, runs too fast without throttling, so I set throttling to 200K instructions per second. After doing this, I noticed that throttling is not smooth.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

```
sim> show version
PDP-1 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 4
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Jun 13 2017 at 10:48:30
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.5
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 10.0.15063]
        Architecture: x86 on AMD64, Processors: 8
        Processor Id: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel, Level: 6, Revision: 3c03
        git commit id: 605ede8c
```

- #### how you built the simulator or that you're using prebuilt binaries
Prebuilt binaries from https://github.com/simh/Win32-Development-Binaries/raw/Win32-Development-Binaries/simh-4.0-Beta--2017-06-13-605ede8c.zip

- #### the simulator configuration file (or commands) which were used when the problem occurred.
```
load munch.rim
set dpy enable
set throttle 200k
d tw 006000
run
```

- #### the expected behavior and the actual behavior

I would expect throttling to occur at a consistent rate. However, it appears that the instruction rate is throttled for a while and then lunges ahead at maximum speed, then gets throttled again. With the settings described above this is evident as a display glitch that occurs every 10 seconds.

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

I'm using munch.rim from the simh repo: https://github.com/simh/simh/raw/master/PDP1/spacewar1/munch.rim

**Comment by markpizz** [comment]
Well, the normal throttling process does a dynamic measurement to achieve the specified throttling rate.  

This measurement is repeated every 10 seconds to attempt to accommodate different instruction mixes which may execute at different rates on the host system.  My guess is that the behavior you're seeing the is due to the recalibration of the throttling rate.

You can avoid the recalibration on your system with the following:
1) Run as you've mentioned above.
2) After running for some 30 seconds, use ^E in the simulator control window and type:
```
sim> sh throt
Throttle:                      200 kilocycles
Throttling by sleeping for:    6 ms every 1333 cycles
sim> # 6 and 1333 will be different on your system.
sim> set throt 1333/6
sim> sh throt
Throttle:                      1333/6
Throttling by sleeping for:    6 ms every 1333 cycles
```
Then modify your pdp1 configuration file to change "set throttle 200k" to "set throt c/t" where c and t are the numbers you observed with the "sh throt" command.

Let me know if this works...

**Comment by jblang** [comment]
In my case, the numbers observed after about a minute were 205/1.  That seems to improve things initially but after the simulation runs for several minutes with these throttle settings, it starts getting jerky again, although in a different way than before.  After several minutes, the simulation appears to be running as many instructions as it can, as quickly as possible, then pausing for a long time, then running another burst of instructions, and pausing again, ad infinitum. 

This doesn't seem to be an ideal solution for timing critical applications (like pretty much anything that uses the display).  I am not sure there's a way to achieve the required accuracy other than putting in an optional per-instruction wait that conforms to the timings listed for each instruction in the PDP-1 handbook.

**Comment by markpizz** [comment]
Well, there have been changes in the simh framework which affect timing related things and throttling since the binary you've been working with.  I've just put out Windows binaries built from the latest code.  Please try your original recipe with the latest simulator.  After that, try my first suggestion and come back here with your impression of both.

**Comment by jblang** [comment]
Thanks for posting those. The original throttling setting of 200k still behaves in the same way. The setting of 205/1 (based on show throttle output) has remained smooth after running for more than 10 minutes.

By the way, I also filed a bug on the simtools repo at the same time as this one regarding an issue I found in the macro1 cross-assembler. Hope it's not bad form to ask about it here, but I wasn't sure anyone was watching that bug tracker since it looks like I'm the first one to file a bug there.

**Comment by markpizz** [comment]
So, given the option of throttling with 205/1 is there still a problem?  If not, the earlier explanation about dynamic recalibrating the throttling delays serves to explain the behavior and the direct setting of the throttling parameters solves it, right?  If so, please close this issue.

As for the macro1 cross-assembler, I commented in your other issue, suggesting that you should feel free to fix the problem and submit the results as a pull request or by any other means you want.

**Comment by jblang** [comment]
There does not seem to be a problem with the setting of 205/1.
