### ISSUE TITLE
VAX: Self-test 53 fails on ARM

### ISSUE THREAD

**Issue by jguillaumes** [simh/simh#482]
Hello,

The current HEAD version of the vax3900 simulator compiled for ARM fails the power up test:

```
$ ../simh-bin/vax /dev/null

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: d02de515
sim> 
sim> 
sim> b
Loading boot code from internal ka655x.bin


KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..

?53 2 0A FF 00 0000

P1=00000002  P2=00000028  P3=00002713  P4=00D40077  P5=00000001
P6=FFFFFFFF  P7=00000000  P8=00000000  P9=00000000 P10=20051CE0
r0=00000008  r1=20140110  r2=94A75DCA  r3=000301F6  r4=94A75DD4
r5=2004E8F9  r6=00018678  r7=000186C8  r8=0001ADB3 ERF=80000000
30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Normal operation not possible.

>>>               
```

As you can see, it fails WITHOUT ANY INI FILE. It also fails with my usual INI file.

SHOW VERSION output follows:

```
sim> show version
MicroVAX 3900 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 4
    Host Platform:
        Compiler: GCC 4.6.3
        Simulator Compiled as C arch: ARM (Release Build) on Sep 15 2017 at 13:55:52
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 1.2.15
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux odroid1 3.10.43 #1 SMP PREEMPT Fri Jan 2 18:47:44 BRST 2015 armv7l armv7l armv7l GNU/Linux
        git commit id: d02de515
```

**Comment by jguillaumes** [comment]
Additional info: my third attempt to boot succeeded, so it is an intermittent problem.

**Comment by pghardy** [comment]
I think this was reported back in March:
"Re: [simh/simh] An intermittent error on system test 31(?) when booting CPU (#408)"

Although it says "Normal operation not possible", if you boot VMS it boots OK. I think it is something to do with sanity checks against the real time clock being too tight for fast simulators.

-- 
Paul Hardy | 
paul@paulhardy.net | www.pghardy.net |

On 15 Sep 2017, at 13:12, Jordi Guillaumes Pons <notifications@github.com> wrote:

Hello,

The current HEAD version of the vax3900 simulator compiled for ARM fails the power up test:

`$ ../simh-bin/vax /dev/null

MicroVAX 3900 simulator V4.0-0 Beta git commit id: d02de51
sim>
sim>
sim> b
Loading boot code from internal ka655x.bin

KA655-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..

?53 2 0A FF 00 0000

P1=00000002 P2=00000028 P3=00002713 P4=00D40077 P5=00000001
P6=FFFFFFFF P7=00000000 P8=00000000 P9=00000000 P10=20051CE0
r0=00000008 r1=20140110 r2=94A75DCA r3=000301F6 r4=94A75DD4
r5=2004E8F9 r6=00018678 r7=000186C8 r8=0001ADB3 ERF=80000000
30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Normal operation not possible.

`

As you can see, it fails WITHOUT ANY INI FILE. It also fails with my usual INI file.

SHOW VERSION output follows:

sim> show version MicroVAX 3900 simulator V4.0-0 Beta Simulator Framework Capabilities: 64b data 64b addresses Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP Idle/Throttling support is available Virtual Hard Disk (VHD) support RAW disk and CD/DVD ROM support Asynchronous I/O support (Lock free asynchronous event queue) Asynchronous Clock support FrontPanel API Version 4 Host Platform: Compiler: GCC 4.6.3 Simulator Compiled as C arch: ARM (Release Build) on Sep 15 2017 at 13:55:52 Memory Access: Little Endian Memory Pointer Size: 32 bits Large File (>2GB) support SDL Video support: SDL Version 1.2.15 PCRE RegEx support for EXPECT commands OS clock resolution: 1ms Time taken by msleep(1): 1ms OS: Linux odroid1 3.10.43 #1 SMP PREEMPT Fri Jan 2 18:47:44 BRST 2015 armv7l armv7l armv7l GNU/Linux git commit id: d02de515

**Comment by markpizz** [comment]
Several timing related changes over the last 9 months have improved the underlying causes of this problem.  I no longer see it on any of my environments and I had thought it was completely solved.

Please run with this single configuration line and accumulate some statistics as to the frequency you are observing failure vs success for test 31 (or any other failure):
```
     sim> EXPECT -p ">>>" BOOT
     sim> BOOT
```

**Comment by jguillaumes** [comment]
I've just run the test 10 times and it just failed the first time (so 1 out of 10). After that I exited the simulator and ran it again, with no error this time.

**Comment by markpizz** [comment]
My windows and Linux environments run for hundreds of times without failure.

**Comment by jguillaumes** [comment]
OK, maybe it is related to a timing issue which gets solved by merely catching. The ARM boards are not really brilliant wrt IO times when they access the filesystem.

**Comment by markpizz** [comment]
The problem is that while this testing is going on, the simulator hasn't had a chance to do any file I/O yet, so caching in that process isn't a factor.

How/when is this happening with respect the system being booted?

**Comment by jguillaumes** [comment]
Unrelated. The system was not booted before the test.
BUT the simulator was built (or copied in) before the failure!

**Comment by jguillaumes** [comment]
I have not been able to reproduce the issue, neither with the original, reported commit nor with the last updates from repo.
