### ISSUE TITLE
microvax3900: Segfault on restoring state

### ISSUE THREAD

**Issue by DNied** [simh/simh#484]
MicroVAX 3900 simulator V4.0-0 Beta (git commit id: c8a420ad) on Linux/x86_64 4.4.75. The 'restore' command (with or without the -F flag) always results in a segfault.

Just once, it also spit a backtrace (which I tried to attach, but since GitHub no longer supports Firefox ESR 52.3.0, the attachment failed -- if you need the backtrace or make's output, please provide an email address).

Output of SimH's "sh version":
```
MicroVAX 3900 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 4
    Host Platform:
        Compiler: GCC 5.3.0
        Simulator Compiled as C arch: x64 (Release Build) on Sep 21 2017 at 23:51:38
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 1.2.15
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux [localhost] 4.4.75 #2 SMP Fri Jun 30 02:57:58 CDT 2017 x86_64 AMD Athlon(tm) 64 Processor 3200+ AuthenticAMD GNU/Linux
git commit id: c8a420ad
```

**Comment by markpizz** [comment]
Please provide the configuration file you're using!

**Comment by DNied** [comment]
Fixing an imprecision in my previous comment: the segfault actually happens on the 'continue' command following the 'restore'.

**Comment by markpizz** [comment]
Send backtrace to mark@infocomm.com

**Comment by markpizz** [comment]
What made you find the -F flag to the restore command?

**Comment by DNied** [comment]
.ini file follows:
```ini
;--------------------------------------------------------------------------
; SIMH initialisation file for Quasijarus.
;--------------------------------------------------------------------------
; Disable devices we are not using.
set cpu 64M
;set throttle 3800K
set throttle 60%
set cr disable
set lpt disable
set rl disable
set rq1 disable
set rq2 disable
set rq3 disable
set ry disable
set tq1 disable
set tq2 disable
set tq3 disable
set ts disable
;--------------------------------------------------------------------------
; Enable the DZ-11 serial lines on port 8023.
set dz enable
attach dz 8023
set dz lines=4
set dz 8b
set dz enable
attach dz 8023
set dz lines=4
set dz 8b
;--------------------------------------------------------------------------
; Attach the Ethernet interface; change 'em0' to your physical Ethernet
; adaptor name.
set xq enable
set xq type=deqna
attach xq0 nat:
;attach xq0 nat:tcp=8022:10.0.2.4:22
;--------------------------------------------------------------------------
; Attach the disk image; change the name if necessary.
; Add more disks if required.
set rq0 ra90
set rq0 noauto
attach rq0 /home/ndr/lib/emu/vax/vaxar.dsk
;--------------------------------------------------------------------------
; Attach the NVRAM file and enable the NVRAM.
attach nvr uvax3900-nvram.bin
;--------------------------------------------------------------------------
; Set 7 bits on the terminal, or at some point we will lose control.
set tti 7b
set tto 7b                            
;--------------------------------------------------------------------------
; CPU idle time tuning. Uncomment to make SIMH recognise the idle loop and
; reduce CPU consumption.
;;set cpu idle=openbsdold
;--------------------------------------------------------------------------
; Autobooting:
; If you want the machine to boot immediately from the default device
; (usually DUA0:), set the Boot and Diagnostic Register (BDR) to zero
; (more specifically, set bit 7 to zero, although SIMH will only have that
; bit set anyway). This bit corresponds to the setting of the Break Enable
; switch on the CPU cover panel on a real VAX 3900.
; deposit bdr 0
;--------------------------------------------------------------------------
; Boot the CPU.
;boot cpu
```

**Comment by DNied** [comment]
I found the -F flag in this message from SimH:
```
+sim> restore vaxar.state 
Eth: closed nat:
Error Attaching NVR to uvax3900-nvram.bin - the restore state is 1949 seconds older than the attach file
restore with the -F switch to override this sanity check
Command not completed
+sim>
```
More findings: if I comment out the line that says `attach xq0 nat:` in my .ini file, the segfault happens right on 'restore' and it *always* spits out a traceback.

**Comment by markpizz** [comment]
Can you describe ALL of the commands entered at the "sim> " prompt from when the simulator is started until you see the problem?

**Comment by markpizz** [comment]
Unrelated to the problem you're seeing, you've got:
```
;set throttle 3800K
set throttle 60%
```
I'd recommend you use idling rather than throttling for the any of the VAX simulators.

**Comment by DNied** [comment]
OK, I'll paste I/O from different sessions, .ini file exactly as above.

With 'restore':
```
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: c8a420ad
vaxar.ini-14> set ry disable
Non-existent device
Listening on port 8023
libpcap version 1.8.1
NAT args: 
NAT network setup:
        gateway       =10.0.2.2/24(255.255.255.0)
        DNS           =10.0.2.3
        dhcp_start    =10.0.2.15
  Protocol[State]    FD  Source Address  Port   Dest. Address  Port RecvQ SendQ
Eth: opened OS device nat:
NVR: buffering file in memory
+sim> restore vaxar.state 
NVR: writing buffer to file
Eth: closed nat:
Error Attaching NVR to uvax3900-nvram.bin - the restore state is 8914 seconds older than the attach file
restore with the -F switch to override this sanity check
Segmentation fault
```

With 'restore -F':
```
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: c8a420ad
vaxar.ini-14> set ry disable
Non-existent device   
Listening on port 8023
libpcap version 1.8.1
NAT args: 
NAT network setup:
        gateway       =10.0.2.2/24(255.255.255.0)
        DNS           =10.0.2.3
        dhcp_start    =10.0.2.15
  Protocol[State]    FD  Source Address  Port   Dest. Address  Port RecvQ SendQ
Eth: opened OS device nat:
NVR: buffering file in memory
+sim> restore -F vaxar.state 
NVR: writing buffer to file
Eth: closed nat:
NVR: buffering file in memory
Listening on port 8023
NAT args: 
NAT network setup:
        gateway       =10.0.2.2/24(255.255.255.0)
        DNS           =10.0.2.3
        dhcp_start    =10.0.2.15
  Protocol[State]    FD  Source Address  Port   Dest. Address  Port RecvQ SendQ
Eth: opened OS device nat:
+sim> continue        
Segmentation fault
```

Now with `attach xq0 nat:` commented out in the .ini file.

With 'restore':
```
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: c8a420ad
vaxar.ini-14> set ry disable
Non-existent device   
Listening on port 8023
NVR: buffering file in memory
+sim> restore vaxar.state
NVR: writing buffer to file
Error Attaching NVR to uvax3900-nvram.bin - the restore state is 9228 seconds older than the attach file
restore with the -F switch to override this sanity check
*** Error in `/home/ndr/net/simh-master/BIN/microvax3900': double free or corruption (fasttop): 0x0000000001e3e3f0 ***
======= Backtrace: =========
<snip>
```

With 'restore -F':
```
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: c8a420ad
vaxar.ini-14> set ry disable
Non-existent device
Listening on port 8023
NVR: buffering file in memory
+sim> restore -F vaxar.state 
NVR: writing buffer to file
NVR: buffering file in memory
Listening on port 8023
libpcap version 1.8.1
NAT args: 
NAT network setup:
        gateway       =10.0.2.2/24(255.255.255.0)
        DNS           =10.0.2.3
        dhcp_start    =10.0.2.15
  Protocol[State]    FD  Source Address  Port   Dest. Address  Port RecvQ SendQ
Eth: opened OS device nat:
+sim> continue
Segmentation fault
```

**Comment by markpizz** [comment]
What you're doing is slightly beyond the intended behavior.

Specifically, you're loading your system configuration in the simulator (due to the config file being named vax.ini in the local directory when you start the simulator).  then you're restoring state from some previous run of the simulator on top of the in memory configured state.  This probably 'should' work, but I can see the combination of screwy data cases that can arise being problematic.

I would recommend stepping back and naming your configuration file myvax-config.ini (or something other than vax.ini).  

Then run your system with your configuration until the time you want to save it's state.  At that time, hit ^E and do a "SAVE vaxar.state".  Immediately exit the simulator.

Later, when you want to resume things, you start the simulator WITHOUT any configuration file (named vax.ini OR explicitly on the command line).  Then enter "RESTORE vaxar.state" followed by a "CONTINUE".

If you follow this recipe you should not need a -F for your restore command.

Something which may or may not be obvious to you:

The simh SAVE and RESTORE commands ARE NOT equivalent to "Snapshots" or "Checkpoints" that some VM environments provide.

Something which would be equivalent to these "Snapshots" would certainly include the state saved by the SAVE command PLUS the actual contents of ALL the attached disk images and/or other related storage.

Knowing this, using various simh commands in addition to the SAVE and RESTORE commands to implement something that models more completely this external idea of "Snapshots".

Please let me know if the above recipe also crashes the simulator in your environment.

**Comment by DNied** [comment]
My .ini file was actually called `vaxar.ini`, so it doesn't get auto-loaded. I also tried to start `microvax3900` without specifying the .ini file on the command line, but this is what happens:
```
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: c8a420ad
+sim> restore vaxar.state 
Memory size changed: CPU0 = 64MB
Invalid device name: INT-THROTTLE
Command not completed
+sim> 
```

**Comment by markpizz** [comment]
As I suggested earlier, you should use idling instead of throttling for all of the VAX simulators, and if you do then this problem won't be observed.  Meanwhile I'll look into solving that case.

**Comment by DNied** [comment]
But I didn't set throttle... no .ini file, no throttle.

**Comment by markpizz** [comment]
You did set throttle before you executed the SAVE command.

**Comment by DNied** [comment]
I had set idle=openbsdold by hand long before saving state (I had experimented with different options, but that was the last one I had used).

**Comment by markpizz** [comment]
But you had previously (in that same simulator session where you executed the SAVE command) enabled throttling.

By the way, these are the choices for the SET CPU IDLE command:

```
The CPU attempts to detect when the simulator is idle.  When idle, the
simulator does not use any resources on the host system.  Idle detection is
controlled by the SET IDLE and SET NOIDLE commands:

   sim> SET CPU IDLE{=VMS|ULTRIX|ULTRIXOLD|ULTRIX-1.X|
                      3BSD|4.0BSD|4.1BSD|4.2BSD|QUASIJARUS|
                      NETBSD|NETBSDOLD|OPENBSD|OPENBSDOLD|32V|ELN}{:n}
                                        enable idle detection
   sim> SET CPU NOIDLE                  disable idle detection

Idle detection is disabled by default.  If idle detection is enabled with
an incorrect operating system setting, simulator performance or correct
functionality could be impacted.  The default operating system setting is
VMS.  The value 'n', if present in the "SET CPU IDLE={OS}:n" command,
indicats the number of seconds which the simulator must run before idling
starts.
```

If you're really running Quasijarus it would make most sense to tell the simulator that.  As it turns out, OPENBSDOLD and QUASIJARUS are equivalent, but I had to look at the code to determine that.

**Comment by DNied** [comment]
Actually, I'm no longer running Quasijarus (although I carried over the old .ini file, just making minimal changes). I was running OpenBSD/vax 3.3 when I saved state. Shouldn't the saved state hold the latest settings, though?

Here's another brief session (with no .ini file) where I inspect the CPU before and after restoring:
```
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: c8a420ad
+sim> sh cpu
CPU     idle disabled, model=VAXServer 3900 (KA655), NOAUTOBOOT
        16MB, HALT to SIMH
+sim> restore vaxar.state 
Memory size changed: CPU0 = 64MB
Invalid device name: INT-THROTTLE
Command not completed
+sim> sh cpu
CPU     idle=OPENBSDOLD, idle enabled, model=VAXServer 3900 (KA655), NOAUTOBOOT
        64MB, HALT to SIMH
+sim> 
```

**Comment by markpizz** [comment]
> Actually, I'm no longer running Quasijarus (although I carried over the old .ini file, just making minimal changes). I was running OpenBSD/vax 3.3 when I saved state. Shouldn't the saved state hold the latest settings, though?

Well, as I said before the simh SAVE is NOT equivalent to a Snapshot. 

> Here's another brief session (with no .ini file) where I inspect the CPU before and after restoring:
> 
> MicroVAX 3900 simulator V4.0-0 Beta        git commit id: c8a420ad
> +sim> sh cpu
> CPU     idle disabled, model=VAXServer 3900 (KA655), NOAUTOBOOT
>         16MB, HALT to SIMH
> +sim> restore vaxar.state 
> Memory size changed: CPU0 = 64MB
> Invalid device name: INT-THROTTLE
> Command not completed
> +sim> sh cpu
> CPU     idle=OPENBSDOLD, idle enabled, model=VAXServer 3900 (KA655), NOAUTOBOOT
>         64MB, HALT to SIMH
> +sim> 

Once a restore fails, the state of the simulator is indeterminate (i.e. not meaningful).

By the way, the latest github code won't create an unrestorable save file independent of how or if throttling is enabled when the save file is created.

**Comment by markpizz** [comment]
When you change operating systems you'll have to SET CPU IDLE to a value which works for the OS you're running.  You may have to try different values to get one that works for any particular OS.  Different idling code exists in various OS flavors.  There may be a couple of BSD OS versions where they changed to an undetectable mechanism.  Once I found that they'd done that, I suggested a pattern that could be detected and that was added to later BSD versions.

**Comment by DNied** [comment]
After some more fiddling... it worked! Continuing from the session pasted above:
```
+sim> cont
ra0: attempt to bring on line failed:  unit offline (not mounted) (code 3, subcode 1)      
<snipped a boatload of the same message spouting off at crazy speed>
ra0: attempt to bring on line failed:  unit offline (not mounted) (code 3, subcode 1)
<here I sent SimH a SIGHUP>
Simulation stopped, PC: 80146A21 (BGEQ 80146A1C)
+sim> set rq0 ra90
+sim> set rq0 noauto
+sim> att rq0 vaxar.dsk
+sim> cont
line failed:  unit offline (not mounted) (code 3, subcode 1)
ra0: size 2376153 sectors
```
I attached the disk by hand and was finally able to login and recover my saved state (although I could no longer telnet in, no doubt for lack of DZ initialization).

OK, thanks for steering me in the right direction. I'll build and test the latest version. IMO, a full snapshot shouldn't necessarily require saving the state of all disk images (as Qemu does) with the caveat that they must not be altered between `SAVE` and `RESTORE`. Maybe saving the disk images could be an option.

**Comment by markpizz** [comment]
> IMO, a full snapshot shouldn't necessarily require saving the state of all disk images (as Qemu does) with the caveat that they must not be altered between SAVE and RESTORE. 

Absolutely true, and things will work nicely that way if you SAVE and then exit the simulator immediately (which will close all "attached" files and thus keep any modify timestamps close enough to the SAVE time.  If subsequently start a simulator attaching the same files before you attempt to do a RESTORE, the time stamps will get messed up and the sanity validation check (have the files changed since the SAVE?) fails.

Meanwhile, back to the original crash you reported....
First, I'm trying to get you to perform things in the expected sequence, and if that still causes crashes, then we've got a must fix problem.  Not all simulators are fully supported using SAVE and RESTORE, but I believe that the VAX simulator should work with all simulated devices enabled.  A basic requirement here is that telnet sessions into the simulator console port or MUX devices (DX, VH, etc) will absolutely get dropped any time the simulator exits.  It will be up to users to reestablish connections of that sort.  Meanwhile, if you're using PCAP networking connected to a host system LAN port, then telnet sessions into or out of the simulated systems will work transparently across a SAVE->exit->restart->RESTORE as long as a user who is telnet'd in doesn't type anything into their telnet session between when the SAVE is started and the RESTORE is complete.

Once you've got a good SAVE you should NOT see problems with disk access when you subsequently RESTORE.  The simulator should not noticed anything has happened.   Earlier simh versions had problems with RQ disks devices not properly saving complete state across SAVE, EXIT, RESTORE and the simulated OS had to reinitialize the controller.  This was due to a bug in the RQ device simulation which has been fixed.

Back to the original problem, if you can give me a reasonable set of commands (and data if necessary) that cause a segfault, I'll track it down and fix it.

**Comment by DNied** [comment]
OK, the following sequence will lead to a segmentation fault. I'm still on the same version as before, no .ini file:

```
$ ~/net/simh-master/BIN/microvax3900

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: c8a420ad
+sim> set cpu 64M
+sim> set cr disable
+sim> set lpt disable
+sim> set rl disable
+sim> set rq1 disable
+sim> set rq2 disable
+sim> set rq3 disable
+sim> set tq1 disable
+sim> set tq2 disable
+sim> set tq3 disable
+sim> set ts disable
+sim> set dz enable   
+sim> attach dz 8023 
Listening on port 8023
+sim> set dz lines=4
+sim> set dz 8b
+sim> set xq enable
+sim> set xq type=deqna
+sim> attach xq0 nat:
libpcap version 1.8.1
NAT args: 
NAT network setup:
        gateway       =10.0.2.2/24(255.255.255.0)
        DNS           =10.0.2.3
        dhcp_start    =10.0.2.15
  Protocol[State]    FD  Source Address  Port   Dest. Address  Port RecvQ SendQ
Eth: opened OS device nat:
+sim> set rq0 ra90   
+sim> set rq0 noauto 
+sim> attach rq0 /home/ndr/lib/emu/vax/vaxar.dsk
+sim> attach nvr uvax3900-nvram.bin
NVR: buffering file in memory
+sim> set tti 7b
+sim> set tto 7b      
+sim> set cpu idle=openbsdold
+sim> boot
Loading boot code from internal ka655x.bin


KA655-B V5.3, VMB 2.7  
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Tests completed.
>>>b
(BOOT/R5:0 DUA0



  2..
-DUA0
  1..0..


>> OpenBSD/vax boot [1.9] [Mar 24 2003] <<
>> Press enter to autoboot now, or any other key to abort: 0
> boot bsd
1399968+50748+256384+[97704+116685] total=0x1d51d9 start=0x8000056c
[ using 214393 bytes of bsd a.out symbol table ]
Copyright (c) 1982, 1986, 1989, 1991, 1993
        The Regents of the University of California.  All rights reserved.
Copyright (c) 1995-2003 OpenBSD. All rights reserved.  http://www.OpenBSD.org

OpenBSD 3.3 (GENERIC) #15: Sat Mar 29 16:06:38 MST 2003
    deraadt@vax.openbsd.org:/usr/src/sys/arch/vax/compile/GENERIC
MicroVAX 3800/3900 [0A000006 01530302]
cpu: KA655, CVAX microcode rev 6 Firmware rev 83
total memory = 67035136
avail memory = 58208256
using 843 buffers containing 3452928 bytes of memory
mainbus0 (root)
ibus0 at mainbus0
uba0 at ibus0: Q22
dz0 at uba0 csr 160100 vec 304 ipl 17
mtc0 at uba0 csr 174500 vec 774 ipl 17
mscpbus0 at mtc0: version 5 model 3
mscpbus0: DMA burst size set to 4
mt0 at mscpbus0 drive 0: TK50
uda0 at uba0 csr 172150 vec 770 ipl 17
mscpbus1 at uda0: version 3 model 3
mscpbus1: DMA burst size set to 4
ra0 at mscpbus1 drive 0: RA90
qe0 at uba0 csr 174440 vec 764 ipl 17
qe0: deqna, hardware address 08:00:2b:0e:ff:2b
booted from device: ra0
root on ra0a
ra0: size 2376153 sectors
rootdev=0x900 rrootdev=0x900 rawdev=0x902
WARNING: / was not properly unmounted
Automatic boot in progress: starting file system checks.
/dev/rra0a: 56155 files, 536299 used, 485902 free (7910 frags, 59749 blocks, 0.8
% fragmentation)
/dev/rra0a: MARKING FILE SYSTEM CLEAN
setting tty flags
net.inet6.ip6.forwarding: 0 -> 0
net.inet6.ip6.accept_rtadv: 0 -> 0
starting network
add net default: gateway 10.0.2.2
starting system logger
starting rpc daemons: rdate.
savecore: no core dump
checking quotas: done.
building ps databases: kvm dev.
clearing /tmp
starting pre-securelevel daemons:.
setting kernel security level: kern.securelevel: 0 -> 1
preserving editor files
creating runtime link editor directory cache.
starting network daemons: sendmail inetd sshd.
starting local daemons:.
standard daemons: cron.
Sun Oct  8 21:38:03 CEST 2017

OpenBSD/vax (vaxar.local) (console)

login:
Simulation stopped, PC: 800007CB (BEQL 800007C5)
+sim> save test.state
+sim> bye
Goodbye
NVR: writing buffer to file
Eth: closed nat:
================================================================================
$ ~/net/simh-master/BIN/microvax3900

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: c8a420ad
+sim> restore test.state
Memory size changed: CPU0 = 64MB
NVR: buffering file in memory
Listening on port 8023
libpcap version 1.8.1
NAT args:
NAT network setup:
        gateway       =10.0.2.2/24(255.255.255.0)
        DNS           =10.0.2.3
        dhcp_start    =10.0.2.15
  Protocol[State]    FD  Source Address  Port   Dest. Address  Port RecvQ SendQ
Eth: opened OS device nat:
+sim> cont
Segmentation fault
```

**Comment by markpizz** [comment]
Excellent.

Can you zip up the vaxar.dsk and uvax3900-nvram.bin files and if you can drop them here, great or if they're less than about 6MB send via eMail OR put them up on a google drive someplace?

Thanks.

**Comment by markpizz** [comment]
Dario,

I think the problem we've narrowed this down to has been fixed.  Please confirm that, AND feel free to test with some of the more 'questionable' cases that you initially started with (i.e. trying to RESTORE after executing your whole initial configuration file).  Both should work.

If you're happy, please close this issue.

Thanks.

- Mark

**Comment by DNied** [comment]
After testing the latest revision, I can confirm that there are no more segfaults on restoring a saved state. I do think that `save` and `restore` still need work. For example, if a saved state contradicts an initialization file, you can find SimH in weird states such as this:
```
+sim> sh throttle
Throttle:                      60%
Throttling by sleeping for:    1 ms every 405 cycles
+sim> sh cpu
CPU     idle=QUASIJARUS, idle enabled, model=VAXServer 3900 (KA655), NOAUTOBOOT
        64MB, HALT to SIMH
+sim> 
```
where options that are supposed to be mutually exclusive are both enabled. Upon restoring and continuing I also got loads of this message repeated:
```
uda0: ra0: attempt to bring on line failed:  unit offline (not mounted) (code 3, subcode 1)
```
although both the .ini file and the saved state were pointing to the same disk image. Reattaching the disk image by hand solved the issue.

But anyway I was always able to recover the saved state without crashes, so this issue can be closed. Thank you!

**Comment by markpizz** [comment]
If you can reproduce the:
```
uda0: ra0: attempt to bring on line failed:  unit offline (not mounted) (code 3, subcode 1)
```
issue WITHOUT 'touching' any of the files that were attached when the SAVE was performed after the SAVE and before the RESTORE.  Specifically, use whatever config you want and run the simulator until things have stabilized.  ^E and SAVE followed immediately by EXIT (or QUIT).  Then start the simulator and immediately do a RESTORE followed by a CONTINUE.  If this problem is visible, then please create an issue describing it and I'll track down what is missing from the in the SAVEd and RESTOREd state.
