### ISSUE TITLE
PDP10: Program requests for level-7 interrupts are not being honored on Linux.

### ISSUE THREAD

**Issue by joeinwap** [simh/simh#486]
Trying to run TYMCOM-X, a TOPS-10 derivative, but clock level interrupts are not happening.
- #### Context
The emulator runs fine under NetBSD-7, but fails with Linux (kernel 4.10.0-38) (Ubuntu-16).
Runs TOPS-10 just fine in both cases, just fails with a custom operating system.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
PDP-10 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        64b data
        32b addresses
        Threaded Ethernet Packet transports:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 4
    Host Platform:
        Compiler: GCC 5.4.0 20160609
        Simulator Compiled as C arch: x64 (Release Build) on Jul  6 2017 at 15:15:53
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux zathras 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
        git commit id: 7ed68aed
```
- #### how you built the simulator or that you're using prebuilt binaries
Simple "make pdp10" on Linux
- #### the simulator configuration file (or commands) which were used when the problem occurred.

```
sim> type tymcom-x.ini
; SIMH Configuration for TYMCOM-X
set dz 8b
set tim y2k
; Use existing two units for dskb
att rp0 tymb00.dsk
att rp1 tymb01.dsk
; Tape with TITO.SAV
att tu0 tito.tape
; Untested: DZ emulation; "telnet loclhost 2014" for mon14
att -am dz 2014
boot rp
```
- #### the expected behavior and the actual behavior

Expected: UPTIME gets incremented 60 times per second. CH7 shows JSR happening
Actual: UPTIME remains zero, CH7 shows no JSR to that point, commands not recognized.
- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem
Specific files are tymb0.dsk and tymb1.dsk, each one is 301 MB in size.

**Comment by markpizz** [comment]
Hi Joe,

I see you're using a version (commit 7ed68ae) from back in July.  Have you tested this with the latest code?  I ask since there has been some general fixes to timing related issues since July.

Although tymb0.dsk and tymb1.dsk are 301MB each, I suspect that they'll compress to something MUCH smaller, and although the result may not be directly attachable to this issue, it should be pretty easy to make them available in a Google Drive or something similar.

Also, details about what is entered after the "boot rp" command to observe the problem.

Thanks.

- Mark

**Comment by joeinwap** [comment]
The details of what I'm seeing are on a newly created wIki page:
http://wiki.livingcomputers.org/doku.php?id=tymcom-x-simh
  -Joe

**Comment by markpizz** [comment]
Hi Joe,

Thanks for providing details about how to build everything.  

Meanwhile, the steps to get to where things diverge (i.e. work on NetBSD and fail on Linux) are somewhat arduous.  If you can provide the dskb.dsk and dskc.dsk files, I can start from the relatively simple step of "Create two TYMCOM-X *.ini files".

Thanks.

- Mark

**Comment by joeinwap** [comment]
The two RP06 disk images compress down to 58MB.
https://drive.google.com/open?id=1xNgJQAnAtX5ZxReP9Qi4hS7n_Faj-rPU

**Comment by markpizz** [comment]
Thanks for that.

Now when I try to execute the tym-fresh.ini script, I really don't know exactly what is necessary to type to get to the point of the failure (clearly I've never been a user of this system, so your interpreting your notes isn't obvious to me):

```
Linux% ./pdp10 tym-fresh.ini
BOOT>mon14/st:141
EDDT ctybrk$b   140$g
RMA0 initialize BAT pages? y
... are you sure? y
RMA1 initialize BAT pages? y
... are you sure? y
FILES* define
... are you sure? y
Type names of physical units
rma0
rma1

RMA0 unit ID needed: dskb00
RMA1 unit ID needed: dskb01
FILES* refresh
... are you sure? y
Enter date as MM-DD-YYYY 11-13-1989     ;Use year-28; must be less than 2008
Enter time as HHMM 0040
FILES* go
please log in: Control-Z ?
```
You could augment the tym-fresh.ini script to automatically provide the appropriate inputs using the simh EXPECT and SEND commands.  The first input (the response to the "BOOT>" prompt can be provided with:
```
....
; Tape with TITO.SAV
att tu0 tito.tape
; Untested: DZ emulation; "telnet loclhost 2014" for mon14
att -am dz 2014
expect "BOOT>" send "mon14/st:141\r"; GO
expect "RMA0 initialize BAT pages? " send "y\r"; GO
expect "RMA1 initialize BAT pages? " send "y\r"; GO
expect -p "are you sure? " send "y\r"; GO
expect "FILES* " send "define\r"; GO
boot rp
```

I have no idea what "ctybrk$b   140$g" is, so I'll leave that one and the rest up to you...

**Comment by markpizz** [comment]
Realize that my goal is to be able to have the failure happening within the simulator so I can observe the details of the simulated device interactions with the SCP framework and the host OS.

**Comment by joeinwap** [comment]
Differences in execution - Linux vs NetBSD/FreeBSD

TOPS-10 emulation works on all systems tested, but TYMCOM-X does not

A quick test for proper operation: does End of ONCE; starting null job get printed at startup?

```
OS       OS version    3.9_0  4.0_0
-------  -----------   -----  -----
Linux    Ubuntu-16.4   yes    no
Cygwin   Windows-7     yes    no
NetBSD   7.0_STABLE    yes  **yes**
FreeBSD  11.1_RELEASE  yes    no
```
no means simh does not acknowledge program requests for level 7 interrupts; therefore UPTIME is not incremented and Console input is ignored.
yes means simh has functioning level 7 interrupts, UPTIME is updated, Console characters acted upon.

**Comment by markpizz** [comment]
If you're going to compare versions, rather than going back to 3.9, please pick the latest from the Supnik-Current branch: https://github.com/simh/simh/archive/Supnik-Current.zip

Meanwhile, I still don't know how to actually start the test case you've put together...

**Comment by joeinwap** [comment]
I tested v3.9 because that is what is still supplied in /usr/ports in FreeBSD-11.1_RELEASE.
Supnik's v3.10 works as well.  It is just v4.0 on all but NetBSD that is failing.

To test, "./pdp10 tymcom-x.ini", "mon14".  If it types "End of ONCE: starting null job" then it is working.  the lack of that message means interrupts are not working.
At this point, I am interested in why it works on NetBSD and not on FreeBSD.

**Comment by markpizz** [comment]
Thanks for testing the other combinations.

Meanwhile, I'm not getting started following your instructions on http://wiki.livingcomputers.org/doku.php?id=tymcom-x-status

Specifically, I do:
```
sim> do tym-fresh.ini
tym-fresh.ini-5> copy dskb.dsk tymb00.dsk
        1 file(s) copied
tym-fresh.ini-6> copy dskc.dsk tymb01.dsk
        1 file(s) copied
tym-fresh.ini-13> att -am dz 2014
Listening on port 2014
Modem control activated
Auto disconnect activated
BOOT V3(47)

BOOT>mon14/st:141
[Loading from DSKB:MON14.EXE[1,4]]
EDDT

 ctybrk$b   140$gU
```
If I do:

```
sim> do tymcom-x.ini
tymcom-x.ini-10> att -am dz 2014
Listening on port 2014
Modem control activated
Auto disconnect activated
BOOT V3(47)

BOOT>mon14
[Loading from DSKB:MON14.EXE[1,4]]

X14, hardware *B*, KS-4257, base 6760, X14-P035/E02, 6-3-92, M02654

Highest memory address is 3,,777777

Checking all units on disk controller - reading UNIT ID from HOME pages.RMA0 FIR
ST HOM PAGE CONSISTENCY ERROR
RMA0 SECOND HOM PAGE CONSISTENCY ERROR

 RMA0:            RMA1 FIRST HOM PAGE CONSISTENCY ERROR
RMA1 SECOND HOM PAGE CONSISTENCY ERROR
 RMA1:             RMA2:-offline-    RMA3:-offline-
 RMA4:-offline-    RMA5:-offline-    RMA6:-offline-    RMA7:-offline-


?NO SYSTEM STRUCTURE

ERRORS which prevent bringing the system UP
Entering the FILES dialogue...
  Type "GO" to return to ONCE.

Checking all units on disk controller - reading UNIT ID from HOME pages.RMA0 FIR
ST HOM PAGE CONSISTENCY ERROR
RMA0 SECOND HOM PAGE CONSISTENCY ERROR

 RMA0:            RMA1 FIRST HOM PAGE CONSISTENCY ERROR
RMA1 SECOND HOM PAGE CONSISTENCY ERROR
 RMA1:


?NO SYSTEM STRUCTURE
RMA0 FIRST BAT PAGE CONSISTENCY ERROR
RMA0 SECOND BAT PAGE CONSISTENCY ERROR

Do you want to initialize the BAT pages on this UNIT?
```
I've got no idea how to answer this question.

I get the same behavior (output) if I use the current 4.x code or the 3.10 version.

**Comment by markpizz** [comment]
Rather than keep banging my head against the wall trying to get to the proof point that things aren't working right, your last comment suggested that the running code in MON14 probably isn't behaving well right from when it is started, and that I probably don't need to get all the way to your proof point.

So, I started MON14 with the following done prior to booting from RP:
```
sim> SET DEBUG stdout
sim> SET TIM    Debug=RRD;RWR;TPS;TRACE
sim> BOOT RP
```

This produced the following output:
```
DBG(0)> TIM TRACE: tim_reset()
DBG(0)> TIM TPS: tim_reset() - clk_tps set to 60
DBG(0)> TIM TPS: update_interval() - clk_tps changed from 60 to 59
BOOT V3(47)

BOOT>MON14
[Loading from DSKB:MON14.EXE[1,4]]
DBG(175826603)> TIM RWR: wrint(000000000000)
DBG(175826603)> TIM TPS: update_interval() - clk_tps changed from 59 to -2147483648

[....]
```
The wrint(000000000000) line is due to an operating which is writing the timer interval register with the value 0.  The results and/or errant behavior flow from there.

Page 4-37 of AA-H391A-TK_DECsystem-10_DECSYSTEM-20_Processor_Reference_Jun1982.pdf doesn't specifically speak to what a 0 value in the interval register might mean.

The code which produces this is:

```
                           static t_bool update_interval (d10 new_interval)
                           {
                           int32 old_clk_tps = clk_tps;

                           tim_new_period = new_interval & ~TIM_HWRE_MASK;
tim_new_period is 0
                           if (new_interval & TIM_HWRE_MASK) tim_new_period += 010000;
tim_new_period still 0
    
                           /* clk_tps is the new number of clocks ticks per second */
                           clk_tps = (int32) ceil(((double)TIM_HW_FREQ /(double)tim_new_period) - 0.5);
Oops here we convert tim_new_period to a double (0) and divide by it.
                           if (clk_tps != old_clk_tps)
                               sim_debug (DEB_TPS, &tim_dev, "update_interval() - clk_tps changed from %d to %d\n", old_clk_tps, clk_tps);

                           /* tmxr is polled every tim_mult clks.  Compute the divisor matching the target. */
                           tim_mult = (clk_tps <= TIM_TMXR_FREQ) ? 1 : (clk_tps / TIM_TMXR_FREQ) ;
   
                           /* Estimate instructions/tick for fixed timing - just for KLAD */
                           tim_unit.wait = TIM_WAIT_IPS / clk_tps;
                           tmxr_poll = tim_unit.wait * tim_mult;

                           /* The next tim_svc will update the activation time.
                            * 
                            */
                           return FALSE;
                           }
```

So, what is expected to happen when the interval register is set to 0?  Is that a no-op?  Is that a zero length interval?  Is that the largest possible interval?

**Comment by joeinwap** [comment]
Thanks for the debugging output.  The interval is suppose to alternate between 16, 16, and 17 (milliseconds) to average 60 interrupts per second.  Zero appears to be a bug in MON14; I will track that down.
   -Joe
P.S. Can 'send' handle arbitrary control characters?  An ESCape in particular (^[, 033, \e).

**Comment by joeinwap** [comment]
Does the debugging you did indicate where the PC was at the time?

**Comment by markpizz** [comment]
From HELP SEND followed by "escaping_string_data":
```
    The following character escapes are explicitly supported:
            \r  Sends the ASCII Carriage Return character (Decimal value 13)
            \n  Sends the ASCII Linefeed character (Decimal value 10)
            \f  Sends the ASCII Formfeed character (Decimal value 12)
            \t  Sends the ASCII Horizontal Tab character (Decimal value 9)
            \v  Sends the ASCII Vertical Tab character (Decimal value 11)
            \b  Sends the ASCII Backspace character (Decimal value 8)
            \\  Sends the ASCII Backslash character (Decimal value 92)
            \'  Sends the ASCII Single Quote character (Decimal value 39)
            \"  Sends the ASCII Double Quote character (Decimal value 34)
            \?  Sends the ASCII Question Mark character (Decimal value 63)
            \e  Sends the ASCII Escape character (Decimal value 27)
    as well as octal character values of the form:
            \n{n{n}} where each n is an octal digit (0-7)
    and hext character values of the form:
            \xh{h} where each h is a hex digit (0-9A-Fa-f)
```

Debug output can include PC info with:
```
sim> SET DEBUG -p stdout
```

**Comment by markpizz** [comment]
```
sim> b rp
DBG(0-PC:755762)> TIM TRACE: tim_reset()
DBG(0-PC:755762)> TIM TPS: tim_reset() - clk_tps set to 60
DBG(0-PC:755762)> TIM TPS: update_interval() - clk_tps changed from 60 to 59
BOOT V3(47)

BOOT>mon15\5\4
[Loading from DSKB:MON14.EXE[1,4]]
DBG(136489911-PC:203154)> TIM RWR: wrint(000000000000)
DBG(136489911-PC:203154)> TIM TPS: update_interval() - clk_tps changed from 59 to -2147483648

X14, hardware *B*, KS-4257, base 6760, X14-P035/E02, 6-3-92, M02654

Highest memory address is 3,,777777
DBG(136585982-PC:056644)> TIM RRD: rdtim() = 000000000000 000121430000
DBG(136586349-PC:056705)> TIM RWR: wrtim(000000000000, 000121430000)
DBG(136586352-PC:056644)> TIM RRD: rdtim() = 000000000000 000121640000
DBG(136586652-PC:056705)> TIM RWR: wrtim(000000000000, 000121640000)
```

**Comment by joeinwap** [comment]
Found it.  A spot in ONCE was referencing unmapped virtual memory.  Moved the variable it was using closer to the code that invoked it.   MON14 now works (as much as possible).

Probably should add defensive code in simh to not divide by zero.

I'm marking this as closed.

**Comment by markpizz** [comment]
Commit 3eadc40 avoids the divide by zero and ignores a zero value for the interval register.  It is not clear what the real hardware did...
