### ISSUE TITLE
MinGW build on Windows 10 Pro  fails on #include statement

### ISSUE THREAD

**Issue by wboerhout** [simh/simh#487]
This is on a freshy installed Windows 10 Pro system with all updates rolled in.

Installed MinGW from https://sourceforge.net/projects/mingw-w64/?source=typ_redirect
Downloaded simh-master.zip and windows-build-windows-build folder from github

This happens:

D:\simh-master>build_mingw.bat vax vax780
lib paths are: C:/MinGW/mingw32/lib
include paths are: C:/MinGW/mingw32/include
using libpcreposix: D:/windows-build/PCRE/lib/pcreposix.a D:/windows-build/PCRE/include/pcreposix.h
***
*** vax vax780 Simulators being built with:
*** - compiler optimizations and no debugging support. GCC Version: Built.
*** - dynamic networking support using windows-build provided libpcap components.
*** - Local LAN packet transports: PCAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
***
*** git commit id is a8010f6fdb23a058794103ffb89160cca7fe3c6b.
***
*** No SDL ttf support available.  BESM-6 video panel disabled.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=a8010f6fdb23a058794103ffb89160cca7fe3c6b -DSIM_COMPILER="GCC Version: Built" -I . -fms-extensions -DUSE_READER_THREAD -DPTW32_STATIC_LIB -D_POSIX_C_SOURCE -I../windows-build/pthreads/Pre-built.2/include -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DPCRE_STATIC -ID:/windows-build/PCRE/include  sim_BuildROMs.c -o BIN/BuildROMs.exe
BIN\BuildROMs.exe
del BIN\BuildROMs.exe
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=a8010f6fdb23a058794103ffb89160cca7fe3c6b -DSIM_COMPILER="GCC Version: Built" -I . -fms-extensions -DUSE_READER_THREAD -DPTW32_STATIC_LIB -D_POSIX_C_SOURCE -I../windows-build/pthreads/Pre-built.2/include -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DPCRE_STATIC -ID:/windows-build/PCRE/include  VAX/vax_cpu.c VAX/vax_cpu1.c VAX/vax_fpa.c VAX/vax_io.c VAX/vax_cis.c VAX/vax_octa.c  VAX/vax_cmode.c VAX/vax_mmu.c VAX/vax_stddev.c VAX/vax_sysdev.c VAX/vax_sys.c  VAX/vax_syscm.c VAX/vax_syslist.c VAX/vax_vc.c VAX/vax_lk.c VAX/vax_vs.c VAX/vax_2681.c PDP11/pdp11_rl.c PDP11/pdp11_rq.c PDP11/pdp11_ts.c PDP11/pdp11_dz.c PDP11/pdp11_lp.c PDP11/pdp11_tq.c PDP11/pdp11_xq.c PDP11/pdp11_vh.c PDP11/pdp11_cr.c PDP11/pdp11_td.c PDP11/pdp11_io_lib.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -DVM_VAX -DUSE_INT64 -DUSE_ADDR64 -DUSE_SIM_VIDEO -I VAX -I PDP11 -DUSE_SHARED -I../windows-build/winpcap/Wpdpack/include -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -lIphlpapi -DHAVE_LIBSDL -ID:/windows-build/libSDL/SDL2-2.0.5/include -lSDL2 -LD:/windows-build/libSDL/SDL2-2.0.5/lib -o BIN/microvax3900.exe -lm -lwsock32 -lwinmm -lpthreadGC2 -L..\windows-build\pthreads\Pre-built.2\lib -lpcreposix -lpcre -L../windows-build/PCRE/lib/
sim_disk.c:2147:10: fatal error: ddk/ntddstor.h: No such file or directory
 #include <ddk/ntddstor.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
mingw32-make: *** [makefile:1650: BIN/microvax3900.exe] Error 1

**Comment by wboerhout** [comment]
With this mod, found in `sim_disk.c`, the vax and vax780 build succeed. Thanks!

**Comment by markpizz** [comment]
That says that the prior workaround (including the ddk files which have now somehow disappeared) is no longer necessary.  Meanwhile, I'd rather not make the change I just had you test since anyone who happens to have a slightly older MinGW environment (which has worked successfully for many years) will now have builds that fail using the latest simh code.

I've just committed a change which should work for both environments.  Please test this and close the issue if it does.

Thanks.

- Mark
