### ISSUE TITLE
What is the syntax for the "set console wru" command?

### ISSUE THREAD

**Issue by joeinwap** [simh/simh#488]
- #### Context

Want to change from Control-E to some other character
- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
Version 3.10 and 4.0; this does not appear to be a version dependent problem.
- #### how you built the simulator or that you're using prebuilt binaries

Both.
- #### the simulator configuration file (or commands) which were used when the problem occurred.

N/A
- #### the expected behavior and the actual behavior

It always says too few arguments.  Is the argument octal, decimal, hex, or carat (^E) form?
- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem
Need a pointer to a page that documents fully all the implemented commands.
For instance, how to send arbitrary control characters in the expect-send dialog.

**Comment by markpizz** [comment]
The syntax is:

```
sim> set console wru=nnn
```

Where nnn is the numeric value corresponding to the WRU.  It is specified in the default radix of the simulator you're using.

I'll look at enhancing the help to cover more details here.

As for "expect-send" details, see HELP EXPECT and at the prompt type "Escaping_String_Data", which probably can be abbreviated to "E"

**Comment by markpizz** [comment]
Added some extra info the the HELP SET CONSOLE making it consistent with sim_doc.doc.
