### ISSUE TITLE
Misuse of sdl*-config breaks Haiku build

### ISSUE THREAD

**Issue by mmuman** [simh/simh#489]
It seems recent changes in the makefile break building on Haiku:
```make
-DUSE_SIM_VIDEO `$(realpath $(dir $(call find_include,SDL2/SDL))../../bin/sdl2-config) --cflags`
```

You just can't assume sdl-config will be in ../../bin/ related to the header. This is wrong on Haiku and probably other platforms as well.
The very reason those config scripts exist is to actually find those headers btw, doing this is taking things in the wrong order.

**Comment by markpizz** [comment]
Well, that change wasn't made very recently.  It happened almost 20 months ago and has worked on all of the most popular host systems without any complaints.

So beyond saying what is wrong, please suggest what you think is right.  That would be helpful.

**Comment by mmuman** [comment]
Yes I meant to propose a patch but I wanted to raise the issue first. I didn't build for a while and didn't have any reason to expect any regression...
As for other platforms it's odd you didn't hit any corner case like on multiarch. Anyway, it's not how it's meant to be used.

**Comment by markpizz** [comment]
Once again you say "it's not how it's meant to be used".  

I'd much rather you explain how it is meant to be used (and refer to documentation describing this) and we discuss the details before you bother with a proposed patch.

**Comment by mmuman** [comment]
https://wiki.libsdl.org/FAQLinux#How_do_I_add_SDL_to_my_project.3F

> The short answer is use the output of the command "sdl-config --cflags --libs" for SDL 1.2 or "sdl2-config --cflags --libs", for example: gcc -o test test.c `sdl-config --cflags --libs` 

The way to detect SDL is to actually check for this command first, which tells where to find and how to use the headers and libs (--cflags and --libs also output -I with the path). Here you are probing for the SDL header at specific hardcoded locations, *then* also assuming the sdl-config command will be at a relative path from there. I already had to add the path for Haiku using quite complicated logic (with getarch), which actually shouldn't be needed since we make sure sdl-config outputs the correct path always.

The whole purpose of those *-config scripts, and pkg-config also which is a "meta" config script for other packages, is to get rid of hardcoding paths, and let the OS vendor provide them through the script output.
The only assumption you should make is that the correct sdl-config (the one for the target arch) is in the PATH, and if even this is wrong then it's the user's setup that's broken. Sadly some platforms miss sdl-config so there I suppose we should fallback to hardcoded paths, but then if they all work with the current code they must have sdl-config already.

So it should just all be done with:
```make
SDL_CFLAGS = $(shell sdl-config --cflags)
SDL_LIBS = $(shell sdl-config --libs)
SDL2_CFLAGS = $(shell sdl2-config --cflags)
SDL2_LIBS = $(shell sdl2-config --libs)
ifeq ($(SDL_CFLAGS)$(SDL2_CFLAGS),)
    $(error *** Cannot find SDL or SDL2)
endif
```
I think. And then appending this to the other defs.

**Comment by markpizz** [comment]
Does the latest code work for you now?  If so, please close this issue.

Thanks.

**Comment by mmuman** [comment]
Looks like it yeah, thanks much!

**Comment by markpizz** [comment]
Please test the build on Haiku again.

Thanks.

- Mark

**Comment by mmuman** [comment]
Hmm, typo: sdl2-config, not sdl2_config.

Is there any reason not to use this for other platforms? IMO it should be the default, and #493 confirmed it works better, and only if it fails fall back to the hardcoded list of paths.

**Comment by mmuman** [comment]
Oh, I didn't have sdl2-ttf installed...
Well, it's a different package than SDL2 itself. So it's quite logical it's not handled by sdl*-config.
It seems they only provide [a .pc file for use by pkg-config](https://packages.debian.org/stretch/amd64/libsdl2-ttf-dev/filelist).

**Comment by mmuman** [comment]
I'll try to propose a cleaner solution.

**Comment by mmuman** [comment]
Damn, now my revert commit is broken :D 

Btw, it seems pkg-config has sdl and SDL2 as well, with the added benefit of supporting cross-compiling.

**Comment by mmuman** [comment]
OTOH the typo fix makes it building again on Haiku.

**Comment by mmuman** [comment]
FWIW https://github.com/mmuman/simh/tree/sdl-detect works fine here. It doesn't address the /usr/local issue though.

**Comment by mmuman** [comment]
Btw, the current code finds SDL2 but tries to use SDL_ttf, not SDL2_ttf:

```
using libSDL2: /boot/system/develop/headers/x86/SDL2/SDL.h
...
using libSDL_ttf: /boot/system/develop/lib/x86/libSDL_ttf.a /boot/system/develop/headers/x86/SDL/SDL_ttf.h
```
