### ISSUE TITLE
Check for SDL_ttf does not use sdl2-config cflags

### ISSUE THREAD

**Issue by sandjo** [simh/simh#493]
- #### Context

The changes in #489 made the Makefile use my SDL2 installation without any special handling, thanks for making that change!

While building I noticed that the BESM-6 simulator couldn't find the SDL_ttf component. I don't use that simulator, but I thought I'd mention it anyway.

```
***
*** all  Simulators being built with:
*** - compiler optimizations and no debugging support. Apple LLVM version 9.0.0.
*** - dynamic networking support using OSX provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
***
*** git commit id is 243ee968fb5484ca7a780aa6ee7da8aa4a75077e.
***
*** No SDL ttf support available.  BESM-6 video panel disabled.
***
```

- #### how you built the simulator or that you're using prebuilt binaries

Just "make".

- #### the expected behavior and the actual behavior

I expected the build to find the SDL_ttf files using sdl2-config information. As an example

```
macos$ echo "#include <SDL_ttf.h>" | cc `sdl2-config --cflags` -E - >/dev/null
macos$ echo $?
0

macos$ echo "#include <SDL_ttf.h>" | cc -E - >/dev/null
<stdin>:1:10: fatal error: 'SDL_ttf.h' file not found
#include <SDL_ttf.h>
         ^~~~~~~~~~~
1 error generated.
```

**Comment by markpizz** [comment]
Please check with the latest code.

**Comment by mmuman** [comment]
SDL_ttf is a different library, and is packaged differently in Debian at least, and not handled by sdl*-config scripts, [they use pkg-config instead](https://packages.debian.org/stretch/amd64/libsdl2-ttf-dev/filelist).

**Comment by mmuman** [comment]
I guess you're on MacOS, did the SDL test actually work before anyway?

**Comment by sandjo** [comment]
The current Git master is now back to the previous behaviour where I have to include /usr/local/lib into LIBPATH to get SDL at all. So it is now consistent in what it finds.

I'm using Homebrew, and that installs under /usr/local/Cellar/{sdl2,sdl2_ttf}/<version>/ and then symlinks files into /usr/local. So in that case both the SDL2 and SDL_ttf packages are in the same directory, which made it a bit strange that it could find only one of them by default before. (And to be explicit, after #489 it did find SDL2 itself, now it is back to finding none.)

Current output:

```
macos$ make LIBPATH="/usr/lib /usr/X11/lib /usr/local/lib"
[...]
***
*** all  Simulators being built with:
*** - compiler optimizations and no debugging support. Apple LLVM version 9.0.0.
*** - dynamic networking support using OSX provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
***
*** git commit id is 5ac4aaa1d49e025286cd1bad0dab3f5ad43e2036.
***
font paths are: /Library/Fonts/ /System/Library/Frameworks/JavaVM.framework/Versions/
font names are: DejaVuSans.ttf LucidaSansRegular.ttf FreeSans.ttf AppleGothic.ttf tahoma.ttf
```

and without setting LIBPATH the usual

```
macos$ make
[...]
***
*** all  Simulators being built with:
*** - compiler optimizations and no debugging support. Apple LLVM version 9.0.0.
*** - dynamic networking support using OSX provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
***
*** git commit id is 5ac4aaa1d49e025286cd1bad0dab3f5ad43e2036.
***
*** No SDL ttf support available.  BESM-6 video panel disabled.
***
```

**Comment by markpizz** [comment]
The current behavior is intentional.

The reason being that /usr/local is where things land when users download and build things themselves which is what we explicitly don't want to support.  It is unfortunate that HomeBrew puts stuff in /usr/local and as such we can't distinguish a properly packaged component from one potentially improperly built by a user.

**Comment by markpizz** [comment]
Read the later comments in #489.  The original fix to that issue had the unintended consequence of accidentally picking components up from the current user path rather than packages which have explicitly been installed by a proper package manager.

**Comment by mmuman** [comment]
Hmm, if it was detected with the config script then it is by all mean intentional too. I mean, if /usr/local/bin is in the PATH and sdl2-config is found there, then it is the user's intention to have it used. At least I'd think so.

What is the rationale behind blacklisting /usr/local? Is it due to it being picked up when packaging? Maybe packaging should be done in a chrooted environment, or maybe just a cleaned up $PATH... At least most software I know do use those config scripts and it doesn't cause any problem even for Debian packaging.

**Comment by sandjo** [comment]
I'm sorry, but I have to nitpick a bit about not being able to detect Homebrew installed SDL2. You can always use the package manager to get the non-symlinked name for sdl2-config.

An example with the current version of SDL2:

```
$ brew ls sdl2 | grep bin/sdl2-config
/usr/local/Cellar/sdl2/2.0.7/bin/sdl2-config
```

Would that be a possible solution?
