### ISSUE TITLE
VH not functional with 4.2BSD

### ISSUE THREAD

**Issue by hbent** [simh/simh#494]
This is pretty straightforward.  Boot the 4.2BSD generic kernel with a VH at the address it expects (160020) and attach it to a remote port.  On boot numerous "dh0: silo overflow" lines are produced, and the same happens on an attempt to connect remotely.  I tried setting the serial lines to both 9600 and 1200 baud with no success.

A 4.2BSD disk image that can replicate the problem is here, root password is alpine.  Driver source is in /usr/sys/vaxuba/dh.c
https://www.dropbox.com/s/xqdwrnfuksdblbr/42bsd.tar.xz?dl=0

sim> show version
VAX 11/780 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 6
    Host Platform:
        Compiler: GCC 7.2.0
        Simulator Compiled as C arch: x64 (Release Build) on Nov 25 2017 at 20:44:52
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux aelfric 4.14.0-gentoo #1 SMP Thu Nov 16 15:55:57 EST 2017 x86_64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz GenuineIntel GNU/Linux
        git commit id: df54c87b

Configuration:
set cpu idle=ultrix-1.x
set tti 7b
set tto 7b
set cr disabled
set lpt disabled
set rp disabled
set rl disabled
set hk disabled
set dz disabled
set vh enabled
set vh lines=16
att vh 420
set vh ADDRESS=2013E010
set rq1 disabled
set rq2 disabled
set rq3 disabled
set ry disabled
set tu disabled
set tq disabled
set rq0 ra81
att rq0 42bsd-ra81.dsk
set xu enabled
set xu type=deuna
set xu mac=02:07:01:00:00:A2
att xu tap:tap3
load -o boot42 0
dep r10 9
dep r11 0
run 2

**Comment by markpizz** [comment]
Well, the tarball you provided via dropbox has the following:
```
root@mark-VirtualBox:/media/sf_U_Drive/nnn/simh/vax/42bsd#root@mark-VirtualBox:/media/sf_U_Drive/nnn/simh/vax/42bsd# tar tvf 42bsd.tar.xz -rw-r--r-- root/root 456228864 2014-09-06 23:42 ra81.dsk
-rw-r--r-- root/root      6600 2014-07-13 12:02 boot42
-rw-r--r-- root/root       465 2017-11-27 14:46 vax780.ini
root@mark-VirtualBox:/media/sf_U_Drive/nnn/simh/vax/42bsd# 
$ tar tvf 42bsd.tar.xz 
-rw-r--r-- root/root 456228864 2014-09-06 23:42 ra81.dsk
-rw-r--r-- root/root      6600 2014-07-13 12:02 boot42
-rw-r--r-- root/root       465 2017-11-27 14:46 vax780.ini
```
vax780.ini contains what you've posted above.
vax780.ini attaches 42bsd-ra81.dsk which although it doesn't exist, might be a copy of the tarball's ra81.dsk file.  So, I try that, but the kernel in that disk image boots as one might expect, but it doesn't seem to be touching the vh device.  Additionally, the OS on the provided ra81.dsk doesn't have a root password, so your directions and the data file you provided don't seem to align.  I modified the vax780.ini file slightly to demonstrate the lack of access to the VH device:

```
set cpu idle=ultrix-1.x
set tti 7b
set tto 7b
set cr disabled
set lpt disabled
set rp disabled
set rl disabled
set hk disabled
set dz disabled
set vh enabled
set rq1 disabled
set rq2 disabled
set rq3 disabled
set ry disabled
set tu disabled
set tq disabled
set rq0 ra81
copy ra81.dsk 42bsd-ra81.dsk
att rq0 42bsd-ra81.dsk
set xu enabled
set xu type=deuna
set xu mac=02:07:01:00:00:A2
att xu tap:tap3
set vh lines=16
set vh ADDRESS=2013E010
att vh 1420
! nohup xterm -e 'telnet localhost 1420' &
sleep 10s
set vh debug
set debug stdout
load -o boot42 0
dep r10 9
dep r11 0
run 2
```

**Comment by hbent** [comment]
Ah, sorry about that, I put the wrong disk image in the tarball.  Here is the correct one: https://www.dropbox.com/s/gvpjd5lqvachbi2/42bsd.tar.xz?dl=0

**Comment by markpizz** [comment]
I'm thinking that the driver you're using is a driver for a DH11 MUX device while the VH device simulates a DHU11.  They have different programming interfaces and thus you can't control a DHU11 with a DH11 device driver.  

The clue to you should have been the fact that you needed to explicitly set the device address to the DH11 device address.

**Comment by hbent** [comment]
Sheesh.  I am really off lately.  No problems here, and my apologies for the noise.
