### ISSUE TITLE
Commit b2b18de0ec breaks PDP-8 throttling

### ISSUE THREAD

**Issue by tangentsoft** [simh/simh#508]
On updating from the April-ish version of SIMH which our prior stable version was based on to the tip of master as of a few days ago in preparation for a new stable release of the PiDP-8/I software, we began to notice that the PDP-8 simulator would not handle fixed throttle values correctly any more.

One symptom is that keyboard input has long delays between each character, roughly half a second per keystroke on some platforms. Simple test case:

    $ BIN/pdp8 os8.script
    .DIR

Here's `os8.script`:

    set cpu 32k
    set cpu noidle
    set df disabled
    set throttle 333k
    set tti 7b
    att rk0 os8v3d-patched.rk05
    boot rk0

The `set throttle 333k` line is meant to roughly mimic the instruction execution rate of a PDP-8/I. Justification of that value is [here](https://tangentsoft.com/pidp8i/doc/trunk/README-throttle.md).

You can get the `os8v3d-patched.rk05` file [from our site](https://tangentsoft.com/pidp8i/uv/os8v3d-patched.rk05). That RK05 disk image is probably more featureful and less crufty than any others you have there to test with, by the way. See [our docs for these new disk images](https://tangentsoft.com/pidp8i/doc/trunk/README.md#os8di) for details. Feel free to use these for future testing.

Back to the report:

If you type the `DIR` command several times, the simulator starts behaving eventually, but if you then hit <kbd>Ctrl-E</kbd> and say `SHOW CLOCK` you will see that the simulator's IPS rate is nowhere near the requested 333k IPS value.

This symptom has been seen on an iMac running macOS 10.12.6, on an Ubuntu 16.04 VM, and on one Pi 3, but not on another one we tried it on. The Pi not showing the problem is running Raspbian Stretch. I'm not sure what the Pi showing the problem is running, but it may well still be running Raspbian Jessie, which may explain the difference in behavior.

On bisecting the repo history, we find that the problem was introduced with commit b2b18de0ec. Not only does the problem go away on reverting to the checkin just prior, reverting just that change against the current repository version also fixes both symptoms reported above.

I say that this affects "fixed-rate throttling" because it doesn't affect something like `set throttle 10%`. That continues to behave the same with this change as without.

**Comment by tangentsoft** [comment]
This does seem to have fixed the keyboard delay issue.

However, I'm not wild about a few aspects of the implementation.

---------

First, 20 seconds is uncomfortably long. I'd be willing to put up with about 3 seconds for interactive simulator startups, more for automatic startups.

I tried adding this to the SIMH startup script to achieve that:

    de THROT_DELAY 3

It complains, "Invalid argument". If I wait 20 seconds, hit <kbd>Ctrl-E</kbd> and repeat the command, it still complains, so I'm apparently not using the right syntax. I've re-read parts of the SIMH manual and tried to find the correct syntax by poking around with `SHOW` commands, but I've failed to figure it out so far.

I like the idea of this being a register, open to modification at run time, not only so I don't have to change the code to get the behavior that I want, but also because I can see that I might want different values in different conditions. [My other open issue](#429) gives one case, for example.

---------

Second, the checkin comment's claim that this register is initially inaccessible seems like undesirable behavior to me. I'd like to be able to set a custom value from the start via the SIMH init script.

---------

Third, if you hit <kbd>Ctrl-E</kbd> (say, to call `show clock`) then continue, the throttle opens wide again and it takes another 20 seconds to recalibrate. Yet, you must do just that in order to change this `THROT_DELAY` register, effectively doubling the delay in the current scheme.

Allowing the user to set the initial `THROT_DELAY` value from the SIMH init script will solve part of that. As for the rest, I propose that once the throttling timer values are known, they are preserved as best-guess initial values when the simulator is reentered, even if a `SET THROTTLE` value was given. Unless conditions have changed wildly, the previous timer values are probably better starting points than the point of ignorance the simulator starts with now. [Bayes and all that](https://en.wikipedia.org/wiki/Bayes%27_theorem), yes?

In fact, I could even see cutting the `THROT_DELAY` value in this case, so that the full delay is taken only the first time. If by the third recalibration point the timer values don't change substantially, the simulator can start cutting the `THROT_DELAY` value until it hits some reasonable minimum. Say, several hundred milliseconds, or maybe a full second.

If a `SET THROTTLE` command is given, maybe the `THROT DELAY` value goes back up again for a while until the new timer values are found.

**Comment by tangentsoft** [comment]
@markpizz: Was the 20 second default found empirically? If so, maybe you can suggest a way I can double-check it here.

I've just checked in a change to our SIMH init scripts to change our `THROT_DELAY` value to 3 seconds, but if I can be convinced that it needs to be longer, I can certainly change it again and document the reason for the new value.

**Comment by markpizz** [comment]
The 20 delay second value comes from the more generic needs of other simulators.  Some of these run their initial boot code from ROM and the ROM memory access is deliberately slowed down to a max of about 1 usec per memory reference.  This indirectly throttles the system's instruction execution behavior while running from ROM.  This ROM throttling is achieved by CPU spinning during the ROM memory references.  Once ROM based execution is no longer in the picture, the sleep based throttling can be calibrated and then engaged.

For the PDP8 simulator, a value of 3 is certainly reasonable.

**Comment by tangentsoft** [comment]
Thanks, Mark.

I'll let you close this or not, depending on whether you're going to implement my Bayesian estimation idea or not.

**Comment by markpizz** [comment]
Well, a Bayesian estimation is far more complicated than what is necessary.  

After thinking about this, I realize that the current logic evaluates the throttling effectiveness every 10 seconds.  If the effective execution rate is close enough (withing THROT_DRIFT_PCT percent), then nothing changes.  If not, then the delay parameters are adjusted to move in the right direction.  

As you say, the initial work to determine the base delay parameters has been done immediately after THROT_DELAY seconds, so the running values are certainly a good starting point to use when instruction execution is resumed after a CTRL-E.  Calibration will only start over if the user changes the throttling mode/rate.

Please confirm that the latest code performs as you desire.

**Comment by tangentsoft** [comment]
The new recalibration avoidance seems to be working, but I now see that I did not test the prior change well enough. 

These recent changes of yours work okay on the Pi, but on my far faster iMac, I get a bad symptom which I expect you can see on any fast host, not just a macOS one. You can see the symptom by running with [our patched OS/8 disk pack](tangentsoft.com/pidp8i/#os8) plus this init script:

<pre>set cpu 32k
set cpu noidle
set df disabled
set throttle 333k
deposit int-throttle THROT_DELAY 3
set tti 7b
att rk0 os8v3d-patched.rk05
boot rk0</pre>

Simply give OS/8 the `DIR` command repeatedly. For the first three seconds, the directory comes up fast, as you'd expect, but then it slows to a crawl, far slower than it should be. Inter-keyboard delay slows to *several seconds* initially, then shortens over about the course of about half a minute to the nearly-imperceptible value it should have at 333 kIPS.

At the point where OS/8 starts feeling normal, the IPS rate is still well under the target value:

<pre>Minimum Host Sleep Time:       1 ms (1000Hz)
Host Clock Resolution:         1 ms
Execution Rate:                159,600 cycles/sec
Throttle:                      333 kilocycles
Throttling by sleeping for:    1 ms every 358 cycles
Calibrated Timer:              CLK
Calibration:                   Always

PDP-8 clock device is CLK
Calibrated Timer 0:
  Running at:                60 Hz
  Tick Size:                 16.667 msecs
  Ticks in current second:   55
  Seconds Running:           7 (7 seconds)
  Calibration Opportunities: 7
  Instruction Time:          200829947
  Current Insts Per Tick:    2,660
  Initializations:           4
  Ticks:                     473
  Tick Time:                 7.866667 seconds
  Initialize Base Time:      14:04:58.813
  Tick Start Time:           14:04:58.813
  Wall Clock Time Now:       14:05:26.956
</pre>

It doesn't get up to the requested 333 kIPS value until about a minute later.

It seems that on that first `THROT_DELAY` timer event, you are not simply dividing the instructions executed by `THROT_DELAY` and then using that to calculate the starting timer values, but are instead using some kind of feedback loop mechanism which sees that it's been running far too many IPS, undershoots badly, and then craws slowly back up to the requested throttle value.

This guess is supported by the fact that the symptom is far less severe on the Pi. I believe it is because the unthrottled IPS rate is about 1/10 that of my iMac, so it undershoots much less.

I've scrawled a crude graph to show what I'm talking about:

![ips](https://user-images.githubusercontent.com/5102038/35414055-99fa1370-01de-11e8-989f-769e510472c1.png)

**Comment by tangentsoft** [comment]
Is is the case that the number of iterations of `sim_instr()` in `pdp8_cpu.c` is equal to the number of instructions executed by the simulator? If so, then I suspect that the "cycles" line in `SHOW CLOCK` output is being calculated incorrectly.

This comes about because I got a surprise when, out of embarrassment over the crudity of the above graph, I decided to instrument the simulator to produce raw data I could feed to a plotting program. I got this raw data on my iMac:

<pre>1, 6.49
2, 74.22
3, 75.35
4, 39.13
5, 0.31
6, 0.31
7, 0.31
8, 0.31
9, 0.31
10, 0.31
11, 0.31
12, 0.31
13, 0.31
14, 0.32
15, 0.33</pre>

That's seconds of run time against MIPS, calculated as the number of passes through `sim_instr()` since the last second's output. This is nearly free for us to produce because we calculate IPS — as passes through the `sim_instr()` loop — as part of our front panel updating code. All we're paying for here is the `printf()` call.

The first value is off not only because the simulator has just started up but also because it's based on the return value of C's `time()` library function, so the first data point is a measurement for the fraction of a second until the seconds counter clicks over for the first time.

This crude timebase also explains the odd value on line 4: it's giving MIPS across the transition between the unthrottled and throttled states, averaging the two values, biased by the fraction of a second where the actual transition time occurs. I must have started the simulator about half a second after `time_t` on this machine last clicked over.

One thing that worries me is that this data doesn't show the severe undershoot I expected. There's a bit, but nowhere near enough to explain the slow keyboard input handling. I don't even see the 0.15 MIPS sort of value I'd expect from the `SHOW CLOCK` output in the prior comment.

Here's another worrying bit of output from a later run:

<pre>2, 74.87
Simulation stopped, PC: 01210 (JMP 1207)
sim> show clock
Minimum Host Sleep Time:       1 ms (1000Hz)
Host Clock Resolution:         1 ms
Execution Rate:                104,106,300 cycles/sec</pre>

The first line was emitted by my instrumentation code. That is, I started the simulator, then let it run for a few seconds to get past the timebase problem that causes the first data point to be too low. I then interrupted the simulation with a <kbd>Ctrl-E</kbd> and asked SIMH what *it* thought the IPS rate was. Why does `SHOW CLOCK` show a value so much higher than my instrumentation?

Could the cause behind this discrepancy also be affecting the scheduling of keystroke delivery to the simulator? I now believe that the PDP-8 KSF instruction is being executed ~160 kIPS immediately after `THROT_DELAY` seconds, so why is the inter-keystroke delay so large?

(The OS/8 keyboard input loop is a KSF instruction followed by JMP .-1 — jump to previous instruction — so it's a 50/50 mix of those two instructions. On keystroke delivery to the simulator, it must then execute a great many instructions to actually process that keystroke, but that code's been debugged for decades, so we can rule it out as the source of the problem.)

**Comment by markpizz** [comment]
Very nice graph!  🥇 :-)

There are two calibration activities going on.  The interval between the system's clock ticks, AND the sleep vs instruction execution rate for throttling.

In any case, what I think is happening is that during the early activities (before THROT_DELAY), the clock ticks are being calibrated at the FAST rate.  Some factor on the clock tick (usually 1 or 2) is used for keyboard input polling.   Once the throttling kicks in, the interval to the next (and future) tick(s) is potentially very excessive and that polling happens after the initial large number of instructions executed, but after THROT_DELAY, those instructions are being executed with periodic throttling sleeps (and the polls happen way too far apart).  Eventually, the clock ticks adjust to reasonable values based on the new throttled execution rate and tick intervals settle down.  Some more analysis/adjustment of the tick calibration is needed to avoid the lag you're seeing once throttling kicks in (or when it is dynamically adjusted).

FYI, the simulator plumbing is instrumented with debug code that help understand what is happening:

     sim> set debug somefile
     sim> set int-clock debug=throt;calib

**Comment by tangentsoft** [comment]
Here's the instrumentation output resulting from the commands you gave:

<pre>Debug output to "/Users/tangent/Desktop/os8-333k.dat"
Debug output to "/Users/tangent/Desktop/os8-333k.dat" at Sat Jan 27 05:22:01 2018
PDP-8 simulator V4.0-0 Beta        git commit id: 11df2a2f
DBG(8333)> INT-CLOCK CALIB: sim_rtcn_init_unit(unit=CLK, time=16000, tmr=0)
DBG(8333)> INT-CLOCK CALIB: _rtcn_configure_calibrated_clock(newtmr=0) - Starting Internal Calibrated Timer at 10Hz
DBG(8333)> INT-CLOCK CALIB: sim_rtcn_init_unit(unit=INT-TIMER, time=50000, tmr=8)
DBG(8333)> INT-CLOCK CALIB: sim_rtcn_init_unit(unit=CLK, time=16000, tmr=0)
DBG(9333)> INT-CLOCK THROT: sim_throt_svc(INIT) Deferring until stable (3 more seconds)
DBG(16666)> INT-CLOCK CALIB: _rtcn_configure_calibrated_clock(newtmr=0) - Stopping Internal Calibrated Timer, New Timer = 0 (60Hz)
DBG(509333)> INT-CLOCK THROT: sim_throt_svc(INIT) Deferring until stable (3 more seconds)
DBG(960607)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=800000, nxintv=1500, result: 1200000)
DBG(1469333)> INT-CLOCK THROT: sim_throt_svc(INIT) Deferring until stable (2 more seconds)
DBG(72957727)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=1121495, nxintv=1500, result: 1682242)
DBG(73469333)> INT-CLOCK THROT: sim_throt_svc(INIT) Deferring until stable (1 more seconds)
DBG(173888167)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=1259163, nxintv=1500, result: 1888744)
DBG(174403853)> INT-CLOCK THROT: sim_throt_svc(INIT) Computing Throttling values based on the last second's execution rate
DBG(174403853)> INT-CLOCK THROT: sim_throt_svc() Throttle values a_cps = 75606382.022472, d_cps = 333000.000000, wait = 334, sleep = 1 ms
DBG(174736853)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=1747219, nxintv=1493, result: 2608597)
DBG(177496359)> INT-CLOCK THROT: sim_throt_svc() Recalibrating throttle based on values a_cps = 309250.600000, d_cps = 333000.000000 deviating by 7.13% from the desired value
DBG(177496359)> INT-CLOCK THROT: sim_throt_svc() Adjusting wait before sleep interval by 23
DBG(177496359)> INT-CLOCK THROT: sim_throt_svc() Throttle values a_cps = 309250.600000, d_cps = 333000.000000, wait = 357, sleep = 1 ms
DBG(177823809)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=262038, nxintv=500, result: 131019)
DBG(185684589)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5443, nxintv=500, result: 2721)
DBG(185847849)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5497, nxintv=500, result: 2748)
DBG(186012729)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5368, nxintv=500, result: 2684)
DBG(186173769)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5314, nxintv=500, result: 2657)
DBG(186333189)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5501, nxintv=500, result: 2750)
DBG(186498189)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5320, nxintv=500, result: 2660)
DBG(186657789)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5352, nxintv=500, result: 2676)
DBG(186818349)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5472, nxintv=500, result: 2736)
DBG(186982509)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5292, nxintv=500, result: 2646)
DBG(187141269)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5345, nxintv=500, result: 2672)

Simulation stopped, PC: 01207 (KSF)
sim> q
Goodbye
</pre>

I let it run here on this Mac just until keyboard I/O started feeling reasonably delay-free.

Are you able to reproduce the symptom there with the init script and disk pack I've provided?

**Comment by markpizz** [comment]
I see the behavior.  I just wasn't using the PDP8 side of things (i.e. typing into its console) when I tested before.  I was looking at the throttling adjustments in the debug log data, not the clock calibration activities.

FYI, the debug command I gave you above will produce more useful information this way:

    sim> set debug -anp somedebugfile
    sim>set int-clock debug=throt;calib

- The -a switch includes the wall clock time with each debug line written.  This is very useful when looking at timing activities.
- The -n switch causes the debug file to start over when the command is executed.  The default is to append to the indicated file.
- The -p switch causes the simulated system's PC value to be includes in each line of the debug output.  This probably isn't useful for this problem, but it doesn't hurt.

**Comment by tangentsoft** [comment]
Here you go:

<pre>Debug output to "/nunya/binness/os8-333k.txt" at Sat Jan 27 21:52:28 2018
PDP-8 simulator V4.0-0 Beta        git commit id: 11df2a2f
DBG(1517115148.960 8333-PC:00000)> INT-CLOCK CALIB: sim_rtcn_init_unit(unit=CLK, time=16000, tmr=0)
DBG(1517115148.960 8333-PC:00000)> INT-CLOCK CALIB: _rtcn_configure_calibrated_clock(newtmr=0) - Starting Internal Calibrated Timer at 10Hz
DBG(1517115148.960 8333-PC:00000)> INT-CLOCK CALIB: sim_rtcn_init_unit(unit=INT-TIMER, time=50000, tmr=8)
DBG(1517115148.960 8333-PC:00023)> INT-CLOCK CALIB: sim_rtcn_init_unit(unit=CLK, time=16000, tmr=0)
DBG(1517115148.960 9333-PC:00023)> INT-CLOCK THROT: sim_throt_svc(INIT) Deferring until stable (3 more seconds)
DBG(1517115148.961 16666-PC:00023)> INT-CLOCK CALIB: _rtcn_configure_calibrated_clock(newtmr=0) - Stopping Internal Calibrated Timer, New Timer = 0 (60Hz)
DBG(1517115148.979 509333-PC:00023)> INT-CLOCK THROT: sim_throt_svc(INIT) Deferring until stable (3 more seconds)
DBG(1517115149.001 960607-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=390243, nxintv=1500, result: 585364)
DBG(1517115149.011 1469333-PC:00023)> INT-CLOCK THROT: sim_throt_svc(INIT) Deferring until stable (2 more seconds)
DBG(1517115149.731 36081007-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=801869, nxintv=1500, result: 1202803)
DBG(1517115149.740 36591173-PC:00023)> INT-CLOCK THROT: sim_throt_svc(INIT) Deferring until stable (1 more seconds)
DBG(1517115151.115 108246247-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=869077, nxintv=1500, result: 1303615)
DBG(1517115151.126 108759353-PC:00023)> INT-CLOCK THROT: sim_throt_svc(INIT) Computing Throttling values based on the last second's execution rate
DBG(1517115151.126 108759353-PC:00023)> INT-CLOCK THROT: sim_throt_svc() Throttle values a_cps = 52069393.939394, d_cps = 333000.000000, wait = 335, sleep = 1 ms
DBG(1517115152.199 109092353-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=1202597, nxintv=1500, result: 1803895)
DBG(1517115161.126 111922423-PC:00023)> INT-CLOCK THROT: sim_throt_svc() Recalibrating throttle based on values a_cps = 316307.000000, d_cps = 333000.000000 deviating by 5.01% from the desired value
DBG(1517115161.126 111922423-PC:00023)> INT-CLOCK THROT: sim_throt_svc() Adjusting wait before sleep interval by 16
DBG(1517115161.126 111922423-PC:00023)> INT-CLOCK THROT: sim_throt_svc() Throttle values a_cps = 316307.000000, d_cps = 333000.000000, wait = 351, sleep = 1 ms
DBG(1517115162.164 112249873-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=181023, nxintv=500, result: 90511)
DBG(1517115178.861 117680293-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5420, nxintv=500, result: 2710)
DBG(1517115179.357 117842893-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5463, nxintv=500, result: 2731)
DBG(1517115179.879 118006753-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5232, nxintv=500, result: 2616)
DBG(1517115180.368 118163713-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5349, nxintv=500, result: 2674)
DBG(1517115180.852 118324153-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5525, nxintv=500, result: 2762)
DBG(1517115181.371 118489873-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5322, nxintv=500, result: 2661)
DBG(1517115181.867 118649533-PC:00023)> INT-CLOCK CALIB: calibrated tmr=0, tickper=60 (base=5364, nxintv=500, result: 2682)

Simulation stopped, PC: 01210 (JMP 1207)
sim> q
Goodbye</pre>

**Comment by markpizz** [comment]
I'll think about the per line time delta.  There already is an option (-R) to have the displayed time values start at 0 at the beginning of the debug output.  The details in each line include the instruction execution count since the simulator started, so if per line time delta were implemented it would also have to affect the instruction count.  Maybe...

Meanwhile, the latest code fully synchronizes the calibrated clock(s) with the throttling rate once when throttling actually starts (after THROT_DELAY).

Let me know if you see any more unexpected behavior.

**Comment by tangentsoft** [comment]
Yep, that's finally got the bug squished. Thank you!

**Comment by tangentsoft** [comment]
I'm reopening this because one of my users has discovered another unwanted side effect of the new timing code. Basically, the new timing code doesn't handle large jumps between throttle rates at run time very well.

Start the PDP-8 simulator with this init script:

<pre>set tti 7b
set cpu 32k
set cpu noidle
set df disabled
set throttle 1/10
deposit int-throttle THROT_DELAY 3
att rk0 os8v3d-patched.rk05
boot rk0</pre>

Nothing will appear to happen, since 100 IPS is way too slow to get even the first character of the boot message out to the console before `THROT_DELAY` is passed.

Wait that delay out to let the throttle become established, then hit <kbd>Ctrl-E</kbd>, say `set throttle 333k` then `cont`, and observe that the boot message doesn't start printing until about 45 seconds later, rather than start printing immediately as it should, now that we're up at real PDP-8 speeds. When the boot message does start printing, it prints at only about 1-2 characters per second rather than the hundreds of CPS it should achieve at that IPS rate.

After the boot message finishes printing out, `show clock` says:

<pre>Minimum Host Sleep Time:       1 ms (1000Hz)
Host Clock Resolution:         1 ms
Execution Rate:                960,000 cycles/sec
Throttle:                      333 kilocycles
Throttling by sleeping for:    1 ms every 1 cycles
Calibrated Timer:              CLK
Calibration:                   Always

PDP-8 clock device is CLK
Calibrated Timer 0:
  Running at:                60 Hz
  Tick Size:                 16.667 msecs
  Ticks in current second:   7
  Seconds Running:           0 ()
  Calibration Opportunities: 0
  Current Insts Per Tick:    16,000
  Initializations:           5
  Ticks:                     6
  Tick Time:                 100 msecs
  Initialize Base Time:      19:01:40.241
  Tick Start Time:           19:01:48.797
  Wall Clock Time Now:       19:03:47.532
</pre>

Execution rate is claimed to be 3x higher than the throttle rate, yet it's demonstrably SSSLLLOOOOWWW.

Lest you think the problem comes from starting with an exceptionally slow throttle rate, you can try the following more complicated test case, which ends up showing the same symptom. Start with the above init script, but change the `1/10` bit to `333k`. Then:

1. Type `DIR` as soon as OS/8 is booted; observe that it completes near-instantaneously because it's still unthrottled.
2. Wait out `THROT_DELAY`
3. Type `DIR`; observe that it takes a few seconds to complete now.
4. <kbd>Ctrl-E</kbd>, `set throttle 1/10`, `cont`
5. Wait out `THROT_DELAY` again
6. <kbd>Ctrl-E</kbd>, `set throttle 333k`, `cont`
7. Wait out `THROT_DELAY` again
8. Type `DIR` again

The same symptom results.

**Comment by markpizz** [comment]
You're mixing two completely different throttling modes which causes the effect.  I'll change things to reset the throttling system completely each time you explicitly change throttling with a command.  

Meanwhile, your description about dramatic change in throttling rate being the cause would be better tested with:
     set throttle 1k
     Run for more than THROT_DELAY
     Ctrl-E and
     set throttle 1m
     Run for more than THROT_DELAY

Look at the clock numbers at various points.  If this is behaves reasonably, I'll only reset the throttling system if the throttling mode is changed.  Let me know.

**Comment by tangentsoft** [comment]
With that test, it takes a bit over a minute to slew in steps from the starting IPS to the target IPS rate. It seems to re-check its IPS rate about every 10 seconds and correct its delay values again. Here's another graph, slightly nicer this time:

<img width="521" alt="mips-vs-secs" src="https://user-images.githubusercontent.com/5102038/36014257-095a32c0-0d26-11e8-945b-cae05b4cd3d0.png">

It's seconds on the X axis, MIPS on the Y.

**Comment by markpizz** [comment]
During that transition from slow to fast was there anything unusual about how the rest of the system behaved (i.e. is it demonstrably SSSLLLOOOOWWW)?

**Comment by tangentsoft** [comment]
Other than feeling increasingly fast, no. You can definitely tell how much faster it's getting when it shifts to a new IPS rate.

**Comment by tangentsoft** [comment]
In this specific case, my user is starting the simulator at PDP-8 equivalent speed, starting a program, then throttling way down (`1/10`) to turn its execution into a blinkenlights demo. If he started the simulator at `1/10` to begin with, he'd be waiting days just for the "run the demo program" command to be executed. The shift back from `1/10` to `333k` is to iterate on the demo, modifying things at normal interactive speed before returning to demo speed.

Another case might be that someone chooses to run unthrottled most of the time but occasionally needs to shift down to PDP-8 equivalent speeds for much the same sort of reasons that old PCs had "turbo" buttons.

It shouldn't take over a minute to slew from one value to another. That's why I brought up PID controllers: that and other applications of control theory apply greater amounts of correction given greater errors. Properly engineered — and here, the word is properly used, since it's using mathematics originally developed for applied physics — a control loop can correct quickly without overshoot.
