### ISSUE TITLE
Question: Running without host operating system?

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#517]
I have the impression that SIMH is made to run in a hosting operating system.  I have an application in mind running a simulator in an embedded environment, possibly with no OS or a small RTOS.  How much in terms of OS support does SIMH need?

**Comment by markpizz** [comment]
simh indeed needs a good number of things from a host OS.

It does not require a GUI user interface unless you want to run a simulator (and device) which specifically provides a graphical device simulation.

A standard C runtime library is a requirement.  

Depending on the simulator and the devices you will be simulating, standard networking APIs will be needed.  If you're going to have networking, then libpcap and the related kernel facilities will be needed,

additionally pthreads are needed for a number of things.

Given the plethora of minimal embedded platforms which run Linux and/or Windows Embedded, these should work just fine.  Trying to run under a different OS would be a porting exercise.

**Comment by larsbrinkhoff** [comment]
I'm thinking minimal as in parts without MMU.  I take it porting to one of those would be a big task indeed.  More work than I can handle in my spare time.

Thanks!
