### ISSUE TITLE
External bus interface

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#518]
Hello,

@rcornwell's KA10 simulator is getting ready.  At MIT, there were PDP-11s connected to the PDP-10 memory and I/O buses.  The 11s acted as dedicated I/O processors.  Some of us are interested in recreating configurations similar to this.  For example, MIT-AI had an PDP-11 connected to control a number of graphical terminals called Knight TVs.  And another PDP-11 for CHAOS networking.

To hook up separate simulator processes this way, I suppose there should be some kind of bus interface for SIMH.  The interface would have to support memory transfers, interrupt signals, etc.

Would it be feasible to create such a bus interface?

**Comment by larsbrinkhoff** [comment]
CC @aap

**Comment by mgthompson** [comment]
This would be an interesting capability have in SIMH. Most DEC systems supported bus interfaces to other DEC systems, so hopefully the SIMH "bus interface" would be generic.

**Comment by larsbrinkhoff** [comment]
I copied this message to the mailing list.  I will post a summary of the discussion here.

**Comment by markpizz** [comment]
This is a good suggestion and it is already a work in progress.  The results will allow various combinations of message passing, interrupt signals, shared memory.

**Comment by aap** [comment]
For the 10-11 interface on the AI KA10 the only thing we need is memory access to a unibus i believe. no interrupts or anything fancy. I don't know how the interface actually works yet, but I've seen no interrupts in the code that uses it.

**Comment by markpizz** [comment]
The facility will be a generic part of the SCP framework.  The set of device simulations that use it (i.e. one on each side of the computer to computer links) will get to configure which of the 'features' it needs.  These capabilities will coherently be integrated to be well behaved when the simulator is idling and to support asynchronous signalling of interrupts and/or message arrival.

**Comment by larsbrinkhoff** [comment]
Wow, that was quick!  I guess I can close this then.

**Comment by rcornwell** [comment]
@aap the DL10, DA10 and DTE10 all could interrupt. The 10 could interrupt the 11 and the 11 could interrupt the 10. Also the 10 could modify 11 memory.
