### ISSUE TITLE
Alpha Emulator CD-ROM and Hard Disk Support

### ISSUE THREAD

**Issue by vincrusher** [simh/simh#520]
I can't use a CD-ROM or a Hard Disk on the Alpha Emulator to install an old OS.
I tried the directions in the Documention and it said "Non-existent Device" when trying to load one.

I tried this with the latest source code and no luck.

**Comment by vincrusher** [comment]
I just tried the latest source code from the last commit as of now and still doesn't work.
Will somebody please help fix this?

**Comment by markpizz** [comment]
The Alpha simulator code is currently just a CPU simulator without any devices being simulated.  Someone has been working on filling in the missing pieces, but that is a very long term project and no where near useful for running any OS.  Look elsewhere for a complete Alpha simulator.  FreeAXP might be useful for you.  Good Luck.
