### ISSUE TITLE
vax780, vax8600: SEGFAULT booting VMS with a DMC device attached

### ISSUE THREAD

**Issue by jguillaumes** [simh/simh#528]
The vax7* and vax8600 simulators crash with a SEGFAULT (signal 11) when trying to boot VMS with a DMC device attached.

#### Context

The simulators crash at boot, just after showing the VAX/VMS version message:

```
$ vax750 vax780.ini

VAX 11/750 simulator V4.0-0 Beta        git commit id: abfb828c
vax780.ini-3> attach todr todr_clock.dat
TODR: buffering file in memory
RQ0: 'RA81.000' Contains ODS2 File system
RQ0: Volume Name: VAXVMSRL4    Format: DECFILE11B   Sectors In Volume: 891072
vax780.ini-11> att vh 32961
Listening on port 32961
vax780.ini-21> att dmc0 33961
Line 0 Listening on port 33961
sim> b rq
Loading boot code from internal vmb.exe


   VAX/VMS Version V4.7 28-Oct-1987 13:00

Segmentation fault: 11
```
The version I'm trying to boot is VMS 4.7. A test image can be downloaded [here](https://drive.google.com/open?id=0B2q64Hq0IZ1WWm41NW40ZVROMG8).  You can use this INI file, where most of the (hopefully) irrelevant stuff has been removed:

```
set cpu conhalt 
set cpu idle=vms
attach todr todr_clock.dat

set rq enable
set rq0 ra81
att rq0 RA81.000

set vh enable 
set vh lines=16
att vh 32961

set ts enable

set hk disable
set tq disable
set tu disable

set dmc enable,lines=1
set dmc0 peer=127.0.0.1:33962
att dmc0 33961
```

#### Output of "sim> SHOW VERSION" 
```
sim> show version
VAX 11/780 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
        Simulator Compiled as C arch: x64 (Release Build) on Feb 19 2018 at 12:33:21
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin MacJordi.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
        git commit id: abfb828c
```

#### Build details

Built under OS/X using the standard makefile. I observed the same behaviour under ARM/Linux. Haven't tested under x86/Linux nor other operating environments.

#### Other info

I've not done a full bisect, but one month ago it worked (if my memory does not betray me). 

Using the same INI file VMS boots correctly if the DMC device is detached:

```
sim> det dmc0
sim> b rq
Loading boot code from internal vmb.exe


   VAX/VMS Version V4.7 28-Oct-1987 13:00


%%%%%%%%%%%  OPCOM  19-FEB-2018 12:59:27.13  %%%%%%%%%%%
Logfile has been initialized by operator _BTES61$OPA0:
Logfile is SYS$SYSROOT:[SYSMGR]OPERATOR.LOG;199
```

**Comment by b4** [comment]
Seeing the same; here's my backtrace from gdb:

VAX 11/780 simulator V4.0-0 Beta        git commit id: 335b4ef2
libpcap version 1.8.1
Eth: opened OS device vde:/tmp/vde
RQ0: 'vms073-ra92-boot.dsk' Contains ODS2 File system
RQ0: Volume Name: A9RT2        Format: DECFILE11B   Sectors In Volume: 2940951
sim> boot rq0
Loading boot code from internal vmb.exe

%SYSBOOT-I-SYSBOOT Mapping the SYSDUMP.DMP on the System Disk
%SYSBOOT-I-SYSBOOT SYSDUMP.DMP on System Disk successfully mapped
%SYSBOOT-I-SYSBOOT Mapping PAGEFILE.SYS on the System Disk
%SYSBOOT-I-SYSBOOT SAVEDUMP parameter not set to protect the PAGEFILE.SYS
   OpenVMS (TM) VAX Version V7.3     Major version id = 1 Minor version id = 0
%WBM-I-WBMINFO Write Bitmap has successfully completed initialization.
Program received signal SIGSEGV, Segmentation fault.
sim_cancel (uptr=0x0) at scp.c:10078
10078   if ((uptr->cancel) && uptr->cancel (uptr))
Current language:  auto; currently minimal
(gdb) bt full
#0  sim_cancel (uptr=0x0) at scp.c:10078
        cptr = (UNIT *) 0x0
        nptr = (UNIT *) 0xdf0b567d00000000
#1  0x00000000004c7e60 in tmxr_poll_conn (mp=0x794608) at sim_tmxr.c:997
        uptr = (UNIT *) 0x7fcd30
        newsock = 0
        lp = (TMLN *) 0x8022162b0
        op = (int32 *) 0xffffeaf8
        i = 0
        j = 0
        address = 0x7cc150 "!\002\b"
        msg = 0x7fffffffac90 "b!\002\b"
        poll_time = 3742062205
#2  0x000000000046bb3e in dmc_poll_svc (uptr=0x7fcd30) at PDP11/pdp11_dmc.c:2608
        dptr = (DEVICE *) 0x7957f0
        controller = (CTLR *) 0x7fffffffeaf8
        mp = (TMXR *) 0x794608
        dmc = 0
        active = 0
        attached = 8
#3  0x00000000004a9290 in sim_process_event () at scp.c:9904
        __was_poll = 0
        uptr = (UNIT *) 0x7fcd30
        reason = 85
#4  0x0000000000405dfb in sim_instr () at VAX/vax_cpu.c:639
        i = 3
        j = 2
        opc = 209
        cc = 4
        acc = 1
        abortval = -36
        ret = 0
        r = -2122297056
        rh = 0
        temp = 28017
        spec = 85
        disp = 82
        rn = 5
        index = -2122297056
        numspec = 2
        vfldrp1 = 0
        brdisp = 65402
        flg = 0
        mstat = 7
        va = 2172670240
        iad = 2175720780
        opnd = 0x7fffffffb530
#5  0x00000000004a587f in run_cmd (flag=5, cptr=0x513c42 "") at scp.c:7270
        addrs = (t_addr *) 0x436d49
---Type <return> to continue, or q <return> to quit---
        not_implemented_message = 0
        gbuf = 0x7fffffffb720 "CPU"
        tptr = 0x0
        i = 34
        j = 10
        sim_next = 0
        unitno = 0
        pcv = 538178664
        orig_pcv = 7850184
        r = 0
        dptr = (DEVICE *) 0x0
        uptr = (UNIT *) 0x7fce20
#6  0x0000000000435935 in vax780_boot (flag=5, ptr=0x7fffffffc0a5 "rq0") at VAX/vax780_sbi.c:634
        r = 0
#7  0x000000000048ae33 in process_stdin_commands (stat=0, argv=0x80221c000) at scp.c:2446
        cbuf = 0x7fffffffc0a0 "boot rq0"
        gbuf = 0x7fffffffbc20 "BOOT"
        cptr = 0x7fffffffc0a5 "rq0"
        stat_nomessage = 32767
        cmdp = (CTAB *) 0x777bc0
#8  0x0000000000489709 in main (argc=1, argv=0x80221c000) at scp.c:2384
        cbuf = 0x7fffffffd870 ""
        cptr = 0x80222b045 "/home/me"
        cptr2 = 0x0
        nbuf = 0x7fffffffd450 "\"/usr/home/me/vm/simh/BIN\"vax780.ini\""
        targv = (char **) 0x80221c000
        i = 1
        sw = -10896
        lookswitch = 1
        stat = 0

**Comment by jguillaumes** [comment]
The current source tree does not show the problem. I'm clossing the issue. Good work, as always!

**Comment by markpizz** [comment]
You've confirmed that the DMC actually works when connected to another system, right?

**Comment by jguillaumes** [comment]
Right. BITXOO uses the DMC to link to BITXT1. Both are in HECNET and working right now,

Jordi Guillaumes Pons


El 23 març 2018, a les 1:17, Mark Pizzolato <notifications@github.com> va escriure:
