### ISSUE TITLE
IMP interface

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#537]
I'm adding an IMP interface to SIMH.  For now, it's for @rcornwell's unmerged KA10.

It's structured as a generic API for connecting a simulator to an IMP as per the BBN 1822 Report, and another layer which emulates the functions of the BBN Network Control Program.

My primary interest is transferring IP packets to and from Ethernet.  It would also be possible to use old Arpanet protocols, or connect to a real or simulated IMP.

I will submit a pull request when the code is getting ready.

**Comment by markpizz** [comment]
When you implement this, please use the TMXR APIs to implement what I'm presuming is a TCP (or UDP) transport you'll be using to connect the end points of these devices.  The pdp11_dmc.c module would serve as an example of how this might be accomplished. TMXR provides either a byte oriented 'wire' between two endpoints or a framed packet oriented (either TCP or UDP) interface.  These are well integrated into the simh event scheduling and delivery model.

The goal is to avoid implementing device simulations which call sim_sock APIs (or other OS specific APIs directly).

**Comment by larsbrinkhoff** [comment]
Thanks, that's valuable feedback.  Much of the work is understanding how to interface with SIMH services.

However, I'm not looking to implement a transport in the first round.  My target operating system, ITS, does TCP/IP through the IMP, so that's what I want to implement first.

**Comment by markpizz** [comment]
The TMXR abstraction provides a way for 'bits' (as bytes or packets - your choice) to get between 2 simulators (as if it were wires - null modem - data circuit).  How you interface that 'bit' transport to the simulated system is your implementation project as well as what you're device may actually implement on top of the bit transport (wire) to simulate a protocol.

**Comment by larsbrinkhoff** [comment]
Oh, I see now!  Yes, that would be appropriate for the transport between the primary simulated machine and a secondary simulated machine for the IMP.  I have an emulated IMP built into the primary SIMH and there is no secondary SIMH.  Maybe TMXR provides for that use case too?  I'll look into it.

**Comment by markpizz** [comment]
> I have an emulated IMP built into the primary SIMH and there is no secondary SIMH. Maybe TMXR provides for that use case too? I'll look into it.

I'm not sure what you mean.  The secondary SIMH would be another instance of the same simulator or a completely different simulator which would be at the other end of a two different IMP connected systems.

TMXR provides the necessary behaviors to allow either (or both) simulator(s) to be up or down and provides the wire connection semantics to allow this.  When both ends of the wire are up it provides the working wire to transport bits between them.  It also provides optional bit error injection to exercise error/data recovery for protocols which may try to use the provided wire.

**Comment by larsbrinkhoff** [comment]
> I'm not sure what you mean. The secondary SIMH would be another instance of the same simulator or a completely different simulator

For my primary use case there is no secondary SIMH at all.  It's all handled inside a single SIMH.  I'm not running the original BBN software for the IMP.  I'll just be writing IP frames to Ethernet.  (Using ARP if necessary.)

**Comment by markpizz** [comment]
Hmm...

So what will you really be talking to?

Certainly no such thing as Ethernet existed when these IMP's were in use, right?  It sounds like you're trying to directly implement a translation of the IMP host/device protocol to directly into current IP?

**Comment by larsbrinkhoff** [comment]
I will be talking standard TCP/IP on Ethernet.

The 1822 Host/IMP protocol does support IP as well as the Arpanet protocol that is often called NCP.  I'm not sure when the IMPs were removed from the ITS machines, but it must have been well into the 80s.  So they did coexist with Ethernet as well as TCP/IP, and also the time period when NCP fell into disuse.

So the plan is to to take the 1822 messages, unwrap the IP packets inside and send out Ethernet frames instead.

**Comment by larsbrinkhoff** [comment]
I believe the ITS IMPs were removed May 1989.  All of Arpanet was shut down in 1990.  Arpanet switched to TCP/IP like the rest of the Internet in 1983.

**Comment by markpizz** [comment]
IMPs didn't actually put packets on an Ethernet, right?  You're combining host routing with Arpanet to TCP/IP translation in one device.  If so, that's a project and using TMXR is not part of the solution.  You'd then be using sim_ether to send and receive raw Ethernet packets.

**Comment by larsbrinkhoff** [comment]
No, the IMPs didn't use Ethernet.  They talked between each other through leased lines to form the Arpnanet network.

Yes, I'm looking to use sim_ether.  And I'll probably have to do ARP as well.

I have a secondary goal to maybe add the NCP protocol in the future, and/or allow connecting to a simulated IMP.  I'll keep TMXR in mind.

**Comment by larsbrinkhoff** [comment]
As part of this, I'm adding a Unibus ACC LH/DH IMP interface device to the PDP-10 simulator.  I suppose the PDP-11 and VAX simulators should be able to use it.  I see 2.11 and 4BSD have drivers for it.

**Comment by larsbrinkhoff** [comment]
@batbarron Did you ever find any documentation on the ACC LH/DH?

**Comment by larsbrinkhoff** [comment]
I think Pat pointed me to a pdf, but now I don't remember where it is!

**Comment by larsbrinkhoff** [comment]
@rcornwell has added an IMP to is KA10 simulator.  It's a simulation of the AI lab "KAIMP" hardware.  The host side uses the sim_ether component.

**Comment by larsbrinkhoff** [comment]
Got it.  Checking with the source and Kossow to see if they can go on Bitsavers.

**Comment by larsbrinkhoff** [comment]
This is now being adressed elsewhere, so I'm closing this issue.
