### ISSUE TITLE
DEQNA/DELQA emulation sets incorrect lengths for receive if multiple descriptors are used for a packet.

### ISSUE THREAD

**Issue by EJMarr** [simh/simh#563]
## Summary
The DEQNA/DELQA sets the data length into receive buffer descriptors as '(data transferred for this descriptor' - 60 ). This is the correct value (once software has added back the 60) if the data all relates to a single descriptor, but not if multiple descriptors are used for a packet. The data length value should (I think) simply be the number of bytes transferred into the receive FIFO.

## Detail

 I am just in the process of resurrecting a different release of an old system for which I have had
 other releases working well under simh. However, the communications in this release did not work. I have tracked it down to the values in the RBL (Received Byte Length) being effectively negative (though in 11 bits).

The packets in question are minimum length packets [60 bytes] split into an initial 16 byte buffer for header/protocol information, and with a second large buffer for the remaining maximum packet.

## Reference

The DEQNA User Manual states, concerning the two Receive Status words of the Receive Buffer Descriptor List:

Receive Status Word 1

Bit         Definition

10:08    RBL <10:08>. Received Byte Length bits 10 thru 08. See receive status word 2, bits 07:00. 
            These bits are all set during set-up mode packet processing.

Receive Status Word 2

This word must be initialized to have unequal high and low bytes. It is then valid when the bytes match.

Bit       Definition
15:08   RBL <07:00>. Receive Byte Length bits 07 through 00. Duplicated from lower byte.
07:00   RBL <07:00>. Receive Byte Length bits 07 through 00. These bits and receive status word
            1 bits 10:08 (above) form RBL <10:00>, the number of bytes transferred into the receive
            FIFO. Software adds 60 to this value, to account for the period during which address
            filtering occurs. The 4-byte CRC is not included in the count; CRC is not transferred to the
            FIFO.

## Code, and what it does

The code extract below is commented to show the resulting arithmetic.

The buffer length for the first buffer is obtained [16]

`    /* decode buffer length - two's complement (in words) */ `
`    w_length = ~xq->var->rbdl_buf[3] + 1;`
`    b_length = w_length * 2;`

The packet length is obtained, rbl is set to 60, 'used' starts off at zero.

`    item = &xq->var->ReadQ.item[xq->var->ReadQ.head];`
`    rbl = `(uint16)item->packet.len;
`    rbuf = item->packet.msg;`
`    if (item->packet.oversize)`
`       rbuf = item->packet.oversize;`

`    /* see if packet must be size-adjusted or is splitting */`
`    if (item->packet.used) {`
`      uint16 used = (uint16)item->packet.used;`
`      rbl -= used;`
`      rbuf = &rbuf[used];`

...

`    /* make sure entire packet fits in buffer - if not, will need to split into multiple buffers */`
`    if (rbl > b_length)`
`      rbl = b_length;`
`    item->packet.used += rbl;`

...

`    xq->var->rbdl_buf[4] = 0;`
`    switch (item->type) {`

...
`      case ETH_ITM_NORMAL: /* normal packet */`
`        rbl -= 60;    /* keeps max packet size in 11 bits */`
The above sets RBL to -44, 0xFFD4
`        xq->var->rbdl_buf[4] = (rbl & 0x0700); /* high bits of rbl */`
`        xq->var->rbdl_buf[4] |= 0x00f8;        /* set reserved bits to 1 */`
The above sets Receive Status Word 1 to 0x7F8
`        break;`
`    }`
`    if (item->packet.used < item->packet.len)`
`      xq->var->rbdl_buf[4] |= XQ_RST_LASTNOT;   /* not last segment */`
This sets RSW1 to 0x17F8
`    xq->var->rbdl_buf[5] = ((rbl & 0x00FF) << 8) | (rbl & 0x00FF);`
This sets RSW2 to 0xD4D4

The code loops for the second descriptor ending up with RSW1 =  0x17F8 and RSW2 = 0xF0F0.

Note that 60 has been subtracted twice.

## Review

So, what should the values be?

The DEQNA manual states

These bits [RBL<7:0>] (Received Byte Length) and receive status word 1 bits 10:08 (above) form RBL <10:00>, the number of bytes transferred into the receive FIFO.

Note that is does **not** say that it relates to the number of bytes transferred into the 
respective buffers.

The system driver in use has no code for handling negative values, so I believe that the
value is unsigned and positive, and that it is likely that for a minimum length packet,
both buffer descriptors should be given an entry of value zero. This is supported by the
fact that the driver adds 46. to the RBL value. (though I have not yet figured out why
it is not 44.) This gives the size of the packet contents, not the overall size. The 16
header bytes are kept separately.

##Debug output

[dbgextract.txt](https://github.com/simh/simh/files/2000292/dbgextract.txt)

## Solution

I changed pdp11_xq.c as follows

From
`      rbl -= 60;    /* keeps max packet size in 11 bits */`

To
`      rbl = item->packet.len - 60;   /* the number of bytes transferred into the receive FIFO */`
	
The system is still mildly flaky when I stress it, but before this change, it just threw away all 
incoming packets. The solution for the flakiness may just be configuration of enough buffers, so I'm
not too worried.

##Version
sim> sho version
PDP-11 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                32b data
                32b addresses
                Threaded Ethernet Packet transports:PCAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                Asynchronous Clock support
                FrontPanel API Version 4
        Host Platform:
                Compiler: Microsoft Visual C++ 15.00.30729.01
                Simulator Compiled as C arch: x86 (Release Build) on Feb 11 2017 at 10:52:53
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.5
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 1ms
                OS: Microsoft Windows [Version 10.0.16299.431]
                Architecture: x86 on AMD64, Processors: 2
                Processor Id: AMD64 Family 16 Model 4 Stepping 3, AuthenticAMD, Level: 16, Revision: 0403
        git commit id: bce72b2b
- #### how you built the simulator or that you're using prebuilt binaries
The above was a pre-built binary.

I have also cloned and used the current source code from GitHub (13th May 2018), built under Visual Studio 2015, to debug what was happening.

**Comment by EJMarr** [comment]
For my application, getting the correct length into the final descriptor, and not having a 'negative' length in the earlier ones would suffice, so your proposal would work for me.
It's not obvious to me what a 'correct' value would be anyway, except that in principle, it ought to match what a DEQNA does.

I'm not convinced that there is a race condition, though.

If one sets the two length bytes different (as instructed in the DEQNA manual), and if the DEQNA writes these last, once it has done the DMA for that descriptor, there is no confusion. The entire packet must have already been received in order that CRC checks etc can have been done, and the various error bits set. The completeness of a follow on descriptor is not implied by this descriptor being complete, even if it tells one the full packet length.

In my case, the short buffer is shorter than the shortest packet: it just contain dest, source and a smattering of protocol. The 'true' data is dumped into a buffer pool, and the relevant application is passed a reference. It's the second descriptor that is actually checked for completion. If that is OK, the first must be OK too, provided one has not pointed it at non-existent memory, for instance. The data length is the buffer length, of course.


Mobile +44 7712 680511

**Comment by EJMarr** [comment]
The solution provided in commit a3c... (above) works for me. If it works for Vax Cluster, the issue can be closed.

**Comment by markpizz** [comment]
FYI, git commit ids are a SHA-1 hash value which as a string is a 40 character hex string.  Since these are relatively random, they are usually referenced uniquely by the first 7 or 8 characters of the string.  Chopping the commit id to less than than 7 or 8 will result in a non-unique value.   The github issue system will automatically take a full (or uniquely truncated) hash string and display it here in the issue system as a link to the actual commit.  For example:

Full 40 Characters: 584147fb640322e1d7674d7694846cc0aa29d847
8 Characters: 584147fb
7 Characters: 584147f

When composing issue comments using the GitHub web UI, you can look at the underlying GitHub interpretation of these things by switching between the Preview and Write tabs.

**Comment by EJMarr** [comment]
I suggest we close this, if nobody has an issue with the fix.
