### ISSUE TITLE
PDP11: RL disk: I/O error and segfault.  SIMH 4-0-0., git commit cc31a504

### ISSUE THREAD

**Issue by dmoisan** [simh/simh#565]
I am running SIMH on an ARM board on Raspian Jessie, the emulated configuration is a PDP-11/60 with four RL drives running RSTS/E V7.  The config is something like:
```
set cpu 11/60
set cpu idle
...
attach rl0 dmsys.dsk
attach rl1 dmsysb.dsk
...
boot rl0
```
The output of `do rsts1160.ini`:
```
sim> do rsts1160.ini
Disabling XQ
rsts1160.ini-27> attach dz 22000
Listening on port 22000
RL I/O error: Invalid argument
                              RL I/O error: Invalid argument
Segmentation fault
outernet@martine:~/emu$
```
I have verified that the emulation config works in SIMH V3.9.  I included all optional packages except SDL (not applicable on my board).
```
show version
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 4.9.2
        Simulator Compiled as C arch: ARM (Release Build) on May 14 2018 at 23:03:49
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        No Large File support
        SDL Video support: No Video Support
        RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux martine 4.10.14-sunxi #21 SMP Sun May 7 22:37:19 UTC 2017 armv7l GNU/Linux
        git commit id: cc31a504
        git commit time: 2018-05-12T10:52:07-0700
sim>
```

[rsts1160.ini.txt](https://github.com/simh/simh/files/2005852/rsts1160.ini.txt)

**Comment by dmoisan** [comment]
OK.  Thanks.

**Comment by dmoisan** [comment]
I have confirmed your workaround.  RSTS/E is running on a Dreamcatcher Armbian board that was originally designed for the Outernet satellite project.  It's good to repurpose hardware. :) 
Regards, Dave M.

**Comment by dmoisan** [comment]
No problem.

**Comment by markpizz** [comment]
Hi there.  It has been quite a while.  

Do you still have this system setup?  If so, does it repeat the original failure with the latest code from the master branch at https://github.com/simh/simh.  It seems from the output you've provided that the failure happens either before the boot command is processed or before the OS gets very far into it's boot.  Given that more, information about precisely what it is doing would be useful.  To get this, will you please add these line to your configuration prior to the attach commands for the RL devices:
```
sim> set RL DEBUG
sim> set debug -f dmoisan.dbg
```
After the failure, please zip the resulting dmoisan.dbg file and either drop it here in this issue, or if it is too big, contact me at mark@infocomm.com so we can work out how I can see that output.

Thanks
