### ISSUE TITLE
PDP11 Idling appears to be broken from commit 1d22b48, but perhaps not in all configurations

### ISSUE THREAD

**Issue by EJMarr** [simh/simh#568]
PDP11 idling appears to be broken from commit 1d22b48, but perhaps not in all configurations.

In particular, it appears to loop if a DHV11 is connected to via Telnet.

- #### Context

I am running a test system with one RSX11M+ system communicating with a bespoke system, and was using the same PDP11.exe simh image for both.

In investigating Issue 563 (DEQNA /DELQA split packet descriptors), I downloaded the latest source (13th May 2018, 16:05 GMT) and built it using Visual Studio 2015 without a problem, and with only the automatic changes. Using it to debug the bespoke system version, I spotted that the RSX system was running at 50% CPU load on my two core PC (i.e. 100% of one core), rather than the low single digits it does when not much is happening. However, the bespoke system did not run at that load.

To avoid the question of the local build, I switched to the prebuilt binaries, and checked which commits give this symptom.

The first binary to do so was commit 1d22b48, and it also occurs with 40508cf. The intervening commit (626...) does not appear to include a PDP11 executable.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

This is from the RSX system 

sim> sho version
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Apr  7 2018 at 22:34:58
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.5
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 10.0.16299.431]
        Architecture: x86 on AMD64, Processors: 2
        Processor Id: AMD64 Family 16 Model 4 Stepping 3, AuthenticAMD, Level: 16, Revision: 0403
        git commit id: 1d22b488
        git commit time: 2018-04-07T22:30:59-07:00
sim>

- #### how you built the simulator or that you're using prebuilt binaries

Initially cloned to Visual Studio, but finally tested using pre-built binaries.

- #### the simulator configuration file (or commands) which were used when the problem occurred.

[RSXsystem.ini.txt](https://github.com/simh/simh/files/2014454/RSXsystem.ini.txt)

- #### the expected behavior and the actual behavior

No specific output - just high CPU load.

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

In obtaining the simh version information, I noticed that the CPU load was low, but that I had not connected a Refection terminal window to a DHV11 telnet port. On connection, the CPU load immediate rose to 50% and stayed there, not reducing when I disconnected. The same symptom is seen with PuTTy.

**Comment by markpizz** [comment]
Please try the latest code from the master branch and close this issue if the problem is no longer observed.

**Comment by EJMarr** [comment]
Thanks Mark. The fix works. Load profile attached.

![issue 568 corrected](https://user-images.githubusercontent.com/13817779/40281118-dc064ba8-5c4c-11e8-8e5a-2e824d0cd5d7.jpg)
