### ISSUE TITLE
VAX 'BOOT CPU' fails with existing nvram

### ISSUE THREAD

**Issue by mike632t** [simh/simh#584]
```
$ ./vax
MicroVAX 3900 simulator V4.0-0 Current        git commit id: 0fa5807e
sim> attach nvr nvram.bin
NVR: buffering file in memory
sim> boot cpu
Exception in interrupt or exception, PC: 200400B8 (CMPZV #0,#2,@#200B8058,#3) 
sim>
```
CPU boots without 'attach nvr nvram.bin'

Compiled with gcc version 4.9.2 (Debian 4.9.2-10+deb8u1) using 'make vax' with libpcap and libsdl.

```
$ make vax
lib paths are: /lib/ /lib/x86_64-linux-gnu/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/ /usr/lib/x86_64-linux-gnu/tls/
include paths are: /usr/lib/gcc/x86_64-linux-gnu/4.9/include /usr/local/include /usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed /usr/include/x86_64-linux-gnu /usr/include
using libm: /usr/lib/x86_64-linux-gnu/libm.so
using librt: /usr/lib/x86_64-linux-gnu/librt.so
using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib/x86_64-linux-gnu/libpcreposix.so /usr/lib/x86_64-linux-gnu/libpcre.so /usr/include/pcreposix.h /usr/include/pcre.h
using libdl: /usr/lib/x86_64-linux-gnu/libdl.so /usr/include/dlfcn.h
using mman: /usr/include/x86_64-linux-gnu/sys/mman.h
using libSDL2: /usr/include/SDL2/SDL.h
using libpcap: /usr/include/pcap.h
*** Info ***
*** Info *** vax Simulator are being built with
*** Info *** minimal libpcap networking support
*** Info ***
*** Info ***
*** Info *** Simulators on your Linux platform can also be built with
*** Info *** extended LAN Ethernet networking support by using VDE Ethernet.
*** Info ***
*** Info *** To build simulator(s) with extended networking support you
*** Info *** should install the vde2 package to provide this
*** Info *** functionality for your Linux system:
*** Info *** $ sudo apt-get install libvdeplug-dev
*** Info ***

*** vax Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 4.9.2.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).

*** git commit id is 0fa5807.
*** git commit time is 2018-05-28T11:58:42-07:00.

gcc -std=gnu99 -U__STRICT_ANSI__ -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=0fa5807e1dae435c129b9e94a09f89f6bff3775d -DSIM_GIT_COMMIT_TIME=2018-05-28T11:58:42-07:00 -DSIM_COMPILER="GCC Version: 4.9.2" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO -DHAVE_PCREPOSIX_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_GLOB -DHAVE_SHM_OPEN sim_BuildROMs.c -o BIN/BuildROMs
BIN/BuildROMs
rm -f BIN/BuildROMs
gcc -std=gnu99 -U__STRICT_ANSI__ -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=0fa5807e1dae435c129b9e94a09f89f6bff3775d -DSIM_GIT_COMMIT_TIME=2018-05-28T11:58:42-07:00 -DSIM_COMPILER="GCC Version: 4.9.2" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO -DHAVE_PCREPOSIX_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_GLOB -DHAVE_SHM_OPEN VAX/vax_cpu.c VAX/vax_cpu1.c VAX/vax_fpa.c VAX/vax_io.c VAX/vax_cis.c VAX/vax_octa.c VAX/vax_cmode.c VAX/vax_mmu.c VAX/vax_stddev.c VAX/vax_sysdev.c VAX/vax_sys.c VAX/vax_syscm.c VAX/vax_syslist.c VAX/vax_vc.c VAX/vax_lk.c VAX/vax_vs.c VAX/vax_2681.c PDP11/pdp11_rl.c PDP11/pdp11_rq.c PDP11/pdp11_ts.c PDP11/pdp11_dz.c PDP11/pdp11_lp.c PDP11/pdp11_tq.c PDP11/pdp11_xq.c PDP11/pdp11_vh.c PDP11/pdp11_cr.c PDP11/pdp11_td.c PDP11/pdp11_io_lib.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -DVM_VAX -DUSE_INT64 -DUSE_ADDR64 -DUSE_SIM_VIDEO -I VAX -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/.c slirp_glue/.c -DHAVE_LIBSDL -DUSE_SIM_VIDEO /usr/bin/sdl2-config --cflags /usr/bin/sdl2-config --libs -o BIN/microvax3900 -lm -lrt -lpthread -lpcreposix -lpcre -ldl
cp BIN/microvax3900 BIN/vax
$
```

**Comment by markpizz** [comment]
Please zip that nvram.bin and attach it to this issue.

Thanks.

**Comment by mike632t** [comment]
Attached

**Comment by mike632t** [comment]
See attached...
[nvram.bin.tar.gz](https://github.com/simh/simh/files/2060613/nvram.bin.tar.gz)

**Comment by markpizz** [comment]
I do not see a problem when using this file in various simulators on different hosts.  There should be nothing about the host which is a factor here.  Please confirm that the file you attached here actually fails for you.

**Comment by markpizz** [comment]
@mike632t, Please put your full name on your GitHub profile.

Please confirm that you can reproduce the problem you're reporting with the file that is attached here, and if not, please file a file that actually fails.

Thanks.

**Comment by mike632t** [comment]
That is the version of the file that left behind after the issue occurred, unfortunately  I don't have an older version of that file.    I did manage to reproduce the issue one more time last night but I've not had the same problem with the again since rebooting.  

As I've recompiled the simulator I don't know if the problem was with the binary or if it has gone away  because I've rebooted. 

Incidentally now that I have the SDL development libraries installed how do I recompile simh without SDL support?  Nothing in the makefile give me a clue (but I'm not very good at reading makefiles).

**Comment by markpizz** [comment]
What purpose would you have to build without SDL support?

You merely don't enable the video device and there should be no negative consequence.

If you REALLY want a simulator which can't enable the QVSS device, then uninstall the libSDL2 package and build the simulator again.

**Comment by markpizz** [comment]
Why would you want to build a simulator without the capability of enabling the video device?

The QVSS device is present in the simulator when it is built with video support, but it starts as disabled.  Nothing forces you to enable the device.

If you REALLY have a need to somehow remove this optional functionality, then uninstall the SDL development package and build the simulator again.

**Comment by mike632t** [comment]
Guessed that might be the only option - I've rebuilt the binaries without video support and (as you probably expected) it makes no difference.  What I DID notice however was the the file was bigger than it was yesterday (actually compiling without video support made only a small difference to the file size).

Since I've not seen the problem since recompiling I'm going to close this issue.

Again many thanks for your help (it is most appreciated)

**Comment by markpizz** [comment]
I can't fix a problem that I can't see.  

I suspect that the nvram.bin file you started with had its contents somehow mangled.

That mangling may have indeed happened with the original hardware.  The nvram is the working scratchpad for the system boot ROM and is used as a stack area when executing in the ROM.  Complete garbage contents might have caused the system to go off into the weeds like it did, and if that happened, the HALT that was encountered would have caused the ROM to re-initialize the nvram and the original hardware AND the simulator would have proceeded normally after that.  In your case, the simulator configuration was set to have it behave differently than the original hardware.  What I'm saying here is that the default simulator behavior on a HALT is to drop back to the sim> prompt rather than taking the console ROM halt path.  This default behavior is controlled by "SET CPU CONHALT" or "SET CPU SIMHALT".

**Comment by mike632t** [comment]
User error!!
