### ISSUE TITLE
MicroVAX 3900 unstable after ACPI suspend / resume

### ISSUE THREAD

**Issue by DNied** [simh/simh#596]
After suspending the host where SimH was running, and then resuming, the `vax` simulator is unstable, halts on an "Invalid argument" as per following screenshot:
```
+sim> cont

Invalid argument, PC: 800007CB (BEQL 800007C5)
+sim> cont

Simulation stopped, PC: 800007CB (BEQL 800007C5)
+sim> cont

Simulation stopped, PC: 800007CB (BEQL 800007C5)
+sim> save vaxar1.state
+sim> bye
Goodbye
NVR: writing buffer to file
Eth: closed nat:tcp=8022:10.0.2.4:22
Cancel failed for XQ-TMRSVC
Aborted
```
After each `cont`, SimH seems to freeze, only interrupted by `^E`. However, no CPU "hogging" on the host during these pauses.

Attempts at restoring the saved state in a newly launched SimH instance result in a similarly unstable emulator: 
```
+sim> rest vaxar1.state
NVR: writing buffer to file
Eth: closed nat:tcp=8022:10.0.2.4:22
Eth: closed tap0
Error Attaching NVR to uvax3900-nvram.bin - the restore state is 72 seconds older than the attach file
restore with the -F switch to override this sanity check
Command not completed
+sim> rest -F vaxar1.state
NVR: buffering file in memory
Listening on port 8023
NAT args: tcp=8022:10.0.2.4:22
NAT network setup:
        gateway       =10.0.2.2/24(255.255.255.0)
        DNS           =10.0.2.3
        dhcp_start    =10.0.2.15
        redir TCP     =8022:10.0.2.4:22
  Protocol[State]    FD  Source Address  Port   Dest. Address  Port RecvQ SendQ
  TCP[HOST_FORWARD]   8               *  8022        10.0.2.4    22     0     0
Eth: opened OS device nat:tcp=8022:10.0.2.4:22
Eth: opened OS device tap0
+sim> cont

Simulation stopped, PC: 800007CB (BEQL 800007C5)
+sim>
```
This same, repeatable issue was found on:
* V4.0-0 Current, git commit id: 8c0439fe
* V4.0-0 Current, git commit id: undeterm

`show version` output from the more recent _undeterm_ version, checked out few days ago and built locally from source:
```
MicroVAX 3900 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 7.3.0
        Simulator Compiled as C arch: x64 (Release Build) on Jul 13 2018 at 21:46:06
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux localhost 4.16.14_1 #1 SMP PREEMPT Tue Jun 12 21:53:22 UTC 2018 x86_64 GNU/Linux
        git commit id: undeterm
        git commit time: undetermined-commit-time
```
Output from `make vax` also available on request.

Configuration file follows:
```
set cpu 64M
set cr disable
set lpt disable
set rl disable
set rq1 disable
set rq2 disable
set rq3 disable
set tq1 disable
set tq2 disable
set tq3 disable
set ts disable
set dz enable
attach dz 8023
set dz lines=4
set dz 8b
set xq enable
set xq type=delqa
attach xq0 nat:tcp=8022:10.0.2.4:22

set xqb enable
set xqb type=delqa-t
att xqb tap:tap0

set rq0 ra90
set rq0 noauto
attach rq0 vaxar.dsk
attach nvr uvax3900-nvram.bin
set tti 7b
set tto 7b
set cpu idle=OpenBSDold
```

**Comment by markpizz** [comment]
Several questions:
1) What, exactly is your host OS?
2) How are you getting the latest code from Github.com/simh/simh?  Downloaded Zip file?  git clone?
3) Please provide the 'make vax' output when you get the source again cleanly using the same method as described in the answer to 2.
4) Do you get the same behavior (and error) with the latest code from the Github.com/simh/simh  master branch?
5) If, before your ACPI suspend, you:
```
^E
sim> save vax-current.state
sim> quit
now suspend
```
and
    6) after your wakeup from suspend, you:
```
$ cd directory-containing vax-current.state
$ invoke the vax binary (presuming this directory DOES NOT contain a vax.ini file)
sim> restore vax-current.state
sim> continue
```
do things behave somewhat reasonably?

**Comment by markpizz** [comment]
Please answer the questions asked.  

Commits today should both provide a more useful error report if/when you might have gotten an "Invalid Argument" during simulator execution AND the simh commit id should not ever show up as undetermined.

**Comment by DNied** [comment]
1. Host OS is Void Linux x86_64 (a rolling distro) with GNU libc 2.26;
2. the 2nd version (the _undeterm_ one) I got via `svn checkout`, the other was probably from a ZIP archive (both from GitHub);
3. checked out the latest code, again with svn. The git commit id is again _undeterm_, but I've made a note and it's really bd347e6. Attaching the output from `make vax`;
4. yes, still getting the same behaviour on the latest code -- about 50% of the time, from today's tests;
5 & 6. that does it, but it's actually overkill. Halting emulation with `^E` before suspending and continuing it after resuming is enough to work around the problem.
[DN-make_vax.log](https://github.com/simh/simh/files/2203172/DN-make_vax.log)

**Comment by markpizz** [comment]
2) Hmmm... One could argue that svn checkout should interpret the .gitattributes information.  I have no other way to support svn checkout.  You know you could merely use 'git clone https://github.com/simh/simh' and subsequently 'git pull' to pickup the latest changes...
3) bd347e6 was yesterday.  Please pickup today's code.  
4) Today's commit will provide some very valuable information to track down the "Invalid Argument" case you are seeing.  Please try it and send that output.
5 & 6)  That in fact would indeed be equivalent to what I proposed given a simple host system ACPI sleep and a subsequent resumption of activities.  The suggested approach should cleanly also allow you to reboot the host system and then resume the simulated session later on.

**Comment by DNied** [comment]
OK, it seems I can't get 15fd71b9 to halt on "Invalid argument". It mostly survives suspend/resume cycles, but just once it became unresponsive, returning to normal after 2 or 3 minutes.

I can also make it unresponsive by sending it a SIGSTOP, followed a couple of minutes later by `fg` from the shell. In that case it will take several minutes for it to respond to a `^E` and let the user regain control.

**Comment by markpizz** [comment]
These strange things you're doing to the running simulator are breaking significant assumptions that are fundamentally part of how it manages time.  There is logic which keeps track of executed instructions vs wall clock time and calibrates the clock ticks that are generated internal to the simulator.  Messing with things by any form of suspension (SIGSTOP or sleeping/suspending the system) does this.  The ^E before suspension and continuing after resuming allows the assumptions to be consistent since while sitting a the sim> prompt it knows that instructions aren't executing and the explicit continue re-initializes the timing parameters.

There were other changes yesterday that addressed some of the potential ways it could have exited with "Invalid Argument" and after that the improved recovery from the broken assumptions is better.  If your original complaint seems to addressed, please close this issue.

Thanks

**Comment by DNied** [comment]
OK, my main concern was not getting a corrupt filesystem for the impossibility of proper unmounting after the error. Although I do think SimH should ideally catch up readily after suspension, the instability and collateral damages are no longer there.

Thank you for the fix, closing this issue.
