### ISSUE TITLE
Problem compiling old commit

### ISSUE THREAD

**Issue by jguillaumes** [simh/simh#597]
I'm trying to compile an old commit to bisect a problem and I've found I can't. 

```
make pdp11 vax780 vax8600
lib paths are: /lib/ /lib/arm-linux-gnueabihf/ /opt/vc/lib/ /usr/lib/ /usr/lib/arm-linux-gnueabihf/ /usr/lib/arm-linux-gnueabihf/libfakeroot/ /usr/lib/arm-linux-gnueabihf/neon/vfp/
include paths are: /usr/include
using libm: /usr/lib/arm-linux-gnueabihf/libm.so
using librt: /usr/lib/arm-linux-gnueabihf/librt.so
using libpthread: /usr/lib/arm-linux-gnueabihf/libpthread.so /usr/include/pthread.h
using regex: /usr/include/regex.h
using libdl: /usr/lib/arm-linux-gnueabihf/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib/arm-linux-gnueabihf/libpng.so /usr/include/png.h
*** Info ***
*** Info *** The simulators you are building could provide more
*** Info *** functionality if video support were available on your system.
*** Info *** Install the development components of libSDL or libSDL2
*** Info *** packaged for your operating system distribution for
*** Info *** your Linux system:
*** Info ***        $ sudo apt-get install libsdl2-dev
*** Info ***    or
*** Info ***        $ sudo apt-get install libsdl-dev
*** Info ***
using libpcap: /usr/include/pcap.h
using libvdeplug: /usr/lib/libvdeplug.so /usr/include/libvdeplug.h
***
*** pdp11 vax780 vax8600 Simulators being built with:
*** - compiler optimizations and no debugging support. GCC Version: 6.3.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP NAT(SLiRP)
***
*** git commit id is SIM_GIT_COMMIT_ID 61d42845423052c370e1db1e0eae7906082a5f2a SIM_GIT_COMMIT_TIME 2018-01-27T13:19:11+0100.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=SIM_GIT_COMMIT_ID 61d42845423052c370e1db1e0eae7906082a5f2a SIM_GIT_COMMIT_TIME 2018-01-27T13:19:11+0100  -DSIM_COMPILER="GCC Version: 6.3.0" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_REGEX_H -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_GLOB  sim_BuildROMs.c -o BIN/BuildROMs
gcc: error: 61d42845423052c370e1db1e0eae7906082a5f2a: El fitxer o directori no existeix
gcc: error: SIM_GIT_COMMIT_TIME: El fitxer o directori no existeix
gcc: error: 2018-01-27T13:19:11+0100: El fitxer o directori no existeix
makefile:1693: recipe for target 'BIN/BuildROMs' failed
make: *** [BIN/BuildROMs] Error 1
```

Tried to do it under MacOS and linux, with the same result. I'm pretty clueless about what's happening here...

**Comment by markpizz** [comment]
The commit you are focusing on (61d42845423052c370e1db1e0eae7906082a5f2a) is not in the master branch of the repo.  It seems to exist in your fix-tmxr-rsx11 branch in your personal github simh repo.
```
Author:			Jordi Guillaumes Pons <jguillaumes@gmail.com>#mailto:jguillaumes@gmail.com
Date:			6 months ago (1/27/2018 4:19:11 AM)
Commit hash:	61d42845423052c370e1db1e0eae7906082a5f2a
Children:		393e6eee38#gitext://gotocommit/393e6eee38b917b2406a4e2aa3ad879095153296
Parent(s):		a6d41ca615#gitext://gotocommit/a6d41ca6157aa866348ac4947010aa9970993e58 2924b338df#gitext://gotocommit/2924b338df57f00a1f56ef628405cd47000d6686
```
I can't really tell what is happening to you, but there have been changes in the makefile which really weren't there 6 months ago, but there is some evidence of in the make output you're showing.  Specifically, the GIT_COMMIT_TIME.  Try removing the .git-commit-id file and run your make again...

**Comment by jguillaumes** [comment]
Uh-oh. I guess it's time to nuke my local copy and start with a fresh clone of the main repo.

**Comment by jguillaumes** [comment]
I was happily bisecting using old versions and I closed the issue and then...

```
gcc -std=c99 -U__STRICT_ANSI__  -O2 -finline-functions -DSIM_GIT_COMMIT_ID=SIM_GIT_COMMIT_ID 045d7dba3656b7de1527ad784a5940eed068b0e9 SIM_GIT_COMMIT_TIME 2018-02-02T05:51:22-08:00  -DSIM_COMPILER="Apple LLVM version 9.1.0" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=dylib -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_GLOB -DHAVE_SHM_OPEN  sim_BuildROMs.c -o BIN/BuildROMs
clang: error: no such file or directory: '045d7dba3656b7de1527ad784a5940eed068b0e9'
clang: error: no such file or directory: 'SIM_GIT_COMMIT_TIME'
clang: error: no such file or directory: '2018-02-02T05:51:22-08:00'
make: *** [BIN/BuildROMs] Error 1
```
It's pretty curious, since this commit is from February:

```
commit 045d7dba3656b7de1527ad784a5940eed068b0e9 (HEAD)
Author: Mark Pizzolato <mark@infocomm.com>
Date:   Fri Feb 2 05:51:22 2018 -0800

    SCP: ON CONTROL_C cleanup and SHOW ON support
```

And I started bisecting with a "good" version from December 31:

```
commit 2389f41f5e6404fc0cbdd8077aeed5ff3c69e4bf
Author: Richard Cornwell <rcornwell@github.com>
Date:   Sun Dec 31 19:21:29 2017 -0500

    I7000: Updated copyright notice on i7000_com.c.

```

This compiled without trouble... 

I don't understand how a checkout doesn't restore a _consistent_ version. Maybe something in the .git subdirectory that DOES NOT get versioned?

**Comment by markpizz** [comment]
A checkout doesn't restore a consistent version since the .git-commit-id is not part of the repo, but is generated.  The format of that file changed along the way (to add the SIM_GIT_COMMIT_TIME) , and the older makefile code that parses it doesn't expect the new format.  During bisect activity that straddles these changes, I suspect that if you remove the .git-commit-id file BEFORE you attempt to make it EACH time during your sequence of bisect activities, things will work out for you.

**Comment by jguillaumes** [comment]
Well, actually it is a little bit more complicated.
I've got to manually edit the .git-commit-id file and leave in it just the, well, the commit id.

The generated content of the file is:

```
$ cat .git-commit-id 
SIM_GIT_COMMIT_ID 045d7dba3656b7de1527ad784a5940eed068b0e9
SIM_GIT_COMMIT_TIME 2018-02-02T05:51:22-08:00
```
I edited it and left this:

```
$ cat .git-commit-id 
045d7dba3656b7de1527ad784a5940eed068b0e9
```
Then the compiling proceeded.

**Comment by markpizz** [comment]
If that works, fine.  

The mechanism which used to generate the .git-commit-id was scripts in .git/hooks/post-commit, .git/hooks/post-merge, and .git/hooks/post-checkout.  If these scripts are present in that location, each checkout runs the post-checkout script that populates the .git-commit-id file contents.  Each make invocation with the older makefile installs the scripts (in the .git/hooks directory) and then invokes it to generate the .git-commit-id file's contents.

**Comment by jguillaumes** [comment]
Yeah, it works doing the manual edit, so I'm closing the issue.
I'd suggest to document this somehow, just in case someone wants to build an older version of the beta, either for bisecting or for other reasons...
