### ISSUE TITLE
DISPLAY: Keyboard input to VT11 and Type 340 windows

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#605]
- #### Context
The VT11 and Type 340 display GUI windows provided by code the `display` directory could be more useful if they accept keyboard input.  For example, I tested a GT40 application but I had to switch to the SIMH console to enter keyboard input.  This works OK, but I think it would be easier to use if both input and output were to the same GUI window.

In the case of the 340 display, keyboard events can be used to simulate Spacewar consoles, so it would have to be a user selectable option.  The 340 didn't have a standard keyboard, but at MIT they attached a Stanford keyboard to the PDP-10 I/O bus and placed it near the display.

**Comment by markpizz** [comment]
Before looking into this, you'll need to use the sim_video APIs (interfacing via SDL).  The x11 code is only there since Phil Budne wanted all of the display stuff to sit in the same place.  Any simulator code that uses display.c which will get merged only if it uses sim_ws.c and NOT x11.c.

**Comment by markpizz** [comment]
Doing what I suggest should not involve any code changes, merely selecting different pieces at compile time: some simh code and linking with libsdl2.

**Comment by markpizz** [comment]
This works just fine already:

1) Build the PDP1 simulator (with libsdl2 installed on your local system).
2) follow the instructions in README (and README.MIT) in PDP1/spacewar1 directory

The existing code in display.c handles key events (in the graphics window) specifically for spacewar.  That could be generalized if you had realistic scenarios (and existing software) that could use it.

**Comment by larsbrinkhoff** [comment]
I have now patched SIMH so it can simulate a GT40 with the VT11 ROM and connect to a PDP-10.  See #614.

It's awkward to type in the window with the SIMH console, and see output in the separate VT window.

**Comment by larsbrinkhoff** [comment]
I took a look at suppying console input from the VT window.  I replaced the body of `display_keydown` with this:

```
  SEND *s = sim_cons_get_send ();
  uint8 ch = k;
  sim_send_input (s, &ch, 1, 0, 0);
```

This almost works, but unfortunately key modifiers do not.  E.g. pressing Control gets me an "R"!

Maybe this is an artifact of code in x11.c, and switching to sim_ws.c will be an improvement.

**Comment by markpizz** [comment]
Using send is an interesting approach.  I'm a little worried about the potential for the input data to accumulate if nothing is actively reading console.  Maybe that isn't a problem at all.

Meanwhile, the original needs of keyboard processing in display.c was absolutely only for spacewar.  This doesn't require a full range of characters.  Keyboard processing there may need to be reworked to interpret key modifiers and keys and translate them to ascii as needed.

Why aren't you using the simh makefile for this simulator?  That will use libsdl2 as long as you have the sdl development package installed in your environment.

**Comment by markpizz** [comment]
I've thought about the send idea and realized that this may work as a direct hack, but that approach violates Phils original goal that display.c be a library used by other things (in simh), but not one which uses simh APIs.

I have an approach which meets Phil's goal.  It still has the same translation issues you noticed.  I'm rewriting the key mapping to properly generate a more natural range of ASCII that most keyboards can generate.

**Comment by larsbrinkhoff** [comment]
Thank you.  Looking forward to see what you come up with.

**Comment by markpizz** [comment]
I didn't think that what I did was specific to the GT40.  I changed the keyboard processing in display.c to be integrated with the PDP11 console polling.  

Another simulator that uses display.c for graphics that wants keyboard input via the graphics window would already have some thing in its console port logic that looks like:
```
if ((c = sim_poll_kbd ()) < SCPE_KFLAG)                 /* no char or error? */
    return c;
```
which should get changed to:
```
#if defined(USE_DISPLAY)
if (display_last_char) {
    c = display_last_char | SCPE_KFLAG;
    display_last_char = 0;
    }
else {
    c = sim_poll_kbd ();
    if (c < SCPE_KFLAG)                     /* no char or error? */
        return c;
    }
#else
if ((c = sim_poll_kbd ()) < SCPE_KFLAG) /* no char or error? */
    return c;
#endif
```
and include display.h earlier with:
```
#include "display/display.h"
 ```

**Comment by larsbrinkhoff** [comment]
In that case, my change will be to @rcornwell's KA10 simulator, and this can really be closed.
