### ISSUE TITLE
hp2100 hangs when trying to generate a new Access system using the 22687-11002_Rev-1812 tape

### ISSUE THREAD

**Issue by wpappas** [simh/simh#619]
- #### Context

The hp2100 simulator hangs after the "2754?" prompt when trying to boot from the master tape.  Answering Y or N doesn't seem to matter.  
- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
HP 2100 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 5.4.0 20160609
        Simulator Compiled as C arch: x64 (Release Build) on Sep 18 2018 at 20:36:04
Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.38 2015-11-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux wap06 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
        git commit id: d35b8725
        git commit time: 2018-09-18T14:24:14-070
- #### how you built the simulator or that you're using prebuilt binaries

The simulator was built using current (as of 9/18) unmodified sources from GitHub on a Ubuntu 16.04 system.  The same behavior was also seen on a Raspbian Stretch build, so I don't think this is host specific. 
- #### the simulator configuration file (or commands) which were used when the problem occurred.

set cpu 2100
set cpu 32K
set cpu FP
;
;Disables for unused devices.
set ptr disabled
set ptp disabled
set lps disabled
set lpt disabled
set baci disabled
set mpx disabled
set dpc disabled
set drc disabled
set dqc disabled
set mtc disabled
set mux disabled
set muxc disabled
set pif disabled
set da disabled
;
;Set up for interconnect
set ipl enabled
set ipl sc=10
attach -S ipl 4020
;
;Set up for tty
set tty sc=12
;
;Set up for tbg
set tbg sc=13
;
;Set up for 7920 drive DS
set ds sc=14
set ds0 7920
set ds1 7920
set ds2 7920
set ds3 7920
set ds4 7920
set ds5 7920
attach ds0 7920-0.dsk
attach ds1 7920-1.dsk
attach ds2 7920-2.dsk
attach ds3 7920-3.dsk
attach ds4 7920-4.dsk
attach ds5 7920-5.dsk
;
;And last is the tape drive.
set msd sc=16
set msc 13181A
attach -R msc0 tapes/22687-11002_Rev-1812.tap
boot msc
go 2000

This configuration (and associated IOP config) has been used to bring up a system booted directly from disk (DS) just fine.  Happy to provide any other information needed.

**Comment by wpappas** [comment]
I've just verified that the same configuration using the 3.9 version of SimH works as expected, so it seems to be related to some of the recent changes.

**Comment by wpappas** [comment]
Hi Mark,
I just complied the 486427c code using the link you provided above and verified that the problem still exists.  I don't boot the simulation from tape very often so it's possible the problem was introduced a while ago and went unnoticed.  Happy to provide anything else -- just let me know.

--Bill

**Comment by markpizz** [comment]
Bill,

I'm passing along Dave Bryan's response:
```
I suspect he's missing this:

  ; Start the MCP.
  ;
  ; The MCP requires the lower select code of the magnetic tape drive
  ; interface to be present in bits 11-6 of the S register when it starts.
  ; The 1000 bootstrap does this automatically, but we must do it manually
  ; when loading from a 2100.  (Actually, we do it unilaterally, as it has
  ; no adverse effect when performed on a 1000 CPU.)

  deposit S 001600

...which is what is done in the automatic system generation script file 
"tsb-spgen.sim" that's included in the software kit containing the
22687-11002_Rev-1812 tape that he's using.

Please ask him to insert the "deposit S 001600" line between the last 
two script lines that he shows in his bug report, i.e.:

  boot msc
  [ insert the "deposit" line here ]
  go 2000

...and see if that fixes his problem.


> This has been verified to be a problem with the commit that is your 
> release 28 version and isn't due to some generic change I introduced 
> since that time.

From the release notes that accompany Release 28:

 - The BOOT command now installs the correct binary loader for the CPU
   model. For example, BOOT PTR installs and runs the Basic Binary Loader
   (BBL) if the CPU is configured as a 2114/15/16 or 2100, or the 12992K
   Paper Tape Loader ROM if the CPU is configured as a 1000 M/E/F-Series.
   Prior releases installed the HP 1000 loader ROM regardless of the CPU
   model. 

It "worked" in earlier releases because the "boot msc" command he uses 
installed the 1000 boot loader regardless of the "set cpu 2100" shown at 
the top of his script.  Release 28 now installs the correct mag tape boot 
loader for the 2100, and that loader doesn't automatically set the S 
register as the 1000 loader does.  So it has to be set manually, as it 
would if it were done on actual hardware.

His script would also work as is if these lines:

  set cpu 2100
  set cpu 32K
  set cpu FP

...are changed to:

  set cpu 1000
  set cpu 32K

...because then the 1000 boot loader would be used.  But adding 
the "deposit S" is the correct action when generating on a 2100 CPU.

(The "set cpu fp" is not needed and will be rejected because floating 
point firmware is standard on the 1000 and cannot be changed.)

If he still has problems after the above, please ask him to contact me 
directly and send both the full SP (System Processor) configuration 
script that he shows in the report and the 
"associated IOP [I/O Processor] config" script that he mentions but 
does not show.

                                      -- Dave
```

**Comment by markpizz** [comment]
Dave then followed up with:
```
On Wednesday, September 19, 2018 at 12:30, I wrote:

> It "worked" in earlier releases because the "boot msc" command he uses 
> installed the 1000 boot loader regardless of the "set cpu 2100" shown 
> at the top of his script.  Release 28 now installs the correct mag 
> tape boot loader for the 2100, and that loader doesn't automatically 
> set the S register as the 1000 loader does.  So it has to be set 
> manually, as it would if it were done on actual hardware.

A little more background:

Strictly speaking, what the correspondent is doing is not supported 
by HP.  
He's booting the Master Configurator Program (MCP) using the 2100 
mag tape loader, but the supported boot method, as documented in 
the "HP 2000 Access Operator's Manual," is to use a supplied paper 
tape loaded via the paper tape reader and the 2100 paper tape loader.  
The paper tape program is a mag tape bootstrap loader that is run to 
begin execution of the MCP from tape.

The paper tape program ends with this little bit of code after the MCP 
has been read in from mag tape:

  *
  *  START MASTER CONFIGURATOR PROGRAM
  * 
  BST20 LDA MAGSC     PUT SELECT CODE 
        LSL 6           INTO BITS 11-6
        OTA SWR           OF SWITCH REGISTER
        JMP MCPSA,I   JUMP TO M.C.P.

...which is what was missing from the correspondent's command 
script (the "deposit S 001600" sets the _S_witch register bits 11-6 to 
the mag tape select code, which is 16 octal in his case).

Booting directly from mag tape works IF the switch register is set 
correctly.  The 1000 boot loader automatically sets the S register 
properly, and indeed the 1000 boot instructions in the Operator's 
Manual explicitly say, "Do not alter the S-register" before running 
the just-loaded MCP.

None of the 2100 loaders set S, so it has to be set manually if the 
just-loaded program expects a value to be there.

So the bottom line for Release 28 is that (a) the supported HP boot 
method for the 2100 of using the standalone paper tape loader to 
load the MCP tape works, (b) the supported HP boot method for the 
1000 of using the mag tape boot loader directly works, and (c) the 
unsupported boot method of using the 2100 mag tape loader directly 
works IF the S register is set as the MCP expects.

As far as I know the 2000 Access MCP is the only program that requires 
this.  I'll see about updating my "Running HP 2000 Time-Shared BASIC 
on SIMH" paper to document this requirement explicitly.

Thanks again for the bug report.

                                      -- Dave
```

**Comment by wpappas** [comment]
Adding the deposit line got it running correctly.  I feel like an idiot as I thought I RTFM, but obviously didn't as closely as I should have.  Sorry for wasting your time.

As a side note, I really appreciate all the work Dave has put into the hp2100 and hp3000 simulators.  They are awesome tools that allow us to run some very neat classic systems that are often overlooked these days since they weren't as widely known as the DEC stuff.

On a final note I am all for authenticity, but having the boot the Access MCP tape using the cross-loader from the IOP is a bit of a pain and like the fact that I can cheat using the boot command in the simulator. 

--Bill

**Comment by wpappas** [comment]
One final note to Dave -- my setup is undoubtedly very non-authentic as I load the IOP code from paper tape to avoid having to cross load it off the mag tape from the SP.  The paper tape was generated by attaching the punch to the interconnect select code during initial IOP configuration on the SP.  This, along with the ability to boot the mag tape on the SP using the "boot" command allows me to start each process separately and avoid some of the Access start-up synchronization issues.

--Bill

**Comment by markpizz** [comment]
Thanks for the feedback.

Meanwhile, if you're satisfied with the state of your problem report, please close this issue.
