### ISSUE TITLE
redefine of DZ__LINES 

### ISSUE THREAD

**Issue by eg90804** [simh/simh#620]
Just a minor issue.
The define 'DZ_LINES' is defined in PDP11/pdp11_defs.h as '8', but gets redefined in PDP11/pdp11_dz.c
as '(UNIBUS ? 8 : 4)'

**Comment by markpizz** [comment]
I'm sorry, but I don't see what you're talking about.

The only place I see DZ_LINES defined (or referenced) in the master branch is in PDP11/pdp11_dz.c.

PDP11/pdp11_defs.h defines DZ_MUXES, and the related bits for proper interrupt dispatching.

**Comment by eg90804** [comment]
You're correct, I was looking at an older file, forgot to do a new pull.
