### ISSUE TITLE
PDP-11+RSTS/E V7.0-07 -- slow terminals

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#621]
A curiosity I first noticed earlier this year that I've decided might be worth
reporting:  I noticed that with recent-ish PDP11 builds of SimH, a
PDP-11/94+RSTS/E V7.0-07 installation now has very slow terminals.
Any telnet-connected terminal on a DZ serial controller (but **not** the console)
outputs characters very slowly, like a slow Teletype.
Curiously, this **only** affects RSTS 7 -- the same pdp11.exe configured as
PDP-11/93+RSTS/E V9.6-11, as PDP-11/70+RSX-11M V4.4, and as PDP-11/94+RSX-11M+ V4.6
behaves normally.

This same behavior occurs under Windows XP (32-bit), Windows 7 (64-bit), and
Windows 10 (64-bit) (I haven't tried under Linux, BSD, or MacOS), using either
32-bit or 64-bit MinGW builds of SimH.

I've narrowed this down to a specific Git commit: d0bd4fb on 11 May 2017 (the
second commit on that date); see
https://github.com/simh/simh/commits/master?before=0fe4bf3281a4d1f9fd10bba07cf0f7e40da92fc3+630

This is listed as a change to sim_tmxr.c:  "TMXR: Enforce output rate limiting when
output is produced by instructions"; see
https://github.com/simh/simh/commit/d0bd4fbdffb61d6b8bf3847e2b8e65f166bf2e9c

Any pdp11.exe built with an earlier commit (up to and including 1e8af71, the first
commit on 11 May 2017) behaves normally in the PDP-11/94+RSTS/E V7.0-07 installation;
anything built with a later commit, up to and including the present, has
the slow terminals in that configuration.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
![show_version](https://user-images.githubusercontent.com/17226010/45927597-988d3c00-bf03-11e8-9b5a-615186f73283.JPG)

- #### how you built the simulator or that you're using prebuilt binaries

![build_output](https://user-images.githubusercontent.com/17226010/45927607-d1c5ac00-bf03-11e8-9e74-b579b34295ca.JPG)

- #### the simulator configuration file (or commands) which were used when the problem occurred.

set xq disabled
set cpu 11/94, 2M
set cpu idle

set ptr disabled
set ptp disabled
set cr disabled

set hk disabled
set rk disabled
set rp enabled
set rq disabled
set rx disabled
set tq disabled

;DB system disks (RP06)

set rp0 rp06
attach rp0 disk_images/rp06_db0_rsts_v7_7.dsk

set rp1 rp06
attach rp1 disk_images/rp06_db1_USER1.dsk

set rp2 rp06
attach rp2 disk_images/rp06_db2_USER2.dsk

set rp3 rp06
attach rp3 disk_images/rp06_db3_USER3.dsk

;DL disk cartridges (RL02)

;set rl0 rl01
;attach rl0 disk_images/sysgng.dsk
;set rl0 lock

set rl0 rl02
attach rl0 disk_images/rl02_dl0_SMALL0.dsk

;set rl1 rl01
;attach rl1 disk_images/sysl1g.dsk
;set rl1 lock

set rl1 rl02
attach rl1 disk_images/rl02_dl1_SMALL1.dsk

;set rl2 rl01
;attach rl2 disk_images/patchg.dsk
;set rl2 lock

set rl2 rl02
attach rl2 disk_images/rl02_dl2_SMALL2.dsk

attach lpt printer.txt

set tm disabled
set ts enabled

;attach ptr input.tap
;attach ptp output.tap

set dz lines=16
;set dz log=1=tt1.log
;attach -am dz 2070
attach dz 2070

set xu mac=08-00-2B-AC-BC-CC
set xu enabled
att xu eth0

;boot rl0
boot rp0

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Hi Jim,

Thanks for isolating this to the commit which caused the changed behavior.

Now: Using the latest code from the master branch, reproduce the problem and when it is happening, use ^E to get to the "sim>" prompt and send along the output of a SHOW MUX command.

Next: I'm going to need a way to reproduce the problem.  Please come up with a minimal configuration file and a boot disk that demonstrates it and either zip them up and attach them to this issue, or make them available somewhere I can pick up the zip file (Google Drive, or other means).  Also provide whatever instructions I'll need to provide as input to the running system that demonstrates the problem.

Thanks.

- Mark

**Comment by Jim-F** [comment]
> . . .send along the output of a SHOW MUX command. . .

It turns out that both before the issue showed up (commit id 1e8af71, first commit on May 11, 2017,
and earlier) and afterwards (commit id d0bd4fb, second commit on May 11, 2017, and later)
the SHOW MUX command gives the same results -- all lines set to Speed=110 bps.  This is
true even though the earlier versions of SimH run both console and terminals much faster than that.

However, on closer examination of the situation it appears that my RSTS-E v7.0-07 installation,
while it had a SY0:[1,2]TTY.CMD file (run by SY0:[1,2]START.CTL) that was setting the
terminal types of KB0:-KB8: to VT50, there was no speed being set, and according to
"RSTS-E V7.0 System Manager's Guide AA-2762C-TC (May 1979)" in that case the default
terminal speeds are all **supposed** to be that of an ASR-33 teletype (110 baud).

So setting the speeds in SY0:[1,2]TTY.CMD eliminated the problem (since it appears that the
correct line speed was actually being ignored by earlier versions of SimH before the problem
appeared):

. . .
FORCE KB0: RUN $TTYSET
FORCE KB0: KB0:
FORCE KB0: VT50
FORCE KB0: SPEED 9600
FORCE KB0: KB1:
. . .
etc.

So I'll close this issue.

**Comment by markpizz** [comment]
I'm glad you reached that conclusion.  That was exactly why I asked for the SHOW MUX output.

FYI: You can set speeds that look like the previous behavior by specifying a speed factor in the configuration file:
```
sim> SET DZ SPEED=*1
sim> SET DZ SPEED=*2
sim> SET DZ SPEED=*3
...
sim> SET DZ SPEED=*31
sim> SET DZ SPEED=*32
```
