### ISSUE TITLE
HP2100 loses time under RTE-6/VM when CPU IDLE is set

### ISSUE THREAD

**Issue by wpappas** [simh/simh#622]
Not sure if this is really a bug or just expected behavior, but the hp2100 simulator loses about one minute per hour when CPU IDLE is set vs. losing less than one second per hour when idling is disabled.

- #### Context
Running two copies of an identically configured simulation, but setting one to use CPU idling, demonstrates the problem.  The host was a four core system and the test was ran overnight so the host system was basically quiet.  I recognize that the simulators are not meant to be a perfect replication of real hardware so this may not be considered a bug, but was surprised at how accurate the clock was without idling vs. with.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 5.4.0 20160609
        Simulator Compiled as C arch: x64 (Release Build) on Sep 23 2018 at 20:56:15
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.38 2015-11-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux wap06 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
        git commit id: 0fe4bf32
        git commit time: 2018-09-19T22:36:48-0700
- #### how you built the simulator or that you're using prebuilt binaries

Standard build (i.e. 'make hp2100') using unmodified current (as of 9/23/2018) github sources via 'git pull' on a Ubuntu 16.04 x86-64 system,
- #### the simulator configuration file (or commands) which were used when the problem occurred.

[RTE-6VM.sim.zip](https://github.com/simh/simh/files/2412626/RTE-6VM.sim.zip)
The above config was used with one instance and the other used the same except CPU was set to NOIDLE.
- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Bill,

I'm commenting here again since some GitHub glitch blocked my earlier attempt to create the prior comment.

Will you please contact me directly at mark@infocomm.com.

Thanks.

- Mark

**Comment by markpizz** [comment]
Bill,

You seem to be a capable git user.  If so, will you perform some tests:

1) Starting from commit 486427c9fe, please confirm whether you see similar time related behaviors or now.  
2) If step 1 does not exhibit the time problems you are seeing, please do a git bisect starting from that commit as 'good' with the latest as 'bad' and determine which commit introduced the different behavior.

Let me know.

Thanks.

- Mark

**Comment by wpappas** [comment]
Mark,
I've compiled the code from commit 486427c and run it for several hours and the clock appears to be staying accurate.  I'll see if I can fool around with 'git bisect' to narrow down when things seem to have broken and report back.

--Bill

**Comment by wpappas** [comment]
Hi Mark,
It looks like the first bad commit was 6b77987 where you made some changes to TIMER.  I haven't had a chance to look at the changes in detail, and am still somewhat surprised that Brian wasn't seeing the same behavior under windows.

--Bill

**Comment by markpizz** [comment]
Hi Bill,

I believe that the changes made in that commit were correct.  However, they entangled an earlier change (from almost 2 years ago) that was in effective then, but I'm now thinking is causing this behavior.

Using the latest code in the master branch, please try to comment out the line in sim_timer.c which contains "act_cyc += (sim_idle_cyc_ms * sim_idle_rate_ms) / 2;"

Let's see how that affects what you're seeing.

Thanks.
-Mark

**Comment by wpappas** [comment]
Hi Mark,
Commenting out that line seems to have fixed it as I have been running for almost two hours with no loss of time.  For avoidance of any doubt, the commit id I am now running is 4dd08bfe and I commented out the line:
>act_cyc += (sim_idle_cyc_ms * sim_idle_rate_ms) / 2;     /* account for half an interval's worth of cycles */

in sim_timer.c before compiling.

--Bill

**Comment by wpappas** [comment]
Sorry -- I accidentally closed this with my prior comment.

**Comment by wpappas** [comment]
I am closing this at this point since it looks like the changes above have been incorporated into the code and a recent pull and build verifies that the clock while idling is no longer exhibiting the behavior documented when this was originally opened.

**Comment by markpizz** [comment]
Hi Bill,

Please test this with the latest code from the master branch to confirm that recent timer related changes have not reintroduced this or another problem.

Thanks.

**Comment by wpappas** [comment]
Hi Mark,
I’m running a test on it now and will report back once it has been up for several hours.

--Bill

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by wpappas** [comment]
> 
> 
> Hi Bill,
> 
> Please test this with the latest code from the master branch to confirm that recent timer related changes have not reintroduced this or another problem.
> 
> Thanks.

It's been running for 6 hours and the clock is spot on.  Haven't done any extensive testing beyond boot up the system and running a few programs, but all seems fine.

**Comment by markpizz** [comment]
Are you sure that you are testing with IDLE enabled?  I ask since folks running other simulators are having issues with idle enabled...

**Comment by wpappas** [comment]
> 
> 
> Are you sure that you are testing with IDLE enabled? I ask since folks running other simulators are having issues with idle enabled...

IDLE is definitely enabled.  Running on a Raspbian Pi 3B, if that makes any difference. Git commit id: 45d8c908

**Comment by wpappas** [comment]
Over 12 hours and the clock under RTE-6/VM is still dead bang on.

**Comment by markpizz** [comment]
Hi Bill,

I think the clock behaviors are stable for all simulators now.  Please test the cases you care about.

Thanks.

- Mark

**Comment by wpappas** [comment]
Hi Mark,
I've been testing with git commit id 8c4f8b0b and the hp2100 simulator running RTE 6/VM (idled) and HP Access (throttled) are both keeping excellent time.  I'm also running VMS (idled) using the Microvax 3900 simulator at the same commit level and it is also keeping excellent time.  All three are running on a Pi 3B under Raspbian Stretch.

--Bill

**Comment by markpizz** [comment]
Hi Bill,

Please run the same test on the latest code.  Various real changes have happened in the timer code since 8c4f8b0, so I want to be sure that no regressions have been inserted.

Thanks.

Mark

**Comment by wpappas** [comment]
Hi Mark,
I've did a pull on 6/19 (git commit id b3fa1f9f) and it also seems to be keeping very accurate time under HP2100 RTE-6/VM and  VAX/VMS.  Both have CPU idling set and are running on a Raspberry Pi 3B under Raspbian Stretch. I believe that pull has the final set of timer changes you recently implemented.

It is kind of fun to have an early '90s era data center running on a 3"x4"x2" piece of hardware. 

--Bill
