### ISSUE TITLE
Divide-by-zero exception, all simulators on Windows XP

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#624]
Beginning with commit 0d9f195 (the second commit on Aug 7, 2018), all simulators
(built with MinGW32 and running under 32-bit Windows XP) terminate soon after
startup with the message "XXX.exe has encountered a problem and needs to close.
We are sorry for the inconvenience."

Following up with gdb reveals a divide-by-zero error in sim_timer.c
(line 1069).

That line contains an expression consisting of all integer variables, a ratio
of two of which gets rounded to zero and winds up in the denominator of another division.
Casting the numerator of the inner ratio to (double) prevents the
integer-rounding-to-zero (and hence the divide by zero exception)
from happening.

---------------------------------
1069c1069
<     sim_os_tick_hz = 1000/(sim_os_clock_resoluton_ms * (sim_idle_rate_ms/sim_os_clock_resoluton_ms));

---
>     sim_os_tick_hz = 1000/(sim_os_clock_resoluton_ms * ((double)sim_idle_rate_ms/sim_os_clock_resoluton_ms));
---------------------------------

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem
![sigfpe_gdb](https://user-images.githubusercontent.com/17226010/46183631-bd850480-c29f-11e8-860c-38b8f5b8ddc3.JPG)

**Comment by markpizz** [comment]
This should be fixed now.

**Comment by Jim-F** [comment]
Fixed as of commit 0e544b71 (Sep 28, 2018).
