### ISSUE TITLE
^E exits SimH altogether, rather than just exiting to SCP 'sim>' command prompt

### ISSUE THREAD

**Issue by Jim-F** [simh/simh#625]
As of commit d35b872 of Sep 18, 2018 ("SCP: Add optional status value to EXIT command",
involving changes to scp.c and sim_defs.h) typing '^E" while a simulation is in progress
exits SimH altogether, rather than just halting the simulation and returning to the SCP
'sim>' command prompt.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
![version](https://user-images.githubusercontent.com/17226010/46220380-e77a0d80-c317-11e8-8af1-f644fc29d71a.JPG)

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

![exit](https://user-images.githubusercontent.com/17226010/46220405-fb257400-c317-11e8-879b-39f0c00dd7f5.JPG)

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Jim,

Please give the latest code a try and close this issue if things are working correctly now.

Thanks.

- Mark

**Comment by Jim-F** [comment]
Fixed as of commit 0e544b71 (Sep 28, 2018).
