### ISSUE TITLE
IBM 1620: Remove redundant paragraph from doc

### ISSUE THREAD

**Issue by DaveWise2** [simh/simh#627]
i1620_doc.doc contains a redundant and mis-numbered paragraph 2.1 on the 1624 paper tape reader.  Attached find a corrected file that removes the extra.
[i1620_doc.doc.zip](https://github.com/simh/simh/files/2438679/i1620_doc.doc.zip)

**Comment by markpizz** [comment]
Fixed.

Thanks.
