### ISSUE TITLE
Exapanding the supported number of Kdp interfaces in Pdp10:KS10 and Tops10 

### ISSUE THREAD

**Issue by R-Voorhorst** [simh/simh#635]
At the moment the maximum number of Kdp/Dup interfaces is limited to 2 interfaces which is rather limited. The Kmc11 was capable of driving many more Dup interfaces but the limit of 2 for the KS10 may have to do with physical limits (and imposed commercial managerial limits) of (for) the KS10 and limitations on memory space for Tops10 with Decnet on the KS10.

In the virtual realm there are less limits for expansion of the number of Kdp interfaces.
In Simh on the Pdp11 there are 8 Kdp/Dup lines enabled; in the Pdp10:KS10 there are only 4 Kdp/Dup's.

There are two cases for expansion:
1.  Expansion to 4 Kdp/Dup lines
2.  Expansion to 8 Kdp/Dup lines.

The difference between 1 and 2 is that the Simh Pdp10:KS10 should be modified to support 8 instead of the standard 4 Dup lines per Kdp. This can be done quite easily as Pdp10_defs,h modifies the standard Pdp11 definition in Pdp11_defs.h:
#define DUP_LINES       8                               /* max # of DUP11's */
from 8 to 4, so modifying it to 8 can be done by editing the specific entry in Pdp10_defs.h and then rebuild the Pdp10 simh image.

That been done, Tops10 has to be modified to accept the extra interfaces which is quite simple but requires the rebuild of the Tops10 monitor image. The steps to this are the following:

1.  Edit the file NETPRM.MAC and change the entry:
      MXNDUP==^D2 to MXNDUP==^D4 or ^D8 whichever is wished for; it can be fixed to 8 anyhow.
2.  Assemble the NETPRM.MAC and then the D8KINT.MAC file as the driver is reliant on NETPRM.MAC.
3.  Recreate the TOPS10.REL database (.R PIP 100k (Ret) TOPS10@ (Ret) ).
4.  Edit the SYSCNF.MAC for the monitor and just like for the DMR add the necessary variables:
      M.KDUP==:4 or 10 (octal!) and then
      M.#KDP==: 1 (ANF) or 2 (Decnet) and #=0(1)3..7, so M.0KDP:==2 ... M.3KDP:==1 or M.7KDP:==2
     Remember that for >1 Decnet lines, Decnet router must be specified and not endnode! 
5.  Reassemble the F,S, and SYSCNF.MAC+<Common, Comdev, Commod> with the new 
       NETPRM.UNV available.
6.  Link the monitor with the new TOP10.REL
7.  Do not forget to specify the extra Kdp/Dup lines in the Simh Pdp10:KS10 config ini file.

With the monitor started up, the number of decnet lines can be seen with:
R OPR
NCP SHO KNO LINE STAT

OPR>NCP SHO KNO LINE STAT
OPR>
20:40:31        NCP

Request # 2; Show Known Lines Status Completed

Line     State
KDP-0-0  On     
KDP-0-1  Off    
KDP-0-2  Off    
KDP-0-3  Off    
KDP-0-4  Off    

This works; a side effect may be that the Monitor low segment free space diminishes leading to a limit of usable disks (do not set the in core SAT blocks to high; 10 blocks suffice usually) and concurrent logged in users (jobslots!).
Remember that  the KS10 is low on free memory and limiting not used sysjobs (MX) can save valuable needed core.

Best regards,

R. Voorhorst

**Comment by markpizz** [comment]
The KDP/DUP was also limited by two independent Unibus characteristics:

1) electrical "bus loads" and/or power
2) bus bandwidth.  The KDP generated NPR bus requests to access and control the DUP devices.

**Comment by R-Voorhorst** [comment]
Yes, As Tim mentioned earlier: “a rather unpleasant device” with the s(t)en(t)(ch) of understatement attached to it, so I presume.
Kmc did a lot of things on the Unibus unless when it had private paths to the interface itself.

At least some people may have fun with 8 network lines now that you provided fertilizer to the Kdp/Dup speed: 90kBd no less! :)
The Dmr has no advantage anymore (als 90kBd) as they all seem to reside in MUXR with this apparent speed limitation of 9 kB/sec which for the Dmr is a pitifull amount as it was capable 0f > 2MBd

**Comment by R-Voorhorst** [comment]
Nothing further to add

R.V.
