### ISSUE TITLE
Would be nice a HOWTO

### ISSUE THREAD

**Issue by Zibri** [simh/simh#645]
It would be nice to have a step by step HOWTO for tasks like:

setup and run a VAX/VMS  using a tape image of the OS (VMS 5.5?!)

**Comment by Zibri** [comment]
Nevermind. I solved the problem and my old VMS 5.5-2 is up and running.

**Comment by vaxvms** [comment]
https://www.wherry.com/gadgets/retrocomputing/vax-simh.html
