### ISSUE TITLE
DHV11 in PDP11 - Output very slow following in-memory restart

### ISSUE THREAD

**Issue by EJMarr** [simh/simh#646]
- #### Context
The system in use has the capability to update its boot file with the current memory contents (a SAVE) , and it will then continue after the SAVE using the existing memory content, starting at the same entry point as it does for a boot. There are two modes of starting, COLD and HOT. In a COLD start the system tables, data and queues etc are set up from initialisation data. On a HOT start, the already set up tables are used.

The example system has connections to terminal emulators via telnet, and these work fine except following a SAVE, having a HOT restart from the memory content. The saved memory content, when booted into a fresh simh (also a HOT start), works fine.

The terminal emulator sessions remain connected during the save and restart.

Following the SAVE, each output transfer takes circa 250ms, although the debug output suggests the next transmission should commence after sub-millisecond to single digit millisecond periods.

I note

1. on first application output transmission after a boot in a fresh simh, the telnet setup completes for all lines. Following a SAVE and the restart from memory, there is no telnet admin activity. Is some necessary action for transmission completion associated with the telnet setup code?
1. `vh_xmt-svc` contains the line
`     sim_activate_after (uptr, 250000); /* requeue ourselves */`

Some of the information in issue #609 relates to this problem, but this is a much cleaner statement of the issue, while the titular issue of #609 has been resolved. It should be closed.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
sim> sho version
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 19.00.24215.01
        Simulator Compiled as C arch: x86 (Debug Build) on Dec 21 2018 at 17:09:47
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.8
        PCRE RegEx (Version 8.36 2014-09-26) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 10.0.17134.471]
        Architecture: x86 on AMD64, Processors: 2
        Processor Id: AMD64 Family 16 Model 4 Stepping 3, AuthenticAMD, Level: 16, Revision: 0403
        git commit id: 2d35feb9
        git commit time: 2018-08-28T17:51:31-07:00
- #### how you built the simulator or that you're using prebuilt binaries
Using Visual Studio Community 2015, and the standard build files. No issues observed.

- #### the simulator configuration file (or commands) which were used when the problem occurred.

[Target2.ini.txt](https://github.com/simh/simh/files/2710475/Target2.ini.txt)

- #### the expected behavior and the actual behavior

An annotated debug file, containing two simh runs; the first being a COLD start of a new system (no problem with output), followed by a SAVE restarting with a HOT start (problem occurs), and the second a boot of the SAVEd image, executing a HOT start (no problem).

[VH annoted.zip](https://github.com/simh/simh/files/2710482/VH.annoted.zip)

**Comment by EJMarr** [comment]
I have identified how it happens.

The RESET instruction results in clearing the UNIT_TM_POLL bit (value 2) from unit->dynflags for VH-XMIT, but the Telnet line remains ATTACHED (as it is supposed to).
                             
RESET instruction calls `reset_all()`
which calls `vh_reset()`
which calls `tmxr_set_line_output_unit()`

`tmxr_set_line_output_unit()` includes
```
if (mp->ldsc[line].o_uptr)
    mp->ldsc[line].o_uptr->dynflags &= ~UNIT_TM_POLL;
```

I have 

1. Put a breakpoint in, watched the value of dynflags change from 2 to 0, then manually set it back to 2 - the system has correct timing afterwards; and
1. Commented out the above statement, and this works without manual intervention.

I see that the previous routine `tmxr_set_line_unit()` has similar code, but I have not been doing input. I would presume that there could be a similar issue here.

The problem seems to stem from simh structures being modified by a card reset when they should not be. Do these routines not need to be called at some earlier stage, with a `vh_init()` routine, and not from `vh_reset()`? There seem to be a number of things in `vh_reset()` that might also be segregated, if they are modifiable by configuration, but would remain over a RESET instruction.

**Comment by markpizz** [comment]
Hmmm... Great digging.  That is a problem.  

The explicit effort to clear that flag exists to address the potential of a reconfiguration that might reassign units to different roles (maybe when the number of active lines is changed).

So rather than merely removing the apparently offending lines of code, the right answer for both _tmxr_set_line_output_unit()_ and _tmxr_set_line_unit()_ is to leave the original clearing activity for the unit being replaced and explicitly set the UNIT_TM_POLL flag after the new unit has been specified.
I've committed a change that does this.

**Comment by markpizz** [comment]
The latest avoids the crash and avoids clearing UNIT_TM_POLL on reset.

**Comment by EJMarr** [comment]
I thought the first version seemed short of an if :-).

Your latest version works on my simple one line DH text test case. I'll run it on a two line graphics version.

**Comment by EJMarr** [comment]
Yes, that seems good.

Thanks.
