### ISSUE TITLE
Maybe this was volountary, maybe not.

### ISSUE THREAD

**Issue by Zibri** [simh/simh#647]
I have noticed that if you don't put set cpu model=Vaxserver you have to manually issue the BOOT command at the >>> prompt
I wonder why this behaviour.

**Comment by markpizz** [comment]
Please show your whole configuration file.

**Comment by markpizz** [comment]
Please provide the configuration file you were using when you saw this happening, or close this issue.

Thanks.

**Comment by markpizz** [comment]
No response.  Closing issue.
