### ISSUE TITLE
SUGGESTION/FEATURE REQUEST

### ISSUE THREAD

**Issue by Zibri** [simh/simh#649]
Since many OS of 198X years lack tcp/ip or unzip or even kermit,it would be great if SIMH implemented a way to share a local directory and make that seen by the guest OS (in my case VMS 5.5-2) as a disk or cdrom.

Could anyone implement this?
It's two days I am fighting with mksimtape and I seem I can't import UNZIP.EXE in that way.

Also I tried tar2mt but how can I then extract the tape in VMS?
Please help.

**Comment by markpizz** [comment]
For versions of VMS that know how to handle ISO9660 structured CDROMs and ISO images, see #696 for example of what you might do.
