### ISSUE TITLE
Generic input interface?

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#650]
I have a need to feed inputs - that are not keyboards or mice - to applications:

- Spacewar consoles.  (PDP-10)
- Logo box with at least 32 buttons.  (PDP-11)
- A/D converter.  (PDP-10)

Modern USB joysticks could provide inputs for some of these.  It has also been suggested that a MIDI mixing table could be used.

Before I rush off and do something on by own, I'd like to raise the issue here.  Does anyone else have similar needs?

**Comment by larsbrinkhoff** [comment]
I previously mentioned this to @markpizz:
> > I see sim_video mentions some SDL_JOY and SDL_CONTROLLER events, to I suppose I should build on that.
> 
> You can go there, but I'd be somewhat cautious about depending on them unless you can find JOY and CONTROLLER hardware that is supported with interfaces on multiple host systems. Maybe this concern is nothing to worry about, I have never looked at any such devices. Since they probably are USB connected, maybe this is not a concern at all.

**Comment by larsbrinkhoff** [comment]
As far as I can see, SDL can handle this transparently for all supported platforms.

**Comment by larsbrinkhoff** [comment]
One complication I see is mapping from host hardware input to simulated input.  This could depend on many things:

- Host device.
- Simulated machine.
- Application.

**Comment by EJMarr** [comment]
This is something I have been idly thinking of, without any solid plans. My interest was in getting access to Raspberry PI IO. 

I would completely agree with your last comment.

My experience in this area is with industrial control systems IO attached to PDP11, and the interfaces were many and varied, including

1. Simple IO page registers for digital and analogue inputs and outputs
1. Dual port RAM in the IO page
1. Dual port RAM in memory space
1. Simple serial connected scanned devices
1. Remote intelligent devices with serial connections, connected through the KXT11-C intelligent communication boards, using the Modbus protocol amongst others.
1. Multiplexed analogue inputs using channel selection in a driver
1. Devices generating interrupts for digital input change of state or for analogue conversion completion.

If one has any existing software to run, I don't see any way but to implement an interface for the specific IO device in simh. On the other hand, if you can be flexible in your application, I could see the interface being a simple set of registers providing the I/O as (say) 16 bit fields of digital inputs or outputs, or individual analogue inputs and outputs. For high performance, you could add a vector for digital inputs changing and one for analogue inputs changing (perhaps by a factor, or an absolute amount).

**Comment by larsbrinkhoff** [comment]
Thanks @EJMarr, that's a good point.  GPIO should be included in this.

**Comment by larsbrinkhoff** [comment]
I will be working on a pull request in the future.
