### ISSUE TITLE
PDP-10 disassembly (command line: pdp10 -m)

### ISSUE THREAD

**Issue by rmaldersoniii** [simh/simh#657]
The documentation for the PDP-10 (KS-10) **simulation** states that typeout from an EXAMINE command will be shown as  symbolic machine instructions if the simulator is invoked with the **-m** switch on the command line.

An octal dump of a PDP-10 program, read from lights on a running console and typed into a file, needs to be translated to symbolic instructions. The file was massaged into a **"do"** script containing **deposit** commands and read into both version 3.9 (prebuilt Windows binary) and version 4.0 (Linux build from Github repository).

Subsequent **examine** commands only type the in-memory value out as a 12 digit octal number, matching the input.

Will this functionality be added to the PDP-10 simulator, or will the documentation be revised?

**Comment by markpizz** [comment]
You are reading the information incorrectly.

The -m switch will display instructions when the EXAMINE command is invoked with the -M switch.
```
sim> EXAMINE -M <addr>
```

**Comment by larsbrinkhoff** [comment]
I have a PDP-10 disassembler running on Unix.  I could add support for octal input quite easily.
