### ISSUE TITLE
PDP11 simulator in headless (batch) mode

### ISSUE THREAD

**Issue by shattered** [simh/simh#665]
- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

I'm looking for a way to run automated tests with SIMH, specifically to compare output of RT-11 DIR command to output of RT-11 filesystem parser I've written, across a few dozen of disk images.

Looks like a command file with ATTACH, BOOT, SEND "DIR\r", BYE commands should work, but DIR command never reaches the simulated OS.   Is this expected to work?

**Comment by markpizz** [comment]
What you want to do should be completely possible using the existing simh commands.

You will need more than the commands you list.

If you want specific help you'll have to provide the precise details of what you've tried and what happened when you did.

**Comment by shattered** [comment]
It is, indeed, possible.  The trick is to SEND before BOOT:
```
set cpu 11/23 256k cis
set console wru=035
attach rl0 root-rt11v53.rl02
send -t after=5000000,delay=10000000,"DIR /VOL/FUL/BLO/COL:1 DL0:\r\035"
bo rl0
bye
```
Plus this patch, so that WRU char is also accepted from sent string:
```
diff --git a/scp.c b/scp.c
index 0f66f7b9..5396d181 100644
--- a/scp.c
+++ b/scp.c
@@ -12157,6 +12157,8 @@ if (snd && (snd->extoff < snd->insoff)) {               /* pending input charact
         char dstr[8] = "";
 
         *stat = snd->buffer[snd->extoff++] | SCPE_KFLAG;/* get one */
+        if ((*stat & 0177) == sim_int_char)
+            *stat = SCPE_STOP;
         snd->next_time = sim_gtime() + snd->delay;
         if (sim_isgraph(*stat & 0xFF) || ((*stat & 0xFF) == ' '))
             sprintf (dstr, " '%c'", *stat & 0xFF);
diff --git a/sim_console.c b/sim_console.c
index 2b7322af..73d8c6cc 100644
--- a/sim_console.c
+++ b/sim_console.c
@@ -2821,7 +2821,11 @@ t_stat sim_poll_kbd (void)
 t_stat c;
 
 if (sim_send_poll_data (&sim_con_send, &c))                 /* injected input characters available? */
-    return c;
+    if (c == SCPE_STOP) {                                   /* ^E */
+        stop_cpu = TRUE;                                    /* Force a stop (which is picked up by sim_process_event */
+        return SCPE_OK;
+        }
+	else return c;
 if (!sim_rem_master_mode) {
     if ((sim_con_ldsc.rxbps) &&                             /* rate limiting && */
         (sim_gtime () < sim_con_ldsc.rxnexttime))           /* too soon? */
```

**Comment by markpizz** [comment]
You are trying to send the WRU within the SEND string so that you can stop execution after the output you've generated is produced, right?

I'm not sure what the OS prompt looks like on the disk you're booting, but lets say it is "$ ".
Your script could look something like:
```
set cpu 11/23 256k cis
attach rl0 root-rt11v53.rl02
set env prompt="$ "
expect %prompt% send "DIR /VOL/FUL/BLO/COL:1 DL0:\r"; expect %prompt%;go
boot rl0
bye
```
This will match "$ " anywhere in the output.  If  you want it to match at the beginning of a line you could use:
```
set env prompt="\r\n$ "
```
Some operating systems might emit nul characters in and/or around newline sequences.  If that's the case for the one you're using you might have to add \000 in appropriate places in the prompt string.  In order to determine what your OS is emitting, you can start with the above mentioned script, and if the expect doesn't match, type the WRU character and look at the output of SHOW EXPECT to see what is actually being emitted.

**Comment by shattered** [comment]
Nice, I will give that a try.   BTW, while I was looking around scp code, found a possible problem (not flagged by Coverity) in sim_send_input()
```
if (snd->insoff+size > snd->bufsize) {
    snd->bufsize = snd->insoff+size;
    snd->buffer = (uint8 *)realloc(snd->buffer, snd->bufsize);
    }
memcpy(snd->buffer+snd->insoff, data, size);
```
realloc could return NULL here.

**Comment by markpizz** [comment]
While, in theory that is true, there are also many other places where buffers are allocated and similarly not checked.  A failure in these cases would only happen if there was a significant memory leak and Coverity is pretty good at detecting and reporting those.  In general, normal simulator instruction execution occurs without allocating and freeing memory.  As you observed, executing some SCP commands does involve dynamic memory but careful review of that code can manage this memory sanely.

**Comment by rcornwell** [comment]
Mark memory allocations should always be checked. SimH is now being run on Pi's and other tiny systems. It is possible the memory request could not be handled. SimH should fail in a graceful way, rather then getting a segment fault.

**Comment by markpizz** [comment]
There already are checks of memory allocation failures for reasonable code paths that allocate big chunks of memory that indeed might fail on smaller systems. 

Without restructuring large sections of the code to pass back errors, the only valid action to take on many small allocation failures is to abort().  This isn't functionally different from a segfault, so the advantage of checking these cases is hardly worth it.

**Comment by shattered** [comment]
Makes sense.   I've also hit a segfault in HELP command a few times, that probably shouldn't happen - will try to reproduce that.

**Comment by markpizz** [comment]
Any HELP segfault should be readily reproducible and certainly should not cause a failure. 

Please send along any input that caused a segfault.

Thanks.

**Comment by markpizz** [comment]
We've been waiting for some HELP input that causes a SEGFAULT.  If/when you find some, please create another issue.

Thanks.
