### ISSUE TITLE
PDP-11 slow ls command listing files while running Unix from Simh Sample Software Packs

### ISSUE THREAD

**Issue by alexaendergfx** [simh/simh#670]
Hello, please excuse my ignorance with the PDP-11 as I am new to this beast!  When booting all 3 versions of Unix (5,6,7) from the SimH Sample Software Pack according to the instructions in the associated PDF, it seems as if the ls command is way slower than it should be when listing files.  It seems quite a bit slower than what I see in Youtube videos of actual PDP-11's listing files in Unix.  It list files line by line like I am on a 300 baud modem rather than a scroll of file names.  Is this due to an inherent delay to emulate hardware or am I missing a terminal setting?  Here are the instructions I used for Unix 7 for example.  Thanks much in advance!!  Brett

sim> set cpu u18
 sim> set rl0 RL02
 sim> att rl0 unix_v7_rl.dsk
 sim> boot rl0 
 @boot
 New Boot, known devices are hp ht rk rl rp tm vt
 : rl(0,0)rl2unix

.......................................................................................................................................
I am using the prebuilt win32 binary

......................................................................................................................................

PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Mar  6 2019 at 18:17:42
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.8
        PCRE RegEx (Version 8.36 2014-09-26) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 10.0.17134.590]
        Architecture: x86 on AMD64, Processors: 8
        Processor Id: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel, Level: 6, Revision: 5e03
        git commit id: d7e116f8
        git commit time: 2019-03-06T10:54:25-08:00

---------------------------------------------------------------------------------------------

**Comment by markpizz** [comment]
I can't say why the single user mode you initially start in appears so slow, but if you enter ^D and then login as root with password root things seem normally fast to me.

I don't think there is any problem with the simulator.

**Comment by alexaendergfx** [comment]
You are 100% correct of course...as soon as I ^D and log in as root/root...it screams along as it should.  Very odd!   

Please let me take a second to say THANK YOU for what you are doing here with SimH.  I would have to assume you understand how incredibly important your work and effort is for so many different reasons.  What you do really truly is a big deal to us.  One last question...any chance we might see PDP-12 sneak into SimH at some point?  Doesn't hurt to ask right?  haha Seriously thank you so much!    Brett

**Comment by markpizz** [comment]
Thanks for the praise.  Most of the credit for the details of where things are and a good number of the simulators is original work done by Bob Supnik.  What were doing now is merely standing on his shoulders.
