### ISSUE TITLE
The Sigma simulator does not read any data from Tape's after attached and then booted

### ISSUE THREAD

**Issue by cvermazen** [simh/simh#671]
The Sigma simulator does not read any data when you start to boot from the tape.
I am trying to boot from a CP-V boot tape.
When booting the tape from a Rad input device it reads the data but transforms it with Little or Big Endian format.
I did already put a lot of investigation in this case but I can't get it to work.

Can some one help me with this ?.

**Comment by markpizz** [comment]
The sigma simulator an experimental simulator.  That means that it will certainly be rough around the edges.  If anyone can help, you will need to provide explicit details about exactly what you did and what happened and what you expected.  The data files and configuration details will also be necessary.  If they're small enough you can zip them and attach them to this issue.

Please put your name in your GitHub profile.

Thanks.

**Comment by cvermazen** [comment]
The version of sigma simh I am using is:

sim> sh ver
XDS Sigma simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 6.3.0 20170516
        Simulator Compiled as C arch: ARM (Release Build) on Mar  8 2019 at 21:23:30
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux pi3plus 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
        git commit id: 2f8fca49
        git commit time: 2019-01-23T15:17:19-08:00
sim> 

<End of version>

The sigma.ini file settings are:

SET CPU SIGMA7B
SET CPU 64K

;  Sigma CP-V operating system tape
ATTACH MT0 -R -E /home/pi/sim/sigma/dev/cpcp.mt
;ATTACH RAD0 -E /home/pi/sim/sigma/dev/cpcp.mt

ECHO ** SHOW DEFAULT BOOT PROGRAM ********************
E 0x20-0x29

SET BREAK 0x2A
BOOT MT0
;BOOT RAD0

ECHO *** SH MT CSTATE ************************************
SH MT CSTATE
;SH RAD CSTATE

ECHO *** E MT0 STATE  *************************************
E  MT0 STATE
;E  RAD0 STATE

ECHO *** E 2A-3F     (Here should be the bootloader program from tape) 
E 0x2A-0x3F

<End of sigma.ini file>


If the above example is run the nothing is loaded from the boot tape. 
I other words the boot loader program from the tape which has to be in location
hex 0x2A until 0x3F is not loaded.

If  I switch from tape MT0 to the RAD0 device is loads the program but it
loads it in Little Endian format. So all the instructions are malformed due to
the Little Endian format.

**Comment by markpizz** [comment]
Well, the 'tape image' you are using CPCP.MT is not a simh format mag tape image, so it isn't surprising that no progress can be made with it.  Digging a little deeper, it seems that the tape format is actually TPC.  The simh framework has support for working with TPC format tape images.  To leverage that you need to do one of:

```
sim> ATTACH MT0 -F TPC CPCP.MT
```
or
```
sim> SET MT0 FORMAT=TPC
sim> ATTACH MT0 CPCP.MT
```

As for connecting that same file to the RAD0 (Fixed Head Disk simulator)... Randomly connecting arbitrary data sets to device simulators would hardly be expected to get very far.  Maybe your inappropriate endian analysis is correct or maybe not.  

Try working with the tape device set to the appropriate format and see if you get further.

Good Luck.

**Comment by cvermazen** [comment]
Hi Mark,

 

Thanks for your answer. I am still chewing on it.

I am writing a conversion program to generate a simh tape format from the boot tape I have.

I did write little programs (Sigma 7) to generate little tape files to see how the format is build up.

 

The only thing I found out that you can’t create a tpc format tape to see how the file format is build-up.

It says when you start it up (format error) when you attach to the output tape. 

 

Regards,

 

Cor Vermazen

 

Van: Mark Pizzolato [mailto:notifications@github.com] 
Verzonden: maandag 11 maart 2019 19:54
Aan: simh/simh
CC: Cornelis Vermazen; Author
Onderwerp: Re: [simh/simh] The Sigma simulator does not read any data from Tape's after attached and then booted (#671)

 

Well, the 'tape image' you are using CPCP.MT is not a simh format mag tape image, so it isn't surprising that no progress can be made with it. Digging a little deeper, it seems that the tape format is actually TPC. The simh framework has support for working with TPC format tape images. To leverage that you need to do one of:

sim> ATTACH MT0 -F TPC CPCP.MT

or

sim> SET MT0 FORMAT=TPC
sim> ATTACH MT0 CPCP.MT

As for connecting that same file to the RAD0 (Fixed Head Disk simulator)... Randomly connecting arbitrary data sets to device simulators would hardly be expected to get very far. Maybe your inappropriate endian analysis is correct or maybe not.

Try working with the tape device set to the appropriate format and see if you get further.

Good Luck.

**Comment by markpizz** [comment]
Well, my initial comment about it being a TPC format tape wasn't correct.  The TPC format is hard to verify since the tape record structure is not contained in very much meta data.

The latest simh now has a more robust process of trying to analyze and verify the structure of the supported tape formats.  Now when a tape is attached in any format, it is read from beginning to end and counts of record sizes are kept and when the logical end of tape is read, the records are read in reverse.  If the tape is well structured and the logical end of tape is at the end of the data in the file the attach completes silently.  If things look somewhat fishy, the structure that was observed is displayed and some advice is offered.  If you want to see what structure has been observed on a tape that otherwise seems to be error free, the -V switch on the attach command will cause that output to be displayed.
```
sim> ATTACH TM0 -VF SIMH CPCP.MT
Tape Image 'CPCP.MT' scanned as SIMH format.
After processing 0 bytes of tape data (0 records, 0 tapemarks)
Read Tape Record Returned Unexpected Status: invalid rec lnt
8680475 bytes of unexamined data remain in the tape image file
sim> DETACH TM0
sim> ATTACH TM0 -VF E11 CPCP.MT
Tape Image 'CPCP.MT' scanned as E11 format.
After processing 0 bytes of tape data (0 records, 0 tapemarks)
Read Tape Record Returned Unexpected Status: invalid rec lnt
8680475 bytes of unexamined data remain in the tape image file
sim> DETACH TM0
sim> ATTACH TM0 -VF TPC CPCP.MT
Tape Image 'CPCP.MT' scanned as TPC format.
contains 8682674 bytes of tape data (437 records, 8987 tapemarks)
Comprising:
      30 1 byte records
       5 2 byte records
       2 3 byte records
       1 4 byte records
       2 6 byte records
       1 7 byte records
       3 8 byte records
       2 10 byte records
       1 12 byte records
      10 16 byte records
       1 19 byte records
       2 22 byte records
       2 25 byte records
       1 29 byte records
       1 30 byte records
       3 39 byte records
       1 46 byte records
       2 60 byte records
       1 64 byte records
       1 69 byte records
       1 70 byte records
       1 80 byte records
       2 91 byte records
       1 98 byte records
       2 104 byte records
       1 106 byte records
       3 128 byte records
       1 132 byte records
       1 137 byte records
       2 138 byte records
       1 154 byte records
       1 160 byte records
       1 164 byte records
      11 168 byte records
       1 192 byte records
       1 202 byte records
       3 204 byte records
       5 205 byte records
       3 206 byte records
       1 207 byte records
       2 208 byte records
       2 215 byte records
       1 224 byte records
       1 248 byte records
      11 256 byte records
       1 260 byte records
       1 296 byte records
       1 360 byte records
       1 448 byte records
       8 512 byte records
       1 740 byte records
       6 768 byte records
       1 769 byte records
       2 1024 byte records
       2 1030 byte records
       7 1280 byte records
       7 1344 byte records
       3 1536 byte records
       1 1600 byte records
       1 1763 byte records
       3 1792 byte records
       1 1793 byte records
       8 2048 byte records
       1 2176 byte records
       1 2304 byte records
       1 2560 byte records
       1 2568 byte records
       5 2816 byte records
       1 3084 byte records
       1 3328 byte records
       1 4101 byte records
       2 4102 byte records
       1 4103 byte records
       1 4147 byte records
       1 4171 byte records
       1 4200 byte records
       1 4201 byte records
       1 4786 byte records
       1 5376 byte records
       1 5632 byte records
       1 5634 byte records
       1 5635 byte records
       1 6323 byte records
       1 6400 byte records
       1 7923 byte records
       1 8224 byte records
       2 8226 byte records
       1 8245 byte records
       1 8256 byte records
       1 8310 byte records
       1 8432 byte records
       1 8713 byte records
       1 8738 byte records
       1 8782 byte records
       1 8872 byte records
       2 9216 byte records
       1 9250 byte records
       1 9432 byte records
       1 9984 byte records
       1 10240 byte records
       1 11009 byte records
       1 11274 byte records
       1 11445 byte records
       1 11821 byte records
       1 11840 byte records
       1 12290 byte records
       1 12320 byte records
       1 12341 byte records
       1 12378 byte records
       1 12699 byte records
       1 13241 byte records
       1 13314 byte records
       2 13568 byte records
       1 13805 byte records
       1 15520 byte records
      15 16448 byte records
       1 16497 byte records
       1 16517 byte records
       1 16601 byte records
       1 16613 byte records
       1 16930 byte records
       1 17156 byte records
       1 17186 byte records
       1 17408 byte records
       1 17420 byte records
       1 17760 byte records
       1 17810 byte records
       1 18694 byte records
       1 18771 byte records
       1 18889 byte records
       1 18944 byte records
       1 19275 byte records
       1 19960 byte records
       1 21218 byte records
       1 22197 byte records
       1 22453 byte records
       1 23040 byte records
       1 23041 byte records
       1 23463 byte records
       1 23472 byte records
       1 23649 byte records
       1 24610 byte records
       1 24682 byte records
       1 25600 byte records
       1 25634 byte records
       1 26705 byte records
       1 27157 byte records
       1 27842 byte records
       1 28160 byte records
       1 28722 byte records
       1 29764 byte records
       1 30162 byte records
       1 30322 byte records
       1 31426 byte records
       1 31432 byte records
       1 31443 byte records
       1 31459 byte records
       1 31702 byte records
       1 32768 byte records
       1 32800 byte records
       1 32802 byte records
       1 32821 byte records
       1 32978 byte records
       1 33394 byte records
       1 33708 byte records
       1 33810 byte records
       1 34327 byte records
       1 34585 byte records
       1 35243 byte records
       1 36075 byte records
       2 36096 byte records
       1 36519 byte records
       1 36535 byte records
       1 37307 byte records
       1 38537 byte records
       1 38600 byte records
       1 38749 byte records
       1 40623 byte records
       1 40705 byte records
       1 41217 byte records
       1 41244 byte records
       1 41478 byte records
       1 41484 byte records
       1 43424 byte records
       1 44480 byte records
       1 45106 byte records
       1 46447 byte records
       1 49059 byte records
       1 49185 byte records
       2 49603 byte records
       1 49604 byte records
       1 49605 byte records
       1 49611 byte records
       1 49670 byte records
       1 49989 byte records
       1 49991 byte records
       1 50129 byte records
       1 50135 byte records
       1 50192 byte records
       2 50373 byte records
       1 50388 byte records
       1 50627 byte records
       1 50628 byte records
       1 50645 byte records
       1 50649 byte records
       1 50695 byte records
       1 51138 byte records
       1 51161 byte records
       1 51513 byte records
       1 51665 byte records
       1 51683 byte records
       1 52172 byte records
       1 52224 byte records
       1 52304 byte records
       1 53348 byte records
       1 53509 byte records
       1 53511 byte records
       1 53512 byte records
       1 53636 byte records
       1 53712 byte records
       1 54002 byte records
       1 54138 byte records
       1 54211 byte records
       1 54231 byte records
       1 54244 byte records
       1 54499 byte records
       1 54702 byte records
       1 54721 byte records
       3 54725 byte records
       1 54742 byte records
       1 54979 byte records
       1 54999 byte records
       1 55162 byte records
       2 55233 byte records
       1 55266 byte records
       2 55267 byte records
       1 55300 byte records
       1 55558 byte records
       1 56016 byte records
       1 56753 byte records
       1 57377 byte records
       1 57381 byte records
       1 57397 byte records
       1 57415 byte records
       1 57525 byte records
       1 57747 byte records
       1 57859 byte records
       1 58082 byte records
       1 58083 byte records
       1 58119 byte records
       1 58306 byte records
       1 58307 byte records
       1 58309 byte records
       1 58313 byte records
       1 58325 byte records
       1 58562 byte records
       1 58839 byte records
       1 59367 byte records
       1 59538 byte records
       1 59568 byte records
       1 59904 byte records
       1 60674 byte records
       1 61166 byte records
       1 61672 byte records
       2 61680 byte records
       1 61818 byte records
       1 62315 byte records
       1 62420 byte records
       1 62966 byte records
       1 63329 byte records
       1 63922 byte records
       1 63985 byte records
       1 63992 byte records
       1 64255 byte records
       1 64278 byte records
       1 65280 byte records
       7 65535 byte records
4294946085 bytes of unexamined data remain in the tape image file
Reverse read of the tape data is inconsistent with the forward read.
sim> DETACH TM0
sim>
```

The file you have does not appear to be a reasonable tape file in any of the accepted formats.  

What drove you to try to connect what you've thought was a tape image file to a disk device?

**Comment by markpizz** [comment]
The file doc/simh_doc.doc is the SIMH User's Guide.

Appendex A.3 describes some details about the various tape image formats that are currently supported.

**Comment by archivisth** [comment]
Definitely not a tape. 14 bytes is the minimum size for a legitimate tape record. The monotonically increasing record sizes indicate a data tape with increasing numbers being interpreted as record lengths.

**Comment by cvermazen** [comment]
This tape is an original boot tape from Sigma CP-V operating system. I found this tapes on https://www.andrews.edu/~calkins/sigma/  
This tapes I have running on an very old laptop with Windows 2000 running as operating system.
There I can do a sysgen of CP-V, on there it runs OK and the sysgen works OK and CP-V starts to run.
Due to the fact that it is not  state of the art technoligy (Windows 2000) I want to run it on Simh.

I did work from 1974 untill 1980 with a Sigma 7 at the company I did work in Amsterdam. So I know the Sigma inside out. I do apreciate all the help I did get from you both at the moment very much.

I am in the process creating a analize and convertion program in C. I did already anilize the first file on tape. (0xBB20C bytes long).

I do include the job log of the first tape file (there are more on the tape)
A CP-V boot tape contains a memory image loaded in blocks of 2048 bytes long.
And there after all the operating system patches (most of them 80 bytes long).

Hereby the primature log of my convertion program:

[cpcp.log](https://github.com/simh/simh/files/2995960/cpcp.log)

The boot tape build up looks like:

32 bit tape mark
32 bit begin record length mark (800)
....
Data 800 bytes
....
32 bit end record length mark (800)
32 bit new begin record length mark (800)
....
Data 800 bytes
....
32 bit end record length mark (800)
32 bit new begin record length mark (800)
....
Data 800 bytes
....
32 bit end record length mark (800)
.....
......
Untill 0xBB20C

The record length vary after the first memory image is loaded.


**I still hear the hummm of fans of the Sigma in my ears !!!!.** 

Cor Vermazen

**Comment by archivisth** [comment]
If you are correct about the format, then the standard boot sequence can't possibly work. According to the Sigma 7 manual, the boot program at 26-29 will attempt to read up to 88 bytes starting at location 2A (hex). It then 'falls through' to execute the instruction at 2A. An initial tape mark will stop the read dead in its tracks, with no data being transmitted; and even if the tape mark is skipped, the initial record is too long.

I'd be the first to admit that the Sigma simulator was written without actual experience on the system or knowledge of its quirks and foibles. Perhaps there's something I missed in the magtape implementation that reads through file marks or ignores them or skips them on rewind. Perhaps channel reads continue even when the byte count is exhausted. But on the face of it, something isn't congruent between the tape format you describe and the operation of the standard boot sequence.

**Comment by markpizz** [comment]
The latest Windows binary has a better automatic validation of tape formats when tape image files are attached.  What you started with was certainly not a tape image in any format that simh understands, so I wouldn't be worrying about whether the sigma_mt device is implemented correctly yet.

Did you get any further with your converted tape image?

**Comment by cvermazen** [comment]
I am still working on the convertion program. (95 % finnisched)
The plan is to create a .simh tape format. More robust the TPC format.
It takes a little time to write.
Also analyzing the cpcp.mt tape is also time consuming.

The boot sequense from the cpcp.mt tape is:

1. It runs the rom program in the Sigma (word location 0x20 - 0x29 standard).

2. This program reads the second boot program from tape which is 0x58 bytes long and is
 loaded after the program in step 1 (word location 02A - 0x3F).

3. This program (from step 2) loads the memory image and stores it to word location 0x5A (byte adr:   0x168) and is 0x800 bytes long).

4. What then happens is memory blocks of 0x800 bytes are loaded in to memory. Stored in byte addresses starting with 0x800 (multiple times). The locations are 0x,800, 0x1000, 0x1800, 0x2000 ..... etc.
What I can read from the progam (step 2) it loads blocks of 0x800 bytes which are on the boot tape.

5. When step 2 program is finnished with loadingmemory blocks of 0x800 bytes it branches from word address 0x36 (BCR,0 0x81DA instr.) to location 0x81DA where the sysgen program starts.

If I put a break at location WA=0x36 then everything must be loaded and can the check what the status is.

There is only a little strange thing in the load procedure. In the phase from location 0x168 load an the next load it overwrites memory. (When step 4 is loaded). Memory loation byte address 0x800.

But I think that was lazy programming when the tape was created.
There is an overlap loading memory images.

**Comment by cvermazen** [comment]
It starts working. After I did create the tape file in .simh format.
Very ruff test run. I did set the BREAK on position 0x36 Word address (WA). 
On the jump in to the loaded memory data blocks.
Checked a bit around for the memory locations or the load went OK.
Then I did give a c (continue) and see hereby the result. It starts moving.

sim> c

ENTER ANY OF:          
I=TTY I/O
P=LP OUTPUT
F=TAPE FILES
T=TAPE PATCHES
C=CARD PATCHES
D=XDELTA
FTP               (I did type this in)

DATE(7//)=
TIME(:)=
NO RESPONSE FOR SWAPPER  DPBF0

DPBF0 => DP
 ??

I do have to set up the devices for the swapper and disc packs and also line printer to do the next test.
But it starts moving.
Thanks for your help and support, both of you.

**Comment by archivisth** [comment]
That's very encouraging and more than a little amazing. The Sigma simulator has only been tested with hand tests and 10 or 11 diagnostics (see the sigma_bugs.txt document). If that document is correct, at least one bug remains outstanding.

Good luck. Please close this issue.
