### ISSUE TITLE
Are the cross assemblers maintained? Where are they documented now?

### ISSUE THREAD

**Issue by rmaldersoniii** [simh/simh#674]
I am looking for information on the PDP-7 cross assembler which was available from the old Trailing Edge hosting site for SimH. In particular, the canonical documentation states that it generates RIM format code, but it is clearly generating relocatable code instead. I am trying to assemble an absolute addressing diagnostic to be loaded via the RIM switch into a physical PDP-7, and cannot see how to force this format (which the program says is the only format, but it lies).

**Comment by markpizz** [comment]
The GitHub simh organization has several repositories.  One of which is the main simulator repository, but another of which is the simtools repository.  I've never used the pdp-7 cross assembler, but it certainly appears to be in the simtools repo (https://github.com/simh/simtools/archive/master.zip).  

If your efforts result in additional documentation or changes to the code, feel free to submit changes either as pull requests to that repo or directly to me via email (mark@infocomm.com).
