### ISSUE TITLE
set throttle x% does not work

### ISSUE THREAD

**Issue by al20878** [simh/simh#678]
Help says:
```
        SET THROTTLE x%             occupy x percent of the host capacity
                                    executing instructions
```

When I execute
```
sim> set throttle 10% 
Invalid throttle specification: 10
sim> set throttle 100%
Invalid throttle specification: 100 
```
I'm using a freshly downloaded MS-WIN executable from the site:
`simh-4.0-Current--2019-03-30-98f6aae3.zip`
- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
sim> sho ver
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Mar 30 2019 at 09:32:30
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.8
        PCRE RegEx (Version 8.36 2014-09-26) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 6.1.7601]
        Architecture: x86 on AMD64, Processors: 4
        Processor Id: Intel64 Family 6 Model 23 Stepping 10, GenuineIntel, Level: 6, Revision: 170a
        git commit id: 98f6aae3
        git commit time: 2019-03-30T09:27:02-07:00
```
- #### the expected behavior and the actual behavior
Either help or the command should be fixed, I suppose

Can you please elaborate how the percentage works?  I assume 10% means that SIMH would use 10% of a host CPU core (right now when I boot RSX11, it seems to burn 100% of one CPU core persistently, regardless of whether there's anything running in the simulated OS or not).

**Comment by markpizz** [comment]
The % has an ambiguous role here.  It is ambiguous since insertion of environment variables is done by mentioning the name surrounded by % characters.  For example: echo %DATE%

Formally, a literal % can be inserted into a command with the string %% in the command.

There shouldn't be a problem allowing a bare (unmatched) % at the end of a line, so that will be allowed.
