### ISSUE TITLE
"eclipse" binary name collides with eclipse IDE

### ISSUE THREAD

**Issue by jwbrase** [simh/simh#679]
- #### Context
In installing a deb package of simh that I had assembled for local use on my Ubuntu desktop, dpkg refused to install the package because the default binary name generated when the eclipse simulator was compiled ("eclipse") collides with the binary for the eclipse IDE (also "eclipse"), which was already installed. I renamed the binary to eclipse-simh via my file browser and rebuilt the package, after which the package installed without issue.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

ECLIPSE simulator V4.0-0 Current

- #### how you built the simulator or that you're using prebuilt binaries

git clone https://github.com/simh/simh.git $MY_BUILD_DIRECTORY
cd $MY_BUILD_DIRECTORY
make

- #### the simulator configuration file (or commands) which were used when the problem occurred.

N/A, the issue is with the executable name generated when compiling, not with any behavior of the executable.

- #### the expected behavior and the actual behavior

Expected behavior: The eclipse simulator should have a distinct name from the eclipse IDE, e.g. "eclipse-simh" or "dg-eclipse".

Actual behavior: Compiling the eclipse simulator produces a binary with a name that collides with the eclipse IDE.

**Comment by markpizz** [comment]
These names have existed in their current forms for many years (since at least 2001).

There really is only a problem if they were to be installed in the same directory.

Even if these were actually installed in the same directory, the problem would exist in the Linux simh package which is not actively maintained (it's been unmodified for more than 8 years),

**Comment by jwbrase** [comment]
There isn't any one "Linux simh package", each distribution has its own repositories, and different distributions have different versions of simh packaged. (e.g., currently 3.8 on Ubuntu, 3.9 on Gentoo and Fedora).

In general, the filesystem structure of Unix systems (not just Linux) will put application binaries all in the same directory, /usr/bin , so the name collision will generally be an issue (I think MacOS likes to put applications in their own directories, but that is probably a relic of its pre-Unix days). Even if they are in different directories, whichever program is in the directory that comes first in the user's $PATH will be the one executed, and the other will have to be called by its full path.

The different distributions have their own solutions to this collision: the Ubuntu package uses "eclipseemu", Fedora prefixes all the simh binaries with "simh-" (so, "simh-eclipse"). Gentoo, being a source-based distribution, appears to pull the source from simh.trailingedge.com and then apply its own patches, which don't seem to alter the compiled executable names, so the collision may actually exist on Gentoo. However, the entire reason I built simh myself and generated a package locally is that the Ubuntu package is out-of-date, as you mentioned. Granted, I could just run simh out of a subdirectory of my home directory without installing it system-wide, but the $PATH collision remains, and it will be something that the package maintainer for simh for any new distribution will have to deal with.

**Comment by markpizz** [comment]
> Granted, I could just run simh out of a subdirectory of my home directory without installing it system-wide, but the $PATH collision remains, and it will be something that the package maintainer for simh for any new distribution will have to deal with.

I'll be glad to work with folks who actually maintain any packages, as soon as someone steps up to that role.

Meanwhile, really interested folks build from the latest source and don't worry about the out of date packages.

**Comment by markpizz** [comment]
Closing this issue until someone comes forward with plans to maintain the OS supplied packages.
