### ISSUE TITLE
printf() format string to argument discrepancy in pdp11

### ISSUE THREAD

**Issue by tangentsoft** [simh/simh#682]
I was just building the latest from master and got this:

> PDP11/pdp11_cpu.c:3562:36: warning: more '%' conversions than data arguments [-Wformat]
>         fprintf (st, "%06o %06o %06o|", h->pc & ~HIST_VLD, h->psw);

It appears to have been introduced by the most recent checkin.

**Comment by markpizz** [comment]
Oops... Typo while hand merging change from Bob Supnik branch.   Now fixed.
