### ISSUE TITLE
vaxstation4000m60 boot result

### ISSUE THREAD

**Issue by TheFausap** [simh/simh#687]
Hello all,
I'm not sure if this is a bug or a standard behaviour, I just clone, compiled and run a vaxstation4000m60 simulator, with the following configuration

```
set cpu 104m
set cpu idle=vms
att xs eth0
set rz0 rz26l
set rz4 rrw11
set rz5 tz30
att rz0 disk0.img
att rz4 VAXVMS071.iso
att rz5 tz30.tap
```
and after the boot cpu (and some internal tests) I got this:

```
KA46-A V1.4-38E-V4.2
08-00-2B-66-27-BC
104MB
                                    
?? 016   2       UNK  0014
?? 001   3        DZ  0032
?? 001   4     CACHE  0768
?? 001   7        IT  8450
?? 001   8       SYS  0128
?? 001   9        NI  0024
?? 020  12       UNK  0014

>>> 
```
the system seems ok, a sh dev shows me all the hardware, so I'm not sure if the output is expected.

thanks
Fausto

**Comment by TheFausap** [comment]
Maybe it's not related, but booting OpenVMS 7.1 for the first installation, I got this

```
-DKA0
%SYSBOOT-I-SYSBOOT Mapping the SYSDUMP.DMP on the System Disk
%SYSBOOT-W-SYSBOOT Can not map SYSDUMP.DMP on the System Disk
%SYSBOOT-I-SYSBOOT Mapping PAGEFILE.SYS on the System Disk
%SYSBOOT-I-SYSBOOT SAVEDUMP parameter not set to protect the PAGEFILE.SYS
%SYSBOOT-E-System version mismatch found EXEC_INIT.EXE
HALT instruction, PC: 0000AAAE (MOVL D31C,R0)

```

**Comment by markpizz** [comment]
If you're thinking the problem you're seeing may or may not be related to the new simulator you're using, I would suggest that you use the VAX simulator (with QVSS enabled) to install and configure the OS disk you are working with.  Once you've got a clean DECwindows working there, just attach that disk to the new simulator and see what happens.

**Comment by TheFausap** [comment]
I don't know if this works. The VAX simulator (I assume you're talking about the microvax3900) has not RZ disks, only the RA, and vaxstation4000 has no RA disks. May I use a disk file generated as RA disk, with the RZ controller?

**Comment by markpizz** [comment]
Yes.  Both the RQ and RZ devices "autosize" on attach, so there will be no problem.  The OS (VMS) dynamically determines disk sizes from the controller they are speaking to, so no problem.

**Comment by TheFausap** [comment]
tested right now. same error. something in the emulation is not working. Could be the GCC used? Mine is GCC 8.3.1
```

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=hsa:nvptx-none
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,ada,go --enable-offload-targets=hsa,nvptx-none=/usr/nvptx-none, --without-cuda-driver --enable-checking=release --disable-werror --with-gxx-include-dir=/usr/include/c++/8 --enable-ssp --disable-libssp --disable-libvtv --disable-cet --disable-libcc1 --enable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --with-slibdir=/lib64 --with-system-zlib --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --with-gcc-major-version-only --enable-linker-build-id --enable-linux-futex --enable-gnu-indirect-function --program-suffix=-8 --without-system-libunwind --enable-multilib --with-arch-32=x86-64 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 8.3.1 20190226 [gcc-8-branch revision 269204] (SUSE Linux) 
```

**Comment by markpizz** [comment]
> tested right now. same error. something in the emulation is not working. Could be the GCC used? Mine is GCC 8.3.1

You haven't been specific about what "same error" you're having.

If that means that you got the same VMS error, rather than blaming the compiler, maybe the problem really is the sequence of things you are doing with VMS or the media you're working with.

The latest VAX VMS is 7.3 and that has a specific version of DECwindows which goes with it.

**Comment by TheFausap** [comment]
The same error I reported above. 

`%SYSBOOT-E-System version mismatch found EXEC_INIT.EXE`

The media is ok. I installed under microvax3900 and vaxstation3100m60, using the same installation procedure.
Only with vaxstation4000 I have this error, maybe is there a specific installation procedure for vaxstation4000, but I cannot be sure.

**Comment by 9track** [comment]
I was able to reproduce this exactly using OpenVMS/VAX 7.1. However, when I reduced the memory size to the default (16MB) I get the following:

```
KA46-A V1.4-38E-V4.2
08-00-2B-97-71-D4
16MB
                                    
?? 001   3        DZ  0032
?? 001   4     CACHE  0768
?? 001   7        IT  7938
?? 001   8       SYS  0128
?? 001   9        NI  0024
```

Note that the unknown devices don't appear now. The other errors are expected as I haven't created patches for this ROM yet and a few aspects of the VAXstation 4000 M60 still aren't implemented. When I boot from the newly installed disk I get:

```
>>> b dka0

 
-DKA0
%SYSBOOT-I-SYSBOOT Mapping the SYSDUMP.DMP on the System Disk
%SYSBOOT-W-SYSBOOT Can not map SYSDUMP.DMP on the System Disk
%SYSBOOT-I-SYSBOOT Mapping PAGEFILE.SYS on the System Disk
%SYSBOOT-I-SYSBOOT SAVEDUMP parameter not set to protect the PAGEFILE.SYS
   OpenVMS (TM) VAX Version BI71-6NO Major version id = 1 Minor version id = 0


           OpenVMS VAX V7.1 Installation Procedure

                         Model: VAXstation 4000-60
                 System device: RZL26 - _DKA0:
                   Free Blocks: 1987512
                      CPU type: 18-04



* Please enter the date and time (DD-MMM-YYYY HH:MM) 
```

So it seems to work with a smaller memory size. I'll have to investigate further.

I did notice some other issues though. Firstly there is an error in the modifiers table in vax4xx_rz94.c as the RRW11 is listed twice and the first entry sets a device type of RRD42. Secondly there is a command (0x42 = Read Sub-Channel) that's missing from sim_scsi.c for CD-ROMs. Neither of these seem to affect the operation of OpenVMS.

The choice of an RRW11 for the installation media is unusual. This is a write-once read-many (WORM) removable cartridge device. It's very close in functionality to a disk so you'll probably get away with it.

**Comment by 9track** [comment]
Actually disregard that I just remembered that the RRW11 is a CD-Recorder not a WORM drive.

**Comment by 9track** [comment]
The DMA address map entries were only capable of addressing 32MB of memory. I've increased this to 128MB for the VAXstation 4000 M60 and MicroVAX 3100 M80. I'm not sure if 128 MB is correct as I can't find any documentation relating to the DMA maps on these systems but it does fix the reported issue.

**Comment by markpizz** [comment]
Hi Matt,

Try to be sure in your commit messages that say "Fixes <hashtag>issuenumber" are only used for relatively simple issues that are somewhat obvious and are completely closed by the commit in question.  I say this since github detects the phrase "Fix" and will automatically close the issue.  Sure you can reopen the issue, but it might be simpler to use phrases like "as discussed in <hashtag>issuenumber" which will get a reference to the commit in question to be added to the issue comments, but leave the issue open so further discussion may naturally follow...

- Mark

**Comment by 9track** [comment]
Apologies for that. I wasn't aware that github used that keyword as a trigger to close the issue.

**Comment by TheFausap** [comment]
Hello I can confirm now, that even with 104mb of RAM, the system is booting without any errors.

**Comment by tuklusan** [comment]
Fausto,

Can you share your final working .ini ?

TIA
Supratim

**Comment by TheFausap** [comment]
Sure.
Here is:

```
set cpu 104m
set cpu idle=vms
att xs eth0
set rz0 rz26l
set rz4 cdrom
set rz5 tz30
att rz0 disk3900.img
att rz4 VAXVMS071.iso
att rz5 tz30.tap
```
