### ISSUE TITLE
Mounting CD ISO image on VAX.EXE works in 3.9 but not in 4.0

### ISSUE THREAD

**Issue by thanratty** [simh/simh#696]
A CD ISO image that can be mounted and read OK in simh 3.9 causes an I/O error and a crash to the simulator in 4.0

I have a fresh install of simh-4.0-Current--2019-04-21-f028802b
I have my OpenVMS hobbyist license keys in a text file on a small CD ISO image.
This ISO mounts OK under simh 3.9 and is readable, but gives the error detailed below on the above 4.0 build.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

sim> show version
MicroVAX 3900 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Apr 21 2019 at 18:42:23
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.8
        PCRE RegEx (Version 8.36 2014-09-26) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 6.1.7601]
        Architecture: x86 on AMD64, Processors: 12
        Processor Id: Intel64 Family 6 Model 45 Stepping 6, GenuineIntel, Level: 6, Revision: 2d06
        git commit id: f028802b
        git commit time: 2019-04-21T16:29:45-07:00
sim>

- #### how you built the simulator or that you're using prebuilt binaries

simh prebuilt Windows binary simh-4.0-Current--2019-04-21-f028802b
Host system:	Windows 7 Pro 6.1.7601 64 bit

- #### the simulator configuration file (or commands) which were used when the problem occurred.

set cpu 512m
at nvr vax.nvr

set xq mac=00-FF-C7-79-D9-62

set rq0 rauser=5000
at  rq0 openvms_73.disk

set rq3 rrd40
at  rq3 Licenses.iso

- #### the expected behavior and the actual behavior

_**Expected Behaviour**_

 $
 $ mount /media_format=cdrom /over=ident dua3
%MOUNT-I-WRITELOCK, volume is write locked
%MOUNT-I-CDROM_ISO, 20171030_192730: (1 of 1) , mounted on  _SIMV$DUA3:
 $
 $ dir dua3:[000000]

Directory DUA3:[000000]

HOBBYIST.TXT;1

Total of 1 file.
 $

_**Actual Behaviour**_

$ mount /media_format=CDROM /over=ident dua3
RQ I/O error: Invalid argument
RQ3 RQ I/O error: The parameter is incorrect.

Unexpected internal error while processing event for RQ3 which returned 66 - I/O error

I/O error, PC: 9E4AA736 (ASHL #1,R3,R0)
sim>

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Please zip up the ISO file and attach drop it into this issue.

Thanks.

**Comment by thanratty** [comment]
[Licenses.iso.zip](https://github.com/simh/simh/files/3135980/Licenses.iso.zip)

ISO image attached as requested.

Regards.

**Comment by markpizz** [comment]
How did you create this ISO file?

**Comment by thanratty** [comment]
Using the Windows program UltraISO Premium Edition 9.5.2.2836.
It mount & reads OK in 3.9.

**Comment by markpizz** [comment]
Thanks for finding this.

Please try the latest (new Windows binaries are available).

**Comment by thanratty** [comment]
Build simh-4.0-Current--2019-05-01-ab3e07a4 now works without error.

Quickest bugfix ever!
