### ISSUE TITLE
Visual Studio build: Post-Build-Event.cmd script parameter quoting

### ISSUE THREAD

**Issue by agn453** [simh/simh#700]
I normally use Cygwin or Linux to build simulators, but I'm using Microsoft Visual Studio 2015 (Community Edition) to look more closely at the issue #698 

I accidently did a Build/Build Solution that proceeded to build all simulators and I noticed 187 errors being thrown up by the Post-Build-Event.cmd file.  Indeed, I have been ignoring this error when building a specific vaxstation3100m38 executable - since I thought the post build testng did not apply.

```
1>------ Build started: Project: VAXstation3100M38, Configuration: Debug Win32 ------
1>  Library support for Visual Studio 2015 is available
1>     Creating library ..\BIN\NT\Win32-Debug\VAXstation3100M38.lib and object ..\BIN\NT\Win32-Debug\VAXstation3100M38.exp
1>  VAXstation3100M38.vcxproj -> C:\Users\tony\Visual Studio 2015\Projects\simh\simh-master\Visual Studio Projects\..\BIN\NT\Win32-Debug\VAXstation3100M38.exe
1>  VAXstation3100M38.vcxproj -> ..\BIN\NT\Win32-Debug\VAXstation3100M38.pdb (Full PDB)
1>EXEC : error : Missing simulator binary: "C:\Users\tony\Visual Studio 2015\Projects\simh\simh-master\BIN\NT\Win32-Debug\VAXstation3100M38.exe"
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "Post-Build-Event.cmd VAX "C:\Users\tony\Visual Studio 2015\Projects\simh\simh-master\BIN\NT\Win32-Debug\VAXstation3100M38.exe" vax-diag_test
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```
Looking into the Post-Build-Event.cmd file I see the second parameter is passed with quotation marks - and it's quoted again in the command file. e.g.

```
if exist "%2" goto _check_script
```

This is what is causing the failure.

If I change this to

```
if exist %2 goto _check_script
```
and further down where ```%2``` is quoted again after the _got_script label, then everything builds without errors.

I should also note that I'm using the latest Windows 10 1903 release (build 18362.86) with filename case-sensitivity enabled.  I'm not sure if any internal windows command file processing changes cause this problem only to appear with similarly configured Windows 10 environments.

```
trillian:~$ diff --strip-trailing-cr -c ~/src/simh-master/Visual\ Studio\ Projects/Post-Build-Event.cmd /c/Users/tony/Visual\ Studio\ 2015/Projects/simh/simh-master/Visual\ Studio\ Projects/Post-Build-Event.cmd
*** "/home/tony/src/simh-master/Visual Studio Projects/Post-Build-Event.cmd"   2019-05-08 11:41:36.000000000 +1000
--- "/c/Users/tony/Visual Studio 2015/Projects/simh/simh-master/Visual Studio Projects/Post-Build-Event.cmd"    2019-05-09 09:45:43.248788300 +1000
***************
*** 12,18 ****
  rem
  rem

! if exist "%2" goto _check_script
  echo error: Missing simulator binary: %2
  exit /B 1

--- 12,18 ----
  rem
  rem

! if exist %2 goto _check_script
  echo error: Missing simulator binary: %2
  exit /B 1

***************
*** 26,29 ****
  exit /B 0

  :_got_script
! "%2" "%_script_path%" "%4"
--- 26,29 ----
  exit /B 0

  :_got_script
! %2 "%_script_path%" "%4"
```

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by jimcausey** [comment]
This doesn't repro for me on VS 2017 on Win10 1903 (18362.1), possibly because I haven't configured case-sensitivity

**Comment by markpizz** [comment]
You really need to avoid case sensitivity with directory trees that you build with Visual Studio.
Some of the VS tools count on the fact that Windows files are generally case insensitive and they either up or lower case some of their arguments arbitrarily.

**Comment by agn453** [comment]
I've already disabled case-sensitivity in my Visual Studio 2015 directory heirarchy

```
C:\Users\tony>fsutil file queryCaseSensitiveInfo "Visual Studio 2015\Projects\simh
Case sensitive attribute on directory C:\Users\tony\Visual Studio 2015\Projects\simh is disabled.
```

(you can use ```fsutil setCaseSensitivity [filename] disable``` to adjust this).

The change I suggested in the Post-Build-Event.cmd script should still work on older systems.  I didn't push the change so that this could be verified by Mark.

**Comment by agn453** [comment]
Thanks Mark.
