### ISSUE TITLE
PDP11: PSW corrupted by breakpoint

### ISSUE THREAD

**Issue by 9track** [simh/simh#701]
The PSW can become corrupted after continuing from a breakpoint. I think this is due to the following assignment near the beginning of the instruction loop:
https://github.com/simh/simh/blob/db26349bd75f2fe796234a3206505e4a14cc661f/PDP11/pdp11_cpu.c#L940
The PSW variable is only updated periodically when sim_interval expires and can therefore contain stale data. I think the assignment should be:
```
inst_psw = get_PSW ();
```
- #### simulator configuration file

```
d -m 00 BIS #170000,@#177776
d -m 06 NOP
d -m 10 NOP
d -m 12 NOP
d -m 14 NOP
d -m 16 NOP
d -m 20 BIC #170000,@#177776
d -m 26 NOP
d -m 30 NOP
d -m 32 NOP
d -m 34 NOP
d -m 36 NOP

set cpu history=100
set break 34

go 0
step 2
show cpu history
```
- #### expected behavior
```
PC     SP     PSW     src    dst     IR

000000 000000 000000|170000 170000  BIS #170000,@#177776
000006 000000 170000|       000000  NOP
000010 000000 170000|       000000  NOP
000012 000000 170000|       000000  NOP
000014 000000 170000|       000000  NOP
000016 000000 170000|       000000  NOP
000020 000000 170000|170000 000000  BIC #170000,@#177776
000026 000000 000000|       000000  NOP
000030 000000 000000|       000000  NOP
000032 000000 000000|       000000  NOP
000034 000000 000000|       000000  NOP    <--- PSW same after breakpoint
000036 000000 000000|       000000  NOP
```
- #### actual behavior
```
PC     SP     PSW     src    dst     IR

000000 000000 000000|170000 170000  BIS #170000,@#177776
000006 000000 170000|       000000  NOP
000010 000000 170000|       000000  NOP
000012 000000 170000|       000000  NOP
000014 000000 170000|       000000  NOP
000016 000000 170000|       000000  NOP
000020 000000 170000|170000 000000  BIC #170000,@#177776
000026 000000 000000|       000000  NOP
000030 000000 000000|       000000  NOP
000032 000000 000000|       000000  NOP
000034 000000 170000|       000000  NOP    <--- PSW changed after breakpoint
000036 000000 170000|       000000  NOP
```

**Comment by markpizz** [comment]
The last person to mess with PDP11 breakpoints of various types was @pkoning2

**Comment by pkoning2** [comment]
Ouch.  I'm not sure if I brought you that bug but in any case I'll take a look.

**Comment by pkoning2** [comment]
Yes, this is mine.
The fix works, thanks for that and the clear test case.
I was hoping to do something a bit more complex to avoid calling get_PSW (which is a fair amount of code) every time, but I don't see a clean way to do that.  It would be easier if only breakpoints were at issue, but in fact inst_psw is used for anything that calls ABORT, which is more than just breakpoints.
