### ISSUE TITLE
PDP-11: Can no longer attach RT-11 5.3 disk image.

### ISSUE THREAD

**Issue by jqw123** [simh/simh#704]
It seems that the recent changes to add RT-11 filesystem disk size detection to the PDP-11 simulator seems to be broken, at least with respect to the disk image of RT-11 5.3 held on trailing-edge.com. I've no been able to attach this file many times in the past, but the recent changes seem to have broken things.

Attached is a screenshot from the Windows subsystem for Linux running the current Debian stable. I've also had the problem on current Raspbian running on a Raspberry Pi Zero W - the same message, apart from the quoted max partition size being 5242KW instead.

![Annotation 2019-05-19 222906](https://user-images.githubusercontent.com/39457600/57988485-04ba4280-7a87-11e9-9fac-3a54565a4926.png)

**Comment by markpizz** [comment]
Thanks for reporting this.  We're looking into the detail.

Meanwhile, please put your full name on your GitHub account so we know who we're talking to.

**Comment by jqw123** [comment]
Seems better - now sees just the one partition, but still fails to mount this image:

`sim> at rl0 Disks/rtv53_rl.dsk
RL0: 'Disks/rtv53_rl.dsk' Contains RT11 partitions
1 valid partition, Type: V05, Sectors On Disk: 20450
RL0: The file system on the disk Disks/rtv53_rl.dsk is larger than simulated device (5235KW > 2621KW)
File open error`

**Comment by markpizz** [comment]
The fundamental file system size detection logic has been corrected when there is an RT11 file system on a disk.

There is a separate problem which is that RL devices (and possibly other disk devices that have fixed sized disk models: HK and RP) don't autosize correctly when a file system has been detected on a disk image at attach time.

**Comment by jqw123** [comment]
That appears to have fixed it. Thanks!
