### ISSUE TITLE
PDP10 TOPS-10 7.04 MIC problem

### ISSUE THREAD

**Issue by davygoat** [simh/simh#710]
TOPS-10 7.04 generates an illegal memory reference if a MIC script invokes another MIC script, and any subsequent attempt to run a MIC script will result in the job consuming large amounts of CPU time.

```
.COPY MAIN.MIC=TT:
.dir
.do sub
.dir
*Ctrl/Z*
.COPY SUB.MIC=TT:
.dir
*Ctrl/Z*
.
.DO MAIN

.dir

MAIN  MIC     1  <057>   12-Jun-19    DSKB:   [42,42]
SUB   MIC     1  <057>   12-Jun-19

?Illegal memory reference at user PC 401677.
.
```

TOPS-10 7.03 has no problem with MIC scripts invoking other MIC scripts, and 7.04 works under KLH10, but not simh.

My reasons for submitting this problem include:

- TOPS-10 7.04 supports later VT models.
- EDT comes up quicker.
- SET KSYS NOW works. Under 7.03 I have to use +0:01, which can take up to 2 minutes.
- Built-in idle support under simh. KLH does not have this.
- The ability to run MIC scripts from MIC scripts makes "sylogin.com" possible under TOPS-10.
- I'd like to keep my MIC scripts small and modular.
- This is too obvious a denial of service for an unprivileged user to get away with.
- I'm not sure if it's a TOPS-10 on KS problem, or a simh problem (e.g. DZ11 related).

git hash 8c4f8b0b, built after git pull, make pdp10.

```
PDP-10 simulator V4.0-0 Current        git commit id: 8c4f8b0b
sim> show version
PDP-10 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 5.5.0
        Simulator Compiled as C arch: x64 (Release Build) on Jun 11 2019 at 17:51:16
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux slackware 4.4.172 #2 SMP Wed Jan 30 17:11:07 CST 2019 x86_64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz GenuineIntel GNU/Linux
        git commit id: 8c4f8b0b
        git commit time: 2019-06-10T14:55:05-0700
sim>

```

TOPS-10 7.04 installation with the problem files, and more detailed instructions can be found on my Google drive:
https://drive.google.com/open?id=1kZZxIAG4ya5QOG3dMyQ4Nl5G99PQbOHI

**Comment by R-Voorhorst** [comment]
Before sending Mark on a wild goose chase in the Simh simulator code, this looks more like a generated monitor TOPS10 7.04 and software error than otherwise. Moreover, contrary to your observations, V7.04 does work on simh KS10 as well as on KLH10, as does V 7.05 and even later additions. 
Probably this specific generated used monitor is in error somewhat, somewhere .....

As I have various versions of Tops10 on line on KLH10 as well as on Simh KS10, I will look shortly if the signaled erroneous is present on my system(s) and will get back on it. The mic scripts should not be too difficult to test.


Best regards,

R.V.

**Comment by R-Voorhorst** [comment]
L.S.

 As a quick initial test, I tried this nested MIC construct on a Tops10 7.05(33772) (say the latest more or less official version of Tops10 V7.04) on a Simh KS10 with a commit of mar-2017, so not a quite so recent commit of simh, but with a recent monitor update version. The signaled error does not appear and it behaves as expected as it should.
So in my opinion this strengthens the case for a monitor error and not a simh code error.

I will try to test a recent commit with some versions of Tops10 monitor later this weekend.


Best regards,

R.V.

**Comment by markpizz** [comment]
While @R-voorhorst is working on checking the PDP10 OS version, I'm traveling today, @davygoat can you see if this problem also occurs when you build the PDP10 simulator from the Supnik-Current branch of the GitHub.com/simh/simh repo?

**Comment by davygoat** [comment]
> While @R-Voorhorst is working on checking the PDP10 OS version, I'm traveling today, @davygoat can you see if this problem also occurs when you build the PDP10 simulator from the Supnik-Current branch of the GitHub.com/simh/simh repo?

Hello Mark,

Just got home and tried. Yes, the Supnik-Current branch (V3.10-0) has the same problem.

David.

**Comment by davygoat** [comment]
> L.S.
> 
> As a quick initial test, I tried this nested MIC construct on a Tops10 7.05(33772) (say the latest more or less official version of Tops10 V7.04) on a Simh KS10 with a commit of mar-2017, so not a quite so recent commit of simh, but with a recent monitor update version. The signaled error does not appear and it behaves as expected as it should.
> So in my opinion this strengthens the case for a monitor error and not a simh code error.
> 
> I will try to test a recent commit with some versions of Tops10 monitor later this weekend.
> 
> Best regards,
> 
> R.V.

Hello R.V.,

It's a fresh install, basically following the MIG, via Quentin North's blog. Here's a link to a transcript I made, with my inputs highlighted. He reports the same problem on his system.

https://drive.google.com/open?id=1GbNl7Uh6Ewxx29e82pQs8--mVtIXmvZn

David.

**Comment by R-Voorhorst** [comment]
L.S.
I cloned the last commit and build the last version:
sim> show vers
PDP-10 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 19.00.23506.00
        Simulator Compiled as C arch: x86 (Debug Build) on Jun 14 2019 at 21:00:26
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.36 2014-09-26) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 6.1.7601]
        Architecture: x86 on AMD64, Processors: 4
        Processor Id: Intel64 Family 6 Model 23 Stepping 10, GenuineIntel, Level: 6, Revision: 170a
        git commit id: 8c4f8b0b
        git commit time: 2019-06-10T14:55:05-07:00

I repeated the test from the old commit in the new one and the results are exactly the same.
Therefor, it is a safe conclusion that the simh implementation is not an issue in resolving this problem.
So Mark's input is not necessary for the resolution of this problem as it appears to be a proper Tops10 problem: either MIC or the monitor or even both.

The mic (the executor of DO) version I use is 11D(1240), yours is 11C(1235), not quite a large difference in versioning. However, when replacing the mic file with a  the latest version, the problem remains still the same. So it appears there may be a monitor problem lurking in the background.
With this, intermediate, result I will try to zoom in in a later post addressing some remarks made in the opening question.


For now, best regards,

R.V.

**Comment by R-Voorhorst** [comment]
Some points to address referring to your first post:

1. By  the way, your MIC 11C(1235) worked as well when executed on the Tops10 7.05(33772) monitor, so it really looks like a monitor problem in the distribution used for the install.

2. Is there a special requirement to use Tops10 7.04(33461) instead of the latest "somewhat official DEC" version Tops10 7.05( 33771) as released with KLH10 (Larry Senlovsky)?

3. EDT is a stand alone program, at the time released on the 10/20 and VMS integration tapes from Dec Grenoble and it's performance has little to do with the monitor; I have not seen quicker activation responses on the various monitor versions. There is a large difference though in performance between KLH10 and Simh; the KLH10 implementation is quite a lot faster than any simh. Reason I use KLH10 mainly for building large monitor sets.

4. KLH10 does have built in idle support, however KLH relies on a specific IO instruction to be present in the Tops10 monitor. Simh detects within the simulator the 2 instructions used when KS is idling and then enters idling mode. The best solution for integrated KLH10 idling is within the Tops10 monitor defining the KLH10 as a separate type of processor (Mongen) and with processor specific type condition testing modifying the idle loop code with the needed IO instruction for the KLH10. That is the way I integrated it in the various monitor versions the KLH10 uses.

Concluding I suppose the best way to go is using TOPS10 7.05(33771/2) but your mileage may vary ...


Best regards,

R.V.

**Comment by davygoat** [comment]
Hello R.V.

Thankyou for looking into this. It's more than I expected.

You refer to TOPS-10 7.05, a.k.a. the latest somewhat official version. How is this arrived at? Is it a matter of applying the TSU tapes? If so, do they have to be applied in order (bitsavers refers to four sets of three tapes, one tape seems to be missing). Or does TSU4 include all the previous updates?

For KLH10, the documentation tells you how to TOPS-10 idling might be implemented, but it does not give specifics for someone who is not a native MACRO speaker. Does anyone have a soup/diff file that could be used as a guide?

Thanks again,
David.

**Comment by R-Voorhorst** [comment]
L.S.

To make a clear cut, I based Tops10 V7.05 (33771) on the KLH10 Tops10 distribution with it's monitor versions 33771 and 33772 whih are the version numbers then used. However a 33772 monitor cannot be generated with the available sources there, so I based it on that latest version delivered with KLH and the latest autopatch tapes (Shoppa's Tops10/20 software archive) available from Dec and called that 33772. 

New functionalities (like KLH idling, Y2k compliance where possible and patched/updated drivers and cusps, booting for all disk types and extended disk types/sizes) I reserved for a new version Tops10 V7.06.


Best  regards,

R. V.

**Comment by markpizz** [comment]
Can you provide precise details about how KLH does idling?  We can certainly add that to simh and thus make simh and KLH binary compatible.  Maybe you want to submit a patch for this...

**Comment by davygoat** [comment]
I'm happy that the problem is not with simh. Are you happy for me to close this issue now?

**Comment by R-Voorhorst** [comment]
I will comment on Marks post - I must finish something for that - then it can be closed.

R. V.

**Comment by Rhialto** [comment]
On Fri 21 Jun 2019 at 11:26:37 -0700, Mark Pizzolato wrote:
> Can you provide precise details about how KLH does idling?  We can
> certainly add that to simh and thus make simh and KLH binary
> compatible.  Maybe you want to submit a patch for this...

Here described is how KLH does it:
https://github.com/PDP-10/klh10/blob/master/doc/dvhost.txt

Code (insofar relevant) is at
https://github.com/PDP-10/klh10/blob/master/src/dvhost.c

**Comment by markpizz** [comment]
I can do this myself if someone provides a KLH10 KS10 disk image that includes this idling functionality.  

A starting simh configuration file would be useful and instructions of how to boot the system far enough that it starts idling...

**Comment by larsbrinkhoff** [comment]
If no one offers to help, I can prepare an ITS disk image.

Or make one yourself by cloning http://github.com/PDP-10/its, and type `make EMULATOR=klh10`

**Comment by davygoat** [comment]
Sorry I can't help. Other than bringing up "twonky" to check that mic could invoke mic, I have not done much else with KLH10. I presume twonky is a KL rather than KS.

David.

**Comment by R-Voorhorst** [comment]
As the topic is moving to a different context - from a monitor version that doesn't play wel with MIC to an implementation of an idling mechanism on the host for the guest simulator - I propose the following:

@David: if you can offline either specify for me what TOPS10 KS10(simh)/KL10(Klh10) configuration you want (eventually accompanied by the Simh/Klh10- config file) to have or provide a MONGEN generated SYSCNF.MAC, possibly edited by hand for the correct details, I can build you a V7.05(33772) monitor on a virtual TOPS10 disk to be downloaded via Google drive. This can be done, if properly specified, almost turnaround.

@Mark: I will open a new issue regarding idling on KS10/KLH10 in virtual hardware and software.

Then, this thread has been dealt with regarding the MIC problem and David can close it.


Best regards,

R.V.

**Comment by davygoat** [comment]
@R-Voorhorst: My current system is TOPS-10 7.03, which I was hoping to move to 7.04. I have uploaded a tape to my Google Drive that contains HDWCNF.MAC and the MIC script containing my MONGEN responses. There is nothing very special about it other than having some ersatzen and a few extra commands. I have no particular preference for KS or KL. Since you write that TOPS-10 runs better on KL, you may as well nudge me to a KLH10 build with plenty of memory.

https://drive.google.com/open?id=1VEF8Z8ShbJMQxh_yV8ZtPh45KoqKM3_U

Contact details are in a file called README.TXT on the tape.

Thankyou again for your help.
David.
