### ISSUE TITLE
PDP10: Systems Concepts DC-10 disk controller

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#722]
The DC-10 was a disk controller used with the MIT AI lab PDP-10.  It's a channel that can connect up to 16 IBM 2314 compatible drives.  MIT initially used Memorex drives, but later upgraded to dual density Calcomps.

I have a work in progress nearing completion.  I made some notes here:  https://github.com/rcornwell/sims/issues/116

(Systems Concepts later made the SA-10 disk controller, but it's a different design.)

**Comment by larsbrinkhoff** [comment]
The major motivation for adding this simulation is to be able to run a 1972 version of ITS.  At this time, support for RP10 had not yet been added.

**Comment by rcornwell** [comment]
Please add this via my sims repo!

**Comment by larsbrinkhoff** [comment]
Ok.
