### ISSUE TITLE
Question: Using simh under expect - separate simulator and system console streams

### ISSUE THREAD

**Issue by wfjm** [simh/simh#728]
I've setup for the [wfjm/w11](https://github.com/wfjm/w11) project a tcl expect based test environment which boots and test runs the available operating systems in a fully automated fashion. I'd like to extend this test suite such that the simh pdp11 is used as alternative execution engine.

For this it be very helpful if 
- the pdp11 console communication and the simh console communication could be separated
- the 1st DL11 (the pdp11 console) and additional DL11 or DZ11 ports be could be treated in a symmetric manner

I tried `att tti 5760` but that results in `Unit not attachable`.

Question: is there a way to separate simulator and system console streams ?

**Comment by markpizz** [comment]
The simh framework has EXPECT and SEND support builtin. In this context, the timing of these interactions are precise and in lock step with instruction execution.  The built-in support can readily be used to examine (EXPECT) and inject (SEND) arbitrary data from (EXPECT) or into (SEND) any serial port on the simulator.  Console EXPECT/SEND traffic deals with CPU (vs simulator) generated traffic.  You might want to try this approach.  

Meanwhile, to answer your  specific question about separating the CPU generated vs the simulator generated input/output, there is:

    sim> SET CONSOLE TELNET=5760
which will then connect the CPU generated (and accepted) traffic to the specified TCP port.  In this mode, a TCP connection will then have to be established before instruction execution can continue.

The command:

    sim> SET CONSOLE TELNET=5760,TELNET=BUFFERED
will allow execution to proceed without an active TCP connection to port 5760 and EXPECT/SEND interactions will still be processed normally.

**Comment by wfjm** [comment]
Dear Mark,

thanks for the fast reply and sorry for my slow response, I had last week some real surprise with one of my FPGA boards (see [blog](https://wfjm.github.io/blogs/w11/2019-07-27-nexys4-obituary.html)).

The simh expect logic is nice for simh-only testing. What I'm after is a test suite which runs the same tests on either my [w11](https://github.com/wfjm/w11) FPGA implementation of the simh Emulation. The test logic is in tcl expect, and depending on a loadable backend either run against an FPGA or a pdp11 session.
Tests look like [this code](https://github.com/wfjm/w11/blob/master/tools/oskit/test/os/211bsd/211bsd_base.tcl) which often encapsulates expect commands in a [wrapper layer](https://github.com/wfjm/w11/blob/master/tools/tcl/exptest/util.tcl). 

Using `set console telnet` and `set remote telnet` is exactly what is needed to remote control the simh session from a tcl expect session.

Thanks,    Walter
