### ISSUE TITLE
enable/disable PDP11 massbus adapters

### ISSUE THREAD

**Issue by wfjm** [simh/simh#733]
**Context**: pdp11 of commit 2f707ffc.
**Short description**:
Tried `set rha enabled` and got `Command not allowed`. That used to work under simh V3.9.
Questions: 
- how to enable/disable a massbus adapter ?
- is it intentional that v4 seems not to be upward incompatible with v3.9 ?

**Long description**:

In current simh I get
```
  PDP-11 simulator V4.0-0 Current        git commit id: 2f707ffc
sho rha
  RHA     address=17776700-17776753, vector=254, BR5
sho rhb
  RHB     disabled
set rha disabled
  Command not allowed
set rha enabled
  Command not allowed
set rhb enabled
  Command not allowed
```

In simh V3.9 it was possible to enable/disable PDP11 Massbus Adapters with commands like `set rha enabled`
```
  PDP-11 simulator V3.9-0

sho rha
  RHA, address=17776700-17776753, vector=254
sho rhb
  RHB, disabled

set rha disabled
sho rha
  RHA, disabled
set rha enabled
  RHA, address=17776700-17776753, vector=254
set rhb enabled
sho rhb
  RHB, address=17772440-17772477, vector=224
```

**Comment by markpizz** [comment]
There is indeed a lack of precise upward compatibility between 3.9 and 4.X.  Things are more robust in the current model and flow through reliably with autoconfigure.

On the PDP11, each of the RHA, RHB and RHC mass bus adapters are actually explicitly bound to support a particular device.  RHA (aka MBA0) -> RP, RHB (aka MBA1) -> TU, and RHC (aka MBA2) -> RS.  This is to support compatible Operating Systems built with 3.9 vs those built for 4.x.

Meanwhile, on the VAX780 (and VAX8600), the MBA0 will get RP if RP is enabled and it will get TU if only TU is enabled.  If both RP and TU are enabled then RP is on MBA0 and TU is on MBA1. VMS will autoconfigure these correctly this way.  If a system only had TU and no RP, then under the 3.9 implementation VMS will not find the TU device.

To enable or disable a particular MBA, merely enable or disable the related connected device.
