### ISSUE TITLE
Sockets on state TIME_WAIT; how to enable SO_REUSEADDR support

### ISSUE THREAD

**Issue by wfjm** [simh/simh#735]
**Context**: pdp11 of commit 2f707ff.

I'm trying a setup with a telnet master and a telnet console, after
```
set cons telnet=5670
set cons telnet=buffered
set remote connections=1
set remote telnet=5679
set remote master
```

Works fine, but when I end simh with a plain `exit` the two sockets are in `TIME_WAIT` state
```
netstat  | grep TIME_WAIT
  tcp6       0      0 localhost:5679          localhost:48410         TIME_WAIT  
  tcp6       0      0 localhost:5670          localhost:32924         TIME_WAIT  
```

and will hang in this state for 60 seconds (my system default inquired via `/proc/sys/net/ipv4/tcp_fin_timeout`). Very well known problem (see [stackoverflow](https://stackoverflow.com/questions/3229860)) with a as well known solution (see [stackoverflow](https://stackoverflow.com/questions/1931043)). I use in [w11](https://github.com/wfjm/w11) the `SO_REUSEADDR` socket option, and I've seen in the simh code base that in [sim_sock.c](https://github.com/simh/simh/blob/master/sim_sock.c) the `SO_REUSEADDR` is used under some conditions.

So I wonder
- what to do to ensure that simh closes all sockets properly
- what to do to enable usage of  `SO_REUSEADDR`

**Comment by markpizz** [comment]
In general, the SO_REUSEADDR option is usually enabled by a -U switch specified on the simh command that creates the listening socket. So:
```
set -U cons telnet=5670
set cons telnet=buffered
set remote connections=1
set -U remote telnet=5679
```
should do what you want.
