### ISSUE TITLE
Using 'remote master': how to determine end-of-response

### ISSUE THREAD

**Issue by wfjm** [simh/simh#736]
**Context**: pdp11 of commit 2f707ff.

I trying to setup an environment in which simh is controlled by a tcl expect session (see last answer in #728). So I use
```
set cons telnet=5670
set cons telnet=buffered
set remote connections=1
set remote telnet=5679
set remote master
```

and open a telnet connection to port 5679. After the `boot` command the simulator returns
```
Simulator Running...
```
and command prompt. The command prompt `SIM>` appears when a single character is send to the simulator. The simulator continues running, as it should. When the command is entered and `\n` is received, the command is executed, potential output send, but no command prompt displayed again.

On the tcl expect level one would like to unambiguously see when a command is completed. At the moment I send a extra blank after the terminating `\n` of a command and provoke a new command prompt this way.

So I wonder
- why is the `SIM>` prompt handled this way ?
- is the workaround described above safe ?

**Comment by markpizz** [comment]
There are two types of command entry modes in the remote console facility:
1) The single command mode (which you're currently interacting with).  In this mode the command is injected to the running simulator and produces specific results between the execution of two simulated instructions and simulator instruction execution continues immediately.
2) The multiple command mode which is entered by sending the WRU character (^E).  This mode suspends instruction execution and allows an arbitrary number of commands to be entered in sequence until an explicit CONTINUE command is executed, OR until a configurable timeout has elapsed.

A more robust way to be sure you've seen all of the output from the prior command would be to send a comment (i.e. a line starting with # or ; followed by a newline).  When whatever this command comes back to you, your output is complete.
