### ISSUE TITLE
PDP8 - Cannot EXAMINE data field register "e df" Too few arguments

### ISSUE THREAD

**Issue by pdr0663** [simh/simh#747]
- #### Context
When trying to examine the value of the data field register using "e df", the system responds with:
Too few arguments.

The instruction field register may be successfully read with "e if" so I'm not sure why "e df" won;t work.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
PDP-8 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Jul  1 2019 at 08:20:35
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.36 2014-09-26) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 10.0.17134.885]
        Architecture: x86 on AMD64, Processors: 4
        Processor Id: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel, Level: 6, Revision: 4501
        git commit id: 81472b58
        git commit time: 2019-07-01T08:11:46-07:00
- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by R-Voorhorst** [comment]
This is a collision between DF data field and the DF(32) disk file drive (devno 60,62).

E DF STATE gives the DF particulars.
E CPU STATE give the IF and the DF (among others).

sim> e df state
STA:    0000
DA:     0000
WC:     0000
MA:     0000
DONE:   1
INT:    0
WLS:    000
TIME:   10
BURST:  1
STOP_IOE:       1
sim> e cpu state
PC:     00000
AC:     0000
L:      0
MQ:     0000
SR:     0000
IF:     0
**DF:     0**
IB:     0
SF:     000
UB:     0
UF:     0
SC:     00
GTF:    0
EMODE:  0
ION:    0
ION_DELAY:      0
CIF_DELAY:      1
PWR_INT:        0
UF_INT: 0
INT:    1000000000
DONE:   00000
ENABLE: 02137
PCQ[0]: 00000
PCQ[1]-PCQ[63]: same as above
STOP_INST:      0
WRU:    005
sim>

B.R.
R.V.

**Comment by markpizz** [comment]
@R-Voorhorst covered the explanation.  

The default EXAMINE/DEPOSIT argument parsing will display the contents of a particular register you mention by name only as long as that register name is unique across all devices in the simulator.  If you're interested in a particular register in a specific simulator device (in this case the device is the CPU), you can either display all of the registers in a device as @R-Voorhorst mentioned with EX CPU STATE or the individual register by:
```
sim> EX CPU DF
DF:     0
sim>
```

It is unfortunate that the device name for the DF32 fixed head disk (conflicts with the register name in the CPU device).  The device name choice was made a long time ago, so we won't be changing it to address the problem you've found.  Sorry.

**Comment by pdr0663** [comment]
Ok
EX CPU DF
is more than adequate, thanks so much for your help!

Paul
