### ISSUE TITLE
PDP-11: Bitmapped frame buffer

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#748]
I addition to the previously added "NG" vector display (#642), I believe the MIT Logo group PDP-11/45 had some kind of bitmapped frame buffer hardware.  It would have been similar to the Knight TV hardware for the AI lab PDP-10.  There may have been monochrome and color versions.  Since the 11/45 also shared memory with the PDP-10, ITS programs could also draw on the frame buffers.

Software:
- Lisp Logo on ITS
- "SPIRO" on ITS (https://github.com/PDP-10/its/issues/1417)
- SITS, the Logo group timesharing system (https://github.com/PDP-10/its/issues/1730)
- Maybe 11LOGO?

**Comment by larsbrinkhoff** [comment]
Hardware registers according to SITS source code.

```
;TV VARIABLES
TVINCR=164140   ;THE INCREMENT REGISTER FOR THE TV'S
TVINC==77       ;THE MASK FOR THE INCREMENT
TVINT==100000   ;INTERRUPT BIT FOR THE PSEUDO TV STATUS WORDS
TVRSET==100000  ;THE RESET BIT
TVCLRW==400     ;THE COLOR WRITE BIT
TVSEL=164142    ;THE CONSOLE SELECT REGISTER
TVRCNS==77      ;THE CONSOLE NUMBER MASK
TVRWMD==300     ;THE REGULAR WRITE MODE MASK
TVNSH==0        ;NO SHIFT WRITE MODE
TVIOR==100      ;THE INCLUSIVE OR MODE
TVXOR==200      ;THE XOR MODE
TVMOV==300      ;THE MOVE FUNCTION
TVDCNS==TVRCNS*400      ;THE DISK CONSOLE NUMBER (SAME, BUT IN TOP BYTE)
TVDWMD==TVRWMD*400      ;THE DISK WRITE MODE MASK
TVRADR=164144   ;THE REGULAR ADDRESS REGISTER
TVWC=164146     ;THE WORD COUNT FOR THE BLOCK WRITE
TVDADR=164150   ;THE DISK TRANSFER ADDRESS REGISTER
TVSHR=164152    ;THE SHIFT REGISTER
TVSHCN==17      ;THE SHIFT COUNT
;TVMAP==17400   ;THE START OF THE 16K PAGE (IN 4K BLOCKS)
TVAMAP==20000   ;THE ACTIVATE TVMAP BIT
TVMSK=164154    ;THE MASK REGISTER
TVDWIN=164156   ;THE WINDOW FOR DISK TRANSFERS
TVRWIN=164160   ;THE WINDOW FOR REGULAR TRANSFERS
TVCNSL=164162   ;THE CONSOLE REGISTER FOR THE MEMORY
TVCLR==160000   ;THE COLOR NUMBER

LKBB==164100    ;LEBEL KEYBOARD INTERFACE
VIDSW=164104    ;VIDEO SWITCH
TVDOIT==11

**Comment by larsbrinkhoff** [comment]
@markpizz, it seems there are two distinct tests of hardware registers: 164140-16162, and 164100-164101.  Do I need to make two DEVICE entities, or can a single DEVICE have more than one IO page region?

**Comment by larsbrinkhoff** [comment]
I have implemented a stub device: https://github.com/larsbrinkhoff/simh/commits/lars/logotv

**Comment by markpizz** [comment]
I will look closely at this problem and let you know what avenue to take.  I won't be able to do for possibly a couple of days.

**Comment by markpizz** [comment]
Please describe this oddball device’s full complement of system resources (Bus Addresses and vectors), AND specifically what those addresses (and vectors) are used for.

**Comment by markpizz** [comment]
Oops.  You had already provided the register list.

You should indeed have two devices (in the same source module).  The device reset routine in both of these devices should contain logic that detects the enable/disable transition of the respective device and then performs the same enable or disable on the other device if it isn't already in the new state.

**Comment by larsbrinkhoff** [comment]
Thank you.

**Comment by markpizz** [comment]
After some additional thinking, what was previously said is still true, along with the DEVICE that handles the terminal should NOT have the DEV_DISABLE flag set in it's DEVICE flags field.  This way, the only way to turn on or off any of this functionality is to:
```
sim> SET frame-buffer-dev-name ENABLE
OR
SET frame-buffer-dev-name DISABLE
```
Both of these devices should start with the DEV_DIS flag specified.

**Comment by markpizz** [comment]
This has been properly addressed long ago, right?  If not, please reopen.
