### ISSUE TITLE
PDP11: Order of enabling RF and VH devices matter

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#753]
- #### Context
The PDP-11 RF device must be enabled before VH if VH has a non-standard address, or else RF will lose its Unibus address and interrupt vector.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
PDP-11 simulator V4.0-0 Current        git commit id: +2a9826c

- #### how you built the simulator or that you're using prebuilt binaries
make pdp11

- #### the simulator configuration file (or commands) which were used when the problem occurred.
Attached below.

- #### the expected behavior and the actual behavior
Described below.

**Comment by larsbrinkhoff** [comment]
SIMH configuration with expected result:

```
set cpu 11/45
set rf enabled
set vh enabled addr=17760020 vector=340 lines=16
show rf
show vh
```

Output:

```
PDP-11 simulator V4.0-0 Current        git commit id: +2a9826c
Disabling XQ
RF      address=17777460-17777477, vector=204, BR5
        262KW, not attached
VH      address=17760020-17760037*, vector=340-344*, BR4, lines=16
        not attached, DHU mode

**Comment by larsbrinkhoff** [comment]
SIMH configuration with unexpected result:

```
set cpu 11/45
set vh enabled addr=17760020 vector=340 lines=16
set rf enabled
show rf
show vh
```

Output:

```
PDP-11 simulator V4.0-0 Current        git commit id: +2a9826c
Disabling XQ
RF      no vector, BR5
        262KW, not attached
VH      address=17760020-17760037*, vector=340-344*, BR4, lines=16
        not attached, DHU mode

**Comment by larsbrinkhoff** [comment]
Update, if VH has the standard Unibus address there is no problem.

**Comment by markpizz** [comment]
As soon as you enter ANY hard coded address or vector in a configuration, you own configuring addresses and vectors for all other devices.  Specifically setting an address or vector disables the autoconfiguration process which would normally assign addresses and vectors for devices.

**Comment by markpizz** [comment]
Devices which are enabled BEFORE you mess with setting any address or vector will already have had their addresses and vectors assigned by auto-configure.  Devices which are enabled after you do that will have to be manually assigned.

**Comment by markpizz** [comment]
This is documented in the doc/pdp11_doc.doc file.

**Comment by larsbrinkhoff** [comment]
Thanks, closing.
