### ISSUE TITLE
ALL: garbage output and segfault when querying settable mux parameters

### ISSUE THREAD

**Issue by al20878** [simh/simh#758]
Hi,

I just downloaded simh from git and built in on Linux.

I'm querying (purposely wrongly) dz settings and getting absurd output and also a segfault.

Please take a look:
```
$ uname -a
Linux coredev2 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

BIN$ ./pdp11

PDP-11 simulator V4.0-0 Current        git commit id: 0de9b628
sim> sh dz
DZ      address=17760100-17760137*, vector=300-334*, BR5, lines=16
        not attached, 8b
sim> sh dz lines
lines=16
sim> sh dz lines=8
lines=56                    <= ???
sim> sh dz conn
all disconnected
sim> sh dz conn=8
Segmentation fault (core dumped)  <= Oh wow!
```

P.S. "<=" are my comments

**Comment by al20878** [comment]
```
sim> sh dz log=7
line 0: 
Segmentation fault (core dumped)
```

I'm sure there're other too

**Comment by markpizz** [comment]
I see the problem(s) which really aren't unique to the DZ.  I'll adjust the title of this issue when I uncover the scope of the problem and I'm sure by then I'll have a fix.  Stay tuned here.

**Comment by al20878** [comment]
Seems fixed by the last commit noted on this issue.  Thanks!
