### ISSUE TITLE
Cygwin issues (very slow start and arrow keys)

### ISSUE THREAD

**Issue by al20878** [simh/simh#761]
Hi,

I just built the PDP11 simh from the current git checkout on Cygwin.  It takes up to 10 seconds to start.  I also noticing that when I run it in the regular Cygwin console (mintty; set to use the "xterm" mode -- which is the default), the "vertical" arrow keys (esp. the up key to recall the last command) do not work: they actually move the cursor around the window instead of scrolling the command history buffer in the command line.  The "horizontal" arrow keys also move the cursor around and do not seem to be doing the actual change of editing position in simh (e.g. you can move the cursor all the way past the end of the command, or all the way to the beginning of the prompt).

```
$ ./BIN/pdp11.exe
<---- very long pause here!
PDP-11 simulator V4.0-0 Current        git commit id: af58efe6
sim>
```

Thanks,
Tony

**Comment by markpizz** [comment]
Cygwin isn't supported.  Use Visual Studio on Windows.  http://download.microsoft.com/download/E/8/E/E8EEB394-7F42-4963-A2D8-29559B738298/VS2008ExpressWithSP1ENUX1504728.iso

Windows binaries are available at: https://github.com/simh/Win32-Development-Binaries

**Comment by al20878** [comment]
Well, I guess I have to live with that.. Slow start is not an issue, and command editing is a luxury (which is not available in the guest RSX11M anyways, so I'm just to back typing very carefully all around).
