### ISSUE TITLE
microvax2 crashes under MacOS 10.8.5 (Mountain Lion) enabling the graphics console

### ISSUE THREAD

**Issue by jguillaumes** [simh/simh#77]
Just tried the graphics console under mac (I haven't done it before) and get a crash when I enable the QVSS device:

sim> set qvss enable
QVSS Display Created.  ReleaseKey=Ctrl-Right-Shift
sim> 2013-09-23 09:57:21.740 microvax2[15584:1803] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error (1000) creating CGSWindow on line 259'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff93df4b06 __exceptionPreprocess + 198
        1   libobjc.A.dylib                     0x00007fff935a03f0 objc_exception_throw + 43
        2   CoreFoundation                      0x00007fff93df48dc +[NSException raise:format:] + 204
        3   AppKit                              0x00007fff94716b49 _NSCreateWindowWithOpaqueShape2 + 655
        4   AppKit                              0x00007fff94715340 -[NSWindow _commonAwake] + 2002
        5   AppKit                              0x00007fff946d3d82 -[NSWindow _commonInitFrame:styleMask:backing:defer:] + 1763
        6   AppKit                              0x00007fff946d2ecf -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1568
        7   AppKit                              0x00007fff946d289f -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
        8   libSDL-1.2.0.dylib                  0x000000010ee08127 -[SDL_QuartzWindow initWithContentRect:styleMask:backing:defer:] + 279
        9   libSDL-1.2.0.dylib                  0x000000010ee05671 QZ_SetVideoMode + 1409
        10  libSDL-1.2.0.dylib                  0x000000010edfba50 SDL_SetVideoMode + 1056
        11  microvax2                           0x000000010eccb4a2 vid_thread + 66
        12  libSDL-1.2.0.dylib                  0x000000010ede4aa5 SDL_RunThread + 53
        13  libSDL-1.2.0.dylib                  0x000000010ee1c9c9 RunThread + 9
        14  libsystem_c.dylib                   0x00007fff920fb772 _pthread_start + 327
        15  libsystem_c.dylib                   0x00007fff920e81a1 thread_start + 13
)
libc++abi.dylib: terminate called throwing an exception
Abort trap: 6                                                                                            

This is the show version output:

sim> show version
MicroVAX II (KA630) simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                64b data
                64b addresses
                Ethernet support
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                Asynchronous I/O support
        Host Platform:
                Compiler: clang 4.2 (clang-425.0.28)
                Simulator Compiled: Sep 23 2013 at 09:55:26
                Memory Access: Little Endian
                Memory Pointer Size: 64 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 1.2.15
                OS clock tick size: 2ms
                OS: Darwin MacJordi.local 12.5.0 Darwin Kernel Version 12.5.0: Mon Jul 29 16:33:49 PDT 2013; root:xnu-2050.48.11~1/RELEASE_X86_64 x86_64

        git commit id: 721a16f7                                                                

Just to clarify it, it also crashes using gcc instead of clang to build simh.

EDIT: Additional info. This is the crashed thread backtrace:

Thread 1 Crashed:
0   libsystem_kernel.dylib        	0x00007fff8b051212 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff920fcb24 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff92140f61 abort + 143
3   libc++abi.dylib               	0x00007fff9155f9eb abort_message + 257
4   libc++abi.dylib               	0x00007fff9155d39a default_terminate() + 28
5   libobjc.A.dylib               	0x00007fff935a0873 _objc_terminate() + 91
6   libc++abi.dylib               	0x00007fff9155d3c9 safe_handler_caller(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff9155d424 std::terminate() + 16
8   libc++abi.dylib               	0x00007fff9155e58b __cxa_throw + 111
9   libobjc.A.dylib               	0x00007fff935a050c objc_exception_throw + 327
10  com.apple.CoreFoundation      	0x00007fff93e88f49 -[NSException raise] + 9
11  com.apple.AppKit              	0x00007fff947151d0 -[NSWindow _commonAwake] + 1634
12  com.apple.AppKit              	0x00007fff946d3d82 -[NSWindow _commonInitFrame:styleMask:backing:defer:] + 1763
13  com.apple.AppKit              	0x00007fff946d2ecf -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1568
14  com.apple.AppKit              	0x00007fff946d289f -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
15  libSDL-1.2.0.dylib            	0x000000010ee08127 -[SDL_QuartzWindow initWithContentRect:styleMask:backing:defer:] + 279
16  libSDL-1.2.0.dylib            	0x000000010ee05671 QZ_SetVideoMode + 1409
17  libSDL-1.2.0.dylib            	0x000000010edfba50 SDL_SetVideoMode + 1056
18  microvax2                     	0x000000010eccb4a2 vid_thread + 66
19  libSDL-1.2.0.dylib            	0x000000010ede4aa5 SDL_RunThread + 53
20  libSDL-1.2.0.dylib            	0x000000010ee1c9c9 RunThread + 9
21  libsystem_c.dylib             	0x00007fff920fb772 _pthread_start + 327
22  libsystem_c.dylib             	0x00007fff920e81a1 thread_start + 13

**Comment by markpizz** [comment]
Well, the presumption that libSDL2 changed the OS X requirement for all event processing be performed on the main thread actually didn't change, even though it was presumed to be a goal of the new version.

I've come up with a way to run the event processing on the main thread and the simulator in a separate thread created by the main thread.  I think this is now in good shape.

Please let me know.

**Comment by markpizz** [comment]
Jordi,

The original complaint here is no longer relevant.  Many things have changed/improved.  Things may not yet be perfect, but there are other issues describing newer problems.  Please close this and focus on either another QVSS issue or create a new going forward.

Thanks.

Mark
