### ISSUE TITLE
vax_cpu.c:1454 - unexecutable code after IDX_IMM_TEST

### ISSUE THREAD

**Issue by bscottm** [simh/simh#770]
Sorry. `cppcheck` continues to find interesting code, this time at line 1450-1460 in `vax_cpu.c`:

```c
                case AIN:
                    index = index + R[rn];
                    if (rn == nPC) {
                        IDX_IMM_TEST;
                        SETPC (PC + DR_LNT (disp));
                        }
                    else {
                        R[rn] = R[rn] + DR_LNT (disp);
                        recq[recqptr++] = RQ_REC (AIN | (disp & DR_LNMASK), rn);
                        }
                    break;
```

`IDX_IMM_TEST` expands to `ABORT (ABORT_RESAD)`, which eventually calls `set_jmp()`. Consequently, `SETPC` doesn't get executed and `cppcheck` considers it dead code. Of course, it's probably never seen in practice -- delete it or manually expand out `IDX_IMM_TEST` to set PC correctly?

**Comment by archivisth** [comment]
IDX_IMM_TEST is a **model-dependent macro**. In some models, it is a NOP, and the SETPC is executed.

It wouldn't be there if it hadn't been needed for some VAX variants.

**Comment by bscottm** [comment]
@archivisth: Fair enough. Better to double check than continue to perpetrate questionable code unintentionally.
