### ISSUE TITLE
vax_fpa.c: vax_fdiv arguments

### ISSUE THREAD

**Issue by bscottm** [simh/simh#771]
This one is an easy fix for questionable style, correct?

```c
[build] vax_fpa.c:1038:21: warning: Function 'vax_fdiv' argument order different: declaration 'b, a, prec, bias' definition 'a, b, prec, bias' [funcArgOrderDifferent]
[build] void vax_fdiv (UFP *a, UFP *b, int32 prec, int32 bias)
[build]                     ^
[build] vax_fpa.c:651:21: note: Function 'vax_fdiv' argument order different: declaration 'b, a, prec, bias' definition 'a, b, prec, bias'
[build] void vax_fdiv (UFP *b, UFP *a, int32 prec, int32 bias);
[build]                     ^
[build] vax_fpa.c:1038:21: note: Function 'vax_fdiv' argument order different: declaration 'b, a, prec, bias' definition 'a, b, prec, bias'
[build] void vax_fdiv (UFP *a, UFP *b, int32 prec, int32 bias)
```

**Comment by markpizz** [comment]
Each place that the vax_fdiv() routine is called, the parameters match the implementation. 

Maybe, during the initial development, there was an actual different ordering of the parameters between the declaration and the implementation.  There might have been a problem there which was detected before the corrected code was added to the code base back in simh v2.9-11 in 2002 when the vax simulator was added to simh.

Changing this solves a "problem in the noise" that will have no consequence on any operational behavior on any host system.

So, the answer to your question is yes.  I'll change BOTH declarations.  There are two implementations of this functionality, one which counts on 64bit integers being available and the other done completely in 32bit for host environments that don't have 64bit integers available in the C compiler.

**Comment by archivisth** [comment]
It's a fair cop. Functionally harmless, but potentially misleading.

**Comment by bscottm** [comment]
Sure, it's a problem in the noise, perhaps, but it does impact IDEs, which show a potentially misleading declaration and end up with swapped arguments (probability of this is pretty low.)
