### ISSUE TITLE
undefined reference to `shm_open'

### ISSUE THREAD

**Issue by joeinwap** [simh/simh#780]
linux% make
/tmp/ccWdzk2R.o: In function `sim_shmem_open':
sim_fio.c:(.text+0x8b9): undefined reference to `shm_open'
sim_fio.c:(.text+0x99c): undefined reference to `shm_open'
collect2: error: ld returned 1 exit status
makefile:2135: recipe for target 'BIN/pdp1' failed
make: *** [BIN/pdp1] Error 1

Failed for "make pdp10" and then a plain "make".

**Comment by larsbrinkhoff** [comment]
Something about the librt library?  What does your compiler command line look like?  When I run make pdp10, I see this:

```
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning
-fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result
-DSIM_GIT_COMMIT_ID=+614318054bc0f9195c7ac8abe3298d68bfe5af44  -DSIM_COMPILER="GCC Version: 5.4.0"
-I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H
-DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so
-DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN 
PDP10/pdp10_fe.c PDP11/pdp11_dz.c PDP10/pdp10_cpu.c PDP10/pdp10_ksio.c PDP10/pdp10_lp20.c
PDP10/pdp10_mdfp.c PDP10/pdp10_pag.c PDP10/pdp10_rp.c PDP10/pdp10_sys.c 
PDP10/pdp10_tim.c PDP10/pdp10_tu.c PDP10/pdp10_xtnd.c PDP11/pdp11_pt.c PDP11/pdp11_ry.c 
PDP11/pdp11_cr.c PDP11/pdp11_dup.c PDP11/pdp11_dmc.c PDP11/pdp11_kmc.c PDP11/pdp11_xu.c 
PDP11/pdp11_ch.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c 
sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -DVM_PDP10 -DUSE_INT64 
-I PDP10 -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING 
-DUSE_SHARED -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu 
-DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -o BIN/pdp10 -lm 
-lrt -lpthread -lpcreposix -lpcre -ldl -lpng -lz
```

(Lines broken for readability.)

I see `-lrt` in there near the end.

**Comment by joeinwap** [comment]
I am running Ubuntu 18.04
Linux zathras 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019
x86_64 x86_64 x86_64 GNU/Linux

There is nothing between "-lm" and "-lpthread" on my "make pdp10".

**Comment by markpizz** [comment]
Hi Joe,

Please provide the precise output that is produced by entering the following 4 commands:
```
$ rm -rf simh
$ git clone https://github.com/simh/simh
$ cd simh
$ make pdp10
```

On my Ubuntu 18.04 the following is produced:
```

mark@Ubuntu-18:~$ git clone https://github.com/simh/simh
Cloning into 'simh'...
remote: Enumerating objects: 144, done.
remote: Counting objects: 100% (144/144), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 28047 (delta 69), reused 85 (delta 49), pack-reused 27903
Receiving objects: 100% (28047/28047), 47.23 MiB | 12.35 MiB/s, done.
Resolving deltas: 100% (21735/21735), done.
mark@Ubuntu-18:~$ cd simh
mark@Ubuntu-18:~/simh$ make pdp10
lib paths are: /lib/ /lib/x86_64-linux-gnu/ /lib32/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/ /usr/lib32/
include paths are:  /usr/lib/gcc/x86_64-linux-gnu/7/include /usr/local/include /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed /usr/include/x86_64-linux-gnu /usr/include
using libm: /usr/lib/x86_64-linux-gnu/libm.so
using librt: /usr/lib/x86_64-linux-gnu/librt.so
using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib/x86_64-linux-gnu/libpcreposix.so /usr/lib/x86_64-linux-gnu/libpcre.so /usr/include/pcreposix.h /usr/include/pcre.h
using semaphore: /usr/include/semaphore.h
using libdl: /usr/lib/x86_64-linux-gnu/libdl.so /usr/include/dlfcn.h
using mman: /usr/include/x86_64-linux-gnu/sys/mman.h
using libpcap: /usr/include/pcap.h
*** Info ***
*** Info *** pdp10 Simulator is being built with
*** Info *** minimal libpcap networking support
*** Info ***
*** Info ***
*** Info *** Simulators on your Linux platform can also be built with
*** Info *** extended LAN Ethernet networking support by using VDE Ethernet.
*** Info ***
*** Info *** To build simulator(s) with extended networking support you
*** Info *** should install the vde2 package to provide this
*** Info *** functionality for your Linux system:
*** Info ***        $ sudo apt-get install libvdeplug-dev
*** Info ***
***
*** pdp10 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 7.4.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
*** - Per simulator tests will be run.
***
*** git commit id is 26128800ee4dcaf6a4647bc755a331d710937238.
*** git commit time is 2019-12-13T06:58:47-0800.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -Wno-format-truncation -DSIM_GIT_COMMIT_ID=26128800ee4dcaf6a4647bc755a331d710937238 -DSIM_GIT_COMMIT_TIME=2019-12-13T06:58:47-0800  -DSIM_COMPILER="GCC Version: 7.4.0" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_GLOB -DHAVE_SHM_OPEN  PDP10/pdp10_fe.c PDP11/pdp11_dz.c PDP10/pdp10_cpu.c PDP10/pdp10_ksio.c PDP10/pdp10_lp20.c PDP10/pdp10_mdfp.c PDP10/pdp10_pag.c PDP10/pdp10_rp.c PDP10/pdp10_sys.c PDP10/pdp10_tim.c PDP10/pdp10_tu.c PDP10/pdp10_xtnd.c PDP11/pdp11_pt.c PDP11/pdp11_ry.c PDP11/pdp11_cr.c PDP11/pdp11_dup.c PDP11/pdp11_dmc.c PDP11/pdp11_kmc.c PDP11/pdp11_xu.c PDP11/pdp11_ch.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -DVM_PDP10 -DUSE_INT64 -I PDP10 -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -o BIN/pdp10 -lm -lrt -lpthread -lpcreposix -lpcre -ldl  
mark@Ubuntu-18:~/simh$ make pdp1
lib paths are: /lib/ /lib/x86_64-linux-gnu/ /lib32/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/ /usr/lib32/
include paths are:  /usr/lib/gcc/x86_64-linux-gnu/7/include /usr/local/include /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed /usr/include/x86_64-linux-gnu /usr/include
using libm: /usr/lib/x86_64-linux-gnu/libm.so
using librt: /usr/lib/x86_64-linux-gnu/librt.so
using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib/x86_64-linux-gnu/libpcreposix.so /usr/lib/x86_64-linux-gnu/libpcre.so /usr/include/pcreposix.h /usr/include/pcre.h
using semaphore: /usr/include/semaphore.h
using libdl: /usr/lib/x86_64-linux-gnu/libdl.so /usr/include/dlfcn.h
using mman: /usr/include/x86_64-linux-gnu/sys/mman.h
using libSDL2: /usr/include/SDL2/SDL.h
***
*** pdp1 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 7.4.0.
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
*** - Per simulator tests will be run.
***
*** git commit id is 26128800ee4dcaf6a4647bc755a331d710937238.
*** git commit time is 2019-12-13T06:58:47-0800.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -Wno-format-truncation -DSIM_GIT_COMMIT_ID=26128800ee4dcaf6a4647bc755a331d710937238 -DSIM_GIT_COMMIT_TIME=2019-12-13T06:58:47-0800  -DSIM_COMPILER="GCC Version: 7.4.0" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_GLOB -DHAVE_SHM_OPEN  PDP1/pdp1_lp.c PDP1/pdp1_cpu.c PDP1/pdp1_stddev.c PDP1/pdp1_sys.c PDP1/pdp1_dt.c PDP1/pdp1_drm.c PDP1/pdp1_clk.c PDP1/pdp1_dcs.c PDP1/pdp1_dpy.c display/display.c display/sim_ws.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -I PDP1 -DUSE_DISPLAY -DHAVE_LIBSDL -DUSE_SIM_VIDEO `/usr/bin/sdl2-config --cflags` `/usr/bin/sdl2-config --libs` -DDISPLAY_TYPE=DIS_TYPE30 -DPIX_SCALE=RES_HALF -o BIN/pdp1 -lm -lrt -lpthread -lpcreposix -lpcre -ldl  
mark@Ubuntu-18:~/simh$ 
```

I haven't run this system in quite a while, so I install all of the updates and the same results were obtained.

```
mark@Ubuntu-18:~/simh$ uname -a
Linux Ubuntu-18 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- Mark

**Comment by joeinwap** [comment]
mintty screen dump

Script started on 2019-12-14 15:56:00-0800

zathras> wget https://github.com/simh/simh/archive/master.zip
2019-12-14 15:58:54 (3.37 MB/s) - 'master.zip' saved [19423627]

zathras> rm -rf simh-master

zathras> unzip master.zip
Archive:  master.zip
26128800ee4dcaf6a4647bc755a331d710937238
...
zathras> cd simh-master
zathras> make pdp10
lib paths are: /lib/x86_64-linux-gnu/ /usr/lib/
/usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/
/usr/local/lib/
include paths are:  /usr/lib/gcc/x86_64-linux-gnu/7/include
/usr/local/include /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
/usr/include/x86_64-linux-gnu /usr/include
using libm: /usr/lib/x86_64-linux-gnu/libm.so

        [Note: does NOT say using librt here.]

using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h
using regex: /usr/include/regex.h
using semaphore: /usr/include/semaphore.h
using libpng: /usr/local/lib/libpng.so /usr/local/include/png.h
using zlib: /usr/local/lib/libz.so /usr/local/include/zlib.h
using mman: /usr/include/x86_64-linux-gnu/sys/mman.h
using libpcap: /usr/include/pcap.h
using libvdeplug: /usr/lib/libvdeplug.so /usr/include/libvdeplug.h
***
*** pdp10 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 7.4.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP NAT(SLiRP)
*** - Per simulator tests will be run.
***
*** git commit id is 26128800ee4dcaf6a4647bc755a331d710937238.
*** git commit time is 2019-12-13T06:58:47-08:00.
***

gcc -std=gnu99 -U__STRICT_ANSI__ -O2 -finline-functions
-fgcse-after-reload -fpredictive-commoning -fipa-cp-clone
-fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result
-Wno-format-truncation
-DSIM_GIT_COMMIT_ID=26128800ee4dcaf6a4647bc755a331d710937238
-DSIM_GIT_COMMIT_TIME=2019-12-13T06:58:47-08:00 -DSIM_COMPILER="GCC
Version: 7.4.0" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO
-DHAVE_REGEX_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM
-DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN
PDP10/pdp10_fe.c PDP11/pdp11_dz.c PDP10/pdp10_cpu.c PDP10/pdp10_ksio.c
PDP10/pdp10_lp20.c PDP10/pdp10_mdfp.c PDP10/pdp10_pag.c PDP10/pdp10_rp.c
PDP10/pdp10_sys.c PDP10/pdp10_tim.c PDP10/pdp10_tu.c PDP10/pdp10_xtnd.c
PDP11/pdp11_pt.c PDP11/pdp11_ry.c PDP11/pdp11_cr.c PDP11/pdp11_dup.c
PDP11/pdp11_dmc.c PDP11/pdp11_kmc.c PDP11/pdp11_xu.c PDP11/pdp11_ch.c
scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c
sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c
sim_card.c -DVM_PDP10 -DUSE_INT64 -I PDP10 -I PDP11 -DHAVE_PCAP_NETWORK
-I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_VDE_NETWORK
-DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu
-DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -o
BIN/pdp10 -lm -lpthread -lpng -lz -lvdeplug -Wl,-R,/usr/lib/ -L/usr/lib/

        [Note: does not say -lrt here.]

/tmp/ccBMdJEQ.o: In function `sim_shmem_open':
sim_fio.c:(.text+0x8b9): undefined reference to `shm_open'
sim_fio.c:(.text+0x99c): undefined reference to `shm_open'
collect2: error: ld returned 1 exit status
makefile:2189: recipe for target 'BIN/pdp10' failed
make: *** [BIN/pdp10] Error 1

zathras> ls -lg /usr/lib/x86_64-linux-gnu/librt*
-rw-r--r-- 1 root  77358 Apr 16  2018 /usr/lib/x86_64-linux-gnu/librt.a
-rw-r--r-- 1 root 113584 Apr 27  2016 /usr/lib/x86_64-linux-gnu/librtmp.so.1

Script done on 2019-12-14 16:05:15-0800

**Comment by markpizz** [comment]
Hi Joe,

Please try:
```
$ sudo apt install libc6
```
if that is already installed, then try:
```
$ sudo apt install libc6-dev
```
and let me know which of these got you going.

Thanks.

- Mark

**Comment by markpizz** [comment]
> using libm: /usr/lib/x86_64-linux-gnu/libm.so
> 
>         [Note: does NOT say using librt here.]
> 
> using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h

It certainly doesn't and that is why your build is failing.

The earlier problem comes from the fact that the library search list is different:
yours is:
```
lib paths are: /lib/x86_64-linux-gnu/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/ /usr/local/lib/
```
mine is:
```
lib paths are: /lib/ /lib/x86_64-linux-gnu/ /lib32/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/ /usr/lib32/
```
On Linux most of this is derived from the output produced by:
```
$ ldconfig -p
```
which seems to be odd on your system since it happens to have an include file (in the include search path) of mmap.h.  An include is found which creates the reference to shm_open, while the dependent library for this default include isn't in the default library path.

**Comment by joeinwap** [comment]
On Sat, Dec 14, 2019 at 5:07 PM Mark Pizzolato <notifications@github.com>
wrote:

> using libm: /usr/lib/x86_64-linux-gnu/libm.so
>
>     [Note: does NOT say using librt here.]
>
> using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so
> /usr/include/pthread.h
>
> It certainly doesn't and that is why your build is failing.
>
Side comment: On a dual-boot system on a GPT disk, running Windows-10 just
once will wipe out the pointer to the grub menu.  I spent this afternoon
reinstalling Ubuntu.  After that the missing librt.so.1 was in place.  No
build problems now.

   -Joe

**Comment by markpizz** [comment]
It's not clear how you ended up with your original system configuration, but if that arises again the makefile will now do the right thing and not allow a reference to shm_open.  This will mean that the UC15 simulator won't work since it requires the shm_ APIs.  Most folks either won't have this problem or won't be bothered by this limitation.  I'm closing this issue now.  Open another if you have other problems.
