### ISSUE TITLE
swtp6800 using incorrect address to data table SOFTWARE INTERRUPT vector

### ISSUE THREAD

**Issue by cyourth-cognonic** [simh/simh#820]
- #### Context
Running SWTP 6800 simulation and testing the SWTBug Monitor with SWI based code.   The simulation is exiting back to SIMH command line with the following error:

        $ M A048            # set RTI address for G command
        $ A048 A4  01
        $ A049 A4  00
        $ A04A A4  1Q
        ...
        $ M 0100
        $ 0100 A0 8E        # LDS #$1000         
        $ 0101 A0 10        
        $ 0102 A0 00        
        $ 0103 A0 CE        # LDX #1234       
        $ 0104 A0 12
        $ 0105 A0 34
        $ 0106 A0 86        # LDAA #$00 
        $ 0107 A0 00
        $ 0108 A0 C6        # LDAB #$FF 
        $ 0109 A0 FF
        $ 010A A0 3F        # SWI
        $ 010B A0 1Q
        $ G
        ...
        PC=A00C SP=0FF9 IX=1234 A=5C B=FF CCR=F0
        Invalid Opcode, PC: A00C

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

        sim> show version
        
            SWTP 6800, V2, MP-A2 CPU Board simulator V4.0-0 Current
            Simulator Framework Capabilities:
                32b data
                32b addresses
                no Ethernet
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support (Lock free asynchronous event queue)
                Asynchronous Clock support
                FrontPanel API Version 12
            Host Platform:
                Compiler: GCC 7.5.0
                Simulator Compiled as C arch: x64 (Release Build) on Mar 20 2020 at 23:34:17
                Build Tool: simh-makefile
                Memory Access: Little Endian
                Memory Pointer Size: 64 bits
                Large File (>2GB) support
                SDL Video support: No Video Support
                PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 1ms
                Time taken by msleep(1): 1ms
                OS: Linux osboxes 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
                git commit id: 45d7a115
                git commit time: 2020-03-18T14:13:55+01:00

- #### how you built the simulator or that you're using prebuilt binaries

        make swtp6800mp-a
        make swtp6800mp-a2

- #### the simulator configuration file (or commands) which were used when the problem occurred.

        ./swtp6800mp-a2 swtp6800mp-a2.ini

        file: swtp6800mp-a2.ini
            # cpu
            set cpu hex
            set cpu itrap
            set cpu mtrap
        
            # ROM : E000h to E3FFh
            set bootrom 2708
            attach bootrom swtbug.bin
        
            # onboard cpu
            set mp-a2 noram, mon
        
            # RAM:
            set mp-b2 bd0, bd1, bd2, bd3, bd4, bd5
        
            # 2716 EPROMs:
            set mp-a2 nolo_prom, nohi_prom
        
            # MP-S Serial
            set mp-s ansi
            attach ptp ptp-a2.txt
        
            # reset and go
            reset
            g
        
- #### the expected behavior and the actual behavior

        expected behavior:
            $ G
            $ F9 FF 00 1234 0111 0FF9

        actual behavior:
            $ G
            PC=A00C SP=0FF9 IX=1234 A=5C B=FF CCR=F0
            Invalid Opcode, PC: A00C
            sim>

- #### changes to make it work

        ./swtp6800/common/m6800.c

            case 0x3F:                  /* SWI */
                push_word(PC);
                push_word(IX);
                push_byte(A);
                push_byte(B);
                push_byte(CCR);
                SET_FLAG(IF);
                /*
                 * Notes:
                 *    - bug: using wrong entry for SWI vector handler, should be 0xFFFA
                 *    - remake binary:
                 *           make swtp6800mp-a
                 *           make swtp6800mp-a2
                 */
                /* PC = CPU_BD_get_mword(0xFFFB) & ADDRMASK; */
                PC = CPU_BD_get_mword(0xFFFA) & ADDRMASK;
                break;

**Comment by markpizz** [comment]
Hi Clinton,

The issue template you were filling out asked to provide: "sim> SHOW VERSION" while running the simulator which is having the issue"

I was trying to suggest that ALL of the output that was produced, not merely suggesting that you pick a little of it.  Please suggest language that I can use in the template that would have inspired you to provide all of it, and I'll update the template.

As soon as you provide the requested output, I'll engage the author to fix the problem you found.

Thanks.

- Mark

**Comment by cyourth-cognonic** [comment]
updated show version details...

**Comment by markpizz** [comment]
You're running a version from last November.  Please pick up the latest source from https://github.com/simh/simh and confirm that this has not yet been fixed.

Thanks.

**Comment by cyourth-cognonic** [comment]
I'm using the 4.0.x release, not 3.11.x - this has not been fixed for any release....

**Comment by markpizz** [comment]
Since anyone can grab the latest code at any time, the current code base does not have a formal release process. The swtp6800 simulators are no longer part of Bob Supnik's 3.11 release but they're maintained here.   The issue reporting system specifically asks for the full output of SHOW VERSION so that we can precisely determine what you may be working with.

I don't know how/where you got what you're working with now, but the latest can always be picked up with either from:
```
$ git clone https://github.com/simh/simh
$ cd simh
$ make {simulator-name(s)}
$# simulators are in the BIN subdirectory
```
OR

download:
```
$ wget https://github.com/simh/simh/archive/master.zip
$ wget https://github.com/simh/simh/archive/master.tar.gz
```
Then build with:
```
$ unzip master.zip
$ cd simh_master
$ make {simulator-name(s)}
```

For the above to work and the build to complete, you'll need: git (maybe), wget(maybe), unzip, gcc (or clang), and make.

**Comment by cyourth-cognonic** [comment]
Testing latest version - still same issue - incorrect address for SWI vector...
