### ISSUE TITLE
PDP-1 paper tape reader ASCII mode hangs on reading

### ISSUE THREAD

**Issue by khaledh** [simh/simh#821]
#### Context
I'm trying to use the PDP-1 simulator's paper tape reader in ASCII mode to read a simple MACRO assembly file I created myself. The simulator hangs at the step where MACRO tries to do pass-1 (i.e. read the symbolic tape). If I create an equivalent tape in FIODEC manually (using an octal editor), MACRO can read it and assemble it without issues.

I narrowed this down to a potential issue in the ptr device's `ptr_get_ascii` function, where it seems like it's not signalling EOF to the caller properly upon end of file; it just sets up a trailer loop.

https://github.com/simh/simh/blob/89cd649c77bf83d059d4f075d6a330f9a399e701/PDP1/pdp1_stddev.c#L409-L412

#### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

```
PDP-1 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Mar 10 2020 at 00:41:54
        Build Tool: simh-Visual-Studio-Project
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.10, PNG Version 1.6.37, zlib: 1.2.11
        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 10.0.18363.719]
        Architecture: x86 on AMD64, Processors: 4
        Processor Id: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel, Level: 6, Revision: 3c03
        git commit id: c30c88c2
        git commit time: 2020-03-10T00:18:19-07:00
```

#### how you built the simulator or that you're using prebuilt binaries
Prebuilt binaries.

#### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

```
λ pdp1

PDP-1 simulator V4.0-0 Current        git commit id: c30c88c2
sim> att ptr C:\Historical\bitsavers.org\DEC\pdp1\papertapeImages\20040106\russell2\macro_sa0.bin
sim> boot ptr

HALT instruction, PC: 001422 (CLA CMA)
sim> att -a ptr c:\sim\simple.asc
sim> c
```
The simulator hangs at this point. The expected output should be:

```
sim> c
100/ - pass 1

HALT instruction, PC: 001375 (LAW 1)
```

PTR and CPU state below.

<details>

```
sim> c

^E
Simulation stopped, PC: 003210 (RPA I)
sim> ex ptr state
BUF:    000000
UC:     0
DONE:   0
RPLS:   1
POS:    20
TIME:   100
STOP_IOE:       0

sim> ex cpu state
PC:     003210
AC:     000000
IO:     000000
MA:     003210
MB:     730001
OV:     1
PF:     002
SS:     00
TA:     000000
TW:     000000
EXTM:   0
RNGM:   0
L:      0
RM:     0
RMASK:  000000
RTB:    000000
RNAME[0]:       0
RNAME[1]-RNAME[3]: same as above
SBON:   0
SBRQ:   0
SBIP:   0
SBSREQ: 000000
SBSENB: 000000
SBSACT: 000000
IOSTA:  100000
CPLS:   40
IOH:    1
IOS:    0
PCQ[0]: 003222
PCQ[1]-PCQ[13]: same as above
PCQ[14]:        003165
PCQ[15]:        001517
PCQ[16]:        003176
PCQ[17]:        003200
PCQ[18]:        003163
PCQ[19]:        003265
PCQ[20]:        003241
PCQ[21]:        003222
PCQ[22]-PCQ[40]: same as above
PCQ[41]:        003165
PCQ[42]:        001517
PCQ[43]:        003176
PCQ[44]:        003200
PCQ[45]:        003163
PCQ[46]:        003265
PCQ[47]:        003241
PCQ[48]:        003222
PCQ[49]-PCQ[63]: same as above
STOP_INST:      0
SBS_INIT:       0
EXTM_INIT:      0
XCT_MAX:        16
IND_MAX:        16
WRU:    005
```
</details>

#### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

PDP-1 MACRO: http://bitsavers.org/bits/DEC/pdp1/papertapeImages/20040106/russell2/macro_sa0.bin

`simple.asc` (input file)
```
100/
	hlt
start 100
```

**Comment by archivisth** [comment]
Please post a link to the FIODEC equivalent, so I can see what is going on with "correct" behavior. Simply having the ASCII read routine return EOF when detected does not solve the problem. Something else is going on.

**Comment by khaledh** [comment]
@archivisth Thanks for the quick response. Here's the FIODEC equivalent: [simple.zip](https://github.com/simh/simh/files/4363174/simple.zip)

**Comment by khaledh** [comment]
My understanding is that the main `ptr_svc` routine expects to get an EOF at some point:

https://github.com/simh/simh/blob/89cd649c77bf83d059d4f075d6a330f9a399e701/PDP1/pdp1_stddev.c#L354-L358

This happens when the ptr is in FIODEC mode (the `temp` variable will be assigned to EOF at the end), but it's not clear to me in ASCII mode how the `temp` variable will be assigned to EOF by calling `ptr_get_ascii` (no where in that subroutine EOF is returned).

**Comment by archivisth** [comment]
Okay... the answer is that simple.asc is "malformed" - that is, it's only got <CR> between lines, rather than <CR><LF> (Windows line format) or <LF> (Linux/modern MacOS format). Retyping the file on Notepad to create "simple1.asc" yields the expected behavior.

This is due to:

`        if (c == '\n')                                  /* NL -> CR */
            c = '\r';
        else if (c == '\r')                             /* ignore CR */
            continue;
`
This handles Windows (discards CR in CR-LF) and Linux (LF only) but won't handle a bare CR.

The external utility ASC was created to handle end-of-line conversions in the ancient days when Macs used bare CRs in text files.

**Comment by archivisth** [comment]
In fact, macro does not expect to see a PTR out-of-tape indication. With simple.oct, the error processing code is never reached.

In a FIODEC tape, macro expects the last non-zero character to be FIODEC_STOP (013). In ASCII mode, the code synthesizes a FIODEC_STOP code when end-of-file is reached. (You could also put a form-feed at the end of the file instead.) The code should be made more robust by adding logic to return EOF if FIODEC_STOP has already been returned once. That would handle true out-of-tape cases correctly.

**Comment by khaledh** [comment]
> Okay... the answer is that simple.asc is "malformed" - that is, it's only got between lines, rather than (Windows line format) or (Linux/modern MacOS format). Retyping the file on Notepad to create "simple1.asc" yields the expected behavior.

I see. I'm not sure how ended up with CR only in newlines. Anyway, I tried creating the file in Notepad (and verified it contains CR+LF) but it still hangs. Here's the new file: [simple2.zip](https://github.com/simh/simh/files/4363381/simple2.zip). Would you be able to share your ASCII file that worked so I can try it?

**Comment by archivisth** [comment]
Your simple2.asc works for me:

PDP-1 simulator V3.11-1
sim> att -e ptr c:\temp\macro_sa0.bin
sim> boot ptr

HALT instruction, PC: 001422 (CLA CMA)
sim> att -e -a ptr c:\temp\simple2.asc
sim> ex ptr 0-23
0:      061
1:      060
2:      060
3:      057
4:      015
5:      012
6:      011
7:      150
8:      154
9:      164
10:     015
11:     012
12:     163
13:     164
14:     141
15:     162
16:     164
17:     040
18:     061
19:     060
20:     060
21:     015
22:     012
End of file
sim> c
100/ - pass 1

HALT instruction, PC: 001375 (LAW 1)
sim>

That's what you posted as expected behavior.

Mark, please verify V4 behavior.

**Comment by khaledh** [comment]
Indeed, this works with V3.11-0, but not with V4.

```
$ bin/pdp1

PDP-1 simulator V3.11-0
sim> show version
PDP-1 simulator V3.11-0 [32b data, 32b addresses, no Ethernet]
sim> att ptr ../macro_sa0.bin
sim> boot ptr

HALT instruction, PC: 001422 (CLA CMA)
sim> att -e -a ptr ../simple.asc
sim> c
100/ - pass 1

HALT instruction, PC: 001375 (LAW 1)
sim>
```

**Comment by markpizz** [comment]
> Mark, please verify V4 behavior.

This problem is strange and subtle and it has nothing to do with where we were looking.

The problem is a consequence of this discussion of just over a year ago where @archivisth wrote in eMail:
```
Actually, it's the other way around.

ATTACH is supposed to be the equivalent of mounting new media on an empty 
device - putting a pack into a disk pack; mounting a tape on a mag tape drive; 
putting a new card deck into a card reader; putting a new box of paper into a 
line printer that has run out.

Every file is opened for writing (unless -r is specified), because even read-only 
devices can be examined - and modified - through the console package. So the 
write attribute is inadequate to distinguish an output-only device from any other. 
It's possible that the !ROABLE attribute provides the necessary differentiation, 
but in fact...

Here's a simple thought experiment to show that the !ROABLE attribute is also 
not sufficient - the IBM 1442 card reader/punch. (I've been looking at the 1440 
recently.) It behaves like a card reader, EXCEPT that cards that are read pass 
through the punch station and can be modified "in situ". (A terrible idea, but I 
didn't design the damned thing.) So it cannot be marked ROABLE, yet when 
opened, it must set pos = 0 for correct functioning, just like all other (read-only) 
card readers.

A safer way is a switch (-a or -p perhaps, for append) that overrides the default 
behavior for files attached to sequential, non-ROABLE devices. That maintains 
behavioral and script compatibility.

On 3/10/2019 12:20 PM, Mark Pizzolato wrote:
>
> Bob,
>
> We’ve got a user who raises what seems like a reasonable question:
>
> Since a real line printer spits out pages, it generally isn’t possible 
> to write over pages previously emitted but not yet torn off the back 
> of the printer.  As such, it would seem that such a device should 
> default to opening with the position at the end of an existing file 
> (if a pre-existing file is attached).  If a determined user wanted to, 
> they could adjust POS to 0 (or anything else) and overwrite previously 
> printed pages which would be somewhat akin to feeding previously 
> printed pages back into the printer.
>
> How about changing attach_unit() to set uptr->pos to the end of file 
> for units with UNIT_SEQ that are opened for write?
>
> Thoughts?
>
> -Mark
>
```

As a consequence of this discussion, the -A switch causes a file opened for read/write (i.e. NOT -R) to be positioned at the current EOF.

The fix in this specific case is easy enough:
change ptr_attach() to:
```
sim_switches |= SWMASK ('R');
```
before calling attach_unit().

This issue illuminates the general issue where -A has been used by other devices.

The list of cases which currently use -A for something and ultimately call attach_unit() is:
```
pdp8_dt
pdp8_td
pdp18b_stddev PTR, PTP
pdp18b_dt
pdp11_tc
pdp11_cr
pdp6_dtc
kx10_dt
pdp1_stddev PTR, PTP
pdp1_dt
lgp_stddev TAP
ibm1130_cr
h316_stddev PTR, PTP
```
Most cases will either involve adding -R as above.  I'll look through all of these more closely later.

**Comment by khaledh** [comment]
@markpizz Thanks for the thorough explanation. Indeed, when I add the `-r` switch to the attach command to open the file read-only, it works.

The following is a complete assembly session using an ASCII input file:

```
λ simh-4.0--2020-03-10\pdp1

PDP-1 simulator V4.0-0 Current        git commit id: c30c88c2
sim> att -e ptr macro_sa0.bin
sim> boot ptr

HALT instruction, PC: 001422 (CLA CMA)
sim> att -e -r -a ptr simple.asc
PTR: unit is read only
sim> c
simple - pass 1

HALT instruction, PC: 001375 (LAW 1)
sim> de ptr pos 0
sim> att -n ptp simple.rim
PTP: creating new file: simple.rim
sim> c
ipe - pass 2

HALT instruction, PC: 001353 (LAC 4046)
sim> c

HALT instruction, PC: 001371 (JMP 1422)
sim> exit
Goodbye
```

**Comment by markpizz** [comment]
@khaledh Please confirm that the latest code works for you.

Normally, I'd generate a new set of Windows binaries, but there are a lot of simh activity now with various folks in Covid-19 lock down, so I'd prefer to wait until things settle down a bit.

**Comment by khaledh** [comment]
@markpizz Looks good 👍 

```
$ bin/pdp1

PDP-1 simulator V4.0-0 Current        git commit id: 614ad520
sim> att ptr tmp/macro_sa0.bin
PTR: unit is read only
sim> boot ptr

HALT instruction, PC: 001422 (CLA CMA)
sim> att -e -a ptr tmp/simple.asc
PTR: unit is read only
sim> c
100/ - pass 1

HALT instruction, PC: 001375 (LAW 1)
sim> de ptr pos 0
sim> att -n ptp tmp/simple.rim
PTP: creating new file: tmp/simple.rim
sim> c
0/ - pass 2

HALT instruction, PC: 001353 (LAC 4046)
sim> c

HALT instruction, PC: 001371 (JMP 1422)
sim> exit
Goodbye
```

> Normally, I'd generate a new set of Windows binaries, but there are a lot of simh activity now with various folks in Covid-19 lock down, so I'd prefer to wait until things settle down a bit.

I fully understand, and I appreciate you taking the time to get this fixed.

Thank you.
