### ISSUE TITLE
Tap network doesn't work at macOS with tuntaposx

### ISSUE THREAD

**Issue by kogule** [simh/simh#823]
- #### Context

Attaching a tap device to a simulator's device (```attach xub tap:tap0``` at vax780 for example) induces SIGABRT at macOS with tuntaposx. This causes by ```strcpy(3)``` at line 2073 of ```sim_ether.c```. On my building system, ```strcpy``` is replaced with ```__strcpy_chk``` and it throws SIGABRT because ```devname``` overlaps with ```savname```. The difference between ```savname``` and ```devname``` is 4 while the length of ```devname``` is at least 5 (```tapN\0```). The standard actually says that the behavior of applying ```strcpy``` to overlapped strings is undefined. Using ```memmove(3)``` removes this problem.

Attaching a tap device doesn't work yet with the modification above. ```write(2)``` at line 2830 of ```_eth_write``` called from ```eth_check_address_conflict_ex``` gets EIO. This is because the network interface is down state. tuntaposx requires making a tap interface up before reading/writing the corresponding tap device. I noticed that there is a block (lines 2076-2094 of ```sim_ether.c```) to try to make a network interface up. This block is really weird. When ```tun``` has a negative value, it's always closed at line 2069. Thus attempting making an interface up always fails. Isn't it ```if (tun >= 0) {```?

The patch below makes my simulators work fine.

```diff
--- sim_ether.c.orig    2020-03-12 04:10:54.000000000 +0000
+++ sim_ether.c
@@ -2070,10 +2071,10 @@ if (0 == strncmp("tap:", savname, 4)) {
         }
       else {
         *fd_handle = (SOCKET)tun;
-        strcpy(savname, devname);
+        memmove(savname, devname, strlen(devname) + 1);
         }
 #if defined (__APPLE__)
-      if (tun < 0) {    /* Not good yet? */
+      if (tun >= 0) {
         struct ifreq ifr;
         int s;
```

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

```
sim> show version
VAX 11/780 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC Clang 9.0.1
        Simulator Compiled as C arch: x64 (Debug Build) on Mar 22 2020 at 16:32:32
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.44 2020-02-12) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Time taken by msleep(1): 1ms
        git commit id: b848cb12
        git commit time: 2020-03-12T00:10:54-04:00
        Build: Unsupported=include+lib
```

**Comment by markpizz** [comment]
Thanks for the report and the fix.
