### ISSUE TITLE
ALTAIRZ80: Execution Logging (new feature)

### ISSUE THREAD

**Issue by deltecent** [simh/simh#838]
- #### Context
The AltairZ80 simulator allows the logging of IN and OUT instructions using the `SET CPU DEBUG=LOG_IN` and `SET CPU DEBUG=LOG_OUT` commands.

I wanted a way to be able to log the execution of instructions between two addresses. What I have running now is `SET CPU DEBUG=LOG_EXEC` to enable the logging of each executed instruction and `SET CPU LOGEXEC=start/end` to set the start and ending addresses that will be logged (default=0000/FFFF).

The logged output is the same at the ``DDT``:

```
Debug output to "test.log"
Debug output to "test.log" at Mon Apr 27 13:32:34 2020
Altair 8800 (Z80) simulator V4.0-0 Current        git commit id: 580b3889
256 bytes [1 page] loaded at ff00.
CPU: C0Z0M0E0I0 A=7B B=0002 D=2CE9 H=FFFC S=0000 P=FF0C DCR C
CPU: C0Z0M0E0I0 A=7B B=0002 D=2CE9 H=FFFC S=0000 P=FF0D JNZ 0FF08h
CPU: C0Z0M0E0I0 A=BD B=0002 D=2CE9 H=FFFC S=0000 P=FF08 MOV A,M
CPU: C0Z0M0E0I0 A=BD B=0002 D=2CE9 H=FFFC S=0000 P=FF09 STAX D
CPU: C0Z0M0E0I0 A=BD B=0002 D=2CE9 H=FFFD S=0000 P=FF0A INX H
CPU: C0Z0M0E0I0 A=BD B=0002 D=2CEA H=FFFD S=0000 P=FF0B INX D
CPU: C0Z0M0E0I0 A=BD B=0001 D=2CEA H=FFFD S=0000 P=FF0C DCR C
CPU: C0Z0M0E0I0 A=BD B=0001 D=2CEA H=FFFD S=0000 P=FF0D JNZ 0FF08h
CPU: C0Z0M0E0I0 A=C9 B=0001 D=2CEA H=FFFD S=0000 P=FF08 MOV A,M
CPU: C0Z0M0E0I0 A=C9 B=0001 D=2CEA H=FFFD S=0000 P=FF09 STAX D
CPU: C0Z0M0E0I0 A=C9 B=0001 D=2CEA H=FFFE S=0000 P=FF0A INX H
CPU: C0Z0M0E0I0 A=C9 B=0001 D=2CEB H=FFFE S=0000 P=FF0B INX D
CPU: C0Z1M0E1I0 A=C9 B=0000 D=2CEB H=FFFE S=0000 P=FF0C DCR C
CPU: C0Z1M0E1I0 A=C9 B=0000 D=2CEB H=FFFE S=0000 P=FF0D JNZ 0FF08h
CPU: C0Z1M0E1I0 A=C9 B=0000 D=2CEB H=FFFE S=0000 P=FF10 JMP 2C00h

Simulation stopped, PC: 02C1C (XRA A)
sim> q
Goodbye

```

While I feel this is a useful feature, I wasn't sure about the best way to implement it. If anyone knows a better way to do this, or thinks it shouldn't be added, I would appreciate your feedback before pushing a PR.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
Altair 8800 (Z80) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)
        Simulator Compiled as C arch: x64 (Release Build) on Apr 27 2020 at 13:31:19
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin Patricks-iMac-2.deltec.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
        git commit id: 580b3889
        git commit time: 2020-04-22T08:55:36-0700
```
- #### the simulator configuration file (or commands) which demonstrates the new feature.
```
SET CPU 8080
SET CPU MMU
SET CPU 64K
SET DEBUG test.log
SET CPU DEBUG=LOG_EXEC
SET CPU LOGEXEC=FF00/FFFF
LOAD dbl.bin FF00
GO FF00
```

**Comment by markpizz** [comment]
Many other simulators have a HISTORY facility that records instructions, operands and results for each instruction that is executed in a circular buffer of a somewhat arbitrary size.  Avoiding writing every instruction executed to disk (and thus running at the potentially extremely slow rate) is a goal along with avoiding filling up disk space with logged execution data.  This combined with breakpoints is often very valuable since you can then SHOW HISTORY=n when at the sim> prompt to review how and/or why you got some place.

The AltairZ80 historical debug logging of IN and OUT instruction execution is somewhat similar to and reasonably aligned with DEVICE level debugging.

**Comment by deltecent** [comment]
A history seems like a much better way to do it. Thank you.

**Comment by psco** [comment]
Actually the AltairZ80 maintains a circular pseudo register of the last 64 jump targets of the program counter. It can be viewed via "e pcq[0-63]".

**Comment by markpizz** [comment]
Is the pcq an architectural feature of the CPU being simulated, or is it a simulator debugging aide?

**Comment by psco** [comment]
It is a simulator debugging aide, not an architectural feature of any of the CPUs simulated.

**Comment by deltecent** [comment]
Added in PR #842
