### ISSUE TITLE
TMXR: Telnet with custom banner message?

### ISSUE THREAD

**Issue by larsbrinkhoff** [simh/simh#843]
**PROBLEM DESCRIPTION**

Imlac minicomputers (graphical workstations) were typically attached to a host computer, and accepted software downloaded over the serial port.  The protocol uses the 16 ASCII characters @-O and ignores everything else.  When the host port is a TXMR connection, a message like ``Connected to the FOO simulator BAR device, line BAZ`` is sent.  This interferes with software download because upper case characters are interpreted by the Imlac as software being sent from the host.

As a workaround, I have set one TMXR line to NOTELNET mode. 

**SUGGESTED SOLUTION**

I wonder if it would be possible to set the message to a custom user specified string?  Then the user could decide to have it empty, use all lower case, or whatever fits the situation.

CC @jdersch

**Comment by markpizz** [comment]
Some how I don't recall seeing this issue.  In any case, I'm not sure I understand the issue.

If the IMLAC simulator has a simulated serial interface using TMXR, then with a default setup, when a connection arrives on this simulated serial interface, the arriving connection will see the ``Connected to the FOO simulator BAR device, line BAZ``.  That is output generated by the simh framework and is not delivered to the simulator the connection arrives from.  Hence this is not the problem you've described.  Please elaborate if I'm reading this wrong.

Beyond that, lets say, for some strange reason, you've got two independent simulators (IMLAC and some other system which was the ``host computer`` that this graphical workstation may have hostorically been connected to) running concurrently.  You've got simulated serial ports on these two simulators connected by a ``virtual null modem cable`` which is specified in the configuration of each simulator with ``attach`` statements pointing at each other.  In such a situation, there is no value for either system for the wire protocol on that ``virtual null modem cable`` to speak the telnet protocol, since it presumes that a real terminal session will be part of the picture.  So, each side's attach statement would specify NOTELNET as part of the LINE=n setup.  If NOTELNET is specified, then when a connection is established the message you're concerned about (``Connected to the FOO simulator BAR device, line BAZ``) will not be issued.

Does this cover it?  Is that what you meant by RAW mode?

**Comment by larsbrinkhoff** [comment]
> As a workaround, I have set one TMXR line to RAW mode.

Sorry, I should have written NOTELNET.

> If the IMLAC simulator has a simulated serial interface using TMXR

I wrote this issue @livingcomputermuseum's [sImlac emulator](https://github.com/livingcomputermuseum/sImlac) in mind.  It's written in C#, so it doesn't have TMXR.  It's the host side with SIMH and TMXR that is the problem.

> the arriving connection will see the `Connected to the FOO simulator BAR device, line BAZ`. 

Yes, and all those lower case characters are causing a problem.  They are sent from the SIMH host to the Imlac side.  The Imlac bootstrap ROM will interpret all characters in the range A-O as data to put in memory and later execute.

> Beyond that, lets say, for some strange reason, you've got two independent simulators (IMLAC and some other system which was the host computer

That is exactly the case.  In my situation the host computer is SIMH simulating a PDP-10.

> In such a situation, there is no value for either system for the wire protocol on that virtual null modem cable to speak the telnet protocol

The situation is more complex.  The PDP-10 host will typically have one (or more) terminal multiplex devices with many ports.  Some of those ports may be dedicated to some particular terminals, Imlac among those.  Other ports may be a free pool, and for those it's beneficial to have the "Connected to FOO" message to give the user some feedback.

In this situation, I would like incoming connections to be able to share the free pool between actual telnet connections and terminal emulators such as Imlacs.

**Comment by markpizz** [comment]
How does this relate to the imlac implementation you are currently working on?

Assuming that it is unrelated, then I'll make the following recommendation:

On the simh PDP-10, configure the specific TMXR ports/lines that will have connections from IMLAC 'terminal emulators' with different TCP listen ports and specify those lines with NOTELNET.

```
sim> ATTACH mux poolport,LINE=X,lineXport;NOTELNET,LINE=Y,lineYport;NOTELNET
```

Apart from this, the C# Imlac terminal emulator you're referring to is clearly speaking over a TCP connection to the PDP-10 simulator and it is quite likely that the traffic contained in that TCP session doesn't really want TELNET option details mangling the traffic on the wire anyway.  Therefore the NOTELNET is the correct selection anyway which then silences the message you have complained about, right?

**Comment by larsbrinkhoff** [comment]
My Imlac implementation will behave the same in this regard.

Ideally, I don't want a separate NOTELNET port.  If I could configure the message to use all lower case, the problem would be solved.  Telnet users would see the helpful message, and Imlac users wouldn't have any trouble, and they could all use the same port.

The C# emulator has both "NOTELNET" and telnet options.

**Comment by deltecent** [comment]
Maybe the thing to do is make the `-V` switch work the same for telnet as it does for the serial ports, or for backwards compatibility, create another switch that disables reporting the connection. Example, `-Q`:
```
sim> ATTACH -Q mux poolport,LINE=X,lineXport
```

**Comment by larsbrinkhoff** [comment]
Disabling the report is not my preferred solution.  I can do that already with NOTELNET.

**Comment by deltecent** [comment]
> Disabling the report is not my preferred solution. I can do that already with NOTELNET.

I misunderstood. The title of this issue is "Telnet without banner message?" and a previous comment was "Ideally, I don't want a separate NOTELNET port."

So what you're wanting is a custom report that can also be set to "" or possibly a flag like "-L" that forces the message to all lowercase?

**Comment by larsbrinkhoff** [comment]
You are right, the title is misleading.  I'll update it.

Forcing to lower case would be fine for my use case.  But I think it would be more generally useful to more people if it were possible to have a custom message.

**Comment by deltecent** [comment]
> But I think it would be more generally useful to more people if it were possible to have a custom message.

I think so too.

**Comment by dugoh** [comment]
Nice to have. I had an sshd honeypot for a while that would call telnet into simh on the 3rd password attempt and dropped you into 4.3BSD root shell. I searched for an option like this to hide the banner message and ended up (trivially) patching sim_tmxr.c.

**Comment by markpizz** [comment]
An arbitrary connection message (as a single static string) doesn't convey the facts of the situation (i.e. what device, simulator and line).  

An option to only have upper or lower case string contents (2 options here) starts down a slippery slope of random options which gets messy and then opens the door to other who knows what kind of other random changes (i.e. user specified string with random inserts that must be validated - VERY BAD practice to accept format strings from user input).

> Nice to have. I had an sshd honeypot for a while that would call telnet into simh on the 3rd password attempt and dropped you into 4.3BSD root shell. I searched for an option like this to hide the banner message and ended up (trivially) patching sim_tmxr.c.

This is a true need to both have a telnet session and no message.

I've added a specific option to avoid connect (and disconnect) messages for telnet enabled circuits.

This can be conveyed by either an attach time option where the TELNET (or NOTELNET) detail:
```
sim> ATTACH <dev> 1234;NOMESSAGE
```

Or an API that a DEVICE may use usually in it's DEVICE reset routine:

```
t_stat tmxr_set_nomessage (TMXR *mp);
t_stat tmxr_clear_nomessage (TMXR *mp);
```

**Comment by larsbrinkhoff** [comment]
Thank you.  I'll close this issue.

> user specified string with random inserts that must be validated - VERY BAD practice to accept format strings from user input

That is indeed a possible option I had in mind.  There may well be pitfalls I haven't considered, but I'm surprised it would be "VERY BAD".  But I will not pursue this further here.
