### ISSUE TITLE
sim_vm_release, sim_vm_release_message multiple definitions in HP2100, HP3000 sims

### ISSUE THREAD

**Issue by bscottm** [simh/simh#855]
New compile issue while building HP2100 and HP3000 simulators: `sim_vm_release` and `sim_vm_release_message` are multiply defined. Problem seems to be that `scp.c` defines those two variables in uninitialized space (.bss), whereas the HP2100 and HP3000 simulators initialize them.

The fix seems to point to renaming `sim_vm_release` and `sim_vm_release_message` in these two simulators and assigning to `scp.c`'s variables during the call to `sim_vm_init`.

```
 : && /usr/bin/cc -g   HP3000/CMakeFiles/hp3000.dir/hp_disclib.c.o HP3000/CMakeFiles/hp3000.dir/hp_tapelib.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_atc.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_clk.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_cpu.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_cpu_base.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_cpu_fp.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_cpu_cis.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_ds.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_iop.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_lp.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_mem.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_mpx.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_ms.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_scmb.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_sel.c.o HP3000/CMakeFiles/hp3000.dir/hp3000_sys.c.o  -o HP3000/hp3000 -L/builds/scooter-phd/simh-cmake/cmake/dependencies/Linux-4-x86_64-linux-gnu-GNU-10.1/lib -Wl,-rpath,/builds/scooter-phd/simh-cmake/cmake/dependencies/Linux-4-x86_64-linux-gnu-GNU-10.1/lib: libsimhcore.a slirp/libslirp.a /usr/lib/x86_64-linux-gnu/libpcap.so /usr/lib/libvdeplug.so -lncurses /usr/lib/x86_64-linux-gnu/libform.so /usr/lib/x86_64-linux-gnu/libpcre2-8.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libbz2.so -lrt -ldl -lm -pthread && :
 /usr/bin/ld: libsimhcore.a(scp.c.o):(.bss+0x1d8): multiple definition of `sim_vm_release'; HP3000/CMakeFiles/hp3000.dir/hp3000_sys.c.o:(.data+0x0): first defined here
 /usr/bin/ld: libsimhcore.a(scp.c.o):(.bss+0x1e0): multiple definition of `sim_vm_release_message'; HP3000/CMakeFiles/hp3000.dir/hp3000_sys.c.o:(.data+0x8): first defined here
```

**Comment by markpizz** [comment]
The problem has something to do with your cmake building.  

Check the Travis build at: https://travis-ci.org/github/simh/simh/jobs/690211384

**Comment by bscottm** [comment]
Yes, you're right, there's a difference. The travis build uses gcc 5.4.0, whereas gitlab's gcc docker image is on gcc 10.1.0. Do you have a way to tweak travis to use gcc 10 offhand or is travis locked into that particular version of Ubuntu + gcc?

**Comment by markpizz** [comment]
It builds without issue using both gcc (9.3.0) and clang (10.0.0) on the just released Ubuntu 20.04.

It builds without issue on macOS Catalina using clang (11.0.3) as part of Xcode 11.5.

If you push the envelope by using bleeding edge tool chain components, you get to either:
1) address problems the tool chain changes introduce with the tool chain developers
2) find your own workaround

As I've said in the past, when I've encountered problems like this with dependencies, I've reported problems with the upstream dependency providers and they were eventually fixed.  This most recently involved Npcap which was reported 2 months back and fixed last month.  Previous issues have included problems with gcc, SDL and others.

**Comment by bscottm** [comment]
Here's the output log for the stock SIMH `makefile`-based build on Gitlab's default gcc docker image.

I'm not pushing the edges, just using what's supplied by Gitlab, something over which I have very little control (more specifically, it's the gcc maintainers providing the Docker image being pulled by Gitlab's CI/CD pipeline.) 

Re: NPCAP: That's something where influence can be exerted via bug reports. Thanks for following up on that and getting the fix implemented.

[gitlab-out.txt](https://github.com/simh/simh/files/4672344/gitlab-out.txt)

**Comment by markpizz** [comment]
You've already identified the problem as a gcc one.  Finding out if the latest gcc (which may be newer than on the docker image) fixes the problem would suggest that you should raise the issue with the maintainers of the gitlab docker image.   If the problem is still in gcc, then you get to go to the gcc folks.  

Good Luck.

**Comment by markpizz** [comment]
It might be the version of ld and not gcc.  Once again, good luck.

**Comment by bscottm** [comment]
`-fno-common` is now the default in gcc 10 (I manually added `-fcommon` to the `makefile` and the compile succeeds.) That's going to be a problem for SIMH at some point down the road for code security/safety purists.

`hp2100` and `hp3000` are the __only__ simulators that rely on `sim_vm_release` and `sim_vm_release_message`, which does beg the overall utility of the two variables. Several options for a fix:

- Add `-fcommon` if `GCC_MAJOR_VERSION` >= 10. Fixes problem, but isn't future-proof if GCC decides to change behavior again.
- Redefine `sim_vm_release` and `sim_vm_release_message` as weak functions returning `const char *` and then call the functions to get the release string and release message inside of `show_version`.

````
    WEAK const char *(*sim_vm_release)();
    WEAK const char *(sim_vm_release_message)();
````

    
- Rename `sim_vm_release` and `sim_vm_release_message` to `hp2100_vm_release`/`hp3000_vm_release` and `hp2100_vm_release_message`/`hp3000_vm_release_message`, respectively and assign to `sim_vm_release` and `sim_vm_release_message` inside of the simulators' `one_time_init` function.

The last two are relatively future-proof and a bit more kosher.
