### ISSUE TITLE
PDP-11 FMUL Issue

### ISSUE THREAD

**Issue by pdr0663** [simh/simh#859]
I am adding floating point instructions to FigForth for the PDP-11. I have both PDP-11/03 and PDP-11/23 machines (not yet working) so I'm simulating on SimH.

I have what seem to be well-formed floats ( 2.0, and pi) on the Forth stack (pointed to by R5), and the FMUL R5 instruction seems to be executed, but the result is missing. Here is the SimH session:

-------------------------------------------------

Breakpoint, PC: 032516 (FMUL R5)
sim> e r5
R5:     055530
sim> e 55530
55530:  040000
sim> e 55532
55532:  000000
sim> e 55534
55534:  040111
sim> e 55536
55536:  007733
sim> e cpu v
V:      0
sim> s

Step expired, PC: 032520 (MOV (R4)+,R2)
sim> e cpu z
Z:      0
sim> e cpu v
V:      0
sim> e cpu z
Z:      0
sim> e cpu c
C:      0
sim> e 55534
55534:  040111
sim> e 55536
55536:  007733
sim> e r5
R5:     055530
sim>

-----------------------------------------------------------

- #### Context

Here is the command I use to start SimH:

set cpu 11/23+ 256K
set tto 8b
attach LPT lpt.txt
set rl0 writeenabled
set rl0 rl02
attach rl0 rl02_figforth-1.3.3.1.dsk.gz
set rl1 writeenabled
set rl1 rl02
attach rl1 rl02.dsk
set rl1 badblock
boot rl0
set console telnet=23
EOF

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
sim> show version
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Jul  1 2019 at 08:21:11
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.8
        PCRE RegEx (Version 8.36 2014-09-26) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 10.0.18363.836]
        Architecture: x86 on AMD64, Processors: 8
        Processor Id: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel, Level: 6, Revision: 3a09
        git commit id: 81472b58
        git commit time: 2019-07-01T08:11:46-07:00
sim>

- #### how you built the simulator or that you're using prebuilt binaries

Using prebuilt binaries for Windows.
- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

Expected 55534 and 55536 to contain the result, i.e. 2.0*pi.
- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

Paul Riley

**Comment by archivisth** [comment]
You're on an 11/23, which implements the register-oriented FP11 instructions. Forth expects the 11/03's stack-oriented FIS instructions. Clearly, this isn't going to work.

On an 11/23, the LSI-11 FIS instructions should trap as illegal instructions. In any case, they won't do what Forth is expecting.

Retry on an 11/03, and be sure to enables the FIS option.

**Comment by pdr0663** [comment]
Archvisth,

Thanks so much, was sure it would be an oversight on my part.

Paul
