### ISSUE TITLE
No/Bad Prompt Printing (Compiled with musl libc)

### ISSUE THREAD

**Issue by mentalisttraceur** [simh/simh#861]
I have compiled SIMH 3.11-0 and SIMH 3.11-1 on two separate systems with musl libc, and when I run the `pdp11` binary, it

1. does **not** print the prompt whenever it is ready for input, but then

2. **does** print one or more prompts on one line back to back at the wrong times.

Here is an example (note how there is no prompts on the lines where user input goes, but the prompts seem to "build up" in memory with every new line of input and then get flushed out all at once when there is some other output):

```
$ pdp11

PDP-11 simulator V3.11-0
set cpu 11/45
sim> Disabling XQ
set cpu 11/45


SHOW VERSION
sim> sim> sim> sim> PDP-11 simulator V3.11-0 [32b data, 32b addresses, Threaded Ethernet Packet transports:PCAP:UDP]

```

#### Output from `SHOW VERSION`

On a clean start:

```
sim> PDP-11 simulator V3.11-0 [32b data, 32b addresses, Threaded Ethernet Packet transports:PCAP:UDP]
```

Again note the prompt at the front. If you hit enter/return `n` times before entering `SHOW VERSION`, you get `n+1` copies of `sim> `.

#### How I built it
`make all`

#### Expected Behavior
Expected behavior is that the prompt is printed normally.

When I compiled it on MacOS I did not have this problem. I also compiled on a system with glibc instead of musl and it worked fine.

My first guess is that it's maybe some code relying on not-guaranteed-by-the-standard impression details about when output is flushed, but I have not had time to dig into the code to find out.

**Comment by markpizz** [comment]
Please try using the latest simh downloadable as https://github.com/simh/simh/archive/master.zip or directly from the git repo https://github.com/simh/simh

If you still see the problem there, see if you have readline installed and if it appears to work (up arrow gets prior commands).  The problem you're seeing may or may not have something to do with readline interactions.

**Comment by mentalisttraceur** [comment]
@markpizz Just... directly from the HEAD of the `master` branch? Unconventional, but I can respect that.

I didn't even realize readline support was an option.

**Comment by mentalisttraceur** [comment]
Oops, accidentally tapped "close and comment" before I could finish typing.

Alright I'll go ahead and try that and get back to you.

So is the official policy to just assume `master` is the latest release? Or is this just to test if it works with the latest code?

**Comment by mentalisttraceur** [comment]
@markpizz Same problem when built from `master`.

Sorry, I don't have time to keep chasing this further right now, so that's where I'll leave it for now.

The musl libc system I just built `master` on running Void Linux, so if anyone wants to follow up more before I can get around to spending more time on it, it should be easy to reproduce in a fresh container or VM running the musl flavor of Void Linux.

**Comment by markpizz** [comment]
Please provide the output produced when you build the pdp11 from the master branch:
```
  $ make pdp11
```

**Comment by mentalisttraceur** [comment]
Yep, that works! Thank you!

(Feel free to close the issue - I'm just leaving it open in case you want to keep it open for some reason.)

**Comment by markpizz** [comment]
> So is the official policy to just assume master is the latest release? Or is this just to test if it works with the latest code?

master is the latest code and has evolved significantly from Bob Supnik's personally maintained simulators represented by the 3.x code base.  Bob's code base is tracked in the "Supnik-Current" branch of the github repo.  There are 26 simulators that Bob maintains.  There are 82 simulators in the master branch.

Please provide the output produced when you build the pdp11 simulator using the code in the master branch.

It is relatively rare we get a new Linux host that has any issues.  The make output helps to understand things.  Likewise, the SHOW VERSION output from the master branch version helps to illuminate more things.

**Comment by mentalisttraceur** [comment]
Thanks for the answer and clarification/explanation about what output you want and why.

Here you go:

```
~/Downloads/simh $ make pdp11
lib paths are: 
include paths are:  /usr/local/include /usr/include /usr/lib/gcc/x86_64-linux-musl/9.3.0/include
using semaphore: /usr/include/semaphore.h
*** Info ***
*** Info *** The simulator you are building could provide more
*** Info *** functionality if video support were available on your system.
*** Info *** Install the development components of libSDL2 packaged by your
*** Info *** operating system distribution and rebuild your simulator to
*** Info *** enable this extra functionality.
*** Info ***
*** Warning ***
*** Warning *** pdp11 Simulator is being built WITHOUT
*** Warning *** libpcap networking support
*** Warning ***
*** Warning *** To build simulator(s) with libpcap networking support you
*** Warning *** should read 0readme_ethernet.txt and follow the instructions
*** Warning *** regarding the needed libpcap development components for your
*** Warning *** Linux platform
*** Warning ***
*** Info ***
*** Info *** Simulators on your Linux platform can also be built with
*** Info *** extended LAN Ethernet networking support by using VDE Ethernet.
*** Info ***
*** Info *** To build simulator(s) with extended networking support you
*** Info *** should read 0readme_ethernet.txt and follow the instructions
*** Info *** regarding the needed libvdeplug components for your Linux
*** Info *** platform
*** Info ***
***
*** pdp11 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 9.3.0.
*** - Local LAN packet transports: TAP NAT(SLiRP)
*** - Per simulator tests will be run.
***
*** git commit id is b9297e185ff42e9cee7db3e4950c8681bf80e026.
*** git commit time is 2020-05-26T09:47:10-0700.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -DSIM_GIT_COMMIT_ID=b9297e185ff42e9cee7db3e4950c8681bf80e026 -DSIM_GIT_COMMIT_TIME=2020-05-26T09:47:10-0700  -DSIM_COMPILER="GCC Version: 9.3.0" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_UTIME -DHAVE_GLOB  ./PDP11/pdp11_fp.c ./PDP11/pdp11_cpu.c ./PDP11/pdp11_dz.c ./PDP11/pdp11_cis.c ./PDP11/pdp11_lp.c ./PDP11/pdp11_rk.c ./PDP11/pdp11_rl.c ./PDP11/pdp11_rp.c ./PDP11/pdp11_rx.c ./PDP11/pdp11_stddev.c ./PDP11/pdp11_sys.c ./PDP11/pdp11_tc.c ./PDP11/pdp11_tm.c ./PDP11/pdp11_ts.c ./PDP11/pdp11_io.c ./PDP11/pdp11_rq.c ./PDP11/pdp11_tq.c ./PDP11/pdp11_pclk.c ./PDP11/pdp11_ry.c ./PDP11/pdp11_pt.c ./PDP11/pdp11_hk.c ./PDP11/pdp11_xq.c ./PDP11/pdp11_xu.c ./PDP11/pdp11_vh.c ./PDP11/pdp11_rh.c ./PDP11/pdp11_tu.c ./PDP11/pdp11_cpumod.c ./PDP11/pdp11_cr.c ./PDP11/pdp11_rf.c ./PDP11/pdp11_dl.c ./PDP11/pdp11_ta.c ./PDP11/pdp11_rc.c ./PDP11/pdp11_kg.c ./PDP11/pdp11_ke.c ./PDP11/pdp11_dc.c ./PDP11/pdp11_dmc.c ./PDP11/pdp11_kmc.c ./PDP11/pdp11_dup.c ./PDP11/pdp11_rs.c ./PDP11/pdp11_vt.c ./PDP11/pdp11_td.c ./PDP11/pdp11_io_lib.c ./PDP11/pdp11_rom.c ./PDP11/pdp11_ch.c   ./PDP11/pdp11_ng.c ./PDP11/pdp11_daz.c  ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -DVM_PDP11 -I ./PDP11 -DHAVE_TAP_NETWORK -DUSE_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c  -o BIN/pdp11   
BIN/pdp11 RegisterSanityCheck  </dev/null 
 Running internal register sanity checks on PDP-11 simulator.
*** Good Registers in PDP-11 simulator.
~/Downloads/simh $ ./BIN/pdp11

PDP-11 simulator V4.0-0 Current        git commit id: b9297e18
sim> show version
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 9.3.0
        Simulator Compiled as C arch: x64 (Release Build) on May 27 2020 at 06:34:25
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        No RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux 9eeed 5.4.42_1 #1 SMP PREEMPT Thu May 21 07:35:36 UTC 2020 x86_64 GNU/Linux
        git commit id: b9297e18
        git commit time: 2020-05-26T09:47:10-0700
sim> 
```

**Comment by markpizz** [comment]
Thanks,
