### ISSUE TITLE
AltairZ80 attempt to use TMXR with serial port issue

### ISSUE THREAD

**Issue by deltecent** [simh/simh#871]
- #### Context
I am writing an 88-2SIO device for the AltairZ80 simulator and have run into a problem with the multiplexer with an attached serial port that I cannot figure out. 

The CP/M banner is sent correctly and the 'A>' is displayed. At that point, when entering a command, such as `DIR`, there is a ~2 second delay between the echoing of characters. When running a `SHOW MUX`, the output shows `off` in between the echoing of characters:
```
Simulation stopped, PC: 0F3FE (MVI A,1Bh)
sim> show mux
Multiplexer device: 2SIO, lines=2, Output Unit: 2SIO0,
    Input Polling Unit: 2SIO0,
    attached to Line=0,Connect=/dev/cu.USA19H14411P1.1;9600-8n1, 1 current connection, sessions=0
Line: 0 - notelnet, Speed=9600 bps
Connected to serial port /dev/cu.USA19H14411P1.1;9600-8n1
 Connected 00:00:20
  input (on) queued/total = 0/12
  output (off) queued/total = 0/83
  speed = 9600 bps
  bytes in buffer = 83
Line: 1
```
Start the simulator again, wait about ~2 seconds, and then the output is `on` again:
```
sim> show mux
Multiplexer device: 2SIO, lines=2, Output Unit: 2SIO0,
    Input Polling Unit: 2SIO0,
    attached to Line=0,Connect=/dev/cu.USA19H14411P1.1;9600-8n1, 1 current connection, sessions=0
Line: 0 - notelnet, Speed=9600 bps
Connected to serial port /dev/cu.USA19H14411P1.1;9600-8n1
 Connected 00:01:16
  input (on) queued/total = 0/22
  output (on) queued/total = 0/100
  speed = 9600 bps
  bytes in buffer = 100
Line: 1
```
This is causing CP/M to wait ~2 seconds when echoing characters.

Also, I cannot figure out how to enable Multiplexer debugging.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
sim> show version
Altair 8800 (Z80) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)
        Simulator Compiled as C arch: x64 (Release Build) on Jun  7 2020 at 18:47:37
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin Patricks-iMac-2.deltec.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
        git commit id: b05ebad7
        git commit time: 2020-06-06T17:54:06-0700
```
- #### how you built the simulator or that you're using prebuilt binaries

```
Patricks-iMac-2:simh patrick$ make altairz80
lib paths are: /usr/lib /opt/local/lib /usr/local/Cellar/gcc/9.3.0_1/lib /usr/local/Cellar/gmp/6.2.0/lib /usr/local/Cellar/isl/0.22.1/lib /usr/local/Cellar/libmpc/1.1.0/lib /usr/local/Cellar/mpfr/4.0.2/lib /usr/X11/lib
include paths are:  /usr/local/include /Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include /Library/Developer/CommandLineTools/usr/include /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include /opt/local/include /usr/local/Cellar/gcc/9.3.0_1/include /usr/local/Cellar/gmp/6.2.0/include /usr/local/Cellar/isl/0.22.1/include /usr/local/Cellar/libmpc/1.1.0/include /usr/local/Cellar/mpfr/4.0.2/include
using libm: /usr/lib/libm.dylib
using libpthread: /usr/lib/libpthread.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/pthread.h
using libpcre: /usr/lib/libpcre.dylib /opt/local/include/pcre.h
using libdl: /usr/lib/libdl.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dlfcn.h
using libpng: /opt/local/lib/libpng.dylib /opt/local/include/png.h
using zlib: /usr/lib/libz.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/zlib.h
using mman: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/mman.h
***
*** altairz80 Simulator being built with:
*** - compiler optimizations and no debugging support. Apple LLVM version 10.0.1.
*** - Per simulator tests will be run.
***
*** git commit id is b05ebad7d4e647621ba827fd43cf43f2920c1c30.
*** git commit time is 2020-06-06T17:54:06-0700.
***
gcc -std=c99 -U__STRICT_ANSI__  -O2 -fno-strict-overflow -finline-functions -DSIM_GIT_COMMIT_ID=b05ebad7d4e647621ba827fd43cf43f2920c1c30 -DSIM_GIT_COMMIT_TIME=2020-06-06T17:54:06-0700  -DSIM_COMPILER="Apple LLVM version 10.0.1" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -I/opt/local/include -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCRE_H -DHAVE_SYS_IOCTL -DHAVE_DLOPEN=dylib -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./AltairZ80/altairz80_cpu.c ./AltairZ80/altairz80_cpu_nommu.c ./AltairZ80/altairz80_dsk.c ./AltairZ80/disasm.c ./AltairZ80/altairz80_sio.c ./AltairZ80/altairz80_sys.c ./AltairZ80/altairz80_hdsk.c ./AltairZ80/altairz80_net.c ./AltairZ80/s100_2sio.c ./AltairZ80/flashwriter2.c ./AltairZ80/i86_decode.c ./AltairZ80/i86_ops.c ./AltairZ80/i86_prim_ops.c ./AltairZ80/i8272.c ./AltairZ80/insnsd.c ./AltairZ80/altairz80_mhdsk.c ./AltairZ80/mfdc.c ./AltairZ80/n8vem.c ./AltairZ80/vfdhd.c ./AltairZ80/s100_disk1a.c ./AltairZ80/s100_disk2.c ./AltairZ80/s100_disk3.c ./AltairZ80/s100_fif.c ./AltairZ80/s100_mdriveh.c ./AltairZ80/s100_jadedd.c ./AltairZ80/s100_mdsa.c ./AltairZ80/s100_mdsad.c ./AltairZ80/s100_selchan.c ./AltairZ80/s100_ss1.c ./AltairZ80/s100_64fdc.c ./AltairZ80/s100_scp300f.c ./AltairZ80/s100_tarbell.c ./AltairZ80/wd179x.c ./AltairZ80/s100_hdc1001.c ./AltairZ80/s100_if3.c ./AltairZ80/s100_adcs6.c ./AltairZ80/m68kcpu.c ./AltairZ80/m68kdasm.c ./AltairZ80/m68kasm.c ./AltairZ80/m68kopac.c ./AltairZ80/m68kopdm.c ./AltairZ80/m68kopnz.c ./AltairZ80/m68kops.c ./AltairZ80/m68ksim.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -I ./AltairZ80 -DUSE_SIM_IMD -o BIN/altairz80 -L/opt/local/lib -L/usr/X11/lib -lm -lpthread -lpcre -ldl -lpng -lz  
BIN/altairz80 RegisterSanityCheck  </dev/null 
 Running internal register sanity checks on Altair 8800 (Z80) simulator.
*** Good Registers in Altair 8800 (Z80) simulator.
```
- #### the simulator configuration file (or commands) which were used when the problem occurred.
```
#dep CLOCK 2000
  
#dep 0000 db
#dep 0001 12
#dep 0002 3e
#dep 0003 2a
#dep 0004 d3
#dep 0005 13
#dep 0006 c3
#dep 0007 00
#dep 0008 00

set debug stdout
#set cpu verbose

set 2sio enable
#set 2sio debug=status;in;out
attach 2sio0 line=0,connect=/dev/cu.USA19H14411P1.1;9600-8n1

ATTACH DSK0 cpm2.dsk
boot dsk0
#LOAD dbl.bin FF00
#GO FF00
```
- #### the expected behavior and the actual behavior
`lp->xmte` should not take ~2 second to be set to 1 after sending a byte while running at 9600bps.

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem
```
/* Terminal multiplexer library descriptors */

static TMLN m2sio_ldsc[2] = {                   /* line descriptors */
    { 0 }
};

static TMXR m2sio_desc = {                      /* multiplexer descriptor */
    2,                                          /* number of terminal lines */
    0,                                          /* listening port (reserved) */
    0,                                          /* master socket  (reserved) */
    m2sio_ldsc,                                 /* line descriptor array */
    NULL,                                       /* line connection order */
    NULL                                        /* multiplexer device (derived internally) */
};

/* Attach routine */
t_stat m2sio_attach(UNIT *uptr, CONST char *cptr)
{
    int32 status,port;

    port = (uptr == &m2sio_unit[1]);    /* Port 0 or 1? */

    sim_debug(STATUS_MSG, &m2sio_dev, M2SIO_SNAME "%d: attach '%s'." NLP, port, cptr);

    status = tmxr_attach(&m2sio_desc, uptr, cptr);          /* attach to serial */

    m2sio_ldsc[port].conn = 1;
    m2sio_ldsc[port].rcve = 1;

    return (status);
}

static int32 m2sio_stat(UNIT *uptr, int32 io, int32 data)
{
    int32 c,port;

    tmxr_poll_tx(&m2sio_desc);
    tmxr_poll_rx(&m2sio_desc);

    port = (uptr == &m2sio_unit[1]);    /* Port 0 or 1? */

    if (io == 0) {
        if (uptr->flags & UNIT_ATT) {
            if (tmxr_rqln(&m2sio_ldsc[port])) {
                uptr->u3 |= M2SIO_RXRDY;
                uptr->buf = tmxr_getc_ln(&m2sio_ldsc[port]);
            }
            uptr->u3 |= (tmxr_tqln(&m2sio_ldsc[port])) ? 0 : M2SIO_TXRDY;
        } else if (port == 0) {
            c = sim_poll_kbd();
            if (c & SCPE_KFLAG) {                               /* character available?                     */
                uptr->u3 |= M2SIO_RXRDY;                     /* indicate character available             */
                uptr->buf = c & 0xff;                        /* store character in buffer                */
            }
        }
        return(uptr->u3);
    } else {
        if (data == M2SIO_RESET) {                             /* reset port! */
            uptr->u3 = M2SIO_TXRDY;
            uptr->buf = 0;
        }
        sim_debug(OUT_MSG, &m2sio_dev, M2SIO_SNAME
                  "%d: STAT OUT = 0x%02x" NLP, port, data);
    }

    return (0);
}

static int32 m2sio_data(UNIT *uptr, int32 io, int32 data)
{
    int port;
    FILE *fp;

    port = (uptr == &m2sio_unit[1]);    /* Port 0 or 1? */

    if (io == 0) {
        uptr->u3 &= ~M2SIO_RXRDY;
        sim_debug(IN_MSG, &m2sio_dev, M2SIO_SNAME
                  "%d: DATA IN  = 0x%02x" NLP, port, uptr->buf);
        return (uptr->buf);
    } else {
        sim_debug(OUT_MSG, &m2sio_dev, M2SIO_SNAME
                  "%d: DATA OUT = 0x%02x" NLP, port, data);
        if (uptr->flags & UNIT_ATT) {
            if (uptr->u3 & M2SIO_TXRDY) {
                tmxr_putc_ln(&m2sio_ldsc[port], data);
                uptr->u3 &= ~M2SIO_TXRDY;
            } else {
                sim_debug(ERROR_MSG, &m2sio_dev, M2SIO_SNAME ": TX buffer overrun at I/O 0x%02x" NLP, pnp.io_base);
            }
            tmxr_poll_tx(&m2sio_desc);
        } else if (port == 0) {
            sim_putchar(data);
        }
    }

    return SCPE_OK;
}
```

**Comment by markpizz** [comment]
Not enough context here.

Please commit your current code to a temporary branch in your personal repo at https://github.com/deltecent/simh

**Comment by deltecent** [comment]
https://github.com/deltecent/simh/tree/2sio

**Comment by deltecent** [comment]
All I can tell so far is when `rxnexttime` is calculated and compared with `sim_gtime()`, it is taking way more time than it should for 9600bps. `txnexttime` uses the same calculation, and although much slower than 9600bps, is not nearly as slow as receive. If I modify the code to ignore the speed, it works great.

**Comment by markpizz** [comment]
> Also, I cannot figure out how to enable Multiplexer debugging.

Add DEV_MUX to the DEVICE flags field.  Without this you get:
```
sim> set 2sio ena
sim> help 2sio
MITS 88-2SIO SERIAL ADAPTER 2SIO help

2SIO device SET commands:

set 2SIO IOBASE                 Sets MITS 2SIO base address
set 2SIO ENABLE                 Enables device 2SIO
set 2SIO DISABLE                Disables device 2SIO
set 2SIO DEBUG                  Enables debugging for device 2SIO
set 2SIO NODEBUG                Disables debugging for device 2SIO
set 2SIO DEBUG=IN;OUT;STATUS;ERROR;VERBOSE
                                Enables specific debugging for device 2SIO
set 2SIO NODEBUG=IN;OUT;STATUS;ERROR;VERBOSE
                                Disables specific debugging for device 2SIO
set 2SIOn ENABLE                Enables unit 2SIOn
set 2SIOn DISABLE               Disables unit 2SIOn

*2SIO device DEBUG settings:
    IN          IN operations
    OUT         OUT operations
    STATUS      Status messages
    ERROR       Error messages
    VERBOSE     Verbose messages

2SIO device SHOW commands:

show 2SIO IOBASE                Sets MITS 2SIO base address
show 2SIO DEBUG                 Displays debugging status for device 2SIO

The 2SIO device implements these registers:

  STAT0    8  2SIO port 0 status buffer
  DATA0    8  2SIO port 0 data buffer
  STAT1    8  2SIO port 1 status buffer
  DATA1    8  2SIO port 1 data buffer
sim>
```
With DEV_MUX you get:
```
sim> help 2sio
MITS 88-2SIO SERIAL ADAPTER 2SIO help

2SIO device SET commands:

set 2SIO IOBASE                 Sets MITS 2SIO base address
set 2SIO ENABLE                 Enables device 2SIO
set 2SIO DISABLE                Disables device 2SIO
set 2SIO DEBUG                  Enables debugging for device 2SIO
set 2SIO NODEBUG                Disables debugging for device 2SIO
set 2SIO DEBUG=IN;OUT;STATUS;ERROR;VERBOSE;XMT;RCV;RET;MODEM;CONNECT;ASYNC;TRACE;XMTPKT;RCVPKT;EXPECT;SEND
                                Enables specific debugging for device 2SIO
set 2SIO NODEBUG=IN;OUT;STATUS;ERROR;VERBOSE;XMT;RCV;RET;MODEM;CONNECT;ASYNC;TRACE;XMTPKT;RCVPKT;EXPECT;SEND
                                Disables specific debugging for device 2SIO
set 2SIOn ENABLE                Enables unit 2SIOn
set 2SIOn DISABLE               Disables unit 2SIOn

*2SIO device DEBUG settings:
    IN          IN operations
    OUT         OUT operations
    STATUS      Status messages
    ERROR       Error messages
    VERBOSE     Verbose messages
    XMT         Transmit Data
    RCV         Received Data
    RET         Returned Received Data
    MODEM       Modem Signals
    CONNECT     Connection Activities
    ASYNC       Asynchronous Activities
    TRACE       trace routine calls
    XMTPKT      Transmit Packet Data
    RCVPKT      Received Packet Data
    EXPECT      Expect Activities
    SEND        Send Activities
```

Meanwhile, your focus on getting I/O to a serial port working is the ultimate goal, but you should get the gears and plumbing working with a network connected (telnet) MUX first.  Get things well behaved there and then ATTACHing to a serial port should just work (the user enters a slightly different ATTACH command).  See HELP 2SIO ATTACH after setting DEV_MUX in the DEVICE flags field.  This provides a model for a single ATTACHable UNIT for the DEVICE where the line being ATTACHed can optionally be specified on the command input line.  If you really want to allow each UNIT to be separately ATTACHable, then you've got to craft the mapping of a particular attach command arguments for all UNITs and pass that to tmxr_attach().  This approach is not recommended since it can be messy.

You may want to step back and understand what simh UNIT really is.  When dealing with disk type devices (which are each separately attached) a 1 to 1 mapping of disk drives to simh UNITs makes sense.  However, internally in the running simulator, a UNIT structure holds a little state, but PRIMARILY is something which can be scheduled for future callback to the unit service routine.  In TMXR devices the activities which occur at scheduled times are: 1) Polling for Connections, 2) Polling for arriving input data, and 3) Transmitting output data.  For physical serial port devices and muxes with programmable line speeds the TMXR layer deals with the precise timing requirement of scheduling even callbacks.  If you have more than one unit in your simh MUX DEVICE, you have to let the TMXR layer know which UNITs perform which activities (for which lines) so that it can schedule callbacks at the appropriate times.  You describe which units do what by calling tmxr_set_line_unit() and tmxr_set_line_output_unit().  

I'm not 100% sure you will have great success with the current design of the AltairZ80 simulator and reliable I/O to physical serial ports.  The problem is that the simh framework counts on for serial port I/O (and in particular timing of port based data rates) requires that the simulator never calls sim_os_ms_sleep().  If the simulator somehow determines that it doesn;'t have something to do for a while (and it wants to be a good citizen and not soak up host CPU cycles)., it should call sim_idle().  This works well with the internal timing for clock devices AND for rate properly limiting network or physical serial port devices.  This likely has nothing to do with the problems you are seeing right now since the current code doesn't really use the various TMXR APIs as intended.  Look closely at all of the tmxr_ APIs described in section 5.2 of doc/simh.doc

Errors in the current implementation:
1) You should NEVER explicitly set or examine a TMLN->conn field.
2) You MUST examine the status of tmxr_putc_ln() and come back later when it returns SCPE_STALL.
3) You unit service routine should attempt to transmit data.
4) The unit service routine should call tmxr_poll_tx() AFTER attempting to transmit data
5) The unit service routine should call tmxr_poll_rx() BEFORE attempting to read data.
6) The unit service routine should reschedule itself AFTER processing input and/or output data.

Remember that even though you have 2 ports in this picture, you have 1 MUX so you should do ALL input processing for ALL ports/lines in the same unit service routine and based on which line(s) received input update the appropriate simulated device.  You can do the transmit processing for ALL units in that same unit service routine, or on a separate UNIT depending on your preference.

**Comment by psco** [comment]
Please note that the usage of sim_os_ms_sleep() is user configurable via the SET SIO SLEEP respectively SET SIO NOSLEEP command and is provided for the kinds of software which rely on some sort of loop to check for I/O availability.

**Comment by deltecent** [comment]
Mark, thank you. That is great information. I initially had everything working in the service, and if I recall, it was working fine a few weeks ago. I think things got strange after the last merge of master. In order to "simplify" the device, and figure out what had broke somewhere along the way, I removed everything out of the service.

I think I have a correct understanding of a device and unit. It makes a lot of sense with disk systems, where you have a single disk controller with attached drives. The 88-2SIO serial device doesn't quite fit the model because it's actually 2 separate devices (Port 0 and Port 1) on a single card. It should probably be 2 separate devices in the emulator, like `2SIO0` and `2SIO1`, but I initially chose to have 2 units. I think I'll change that too.

Regarding `TMLN->conn`, after attaching a serial device, it was always false, and digging through `sim_tmxr.c`, I could never see a way to get it true other than setting it myself. It seemed to be related to polling for TCP connections. Serial ports are always connected and I don't know of a way to poll for serial connection using the MUX.

A secondary goal of this project is to have a simple device that shows the proper way use the DEV-MUX with serial ports. With your information, I can hopefully accomplish that too.

Thank you for the input. Now I feel like I'm going in the right direction.

**Comment by markpizz** [comment]
> Please note that the usage of sim_os_ms_sleep() is user configurable via the SET SIO SLEEP respectively SET SIO NOSLEEP command and is provided for the kinds of software which rely on some sort of loop to check for I/O availability.

I would guess that the use of sim_os_ms_sleep() possibly existed before simh had idle support, but from what you say, you might be able to replace that functionality with calls to sim_idle() to achieve precisely the same goal while also keeping simh's under the covers bookkeeping in good shape.  If you go down this path, you'll have to add UNIT_IDLE to device UNIT structure flag biits for devices that get activated regularly (terminal muxes, clocks, etc.).

**Comment by markpizz** [comment]
> Regarding TMLN->conn, after attaching a serial device, it was always false, and digging through sim_tmxr.c, I could never see a way to get it true other than setting it myself. It seemed to be related to polling for TCP connections. Serial ports are always connected and I don't know of a way to poll for serial connection using the MUX.

As I said previously, get this working correctly with network connections and the serial behaviors will just fall out.

Does this device have programmable speed settings?

Does it have modem signalling (DTR, CTS, etc)?
Does it report incoming modem state (DCD, RTS, RI, etc.)?

**Comment by deltecent** [comment]
One other odd thing while we're on the subject of attach, after attaching and quitting SIMH, I'm always getting `String must be quote delimited`:

```
2sio.sim-19> attach 2sio 127.0.0.1:8000
Listening on port 127.0.0.1:8000
sim> q
Goodbye
DBG(0)> 2SIO VERBOSE: m2sio_detach.
-0> q
String must be quote delimited
Debug output disabled
```

Any idea what that means?

**Comment by markpizz** [comment]
It relates to the choice of the DEVICE name you are using.  Starting the DEVICE name with a number gets the name parser confused when trying to cleanup the MUX state when you detach it.  In particular the each line if the MUX can be referenced by the DEVICE name followed by a colon followed by the line number if/when you try to specify EXPECT and/or SEND commands relating to traffic on the mux.  The name starting with a number gets the parser confused.  Most languages don't allow user variable names to start with numeric strings.  This falls into that case.

**Comment by deltecent** [comment]
Ok, I have all input/output processing working in the service routine. I have it working with the console and telnet. Both behave the same. Output is sent at full speed. As soon as the output is done, the service function switches from being called quickly to being called about every second, not at the `KBD_POLL_WAIT` speed that is specified by `sim_activate_abs()`; (`sim_printf("m2sio_svc\n");`) is displayed about once per second.

I have no idea how to determine where this delay/pause/sleep is happening, but there has to be a way to disable it so the service routine gets called at the rate specified and console input is responsive.

```
static t_stat m2sio_svc(UNIT *uptr)
{
    int32 c,l,r;

    sim_printf("m2sio_svc\n");

    /* Check for new incoming connections */
    if (uptr->flags & UNIT_ATT) {
        if ((l = tmxr_poll_conn(&m2sio_tmxr)) >= 0) {     /* poll connection */
            m2sio_tmln[l].rcve = 1;                       /* enable receive  */
            sim_debug(STATUS_MSG, &m2sio_dev, "new connection on line %d.\n", l);
        }
    }

    /* TX data */
    if (!(uptr->u4 & M2SIO_TXRDY)) {
        if (uptr->flags & UNIT_ATT) {
            r = tmxr_putc_ln(&m2sio_tmln[uptr->u3], uptr->u6);
            tmxr_poll_tx(&m2sio_tmxr);
        }
        else {
            r = sim_putchar(uptr->u6);
        }

        /* Buffer available for another character */
	if (r == SCPE_OK) {
            uptr->u4 |= M2SIO_TXRDY;
        }
    }

    /* RX Data */
    if (uptr->flags & UNIT_ATT) {
        tmxr_poll_rx(&m2sio_tmxr);

        c = tmxr_getc_ln(&m2sio_tmln[uptr->u3]);
    }
    else {
        c = sim_poll_kbd();
    }

    if (c & (TMXR_V_VALID | SCPE_KFLAG)) {
        if (uptr->u4 & M2SIO_RXRDY) {
            sim_debug(STATUS_MSG, &m2sio_dev, "RX overrun on port %d.\n", uptr->u3);
        }
        uptr->u5 = c & 0xff;
        uptr->u4 |= M2SIO_RXRDY;
    }

    sim_activate_abs(uptr, uptr->wait);

    return SCPE_OK;
}
```

**Comment by deltecent** [comment]
Here's a video that shows my issue:

https://youtu.be/zqtaDwoVWwc

I enabled SCP Event logging. I don't know why the 5000 event interval changes from running quickly to running once every second or so.

**Comment by markpizz** [comment]
The video is nice, but either you're still running the original code (that I can see in your repo) and not heeded any of my earlier suggestions, OR you've not provided the code you're actually using here.

Either heed my earlier suggestions, OR provide the code you're actually using and I'll look at it.

When I say provide the code, I mean some place where I don't have to cobble together with cut an paste to try to get something close to what you may be using!  Put it in your private repo!

**Comment by deltecent** [comment]
> When I say provide the code, I mean some place where I don't have to cobble together with cut an paste to try to get something close to what you may be using! Put it in your private repo!

Gotcha! the 2sio branch has been updated.

**Comment by markpizz** [comment]
Please explain why you didn't heed ALL of my suggestions.  I will not  bother to repeat previously provided suggestions.  If you come back with another video or specific question without updating the repository, I will close this issue and be done with the subject.

**Comment by deltecent** [comment]
> Please explain why you didn't heed ALL of my suggestions. I will not bother to repeat previously provided suggestions. If you come back with another video or specific question without updating the repository, I will close this issue and be done with the subject.

I believe I heeded all of your suggestions. I'll save you the trouble.

**Comment by markpizz** [comment]
Putting changes WITHIN comment blocks doesn't change the behavior of the code.  I never suggested you should do anything like this!  If you have questions about some aspect of the the suggestions I've made, then ask rather than merely commenting them out without discussion!

**Comment by markpizz** [comment]
Looking closer, given that you've restructured to use a single unit, the calls to tmxr_set_line_unit() and tmxr_set_line_output_unit() aren't necessary.  I'm sorry for my impatience.

Looking at what you're doing in your _svc routine, there are several distinct problems:
1) You're missing a loop to process things on BOTH of the lines in your MUX.  Yes, you've currently only got a single line in the MUX, but many of the other code is built around more than one line.
2) You're marking transmit ready just because you successfully managed to present a character into the tmxr layer.  tmxr_txdone_ln() is relevant here.  Apart from this, didn't this device potentially generate interrupts on transmit complete?
3) since you're 

You never answered the specific  questions I asked:

**Comment by markpizz** [comment]
Does this device have programmable speed settings?

Does it have modem signalling (DTR, CTS, etc)?
Does it report incoming modem state (DCD, RTS, RI, etc.)?

**Comment by markpizz** [comment]
It is fine to take advantage of the user reserved fields in the UNIT structure (u3, u4, u5, and u6), however, best practice suggests that you should actually refer to these fields via a #defined name that has some useful meaning so that someone reading the code can more easily relate to what is going on rather than bare references to the u# field names.

**Comment by deltecent** [comment]
The AltairZ80 SIO device doesn't even follow the heedings of Mark, I suspect because it won't work that way either.

Way down here at my low level of understanding and programming skills, modem controls, UNIT structure usage, transmit ready handling, and everything else you mentioned seems irrelevant if the following _svc routine doesn't work as I expect (it too gets called at a slower rate than I expect).
```
static t_stat m2sio_svc(UNIT *uptr)
{
    uptr->u4 |= M2SIO_TXRDY;

    sim_activate(uptr, uptr->wait);

    return SCPE_OK;
}
```
I do not have enough information at this time to open an issue as my lack of understanding doesn't appear to have anything to do with TMXR or the console. Should I obtain the relevant information, I will create another issue.

I do this for fun. As far as I'm concerned, Mark, you kill that fun. In the future, if I post something that doesn't meet your high standards, don't feel obligated to subject yourself to such intellectual torture and respond. I'd rather wait for someone else that also doesn't understand what a C comment does and we can blindly fumble through this together.

**Comment by markpizz** [comment]
The AltairZ80 SIO device predates any enhancements to TMXR which made I/O to physical serial ports possible.  It therefore isn't good example of how to get the more complicated capabilities working of TMXR.  If you're really interested in a good example, the pdp11_dz.c, pdp11_vh.c and 3b2_ports.c are examples that I know to work.  As I mentioned in an earlier response, that this simulator's calling sim_os_ms_sleep() may ultimately interfere with the timing that I/O to physical serial ports will need.

I ask those questions since the answers play into what you actually need to implement in simulation and/or what you need to fudge to get working I/O to a serial port.  When I ask a question, if you don't know the answer then a discussion is necessary to clarify the understanding of the issues.  This solves problems and helps you understand the subtleties.  If you ignore the questions that are asked and then repeatedly ask questions which may have usefully needed the ignored discussion, then I'm wasting my time by repeating myself.  If I have to repeatedly ask to actually see ALL of the code you're working with, I again have spent time focusing on what may be going on but then not seeing all the pieces.

The sim_activate*() APIs for MUX DEVICEs manage precise timing of MUX line I/O activities based on the internal state of the MUX device and all of the lines on it and only use the provided delay value specified in the API call as a fallback when nothing else interesting is happening.  Alternatively the simulator developer would be stuck with timing interactions that are reasonably complex, different for all host platforms, and potentially interfere with other DEVICEs in the system.

**Comment by deltecent** [comment]
> As I mentioned in an earlier response, that this simulator's calling sim_os_ms_sleep() _**may**_ ultimately interfere with the timing that I/O to physical serial ports will need.

That is the pivotal question to which I was alluding to in my video and _svc routine; that I cannot see anything that my _svc routine is doing that would cause _svc dispatching to be slow, regardless of whether or not is it utilizing TMXR 100% as it was intended to be utilized in your mind. At this point I am only trying to set RXRDY and TXRDY bits, receive a byte on IN instruction, send a byte on OUT instruction, just on the console, using the _svc routine. The only problem I am having is the AltairZ80's `sim_instr_mmu` loop is running much slower than _I think_ it should, causing sim_interval to decrement slow, which causes the _svc routines to be dispatched slow. Serial ports and status lines are no longer even on my radar.

If the simulator's calling `sim_os_ms_sleep()` _**will**_ ultimately interfere with the timing that I/O to physical serial ports (and apparently the console or any other _svc function) will need, then I'm wasting my time until that issue is known and potentially resolved. On a side note, I cannot find that `sim_os_ms_sleep()` is ever called unless `clockFrequency | timerInterrupt | keyboardInterrupt | sim_brk_summ` are used.

How is anyone supposed to know from the documentation that:

- `altairz80_sio.c` is a poor example of using TMXR.
- `pdp11_dz.c` is a good example of using TMXR.
- You should NEVER explicitly set or examine a TMLN->conn field.
- It's perfectly acceptable to set or examine a TMLN->rcve field.
- Your unit service routine should attempt to transmit data.
- The unit service routine should call tmxr_poll_tx() AFTER attempting to transmit data
- The unit service routine should call tmxr_poll_rx() BEFORE attempting to read data.
- The unit service routine should reschedule itself AFTER processing input and/or output data.
- If your simulator calls `sim_os_ms_sleep()`, it _**may**_ interfere with timing.

There is a steep learning curve. The simulator is anything but simple, and as good as the documentation is, it lacks detail in certain areas (TMXR), examples (TMXR), and one must still dig into the source to figure out how it all works (just make sure you're looking at the _right_ source code) and if that fails, try to get assistance from others.

I have been doing my best to provide information based on my current understanding of how the simulator works, which I admit has only scratched the surface. It is not my intention to frustrate anyone or waste their time. I am trying to contribute to the project with something that I think others may find useful.

**Comment by deltecent** [comment]
The problem isn't with the simulator at all (or my code). The problem is with the version of CP/M that I downloaded from the `schorn.ch` web site. That CP/M's BIOS sends sleep commands to the simulator on port 0FEH while waiting for console input, which essentially breaks any sort of timing-dependent service routines. It also seems superfluous since there is sleep logic built into the SIO device on the simulator.

This issue can stay closed as there shouldn't be any issues with standard CP/M distributions from sources like `deramp.com`. I'll just have to make a note that the M2SIO device cannot be used with the simulator-specific versions of CP/M from `schorn.ch` as it breaks `_svc` dispatching (and therefore TMXR) without assembling the BIOS with `sleepol` set to `false`.
```
sleepol equ     true            ; if true then sleep a bit while status polling
                                ; Note: requires SIMH

; The next console character is read into register A, and the parity bit is set,
; high-order bit, to zero.  If no console character is ready, wait until a
; character is typed before returning.
        if      sleepol

conin:  in      a,(constat)     ; get console status
        rra                     ; I bit into carry
        jp      c,getchr        ; get character
        ld      a,27            ; otherwise sleep for SIMHSleep microseconds     <-------------
        out     (0feh),a        ; execute command                                              <-------------
        jp      conin           ; try again
```
```
DBG(673968)> SIMH CMD: SIMH: [0x0000f400] CMD(0xfe) <- 27 (0x1b, 'SIMHSleep')
DBG(674994)> same as above (171 times)
DBG(675000)> SCP-PROCESS EVENT: Processing Event for SIMH
DBG(675000)> SCP-PROCESS EVENT: Processing Event for NULL
DBG(675000)> SCP-PROCESS EVENT: Processing Queue Complete New Interval = 5000(SIMH)
DBG(675000)> SIMH CMD: SIMH: [0x0000f400] CMD(0xfe) <- 27 (0x1b, 'SIMHSleep')
DBG(679998)> same as above (833 times)
DBG(680000)> SCP-PROCESS EVENT: Processing Event for SIMH
DBG(680000)> SCP-PROCESS EVENT: Processing Event for NULL
DBG(680000)> SCP-PROCESS EVENT: Processing Queue Complete New Interval = 5000(SIMH)
DBG(680004)> SIMH CMD: SIMH: [0x0000f400] CMD(0xfe) <- 27 (0x1b, 'SIMHSleep')
DBG(684996)> same as above (832 times)
```
