### ISSUE TITLE
Setting PDP11 DATE and TIME from host ?

### ISSUE THREAD

**Issue by gavineadie** [simh/simh#879]
I'm running RT-11 on a simulated PDP-11/84 (`SET CPU 11/84 1M`).  Everything runs very nicely, I'm very impressed by the quality and depth of simh, and I'm have fun reliving my days of yesteryear!

Since I'm lazy (more accurately, forgetful) I often forget to set the RT-11 `DATE` and `TIME` when I boot up the emulator, and I was wondering if there is a way to pull the a date stamp from the host computer (macOS, in my case, but clearly some method that was not dependent of platform would be desirable) and pass it to the emulated clock?

I looked at using the `BREAK` and `REPLY` simh commands, and I think I could get them to work in conjunction with coercing the STRTxx.COM command file, that runs when RT-11 starts up, to output some prompts for `BREAK` and `REPLY` to trigger on.

I also wondered if the simh `SET CLK` command could be enhanced to take a date and time and pass that, as an initial tick count (?), into the PDP-11 clock.  The machine clock just ticks and it needs an OS to make sense of that ticking in terms of the wall clock time, so we're back to an OS dependency.

Neither of the above feels very sanitary (making the simulator do things that the real computer cannot does seem wrong) and I wonder if this feature has been considered in the past or, perhaps, is already implemented and I didn't see it!

I've written a little macOS program to move files between emulated RT-11 disks and that host; I would consider working on the time question too if an acceptable mechanism was agreed.  I'm still learning about simh, and about the real hardware and will continue to think about this, but wanted to get the idea on the table in case I'm wasting my time .. after all, typing `date 13-Jun-2020` is not difficult!

**Comment by markpizz** [comment]
I'm not a RT11  user, but most systems have some sort of prompt that relates to setting the time.  What you do to generate that prompt (maybe some sort of OS startup script) can then be captured and responded to automatically using simh's built in EXPECT.  The Date/Time details can dynamically provided and you are done.

You can achieve this if your configuration file contains lines somewhat like this before the line which boots the system:
```
EXPECT "whatever the what-time-is-it-prompt" SEND "%DATE%\r"'; CONTINUE
```

More nuts and bolts about what your options are can be found at:
```
sim> HELP EXPECT
sim> HELP SEND
sim> HELP DO VARIABLE_INSERTION
```
Maybe you don't get an explicit "what time is it prompt".  Maybe you just have the initial system prompt after a successful boot.  And maybe the command to set the date/time is like the unix date command:
```
EXPECT "initial-system prompt" SEND "date %DATE_MM%%DATE_DD%%TIME_HH%%TIME_MM%.%TIME_SS%\r"; CONTINUE
```

**Comment by agn453** [comment]
If you specify one of the models with a TOY clock chip then this is detected by recent versions of RT-11 (e.g. a qbus PDP-11/93).  The following is an extract from my RT-11 setup for RT11 V5.7 -

```
;
; 11/93 cpu with 22 bit addressing Qbus and 4Mb memory
set cpu 11/93
set cpu 4m
; cpu idle detection does not work for RT11 operating system
set cpu noidle
; use throttling instead
set throttle 10%
; KDJ11B clock frequency (11/83, 11/84, 11/93, 11/94 only)
set system jclk_dflt=60hz
...
```

Both the date and time are set correctly at boot-up from the SIMH host system.

**Comment by gavineadie** [comment]
Oooh!  Never thought of using a Time of Year clock .. kinda obvious!  Super Thanks!!

I'm also using RT11 V5.7 (`RT-11XM (S) V05.07`), my simh.ini was `SET CPU 11/84 1M` which does **not** capture the date+time.

Your comment `; KDJ11B clock frequency (11/83, 11/84, 11/93, 11/94 only)`, with four models named, implies maybe it should, and 11/83 and 11/84 contained KDJ11-B CPUs, so some other setting is probably wrong.  **But** `SET CPU 11/93 1M` like yours, and `SET CPU 11/94 1M` (more like mine) do work; they had a KDJ11-E CPU.

Still digesting, but I wanted to report your suggestion is successful if I upgrade from an 11/84 to an 11/94 (glad I don't have to pay actual money!).  Still wondering if I can cheat without TOY clock?

Interesting [TOY clock](https://www.5volts.ch/projects/toy/) page

**Comment by gavineadie** [comment]
As I read more, I see real-time clocks arrived with PDP-11/9x.

It looks like PDP-11/8x (KDJ11-B CPUs) did **not** have TOY clocks; PDP-11/9x (KDJ11-E CPUs did).

**Comment by agn453** [comment]
RSTS/E V10.1 as well as RSX-11M-PLUS V4.6 detect the TOY clock too when using a 11/93 and 11/94 cpu under SIMH (and real hardware).

**Comment by gavineadie** [comment]
> Maybe you don't get an explicit "what time is it prompt".
> Maybe you just have the initial system prompt after a successful boot.

RT-11 just emits the initial system prompt (a period: ".")
These are commands that seem to work:
```
EXPECT ".\r\n" SEND "date %DATE_DD%-%DATE_MMM%-%DATE_YYYY%\r"
EXPECT ".\r\n" SEND "time %TIME_HH%:%TIME_MM%-%TIME_SS\r"; CONTINUE
```

**Comment by gavineadie** [comment]
@markpizz .. Re: using `EXPECT` and `SEND` .. I have concocted a sequence of two `EXPECT/SEND` directives in my `simh.ini` that works for setting time and date on lesser PDP-11s running RT-11.  RT-11 does not emit an explicit "what time is it prompt" which made it a little tricky.

What would have helped a little would be having the `EXPECT` string could be marked to signal that the "\r\n\r\n." (the system prompt) be matched only if no characters immediately follow it within, say, half a second.

**Comment by markpizz** [comment]
> What would have helped a little would be having the EXPECT string could be marked to signal that the "\r\n\r\n." (the system prompt) be matched only if no characters immediately follow it within, say, half a second.

Well, that's not a feature of the EXPECT capabilities, but since you're bounded to RT11, and it really doesn't do anything asynchronously, so you'll always get the same output on each boot, you can make the EXPECT match string arbitrarily long/complex including using a regular expression if that is useful in this context.

**Comment by gavineadie** [comment]
@markpizz "so you'll always get the same output on each boot" .. all you say is true (of course), though there is a little variability introduced by what one does in the start-up script.  My EXPECT needs to include a little of the last output from that, and that could change.  However, since that is all under my control, I'm happy.  Thanks, again !

**Comment by gavineadie** [comment]
Learning as I go, I discovered a small program called DATIME which prompts for date and time.  If that program is executed from the startup file, the EXPECT/SEND sequences can be less arcane.  Downside is that the DATIME program invokes the startup, causing a loop .. but that can be resolved easily enough.  The result on a PDP-11 with a non-TOY clock looks like:

```
.IND DATIME

Date [dd-mmm-yyyy]? 20-Jun-2020
Time [hh:mm:ss]? 19:52:50

	RT-11 Foreground Background Monitor, volume ID RT11 V5.7   
	Booted on 20-Jun-2020 at 19:52:50 from file DL0:RT11FB.
```
