### ISSUE TITLE
Intel-Systems/common/multibus.c: isbc208_reset, isbc208_cfg undefined

### ISSUE THREAD

**Issue by bscottm** [simh/simh#880]
Sorry to bring this up (again, I think), which is that dead code elimination is generally only done by an optimizer in a Release build, not in a Debug build. In `Intel-Systems/common/multibus.c`, there is code as follows:

```
150:    if (SBC208_NUM) isbc208_cfg(SBC208_BASE);

181:        if (SBC208_NUM) { //unit enabled
            isbc208_reset(&isbc208_dev);
            sim_printf("    Multibus: SBC208 reset\n");
            }
````

The Release build is the only way that this code will link -- it depends entirely on dead code elimination to optimize away the `if`. Debug builds fail. 

`9d0d567e` is when this problem came back into existence.

**Comment by markpizz** [comment]
9d0d567e is not in this repo.

**Comment by bscottm** [comment]
You're right, it's a local change on my part to unbreak Debug builds, which got overwritten by recent `makefile` updates. Suggest adding the following back to the master `makefile` to unbreak Debug builds:

````
@@ -1841,7 +1841,8 @@ IMDS800 = ${IMDS800C}/i8080.c ${IMDS800D}/imds-800_sys.c \
        ${IMDS800C}/multibus.c ${IMDS800C}/isbc064.c \
        ${IMDS800C}/isbc202.c ${IMDS800C}/isbc201.c \
        ${IMDS800C}/zx200a.c ${IMDS800C}/isbc464.c \
-       ${IMDS800C}/isbc206.c ${IMDS800C}/i3214.c
+       ${IMDS800C}/isbc206.c ${IMDS800C}/i3214.c \
+       ${IMDS225C}/isbc208.c
 IMDS800_OPT = -I ${IMDS800D}


@@ -1854,7 +1855,8 @@ IMDS810 = ${IMDS800C}/i8080.c ${IMDS810D}/imds-810_sys.c \
        ${IMDS810C}/multibus.c ${IMDS810C}/isbc064.c \
        ${IMDS810C}/isbc202.c ${IMDS810C}/isbc201.c \
        ${IMDS810C}/zx200a.c ${IMDS810C}/isbc464.c \
-       ${IMDS810C}/isbc206.c ${IMDS800C}/i3214.c
+       ${IMDS810C}/isbc206.c ${IMDS800C}/i3214.c \
+       ${IMDS225C}/isbc208.c
````

**Comment by markpizz** [comment]
This should be fixed now.
