### ISSUE TITLE
Incorrect sim_time on breakpoint if sim_interval counts cycles rather than instructions

### ISSUE THREAD

**Issue by wachsler** [simh/simh#886]
- #### Context
I'm adding a cycle-accurate profiler to the I1401 simulator, to help optimizing demo programs to run on the machines at the Computer History Museum. (Instructions can take anywhere from 2 cycles to many thousands, so just counting instructions isn't very useful.)

It seemed to me that as part of this project it would make sense to change `sim_vm_interval_units` to be cycles instead of instructions, but I've run into a problem.

When `sim_interval` counts instructions, `sim_process_event` is always called with `sim_interval == 0`. But when counting cycles, it's possible that `sim_interval < 0` when `sim_process_event` is called. **When this happens, and there is a breakpoint on the next instruction, `sim_time` is getting incremented twice**, so that, *e.g.*, an instruction taking 10 cycles can result in `sim_time` being incremented by 19. In general an instruction taking *n* cycles results in *2n-1* being added `sim_time`, instead of *n*.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

```
sim> SHOW VERSION
IBM 1401 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
        Simulator Compiled as C arch: x64 (Release Build) on Jun 14 2020 at 14:06:27
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        No RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin IsabellsMacBook.localdomain 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
        git commit id: 50266704+uncommitted-changes
        git commit time: 2020-06-14T18:50:48+0200
sim> 
```

- #### how you built the simulator or that you're using prebuilt binaries

Here's a patch demonstrating the problem, by simply assuming all instructions take 10 cycles:

```
diff --git a/I1401/i1401_cpu.c b/I1401/i1401_cpu.c
index f54f4060..538df4f9 100644
--- a/I1401/i1401_cpu.c
+++ b/I1401/i1401_cpu.c
@@ -559,7 +559,7 @@ while (reason == 0) {                                   /* loop until halted */
         break;
         }
 
-    sim_interval = sim_interval - 1;
+    sim_interval = sim_interval - 10;
 
 /* Instruction fetch - 1401 fetch works as follows:
```

And the output of make:
```
$ make i1401
lib paths are: /usr/lib /usr/local/Cellar/gdbm/1.18.1/lib /usr/local/Cellar/openssl@1.1/1.1.1d/lib /usr/local/Cellar/pkg-config/0.29.2/lib /usr/local/Cellar/python/3.7.6_1/lib /usr/local/Cellar/readline/8.0.4/lib /usr/local/Cellar/sqlite/3.31.1/lib /usr/local/Cellar/xz/5.2.4/lib
include paths are:  /usr/local/include /Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/include /Library/Developer/CommandLineTools/usr/include /usr/include /usr/local/Cellar/gdbm/1.18.1/include /usr/local/Cellar/openssl@1.1/1.1.1d/include /usr/local/Cellar/pkg-config/0.29.2/include /usr/local/Cellar/python/3.7.6_1/include /usr/local/Cellar/readline/8.0.4/include /usr/local/Cellar/sqlite/3.31.1/include /usr/local/Cellar/xz/5.2.4/include
using libm: /usr/lib/libm.dylib
using libpthread: /usr/lib/libpthread.dylib /usr/include/pthread.h
using libdl: /usr/lib/libdl.dylib /usr/include/dlfcn.h
using mman: /usr/include/sys/mman.h
***
*** i1401 Simulator being built with:
*** - compiler optimizations and no debugging support. Apple LLVM version 9.0.0.
*** - Per simulator tests will be run.
***
*** git commit id is 50266704ca4a9955366fa47a7becb050fb48860c+uncommitted-changes.
*** git commit time is 2020-06-14T18:50:48+0200.
***
gcc -std=c99 -U__STRICT_ANSI__  -O2 -fno-strict-overflow -finline-functions -DSIM_GIT_COMMIT_ID=50266704ca4a9955366fa47a7becb050fb48860c+uncommitted-changes -DSIM_GIT_COMMIT_TIME=2020-06-14T18:50:48+0200  -DSIM_COMPILER="Apple LLVM version 9.0.0" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_SYS_IOCTL -DHAVE_DLOPEN=dylib -DHAVE_UTIME -DHAVE_GLOB -DHAVE_SHM_OPEN  ./I1401/i1401_lp.c ./I1401/i1401_cpu.c ./I1401/i1401_iq.c ./I1401/i1401_cd.c ./I1401/i1401_mt.c ./I1401/i1401_dp.c ./I1401/i1401_sys.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -I ./I1401 -o BIN/i1401 -lm -lpthread -ldl  
BIN/i1401 RegisterSanityCheck  </dev/null 
 Running internal register sanity checks on IBM 1401 simulator.
*** Good Registers in IBM 1401 simulator.
$
```

- #### the simulator configuration file (or commands) which were used when the problem occurred.

```
# Fill memory with NOP instructions
d 0-50 '`N

# Break at 10, 11, 12... and show the simulated time 
br 10-20; show time

run 0
c
c
c
```

- #### the expected behavior and the actual behavior

Expected:
```

Breakpoint, IS: 10 (NOP)
Time:	100

Breakpoint, IS: 11 (NOP)
Time:	110

Breakpoint, IS: 12 (NOP)
Time:	120

Breakpoint, IS: 13 (NOP)
Time:	130
```

Actual:

```

Breakpoint, IS: 10 (NOP)
Time:	109
sim> c

Breakpoint, IS: 11 (NOP)
Time:	128
sim> c

Breakpoint, IS: 12 (NOP)
Time:	147
sim> c

Breakpoint, IS: 13 (NOP)
Time:	166
sim> 
```

**Note that each breakpoint is adding an additional 9 cycles.**

From the sleuthing I've done it appears that the first increment happens (as expected) in the `UPDATE_SIM_TIME` call at the beginning of `sim_process_event`. Then, after `sim_process_event` has returned to `sim_instr`, the call to `sim_brk_test` also results in `sim_time` being incremented. More specifically, `sim_brk_test` calls `sim_brk_fnd_ex`, which calls `sim_gtime`, which calls `UPDATE_SIM_TIME`, which modifies `sim_time`. 

That's as far as I've been able to go; it's not at all clear to me what needs to be changed to fix this properly.

I can work around the problem in `sim_instr` by ensuring that `sim_interval` is never negative when calling `sim_process_event`, as follows:
```
diff --git a/I1401/i1401_cpu.c b/I1401/i1401_cpu.c
index f54f4060..0281ba21 100644
--- a/I1401/i1401_cpu.c
+++ b/I1401/i1401_cpu.c
@@ -550,8 +550,12 @@ while (reason == 0) {                                   /* loop until halted */
 
     saved_IS = IS;                                      /* commit prev instr */
     if (sim_interval <= 0) {                            /* check clock queue */
-        if ((reason = sim_process_event ()))
-            break;
+        int32 pending_cycles = -sim_interval;
+        sim_interval = 0;
+        reason = sim_process_event ();
+        sim_interval -= pending_cycles;
+        if (reason)
+           break;
         }
 
     if (sim_brk_summ && sim_brk_test (IS, SWMASK ('E'))) { /* breakpoint? */
@@ -559,7 +563,7 @@ while (reason == 0) {                                   /* loop until halted */
         break;
         }
 
-    sim_interval = sim_interval - 1;
+    sim_interval = sim_interval - 10;
 
 /* Instruction fetch - 1401 fetch works as follows:
```

This does result in the expected behavior in my example above, but I wouldn't think this should be necessary. It's possible that this is specific to the way the 1401 simulator is coded, or that I'm doing something wrong, but it also seems possible that there's a bug here which might be affecting other simulators which use `sim_interval` to count instructions.

To be fair, I haven't tried running any of the other simulators, but I have looked at the source for some of the simulators which count cycles, and for the most part they appear to be calling `sim_process_event` and `sim_brk_test` in pretty much the same way as the 1401 simulator.

Please let me know if there's any more information I can provide to help debug this. Thanks!

**Comment by markpizz** [comment]
Thanks for finding this and you digging to analyze it and provide simplified test case.

> From the sleuthing I've done it appears that the first increment happens (as expected) in the UPDATE_SIM_TIME call at the beginning of sim_process_event. Then, after sim_process_event has returned to sim_instr, the call to sim_brk_test also results in sim_time being incremented. More specifically, sim_brk_test calls sim_brk_fnd_ex, which calls sim_gtime, which calls UPDATE_SIM_TIME, which modifies sim_time.

I've updated the processing logic to handle the negative sim_interval scenario.

As you observed, this problem would affect any simulator with variable updates to sim_interval.  These would most certainly be simulators that count cycles as well as the small handful of simulators which don't formally count cycles, but do adjust sim_interval by chunks from time to time.

Thanks again for your excellent problem report.

**Comment by markpizz** [comment]
Mark,

Please confirm that the latest code fixes the problem you found and if so, close this issue.

Thanks.

**Comment by wachsler** [comment]
Yes, thanks Mark, I'm seeing the expected behavior now. That was an impressively quick fix!

**Comment by markpizz** [comment]
Your detailed bug report and easy to demonstrate failure case played a big part.

Did you notice that the real fix was adding this line:

         sim_interval -= uptr->time;

to sim_process_event().

Such a small change with such a big consequence.

**Comment by wachsler** [comment]
I see that now that you pointed it out, but so far I only have a rudimentary understanding of how this all works, so heaven knows how long it would have taken me to figure out that that's where the root cause lay.

It makes sense to me that if `sim_process_event` was always called with `sim_interval == 0`, then you'd always hit the first item in the queue exactly, so `uptr->time` would already be zero, which is why the old code worked correctly in that case. OTOH if sim_interval is negative and you just clear `uptr->time`, now you've lost track of that extra time.

But I don't really understand the data structures involved well enough to know why the fix is to subtract `uptr->time` from `sim_interval` as opposed to, say, adding it. :-)

Anyway, thanks for unblocking me. I'll let you know if I run into any other quandries that I can't puzzle my way out of.

**Comment by markpizz** [comment]
> But I don't really understand the data structures involved well enough to know why the fix is to subtract uptr->time from sim_interval as opposed to, say, adding it. :-)

Well, UPDATE_SIM_TIME ends up making BOTH sim_interval and the event at the top of the queue->time the same as it adjusts sim_time.  Thus they are either both 0 or both the same negative number.  Adding two negative numbers gives you a larger negative number.  Subtracting them moves you back towards 0 where things otherwise would have been.

**Comment by wachsler** [comment]
Ah, sure enough. I was so focused on what `UPDATE_SIM_TIME` was doing to `sim_time` that I overlooked what it did with `sim_clock_queue->time`. It's clear to me now why this is correct on the first iteration, but it wasn't immediately obvious to me that it's correct on subsequent iterations.

I guess you only get a second iteration if sim_interval stays <= 0, which will only happen if the 2nd element in the queue also has a time which is <= 0. But in this case, they will be equal again, right? (Then again, I haven't checked to see what `sim_timer_activate_after` does, and I have no idea what `uptr->action` might be doing, so I could be way off-base here.)

Because if there really was an invariant that sim_interval and uptr->time are equal at the point where you're subtracting them, obviously you could just do `sim_interval = 0;` instead.

In any case, don't feel that you need to explain this all to me unless you want to. I don't urgently need to understand all the details of how SCP works. :-)

**Comment by markpizz** [comment]
> I guess you only get a second iteration if sim_interval stays <= 0, which will only happen if the 2nd element in the queue also has a time which is <= 0. But in this case, they will be equal again, right? 

True.

> (Then again, I haven't checked to see what sim_timer_activate_after does, and I have no idea what uptr->action might be doing, so I could be way off-base here.)

 sim_timer_activate_after() and many/most uptr->action() routines will indeed schedule events, all of which will be further into the future (hence deeper into the queue than we're currently working).
