### ISSUE TITLE
SIMH: Register Change Notification

### ISSUE THREAD

**Issue by deltecent** [simh/simh#891]
Is it possible for a UNIT to get notification of a register change from a `simh> d register` command?

It looks like the UNIT's `_deposit` function only gets called if there is a deposit to memory, not a register.

The MITS 88-2SIO adapter does not support changing the baud rate through software. My thought was to have a register that contains the baud rate. If the user wants to change the baud rate, they could deposit a new baud rate into the register. The UNIT, being notified of the change, could then call `tmxr_set_config_line` to set the new baud rate. I don't see a mechanism for a UNIT to know that a register has been changed other than keeping a copy of the value and comparing for a value change during `_svc`.

**Comment by markpizz** [comment]
Rather than changing the underlying semantics of the DEPOSIT command, the right way to do this is to add a MTAB entry to your device that takes the desired speed as an argument.  Your argument validation routine gets to validate it and then do anything you want with the result,
