### ISSUE TITLE
Understanding sim_debug output

### ISSUE THREAD

**Issue by deltecent** [simh/simh#892]
I am trying to understand how `sim_debug` output works. When starting the AltairZ80 sim, debug output seems to display at the time `sim_debug` is called. As soon as the `A>` prompt appears, the last `sim_debug` line doesn't print until `Ctrl-E` is entered:
```
Altair 8800 (Z80) simulator V4.0-0 Current        git commit id: f8d389af+uncommitted-changes
/Users/patrick/Library/Mobile Documents/com~apple~CloudDocs/simh/2sio.sim-13> set debug stdout
Debug output to "STDOUT"
Debug output to "STDOUT" at Tue Jun 16 13:51:05 2020
Altair 8800 (Z80) simulator V4.0-0 Current        git commit id: f8d389af+uncommitted-changes
256 bytes [1 page] loaded at ff00.
DBG(400)> M2SIO1 STATUS: new connection.
DBG(400)> M2SIO1 STATUS: DCD state changed to LOW.
DBG(3400)> M2SIO1 STATUS: CTS state changed to LOW.
DBG(129830)> M2SIO1 STATUS: MC6850 master reset.
DBG(129833)> M2SIO1 STATUS: RTS state changed to HIGH.


56K CP/M 2.2b v2.2
For Altair 8" Floppy

A><Ctrl-E>DBG(129833)> M2SIO1 STATUS: port configuration set to '9600-8N2'.

Simulation stopped, PC: 0CA73 (ANI 01h)
sim> 
```
Here's my startup:
```
sim> set debug stdout

sim> set m2sio1 enable
sim> set m2sio1 debug=status
sim> attach m2sio1 connect=/dev/cu.USA19H14411P1.1

sim> ATTACH DSK0 cpm22b22-56k.dsk
sim> LOAD dbl.bin FF00
sim> GO FF00
```
Does something need to be done in order to flush the debug output?

**Comment by markpizz** [comment]
Set HELP SET DEBUG.

In particular look at the -F switch

**Comment by deltecent** [comment]
```
-F
    The -F switch causes duplicate successive lines of debug NOT to be
    summarized to reduce repetative noise from the debug data stream.
```
So what this is saying is without `-F`, the last line of debug output will never be displayed until either another line is sent to debug that's different from the previous line or the simulator is stopped.

I would suggest changing this to work like `syslogd`, where the debug line is always displayed right away, and only subsequent duplicate lines are not displayed, but only for a specific amount of time, at which time the `same as above (X times)` is displayed and the process starts over. Without digging into the flags, most people would have no idea what's going on, especially people that are familiar with systems like `syslogd` where only the `same as above (X times)` output may be hidden, but for no more than a few seconds. Non-duplicate debug lines are always shown right away, not hidden in anticipation of a possible duplicate following it.

**Comment by markpizz** [comment]
Debugging simulator devices is not an activity normally done by Joe average simh user.  It is specifically done by simulator developers and/or by a Joe average user at the specific direction of a simulator developer so that the Joe average user can gather data which may be unique to their particular setup.

What we have now works for those who use it, including you, now that you've read and digested the documentation.  If you really feel the need for it to work differently, change it and submit a pull request.  If you go down this path, retain the functionality of -F to cause immediately output without regard to trying to reduce and count duplicates.

**Comment by markpizz** [comment]
If you decide to pursue the idea you suggested, get the first part you described working.  That will actually cover all interesting cases.  The only case it won't cover is an infinite loop emitting  the same debug output forever.  Realistic cases may spin on something for possibly thousands of times (hence the value of compressing these things out) but then go off and do something else that changes the output stream anyway.  The point of counting and only emitting a count hopefully avoids visible slowdowns of the running simulator.  Adding additional system calls to get and compare timestamps on each output, and to dynamically come back to force output flush later can get more expensive than it is worth.
