### ISSUE TITLE
DEC Alpha ini file 

### ISSUE THREAD

**Issue by akhribfarouk** [simh/simh#893]
**Please how to configure Alpha simh using alpha.ini file (Example)**

**Comment by markpizz** [comment]
The Alpha simulator is not a full system but merely something capable of executing instructions.  There are no devices implemented at this time.

**Comment by akhribfarouk** [comment]
Ah ok because when i read the Simh guide maybe it was not mentioned that Alpha emulator is not complete yet.. so thank you and i hope that the devices will be added soon, personally i think Simh best emulator :)

**Comment by markpizz** [comment]
Which simh guide are you referring do?  What specific mention did it make of the alpha simulator?

**Comment by akhribfarouk** [comment]
> Which simh guide are you referring do? What specific mention did it make of the alpha simulator?

i don't mean a guide literally but when you see the simh directories you can found Alpha directory wait for build so in my oppinion it must exclude the folder from the main directory or just mention that the Alpha station is still experimental .. that's all

***********************************************************************************
just quick question: do you know where to find the "AlphaVM_free for linux" ? 
***********************************************************************************

**Comment by markpizz** [comment]
```
make all
```
DOES NOT built the alpha pieces, while it DOES build all of the functional ones.  That's all you're going to get.  We're not going to reorganize the directory structure, sorry.

> just quick question: do you know where to find the "AlphaVM_free for linux" ?

I have no idea.
