### ISSUE TITLE
TMXR: Need help finding cause of output delay

### ISSUE THREAD

**Issue by deltecent** [simh/simh#894]
- #### Context
I am using the AltairZ80 simulator and attaching the M2SIO1 device to `*:8800`.

When I telnet into port 8800, characters are sent from the simulator to the remote at what appears to be approximately 9600bps.

If I terminate the connection and then reconnect, characters are sent slowly, at about 3-4 per second.

This does not happen if I remove `DEP CLOCK 2000` from the simulator's startup script.

I have been unable to figure out why this happens.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
sim> show version
Altair 8800 (Z80) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 7.5.0
        Simulator Compiled as C arch: x64 (Release Build) on Jun 18 2020 at 08:46:02
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        No RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux app-west.deltecent.com 4.15.0-1051-aws #53-Ubuntu SMP Wed Sep 18 13:35:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
        git commit id: 558c4c03
        git commit time: 2020-06-17T20:56:11-0700
```
- #### how you built the simulator or that you're using prebuilt binaries

```
patrick@app-west:~/simh$ make altairz80
lib paths are: /lib/ /lib/x86_64-linux-gnu/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/
include paths are:  /usr/lib/gcc/x86_64-linux-gnu/7/include /usr/local/include /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed /usr/include/x86_64-linux-gnu /usr/include
using libm: /usr/lib/x86_64-linux-gnu/libm.so
using librt: /usr/lib/x86_64-linux-gnu/librt.so
using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h
using semaphore: /usr/include/semaphore.h
using libdl: /usr/lib/x86_64-linux-gnu/libdl.so /usr/include/dlfcn.h
using mman: /usr/include/x86_64-linux-gnu/sys/mman.h
***
*** altairz80 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 7.5.0.
*** - Per simulator tests will be run.
***
*** git commit id is 558c4c03af67c9ab56edab6a83126110f967827d.
*** git commit time is 2020-06-17T20:56:11-0700.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -DSIM_GIT_COMMIT_ID=558c4c03af67c9ab56edab6a83126110f967827d -DSIM_GIT_COMMIT_TIME=2020-06-17T20:56:11-0700  -DSIM_COMPILER="GCC Version: 7.5.0" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_GLOB -DHAVE_SHM_OPEN  ./AltairZ80/altairz80_cpu.c ./AltairZ80/altairz80_cpu_nommu.c ./AltairZ80/altairz80_dsk.c ./AltairZ80/disasm.c ./AltairZ80/altairz80_sio.c ./AltairZ80/altairz80_sys.c ./AltairZ80/altairz80_hdsk.c ./AltairZ80/altairz80_net.c ./AltairZ80/s100_2sio.c ./AltairZ80/flashwriter2.c ./AltairZ80/i86_decode.c ./AltairZ80/i86_ops.c ./AltairZ80/i86_prim_ops.c ./AltairZ80/i8272.c ./AltairZ80/insnsd.c ./AltairZ80/altairz80_mhdsk.c ./AltairZ80/mfdc.c ./AltairZ80/n8vem.c ./AltairZ80/vfdhd.c ./AltairZ80/s100_disk1a.c ./AltairZ80/s100_disk2.c ./AltairZ80/s100_disk3.c ./AltairZ80/s100_fif.c ./AltairZ80/s100_mdriveh.c ./AltairZ80/s100_jadedd.c ./AltairZ80/s100_mdsa.c ./AltairZ80/s100_mdsad.c ./AltairZ80/s100_selchan.c ./AltairZ80/s100_ss1.c ./AltairZ80/s100_64fdc.c ./AltairZ80/s100_scp300f.c ./AltairZ80/s100_tarbell.c ./AltairZ80/wd179x.c ./AltairZ80/s100_hdc1001.c ./AltairZ80/s100_if3.c ./AltairZ80/s100_adcs6.c ./AltairZ80/m68kcpu.c ./AltairZ80/m68kdasm.c ./AltairZ80/m68kasm.c ./AltairZ80/m68kopac.c ./AltairZ80/m68kopdm.c ./AltairZ80/m68kopnz.c ./AltairZ80/m68kops.c ./AltairZ80/m68ksim.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -I ./AltairZ80 -DUSE_SIM_IMD -o BIN/altairz80 -lm -lrt -lpthread -ldl  
BIN/altairz80 RegisterSanityCheck  </dev/null 
 Running internal register sanity checks on Altair 8800 (Z80) simulator.
*** Good Registers in Altair 8800 (Z80) simulator.
```

- #### the simulator configuration file (or commands) which were used when the problem occurred.

```
set cpu 8080
dep clock 2000
#set debug stderr

set m2sio1 enable
set m2sio1 dtr
attach m2sio1 -U *:8800

attach dsk0 CPM22-8MB-56K.DSK
attach dsk1 DATA-8MB.DSK
attach dsk2 RCPMA.dsk
attach dsk3 BYE.dsk
load dbl.bin ff00
g ff00
```
- #### the expected behavior and the actual behavior

I would expect the behavior to remain the same after disconnect/reconnect of the telnet session.

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem
If it would be helpful, I can make and post a video link to YouTube.

**Comment by psco** [comment]
You are setting the clock speed to 2 MHz and this invokes a very precise mechanism to simulate this speed. This mechanism does its own time computation and probably gets in the way what you are doing. I strongly recommend to not use this simulator feature in your case, "D CLOCK 0".

**Comment by deltecent** [comment]
The problem is, much of the software I'm trying to run has timeouts (like idle timeouts) which don't work unless the clock speed is adjusted. I am trying to determine what is different between the first telnet connection and the second? It is also inconsistent. I added some additional sim_debug statements, and now I can connect and disconnect all I want without any change in TX speed. If I keep the same debug statements, but disable debug, the slow problem shows up again. I think if I can find out what's different between the first connection and the second connection, I will be able to find a solution to this problem.

**Comment by markpizz** [comment]
As I said when you started down this path, the timing that SCP does to support TMXR activities absolutely presumes that simulators DO NOT call sim_os_ms_sleep() during instruction execution.   A possibly useful approach (maybe) would be to rework how/why that sleep activity is being done and convert to using sim_idle().  If @psco is interested in this, I'll be available to support that.

**Comment by deltecent** [comment]
I get that. I just find all of the inconsistencies interesting, which leads me down the "it might be a bug" path. It seems that the behavior would be more consistent. For example, I wouldn't expect  simply closing and opening a connection to completely change the behavior of the simulator. If it works as expected on the first connection, why not the second... that's what I'm trying to figure out. Unfortunately, adding sim_debug statements also changes the behavior, mostly making the problem go away. I do like the idea of conforming the AltairZ80 simulator to the correct way of doing things. I think it would greatly enhance the functionality of the simulator if it could run at a simulated clock speed AND be able to use TMXR, as TMXR is really cool.

**Comment by psco** [comment]
I have no interest in these kind of changes and I am not convinced its even worth it. My objective is to run relevant, old software on contemporary hardware. The simulator is just a means to this end.

**Comment by markpizz** [comment]
Once again, there isn't anything to discuss here, given what has already been explained and warned about, I will have no further comment on this subject.
