### ISSUE TITLE
SIMH: DEVICE name length

### ISSUE THREAD

**Issue by deltecent** [simh/simh#901]
- #### Context
Is there a preferred DEVICE name length limit? Looking at `show_device` in `scp.c`, it prints out the device name followed by a TAB character. If a device name is longer than 7 characters, the columns will not align.

I previously added a `TARBELL` DEVICE, which is a single density disk controller. I now wish to add the double density version of the Tarbell disk controller. I was thinking of using `TARBELLD` to match the `MDSA` (single density) and `MDSAD` (double density) DEVICE name format, but that is 8 characters which would mess up the `SHOW DEV` alignment.

Would it be possible to change:
```
fprintf (st, "%s", sim_dname (dptr));      /* print dev name */
```
to something like:
```
fprintf (st, "%-*.*s", MAX_NAME, MAX_NAME, sim_dname (dptr));     /* print dev name */
```
Or is it not a problem if the columns do not line up and using an 8 character DEVICE name isn't an issue.

```
Altair 8800 (Z80) simulator V4.0-0 Current        git commit id: 54a102ca+uncommitted-changes
sim> show dev
Altair 8800 (Z80) simulator configuration

CPU
SIO	no extra port
SIMH
PTR
PTP
DSK	16 units
MHDSK	8 units
HDSK	I/O=0xFD-0xFD, 16 units
NET
ADCS6	disabled
HDC1001	disabled
DISK1A	disabled
DISK2	disabled
DISK3	disabled
SS1	disabled
MDRIVEH	disabled
SELCHAN	disabled
IF3	disabled
CROMFDC	disabled
FIF	disabled
MDSK	disabled
MDSA	disabled
MDSAD	disabled
SCP300F	disabled
JADEDD	disabled
TARBELL	disabled
TARBELLD	disabled
M2SIO0	disabled
M2SIO1	disabled
PMMI	disabled
FWII	disabled
VFDHD	disabled
N8VEM	disabled
I8272	disabled
WD179X	disabled
```

**Comment by markpizz** [comment]
Don't bother messing with trying to format this differently specifically in your device (unless you want to make the device name shorter).  Maybe I will change the SCP functionality to make things look nicer at some time.  This isn't a high priority problem.

**Comment by deltecent** [comment]
Sounds good. I wanted to make sure I wasn't breaking some unwritten rule for device name lengths.

**Comment by markpizz** [comment]
Please confirm that the latest code behaves reasonably when you've got long device names.

**Comment by deltecent** [comment]
"Reasonably" is subjective, but as I recall, it behaved just fine. I was initially adding a second Tarbell device "TARBELLD" for the double density controller, which was 8 characters. I changed my mind and added double density support to the existing "TARBELL" controller, so the issue become moot.
