### ISSUE TITLE
The blocks in RK05 disk images on PDP11 are written only as needed

### ISSUE THREAD

**Issue by gavineadie** [simh/simh#905]
Newly created RK05 disks, on PDP11, are zero bytes long.

    ATT RK0 EMTY.RK05

.. generates such an empty file.  This was a surprise since other hard disks generate images of an appropriate length for their type.

It turns out not to be a problem since `simh` expands the image as necessary, up to (approximately) the size of a real RK05 disk.  I say "approximately" because any unused space at the end of the disk is not present in the disk image and neither is the terminal `simh` signature block written at the end of the image.

This is, obviously, not really a problem .. as far as I have tested, everything works OK.  No action is called for unless the authors want to make note of this in the documentation.

*Further reading is only for some tricky details:*

The only trap might be for people moving RK05 images around.  I have a macOS program that checks for consistency of (and allows some operations on RT-11) disk images, and it was caught out.  In RT-11, after doing an `INIT` to put a directory on the disk, only enough blocks were written to create a directory with one empty file (and no blocks were written, obviously, for that non-existent file).

Strictly speaking, this is what I would expect .. the only blocks `simh` write to the image are those that RT-11 writes.  When RT-11 writes its first file on the disk, its blocks start some distance after the directory blocks, so `simh` has to, quick as a bunny because it doesn't accommodate sparse disk images, zero-fill and write out the previously unwritten blocks between the end of the (truncated) directory and the start of that first file.  Following from this, I assume any block absent in the image is read as 512 null bytes.

I'll have to go and read the `simh` code for this .. I'm guessing that RK05 disks are considered small enough to allow a write-though, in-memory image (RX and RY floppy disk are the same, at least they too are created empty).

**Comment by markpizz** [comment]
Opps.  I thought I had reworked all the VAX and PDP11 disks to use the new sim_disk APIs.  Clearly I had missed this one.  I will fix this next week.  

The behavior you are seeing is how things worked from the beginning of simh's PDP11 simulator for all disk types.  The other disks were migrated to the new sim_disk API to address and alert for the potential problems you seeing with disks being mixed up.

**Comment by gavineadie** [comment]
Oh!  OK .. I live and learn .. I don't know the `simh` history.  I've worked with Bernhard Baehr's PDP-8e and Hercules, the IBM System 360/370/.., simulator in the past.  I brought our old University time-sharing system back to life on Hercules!  Paleo-computing is fun!

**Comment by archivisth** [comment]
Historically, SimH always implemented (and V3.X still does implemented) exactly as much of a disk as is written with data. DEC disks that used bad block tables (RL, RP) are filled out by the bad block writing process. Otherwise, a newly created disk is 0 length and implicitly all 0s.

Storage devices that are buffered in memory (fixed head disks, floppy disks, DECtapes) maintain a "high water mark" and only write out that much data when the device is detached.

The RK was not buffered because when SimH was written (in 1993), memory and disks on PCs were quite small, and the simulators attempted to minimize resource usage.

A guiding principal for devices was that, where possible, they were unstructured byte/word streams of data. This allowed for straightforward transfer of device images between real machines and the simulators. As originally coded, magtapes were the only devices with metadata in the data stream.

**Comment by gavineadie** [comment]
Makes sense to me !!

**Comment by gavineadie** [comment]
Thanks, Mark.

**Comment by markpizz** [comment]
Please confirm that you get complete functionality using RK disk containers and that they are:
1) actually of the expected size of the original device
2) that they can't inadvertently be attached to any controller other than the RK
3) that if you've got an OS built file system on the disk, it is recognized as such when you ATTACH the container to an RKn unit.

Thanks.

**Comment by gavineadie** [comment]
My RT-11 file system utility says block count is correct (4872 = 203\*2\*12):
```
gavin@Ramsay-Mobile 11-40 % rt11
Start ..

rt11: mount EMTY.RK05
┌────────────────────────────────────────────────────────
│ Volume Image File: "EMTY.RK05"
│    System Version: V05
│             VolID: RT11A
│             Owner:
│             SysID: DECRT11A
│ 4872 blocks of 512 bytes +1 simh end block
└────────────────────────────────────────────────────────
```

An effort to attach to an RL02 controller fails:

```
/Volumes/RT-11/RT11_v57/11-40/simh.ini-10> ATT RL2 EMTY.RK05
RK05 container created by the PDP-11 simulator is incompatible with the RL device on the PDP-11 simulator
```

RT-11 sees files on the disk:

```
PDP-11 simulator V4.0-0 Current        git commit id: a73ab48c
/Volumes/RT-11/RT11_v57/11-40/simh.ini-11> ATT RK0 EMTY.RK05
RK0: 'EMTY.RK05' Contains RT11 partitions

RT-11FB  V05.07  

.dir rk0:
 10-Jul-2020
DATIME.MAC    23  20-Jun-2020    
 1 Files, 23 Blocks
 4739 Free blocks

.
```
I have one more number to check (total blocks - free blocks = 110).  That seems high for base blocks plus directory blocks but I need to attend supper (!) and will be back asap to verify.

**Comment by gavineadie** [comment]
We're OK. Base blocks plus directory blocks take up 38 blocks, the blocks devoted to files amount to another 4762 .. giving a total of 4800 blocks used by RT-11.  The physical disk has three extra cylinders on either side of the platter, that's 72 more blocks.  Documentation notes these 72 "spare" blocks are used by some systems because they are reliable but not, apparently, by RT-11.

**Comment by markpizz** [comment]
Looks good.
