### ISSUE TITLE
SIMH ignores function/editing keys

### ISSUE THREAD

**Issue by jgharston** [simh/simh#907]
I've been trying to get either SIMH or Ersatz-11 to connect via telnet to a terminal program, and have comprehensively failed, so I'm giving up and coming here to request an update to SIMH.

Currently, my PDP11 code can get function/editing keypresses when running on Ersatz-11, but it has a black-and-white console. I can get a colour console on SIMH as it uses the host's console, but can't get function/editing keypresses. After digging through the documentation to try and work out what I was doing wrong, I eventually came here and read the source. Which told me what I was trying to do was impossible.

So, can I request the following update to sim_console.c in function static t_stat sim_os_poll_kbd():

....
  if (rec.EventType == KEY_EVENT) {
    if (rec.Event.KeyEvent.bKeyDown) {
      if (0 == rec.Event.KeyEvent.uChar.UnicodeChar) {     /* Special Character/Keys? */
        if (rec.Event.KeyEvent.wVirtualKeyCode == VK_PAUSE) /* Pause/Break Key */
          c = sim_brk_char | SCPE_BREAK;
/*
INSERT HERE
Recognise function and editing keys and return appropriate keycodes to the caller.
Recommend VT220 sequences, ie <esc>[nnn;mmm~ for function keys and <esc>[mmm<char>
for editing keys. Ideally implement a 'SET TERM xxxx' configuration command.
 */
        else
          if (rec.Event.KeyEvent.wVirtualKeyCode == '2')  /* ^@ */
            c = 0;                                      /* return NUL */
      } else
        c = rec.Event.KeyEvent.uChar.AsciiChar;
    }
  }
....

**Comment by agn453** [comment]
I regularly use SIMH simulators by running them in an xterm window (on Raspberry Pis running Raspberry Pi OS [previously called Raspbian], on macOS with XQuartz), or on Windows 10 under Cygwin (32-bit).

xterm provides an excellent VT200-style (or later) emulation including keyboard mapping capabilities - and the function key escape sequences from keystrokes are passed correctly - e.g. using keypad editing with EDT (or EVE/TPU) under OpenVMS, or PDP-11 operating systems (RSTS/E, RSX-11M-Plus and RT-11).

Terminal programs like Kermit-95 also work albeit with some changes for the PF1..PF4 keys (mapped to F1..F4) when telnetting to a serial interface (like a DZ11 ports).

Which terminal program are you using?  It may be that it hasn't been set-up to send the correct keycodes for function keys.  Also the emulated serial port may need to be set to pass 8-bit characters and the emulated operating system needs to know the right terminal type.

**Comment by markpizz** [comment]
Hi @jgharston sorry to not have been available for the last week.  I've been buried in a move and rebuilding my email infrastructure.  Anyway, here we are now.

@agn453 comments are totally relevant.

Before discussing changes to code, please describe (with configuration file examples and version info (SHOW VERSION output)) what you have tried that doesn't provide useful functionality.

Be aware that embedding specific details of terminal emulation support in the simh code base was a strategy abandoned long ago.  Various Terminal emulators exist that can easily connect to the simh console or multiplexer ports to get things to work the ways they may have in days gone by.

A telnet session to the simh console device can be enabled with:
```
sim> SET CONSOLE TELNET=port
```
You then use a terminal emulator to connect to the simulator's console device and the experience you have will depend on the quality of the terminal emulator complete functionality.

**Comment by jgharston** [comment]
On 08-07-2020 17:03, Mark Pizzolato wrote:
> @agn453 [2] comments are totally relevant.
> 
> Before discussing changes to code, please describe (with configuration
> file examples and version info (SHOW VERSION output)) what you have
> tried that doesn't provide useful functionality.

The travails I've been though are discussed in the PDP newgroup:

https://groups.google.com/forum/#!topic/alt.sys.pdp11/ZvRZ95lhYzk

When I get back home I'll do some more testing again. I only ended up
digging into the source as I'd got to the point that it seemed the
only way to work out what SIMH was expecting me to do that I was
doing wrong - and then discovered that there was nothing I could do.

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by markpizz** [comment]
Your travails seem to be a problem that is unique to you.

I can readily connect PuTTY on a windows host to a running simulator without any problem, on either the console or device (DZ or VH) ports.

The particular specifics which the issue template here specifically asks for, as I did previously, is the output of SHOW VERSION from the "sim>" prompt on the simulator you are using.   If you're not using a very recent version, the please download one from https://github.com/simh/Win32-Development-Binaries/ . The SHOW VERSION output will give general info about your Windows version, but it wouldn't hurt to spell that out as well.

**Comment by jgharston** [comment]
Mark Pizzolato wrote:
> The particular specifics which the issue template here specifically
> asks for, as I did previously, is the output of SHOW VERSION from the
> "sim>" prompt on the simulator you are using. If you're not using a
> very recent version, the please download one from
> https://github.com/simh/Win32-Development-Binaries/

A couple of months ago I downloaded the latest version, checking it 
today
it was 3.9. Today I found there was a v4.000 20-Jun-2020 update, I 
downloaded
that and it works just as everybody desribes it should do.

I now have another problem, in that the latency of characters from the
keyboard via the telnet connection is such that my code can no longer
tell the difference between <esc> <nochar> and <esc> <char> ;)

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by markpizz** [comment]
For the third time.  I ask for the output produced by "SHOW VERSION" at the sim> prompt on your running environment.

Then, like in the original issue template, I ask for the precise configuration details you are using when you experience your problem.

What operating system are you running within the simulator?

What port on the simulated system are you using (Console, DZ, etc,?)

> I now have another problem, in that the latency of characters from the
keyboard via the telnet connection is such that my code can no longer
tell the difference between <esc> <nochar> and <esc> <char> ;)

What program is generating these characters?

Answering all the questions helps to get a useful answer.

**Comment by jgharston** [comment]
sim> show version
PDP-11 simulator V4.0-0 Current
     Simulator Framework Capabilities:
         32b data
         32b addresses
         Threaded Ethernet Packet transports:PCAP:NAT:UDP
         Idle/Throttling support is available
         Virtual Hard Disk (VHD) support
         RAW disk and CD/DVD ROM support
         Asynchronous I/O support (Lock free asynchronous event queue)
         Asynchronous Clock support
         FrontPanel API Version 12
     Host Platform:
         Compiler: Microsoft Visual C++ 15.00.30729.01
         Simulator Compiled as C arch: x86 (Release Build) on Jun  9 2020 
at 20:10:11
         Build Tool: simh-Visual-Studio-Project
         Memory Access: Little Endian
         Memory Pointer Size: 32 bits
         Large File (>2GB) support
         SDL Video support: SDL Version 2.0.10, PNG Version 1.6.37, zlib: 
1.2.11
         PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
         OS clock resolution: 1ms
         Time taken by msleep(1): 1ms
         Ethernet packet info: npcap or winpcap not installed
         OS: Microsoft Windows [Version 6.1.7601]
         Architecture: x86, Processors: 2
         Processor Id: x86 Family 6 Model 15 Stepping 13, GenuineIntel, 
Level: 6, Revision: 0f0d
         git commit id: 0912a927
         git commit time: 2020-06-09T20:07:41-07:00
sim>


Console is puTTY 0.74 (2020)


Started with:
rt11.bat
----8<----
cd %0\..
start c:\apps\internet\putty\putty.exe -telnet localhost 8023
start ..\pdp11\pdp11 rt11.ini
----8<----
rt11.ini
----8<----
set console telnet=8023
set console pchar=37777777777
set cpu 11/45
set rl0 RL02
attach rl0 ..\RT11\rtv53_rl.dsk
boot rl0
----8<----
Running RT11 v5.3


Started with:
unix7.bat
----8<----
cd %0\..
start c:\apps\internet\putty\putty.exe -telnet localhost 8023
start ..\pdp11\pdp11 unix7.ini
----8<----
unix7.ini
----8<----
set console telnet=8023
set console pchar=37777777777
set cpu 11/45
set rl0 RL02
attach rl0 unix_v7_rl.dsk
boot rl0
----8<----
Running Unix v7


-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by markpizz** [comment]
Thanks for the base information.

Now, given that, the problem you originally voiced seem to possibly be related to input data going towards the simulated systems.  In particular you've mentioned simple escape characters vs escape sequences.  I'd expect that the case of the simple escape character isn't a problem since most keyboards have specific ESC keys which essentially every terminal emulator will transmit directly.  The case of escape sequences is a completely different story and is an absolute case of how the terminal emulator program is configured to behave (i.e. what type of terminal it is emulating AND what keys on the physical keyboard you've got are mapped to the original keys that existed on the terminal type being emulated).

You can see precisely what data is moving into and out of the console telnet session by adding the following to your configurations:
```
sim> set debug -AF stdout
sim> set con-telnet debug=XMT;RET
```
You can influence the apparent "speed" of the console session via:
```
sim> set console speed=1200
```
You may want to explore the various HELP option available in the simulator:
```
sim> HELP SET CONSOLE
sim> HELP CON-TELNET 
```

Have fun.

**Comment by jgharston** [comment]
Mark Pizzolato wrote:
> You may want to explore the various HELP option available in the
> simulator:
> 
> sim> HELP SET CONSOLE
> sim> HELP CON-TELNET

Ah, that's a whole lot of useful information. I'd been digging around
trying to work out the right wording to get various system info.

Yesterday I'd tested on my laptop. Back home today and testing on my
main system, and it again doesn't work. This is with a fresh install
of puTTY and a fresh install of SIMH. With the same .bat and .ini
files, puTTY just bombs out with "Connection refused", with SIMH
waiting for a connection.

sim> show version
PDP-11 simulator V4.0-0 Current
     Simulator Framework Capabilities:
         32b data
         32b addresses
         Threaded Ethernet Packet transports:PCAP:NAT:UDP
         Idle/Throttling support is available
         Virtual Hard Disk (VHD) support
         RAW disk and CD/DVD ROM support
         Asynchronous I/O support (Lock free asynchronous event queue)
         Asynchronous Clock support
         FrontPanel API Version 12
     Host Platform:
         Compiler: Microsoft Visual C++ 15.00.30729.01
         Simulator Compiled as C arch: x86 (Release Build) on Jun  9 2020 
at 20:10:11
         Build Tool: simh-Visual-Studio-Project
         Memory Access: Little Endian
         Memory Pointer Size: 32 bits
         Large File (>2GB) support
         SDL Video support: SDL Version 2.0.10, PNG Version 1.6.37, zlib: 
1.2.11
         PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
         OS clock resolution: 1ms
         Time taken by msleep(1): 2ms
         Ethernet packet info: npcap or winpcap not installed
         OS: Microsoft Windows XP [Version 5.1.2600]
         Architecture: x86, Processors: 2
         Processor Id: x86 Family 16 Model 2 Stepping 3, AuthenticAMD, 
Level: 16, Revision: 0203
         git commit id: 0912a927
         git commit time: 2020-06-09T20:07:41-07:00
sim>


-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by markpizz** [comment]
Your bat files set you up for a race condition.  The Putty telnet are attempting to connect to a TCP port which may or may not have been setup in the simulator when Putty tries to connect.

Try this:
```
rt11.bat
----8<----
cd %0\..
start ..\pdp11\pdp11 rt11.ini
----8<----
rt11.ini
----8<----
set console telnet=8023
! start c:\apps\internet\putty\putty.exe -telnet localhost 8023
set console pchar=37777777777
set cpu 11/45
set rl0 RL02
attach rl0 ..\RT11\rtv53_rl.dsk
boot rl0
----8<----
Running RT11 v5.3
```

**Comment by jgharston** [comment]
Mark Pizzolato wrote:
> Try this:

That didn't work, but something else did.

I've just come back from my neighbour's, I tried using her Win8
system. I got exactly the same problem, waiting for connection,
connection refused.

I ran a second time, and Avast Antivirus popped up asking for
permission to allow the program to run. I said yes, and it worked
perfectly.

I've just come home, and have disabled Avast, and it works perfectly!

It looks like the documentation needs updating: "to use, disable any
virus protection beforehand".

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by markpizz** [comment]
Well, that's a feature of Avast. 
 
If you were using Windows Defender, when the simulator tried to setup the TCP port it is listening on, you usually will be prompted with an OS pop-up to allow it to do that.  This happens since attaching a generic TCP port specifically says that you want that port to be reachable on all interfaces on the computer.  Since you really don't want to reach into this computer from arbitrary places, and, in general it isn't a good idea to disable your defenses, when you merely intend to reach the simulator from within the same system, you could change your ```SET CONSOLE TELNET``` command to be:
```
sim> SET CONSOLE TELNET=localhost:8023
```
Windows Defender won't attempt to stop that, and your PuTTY connection would work fine.  This may also be true with Avast.

If you actually want to reach into the simulator's console from somewhere else on your network, you could configure Avast (or Windows Defender) to specifically allow just this program to establish the listen ports while still having your computer otherwise protected by the anti-virus/firewall protection.
