### ISSUE TITLE
string overflow in scp.c

### ISSUE THREAD

**Issue by gavineadie** [simh/simh#915]
Working with Richard on his emulators, I hit a problem.  In `scp.c` at line 13077, there's a sprintf call to print "same as above (n times)" with a variable `debug_line_count` holding the number of repetitions.  For reasons I don't know, but I'll work with Richard to help locate, `debug_line_count` reached tens of millions.  The result:

    (char [32]) countstr = "same as above (25864432 times)\r"

overflows 32 characters.  I'm changing that string to `char countstr[40];` and retesting, but the problem is pretty clearly that string overflow in `scp.c` ..

**Comment by markpizz** [comment]
Fixed now thanks!

**Comment by gavineadie** [comment]
Sorry, Mark, there's another usage a little before that one at line 13042 .. I haven't crashed at that one but just noticed it while reading the code.
