### ISSUE TITLE
80-col card formats [sim_card.c]

### ISSUE THREAD

**Issue by gavineadie** [simh/simh#919]
I may just be blind but there's a punch card format I'm not seeing documented.  Records start with "~raw" followed by 320 digits in the range 0..7 (octal?).  I could probably reverse engineer what's going on, or carefully read the "sim_card.c" code, where I see reference to this, but a definitive description would be better.

**Comment by rcornwell** [comment]
Updated documentation in the source to describe the formats for ~raw and other ~ record.

**Comment by gavineadie** [comment]
Appreciated.
