### ISSUE TITLE
little bug in sim_card.c

### ISSUE THREAD

**Issue by gavineadie** [simh/simh#920]
An easy little bug:

In sim_card.c, in  `sim_card_attach_help` [line 1356], the parameter `uptr` is null (called from `scp.c` [3178]) and then used in two places with `(uptr->flags & UNIT_RO)`

**Comment by rcornwell** [comment]
Try this Mark.

`diff --git a/sim_card.c b/sim_card.c
index fcb2af2..b61440f 100644
--- a/sim_card.c
+++ b/sim_card.c
@@ -1353,8 +1353,10 @@ sim_card_detach(UNIT * uptr)
 
 t_stat sim_card_attach_help(FILE *st, DEVICE *dptr, UNIT *uptr, int32 flag, const char *cptr)
 {
+    if (uptr == NULL)^M
+        uptr = dptr->units;^M
     fprintf (st, "%s Card %sAttach Help\n\n", dptr->name, (uptr->flags & UNIT_RO) ? "Reader " : "Punch ");
-    if (0 == (uptr-dptr->units)) {
+    if (0 == (dptr->units)) {^M
         if (dptr->numunits > 1) {
             uint32 i;
 
`
If it works just commit me as author.

**Comment by markpizz** [comment]
A more general solution covers readers and punches all done in one device is appropriate.
