### ISSUE TITLE
Unable to boot PANDA TOPS-20 disk image on SIMH pdp10-kl

### ISSUE THREAD

**Issue by patbarron** [simh/simh#928]
- #### Context

I am trying to use the RP07 disk image provided with the PANDA TOPS-20 distribution (from http://panda.trailing-edge.com) with SIMH pdp10-kl, rather than using the version of KLH10 that it comes bundled with.  When I try to do so, it fails in the following manner:

```
$ pdp10-kl

KL-10 simulator V4.0-0 Current        git commit id: d8004cca
sim> set cpu kl10b
sim> set cpu 2048K
sim> set rpa rh20
sim> set rpa0 rp07
sim> attach -f rpa0 dbd9 RH20.RP07.1
sim> set cty rsx20
sim> deposit sw 254200000147
sim> load boot.sav
Start addr=040000
sim> go

BOOT V11.0(315)

BOOT>/e

  ?BOOT: Can't find bootable structure

BOOT>
```

The "boot.sav" program loaded here is provided with the PANDA TOPS-20 distribution.  The file "RH20.RP07.1" is an RP07 disk image in DBD9 format.  The sequence above should have located a bootable structure on an RH20, and booted it.  I didn't necessarily expect this to fully work, but I am confused as to why it doesn't see this disk as containing a valid structure when using SIMH.  I turned on some debugging on the disk during one of my attempts, and that indicates that it does see the disk and is reading something off of it.  I could provide that if it would be useful, but it might be too large to attach to a Github issue.

The equivalent sequence does work as expected on KLH10 (it finds the disk on the first RH20 controller, loads the monitor from it, and starts the monitor).

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

The version of SIMH I am using is as indicated above.  

- #### how you built the simulator or that you're using prebuilt binaries

I built this using "make GCC=clang" on Fedora 32.  Unfortunately, I did not save the output of make.  I'm actually planning to rebuild it with GCC to see if that makes any difference.  I will report back if it does.

**Comment by larsbrinkhoff** [comment]
CC @kiteguy.

**Comment by larsbrinkhoff** [comment]
@patbarron, I keep forgetting which disk pack formats KLH10 supports, and which SIMH supports.

I'm pretty if you make KLH10 use its "dlw8" format, that is compatible with SIMH's default format.  I don't think I have tried KLH10's default format with SIMH's "dbd9" though it certainly seems it should work per the documentation.

**Comment by patbarron** [comment]
I tried rebuilding with GCC 10.2.1, no change in this behavior.

I can't rebuild the disk in a different format, since this disk image is prepackaged with the distribution and the distribution doesn't include all the things you'd need to rebuild the prepackaged disk image.  But in the KLH10 ini file, it attaches as:

devdef dsk0 rh0.0 rp    type=rp07 format=dbd9

I did try attaching in in SIMH format as well, and that produces the same result.

**Comment by patbarron** [comment]
Also, confirmed same behavior on current Windows development binary (KL-10 simulator V4.0-0 Current        git commit id: 0912a927) downloaded from Github.

**Comment by larsbrinkhoff** [comment]
From your reports, it would look like KLH10's dbd9 format isn't the same as SIMH's dbd9 format.  I really hope that's not the case!

I suggest the quickest way forward for you would be to write a 20-line program to convert the Panda disk image to something SIMH accepts.  It might take some trial and error, but if you hexdump the Panda image and some known working SIMH image it would be pretty clear what to do.

**Comment by rcornwell** [comment]
use:
set rpa0 rp07
at rpa0 -f dbd9 RH20.RP07.1

KL-10 simulator V4.0-0 Current        git commit id: dea1e9f2
/home/rich/pdp10/panda/run.ini-16> at ni tap:tap0
Eth: opened OS device tap0
/home/rich/pdp10/panda/run.ini-18> att lp20 -n prt.lst
LP20: creating new file: prt.lst
/home/rich/pdp10/panda/run.ini-21> att tty -U 2020
Listening on port 2020
Start addr=040000

sim> c

BOOT V11.0(315)

BOOT>TOPS20:

[BOOT: Loading] [OK]

 System structure not found.  What is its name? TOPS20:

[TOPS20 mounted]
Panda Distribution, PANDA TOPS-20 Monitor 7.1(21733)-4 Internet: Loading host names [OK]

System res
Date and time is: Friday, 25-September-2020 12:50AM
Why reload? sa
Run CHECKD? n
 DDMP: Started
[KNILDR: Loading microcode version 1(172) into Ethernet channel 0]


For some reason on pdp10-kl BOOT does not find the structure. I am not entirely sure what changes where made to the image to generate Panda. FE serial terminals and FE printer do not appear to work on Panda, but work fine on normal TOPS20.

**Comment by patbarron** [comment]
This is really weird ... if I build KLH10 (the version bundled with the PANDA distribution) on Fedora 32, it too has the same behavior with not being able to find the boot structure.  If I build the same sources on FreeBSD 12.0 using GCC, it works fine.  I'm at a loss...  But I also confirm that if I name the boot structure specifically, at least it does start to boot (then it has other problems, but that's a separate issue entirely...).

I don't know exactly what changes were done in the PANDA monitor, though I don't think any of them involved the FE.  I know there is a tweak to leverage the "idle device", and there's also support for MRC's blinky-lights virtual front panel display.  I'm sure he installed all of the DEC-provided fixes he had, and probably fixed some things on his own as well.  I'm personally interested in it not so much for any customizations to the monitor, but for all the third-party software that's preinstalled on it.

I'll go ahead and close this issue out, as @rcornwell's observation sent me down the right path to at least somewhat figure out what's going on.  If I run into any other problems, I'll open separate issues.

**Comment by rcornwell** [comment]
If you find bugs with my simulators it is best to post to my sims repo first. I prefer all fixes to my simulators to go though my repo first.

**Comment by patbarron** [comment]
Can you give me a link to that?  I'll be happy to open issues in wherever the most appropriate place is.

**Comment by Rhialto** [comment]
On Fri 25 Sep 2020 at 14:35:35 -0700, Pat Barron wrote:
> This is really weird ... if I build KLH10 (the version bundled with
> the PANDA distribution) on Fedora 32, it too has the same behavior
> with not being able to find the boot structure.  If I build the same
> sources on FreeBSD 12.0 using GCC, it works fine.  I'm at a loss...  

The bundled version of KLH is 2.0a I think? That's very old. There have
been patches to avoid "compiler bugs" (read: the C code had undefined
behaviour). The latest (and maintained, somewhat at least) version can
be found at https://github.com/PDP-10/klh10/ .

-Olaf.
-- 
Olaf 'Rhialto' Seibert -- rhialto at falu dot nl
___  Anyone who is capable of getting themselves made President should on
\X/  no account be allowed to do the job.       --Douglas Adams, "THGTTG"

**Comment by patbarron** [comment]
I'm not sure what I did with the Linux system before, but I have rebuilt KLH10 (yes, the bundled version that comes with the Panda distribution) using GCC, and now it works....

I was looking at the updated version in the repo, but I was under the impression that MRC had made changes to the version of KLH10 bundled with the distribution to support his monitor.  But I will try that too and see what happens.

As to my original point - I tried using the disk converter that comes with KLH10 to convert the bundled RP07 image from DBD9 format to SIMH format, and I got the same behavior when I tried to boot the converted image under SIMH PDP10-KL.  So there's definitely something odd going on here, especially since I know that SIMH PDP10-KL boots and runs TOPS-20 V7, so I wouldn't think there'd be any problem with the actual emulation - just possibly that the two emulators don't agree on what the disk formats are supposed to look like.

**Comment by R-Voorhorst** [comment]
L.S.

 

When trying to do some testing on pdp10-kl, I tried and tested the Tops10 version which runs successfully on Klh10.

That was before dbd9 support, so I created a dbd9 to simh format convertor and translated working Tops10 images for Klh10 to Simh and booted them with Pdp10-kl.

With a generated boot program loaded into the Pdp10-kl sim, there was no problem with booting and the Klh10 monitor image booted correctly.

Due to other issues, I never tested the Tops20 Panda variant as it was a step to far at the moment.

 

Best regards,

 

R.V.

**Comment by jguillaumes** [comment]
MRC did indeed modify the monitor to work with the KLH10 ‘idling device’. I’m not sure if that makes the Panda monitor unrunnable in other simulators.

Jordi Guillaumes Pons

**Comment by patbarron** [comment]
It also looks like there are some additional instructions added for the Panda monitor, but I don't know if they're in the normal KLH10 package, or if MRC put them in KLH10 himself as a custom addition, or if their absence would prevent the monitor from working.

However, this problem is before the monitor even loads - "BOOT.SAV" (entirely DEC code) doesn't recognize the boot structure when I try to use the RP07 image supplied with the Panda distribution in SIMH PDP10-KL.

**Comment by rcornwell** [comment]
The idle patches should work on other simulators. But the fact that I can't enable the FE printer or terminal lines tells me that there was changes. Note KLH10 does not support these so it is very likely that they were removed from the system. I also can't see any place in the KLH10 code that would cause BOOT.SAV to see TOPS20 as structure, so I don't know why it is needed to be typed in on PDP10-KL.
