### ISSUE TITLE
"help topic" output goes to local console, will not (immediately) display on remote console

### ISSUE THREAD

**Issue by jwbrase** [simh/simh#931]
If I start up a remote console (master mode or not) and type:

`help`

The output of help goes to the remote console.

However, if I type:

`help topic`

where "topic" is any valid help topic, the help entry for that command is output to the local console (that is, whatever terminal simh was started on), along with a prompt for a subtopic, and the remote console does not display anything or respond to input (it does, however, buffer whatever input it receives). 

The help system continues to operate normally on the local console until the user backs out of the help hierarchy to the sim> prompt, at which point the remote console then displays the help item that was requested, without any prompt for a subtopic. If any input was buffered while the remote console was unresponsive, it is now processed, and executed up to the last line feed. 

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

I have encountered the issue on two builds of the pdp11 simulator, and one build of the vax simulator. I have not yet tried other simulators, but assume that they are likewise affected.

I first encountered the issue on a pdp11 simulator using the realcons patch for the PIDP-11 project. The SHOW VERSION output is as follows:

```
PDP-11 simulator V4.0-0 Current  REALCONS build Sep 18 2020
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 5.4.0 20160609
        Simulator Compiled as C arch: ARM (Release Build) on Sep 18 2020 at 18:07:41
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.4
        No RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux jwb-pidp-11 4.1.10-v7+ #821 SMP PREEMPT Sat Oct 10 00:16:28 BST 2015 armv7l armv7l armv7l GNU/Linux
        git commit time: $Format:%aI$
```

Because the above simulator uses modified simh code, I then tried git-pulling the latest simh code on my desktop, and ran "make pdp11", generating a simulator that also exhibits the issue, and does not use modified sources. SHOW VERSION output:

```
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 8.4.0
        Simulator Compiled as C arch: x64 (Release Build) on Sep 27 2020 at 03:14:03
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.2, PNG Version 1.6.34, zlib: 1.2.11
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: libpcap version 1.8.1
        OS: Linux orthanc 5.4.0-49-generic #53~18.04.1-Ubuntu SMP Mon Sep 21 14:12:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
        git commit id: 83d35a26
        git commit time: 2020-09-26T17:57:17-0400
```

Lastly, to make sure that the issue isn't limited to just the pdp11 simulator, I ran an older copy of the VAX simulator that I already had installed as /usr/bin/vax. Its SHOW VERSION output is: 

```
MicroVAX 3900 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 8.1.0
        Simulator Compiled as C arch: x64 (Release Build) on Apr 11 2019 at 00:23:01
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.2
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux orthanc 5.4.0-49-generic #53~18.04.1-Ubuntu SMP Mon Sep 21 14:12:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
        git commit id: dfd011a9
        git commit time: 2019-04-10T15:09:47-0700
```

- #### how you built the simulator or that you're using prebuilt binaries

The pdp11 simulator that I built fresh on my desktop to confirm the issue (commit ID: 83d35a26) was generated with

```
$ git pull
$ make -j4 pdp11
```

The make output is:

```
lib paths are: /lib/ /lib/i386-linux-gnu/ /lib/x86_64-linux-gnu/ /lib32/ /libx32/ /usr/lib/ /usr/lib/i386-linux-gnu/ /usr/lib/i386-linux-gnu/sse2/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/ /usr/lib32/ /usr/libx32/ /usr/local/lib/
include paths are:  /usr/lib/gcc/x86_64-linux-gnu/8/include /usr/local/include /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed /usr/include/x86_64-linux-gnu /usr/include
using libm: /usr/lib/x86_64-linux-gnu/libm.so
using librt: /usr/lib/x86_64-linux-gnu/librt.so
using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h
using libpcre: /usr/lib/x86_64-linux-gnu/libpcre.so /usr/include/pcre.h
using semaphore: /usr/include/semaphore.h
using libdl: /usr/lib/x86_64-linux-gnu/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib/x86_64-linux-gnu/libpng.so /usr/include/png.h
using zlib: /usr/lib/x86_64-linux-gnu/libz.so /usr/include/zlib.h
using mman: /usr/include/x86_64-linux-gnu/sys/mman.h
using libSDL2: /usr/local/include/SDL2/SDL.h
using libpcap: /usr/include/pcap.h
using libvdeplug: /usr/lib/libvdeplug.so /usr/include/libvdeplug.h
***
*** pdp11 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 8.4.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
*** - Per simulator tests will be run.
***
*** git commit id is 83d35a26aa5af6c71b3e8ce52d10e1337678318e.
*** git commit time is 2020-09-26T17:57:17-0400.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -DSIM_GIT_COMMIT_ID=83d35a26aa5af6c71b3e8ce52d10e1337678318e -DSIM_GIT_COMMIT_TIME=2020-09-26T17:57:17-0400  -DSIM_COMPILER="GCC Version: 8.4.0" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCRE_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./PDP11/pdp11_fp.c ./PDP11/pdp11_cpu.c ./PDP11/pdp11_dz.c ./PDP11/pdp11_cis.c ./PDP11/pdp11_lp.c ./PDP11/pdp11_rk.c ./PDP11/pdp11_rl.c ./PDP11/pdp11_rp.c ./PDP11/pdp11_rx.c ./PDP11/pdp11_stddev.c ./PDP11/pdp11_sys.c ./PDP11/pdp11_tc.c ./PDP11/pdp11_tm.c ./PDP11/pdp11_ts.c ./PDP11/pdp11_io.c ./PDP11/pdp11_rq.c ./PDP11/pdp11_tq.c ./PDP11/pdp11_pclk.c ./PDP11/pdp11_ry.c ./PDP11/pdp11_pt.c ./PDP11/pdp11_hk.c ./PDP11/pdp11_xq.c ./PDP11/pdp11_xu.c ./PDP11/pdp11_vh.c ./PDP11/pdp11_rh.c ./PDP11/pdp11_tu.c ./PDP11/pdp11_cpumod.c ./PDP11/pdp11_cr.c ./PDP11/pdp11_rf.c ./PDP11/pdp11_dl.c ./PDP11/pdp11_ta.c ./PDP11/pdp11_rc.c ./PDP11/pdp11_kg.c ./PDP11/pdp11_ke.c ./PDP11/pdp11_dc.c ./PDP11/pdp11_dmc.c ./PDP11/pdp11_kmc.c ./PDP11/pdp11_dup.c ./PDP11/pdp11_rs.c ./PDP11/pdp11_vt.c ./PDP11/pdp11_td.c ./PDP11/pdp11_io_lib.c ./PDP11/pdp11_rom.c ./PDP11/pdp11_ch.c ./display/display.c ./display/sim_ws.c ./display/vt11.c ./PDP11/pdp11_ng.c ./PDP11/pdp11_daz.c ./display/ng.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -DVM_PDP11 -I ./PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_VDE_NETWORK -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -DUSE_DISPLAY -DHAVE_LIBSDL -DUSE_SIM_VIDEO `/usr/local/bin/sdl2-config --cflags` `/usr/local/bin/sdl2-config --libs` -o BIN/pdp11 -lm -lrt -lpthread -lpcre -ldl -lpng -lz -lvdeplug -Wl,-R,/usr/lib/ -L/usr/lib/ 
BIN/pdp11 RegisterSanityCheck  </dev/null 
 Running internal register sanity checks on PDP-11 simulator.
*** Good Registers in PDP-11 simulator.
```

- #### the simulator configuration file (or commands) which were used when the problem occurred.

No configuration file was used. The commands run were:

```
set remote telnet=2048
set console telnet=2049
set remote master
```

Once attached to the master console, the issue can be triggered with:

`help go`

- #### the expected behavior and the actual behavior

Expected behavior: Help information output once to the remote console when "help topic" is invoked from the remote console, or "help" rejected as an invalid command for the remote console. It does not matter to me if this is done in the hierarchical or non-hierarchical help mode.

Actual behavior: When "help topic" is invoked from the remote console, the local console displays the help information in hierarchical help mode, and the remote console produces no output until the user backs out of the help hierarchy on the local console, at which point the help information is displayed again, this time on the remote console in non-hierarchical mode.

**Comment by markpizz** [comment]
Thank you for reporting this problem.  This actually worked correctly in the initial implementation of remote console functionality.  Subsequent additions to remote console introduced this problem.

Additionally, while exploring the problem another possibly long standing issues was found and fixed.  Thanks again.

**Comment by jwbrase** [comment]
Pulling the latest code, the issue with simh printing to and waiting for input on the local console is now resolved, but now the help text gets printed twice on the remote console. (It had previously been reprinted to the remote console once the local console backed out of the help hierarchy). But the double-print is fairly minor compared to the original issue.

**Comment by markpizz** [comment]
As it turns out, the dual help output of phenomena only happened in some simulators.  The distinction being those which have all simh REG variables in single memory cells vs pieces of the same cell.  For example, the VAX PSL register is comprised of several internal variables that get extracted from or combined combined to a REG variable when instruction execution starts or returns to the sim> prompt.  In any case, both scenarios now behave as expected.

**Comment by jwbrase** [comment]
I've pulled the latest code and agree that everything looks to have been fixed.
