### ISSUE TITLE
SIMH build doesn't find proper OS libraries with Xcode 12 on macOS 11

### ISSUE THREAD

**Issue by eschaton** [simh/simh#934]
When building with the latest Xcode 12.2 beta on the latest macOS 11 beta, SIMH cannot find libraries because it use a naïve means of looking for them.

For background, macOS uses a prebuilt shared library cache and as of macOS 11 *system libraries are not present elsewhere in the filesystem*. Calling `dlopen()` with a path like `/usr/lib/libpcap.dylib` will still load them because `dyld` goes through the cache, but `stat()` will not find a library at that path because there's no longer a library (or a symlink to a versioned library) there.

Similarly, Xcode switched a couple releases ago to "text-based dylibs" where instead of `.dylib` stubs in the SDK, libraries are represented by a YAML `.tbd` file in the SDK. So just searching the SDK for `libpcap.dylib` won't find it either.

**Comment by eschaton** [comment]
All of this is really a side-effect of SIMH having an incredibly convoluted procedural build system. If it used a more normal makefile, or if it used CMake or even autotools, this would be addressable in a straightforward fashion. Instead I have to ask for someone else to look into it, an issue I brought up in #697.

**Comment by markpizz** [comment]
If you are writing a new simulator, then you should absolutely use whatever toolchain you prefer that makes your development process easier during that active simulator development.

Once you simulator is ready to be added to the pool of some 80+ simulators, it should be easy enough to add the details needed to build your simulator to the base simh makefile.  

On MaxOS, the simh makefile sanely finds its dependencies based on dependent packages provided by either HomeBrew or MacPorts.  These are tested continuously (with TravisCI) and work reliably for anyone who attempts to build either a single simulator or the whole pile.  If you have different goals, feel free to do as you please, but what's there now, in fact, works fine for the generic community of users.  

The VAST majority of folks who touch simh simulators are very interested in actually using the simulators and are absolutely not involved in active development of new simulators.  Therefore, build once and then use works out just fine for that VAST population.

If you are actually interested in building a new simulator, that is fabulous.  Please provide some details about what you're looking at.

**Comment by eschaton** [comment]
It’s macOS, not “MaxOS.” What I’m reporting here is that the SIMH makefile *does not* find these libraries sanely on macOS 11 with Xcode 12, regardless of whether you’re using MacPorts, Homebrew, or just the stock operating system, because of changes to how SDKs and the operating system are deployed. The way SIMH’s makefile works here *will* need to be adjusted, I’m giving you a heads up about that.

Also, please stop treating constructive criticism of SIMH’s procedural-makefile build system as a personal attack. I get that you don’t want to change it. That doesn’t mean it’s good, or that it’s not *extremely* different than most other projects. You’re not the only person who has been working in this industry for a long time, across a lot of projects, across a lot of platforms.

**Comment by markpizz** [comment]
Thanks for the spelling correction.

Meanwhile, on my test MacMini which is running macOS Catalina 10.15.7 and has the latest Xcode (updated yesterday 12.0.1).  I open a terminal window, clone the github simh repository, and cd to the clone target directory and type "make pdp11" which is the simplest case of a simulator which depends on all of the potential simh external libraries.  This is what is produced:
```
marks-mac-mini:simh mark$ make pdp11
lib paths are: /usr/lib /usr/local/Cellar/freetype/2.10.1/lib /usr/local/Cellar/gdb/8.3/lib /usr/local/Cellar/libpng/1.6.37/lib /usr/local/Cellar/pcre/8.43/lib /usr/local/Cellar/sdl2/2.0.10/lib /usr/local/Cellar/sdl2/2.0.9_1/lib /usr/local/Cellar/sdl2_ttf/2.0.15/lib /usr/local/Cellar/vde/2.3.2/lib /usr/local/Cellar/zlib/1.2.11/lib
include paths are:  /usr/local/include /Library/Developer/CommandLineTools/usr/lib/clang/11.0.3/include /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include /Library/Developer/CommandLineTools/usr/include /usr/local/Cellar/freetype/2.10.1/include /usr/local/Cellar/gdb/8.3/include /usr/local/Cellar/libpng/1.6.37/include /usr/local/Cellar/pcre/8.43/include /usr/local/Cellar/sdl2/2.0.10/include /usr/local/Cellar/sdl2/2.0.9_1/include /usr/local/Cellar/sdl2_ttf/2.0.15/include /usr/local/Cellar/vde/2.3.2/include /usr/local/Cellar/zlib/1.2.11/include
using libm: /usr/lib/libm.dylib
using libpthread: /usr/lib/libpthread.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h
using libpcre: /usr/lib/libpcre.dylib /usr/local/include/pcre.h
using libdl: /usr/lib/libdl.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/dlfcn.h
using libpng: /usr/local/Cellar/libpng/1.6.37/lib/libpng.dylib /usr/local/include/png.h
using zlib: /usr/lib/libz.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/zlib.h
using mman: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/mman.h
using libSDL2: /usr/local/include/SDL2/SDL.h
using libpcap: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pcap.h
using libvdeplug: /usr/local/Cellar/vde/2.3.2/lib/libvdeplug.dylib /usr/local/include/libvdeplug.h
***
*** pdp11 Simulator being built with:
*** - compiler optimizations and no debugging support. Apple clang version 11.0.3.
*** - dynamic networking support using OSX provided libpcap components.
*** - Local LAN packet transports: PCAP VDE NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
*** - Per simulator tests will be run.
***
*** git commit id is 4db4f90429f254c441818245baf473ecd55886ae.
*** git commit time is 2020-10-09T05:10:34-0700.
***
gcc -std=c99 -U__STRICT_ANSI__  -O2 -fno-strict-overflow -finline-functions -DSIM_GIT_COMMIT_ID=4db4f90429f254c441818245baf473ecd55886ae -DSIM_GIT_COMMIT_TIME=2020-10-09T05:10:34-0700  -DSIM_COMPILER="Apple clang version 11.0.3" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCRE_H -DHAVE_SYS_IOCTL -DHAVE_DLOPEN=dylib -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./PDP11/pdp11_fp.c ./PDP11/pdp11_cpu.c ./PDP11/pdp11_dz.c ./PDP11/pdp11_cis.c ./PDP11/pdp11_lp.c ./PDP11/pdp11_rk.c ./PDP11/pdp11_rl.c ./PDP11/pdp11_rp.c ./PDP11/pdp11_rx.c ./PDP11/pdp11_stddev.c ./PDP11/pdp11_sys.c ./PDP11/pdp11_tc.c ./PDP11/pdp11_tm.c ./PDP11/pdp11_ts.c ./PDP11/pdp11_io.c ./PDP11/pdp11_rq.c ./PDP11/pdp11_tq.c ./PDP11/pdp11_pclk.c ./PDP11/pdp11_ry.c ./PDP11/pdp11_pt.c ./PDP11/pdp11_hk.c ./PDP11/pdp11_xq.c ./PDP11/pdp11_xu.c ./PDP11/pdp11_vh.c ./PDP11/pdp11_rh.c ./PDP11/pdp11_tu.c ./PDP11/pdp11_cpumod.c ./PDP11/pdp11_cr.c ./PDP11/pdp11_rf.c ./PDP11/pdp11_dl.c ./PDP11/pdp11_ta.c ./PDP11/pdp11_rc.c ./PDP11/pdp11_kg.c ./PDP11/pdp11_ke.c ./PDP11/pdp11_dc.c ./PDP11/pdp11_dmc.c ./PDP11/pdp11_kmc.c ./PDP11/pdp11_dup.c ./PDP11/pdp11_rs.c ./PDP11/pdp11_vt.c ./PDP11/pdp11_td.c ./PDP11/pdp11_io_lib.c ./PDP11/pdp11_rom.c ./PDP11/pdp11_ch.c ./display/display.c ./display/sim_ws.c ./display/vt11.c ./PDP11/pdp11_ng.c ./PDP11/pdp11_daz.c ./display/ng.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -DVM_PDP11 -I ./PDP11 -DHAVE_PCAP_NETWORK -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_VDE_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -DUSE_DISPLAY -DHAVE_LIBSDL -DUSE_SIM_VIDEO `/usr/local/Cellar/sdl2/2.0.10/bin/sdl2-config --cflags` -DSDL_MAIN_AVAILABLE `/usr/local/Cellar/sdl2/2.0.10/bin/sdl2-config --libs` -o BIN/pdp11 -lm -lpthread -lpcre -ldl -lpng -lz -lvdeplug -L/usr/local/Cellar/vde/2.3.2/lib/ 
BIN/pdp11 RegisterSanityCheck  </dev/null 
 Running internal register sanity checks on PDP-11 simulator.
*** Good Registers in PDP-11 simulator.
marks-mac-mini:~ mark$ brew list
freetype	libpng		sdl2		vde
gdb		pcre		sdl2_ttf	zlib

```

Please notice that this is precisely how things are expected to work and we do not see any problems with the latest released operating system and tool chain.  The simulator runs as expected just fine.  If something about this doesn't work, I absolutely welcome many forms of criticism.  If you're running pre-release OS or tool chain versions, then we make no guarantee about the results until the release to the masses versions are available.  Once that release happens, the dependent packages will likely change and we'll need to check things out then.  If you have specific suggestions about changes to the makefile build on macOS, we'll welcome them as the problem arises.

**Comment by eschaton** [comment]
That's using the (unnecessary) command line tools package to build, rather than Xcode. If you `export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer` (substituting the path to your Xcode 12 installation) it will build using the latest tools and SDK from within Xcode.

It'll still build on macOS 10.15 since that still has the OS shared libraries in the filesystem so the makefile's checks for them will pass. Using the latest Xcode 12.2 beta on the latest macOS 11 beta, however, results in this failure to find `libpcap`:

```
$ make pdp11
lib paths are: /usr/lib
include paths are:  /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
using mman: /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/mman.h
*** Info ***
*** Info *** The simulator you are building could provide more
*** Info *** functionality if video support were available on your system.
*** Info *** Install the MacPorts libSDL2 package to provide this
*** Info *** functionality for your OS X system:
*** Info ***       # port install libsdl2 libpng zlib
*** Info ***
*** Info ***
*** Info *** Simulators on your OSX platform can also be built with
*** Info *** extended LAN Ethernet networking support by using VDE Ethernet.
*** Info ***
*** Info *** To build simulator(s) with extended networking support you
*** Info *** should install the MacPorts vde2 package to provide this
*** Info *** functionality for your OS X system:
*** Info ***       # port install vde2
*** Info ***
*** Warning ***
*** Warning *** pdp11 Simulator is being built WITHOUT LAN networking support
*** Warning ***
*** Warning *** To build simulator(s) with networking support you should read
*** Warning *** 0readme_ethernet.txt and follow the instructions regarding the
*** Warning *** needed libpcap components for your Darwin platform
*** Warning ***
***
*** pdp11 Simulator being built with:
*** - compiler optimizations and no debugging support. Apple clang version 12.0.0.
*** - WITHOUT Local LAN networking support.
*** - Local LAN packet transports: PCAP NAT(SLiRP)
*** - Per simulator tests will be run.
***
*** git commit id is 91bce50a5fa51d7bb4e7be7244626c34a9f8e245.
*** git commit time is 2020-10-07T09:15:35-0700.
***
gcc -std=c99 -U__STRICT_ANSI__  -O2 -fno-strict-overflow -finline-functions -DSIM_GIT_COMMIT_ID=91bce50a5fa51d7bb4e7be7244626c34a9f8e245 -DSIM_GIT_COMMIT_TIME=2020-10-07T09:15:35-0700  -DSIM_COMPILER="Apple clang version 12.0.0" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DHAVE_SYS_IOCTL -DHAVE_UTIME -DHAVE_GLOB -DHAVE_SHM_OPEN  ./PDP11/pdp11_fp.c ./PDP11/pdp11_cpu.c ./PDP11/pdp11_dz.c ./PDP11/pdp11_cis.c ./PDP11/pdp11_lp.c ./PDP11/pdp11_rk.c ./PDP11/pdp11_rl.c ./PDP11/pdp11_rp.c ./PDP11/pdp11_rx.c ./PDP11/pdp11_stddev.c ./PDP11/pdp11_sys.c ./PDP11/pdp11_tc.c ./PDP11/pdp11_tm.c ./PDP11/pdp11_ts.c ./PDP11/pdp11_io.c ./PDP11/pdp11_rq.c ./PDP11/pdp11_tq.c ./PDP11/pdp11_pclk.c ./PDP11/pdp11_ry.c ./PDP11/pdp11_pt.c ./PDP11/pdp11_hk.c ./PDP11/pdp11_xq.c ./PDP11/pdp11_xu.c ./PDP11/pdp11_vh.c ./PDP11/pdp11_rh.c ./PDP11/pdp11_tu.c ./PDP11/pdp11_cpumod.c ./PDP11/pdp11_cr.c ./PDP11/pdp11_rf.c ./PDP11/pdp11_dl.c ./PDP11/pdp11_ta.c ./PDP11/pdp11_rc.c ./PDP11/pdp11_kg.c ./PDP11/pdp11_ke.c ./PDP11/pdp11_dc.c ./PDP11/pdp11_dmc.c ./PDP11/pdp11_kmc.c ./PDP11/pdp11_dup.c ./PDP11/pdp11_rs.c ./PDP11/pdp11_vt.c ./PDP11/pdp11_td.c ./PDP11/pdp11_io_lib.c ./PDP11/pdp11_rom.c ./PDP11/pdp11_ch.c   ./PDP11/pdp11_ng.c ./PDP11/pdp11_daz.c  ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -DVM_PDP11 -I ./PDP11 -DHAVE_PCAP_NETWORK -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ -DBPF_CONST_STRING -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -DUSE_NETWORK  -o BIN/pdp11   
Undefined symbols for architecture x86_64:
  "_pcap_close", referenced from:
      __eth_devices in sim_ether-6ec4b9.o
      _eth_close in sim_ether-6ec4b9.o
      __eth_error in sim_ether-6ec4b9.o
  "_pcap_compile", referenced from:
      __eth_open_port in sim_ether-6ec4b9.o
      _eth_filter_hash in sim_ether-6ec4b9.o
      _sim_ether_test in sim_ether-6ec4b9.o
  "_pcap_datalink", referenced from:
      __eth_devices in sim_ether-6ec4b9.o
  "_pcap_dispatch", referenced from:
      _eth_read in sim_ether-6ec4b9.o
  "_pcap_fileno", referenced from:
      __eth_open_port in sim_ether-6ec4b9.o
  "_pcap_findalldevs", referenced from:
      __eth_devices in sim_ether-6ec4b9.o
  "_pcap_freealldevs", referenced from:
      __eth_devices in sim_ether-6ec4b9.o
  "_pcap_freecode", referenced from:
      __eth_open_port in sim_ether-6ec4b9.o
      _eth_filter_hash in sim_ether-6ec4b9.o
      _sim_ether_test in sim_ether-6ec4b9.o
  "_pcap_geterr", referenced from:
      __eth_open_port in sim_ether-6ec4b9.o
      _eth_filter_hash in sim_ether-6ec4b9.o
      __eth_error in sim_ether-6ec4b9.o
      _sim_ether_test in sim_ether-6ec4b9.o
  "_pcap_lib_version", referenced from:
      _eth_version in sim_ether-6ec4b9.o
  "_pcap_lookupnet", referenced from:
      __eth_open_port in sim_ether-6ec4b9.o
      _eth_filter_hash in sim_ether-6ec4b9.o
  "_pcap_open_live", referenced from:
      __eth_devices in sim_ether-6ec4b9.o
      __eth_open_port in sim_ether-6ec4b9.o
  "_pcap_sendpacket", referenced from:
      __eth_write in sim_ether-6ec4b9.o
  "_pcap_setfilter", referenced from:
      __eth_open_port in sim_ether-6ec4b9.o
      _eth_filter_hash in sim_ether-6ec4b9.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [BIN/pdp11] Error 1
```

**Comment by markpizz** [comment]
Thank you for providing the build output you get.  There definitely seems to be a bug in the logic which attempts to use a link library rather than the shared object.  I'll look into that detail.

As you may have noticed, I absolutely am not a Mac user nor an Xcode developer.  

Please give me precise instructions with Xcode open to get to the $ prompt where you entered that make command.

All I needed to do was to open a terminal window, change to the appropriate working directory and enter the make command.

**Comment by markpizz** [comment]
You say:
> If you export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer (substituting the path to your Xcode 12 installation) it will build using the latest tools and SDK from within Xcode.

Precisely what to press where to achieve exactly what you're saying here.

**Comment by markpizz** [comment]
I just updated my macOS test system to the recently released XCode 12.1.

As I have consistently done before, I:
1) opened a terminal window.  
2) change directory to the directory with the code from the github.com/simh/simh master branch.
3) typed 'make pdp11'
4) that command built the pdp11 simulator with native PCAP networking just fine.
5) tested the simulator which worked as it has always has in the past.

Maybe this consistent behavior of the various Xcode versions will change sometime in the future, or maybe the issues you observed with the Beta 12.2 version will ultimately either be changed before it is released or will exist in the released version.  As I said previously, if/when that or a similar problem reveals itself in a released version, we'll address it.

**Comment by eschaton** [comment]
Now that both macOS 11 and Xcode 12.2 are fully released, here’s what you can do in a Terminal window, assuming Xcode 12.2 is at /Applications/Xcode.app:

    $ export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
      # The above makes the stubs in /usr call the tools in /Applications/Xcode.app
      # rather than the tools in /Library/Developer
    $ cd Documents/Projects/github/simh
    $ make pdp11

You’ll get output like I describe above: `pcap` is not recognized being present, despite it being in Xcode’s macOS SDK, and the SIMH build system still tries to build with networking support via `pcap` but doesn’t actually specify to link against it and thus fails with the listed errors.

**Comment by markpizz** [comment]
This problem no longer exists since the above mentioned commit fixed a minor logic problem in the makefile and also added support for the macOS 11, XCode 12 environment.
