### ISSUE TITLE
microvax2000 cannot boot Athena 4.3BSD

### ISSUE THREAD

**Issue by dreamlayers** [simh/simh#942]
- #### Context

I installed Athena 4.3BSD on a real VAXstation 2000, starting the installation by booting from the https://stuff.mit.edu/afs/athena/astaff/project/bootkit/vs2000/61+.floppy RX33 floppy image. Afterwards, I wanted to do the same thing in simh microvax2000. Ultrixboot works, but then I get `Unexpected exception at SCB vector 0x18` instead of kernel output. The same happens if I attach an image of the completed installation from the RD32 drive in the VAXstation, which uses the https://stuff.mit.edu/afs/athena.mit.edu/system/vax_bsd43/srvd/vmunix.VS2000 kernel.

(BTW the microvax2 simulator can successfully boot an Athena 4.3BSD RD53 image taken from a real MicroVAX II and properly run it in multi-user mode. The microvax2 simulator can also boot the RX50 installation floppy at https://stuff.mit.edu/afs/athena/astaff/project/bootkit/vs2/61+.floppy1, producing kernel output, but failing to mount root due to what seems to be an unrelated problem relating to `ra0c: hard error sn0 OFFLINE` output from the kernel. I've created an Athena 4.3BSD installation guide at https://dreamlayers.blogspot.com/2020/10/installing-mit-project-athena-43bsd.html but for now that cannot be done in simh apparently.  I've also been unable to successfully boot installers on vaxstation3100m30 and vaxstation3100m38, though I'm not certain those are impossible or bugs yet.)

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
sim> show version
MicroVAX 2000 (KA410) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 9.3.0
        Simulator Compiled as C arch: x64 (Release Build) on Oct 20 2020 at 11:01:31
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.10, PNG Version 1.6.37, zlib: 1.2.11
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: libpcap version 1.9.1 (with TPACKET_V3)
        OS: Linux vortex 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
        git commit id: c8a8cca7
        git commit time: 2020-10-20T02:47:33-0700
sim> 
```

- #### how you built the simulator or that you're using prebuilt binaries

This is built on Ubuntu 20.04:
```
bgjenero@vortex:~/tmpfs/simh$ git clean -fxd
Removing .git-commit-id
Removing BIN/
Removing VAX/vaxstation.bin
bgjenero@vortex:~/tmpfs/simh$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
bgjenero@vortex:~/tmpfs/simh$ git rev-parse HEAD
c8a8cca7a3c14b4bfbc97160489c137eb713f04f
bgjenero@vortex:~/tmpfs/simh$ make microvax2000
lib paths are: /lib/ /lib/x86_64-linux-gnu/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/ /usr/local/lib/
include paths are:  /usr/lib/gcc/x86_64-linux-gnu/9/include /usr/local/include /usr/include/x86_64-linux-gnu /usr/include
using libm: /usr/lib/x86_64-linux-gnu/libm.so
using librt: /usr/lib/x86_64-linux-gnu/librt.so
using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h
using libpcre: /usr/lib/x86_64-linux-gnu/libpcre.so /usr/include/pcre.h
using semaphore: /usr/include/semaphore.h
using libdl: /usr/lib/x86_64-linux-gnu/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib/x86_64-linux-gnu/libpng.so /usr/include/png.h
using zlib: /usr/lib/x86_64-linux-gnu/libz.so /usr/include/zlib.h
using mman: /usr/include/x86_64-linux-gnu/sys/mman.h
using libSDL2: /usr/include/SDL2/SDL.h
using libpcap: /usr/include/pcap.h
using libvdeplug: /usr/lib/libvdeplug.so /usr/include/libvdeplug.h
***
*** microvax2000 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 9.3.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
*** - Per simulator tests will be run.
***
*** git commit id is c8a8cca7a3c14b4bfbc97160489c137eb713f04f.
*** git commit time is 2020-10-20T02:47:33-0700.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -DSIM_GIT_COMMIT_ID=c8a8cca7a3c14b4bfbc97160489c137eb713f04f -DSIM_GIT_COMMIT_TIME=2020-10-20T02:47:33-0700  -DSIM_COMPILER="GCC Version: 9.3.0" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCRE_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./VAX/vax_cpu.c ./VAX/vax_cpu1.c ./VAX/vax_fpa.c ./VAX/vax_cis.c ./VAX/vax_octa.c ./VAX/vax_cmode.c ./VAX/vax_mmu.c ./VAX/vax_sys.c ./VAX/vax_syscm.c ./VAX/vax_watch.c ./VAX/vax_nar.c ./VAX/vax4xx_stddev.c ./VAX/vax410_sysdev.c ./VAX/vax410_syslist.c ./VAX/vax4xx_dz.c ./VAX/vax4xx_rd.c ./VAX/vax4xx_rz80.c ./VAX/vax_xs.c ./VAX/vax4xx_va.c ./VAX/vax4xx_vc.c ./VAX/vax_lk.c ./VAX/vax_vs.c ./VAX/vax_gpx.c ./sim_scsi.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -DVM_VAX -DVAX_410 -DUSE_INT64 -DUSE_ADDR64 -DUSE_SIM_VIDEO -I ./VAX -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_VDE_NETWORK -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -DHAVE_LIBSDL -DUSE_SIM_VIDEO `/usr/bin/sdl2-config --cflags` `/usr/bin/sdl2-config --libs` -o BIN/microvax2000 -lm -lrt -lpthread -lpcre -ldl -lpng -lz -lvdeplug -Wl,-R,/usr/lib/ -L/usr/lib/ 
BIN/microvax2000 RegisterSanityCheck /home/bgjenero/tmpfs/simh/VAX/tests/vax-diag_test.ini </dev/null 
 Running internal register sanity checks on MicroVAX 2000 (KA410) simulator.
*** Good Registers in MicroVAX 2000 (KA410) simulator.

MicroVAX 2000 (KA410) simulator V4.0-0 Current        git commit id: c8a8cca7
No diagnostics are available for the MicroVAX 2000 (KA410) Simulator

bgjenero@vortex:~/tmpfs/simh$ 
```
- #### the simulator configuration file (or commands) which were used when the problem occurred.

```
bgjenero@vortex:~/tmpfs/simh$ BIN/microvax2000 

MicroVAX 2000 (KA410) simulator V4.0-0 Current        git commit id: c8a8cca7
sim> set rd0 rd32
sim> att rd0 rd32image
RD0: creating new file: rd32image
sim> set rd2 rx33
sim> att rd2 ../bootkit/vs2000/61+.floppy
sim> b
```
(The rd0 rd32 image is irrelevant. I'm only adding it so the configuration is the same as the real VAXstation. The same happens without it.)

- #### the expected behavior and the actual behavior

This is what happens on a real VAXstation 2000 using a serial console cable:
```
 83 BOOT SYS
-DUA2

Ultrixboot (using VMB version 13)

bad partition table
Loading (a)vmunix ...

Sizes:
text = 288532
data = 175380
bss  = 83504
Starting at 0x1af4

Athena 4.3BSD UNIX #6-1-3 (probe@paris:VS2000) Tue Mar 14 23:02:17 EST 1989
real mem  = 4182016 (0x3fd000)
avail mem = 3091456 (0x2f2c00)
using 153 buffers containing 313344 bytes of memory
VAXstation 2000
sdc0 at uba0 csr 0x200c0000 vec 0x1fc, ipl 0x14
Drive 0 is RD32
rd0 at sdc0 slave 0
rd2 at sdc0 slave 2
stc0 at uba0 csr 0x200c0080 vec 0x1f8, ipl 0x14
st0 at stc0 slave 0
ss0 at uba0 csr 0x200a0000 vec 0xc0, ipl 0x14
sm0 at uba0 csr 0x200f0000 vec 0x44, ipl 0x14
se0 at uba0 csr 0x200e0000 vec 0x50, ipl 0x14
se0: hardware address 08:00:2b:06:d0:e1
Reading installation configuration file...
Setting machine dependent variables...
Verifying floppy...
/dev/rd2a: 117 files, 1684 used, 627 free (3 frags, 78 blocks, 0.1% fragmentation)


************************************************************
               DESTROYS
THIS PROCEDURE DESTROYS THE CONTENTS OF THE HARD DISK.
               DESTROYS

IF YOU DO NOT WISH TO CONTINUE, TYPE ^C.

OTHERWISE, PLEASE ENTER THE HOSTNAME OF THIS MACHINE.

When you enter the hostname, please enter the complete
domain name.  If you don't, the domain will default to
'MIT.EDU'.  After you enter the hostname, the temporary
network address will be in use for a minute.  Be sure only
one host is doing this at a time.
************************************************************
What is the hostname of this machine? ^C
#
```
(After pressing control-C there is a shell which works, but only has access to a minimal system on the floppy.)

This is what happens in the simulator after the `b` command:
```
Loading boot code from internal ka410.bin



KA410-A V2.3           

F_..E?..D...C?..B...A...9...8...7...6...5...4_..3_..2_..1_..


??  E  0040  0000.0054
 ?  D  0050  0000.0005
??  C  0080  0000.0004

>>> b dua2


-DUA2

Ultrixboot (using VMB version 13)

bad partition table
Loading (a)vmunix ...

Sizes:
text = 288532
data = 175380
bss  = 83504
Starting at 0x1af4

Unexpected exception at SCB vector 0x18

HALT instruction, PC: 00180533 (HALT)
sim> 
```

If I also use `set cpu model=vaxstation`, the same happens on the graphical display, up to and including `bss  = 83504`. The cursor remains below that line and nothing more is output to the graphical display. There is no `Starting`  or `Unexpected exception`, but the `HALT` line is the same, being output to the terminal window running microvax2000.

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

The RX33 floppy image is available from https://stuff.mit.edu/afs/athena/astaff/project/bootkit/vs2000/61+.floppy, as mentioned earlier.

**Comment by markpizz** [comment]
You comparison is fantastic.  It would be useful to confirm that we're working with the same ROM version on the real VAXStation 2000.  Can you include that detail.

Thanks

**Comment by dreamlayers** [comment]
@markpizz yes, the ROM versions differ. That's one reason why it might be failing but not a bug here. The VAXstation reports V1.2 and the simulator V2.3

 I recently read all the EPROMs in this VAXstation. Could I try the simulator with those?

Here's the beginning of the boot sequence of the VAXstation
```



KA410-A V1.2           

F...E...D...C...B...A...9...8...7...6...5...4_..3_..2_..1...


 ?  E  0040  0000.0045
 ?  D  0050  0000.0005
 ?  C  0080  0000.4001
 ?  6  00A0  0000.4001


 83 BOOT SYS
-DUA0

Ultrixboot (using VMB version 13)

bad partition table
Loading (a)vmunix ...

Sizes:
text = 402280
data = 194264
bss  = 129876
Starting at 0x1af4

Athena 4.3BSD UNIX #7-4-2 (builder@ajax:VS2000) Tue May 26 16:03:40 EDT 1992
real mem  = 4182016 (0x3fd000)
avail mem = 2915328 (0x2c7c00)
using 153 buffers containing 313344 bytes of memory
VAXstation 2000
sdc0 at uba0 csr 0x200c0000 vec 0x1fc, ipl 0x14
Drive 0 is RD32
rd0 at sdc0 slave 0
rd2 at sdc0 slave 2
stc0 at uba0 csr 0x200c0080 vec 0x1f8, ipl 0x14
st0 at stc0 slave 0
```

**Comment by dreamlayers** [comment]
I booted the simulator with my ROM dumps. (For the record, the interleaving of the 4 chips, which can be performed via https://github.com/drojaazu/interleave --width=1 is: by the memory connectors, board corner, board centre, board edge.) I'm impressed that simh works with the unpatched V1.2 ROM, though with more self test errors from the ROM. Athena-4.3BSD fails to boot in the exact same way.
```
bgjenero@pacifica:~/tmpfs$ ../gitapps/simh/BIN/microvax2000 

MicroVAX 2000 (KA410) simulator V4.0-0 Current        git commit id: c8a8cca7
sim> set rd2 rx33
sim> att rd2 61+.floppy
sim> b 
Loading boot code from ka410.bin



KA410-A V1.2           

F_..E?..D...C?..B?..A?..9...8...7...6...5?..4_..3_..2_..1_..


??  E  0040  0000.0054
 ?  D  0050  0000.0005
??  C  0080  0000.0004
??  B  0010  0002.0020
??  A  0020  0000.0132
??  5  0001  0000.0002

>>> b dua2


-DUA2

Ultrixboot (using VMB version 13)

bad partition table
Loading (a)vmunix ...

Sizes:
text = 288532
data = 175380
bss  = 83504
Starting at 0x1af4

Unexpected exception at SCB vector 0x18

HALT instruction, PC: 00180533 (HALT)
sim> 
```

**Comment by markpizz** [comment]
Try the latest code in the master branch.

**Comment by dreamlayers** [comment]
Wow, that was fast, and it works in 95721084713ff3d2670892a86eae9e1b11d4dbd6! Thank you! I can boot and use the installer and I can successfully boot into multi-user off the RD32 image copied from the real VAXstation where I did the installation recently. 

With the floppy boot, it seems the hard drive must be present in order to avoid a `panic: vstodb` after the clock warning line. That could be a bug in the kernel being booted, not in simh. It's not important to me, but I could try unplugging the hard drive to see if I could reproduce that on the real VAXstation if you want.

With the default 16 MB of RAM Athena 4.3BSD acts as if only 2 MB is present. According to https://www.netbsd.org/docs/Hardware/Machines/DEC/vax/microvaxes.html#microvaxes:microvax_2000

> Base 2MB. Space for one extra board of 4M, 8M or 12MB for a maximum of 14MB. Clearpoint produced a 16MB board that also included an updated ROM required for the vax accept the board (parity)

I don't know if the simulator needs that updated ROM or if the kernel doesn't support 16 MB. With `set cpu 14M`, 14 MB is detected properly.

There is this warning from the kernel, but it seems inconsequential.
```
Drive 0 is RD32
WARNING: # of cyls differ from std 820 to formatted 821
USING STANDARD VALUES
```

With `set cpu model=vaxstation` boot fails with `Exception in interrupt or exception, PC: 8000025C (BPT)` right after the screen is cleared when the kernel starts executing. It also happens with my V1.2 ROM. No such problems happen with the default microvax model. I'll leave it up to you whether to close this issue now or take a look at this other problem.
