### ISSUE TITLE
PDP-11/03 - Simulation of Front Panel Switches (Particularly LTC)

### ISSUE THREAD

**Issue by pdr0663** [simh/simh#945]
The great people in The Unix Heritage Society are working on a version of Mini-Unix (cut down Research Unix V6) for the smaller PDP-11 models such as the PDP-11/03. As these machines rarely have a real-time-clock card, the implementation on the /03 uses only the line time clock LTC, enabled or disabled by the front panel switch.

Because a clock interrupt during Mini-Unix boot will crash and corrupt the system, the process for booting Mini-Unix is to disable the LTC from the front panel switch, and re-enable it when prompted by the system.

My question is, does the simulator emulate the front panel LTC switch? How can I disable the LTC, and re-enable when required?

Regards,

Paul

**Comment by archivisth** [comment]
Already there.

SET CPU NOBEVENT

**Comment by markpizz** [comment]
In case you're not an active user and familiar with the simh management interface, Bob's suggestion is to:

1) include the SET CPU NOEVENT in your initial configuration
2) boot the simulator
3) enter the WRU character (CTRL-E by default) to return to the sim> prompt.
4) enter SET CPU BEVENT to enable the clock interrupts
5) enter CONT to allow the simulator to continue execution where it left off.

**Comment by pdr0663** [comment]
Ok thanks got it now. Could not find in the PDP11 doc.

Paul
