### ISSUE TITLE
Why do we need an extra NIC on Linux?

### ISSUE THREAD

**Issue by RaymiiOrg** [simh/simh#950]
Over here: https://github.com/lenticularis39/axpbox/issues/16 we are troubleshooting networking in an Alpha emulator that uses lib pcap and pcap_sendpacket just like simh. 

In the simh docs:

https://github.com/simh/simh/blob/master/0readme_ethernet.txt

> On Windows using the WinPcap interface, the simulated computer can "talk" to
the host computer on the same interface. On other platforms with libpcap
(*nix), the simulated computer can not "talk" to the host computer via the
selected interface, since simulator transmitted packets are not received
by the host's network stack. The workaround for this is to use a second NIC
in the host and connect them both into the same network; then the host and
the simulator can communicate over the physical LAN.

And in the FAQ PDF:

http://simh.trailing-edge.com/pdf/simh_faq.pdf

> 2.11My Linux, OSX or other Unix host can't communicate with the PDP- 11 or VAX over Ethernet; why?

> The network stacks on these systems don’t naturally receive packets which are transmitted with the pcap_sendpacket API... 

I'm not per se looking for a solution, but more of a technical explanation.

I've searched around but couldn't find an explanation of why Linux doesn't handle these specific packets. The manpage for pcap_sendpacket is quite sparse and most things I can find are related to pcap capture files, or c example tutorials.

If anyone can point me in the right way, links or source code, that's fine as well.

And for bonus points, how hard would it be to fix, or make working without an extra interface?

**Comment by Rhialto** [comment]
On Sat 31 Oct 2020 at 10:37:45 -0700, Remy wrote:
> In the simh docs:
> 
> https://github.com/simh/simh/blob/master/0readme_ethernet.txt
> 
> > On Windows using the WinPcap interface, the simulated computer can
> > "talk" to the host computer on the same interface. On other
> > platforms with libpcap (*nix), the simulated computer can not "talk"
> > to the host computer via the selected interface, since simulator
> > transmitted packets are not received by the host's network stack.
> > The workaround for this is to use a second NIC in the host and
> > connect them both into the same network; then the host and the
> > simulator can communicate over the physical LAN.

To expand on that:

a classic way that programs like emulators use to communicate via the
real ethernet is by using BPF: the Berkeley Packet Filter. Originally
that was made to assist with programs like tcpdump: looking at a
selection of frames transmitted to or from a physical interface.

The pcap library is a (much later I think) abstraction over using
/dev/bpf directly (and it potentially supports using other packet
capture methods too, depending on the operating system you run).

I guess at some point somebody added a possiblity to BPF to not only
look at frames, but also to send them. If you send a frame it will go
out on the interface directly. The IP stack on the host will not see it,
so the emulator can't talk to the host.

Hence the suggestion to use an extra, dedicated, interface for the
emulator, where you put two interfaces on the same network. The frame
goes out one interface and comes in the other, and presto, the IP stack
sees it.

These days there are much easier ways with virtual interfaces and
virtual bridges. You can create a "tap" device and bridge it to your
ethernet interface[1]. Sending and receiving from the tap can still be
done with BPF/pcap if the emulator doesn't know any better, but the
frames will be seen by the host's IP stack thanks to the bridge. If the
emulator is tap-aware, it can use it directly, which is simpler in some
ways.

Note [1]: be careful with Linux. Linux has the strange idea that once
you connect your ethernet interface to a bridge, it doesn't use the
interface for communications any more, but the bridge instead. So you
have to overhaul your whole network config, which is stupid and
inconvenient.

**Comment by markpizz** [comment]
> These days there are much easier ways with virtual interfaces and
virtual bridges. You can create a "tap" device and bridge it to your
ethernet interface[1]. Sending and receiving from the tap can still be
done with BPF/pcap if the emulator doesn't know any better, but the
frames will be seen by the host's IP stack thanks to the bridge. If the
emulator is tap-aware, it can use it directly, which is simpler in some
ways.
> 
> Note [1]: be careful with Linux. Linux has the strange idea that once
you connect your ethernet interface to a bridge, it doesn't use the
interface for communications any more, but the bridge instead. So you
have to overhaul your whole network config, which is stupid and
inconvenient.

Whether an additional NIC is "easier" or "solving this problem via virtual host interfaces (via bridges)" is up to the expertise of the user and the various ways configuring the virtual host interfaces that needs to be done on a particular host platform.  

If the host platform happens to be a VM, then adding an additional NIC is both cheap and easy and certainly far less of a headache than possibly struggling with the voodoo required to get the virtual stuff working.  Sometimes the this will also be true for non VM host machines.  Your comment about Linux bridge setup being stupid and inconvenient is the another description of the required voodoo.  :-)

**Comment by RaymiiOrg** [comment]
Thank you both for your explanations!
